### ISSUE TITLE
Free flowing 1-row ticker a la Fantastical

### ISSUE THREAD

**Issue by soundsmitten** [patchthecode/JTAppleCalendar#10]
The iOS app [Fantastical](https://flexibits.com/fantastical-iphone) allows for fluid horizontal scrolling in a one-row calendar view. Rather than paging per week, the days slide by fluidly by any increment. How much modification to JTAppleCalendar do you think this would take?
![2014-04-01 04_38_10 pm](https://cloud.githubusercontent.com/assets/852801/14756985/bc497b2a-08b4-11e6-9756-1c3873d59f6a.gif)

**Comment by patchthecode** [comment]
Acknowledged.
Downloading the app to see it my self. brb.

**Comment by patchthecode** [comment]
Ok scratch that.. haha. Its not a free app >_< 

So let me understand.
You want one row fluid scrolling?

**Comment by patchthecode** [comment]
On closer inspection of the gif image, you want the calendarView to be able to be incremented scrolled by one single day?

**Comment by soundsmitten** [comment]
Wow I was away for a second and you did it! Thank you! I'm a beginner with iOS but I'm looking to dig into this control as I have a couple of calendar-dependent ideas. Definitely the last calendar app I'll try ;)

**Comment by patchthecode** [comment]
Thanks much. I appreciate it. Yea i pushed the update. 
I'm will be updating the cocoa pod in a bit (just doing some last minute tests).
But if you want to preview it before release you can see the code already on github (here).
Looking forward to the ideas.

**Comment by patchthecode** [comment]
Also, this is a new project that has little publicity :< 
If you create a cool calendar, feel free to share an image here to inspire others -> https://github.com/patchthecode/JTAppleCalendar/issues/2
cheers
