### ISSUE TITLE
Start and EndDates incorrect in didScrollToSegment

### ISSUE THREAD

**Issue by CapslockCruiser** [patchthecode/JTAppleCalendar#100]
![screen shot 2016-08-03 at 11 51 37 pm](https://cloud.githubusercontent.com/assets/7290451/17390739/7c4f098c-59d5-11e6-808c-7304c24d27a1.png)

In the screenshot, I am scrolling to February 2016, but as one can see in the debug console, the start and end dates are still January. Once I do scroll, the dates are correct for February, but the month still points to January.

**Comment by patchthecode** [comment]
possible to join me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Here is the weird thing.
All works fine (even with your constraints) on iPhone 6s Simulator. But not on iPhone 6s Plus :/

**Comment by patchthecode** [comment]
ok i see the bug
when we scroll to a new section.
i check to see what the section is
here are the section offset values

(lldb) po sectionSize
▿ 8 elements
  - [0] : 331.33333333333337
  - [1] : 662.66666666666674 { ... }
  - [2] : 994.00000000000011
  - [3] : 1325.3333333333335 { ... }
  - [4] : 1656.666666666667 { ... }
  - [5] : 1988.0000000000005 { ... }
  - [6] : 2319.3333333333339 { ... }
  - [7] : 2650.6666666666674 { ... }

and here is the section offset

331.333333333333

**Comment by patchthecode** [comment]
I have fixed on main branch.
I will release version 4.1.5 soon. You can use the master branch in the mean time till the official release is done. Instructions on how to do this [are here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#8)
