### ISSUE TITLE
CollectionView at second load shows empty

### ISSUE THREAD

**Issue by eliomartinezb** [patchthecode/JTAppleCalendar#1002]
When I load the first time the view it works perfectly.

<img width="320" alt="screen shot 2019-02-21 at 02 33 01" src="https://user-images.githubusercontent.com/4325977/53137479-30f71d80-3583-11e9-9b84-5b71ca628ad6.png">

The problem appears when i go out of the view and then returning to the calendar view, the header with the months and days appears correctly but the cells with the days appears blank until I interact with it. Then it works correctly.

![not working](https://user-images.githubusercontent.com/4325977/53138043-440aed00-3585-11e9-9320-652a83315c0b.gif)

I set up the calendar view in the viewDidLoad 

`self.calendarCollectionView.visibleDates {
            [unowned self] (visibleDates: DateSegmentInfo) in
            self.setUpCalendarView(from: visibleDates)
        }`
`self.calendarCollectionView.scrollToDate(Date())`

I don't know if the error is from the collection view, but the other collectionViews I'm using in the app works correctly. 

Thanks in advance for the help.

**Comment by patchthecode** [comment]
do you have that sample project zipped?
If yes, then can you drag it into this chat box?

**Comment by eliomartinezb** [comment]
Here you go!

Thank you.
[sendCalendart.zip](https://github.com/patchthecode/JTAppleCalendar/files/2887596/sendCalendart.zip)

**Comment by damiandara** [comment]
Any updates on this, I'm experiencing the same issue

**Comment by patchthecode** [comment]
will have an update later today.

**Comment by damiandara** [comment]
Thanks for the quick response @patchthecode

**Comment by damiandara** [comment]
@patchthecode Not sure if that helps but this is only happening on the iPhone X, XR, XS, XSMax

**Comment by eliomartinezb** [comment]
For me it happens on an iPhone 6s if it helps in something

**Comment by damiandara** [comment]
@patchthecode how did you go on Friday ?

**Comment by damiandara** [comment]
It seems like It has something to do with the **scrollToHeaderForDate()** function. If I comment this line of code the calendar view displays correctly @patchthecode

**Comment by patchthecode** [comment]
I am not sure if the issue you are experiencing is the same is the original poster.
I know how to avoid the issue from happening, I am just trying to figure out why it is happening.

**Comment by eliomartinezb** [comment]
> **scrollToHeaderForDate()**

did you mean scrollToDate()? I need to use that to change to it to the current month

**Comment by patchthecode** [comment]
@damiandara can you create a new issue, and upload your sample app just like user @eliomartinezb did?

I am still looking at his issue. But i believe yours may be different.

**Comment by patchthecode** [comment]
@eliomartinezb 
Hey, i have made a fix.
Can you check master branch and see if it was fixed? You can find the [instructions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions).

**Comment by patchthecode** [comment]
@damiandara follow the instructions as well to test master branch to see if your issue was resolved.

**Comment by michaelavila** [comment]
@patchthecode hi there, thanks for the info, any way you could point me to the commit that fixed this issue?

**Comment by patchthecode** [comment]
This will be hard to find.
Are you experiencing this issue on version 7.1.7 ?

**Comment by michaelavila** [comment]
@patchthecode appreciate the quick response, thank you.

**Comment by Willamin** [comment]
@patchthecode Is there any chance you can add a release tag as a patch for 7.1.x that includes 4fd1c04? This would help my project out a ton 😄
