### ISSUE TITLE
show month and year as like below image 

### ISSUE THREAD

**Issue by SwiftAmit** [patchthecode/JTAppleCalendar#1003]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. 7.1.6
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6 YES
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

![screenshot 2019-02-23 at 10 56 54 am](https://user-images.githubusercontent.com/34594282/53282177-20e56680-375a-11e9-8b1c-ee8575eaf037.png)

create a month list like above image and and scroll to selected moth as a selected month

**Comment by patchthecode** [comment]
On which part are you stuck?

**Comment by SwiftAmit** [comment]
i am not able to show month list , it shows 1 to 30 days  i need only show month .

**Comment by patchthecode** [comment]
I do not understand what you mean.
You are unable to show the month list? What do you mean by month list?

also
> it shows 1 to 30 days i need only show month .

Isnt 1-30 days a month?

**Comment by SwiftAmit** [comment]
I have to create scrolling month picker based on month selection I have to show data of that month.

**Comment by patchthecode** [comment]
Hey its good that you are asking questions, but you need to be clear.
I have no clue what you are talking about.

You need to state
1. What you want _clearly_
2. What you have done so far
3. And how what you have done is different from what you want

Without clearly telling me these things, I do not know how to answer your question.

**Comment by patchthecode** [comment]
Here is a setup for a weekview calendar --> https://github.com/patchthecode/JTAppleCalendar/issues/581
Hope it helps

**Comment by patchthecode** [comment]
Let me know if this works for you

**Comment by SwiftAmit** [comment]
no this is for single row which contains date wise row. i need month wise like [DatePicker](https://github.com/noxt/ScrollableDatepicker) in this libaray  there is an option to show only for month column(like jan 18, feb18  ,mar 18..... jan 19,feb19,mar19  etc) not (1 jan18,2 jan18...  1 feb18,2 feb18.... 1 mar18 ...1 jan19,2 jan19...  1 feb19,2 feb19.... 1 mar19 ... etc).

**Comment by patchthecode** [comment]
I think there is misunderstanding.
The only thing that is different with the image that you showed me VS the one that i showed you, was that you image had an extra label for month. Is this correct?
