### ISSUE TITLE
Cell's contentView returns wrong bounds after clicks

### ISSUE THREAD

**Issue by Gray-Wind** [patchthecode/JTAppleCalendar#1004]
The version of library I use is 7.1.6

I'm trying to draw some kind of selection with pattern image.
On start it looks perfect (before user interaction)
<img width="233" alt="screenshot 2019-02-26 at 21 40 02" src="https://user-images.githubusercontent.com/4902794/53441709-10f6ac80-3a10-11e9-98b1-9514b38639a2.png">

But after clicks it looks not so good
<img width="255" alt="screenshot 2019-02-26 at 21 40 28" src="https://user-images.githubusercontent.com/4902794/53441710-10f6ac80-3a10-11e9-92a9-ee1c52676d23.png">
<img width="211" alt="screenshot 2019-02-26 at 21 40 32" src="https://user-images.githubusercontent.com/4902794/53441708-10f6ac80-3a10-11e9-9c9d-dc7d7658f0ed.png">

The reason in cell's ```contentView.bounds.width```. It returns different values before and after clicks.
I [do logs](https://github.com/Gray-Wind/SimpleCalendar/blob/master/SimpleCalendar/CalendarViewController.swift#L89) for sizes used for drawing stripes:
```
5.333333333333333
5.333333333333333
5.357142857142857
5.357142857142857
```

It is visible that they are changing after clicks.

You can find sample project here:
https://github.com/Gray-Wind/SimpleCalendar

**Comment by patchthecode** [comment]
I think your issue is this -> https://github.com/patchthecode/JTAppleCalendar/issues/538

Let me know if it helps

**Comment by Gray-Wind** [comment]
Thank you very much, it helps.
