### ISSUE TITLE
Cant import Calendar to new project

### ISSUE THREAD

**Issue by babakmuir** [patchthecode/JTAppleCalendar#1005]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by babakmuir** [comment]
Hi I have created a new UI for start of my new app
Whats is the best way to import my JTCalendarSettings from my previous project

**Comment by patchthecode** [comment]
This isnt JTCalendar.
This is JTAppleCalendar

**Comment by babakmuir** [comment]
Sorry that's what I meant. still can't figure out how to use it on some other project. I know its wrong to just copy classes but I can't figure it out why Xcode gives me this error
Use of unresolved identifier 'dateFormatter'; did you mean 'DateFormatter'?
while I have it as global var

**Comment by patchthecode** [comment]
This seems to be a code error unrelated to the library.
`dateFormatter` is a variable created by you.
unresolved identifier simply means that `dateFormatter` is not declared in your new pasted class.
Will close this issue.

**Comment by babakmuir** [comment]
I have declare as global
