### ISSUE TITLE
VisibleDates showing outdates even with .generateOutDates is off

### ISSUE THREAD

**Issue by ThasneemH** [patchthecode/JTAppleCalendar#1006]
Hi,

I am using v 7.1.5

I have the following setting: 
```swift
calendar.generateInDates = .forAllMonths
calendar.generateOutDates = .off
```

When I print out the visible dates , it prints out  June 1, 2019 even though it is not shown in the screen. Please see screen shot.   Why does it show it even when we have outdates to off? Thanks for your help.
```swift
  for element in self.calendar.visibleDates().monthDates {
                       print(element.date, terminator: " ")
              }
```
![visibledates](https://user-images.githubusercontent.com/13650795/53585581-1f8db280-3b3b-11e9-840d-9dcd71b346ab.png)

**Comment by ThasneemH** [comment]
I have set the number of rows to 6. It appears that out of the 2 months visible on the screen at any time, if the month at the end of the screen ( May above) only takes up 5 rows, then this issue happens. If it actually takes up 6 rows, then we don't see this issue.

**Comment by Gray-Wind** [comment]
Try to draw border around all day cells. It could be possible that 1st of June is actually shown, at least its top border.

**Comment by ThasneemH** [comment]
But I have set the outdate generation to off , i believe it means outdates are not generated at all.

**Comment by patchthecode** [comment]
The June 1st you are seeing is not an outDate.
You are actually seeing the June 1st, under the June month.

You may think you cant see it. But are you sure that probably 1pixel of the cell is not on the screen (which is too hard for you to see?)

**Comment by ThasneemH** [comment]
Really appreciate your quick response, I will do some more testing and get back to you.

**Comment by ThasneemH** [comment]
On further reflection, I think this is actually ok, since its functionally correct. As @Gray-Wind  commented earlier, if the border was a different color or the cell color was different, it would be clearer. The confusion is because of the white background. Will close this issue.

**Comment by patchthecode** [comment]
yea. thats right.
cool.
