### ISSUE TITLE
Selection bug inside a tab bar controller

### ISSUE THREAD

**Issue by kaizer122** [patchthecode/JTAppleCalendar#1007]
I am using the latest version of JTAppleCalendar .
Problem : i have a calendar embeded in a tab bar controller , selection is very weird : if i tap a day it does not select it unless i tap the tab bar .
steps to recreate : 
1- implement normally 
2- embed in a tab bar controller
3- tap a day 
=> nothing happens 
 
i did NOT test this on a real device .

**Comment by patchthecode** [comment]
better thing to do would be to zip a sample project with the bug and share it here.

**Comment by patchthecode** [comment]
closing until user responds.
