### ISSUE TITLE
Please add programmatic tutorials and documentations.

### ISSUE THREAD

**Issue by lurui1029** [patchthecode/JTAppleCalendar#1008]
### Tutorial
I noticed that you are providing storyboard tutorial videos for this library, which is great. But for those who code programmatically, a tutorial page **only** containing storyboard videos is really a nightmare.

At least, I expect fewest lines of code to run this calendar , such as:
```
let calendar = JTAppleCalendarView(frame: .zero)
calendar.scrollDirection = .horizontal
calendar.calendarDelegate = self
calendar.calendarDataSource = self
calendar.register(MyCell.self, forCellWithReuseIdentifier: "Cell")
self.view.addSubview(calendar)
calendar.translatesAutoresizingMaskIntoConstraints = false
......
```

### Documentation
It's great if there's a complete documentation, if not, users can read public vars and methods  in source code. But what can they do if private vars and methods are public too?
```
    var pathsToReload: Set<IndexPath> = [] //Paths to reload because of prefetched cells
    var anchorDate: Date?
    var lastMonthSize: [AnyHashable:CGFloat] = [:]
```
Should I use them outside or what?

### Version
Latest pod 7.1.7

**Comment by patchthecode** [comment]
Ok. I will do it.

**Comment by andrewfashion** [comment]
Agreed!

**Comment by patchthecode** [comment]
It was just easier to do the vids.
And also there's  a sample project attached to this library.

But yea... text tutorials would be better i guess..

**Comment by andrewfashion** [comment]
No - what we mean is tutorials video or text on how to use this library programmatically without the use of storyboards @patchthecode

**Comment by lurui1029** [comment]
Excellent! @andrewfashion 

It's not about

**Comment by andrewfashion** [comment]
@patchthecode When do you think this is possible? :)

**Comment by lurui1029** [comment]
I wasn't making a clear point...  Here is the thing:

**Personally, before deciding to use this library, I expect a tutorial to demonstrate on these questions as much as possible:**
1. How many ways can I create a calendar view, which parameters are required? which optionals? 
2. What are necessary setups? What are optionals? 
3. How do I customize a cell view?
3. How does this library work with Auto Layout or frame layout? If supports Auto Layout, does it have intrinsic content size or do I have to define both width and height? Further on, do I need to define cell size as well?
4. What's the common manipulations on the calendar view?
5. What's the common concerns and issues?

These questions help me understand how is this library designed and whether it fits me. Storyboard demos are not clearly answering them. (it took me quite a while to figure out some of them, not all of them even now). BTW, youtube videos are not even accessible in some countries.


@patchthecode But you're right, using storyboards or coding programmatically is not the real problem, since they are using the same codebase. **The real problem is the lacking of code documentation**, I mean:
1. private methods and variables should just be private, not public (Apparently they are all public now, which stops me from reading code directly, and there's no tutorials on code too...)
2. Documentation on public methods and variables

With a good documentation, it doesn't actually matter that much how well tutorials are! :)

**Comment by SeanLintern** [comment]
There is an example project provided, literally the source code of the tutorials? Theres hardly any difference from using a storyboard to programatic when using this SDK.

**Comment by patchthecode** [comment]
@SeanLintern i agree.. but they still seem stuck for some reason :/

**Comment by jusher** [comment]
I have tried running the example code, but it does not result in a functioning program.  How do I get it to run, so I can evaluate what it does?  I tried following the examples from the videos, but all I get in the latest version of Xcode and the latest version is a bunch of errors.  It says it cannot find files, and such

**Comment by patchthecode** [comment]
I am in the process of doing text documentation.
I didnt do it originally because this library is just a UICollectionView, and many of the functions are the same. The only different ones are mentioned in videos.

@jusher you can try the example project attached to this project.

**Comment by patchthecode** [comment]
closing this.
text documentation is in progress @ patchthecode.com
