### ISSUE TITLE
How to select a range of Dates from and to

### ISSUE THREAD

**Issue by errabelli09** [patchthecode/JTAppleCalendar#101]
IMPORTANT:

Make sure you have checked the following BEFORE creating this issue:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 4.1.4
2. Did you leave a ★ rating on this repository if you like it? Yea.. I kinda need that. Get's me all pumped to answer questions/bugs.
3. Did you check the Wiki page to see if your question is already answered? --> https://github.com/patchthecode/JTAppleCalendar/wiki

If you've already done the above, then delete this text, and start your issue.

**Comment by patchthecode** [comment]
by using this function -> `public func selectDates(from startDate:NSDate, to endDate:NSDate, triggerSelectionDelegate: Bool = true, keepSelectionIfMultiSelectionAllowed: Bool = false)`

**Comment by errabelli09** [comment]
Thanks patchthecode
