### ISSUE TITLE
One specific date's indate won't get selected 

### ISSUE THREAD

**Issue by rs658726** [patchthecode/JTAppleCalendar#1010]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
Using JTAppleCalendar (7.1.7)

2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
Yes, but the latest version is now 7.1.7.

3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.
First and foremost, thanks for making this library available. It saved me a valuable amount of time. 
Now on to the issue I'm seeing... 
The calendar I'm working on allows multiple selections which are supposed to stick. I have the following parameters set: 

`calendar.allowsMultipleSelection = true
  calendar.isRangeSelectionUsed = true
  calendar.minimumLineSpacing = 0
  calendar.minimumInteritemSpacing = 0`

I've noticed that when February 24th 2019 gets selected (in February), it's won't get selected as an indate in March. I've tried with multiple dates and this is the only date that fails to get selected as an indate. 

Here are my willDisplay, cellForItem, select and deselect functions:

```
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let calendarCell = cell as! CalendarCollectionViewCell
        calendarCell.calendarCellLabel.text = cellState.text
        
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelected(view: cell, cellState: cellState)
        
    }
    
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarDate", for: indexPath) as! CalendarCollectionViewCell
        cell.calendarCellLabel.text = cellState.text
                
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelected(view: cell, cellState: cellState)
        
        return cell
    }

    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        handleDataWhenCellSelected(selectedDate: cellState.date, duration: nil)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        handleDataWhenCellDeselected(deselectedDate: cellState.date)
    }
```

It seems to me that the issue is not related to my code, but I could be wrong.

I've tried tracking the 'cellState.isSelected' variable and it does confirm that when I'm in March, it returns false for the date Feb 24th.

Hope this makes sense.

Any help would be appreciated.
Thanks

**Comment by patchthecode** [comment]
is the date you are trying to select contained within the calendar's startDate and endDate boundary?

**Comment by rs658726** [comment]
Absolutely. 
I'm able to select it within its month, but it won't get selected as an indate in the following month. I have to manually select it.

**Comment by patchthecode** [comment]
can you paste your configureCalendar function please?

**Comment by rs658726** [comment]
Of course, here it is:
`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let parameters = ConfigurationParameters(startDate: startDate, endDate: Date(), numberOfRows: 6, calendar: Calendar.current, generateInDates: .forAllMonths, generateOutDates: .tillEndOfGrid, firstDayOfWeek: .sunday, hasStrictBoundaries: true)
        return parameters
    }`

**Comment by patchthecode** [comment]
Sorry, you need to tell me the `startDate` in order for me to have the correct start boundary.

**Comment by rs658726** [comment]
I've tried with multiple start dates: October 9th 2018, January 9th 2019, or February 19th 2019 (among others).

**Comment by patchthecode** [comment]
ok testing this in a bit

**Comment by rs658726** [comment]
Thanks!

**Comment by rs658726** [comment]
Just curious: were you able to recreate the problem?

**Comment by rs658726** [comment]
Yes, I did -- it's in the first post. I followed the instructions that were in the README doc.

**Comment by patchthecode** [comment]
ok. then give me till tomorrow.
Right now, i was just completing another unrelated bug.

**Comment by patchthecode** [comment]
just zip the project.
and drag it into the chat box of your next message.

**Comment by rs658726** [comment]
[CalendarApp.zip](https://github.com/patchthecode/JTAppleCalendar/files/2955617/CalendarApp.zip)

Here you go. Scroll once to the left (previous month) and select February 24th, 25th, 26th etc.. and then swipe back to March and you'll notice that Feb 24th is the only indate that is not highlighted in red.

Also, please ignore the fact that the month isn't displayed until you actually swipe. I was just trying to quickly reproduce the bug.

**Comment by patchthecode** [comment]
thanks.
Having a look right now.

**Comment by patchthecode** [comment]
wow.. you found a bug in code that was tested very much.
congrats. 🎉
fixed on master branch.
Let me know if it worked for you.

follow the instructions [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions) to test master branch.

**Comment by rs658726** [comment]
Thanks! Glad I was able to help. 
It works now, thanks for being quick to respond.

**Comment by patchthecode** [comment]
cool. 
ok use master for now.
I'll release version 7.1.8 after more testing

**Comment by AndrewZhuCC** [comment]
Could you tell me when will you release version 7.1.8?
