### ISSUE TITLE
select calendar cell with date instead of IndexPath

### ISSUE THREAD

**Issue by SajjadKharrazi** [patchthecode/JTAppleCalendar#1011]
hi
i generated all calendar perfectly. in my calendar some cell are disable.
now i want to do like this:
when user didSelect a cell, i want to enable some disabled cell.

in didSelect delegate i can do with this cell, but i want to select another cell with "date" and change its UI and enable that.

something like `calendar.cellForItem(at: IndexPath)`
`calendar.cellForItem(at: Date)`

i can do this with `calendar.reloadData()`, but it will be very slow

**Comment by patchthecode** [comment]
how about calendarView.reloadDates([dateArray]) ?

**Comment by SajjadKharrazi** [comment]
i will try

**Comment by patchthecode** [comment]
By the, if you ever want `select calendar cell with date` just call the 
```swift
calendarView.selectDate(TheDate)
```
function.

Closing this issue. Let me know how it goes.

**Comment by SajjadKharrazi** [comment]
tnx. it works correctly
