### ISSUE TITLE
Reduce reloadItems lag

### ISSUE THREAD

**Issue by bbo-jay** [patchthecode/JTAppleCalendar#1012]
1. PLEASE STATE THE VERSION NUMBER you are using.
-> 7.1.6

Every time the user scrolls the calendar (vertically), the cells are reloaded using reloadItems. The problem is, it is laggy which is understandable. Question is, is there a way to reduce the lag when reloading?

**Comment by patchthecode** [comment]
...laggy is not understandable 😅

What are you doing in your `cellForItemAt Date`  function?

**Comment by patchthecode** [comment]
closing this issue until more information is provided.
