### ISSUE TITLE
Question on keepSelectionIfMultiSelectionAllowed

### ISSUE THREAD

**Issue by ThasneemH** [patchthecode/JTAppleCalendar#1013]
I am using verison  7.1.5

I am trying to select multipledates. I would like to understand what keepSelectionIfMultiSelectionAllowed means. I could not find more details in the reference. In the comments i UserInteractionFunctions.swift, I found the comments below , could you please elaborate on it.  If this parameter is true, i would assume it selects all the dates, but what does it do otherwise. What does 'toggle' mean in the context of selecting multiple dates?

  // If multiple selection is on. Multiple selection behaves differently to singleselection.
                // It behaves like a toggle. unless keepSelectionIfMultiSelectionAllowed is true.
                // If user wants to force selection if multiselection is enabled, then removed the selected dates from generated dates

Thanks

**Comment by patchthecode** [comment]
S | U | S | S

if (in range selection) there are 4 dates. -> selected, unselected, selected, selected.
Selecting those 4 dates again would give you

U | S | U | U

with force selection set to on, it will give you this

S | S | S | S 

Closing this.
Let me know if anything else.

**Comment by ThasneemH** [comment]
Thanks! that makes it so clear that  I think it should be in the documentation.

**Comment by patchthecode** [comment]
yes, im planning to revamp all the docs.

**Comment by patchthecode** [comment]
documentation added. Will reflect in next release.
