### ISSUE TITLE
Two weeks view

### ISSUE THREAD

**Issue by JakubLares** [patchthecode/JTAppleCalendar#1016]
Hey I have two weeks view calendar and I made to have calendar scrolled for today. It looks like this 
![iPhone_8_-_12_1](https://user-images.githubusercontent.com/7167209/54834686-f4712b80-4cc0-11e9-8344-0a2c2d8370ef.png)
Is there any chance to have bolded today on first line?

**Comment by patchthecode** [comment]
vertical/ horizontal calendar?

**Comment by JakubLares** [comment]
Horizontal, but I can change it to vertical, if it helps. Scrolling is disabled in this mode.

**Comment by patchthecode** [comment]
It is not possible. The location of the dates are set based on the number of days in the actual month.

For a vertical calendar however, you may cheat a bit and have the `scrollMode = .none`.
There you can probably scroll to that date and make it "appear" on the top.

**Comment by JakubLares** [comment]
ou, nice idea ... but this is result 
<img width="357" alt="iPhone_8_-_12_1" src="https://user-images.githubusercontent.com/7167209/54854788-6b73e780-4cf4-11e9-9e8c-4ae7a6789d34.png">
but I really appreciate your effort to help me, thank you

**Comment by patchthecode** [comment]
Yes, sorry about that.
Hope it helps.
Closing this issue now.
Let me know of anything else
