### ISSUE TITLE
Release note

### ISSUE THREAD

**Issue by omerCoosto** [patchthecode/JTAppleCalendar#1018]
Hello!

Thanks for the library it's really great but could you please add some release note each time you do a release. It's really important to know quickly what are the changes.

Thanks!

![Screenshot 2019-03-25 at 14 48 44](https://user-images.githubusercontent.com/34768792/54924714-46a68c80-4f0d-11e9-95bd-18309c68e63e.png)

**Comment by patchthecode** [comment]
This is not enough?
https://github.com/patchthecode/JTAppleCalendar/blob/master/CHANGELOG.md

**Comment by omerCoosto** [comment]
thanks my bad. 
i didn't think of checking files, I use to check this: https://github.com/patchthecode/JTAppleCalendar/releases

You can close this ticket ;)

**Comment by patchthecode** [comment]
cool :)
