### ISSUE TITLE
Highlights cell

### ISSUE THREAD

**Issue by DiegoCaroli** [patchthecode/JTAppleCalendar#1019]
Hi, I need to highlights cells. 
Is there some way for implementing didHighlightItemAtIndexPath and didUnhighlightItemAtIndexPath of the collectionView for highlights cells?

**Comment by patchthecode** [comment]
didSelectDateAt...
didDeselectDateAt

closing this.
let me know if anything else

**Comment by DiegoCaroli** [comment]
Is there something that I can do for highlight the cell at the begging of the tap of the date and not at the end of the tap?

**Comment by patchthecode** [comment]
One question, have you every used the UICollectionView before?

The calendar behaves exactly the same like it (the name of the function are very similar).
So the answer the questions you are asking, if you can answer them for a UICollectionView, then it is the same for this lib.

> Is there something that I can do for highlight the cell at the begging of the tap of the date and not at the end of the tap?

Do you mean the `shouldSelect` delegate functions? If so, then yes. You can use the shouldSelect functions to accomplish this
