### ISSUE TITLE
sectionInset causes week view cell misalignment

### ISSUE THREAD

**Issue by ImEric** [patchthecode/JTAppleCalendar#1020]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
7.1.7
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
Yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I am trying to switch from monthly view to week view. However, this causes all the dates in weekly view mis-aligned with headers if there are sectionInsets.

The configuratinParameters I am using are as follows:

```
        switch (mode) {
        case .daily:
            return ConfigurationParameters(startDate: startDate,
                                           endDate: endDate,
                                           numberOfRows: 6,
                                           generateInDates: .forAllMonths,
                                           generateOutDates: .tillEndOfGrid,
                                           firstDayOfWeek: .sunday,
                                           hasStrictBoundaries: true)
        case .weekly:
            return ConfigurationParameters(startDate: startDate,
                                           endDate: endDate,
                                           numberOfRows: 1,
                                           generateInDates: .forFirstMonthOnly,
                                           generateOutDates: .off,
                                           firstDayOfWeek: .sunday,
                                           hasStrictBoundaries: false)
        }
```

The calendar was set up using:
```
    func setupCalendarView() {
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        calendarView.sectionInset = UIEdgeInsets(top: 0, left: 10, bottom: 5, right: 10)
        calendarView.visibleDates { (visibleDates) in
            self.setupDatesOfCalendar(from: visibleDates)
        }
    }
```

I am also reloading the calendar each time after the switch as required:
```
func switchToStatsView(mode: statsViewMode) {
        switch (mode) {
        case .daily:
            statsViewCurrentMode = .daily
            calendarViewHeightConstraint.constant = 260
            self.view.layoutIfNeeded()
            calendarView.reloadData()
            setupDefaultSelectDates(mode: .daily)
            break;
        case .weekly:
            calendarViewHeightConstraint.constant = 47.5
            statsViewCurrentMode = .weekly
            self.view.layoutIfNeeded()
            calendarView.reloadData()
            setupDefaultSelectDates(mode: .weekly)
            break;
```

Here are screenshots of calendar in month view and in weekly view:

<img src="https://user-images.githubusercontent.com/4133769/55053312-05030800-5019-11e9-99eb-c9b75bbf0d2d.png" width="400">

<img src="https://user-images.githubusercontent.com/4133769/55053324-0f250680-5019-11e9-9250-e0bf2f13894f.png" width="400">

If I comment out sectionInsets, dates in weekly view is aligned perfectly

<img src="https://user-images.githubusercontent.com/4133769/55053398-472c4980-5019-11e9-90cc-575f76f309bd.png" width="400">

Please let me if I am doing anything wrong. Thank you very much!

**Comment by patchthecode** [comment]
Does master branch also have this issue?
Master branch contains a number of fixes for section inset.

You can test it by following this -> https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by ImEric** [comment]
Thank you for your quick response.
Sadly no, the issue still persists after I updated pod, cleaned and rebuild my project.

**Comment by patchthecode** [comment]
ok, its hard to determine what the issue is without a sample app replicating the issue.
Its difficult because these types of errors are visual. Therefore a sample app with the issue would be helpful.

**Comment by ImEric** [comment]
I think I am experiencing the same issue as #1032

**Comment by patchthecode** [comment]
i just made a push to master branch

**Comment by patchthecode** [comment]
let me know if issue is resolved.

**Comment by ImEric** [comment]
Thanks, it's resolved after updating to the most recent pod:)

**Comment by patchthecode** [comment]
@ImEric 
OK, i am still making fixes to it, and i am still testing it.
It should be more well tested by the weekend.

But you can use it for now.
Any new issues found then let me know.
