### ISSUE TITLE
Error installing the framework using carthage

### ISSUE THREAD

**Issue by nourahassan** [patchthecode/JTAppleCalendar#1021]
I am trying to install the calendar using carthage but doing carthage update gives next error:

```
*** Building scheme "JTAppleCalendar tvOS" in JTAppleCalendar.xcworkspace
Build Failed
...
This usually indicates that project itself failed to compile. 

```

This is for version `7.1.7`

**Comment by patchthecode** [comment]
what version of 
1. xcode
2. swift

do you have?

**Comment by Unknoob** [comment]
Same error here on XCode 10.1

In my case the logs indicate a Swift version error:

`/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UserInteractionFunctions.swift:162:80: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
        super.register(viewClass, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: identifier)
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                               UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UserInteractionFunctions.swift:168:74: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
        super.register(nib, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: identifier)
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                         UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UserInteractionFunctions.swift:173:90: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
        guard let headerView = dequeueReusableSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader,
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                                         UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarView.swift:135:117: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
            guard let attributes = calendarViewLayout.layoutAttributesForSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, at: indexPath) else { return retval }
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                    UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarView.swift:171:47: error: type 'UIScrollView.DecelerationRate' (aka 'CGFloat') has no member 'fast'; did you mean 'hash'?
        case .stopAtEachCalendarFrame: return UIScrollView.DecelerationRate.fast.rawValue
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~
                                                                            hash
CoreGraphics.CGFloat:3:17: note: 'hash' declared here
    public func hash(into hasher: inout Hasher)
                ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarView.swift:172:54: error: type 'UIScrollView.DecelerationRate' (aka 'CGFloat') has no member 'fast'; did you mean 'hash'?
        case .stopAtEach, .stopAtEachSection: return UIScrollView.DecelerationRate.fast.rawValue
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~
                                                                                   hash
CoreGraphics.CGFloat:3:17: note: 'hash' declared here
    public func hash(into hasher: inout Hasher)
                ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarView.swift:173:75: error: type 'UIScrollView.DecelerationRate' (aka 'CGFloat') has no member 'normal'; did you mean 'isNormal'?
        case .nonStopToSection, .nonStopToCell, .nonStopTo, .none: return UIScrollView.DecelerationRate.normal.rawValue
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~
                                                                                                        isNormal
CoreGraphics.CGFloat:40:16: note: 'isNormal' declared here
    public var isNormal: Bool { get }
               ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarView.swift:180:32: error: argument labels '(rawValue:)' do not match any available overloads
            decelerationRate = UIScrollView.DecelerationRate(rawValue: decelerationRateMatchingScrollingMode)
                               ^                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarView.swift:180:32: note: overloads for 'UIScrollView.DecelerationRate' exist with these partially matching parameter lists: (Float), (Double), (CGFloat), (UInt8), (Int8), (UInt16), (Int16), (UInt32), (Int32), (UInt64), (Int64), (UInt), (Int), (exactly: T), (bitPattern: UInt), (floatLiteral: CGFloat.NativeType), (integerLiteral: Int), (from: Decoder), (NSNumber), (truncating: NSNumber), (exactly: NSNumber)
            decelerationRate = UIScrollView.DecelerationRate(rawValue: decelerationRateMatchingScrollingMode)
                               ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarLayout.swift:374:100: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
                        let attrib = layoutAttributesForSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, at: IndexPath(item: data.0, section: data.1))
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                   UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/JTAppleCalendarLayout.swift:672:86: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
            return attributes.filter { $0.representedElementKind != UICollectionView.elementKindSectionHeader }
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                                     UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/InternalActionFunctions.swift:67:29: error: type 'UIScrollViewDecelerationRate' (aka 'CGFloat') has no member 'fast'; did you mean 'hash'?
        decelerationRate = .fast
                            ^~~~
                            hash
CoreGraphics.CGFloat:3:17: note: 'hash' declared here
    public func hash(into hasher: inout Hasher)
                ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/InternalActionFunctions.swift:99:113: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
        guard let attributes = calendarViewLayout.layoutAttributesForSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, at: indexPath) else { return }
                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UIScrollViewDelegates.swift:79:33: error: type 'UIScrollViewDecelerationRate' (aka 'CGFloat') has no member 'fast'; did you mean 'hash'?
            decelerationRate = .fast
                                ^~~~
                                hash
CoreGraphics.CGFloat:3:17: note: 'hash' declared here
    public func hash(into hasher: inout Hasher)
                ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UIScrollViewDelegates.swift:203:115: error: 'elementKindSectionHeader' has been renamed to 'UICollectionElementKindSectionHeader'
                        let attrib = calendarLayout.layoutAttributesForSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, at: attribPath) { // JT101 this was changed
                                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                  UICollectionElementKindSectionHeader
UIKit.UICollectionView:4:22: note: 'elementKindSectionHeader' was introduced in Swift 4.2
    public class let elementKindSectionHeader: String
                     ^
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UIScrollViewDelegates.swift:231:37: error: argument labels '(rawValue:)' do not match any available overloads
            self.decelerationRate = UIScrollView.DecelerationRate(rawValue: self.decelerationRateMatchingScrollingMode)
                                    ^                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/{redacted}/Carthage/Checkouts/JTAppleCalendar/Sources/UIScrollViewDelegates.swift:231:37: note: overloads for 'UIScrollView.DecelerationRate' exist with these partially matching parameter lists: (Float), (Double), (CGFloat), (UInt8), (Int8), (UInt16), (Int16), (UInt32), (Int32), (UInt64), (Int64), (UInt), (Int), (exactly: T), (bitPattern: UInt), (floatLiteral: CGFloat.NativeType), (integerLiteral: Int), (from: Decoder), (NSNumber), (truncating: NSNumber), (exactly: NSNumber)
            self.decelerationRate = UIScrollView.DecelerationRate(rawValue: self.decelerationRateMatchingScrollingMode)
                                    ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
`

**Comment by nourahassan** [comment]
> what version of
> 
> 1. xcode
> 2. swift
> 
> do you have?

I had Xcode 10.1, Swift 4.2. Now it also fails after the upgrade to Xcode 10.2, Swift 5.

**Comment by pcmanik** [comment]
Do you guys really target tvOS?
If you target just iOS use `carthage update --platform ios` and it works.

**Comment by danl3v** [comment]
I am not able to build with Xcode 10.2 in carthage either. I get an error saying that JTAppleCell cannot be found

**Comment by patchthecode** [comment]
closing this issue.
Updated to swift 5 and fixed TVOS build error.
Let me know if it is still failing.

**Comment by nourahassan** [comment]
@patchthecode 
You didn't make a release. Latest release still 7.1.7?

**Comment by patchthecode** [comment]
Didnt make the release yet.
I was trying to push another fix for another issue before i released.
Can you just use master branch for now?

**Comment by nourahassan** [comment]
The iOS platform fails on master.

```
/usr/bin/xcrun xcodebuild -workspace Carthage/Checkouts/JTAppleCalendar/JTAppleCalendar.xcworkspace -scheme JTAppleCalendar\ iOS -configuration Release -derivedDataPath DerivedData/10.2_10E125/JTAppleCalendar/47b35f67cff94f5bc717096f644920dcc2111f28 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /JTAppleCalendar SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Carthage/Checkouts/JTAppleCalendar)

This usually indicates that project itself failed to compile
```

**Comment by patchthecode** [comment]
sorry. I forgot to push.
Is it working now?

**Comment by nourahassan** [comment]
Yes! It works now both platform builds. Thanks!

**Comment by patchthecode** [comment]
cool.

**Comment by nourahassan** [comment]
When this will be released?
