### ISSUE TITLE
Make JTAppleCell.isSelected available back

### ISSUE THREAD

**Issue by agordeev** [patchthecode/JTAppleCalendar#1023]
This is a follow-up issue of this: https://github.com/patchthecode/JTAppleCalendar/issues/923

I use isSelected.didSet to update cell's colors. Not sure that would be achievable using cellState.isSelected.

For now I had to delete unavailable block manually. Note if there will be a warning I'll have to delete it manually as well :) As we tend to keep 0 warnings through the project.

**Comment by patchthecode** [comment]
closing this issue.
Will be merged to master branch soon.
