### ISSUE TITLE
Enable APPLICATION_EXTENSION_API_ONLY in iOS target.

### ISSUE THREAD

**Issue by paulkite** [patchthecode/JTAppleCalendar#1024]
Would it be possible to set the APPLICATION_EXTENSION_API_ONLY build configuration setting to YES in the iOS target so it can be embedded / used in iOS extensions, like iMessage?

**Comment by patchthecode** [comment]
Done on master branch.

**Comment by patchthecode** [comment]
I do not know much about App extensions.
Hope it works well with this change and that nothing breaks.

**Comment by paulkite** [comment]
Really it just seems to forbid use of UIApplication.shared

**Comment by patchthecode** [comment]
Ok. you lost me..
Can you explain it like i am 5?

**Comment by paulkite** [comment]
Haha. So iOS extensions aren't allowed access to UIApplication.shared. This setting ensures that the framework doesn't and isn't able to call it is all.

**Comment by patchthecode** [comment]
ok.
So if i make the change you requested, then it will be fixed?

**Comment by paulkite** [comment]
Yup.

**Comment by patchthecode** [comment]
alright then. well the change is made. I will push the change to master branch soon
