### ISSUE TITLE
Multiple Date select problem

### ISSUE THREAD

**Issue by danielmekis** [patchthecode/JTAppleCalendar#1026]
Hey,

I have a problem with multiple date selection. In first I build a Date array, then I set selection... Sometimes its appear sometimes its not. If I scrolling and scroll back then it appears, but its really random.
Do anyone has any idea how can I solve this problem?

My goal is to show check ins, and its necessary to select the right dates.

**Comment by patchthecode** [comment]
did you 
1. implement the `willselect` delegate function call?
2. reset your cells in your `cellForItemAtDate` delegate? (cells are reused. This is a UICollectionView)

**Comment by patchthecode** [comment]
closing issue.
assuming resolved.

I left the awaiting user response flag open
