### ISSUE TITLE
12 months display in a tableView, swift

### ISSUE THREAD

**Issue by taktikal17** [patchthecode/JTAppleCalendar#103]
Hi, 

I used to use your code with the horizontal scrolling between the months, it was perfect! Thanks!

But this time, I would like to to have the 12 months display in a tableView or a scrollView, one month under the other.
<img width="100" alt="screenshot at aug 05 23-12-08" src="https://cloud.githubusercontent.com/assets/8819239/17455108/cd736838-5b62-11e6-977e-a5f0aef2e7fc.png">

Do you know how I can do it ? 

Thank you a lot!

**Comment by patchthecode** [comment]
```swift
calendarView.direction = .Vertical
calendarView.itemSize = someSmallValue // try 30 maybe ?
```

I do not think you can get a 12 month display. It will be too small.

**Comment by taktikal17** [comment]
It is just perfect!

Thank you again!!

**Comment by patchthecode** [comment]
cool. closing this issue.

**Comment by taktikal17** [comment]
Just one more question :

Is it possible to hide or to enable the selection of dates from the previous or following month and  to not change their states as selected ?

For instance if I select September 1st, I would like that in the August View, the September 1st stays white and unselectable. 

![simulator screen shot aug 7 2016 8 02 24 pm](https://cloud.githubusercontent.com/assets/8819239/17468213/69d475fa-5cda-11e6-9a77-2f9db463fffc.png)


Thank you!

**Comment by patchthecode** [comment]
Hey one thing. Could you please create this under a new issue?
We have to separate the issues into different ones. I cant track them properly if different issues are all merged into one :)  thanks!.

also, [join me here](https://gitter.im/patchthecode/JTAppleCalendar) when you are done.

**Comment by taktikal17** [comment]
No problem! Thank you a lot!
