### ISSUE TITLE
Single selection calendar - how to deselect a date correctly?

### ISSUE THREAD

**Issue by bivant** [patchthecode/JTAppleCalendar#1030]
Version: JTAppleCalendar (7.1.7)
allowsMultipleSelection = false
workflow:
1. select a date in the calendar (user input)
2. deselect it in code using: 
`calendarView.deselect(dates: [date])` by a button (control outside of the calendarView)
3. select a date in the calendar (user input)

What do I expect:
get deselected delegate call through
`func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState)` once at step 2.

What do I get:
get deselected delegate call 2 times: at step 2 and step 3 (I believe because collection view remembers that the item was selected).

Am I using the wrong method for deselection?

**Comment by bivant** [comment]
I am able to solve the issue by adding the line in the UserInteractionFunctions.swift:
<pre>
    public func deselect(dates: [Date], triggerSelectionDelegate: Bool = true) {
        if allowsMultipleSelection {
            selectDates(dates, triggerSelectionDelegate: triggerSelectionDelegate)
        } else {
            let paths = pathsFromDates(dates)
            guard !paths.isEmpty else { return }
            if paths.count > 1 { assert(false, "WARNING: you are trying to deselect multiple dates with allowsMultipleSelection == false. Only the first date will be deselected.")}
            <b>deselectItem(at: paths[0], animated: true)</b>
            collectionView(self, didDeselectItemAt: paths[0])
        }
    }
</pre>
But maybe I am doing it wrong from the start and should use another method?

**Comment by patchthecode** [comment]
checking this out

**Comment by patchthecode** [comment]
I am not able to reproduce this.
Can you try to replicate it on the sample project i have attached to guthub?
Or can you provide a sample app which demonstrates this?

**Comment by bivant** [comment]
Hello @patchthecode 
(This one?)[https://github.com/patchthecode/JTAppleCalendarDemo]

**Comment by bivant** [comment]
You can see unbalanced "deselect" (2 records) in the log if press the "Delete the date" button above the calendar and select a date afterward.
[JTAppleCalendarDemo.zip](https://github.com/patchthecode/JTAppleCalendar/files/3047530/JTAppleCalendarDemo.zip)

**Comment by patchthecode** [comment]
checking this out now

**Comment by patchthecode** [comment]
This is not happening with the file you gave me :/
Let me know know when you will be online.
Chat is faster -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by bivant** [comment]
Hello @patchthecode . I would like to deal with this now if you available

**Comment by bivant** [comment]
[Video](https://we.tl/t-1Kcpfwod74) with the issue (check the textview at the bottom of the screen)
![selection](https://user-images.githubusercontent.com/6350992/55660899-46fa2e00-5811-11e9-9267-eb7350dbf0c2.gif)
I have updated the pod in the sample project(was 7.1.5, now 7.1.7) and added a textview to see the output.
[JTAppleCalendarDemo.zip](https://github.com/patchthecode/JTAppleCalendar/files/3049916/JTAppleCalendarDemo.zip)

**Comment by patchthecode** [comment]
your issue is recreated.
Checking this now.

**Comment by patchthecode** [comment]
...bug

**Comment by patchthecode** [comment]
Fixed on master branch.
Can you check and let me know if it was fixed on master branch for your project?
Follow instructions [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#how-do-i-test-my-project-with-your-latest-code-to-see-if-a-bug-is-fixed-there) to test master branch. Let me know

**Comment by bivant** [comment]
Thank you.
I can not test the fix from master branch right now because of the "old" XCode version (10.1, Swift 4.2).
Cherry pick of the commit over the 7.1.7 tag fixes the issue though.

**Comment by patchthecode** [comment]
cool.

**Comment by ekchhuon** [comment]
I am having this issue too. May you help me please

**Comment by bivant** [comment]
Hello @ekchhuon 
Use [the master branch](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions) or apply [the fix](https://github.com/patchthecode/JTAppleCalendar/commit/62501f95b5b5a693ab4caa967736d1ee120d0b5d) manually. Current tag (7.1.7) does not include the solution of the issue.
By the way, you can check the [example](https://github.com/patchthecode/JTAppleCalendar/files/3049916/JTAppleCalendarDemo.zip) for the deselection code

**Comment by patchthecode** [comment]
Exactly what @bivant said is correct.
If you need help let us know. I can help you.
