### ISSUE TITLE
Switch covers known cases, but 'UICollectionView.ScrollDirection' may have additional unknown values, possibly added in future versions

### ISSUE THREAD

**Issue by aynakora** [patchthecode/JTAppleCalendar#1031]
After Converting it to Swift 5, got this error message
'Switch covers known cases, but 'UICollectionView.ScrollDirection' may have additional unknown values, possibly added in future versions'

I'm currently using latest version of JTAppleCalendar.

**Comment by aynakora** [comment]
![Image20190405125142](https://user-images.githubusercontent.com/21150022/55604329-c3edbf00-57a1-11e9-821c-e6aa6aa64780.jpg)

**Comment by patchthecode** [comment]
Yea no worries. Im still making commits there.
Saw that one.
I till be resolved.

Will close this once i fix and push it.

**Comment by patchthecode** [comment]
done.
