### ISSUE TITLE
StrictBoundary = false together with section inset causes misaligned sections.

### ISSUE THREAD

**Issue by gsmumbo** [patchthecode/JTAppleCalendar#1032]
I'm using the most current version of JTAppleCalendar (added the pod earlier today). Here's my DataSource (dates are the same ones used in the example video):

```
dateFormatter.dateFormat = "yyyy MM dd"
dateFormatter.timeZone = Calendar.current.timeZone
dateFormatter.locale = Calendar.current.locale
        
let startDate = dateFormatter.date(from: "2017 01 01")!
let endDate = dateFormatter.date(from: "2017 12 31")!
        
let parameters = ConfigurationParameters(startDate: startDate,
                                         endDate: endDate,
                                         numberOfRows: 1,
                                         generateInDates: .forFirstMonthOnly,
                                          generateOutDates: .off,
                                          hasStrictBoundaries: false)
        
return parameters
```

I also have these in my viewDidLoad:

```
journalCalendar.minimumLineSpacing = 0
journalCalendar.minimumInteritemSpacing = 0
```

When I run the app the first section goes all the way from the 1st to the 14th:

![IMG_0089](https://user-images.githubusercontent.com/3220181/55676706-69d72180-58a7-11e9-8b7b-7fb0442e1c7e.jpeg)

![IMG_0090](https://user-images.githubusercontent.com/3220181/55676707-6e033f00-58a7-11e9-8b2c-6d4cde88d4b8.jpeg)

Every week after that has the correct number of items in it (7):

![IMG_0091](https://user-images.githubusercontent.com/3220181/55676710-7bb8c480-58a7-11e9-898e-69ea5cbe7112.jpeg)

Because the first section has 14 items in it the alignment for the rest of the rows gets thrown off. 

Here are my Storyboard settings:
![Screen Shot 2019-04-06 at 8 12 07 PM](https://user-images.githubusercontent.com/3220181/55676726-54aec280-58a8-11e9-8aed-04e9bc359c87.png)
![Screen Shot 2019-04-06 at 8 12 28 PM](https://user-images.githubusercontent.com/3220181/55676727-57111c80-58a8-11e9-94ad-15e18e6a21f0.png)

Any idea what could be causing this?

**Comment by patchthecode** [comment]
checking it out

**Comment by patchthecode** [comment]
can you set strict boundary = true? This should resolve your issue.

However, what you have showed is interesting.
I never tried the combination of section inset + strict boundary = false   before.
Checking this out now.

**Comment by patchthecode** [comment]
technically, 
strictboundary = false 
+ section inset = false 
should not be allowed.

If the strict boundary is set to false, there will no more be boundaries between sections which will cause the sections to join, BUT, the sectionInset is causing the sections to separate.
Obviously they cant be joined and separate at the same time. Therefore I should disallow this.

What effect were you trying to accomplish?

**Comment by patchthecode** [comment]
ignore that last comment.
I think i may have an error there. Investigating now.

**Comment by patchthecode** [comment]
I guess the combination with these 2 settings were not well tested.
Congrats on the bug find.

Investigating now.

**Comment by patchthecode** [comment]
Can you test master branch and see if this issue is resolved for you?
Follow instructions [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#how-do-i-test-my-project-with-your-latest-code-to-see-if-a-bug-is-fixed-there)

**Comment by patchthecode** [comment]
Horizontal fixed.
Working on vertical

**Comment by patchthecode** [comment]
closing issue.
