### ISSUE TITLE
xcode 10.2 (swift 5) update

### ISSUE THREAD

**Issue by lsmilek1** [patchthecode/JTAppleCalendar#1035]
Hello,

I updated my xcode to the latest version and then also pods, for what I cleaned the build folder also. But now I am unfortunately not able to build it again. Error pops while compile JTAppleCalendar.

I am using version 7.1.7. and the error is:
'semanticContentAttribute' is only available on iOS 9.0 or newer

Anyone else observes the same?

Thanks for help!
![Screenshot 2019-04-13 at 20 15 04](https://user-images.githubusercontent.com/41491201/56083695-e1b5c680-5e28-11e9-963e-4be9188369e4.png)

**Comment by patchthecode** [comment]
You probably have your pod building on something lower.
Click the pod project and make sure that all targets are built with at least iOS 9.0

<img width="1008" alt="Screen Shot 2019-04-13 at 2 07 07 PM" src="https://user-images.githubusercontent.com/2439146/56085299-8ae2c980-5df5-11e9-9b1d-0945bed8c6ff.png">

closing issue let me know if it was resolved.

**Comment by lsmilek1** [comment]
resolved, thank you for your prompt answer!
