### ISSUE TITLE
"not conforming to protocol"

### ISSUE THREAD

**Issue by alynaj36** [patchthecode/JTAppleCalendar#1036]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. XCODE 10.1, Swift: 4, JT: 7.1.7

I followed your first few tutorials (the Cocoapods and the from scratch tutorial). Because I was receiving the "doesn't conform to protocol" error, as many people were, I read through your #553 many times. I think I'm having trouble understanding what exactly to implement. I was going to try to follow your instructions to implement the willDisplayCell() function, but I'm not sure what to put in it exactly? Also, Xcode suggests to implement the calendar(willDisplay cell) function (which I also wasn't sure how to implement). Any help would be greatly appreciated!

I sent you an email about this instead, with my zip file attached.

**Comment by patchthecode** [comment]
There is an example project attached to this github project.
Does this help?

Unfortunately, i cannot update the videos.

**Comment by alynaj36** [comment]
I think this is just a bit confusing because the example is in pieces, so I assume you'll be addressing it in your documentation. 

I was looking at the example, however I was confused because I wasn't sure what to do with the CellView, WhiteSectionHeader and PinkSectionHeader since you use it in the ViewController file. In order to use those to mimic your example, I firstly created them as separate files but then I'm not quite sure what to do after that? 

Also, for the CodePinkSectionHeaderView (and White), did you mean to name the classes PinkSectionHeaderView since that's what you reference in the ViewController? Additionally, it gives me an error that they have no member "title".

**Comment by patchthecode** [comment]
Are you online now? If so - https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Text docs are not yet finished, but does this help --> http://patchthecode.com/calendar-from-scratch/

**Comment by patchthecode** [comment]
Doesnt conform to protocol errors should be resolved if you click on the red button in XCode and let it put in the missing function.

In regards to what to put in the willDisplay function (issue #553), it is saying that the willDisplay function should have the exact same code as the *cellForItemAtDate* function.

The only difference is the **dequeue** line of code as shown in #553

**Comment by alynaj36** [comment]
I apologize, it was 1 am so I fell asleep haha. But I'm going to follow your calendar-from-scratch! It definitely seems to clarify things. I'll let you know if there are anymore questions. Will you still be checking your email by any chance?

**Comment by patchthecode** [comment]
Yes i still check my emails.
But i check it weekly unless i am aware you sent an email.

If an issue is crated here, i check these every day.

**Comment by patchthecode** [comment]
I responded to your email.
And fixed the issue.
Follow the suggestion in the email to learn more about how to build it.
