### ISSUE TITLE
Any Updates for Swift 5?

### ISSUE THREAD

**Issue by mervekeles** [patchthecode/JTAppleCalendar#1037]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

You can now clear this text and ask your question.

**Comment by patchthecode** [comment]
Swift 5 is currently on master branch awaiting to be released.

I've made quite a number of fixes, so i am just testing things out before i release. Making sure i do not break any thing.

You can try out swift 5 version by point to master branch in your podfile. [Instructions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#how-do-i-test-my-project-with-your-latest-code-to-see-if-a-bug-is-fixed-there).

**Comment by patchthecode** [comment]
closing issue.
assuming resolved.

**Comment by amberkatyal** [comment]
I have updated to Swift 5 and followed the above instructions. And renamed everything based on suggestions and will do testing.
I wonder will swift 5 ABI will do have any benefits on this.

**Comment by SwiftyFivve** [comment]
Can we expect a Swift 5 official release anytime soon?

**Comment by patchthecode** [comment]
@SwiftyFivve is 7.1.7 not able to be built in your project?

**Comment by SwiftyFivve** [comment]
7.1.7 is being built, but I'm still getting a Swift Conversion warning

**Comment by patchthecode** [comment]
ok. I see.
it is one line of code that needs to be converted.
I have released version 8.0.0 which is swift 5 convertable.
however, there are breaking changes.

I cannot release a new version right now because of a cocoapod bug.
I'll see what i can do over his weekend.

**Comment by SwiftyFivve** [comment]
Sounds great! Thank you so much

**Comment by sunilmaurya04** [comment]
I'm using pod 'JTAppleCalendar', '~> 8.0.3'
Still it is showing 'Conversion to Swift 5 is available'. How can I upgrade it?

**Comment by patchthecode** [comment]
I would do an XCode clean.
Probably your project cache folders are dirty.

8.0.3 has been out for almost a year. And people have been updating without issue.
The people who have reported something similar to what you just posted is usually related to dirty cache.

**Comment by sunilmaurya04** [comment]
Yes, I cleaned the cache. It is working fine. Thank you so much, you saved my time.
