### ISSUE TITLE
Hide certain month days

### ISSUE THREAD

**Issue by kuchmiyalex** [patchthecode/JTAppleCalendar#1039]
Using version 7.1.7, vertical scrolling with month headers.

Thanks for your hard work, really like your project and ability to customize dozes of things. 
Can you help me to figure out if that's possible to dynamically hide/collapse days for certain months while keeping header visible?
For example dates in April are not available for selection and I want to leave only month header for April with subtitle "Not available for selection"?
Do you think it's something that can be done without forking the project? Can you give any clues how to achieve that?
Thanks a lot

**Comment by patchthecode** [comment]
like this? 
https://github.com/patchthecode/WLAppleCalendar

**Comment by kuchmiyalex** [comment]
hm, not sure, here's my example what i'm trying to build, thanks for reply

<img width="377" alt="Screen Shot 2019-04-17 at 17 16 55" src="https://user-images.githubusercontent.com/772816/56295076-dd452280-6134-11e9-897a-b87acbfb0029.png">

**Comment by patchthecode** [comment]
oh.. hmmm... let em think on that

**Comment by patchthecode** [comment]
Its not built for this, so i'm trying to think of a way.

**Comment by patchthecode** [comment]
Sorry, but i do not think this is possible.
I cannot even begin to think how i can make this generic.

**Comment by patchthecode** [comment]
closing this issue
