### ISSUE TITLE
Hide and enable dates

### ISSUE THREAD

**Issue by taktikal17** [patchthecode/JTAppleCalendar#104]
Just one more question :

Is it possible to hide or to enable the selection of dates from the previous or following month and  to not change their states as selected ?

For instance if I select September 1st, I would like that in the August View, the September 1st stays white and unselectable. 

![simulator screen shot aug 7 2016 8 02 24 pm](https://cloud.githubusercontent.com/assets/8819239/17468213/69d475fa-5cda-11e6-9a77-2f9db463fffc.png)

Thank you!

**Comment by patchthecode** [comment]
How are you currently hiding the other dates?  In your image above, I see dates are hidden.

**Comment by taktikal17** [comment]
I change the color for white. But the dates are still selectable.

**Comment by patchthecode** [comment]
Ok, one thing, when you create a new issue, 
did you see some text giving you some instructions? I do not think you read it. 😞  

It should have given you a link with the very thing you are asking for. Setting the color to while is not really the way to make the cell invisible.

**Comment by patchthecode** [comment]
If you still can't find it in the instructions, let me know. I'll give you the link here.

**Comment by taktikal17** [comment]
I am so sorry about that! I went straightforward to open a new issue, and I didnt go through the doc.. I found everything! Thanks again! I am going to delete this issue right after this message.

Take care! Thanks.

**Comment by patchthecode** [comment]
welcome! It's all good.
If you have another issue, we can open a new one. Have a good one. 👍
