### ISSUE TITLE
The first scroll is not smooth

### ISSUE THREAD

**Issue by fawzirifai** [patchthecode/JTAppleCalendar#1042]
I followed your tutorial to create a calendar from scratch, the problem is that the first scroll after presenting the calendar is always laggy and not smooth, after that the scroll become smooth. I'm using the latest version.

**Comment by patchthecode** [comment]
1. Scrolling by finger? or programmatically?
2. How large is your date range?

**Comment by fawzirifai** [comment]
By finger, and the range is 3 years. I'm testing it on a real iPhone.

**Comment by patchthecode** [comment]
Then it should never lag.

What do you have in the following functions?
1. ViewDidLoad?
2. CellForItemAtDate
3. WillDisplayCell

You probably have something in there. Let me know.

**Comment by patchthecode** [comment]
Also, do you have something loading from the internet before loading calendar?

**Comment by patchthecode** [comment]
closing this issue.
assuming resolved.

added `awaiting user input` flag
