### ISSUE TITLE
[Feature request]: Automatic firstDayOfWeek based on user's calendar

### ISSUE THREAD

**Issue by AllioNicholas** [patchthecode/JTAppleCalendar#1043]
The `ConfigurationParameters` of the calendar allow to set a `firstDayOfWeek` value to start the calendar from. This has to be defined by the developer and currently is not flexible as users might have different calendar configurations based on their Locale.
It would be nice to have an option for that, or an helper method mapping [Calendar.current.firstWeekday](https://developer.apple.com/documentation/foundation/nscalendar/1408310-firstweekday) to `DaysOfWeek` enum (which is the type of the parameter to be passed in the configuration)

Something like:
```
func mapDafaultCalendarToDaysOfWeek() -> DaysOfWeek {
    switch Calendar.current.firstWeekday {
    case 1: return .sunday
    case 2: return .monday
    case 3: return .tuesday
    case 4: return .wednesday
    case 5: return .thursday
    case 6: return .friday
    case 7: return .saturday
    default: return .monday
}
```

**Comment by patchthecode** [comment]
Done.

Can you test and let me know if it works for you?
Use the [instruction here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#common-questions-can-now-be-found-on-this-link) to test the latest master branch.

**Comment by patchthecode** [comment]
So now you do not have to set the first day of week.
If it is not set, then it will automatically select it from the Calendar.current.

The "mapping code" is now simply this
```swift
self.firstDayOfWeek = DaysOfWeek(rawValue: calendar.firstWeekday) ?? .sunday
```
