### ISSUE TITLE
Prevent scrolling through 2 month with 1 scroll

### ISSUE THREAD

**Issue by fawzirifai** [patchthecode/JTAppleCalendar#1046]
How to prevent scrolling through 2 month with 1 scroll?

![IMG_0944](https://user-images.githubusercontent.com/35241593/57052022-2fd22300-6c8d-11e9-8be0-3705ba24a4b5.gif)

**Comment by patchthecode** [comment]
This library is a UICollectionView. What you are looking for is paged scrolling.

Therefore, just make the UICollectionView to be paged on storyboard.

**Comment by patchthecode** [comment]
let me know if you need anything else.
