### ISSUE TITLE
Month title not updates quickly

### ISSUE THREAD

**Issue by fawzirifai** [patchthecode/JTAppleCalendar#1047]
When I scroll quickly over months the month title not update. How can I fix this please?

![RPReplay_Final1556758221](https://user-images.githubusercontent.com/35241593/57052154-33b27500-6c8e-11e9-83ac-7c9566c0418e.gif)

**Comment by patchthecode** [comment]
This library is a UICollectionView.
Therefore use what every UICollectionView function there is to accomplish this.

For example, try putting the month updating code in this function:
```swift
func calendar(_ calendar: JTAppleCalendarView, willScrollToDateSegmentWith visibleDates: DateSegmentInfo)
```

**Comment by patchthecode** [comment]
let me know if this helped

**Comment by fawzirifai** [comment]
Great, that was very helpful, but I found 2 bugs in willScrollToDateSegmentWith that don't present in didScrollToDateSegmentWith, the first is willScrollToDateSegmentWith not called when I scroll to date in viewDidLoad, second July month appears as June, so when I scroll from June to July the month title stay June, although willScrollToDateSegmentWith is called when scrolling.

**Comment by fawzirifai** [comment]
![RPReplay_Final1556771000](https://user-images.githubusercontent.com/35241593/57056535-d0cfd680-6cab-11e9-8040-e51e3211ef9f.gif)

**Comment by patchthecode** [comment]
I saw the issue u mentioned.
I did not call willScroll for the scrollToDateFunction
looking into why i missed that.

**Comment by patchthecode** [comment]
in the mean time, add the header update code both in the `willScroll` and the `didScroll` delegate functions. I think of a fix for this

**Comment by patchthecode** [comment]
In regards to the wrong month being displayed. I am not experiencing this.
Maybe a sample application demonstrating this will help.

**Comment by fawzirifai** [comment]
Thank you! I will check it in a few hours and get back to you.

**Comment by fawzirifai** [comment]
Okay I create a sample project and June-July wrong month issue is still there, please check it here:
https://github.com/fawzirifai/TestingJTAppleCalendar/

**Comment by patchthecode** [comment]
if you are online, texting is faster here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
I am not seeing the problem you spoke of.

**Comment by fawzirifai** [comment]
Maybe it is timezone related issue?

**Comment by patchthecode** [comment]
Yes it is -->  If you are on the east side of the world, then you will see this.
This happens with every calendar library on github.

Here is a detailed explanation of the issue --> https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
In order to fix it, do this:

In your `configureCalendar` delegate function, please provide a calendar configured with the time zone settings that you want 

```swift
let parameters = ConfigurationParameters(startDate: Calendar.current.date(byAdding: .month, value: -4, to: Date())!,
                                                 endDate: Calendar.current.date(byAdding: .month, value: +4, to: Date())!,
                                                 calendar: Calendar())
```

**Comment by fawzirifai** [comment]
Let me try.

**Comment by patchthecode** [comment]
As for the first issue --> calling the `willScroll` delegate when a developer calls the `scrollToDate` function. I am still thinking about if I should do this or not.

**Comment by fawzirifai** [comment]
It is not a big problem, I can configure the label when the calendar loaded. Regarding to the second issue, why it is happens only with willScroll? the issue is not present in didScroll.

**Comment by patchthecode** [comment]
> Regarding to the second issue

2nd issue being the wrong month is shown?

**Comment by fawzirifai** [comment]
Yes

**Comment by patchthecode** [comment]
mind going here?

https://gitter.im/patchthecode/JTAppleCalendar

Chatting here is like watching 2 garbage trucks collide in slow motion.

**Comment by fawzirifai** [comment]
Okay.

**Comment by patchthecode** [comment]
issue resolved with master branch code.
