### ISSUE TITLE
Carthage build fails with swift 3 error (not allowed)

### ISSUE THREAD

**Issue by billpatterson** [patchthecode/JTAppleCalendar#1048]
github "patchthecode/JTAppleCalendar" "7.1.7"

Xcode 10.2.1

`error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'JTAppleCalendar tvOS')`

Detail:

```
xcodebuild -workspace /Users/bill/Documents/work/clients/Antics/github-repo/octapharma/iOS-app/igcares/Carthage/Checkouts/JTAppleCalendar/JTAppleCalendar.xcworkspace -scheme JTAppleCalendar\ tvOS -configuration Release -derivedDataPath /Users/bill/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/JTAppleCalendar/7.1.7 -sdk appletvos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/pt/jl9w0f5n1z9__xst3s243hhw0000gn/T/JTAppleCalendar SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/bill/Documents/work/clients/Antics/github-repo/octapharma/iOS-app/igcares/Carthage/Checkouts/JTAppleCalendar)User defaults from command line:
    IDEArchivePathOverride = /var/folders/pt/jl9w0f5n1z9__xst3s243hhw0000gn/T/JTAppleCalendar
    IDEDerivedDataPathOverride = /Users/bill/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/JTAppleCalendar/7.1.7

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos12.2
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'JTAppleCalendar tvOS')
```

**Comment by patchthecode** [comment]
can you point to master branch?

**Comment by patchthecode** [comment]
assuming resolved.

**Comment by pieperu** [comment]
I'm also experiencing this error:

```SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'JTAppleCalendar tvOS'```

'''github "patchthecode/JTAppleCalendar"'''

**Comment by patchthecode** [comment]
1. What version of swift are you using?
2. What version of XCode are you using?
3. What do you have in your `Podfile` ?

**Comment by pieperu** [comment]
1. Swift version 4.2
2. XCode 10.2.1
3. I use carthage - github "patchthecode/JTAppleCalendar"

**Comment by pieperu** [comment]
I cannot find a work around for this. I think this ticket should be re-opened. I'm happy to raise a new issue if you prefer.

**Comment by pieperu** [comment]
@patchthecode my apologies for wasting your time, after changing my carthage file to this:

`github "patchthecode/JTAppleCalendar" "master"`

The problem went away - I'm new to swift and xcode and assumed leaving out the version as i had before would:

`github "patchthecode/JTAppleCalendar"`

that it would default to master - but it doesn't.

Problem solved for me.

Thanks

**Comment by patchthecode** [comment]
cool.

**Comment by waterskier2007** [comment]
@patchthecode I am seeing the same error message when using "master"

**Comment by patchthecode** [comment]
can you set you carthage to this commit Hash -> 1d9e3d0b4d8fbd0649da8cb6c9f1de2374c51cde

That hash is version 7.1.7 
From version 8.0 and upwards i am removing support for Carthage and Cocoapods, because SwiftPackageManager comes built directly into XCode. All you gotta do is paste in this repository's link and thats it.

let me know your thoughts.

**Comment by waterskier2007** [comment]
@patchthecode that worked great! I would love to use SPM, but I am updating a legacy project, and we are not at that point yet. Thanks for the quick response.

**Comment by patchthecode** [comment]
Understood. Well 7.1.7 should do good for you then
version 8 is mainly minor bug fixes (some rare ones) and support for a yearView calendar.
