### ISSUE TITLE
Help to implement Year View

### ISSUE THREAD

**Issue by RomuloVHSYS** [patchthecode/JTAppleCalendar#1049]
Hi! Before start this issue, i know that your library don't support year view, and i found some issues that you tell that, in that issues you tell that the main problem is on loading many collections for months inside a collection for year, and that results on great number of cells and all it's subviews in memory.

Thinking on that main problem i'm trying to implement my own Year view. My idea to workaround that problem with many views in memory, is:

1. Load a collection view for month;
2. Convert that collection view into a UIImage;
3. Keep that image on a Collection of UIImages and dealocate the source collection view;
4. Show only six months on the year collectionView(like the Apple calendar does)
5. Store 18 month images on that collection
6. Dynamically load the sequencial months repeating the above steps in background 

I can do 5 steps, but i'm stuck trying to dynamically load the next views. My idea is to implement something like a infinite scroll, iterating on the collection of 18 month images.

That collection work like a treadmill, if i insert a new value, and the collection if full(18 elements), the collection automatically drop the element on the opposite side.

Testing that logic appear to don't delay the screen on the first load, but i'm stuck on dynamically load the next months while scrolling the collection. Maybe you can help me with you knowledge working with collection view and dates, and i help you to implement a native Year View to your library.

Se the code snippets on comments Above. And fell free to ask what the code does and suggest better ways to do that.

**Comment by RomuloVHSYS** [comment]
### Image conversion

```
extension UIView {
    
    func asImage() -> UIImage {
        if #available(iOS 10.0, *) {
            let renderer = UIGraphicsImageRenderer(bounds: bounds)
            return renderer.image { rendererContext in
                layer.render(in: rendererContext.cgContext)
            }
        } else {
            if self.frame.size != CGSize(width: 0, height: 0){
                UIGraphicsBeginImageContext(self.frame.size)
                self.layer.render(in:UIGraphicsGetCurrentContext()!)
                let image = UIGraphicsGetImageFromCurrentImageContext()
                UIGraphicsEndImageContext()
                return UIImage(cgImage: image!.cgImage!)
            }
        }
        return UIImage()
    }
}
```

**Comment by RomuloVHSYS** [comment]
### Utilities and the custom Collection

import Foundation
import JTAppleCalendar

class JTAppleCalendarHelper{
    
    struct DateRange {
        var startDay : Date
        
        var endDay : Date
    }
    
    enum DateRangeType{
        case ofMonth, ofYear
    }
    
    var dateRange : DateRange = DateRange(startDay: Date(), endDay:  Date())
    
    func getRange(_ type: DateRangeType, for date: Date) -> DateRange{
        switch type {
        case .ofMonth:
            let componentDay = DateComponents(day: 1)
            let calendar = Calendar.current
            let zeroHourDate = calendar.date(bySettingHour: 0, minute: 0, second: 0, of: date)!
            let firstDayOfMonthDate = calendar.nextDate(after: zeroHourDate, matching: componentDay, matchingPolicy: .previousTimePreservingSmallerComponents, direction: .backward)!
            
            let lastHourDate = calendar.date(bySettingHour: 23, minute: 59, second: 59, of: firstDayOfMonthDate)!
            let firsDayNextMonth = calendar.date(byAdding: .month, value: 1, to: lastHourDate)!
            let lastDayOfMonthDate = calendar.date(byAdding: .day, value: -1, to: firsDayNextMonth)!
            
            return DateRange(startDay: firstDayOfMonthDate, endDay: lastDayOfMonthDate)
        case .ofYear:
            
            let calendar = Calendar.current
            let currentYear = calendar.component(.year, from: date)
            let firstDayOfTheYear = DateFormatter.getDateFromString(string: "01/01/\(currentYear)")!
            let lastDayOfTheYear = DateFormatter.getDateFromString(string: "31/12/\(currentYear)")!
            
            return DateRange(startDay: firstDayOfTheYear, endDay: lastDayOfTheYear)
        }
    }
    
    func calendarViewFor(_ dateRange: DateRange, withFrame frame: CGRect) -> JTAppleCalendarView{
        self.dateRange = dateRange
        
        let calendarView = JTAppleCalendarView(frame: frame)
        calendarView.ibCalendarDelegate = self
        calendarView.ibCalendarDataSource = self
        calendarView.backgroundColor = .clear
        calendarView.register(ScheduleDateCollectionViewCell.self, forCellWithReuseIdentifier: "dateCell")
        
        
        calendarView.reloadData()
        
        return calendarView
    }
    
}
extension JTAppleCalendarHelper : JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource{
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let configuration = ConfigurationParameters(startDate: self.dateRange.startDay,
                                                    endDate: self.dateRange.endDay,
                                                    numberOfRows: 6,
                                                    calendar: Calendar.current,
                                                    generateInDates: .forAllMonths,
                                                    generateOutDates: .off,
                                                    firstDayOfWeek: .sunday,
                                                    hasStrictBoundaries: true)
        return configuration
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! ScheduleDateCollectionViewCell
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        configureCell(view: cell, cellState: cellState)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: collectionView.frame.size.width/7, height: collectionView.frame.size.width/7)
    }
    
    func configureCell(view: JTAppleCell?, cellState: CellState) {
        guard let cell = view as? ScheduleDateCollectionViewCell  else { return }
        cell.addBorders(edges: [.top], color: .lightGray)
        cell.dateLabel.text = cellState.text
        handleCellTextColor(cell: cell, cellState: cellState)
    }
    
    func handleCellTextColor(cell: ScheduleDateCollectionViewCell, cellState: CellState) {
        if cellState.dateBelongsTo == .thisMonth {
            cell.isHidden = false
        } else {
            cell.isHidden = true
        }
    }
    
    
}


struct MonthImagesCollection: Collection {
    typealias DictionaryType = [Int : UIImage]

    // Underlying, private storage, that is the same type of dictionary
    // that we previously was using at the call site
    private var monthImages = DictionaryType()

    // Enable our collection to be initialized with a dictionary
    init(monthImages: DictionaryType) {
        self.monthImages = monthImages
    }

    // Required nested types, that tell Swift what our collection contains
    typealias Index = DictionaryType.Index
    typealias Element = DictionaryType.Element

    // The upper and lower bounds of the collection, used in iterations
    var startIndex: Index { return monthImages.startIndex }
    var endIndex: Index { return monthImages.endIndex }

    // Required subscript, based on a dictionary index
    subscript(indexDate: Index) -> MonthImagesCollection.Element {
        get { return monthImages[indexDate] }
    }

    // Method that returns the next index when iterating
    func index(after i: Index) -> Index {
        return monthImages.index(after: i)
    }

    var maxRange : Int = 18

    subscript(indexDate: Int) -> UIImage{
        get { return monthImages[indexDate] ?? UIImage() }
        set {
            monthImages[indexDate] = newValue
            if monthImages.count > maxRange{
                let isAddedOnEnd = indexDate > monthImages.keys.max()!
                if isAddedOnEnd{
                    monthImages.removeValue(forKey: monthImages.keys.min()!)
                }else{
                    monthImages.removeValue(forKey: monthImages.keys.max()!)
                }
            }
        }
    }
}
extension MonthImagesCollection: ExpressibleByDictionaryLiteral {
    typealias Key = Int
    typealias Value = UIImage
    
    var keys: Dictionary<Int, UIImage>.Keys {return (monthImages.keys)}
    var values: Dictionary<Int, UIImage>.Values {return monthImages.values}
    
    init(dictionaryLiteral elements: (Int, UIImage)...) {
        for (indexDate, monthImage) in elements {
            monthImages[indexDate] = monthImage
        }
    }
}

**Comment by RomuloVHSYS** [comment]
### The Year view controller

Here i'm reusing the same cell that i create(on storyboard) to the month view, that i'm opening by clicking on a cell on the year view.

```
import UIKit
import JTAppleCalendar
import Hero

class YearScheduleViewController: UIViewController, UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    
    @IBOutlet weak var collectionView: UICollectionView!
    
    var monthImages : MonthImagesCollection = [:]
    var selectedCell : UICollectionViewCell?
    
    enum Direction {
        case up, down, none
    }
    var scrollDirection : Direction = .none
    
    var queue = OperationQueue()
    var monthIndexesInLoading : [Int] = []
    
    override func viewDidLoad() {
        super.viewDidLoad()
        queue.maxConcurrentOperationCount = 6
        
        let calendarHelper = JTAppleCalendarHelper()
        
        let calendar = Calendar.current
        let currentDate = Date()
        monthImages = [:]
        for i in -6..<12{
            let date = (i == 0) ? currentDate : calendar.date(byAdding: .month, value: i, to: currentDate)!
            let dateRange = calendarHelper.getRange(.ofMonth, for: date)
            var calendarView : JTAppleCalendarView? = calendarHelper.calendarViewFor(dateRange, withFrame: CGRect(origin: CGPoint(x: 0, y: 0), size: CGSize(width: collectionView.frame.size.width/3, height: collectionView.frame.size.height/4)))
            let calendarImage = calendarView!.asImage()
            calendarView = nil
            let indexDate = encode(indexDate: date)
            monthImages[indexDate] = calendarImage
        }

        // Do any additional setup after loading the view.
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        Hero.shared.defaultAnimation = .none
//        if #available(iOS 10.0, *) {
//            collectionView.prefetchDataSource = self
//        } else {
//            // Fallback on earlier versions
//        }
        
        
    }
    
    func dinamicallyLoadCollectionViewData(){
        let calendarHelper = JTAppleCalendarHelper()
        let monthIndexesLoaded = Array(monthImages.keys)
        let allIndexesMonth = monthIndexesLoaded + monthIndexesInLoading
        
        var nextDateToLoad = Date()
        if self.scrollDirection == .up{
            let lastVisibleIndex = allIndexesMonth.min()!
            let lastVisibleDateToLoad = decode(indexDate: lastVisibleIndex)
            
            nextDateToLoad = Calendar.current.date(byAdding: .month, value: -1, to: lastVisibleDateToLoad)!
        }else{
            let lastVisibleIndex = allIndexesMonth.max()!
            let lastVisibleDateToLoad = decode(indexDate: lastVisibleIndex)
            
            nextDateToLoad = Calendar.current.date(byAdding: .month, value: 1, to: lastVisibleDateToLoad)!
        }
        monthIndexesInLoading.append(encode(indexDate: nextDateToLoad))
        let imageCalendarLoader = BlockOperation {
            let dateRange = calendarHelper.getRange(.ofMonth, for: nextDateToLoad)
            var calendarView : JTAppleCalendarView?
            let group = DispatchGroup()
            group.enter()
            DispatchQueue.main.async {
                calendarView = calendarHelper.calendarViewFor(dateRange, withFrame: CGRect(origin: CGPoint(x: 0, y: 0), size: CGSize(width: self.collectionView.frame.size.width/3, height: self.collectionView.frame.size.height/4)))
                group.leave()
            }
            group.notify(queue: .main) {
                let calendarImage = calendarView!.asImage()
                calendarView = nil
                let indexDate = self.encode(indexDate: dateRange.endDay)
                
                self.monthImages[indexDate] = calendarImage
                self.monthIndexesInLoading = self.monthIndexesInLoading.filter({$0 != indexDate})
            }
        }
        
        self.queue.addOperation(imageCalendarLoader)
    }
    
    func decode(indexDate number: Int) -> Date{//.reduce(0, combine: {$0*10 + $1})
        let digits = String(number).compactMap{ Int(String($0)) }
        let year = Array(digits[0..<4]).reduce(0) { return $0*10 + $1 }
        let month = Array(digits[4..<digits.count]).reduce(0) { return $0*10 + $1 }
        return DateFormatter.getDateFromString(string: "15/\(month)/\(year)")!
    }
    
    func encode(indexDate date: Date) -> Int{
        let calendar = Calendar.current
        let yearComponent = calendar.component(.year, from: date)
        let monthComponent = calendar.component(.month, from: date)
        let monthString = (monthComponent < 10) ? "0\(monthComponent)" : "\(monthComponent)"
        return Int("\(yearComponent)"+monthString)!
    }
    
    func nextIndexDate(forScrollDirection direction: Direction) -> Int{
        var nextIndexDate = 0
        let calendar = Calendar.current
        switch direction {
        case .up:
            let firstIndexDate = self.monthImages.keys.min()!
            let date = self.decode(indexDate: firstIndexDate)
            let nextDate = calendar.date(byAdding: .month, value: 5, to: date)!
            
            let nextYear = calendar.component(.year, from: nextDate)
            let nextMonth = calendar.component(.month, from: nextDate)
            
            nextIndexDate = Int("\(nextYear)\(nextMonth)")!
        case .down:
            let lastIndexDate = self.monthImages.keys.max()!
            let date = self.decode(indexDate: lastIndexDate)
            let nextDate = calendar.date(byAdding: .month, value: -5, to: date)!
            
            let nextYear = calendar.component(.year, from: nextDate)
            let nextMonth = calendar.component(.month, from: nextDate)
            
            nextIndexDate = Int("\(nextYear)\(nextMonth)")!
        case .none:
            return 0
        }
        
        return nextIndexDate
    }
    
    //MARK: - Collection view delegate
    
//    func collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) {
//        if indexPaths.contains(<#T##element: IndexPath##IndexPath#>)
//    }
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 18
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "monthCell", for: indexPath)
        var nextIndexDate = 0
        if scrollDirection == .none{
            var indexes = Array(monthImages.keys)
            indexes.sort()
            nextIndexDate = indexes[indexPath.row]
        }else{
            nextIndexDate = self.nextIndexDate(forScrollDirection: self.scrollDirection)
        }

        (cell.viewWithTag(1) as! UIImageView).image = monthImages[nextIndexDate]
        
        self.dinamicallyLoadCollectionViewData()
        
        return cell
    }
    
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let size = CGSize(width: collectionView.frame.size.width/2, height: collectionView.frame.size.height/3)
        return size
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        self.selectedCell?.hero.id = ""
        
        if let cell = collectionView.cellForItem(at: indexPath){
            self.selectedCell = cell
        }
        self.selectedCell?.hero.id = "MonthSchedule"
        self.performSegue(withIdentifier: "calendarScheduleView", sender: self)
    }
    
    func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
        scrollDirection = targetContentOffset.pointee.y > scrollView.contentOffset.y ? .down : .up
    }

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */

}
```

**Comment by RomuloVHSYS** [comment]
### The date cell

```
import JTAppleCalendar
import UIKit

class ScheduleDateCollectionViewCell: JTAppleCell {
    @IBOutlet var dateLabel: UILabel!
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        if let _ = dateLabel{
            print("created By Xib")
        }else{
            dateLabel = UILabel(frame: self.contentView.bounds)
            dateLabel.font = UIFont(name: "OpenSans-Regular", size: 12)
            self.contentView.addSubview(dateLabel)
        }
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}
```

**Comment by patchthecode** [comment]
will think on this after work

**Comment by patchthecode** [comment]
I know you have posted the code here.
But is there some sample project on github, or zip file that i can take a look at?
Its easier for me to make suggestions (if needed) if i have some sample app to play around with.

**Comment by RomuloVHSYS** [comment]
I can't share the entire project because it's my company property, but i can share a zip file containing all the .swift files that i'm using for implement this and a storyboard that is apart of the main.storyboard. It suits?

**Comment by patchthecode** [comment]
Yes that works.

**Comment by patchthecode** [comment]
Btw, chatting here is slow.
I am online now here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing this issue.
YearView cannot be implemented like this without taking a performance hit.

I have decided to code Year view natively so no more hacks are required.
Tracking it here https://github.com/patchthecode/JTAppleCalendar/issues/349
