### ISSUE TITLE
Not generating  accurate Calender 

### ISSUE THREAD

**Issue by techmehra** [patchthecode/JTAppleCalendar#105]
Your library is high customizable 
But is giving such Ui 
![simulator screen shot 08-aug-2016 6 01 27 pm](https://cloud.githubusercontent.com/assets/18284379/17504098/53e190ae-5e13-11e6-9bcf-385d677e4d1d.png)

**Comment by techmehra** [comment]
It occurs if you do like this :- 
func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar) {
		let firstDate = formatter.dateFromString("2016 01 01")
        print(NSDate())
		let secondDate = formatter.dateFromString("2099 01 01")
		let aCalendar = NSCalendar.currentCalendar() // Properly configure your calendar to your time zone here
		return (startDate: firstDate!, endDate: secondDate!, numberOfRows: 6, calendar: aCalendar)
	}

**Comment by patchthecode** [comment]
can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
What you are seeing there is boundary dates.
You are seeing the end of one month, and the start of another.
