### ISSUE TITLE
Start at specific date

### ISSUE THREAD

**Issue by robertcrabtree** [patchthecode/JTAppleCalendar#1050]
1. PLEASE STATE THE VERSION NUMBER you are using.

7.1.7

2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.7

Yes

3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I'd like for the calendar to start at a specific date. Right now I have a work around in place where in the viewDidLoad method I have this:

```
    override func viewDidLoad() {
        super.viewDidLoad()
        calendar.scrollingMode = .stopAtEachCalendarFrame
        calendar.scrollToDate(startingMonth)
    }

```

And then in the calendar delegate implementation I have this:

```
    func calendar(_ calendar: JTAppleCalendarView,
                  didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        if let firstDay = visibleDates.monthDates.first?.date {
            calendar.selectDates([firstDay])
        }
    }

```

The problem with this approach is that you actually see the calendar scroll to the `startMonth` before it selects the first day of the month. I don't want the user to see any scrolling when the calendar first appears.

**Comment by patchthecode** [comment]
that `scrollToDate` function has many parameters (including the one to stop animation).
CMD + click into that function to see all the possibilities.

closing this.
Let me know if youre still stuck.

**Comment by patchthecode** [comment]
scrollToDate(date, animateScroll: false

**Comment by robertcrabtree** [comment]
Thank you!

**Comment by patchthecode** [comment]
BTW, in future, most of the functions you use in this library has hidden parameters. Hope this helps. Have a good oen.
