### ISSUE TITLE
 Calendar with specific months only

### ISSUE THREAD

**Issue by twojPan** [patchthecode/JTAppleCalendar#1051]
Hi
I need to create a calendar with specific months only. I have a list of events and need to display only that months which contain at least one event. Can you help me with that ?

**Comment by patchthecode** [comment]
When you say specific months, you mean like

Jan, March, December       while skipping out the other months?

**Comment by twojPan** [comment]
Yes, some of the months need to be skipped

**Comment by patchthecode** [comment]
Sorry, but this does not come out of the box.
Can it be done? Yes. But not out of the box.

**Comment by twojPan** [comment]
So there is some hope for me. Are you be able to prepare some solution ? I really need this

**Comment by patchthecode** [comment]
i meant, its possible as in you'd have to change the code of the library.
If you do not know how to this though, you'd have to wait until i get the time (which unfortunately may not be soon).

**Comment by twojPan** [comment]
I will try to do this by myself in that case. In my opinion, the issue should stay open until you had time to implement some example - maybe someone else will need that in future.
Thanks again for a quick response. Keep up the good work

**Comment by patchthecode** [comment]
Upon further, I think i'll close this issue.
After reviewing again, a requirement such as this with require a major rewrite of everything. This requirement basically need non-continuous months. Every calculation/code in this entire lib is geared toward continuous months. I think what is requested calls for a new library.

let me know your thoughts.
