### ISSUE TITLE
Any documentation or tutorials on range selection?

### ISSUE THREAD

**Issue by patpatchpatrick** [patchthecode/JTAppleCalendar#1052]
Hello,

Is there any documentation out there currently on how to implement range selection functionality as part of the calendar?  I'm having trouble figuring it out from the example range selection view controller.  
The old tutorial also seems to be a dead link: https://patchthecode.github.io/RangeSelection/

My current code can be seen here:
https://github.com/patpatchpatrick/Eventr/blob/redesign/Eventr/Views/Controllers/ViewControllerCalendarExtension.swift

I guess the piece I'm missing is, how does the calendar determine if a cell should be .Left, .Right, .Middle or .Full and how does it determine if a cell should be selected?  Do I need to add my own logic in the "didSelectDate" method or is it automatic?

**Comment by patchthecode** [comment]
yea sorry about that.
I till be up in a bit.

**Comment by patpatchpatrick** [comment]
Ok thanks.  No problem, I will wait for the tutorial.

**Comment by patchthecode** [comment]
SingleTap Range selection added.

https://patchthecode.com/ranged-selection

Adding the other types now.

**Comment by patpatchpatrick** [comment]
thank you!

**Comment by dimpy-iroid** [comment]
https://patchthecode.com/ranged-selection

This is not working!!
Can anyone please provide me with a tutorial on how to achieve range selection exactly like this library, "https://github.com/simla-tech/Fastis," in this JTAppleCalendar?

**Comment by patchthecode** [comment]
@dimpy-iroid -> https://github.com/patchthecode/JTAppleCalendar/blob/master/docs/range-selection-styles/Range%20selection%20styles.md

I couldnt afford to have the document site anymore because google cancled my ads which gave me about $10 a month to keep the site up. So a controbuter helped me and did it on the link above.
