### ISSUE TITLE
wrong dates returned in single row calendar while scrolling week wise 

### ISSUE THREAD

**Issue by parveenkumar5** [patchthecode/JTAppleCalendar#1056]
Please validate, there is some issue with this calendar while using in single row. sometimes while scrolling the calendar it gives wrong dates in return. Video attached for your reference. 
if you see in video at 0:08, dates given was 2 sept while it should have given date as 19 Aug.

video link : https://drive.google.com/open?id=1OsPZfDasaT3L7l8jWnDwYMEDBcJM4l_B

Please provide a solution.

Thanks,
Parveen

**Comment by patchthecode** [comment]
taking a look

**Comment by patchthecode** [comment]
i do not think you have your 1 week calendar configured correctly.

What you are seeing might be expected. (Indates/outdates)

The proper setup for a 1 week calendar is this --> https://github.com/patchthecode/JTAppleCalendar/issues/581

Let me know if this works

**Comment by patchthecode** [comment]
I forgot to add that note to the Tutorial. I'll add this now.

**Comment by parveenkumar5** [comment]
Thanks,  worked for me using below code .

let parameter = ConfigurationParameters(startDate: startDate,
                                                endDate: allowedTillDate,
                                                numberOfRows: 1,
                                                generateInDates: .forFirstMonthOnly,
                                                generateOutDates: .off,
                                                firstDayOfWeek: DaysOfWeek(rawValue: Calendar.current.component(.weekday, from: startDate))!)
        return parameter
