### ISSUE TITLE
Not working in Xcode 8 beta 4

### ISSUE THREAD

**Issue by abhaysingh007** [patchthecode/JTAppleCalendar#106]
IMPORTANT:

Make sure you have checked the following BEFORE creating this issue:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 4.1.4
2. Did you leave a ★ rating on this repository if you like it? Yea.. I kinda need that. Get's me all pumped to answer questions/bugs.
3. Did you check the Wiki page to see if your question is already answered? --> https://github.com/patchthecode/JTAppleCalendar/wiki

If you've already done the above, then delete this text, and start your issue.

**Comment by patchthecode** [comment]
yea. its not swift 3 yet.
will convert in some time.

You will have to to the conversion your self for now.

**Comment by patchthecode** [comment]
I have now converted this to swift 3. 
It is located on the [Swift 3](https://github.com/patchthecode/JTAppleCalendar/tree/Swift3) branch
