### ISSUE TITLE
Mess with dates after calendar scrolling

### ISSUE THREAD

**Issue by VictorShurapov** [patchthecode/JTAppleCalendar#1061]
Version Number: Using JTAppleCalendar (7.1.7)

I'm trying to show the current month with the app start. 

I call  `calendarView.scrollToDate(Date(), animateScroll: false)` in viewDidLoad and it gives me wrong dates order.
<img width="447" alt="Screen Shot 2019-06-05 at 4 05 43 PM" src="https://user-images.githubusercontent.com/12258873/58959467-d5f1db00-87ad-11e9-94d4-b69f9e04b937.png">

If I'll click the previous month and then return to the current calendar shows the right ones.
<img width="441" alt="Screen Shot 2019-06-05 at 4 19 30 PM" src="https://user-images.githubusercontent.com/12258873/58959438-cbcfdc80-87ad-11e9-988b-85b54876b13d.png">

**Comment by patchthecode** [comment]
1. do you have a regular calendar view inside of a UIViewController?
or do you have a more complex setup, with views stacked inside views?

2. is it possible you can provide a sample program demonstrating this?

**Comment by VictorShurapov** [comment]
Regular calendarView inside MyViewController's root view :)
[conferenceroomcalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/3257457/conferenceroomcalendar.zip)

**Comment by VictorShurapov** [comment]
Also, I noticed that function calendar 'willScrollToDateSegmentWith' doesn`t get called with 'calendarView.scrollToSegment' so I couldn't update the monthLabel.

**Comment by patchthecode** [comment]
ok it looks like this behavior is expected.
You have the scrolling mode set to `.none`. Therefore if youre scroll to today's date (the 5th), you will see the 5th cell is scrolled to the left side.

If you have your scrolling mode set paged scrolling, then it would not stop at the 5th. it will scroll to the next paged section. Whish should be the behavior u want.

So either set it to paged mode in storyBoard, is set it in the ViewDidLoad in code.
If you set it in code, here are the possible options you can use --> https://patchthecode.com/jtapplecalendar-home/scrolling-modes/

**Comment by VictorShurapov** [comment]
Thank you a lot!! I didn't notice this scrolling options. What about 'willScrollToDateSegmentWith' function. I see that it doesn't get called in pair with 'scrollToSegment'. How can I update the month label in the right way?

**Comment by patchthecode** [comment]
built this project for 2+ years, and you found a bug. haha.
i forgot to call that delegate-function within the segment one.

Will fix later today.

**Comment by patchthecode** [comment]
since this is fixed. Closing  this issue.
Ive created a new one to reflect the calling of the delegate function here 
https://github.com/patchthecode/JTAppleCalendar/issues/1070
