### ISSUE TITLE
Swift Packages support

### ISSUE THREAD

**Issue by boborbt** [patchthecode/JTAppleCalendar#1065]
Hi Jay, given the emphasis given in the latest WWDC to swift packages, I was just wondering if you are planning to support them so to push even further the adoption of this awesome library.

Best,
   Roberto

**Comment by patchthecode** [comment]
I already had SPM support since this lib started 2+ years ago :D 
Is it not working?

I just tried Packages using master branch and it worked.

**Comment by boborbt** [comment]
LOL, sorry. I didn’t know about it, the instruction on the site don’t mention it and I just assumed it was not there.

Sorry for the mistake and thanks for the answer.

**Comment by patchthecode** [comment]
Hmm.. i tried 7.1.7

and it says "unable find any available tag"
But strangely, master branch works 
🤔
confused...

**Comment by boborbt** [comment]
I cannot try until tomorrow morning. If I see something interesting I’ll post it here.

**Comment by patchthecode** [comment]
Thanks.
reopening issue.

**Comment by boborbt** [comment]
I've tried to create a test project with the following Package.swift file:

```swift
import PackageDescription

let package = Package(
    name: "tmp",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "tmp",
            targets: ["tmp"]),
    ],
    dependencies: [
        .package(url: "https://github.com/patchthecode/JTAppleCalendar.git", from: "7.0.0"),
        //.package(url: "https://github.com/vapor/json.git", from: "2.0.0")
    ],
    targets: [
        .target(
            name: "tmp",
            dependencies: ["JTAppleCalendar"])
            // dependencies: ["JSON"])
    ]
)
```

I threw in the json package just to check that any error could not be caused by my code. 

While the json package works fine, with the JTAppleCalendar I get the following error:

```bash
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
    https://github.com/patchthecode/JTAppleCalendar.git @ 7.0.0..<8.0.0
```

My guess is that there is something funny in the package description of JTAppleCalendar. 

I'll look into it to see if somethings occurs to me (I am no swift package expert though...)

**Comment by boborbt** [comment]
Here is Xcode 11-beta error message when I try to add JTAppleCalendar as a dependency:

![Screenshot 2019-06-18 at 14 48 04](https://user-images.githubusercontent.com/204476/59683290-359dac80-91d8-11e9-8fd2-31c6d9ad0dce.png)

The above error refers to a configuration in which I asked explicitly for the 7.1.7 version. The same happens if I try a range of versions.

I tried other packages (e.g., SwiftyJSON and it works fine).

**Comment by somenkovnikita** [comment]
I tried use **master** and I got a lot of errors like:
```
error: use of undeclared type 'UICollectionViewDelegateFlowLayout'
error: use of undeclared type 'CGFloat'
...
error: use of undeclared type '<defenition-in-uikit,core-animation,etc..>'
```
I cannot understand why?

Using SHA of 7.1.7 (`1d9e3d0b4d8fbd0649da8cb6c9f1de2374c51cde`) in Xcode 11 fail:
<img width="598" alt="Screenshot 2019-06-18 at 16 49 23" src="https://user-images.githubusercontent.com/7226846/59690462-27f12280-91ea-11e9-84fd-a9bc7d977094.png">

**Comment by JoelJWest** [comment]
I'm also seeing these issues and would be interested in adding JTAppleCalendar as a Swift package in Xcode 11.

**Comment by patchthecode** [comment]
i will appreciate any help i can get on this.
i am a swift package noob.

**Comment by patchthecode** [comment]
Fixed closing issue.
NOTE --> 

1. What is fixed is master branch for
XCode 11 Beta Swift 5

2. Master branch contains breaking changes, Because YearView is added to this project.
