### ISSUE TITLE
Showing wrong weekday

### ISSUE THREAD

**Issue by ErAshu** [patchthecode/JTAppleCalendar#1066]
I have just download the example app and run. Its showing wrong day.
14 June 2019 is Friday and its showing Saturday.  Screenshot Attached.

Plz help.
<img width="329" alt="Screenshot 2019-06-14 at 12 56 42 PM" src="https://user-images.githubusercontent.com/4178384/59491644-cb69cc80-8ea4-11e9-8ecf-0cc7c39c0016.png">

**Comment by patchthecode** [comment]
show me your configure calendar code please?

**Comment by patchthecode** [comment]
will reopen once responds

**Comment by ErAshu** [comment]
I have fixed this. Thanks for response.

**Comment by basabendra** [comment]
Hi, I am facing this issue. Please help.
As per JT calendar yesterday was sunday (it was monday). Similarly, today is monday (it is tuesday).
