### ISSUE TITLE
Calendar isn't working

### ISSUE THREAD

**Issue by whatweneed** [patchthecode/JTAppleCalendar#1067]
**7.1.7**

The "didSelectDate" and "didDeselectDate" function isn't called 

The click on any cell doesn't respond selecting the date

It expect to select the date

**Comment by whatweneed** [comment]
See the screen recording. It's the example project.
[Screen Recording2.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/3302478/Screen.Recording2.mov.zip)

**Comment by felipeflorencio** [comment]
see the comments at #1068 @whatweneed

**Comment by patchthecode** [comment]
Can you let me know if you have facebook as one of your Pods?

**Comment by whatweneed** [comment]
Yes

**Comment by patchthecode** [comment]
Can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
I think you are experiencing this -> https://github.com/patchthecode/JTAppleCalendar/issues/1015

**Comment by whatweneed** [comment]
That problem isn’t solved in the last release of the library?
Anyway the most strange thing is this:
In the currently (and previous) build online the calendar has stopped to work.
