### ISSUE TITLE
Can't get the dateCell text to display dates in English 

### ISSUE THREAD

**Issue by blastback360** [patchthecode/JTAppleCalendar#1071]
Version Number: 7.1.7

I just finished following the steps for the first tutorial titled "Calendar from scratch" and everything is going pretty good besides the fact that when I run my app, the calendar is displaying the dates in another language. I'm not entirely sure what it is though. I followed all the steps correctly to the best of my knowledge, and I didn't deviate from what the tutorial told me to do except when I made my ViewController the delegate and dataSource of the calendar programmatically instead of connecting it on the storyboard. 

Any help will be greatly appreciated. Thank you!!

My code and a screenshot of the viewController is gonna be down below. 

<img width="380" alt="Screen Shot 2019-06-19 at 9 31 02 PM" src="https://user-images.githubusercontent.com/42794755/59818651-952fb100-92d9-11e9-8e4c-6f0b6270a5f5.png">

![Screen Shot 2019-06-19 at 9 29 21 PM](https://user-images.githubusercontent.com/42794755/59818605-6b768a00-92d9-11e9-889a-3faaffc70a22.png)

**Comment by patchthecode** [comment]
1. why are your dates squished like that? Did you remember to remove the minimin-line and cell spacing by setting it to zero as stated in the tutorial?
2. If you want to set the calendar to a language of your choice, do 2 things (i should probably add this to the tutorial)

1st, set the calendar instance
```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let startDate = formatter.date(from: "2018 01 01")!
        let endDate = Date()
        let calendar = Calendar(identifier: .gregorian) // Pick your calendar type here
        return ConfigurationParameters(startDate: startDate, endDate: endDate)
    }
``` 

2nd print the calendar in your language
```swift
func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
   let cell = ....
   cell.dateLabel.text = myDateFormmater.string(from: date)
   return cell
}
```

where `myDateFormmater` is a DateFormatter() configured to your region and your language.

**Comment by blastback360** [comment]
OHHH ok I did remember to reset the space settings BUT I set my label height to be too small so it was cutting off the top and the bottom of the text. It was only until you told me that my dates were squished that I took a harder look at them and realized they were regular English characters but just cut off lol. Thank you!!
