### ISSUE TITLE
How to trigger events that stop scrolling through scrollToSegment

### ISSUE THREAD

**Issue by zooooooooom** [patchthecode/JTAppleCalendar#1072]
Hi, I have a scene. I want to monitor scrolling if stoped.  Any way?

**Comment by patchthecode** [comment]
This library is a UICollectionView.
So it is done the same way you would monitor if the scrolling of a UICollectionView has stopped.

**Comment by patchthecode** [comment]
Did i answer your question?

**Comment by patchthecode** [comment]
closing until user responds
