### ISSUE TITLE
podspec deleted

### ISSUE THREAD

**Issue by michaelgmcd** [patchthecode/JTAppleCalendar#1073]
**(Required) Version Number:** Master

## Description

When trying to pod install via git, I receive:
```
Pre-downloading: `JTAppleCalendar` from `https://github.com/patchthecode/JTAppleCalendar.git`
[!] Unable to find a specification for 'JTAppleCalendar'.
```

It looks like the podspec was deleted in adbb2da9d3215be6824d0b5ea82e0022636acd64. Was this intentional?

**Comment by patchthecode** [comment]
I was getting Swift package manager to work.

It was intentionally done.
But Cocoapods will still be supported.
Will finish the update after work today.

**Comment by patchthecode** [comment]
Thanks for finding this issue.
I fixed it up again.

Can you let me know if ti works?
