### ISSUE TITLE
Hi I am getting EXC_BAD_ACCESS when selecting dates in didSelectDate

### ISSUE THREAD

**Issue by henrydeclety** [patchthecode/JTAppleCalendar#1075]
<img width="621" alt="Screenshot 2019-06-27 at 10 38 01" src="https://user-images.githubusercontent.com/15074586/60250899-cd318800-98c7-11e9-9198-568cc095b839.png">

**Comment by bivant** [comment]
Not enough information. As nobody else posted such kind of error earlier it is quite possible that problem in your code. Are you able to reproduce the issue [on the sample](https://github.com/patchthecode/JTAppleCalendar/tree/master/SampleJTAppleCalendar) in the library?
Please describe the user case (what you do before the exception) - does it crash after first tap?

Calling the selectDates method inside the selection handling one does not look like a good practice.
What version of the library are you using? Can not find the **selectDates** method in the JTAppleCalenderView

**Comment by henrydeclety** [comment]
Okay yeah, I don't have to call selectDate myself, Im guessing selectDates was calling DidSelect..

**Comment by patchthecode** [comment]
Yea, @bivant is correct.

> Calling the selectDates method inside the selection handling one does not look like a good practice.

If you select a cell, then the didSelect delegate will be called, which in turn selects more dates
`calendar.selectDates([dates]), which in turn calls didSelect, which in turn calls... etc  inf loop.

If your design DOES call for calling a select inside of the didselect, then you can break the loop cycle by adding another parameter:

```
calendar.selectDates([dates], triggerSelectionDelegate: false)
```

This will cause the delegate to not be triggered.

**Comment by patchthecode** [comment]
closing issue.
