### ISSUE TITLE
I want the week view to separate each month

### ISSUE THREAD

**Issue by babyfanta168** [patchthecode/JTAppleCalendar#1076]
**(Required) Version Number:**
latest version

## Description
![Screen Shot 2019-06-28 at 10 22 33 AM](https://user-images.githubusercontent.com/52305594/60315143-958e1300-998f-11e9-9dac-670db1a4e309.png)
In week view I want all the months are separate from each other. Is there a solution?

**Comment by patchthecode** [comment]
i am trying to understand this but...
Can you show a screen shot of what you would like the screen to look like?
I do not know what you mean by 

> In week view I want all the months are separate from each other

**Comment by babyfanta168** [comment]
Sorry for very late reply, In week view I mean when set to one row view. Suppose today is 1st May. I want it look like this
![60315143-958e1300-998f-11e9-9dac-670db1a4e309](https://user-images.githubusercontent.com/52305594/60405357-cfeaf080-9bd9-11e9-8142-b0b6545876ab.png)
and previous month(April) is
![Screen Shot 2019-06-28 at 10 22 33 AM](https://user-images.githubusercontent.com/52305594/60405372-e6914780-9bd9-11e9-9658-1967b333245a.png)

**Comment by patchthecode** [comment]
I am still not understanding.
But if you want a week view, your setup could be what is described here -> https://github.com/patchthecode/JTAppleCalendar/issues/581
