### ISSUE TITLE
Some dates can't be selected.

### ISSUE THREAD

**Issue by star-essence** [patchthecode/JTAppleCalendar#1077]
**Version Number:**
7.1.7

<img width="379" alt="image" src="https://user-images.githubusercontent.com/14901381/60345061-15999480-99f3-11e9-8694-f78753805c8a.png">

## Description ##
I can't select some dates. Why this happens?
Please check out attached image.
Other dates can be selected without problem.
Thanks in advance.

## Some Code ##
```swift
    override func viewDidLoad() {
        super.viewDidLoad()

        calendarView.scrollDirection = .vertical
        calendarView.scrollingMode   = .none
        calendarView.showsHorizontalScrollIndicator = false
        
        calendarView.scrollToDate(Date())
        
        calendarView.selectDates([Date()])
        
    }
```

-----
```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let startDate = formatter.date(from: "2018 01 01")!
        let endDate = Date()
        let calendar = Calendar.current
        
        return ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: calendar, generateInDates: .forAllMonths, generateOutDates: .tillEndOfGrid, firstDayOfWeek: .monday, hasStrictBoundaries: false)
    }
```

**Comment by patchthecode** [comment]
This was a bug that was fixed.
can you set you pod version to this commit and let me know if the error goes away -> `eea5725b2fb84e998b2998cf3ba724194b1eb705`

Put this in you pod file: 
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :commit => 'eea5725b2fb84e998b2998cf3ba724194b1eb705'
```

Let me know

**Comment by star-essence** [comment]
Thanks for your fixing.

I've updated to 8.0.0.

And I changed some object names as 8.0.0 MIGRATION GUIDE said.

So I could build succeeded.

But a problem occurred.

This error message was displayed.

<img width="1147" alt="error" src="https://user-images.githubusercontent.com/14901381/60378488-26332480-9a5e-11e9-9039-f964d8c5291f.png">

How can I solve this?

Thanks in advance.

**Comment by star-essence** [comment]
I solved this problem by installing ver8.0.0 again and again.

Thanks for your help.
