### ISSUE TITLE
Programmatically selecting cell based on current date

### ISSUE THREAD

**Issue by QuasarkStudios** [patchthecode/JTAppleCalendar#1078]
**(Required) Version Number:**
Version (7.1.7)

Hey, I'm trying to implement a pretty simple behavior for the calendar but I'm running into trouble doing it, and I was wondering if there was a recommended way to do it. 

Basically, upon opening the calendar, I would like the cell with that date that matches the current date to be selected. I've already read through and implemented the code to select and deselect a cell, but this is giving me some trouble. Any help would be greatly appreciated. 

Thanks!!

**Comment by babyfanta168** [comment]
You can try this in viewDidLoard()
self.calendarView.scrollToDate(Date(),animateScroll: false)
self.calendarView.selectDates([ Date() ], triggerSelectionDelegate: false)

**Comment by patchthecode** [comment]
I would just do this inside viewDidLoad

```swift
self.calendarView.scrollToDate(Date(),animateScroll: false)
self.calendarView.selectDates([ Date() ])
```

Similar to @babyfanta168 , but leave out the `triggerSelectionDelegate`

**Comment by QuasarkStudios** [comment]
I knew it was something simple. Thank you both!
