### ISSUE TITLE
(On Test Branch) Incorrectly Cell State on multi-selection mode

### ISSUE THREAD

**Issue by mrjimoy** [patchthecode/JTAppleCalendar#108]
Hey there, when I tried to repetitively select and deselect the dates on a multi-selection mode, I found this:
![snip20160811_15](https://cloud.githubusercontent.com/assets/6197219/17583883/92007c26-5fdd-11e6-9721-c782eccf1429.png)
The CellState of 22 is .Full. 

I tried it like:

1. Select the date August 16-August 23
2. Then try to select another date, let say August 17-August 24, then the CellState for 22 is Full, which should be : Middle.

Please confirm. Thanks.

**Comment by patchthecode** [comment]
Hmm.. im trying to recreate this but im not able to.
Join on chat when you got the chance

**Comment by mrjimoy** [comment]
![image](https://cloud.githubusercontent.com/assets/6197219/17654083/2dc92f0c-62c9-11e6-9f33-f32135c183f8.png)

The calendar should be enable the multi-selection, and only based on one minimum and one maximum, cannot have another range (only 1 range).

Steps to reproduce (as on image above):
1. Set August 15th-23rd as a default selected value while you first load the calendar
2. Then, select August 16th, this should reset previously default selected date
3. Select August 23rd. This will make 22th's state as Middle
4. Try to select another date, August 17th. This also should reset previously selected date
5. Select August 24th. This will make 22th's state as Middle
6-9. Retry the steps from 2-3 or 4-5

**Comment by patchthecode** [comment]
ok one sec. trying to recreate

**Comment by patchthecode** [comment]
Ok. I checked it out. I will need to know the functions you have called. For your date selections. Your steps are clear, but I need to know what functions you called. E.g. did you use force selections? did you call delegates etc? This information is needed.

**Comment by mrjimoy** [comment]
This is on **viewDidLoad()**:
```
calendarView.delegate = self
calendarView.dataSource = self
calendarView.backgroundColor = UIColor.clearColor()
calendarView.cellInset = CGPoint(x: 0, y: calendarView.cellInset.y)
        
calendarView.itemSize = 34
calendarView.direction = .Vertical
calendarView.firstDayOfWeek = .Sunday
calendarView.scrollingMode = .StopAtEachSection

calendarView.registerCellViewXib(fileName: "CalendarCellView")
calendarView.registerHeaderViewXibs(fileNames: ["CalendarHeaderView"])
```
And this is the delegate:
```
extension CalendarViewController: JTAppleCalendarViewDelegate {
    
    func calendar(calendar: JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date: NSDate, cellState: CellState) {
        let cell = (cell as! BM_CalendarCellView)
        cell.setupCellBeforeDisplay(cellState, selectedCheckInDate: selectedCheckInDate, selectedCheckOutDate: selectedCheckOutDate)
    }
    
    func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {
        setDateRange(true, date: date)

        (cell as? BM_CalendarCellView)?.cellSelectionChanged(cellState, selectedCheckInDate: selectedCheckInDate, selectedCheckOutDate: selectedCheckOutDate)
    }
    
    func calendar(calendar: JTAppleCalendarView, didDeselectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {
        setDateRange(false, date: date)

        (cell as? BM_CalendarCellView)?.cellSelectionChanged(cellState, selectedCheckInDate: selectedCheckInDate, selectedCheckOutDate: selectedCheckOutDate)
    }
    
    func calendar(calendar: JTAppleCalendarView, isAboutToResetCell cell: JTAppleDayCellView) {
        (cell as? BM_CalendarCellView)?.roundSelectedView.hidden = true
        (cell as? BM_CalendarCellView)?.leftSelectedView.hidden = true
        (cell as? BM_CalendarCellView)?.rightSelectedView.hidden = true
    }
    
    func calendar(calendar: JTAppleCalendarView, canSelectDate date: NSDate, cell: JTAppleDayCellView, cellState: CellState) -> Bool {
        let dateOrder = NSCalendar.currentCalendar().compareDate(date, toDate: NSDate(), toUnitGranularity: .Day)
        if dateOrder == .OrderedAscending {
            return false
        }
        return true
    }

}
```

I omit some of the code but if you required it for your inspections, please let me know..

**Comment by patchthecode** [comment]
My code works perfectly :/ 

Here is my code logic for the range selection (you did not give me yours)
```swift
switch cellState.selectedPosition() {
        case .Full, .Left, .Right:
            selectedView.backgroundColor = UIColor.yellowColor()
        case .Middle:
            selectedView.backgroundColor = UIColor.blueColor()
        default:
            selectedView.backgroundColor = nil
}
```

I have placed this code inside the following  2 functions:
```swift 
func calendar(calendar: JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date: NSDate, cellState: CellState) 
```
And
```swift
func calendar(calendar: JTAppleCalendarView, didDeselectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState)
```

if you still can get it to work, message [here](https://gitter.im/patchthecode/JTAppleCalendar)

**Comment by mrjimoy** [comment]
Mannnn, so sorry, after I tidied up my code, it works perfectly :(

I modified the code under switch cellState.selectedPosition()..

**Comment by patchthecode** [comment]
great 👍
