### ISSUE TITLE
can't connect calendarView to dataSource in storyboard

### ISSUE THREAD

**Issue by Polkendotts** [patchthecode/JTAppleCalendar#1082]
**(Required) Version Number:**
JTAppleCalendar (8.0.0)

## Additional Context

I am following the wiki tutorial but I am unable to get past the first step of setting the calendar’s ibCalendarDataSource and ibCalendarDelegate to be the ViewController subclass in the storyboard as shown here:
<img width="803" alt="Screen Shot 2019-07-04 at 8 55 02 PM" src="https://user-images.githubusercontent.com/44610034/60664977-343dd680-9e9e-11e9-9543-0b0b15ae08e4.png">

On my screen it looks like this, and there is no ibCalendarDataSource or ibCalendarDelegate
delegate to be connected:
<img width="1139" alt="Screen Shot 2019-07-04 at 9 00 15 PM" src="https://user-images.githubusercontent.com/44610034/60665195-c80fa280-9e9e-11e9-8787-69ae48345641.png">

I've properly classed the uicollection view to JTAppleCalendarView
<img width="260" alt="Screen Shot 2019-07-04 at 9 34 47 PM" src="https://user-images.githubusercontent.com/44610034/60667448-871a8c80-9ea4-11e9-899b-0568bff52313.png">

I've tried to work around this by setting the dataSource and delegate manually in my viewcontroller, but I put a print command in the dataSource and delegate extensions, I can see they are not being called. 

<img width="1014" alt="Screen Shot 2019-07-04 at 9 04 23 PM" src="https://user-images.githubusercontent.com/44610034/60666103-33f30a80-9ea1-11e9-856d-1af3f4cc57d9.png">
<img width="1020" alt="Screen Shot 2019-07-04 at 9 17 25 PM" src="https://user-images.githubusercontent.com/44610034/60666107-36556480-9ea1-11e9-801c-df76aea7c736.png">

And the simulation looks like this:
<img width="334" alt="Screen Shot 2019-07-04 at 9 02 17 PM" src="https://user-images.githubusercontent.com/44610034/60666127-48370780-9ea1-11e9-912c-43b51154c818.png">

I've tried looking through more recent examples such as, this from 7months ago
https://github.com/lamkjbo/JTCalendarCustom

However every example has the same ibCalendarDataSource or ibCalendarDelegate outlets in their storyboard, I can't figure out where they come from- i've searched through the pod files to see if they are declared somewhere as well, but to no avail. I think my skill level and knowledge is not deep enough to figure it out. 

Im frustrated because it seems so simple but I can't get past the first step. I've already devoted 2 days developing a beautiful calendar by building off of one of the basic sample projects downloadable on the wiki tutorial page, but I am unable to recreate it in my own project because of this issue.

**Comment by patchthecode** [comment]
checking.
give me a sec.

**Comment by patchthecode** [comment]
what package manager are u using?
cocoapods? carthage? swiftpackagemanager ?

**Comment by Polkendotts** [comment]
Thanks! I use cocoapods

**Comment by Polkendotts** [comment]
> what package manager are u using?
> cocoapods? carthage? swiftpackagemanager ?

Thanks! I use cocoapods

**Comment by patchthecode** [comment]
I just created a new project and every thing works well.

are you following this tutorial? -> https://patchthecode.com/jtapplecalendar-home/calendar-from-scratch/

**Comment by patchthecode** [comment]
If you are, then just know that you are following the tutorial for version 7.1.7 ok.
But you just told me that you have version 8.0.0 installed :/ 

Could that be the source of confusion?

**Comment by Polkendotts** [comment]
Ah of course, that's most likely the issue. I had an issue downloading the specific version pod 'JTAppleCalendar', '~>; 7.1' I realize now it was because the ";" needed to be removed. Ok, I will try again now with the correct version and hopefully the issue will be resolved. Thank you so much.

**Comment by patchthecode** [comment]
cool. let me know how it goes.
If all is well, you can close this issue.

**Comment by Polkendotts** [comment]
> cool. let me know how it goes.
> If all is well, you can close this issue.

yep works great now :)

**Comment by patchthecode** [comment]
awesome

**Comment by orcunorcun** [comment]
@patchthecode Can you share your codes and pod file. I tried but it response error after build :/

**Comment by orcunorcun** [comment]
@patchthecode Can you share your codes and pod file. I tried it, but it responses error after build :/
