### ISSUE TITLE
warnings compiling with 

### ISSUE THREAD

**Issue by appsird** [patchthecode/JTAppleCalendar#1083]
I receive the following warnings when compiling with Version 11.0 beta 3 (11M362v) for iOS
<img width="649" alt="Screen Shot 2019-07-05 at 1 06 19 PM" src="https://user-images.githubusercontent.com/8471833/60743321-e2409380-9f25-11e9-963c-91f8e284bd9f.png">
 12.4

**Comment by patchthecode** [comment]
Yea. 
Im still sorting out the beta stuff.
It will be ready before XCode 11 is out of beta.
