### ISSUE TITLE
Help me please, the same week is scrolled twice

### ISSUE THREAD

**Issue by Evlring** [patchthecode/JTAppleCalendar#1084]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29180327/60830684-6f9f1480-a1c0-11e9-9b80-54c7a3a3db0e.gif)

**Comment by Evlring** [comment]
If you open the monthly view of July, it will end in the first week of June. If we scroll a month ahead, there will again be the first week of the month. Maybe this is the reason for this calendar behavior.

<img width="345" alt="Снимок экрана 2019-07-08 в 20 42 47" src="https://user-images.githubusercontent.com/29180327/60830923-f9e77880-a1c0-11e9-9607-c35f80b6e153.png">
<img width="352" alt="Снимок экрана 2019-07-08 в 20 42 50" src="https://user-images.githubusercontent.com/29180327/60830924-fbb13c00-a1c0-11e9-8e0d-068d8d9834a9.png">

**Comment by patchthecode** [comment]
Yes this is your reason.
Have you taken a look at the setup for a typical 1 row calendar? -> https://patchthecode.com/jtapplecalendar-home/week-view-month-view/ ?

here is the code for 1 row calendar setup

```swift
let parameters = ConfigurationParameters(startDate: startDate,
                                         endDate: endDate,
                                         numberOfRows: 1,
                                         generateInDates: .forFirstMonthOnly,
                                         generateOutDates: .off,
                                         hasStrictBoundaries: false)
```

Put that in your configure calendar setup
let me know if it works for you,

**Comment by Evlring** [comment]
Thank you very much!
