### ISSUE TITLE
Push 8.0.1 podspec to Cocoapods Trunk Repo

### ISSUE THREAD

**Issue by terenceyan** [patchthecode/JTAppleCalendar#1085]
**(Required) Version Number:**
8.0.1
## Description
Currently it's not possible to use JTAppleCalendar 8.0.1 via cocoapods, despite the release is in master.

## Steps To Reproduce
1. Update a project's Podfile to `pod 'JTAppleCalendar', '8.0.1'`
2. Perform `pod install`

## Expected Behavior
JTAppleCalendar 8.0.1 is installed and integrated into workspace. Current pod specs master repo is still on 8.0.0

**Comment by patchthecode** [comment]
i know... i cant push :/ 
I have a bug with cocoa pods that i filed here -> https://github.com/CocoaPods/fourflusher/issues/24

**Comment by patchthecode** [comment]
Ok.
i have decided to drop support of cocoapods and carthage on versions 8+
Why?
Because XCode 11 comes builtin with SwiftPackageManager.
No weird configuration of 3rd party app is needed. SImply go inside XCode and enter my repository -> 
https://github.com/patchthecode/JTAppleCalendar

done

**Comment by patchthecode** [comment]
closing this. let me know what you think.
