### ISSUE TITLE
Is there any basic example with last version?

### ISSUE THREAD

**Issue by orcunorcun** [patchthecode/JTAppleCalendar#1086]
version: 8.0.0 and 7.1.7
I tried the example with version 8.0.0 and 7.1.7 but both of them doesn't work. It shows only white screen for 8.0.0, for 7.1.7 version it crashed after build with error bellow.

 required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setupNewLayout(from: collectionViewLayout as! JTAppleCalendarLayoutProtocol <<<ERROR--------Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) ----->>>
    }

Please show me a basic example with last version of library.

**Comment by patchthecode** [comment]
have you taken a look at the tutorials? https://github.com/patchthecode/JTAppleCalendar/wiki

They are for version 7.1.7

**Comment by patchthecode** [comment]
I have yet to update the examples for 8.0.0.
Please use 7.1.7 and the examples  located here  https://github.com/patchthecode/JTAppleCalendar/wiki

It has every thing you need.

**Comment by patchthecode** [comment]
closing this. but let me know if youre still stuck.

**Comment by orcunorcun** [comment]
Yes I tried it but it doesn't work :/
