### ISSUE TITLE
Unknown class _JTACMonthView in Interface Builder file

### ISSUE THREAD

**Issue by iOSUser110** [patchthecode/JTAppleCalendar#1087]
Getting error like 
Unknown class _JTACMonthView in Interface Builder file

**Comment by patchthecode** [comment]
did you set the module?

**Comment by iOSUser110** [comment]
Yes i have already set the Module, Just i ma using this in XIB file

**Comment by patchthecode** [comment]
what version do you have in have in your podfile?

**Comment by iOSUser110** [comment]
8.0.0

**Comment by patchthecode** [comment]
can you send me a an example app with the error?

**Comment by patchthecode** [comment]
closing until user responds.
seting the awaiting response flag.

**Comment by rup2701** [comment]
What's the new module name?
Thx.
