### ISSUE TITLE
didSelectDate and didDeselectDate not working in version 8.0.0

### ISSUE THREAD

**Issue by AmjadAlmu** [patchthecode/JTAppleCalendar#1088]
Hello, 
I'm using JTAppleCalendar 8.0.0 because I didn't find 8.0.1 in CocoaPods and I realized didSelectDate and didDeselectDate don't work.
here is screenshots from storyboard 
<img width="257" alt="Screen Shot 2019-07-11 at 10 52 51 AM" src="https://user-images.githubusercontent.com/35580200/61034447-f37a1c00-a3cd-11e9-95f5-3d48183e5e69.png">
<img width="255" alt="Screen Shot 2019-07-11 at 10 53 08 AM" src="https://user-images.githubusercontent.com/35580200/61034453-f5dc7600-a3cd-11e9-9126-e7e3b7dbb202.png">

and here how I wrote them
```swift
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
}


func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
    }
```

**Comment by patchthecode** [comment]
did you look at the migration guide?
https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

**Comment by patchthecode** [comment]
8.0.1 is waiting to be released.
I cannot release it because I am getting a cocoapod error on my end.

I have filed an issue here -> https://github.com/CocoaPods/fourflusher/issues/24

But, since you are using XCode 11 Beta, why are you even using CocoaPods?
Please use Swift Package Manager.
It is extremely easier and is built into XCode.

**Comment by AmjadAlmu** [comment]
Thank you it worked!
I don't know about Swift Package Manager but I will read about it

**Comment by sandeep9607** [comment]
`extension DashboardViewController : JTACMonthViewDelegate{

    func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTACMonthView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {

          setupViewsFromCalendar(from: visibleDates)
    }
}`

**didScrollToDateSegmentWith** method calls but didSelectDate and didDeselectDate don't call

**Comment by Guiraudou** [comment]
> `extension DashboardViewController : JTACMonthViewDelegate{
> 
> ```
> func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
>     handleCellSelected(view: cell, cellState: cellState)
>     handleCellTextColor(view: cell, cellState: cellState)
> }
> 
> func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
>     handleCellSelected(view: cell, cellState: cellState)
>     handleCellTextColor(view: cell, cellState: cellState)
> }
> 
> func calendar(_ calendar: JTACMonthView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
> 
>       setupViewsFromCalendar(from: visibleDates)
> }
> ```
> 
> }`
> 
> **didScrollToDateSegmentWith** method calls but didSelectDate and didDeselectDate don't call @AmjadAlmu @patchthecode

I Have the same issue. Did you find a solution ? Thanks :)

**Comment by patchthecode** [comment]
@Guiraudou if you have an issue with this i suggest you open a new one as this was fixed some time ago, and i am unclear on the nature of your issue
