### ISSUE TITLE
How would I create overlapping cells?

### ISSUE THREAD

**Issue by charlieporth1** [patchthecode/JTAppleCalendar#1089]
**(Required) Version Number:**
7.0.1
## Description
@ryanhughes How would I create overlapping cells?
I want to recreate the Google Fit app calendar 
I would like to center the cells and after resizing only a couple of them

## Additional Context
this is my cell code
```
class DateCell: JTACDayCell {
    @IBOutlet var dateLabel: UILabel!
    @IBOutlet var progressUIView: UIView!
    @IBOutlet var innerProgressViewWidthConstraintW: NSLayoutConstraint!
    @IBOutlet var innerProgressViewWidthConstraintH: NSLayoutConstraint!
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }

    func setUpCell(label: String, progressDate: [String], progress: [MonthlyProgressDocument], cellCount: Int, cellRow: Int, cellColl: Int, cellState: CellState, cellSize:CGFloat) {
        var count: Int = 0
        progressUIView.backgroundColor = UIColor.clear.withAlphaComponent(0.0)
        for date in progressDate {
            let cellSizd = Float(cellSize)
            print("date, cellSizd", date, cellSizd)
            dateLabel.text = label
            if date == dateLabel.text {
                var size: Float = Float(Float((progress[count].practiceTime ?? 0)) / Float(cellSizd / 2))
                print("size ", size)
                if size < cellSizd {
                    size = cellSizd
                }
                print("(size / 2)  ", size / 2) // (size / ((size / 0.085) + 1.0) (size / ((size / 0.055) + 1.0))
                let orgY = CGFloat(Float(size / 2) - Float(frame.origin.y))
                let orgX = CGFloat(Float(size / 2) - Float(frame.origin.x))
                print("orgX,  orgY", Float(orgX), Float(orgY))
                let rect:CGRect = CGRect(x: 0, y: 0, width: CGFloat(size), height: CGFloat(size))
                let rectCell:CGRect = CGRect(x: orgX, y: orgY, width: CGFloat(size), height: CGFloat(size))
                let rad:CGFloat = CGFloat(Float((size / 2)))
                progressUIView.layer.cornerRadius = rad
                progressUIView.frame = rect
                innerProgressViewWidthConstraintH.constant = CGFloat(size)
                innerProgressViewWidthConstraintW.constant = CGFloat(size)
                dateLabel.textColor = UIColor.white
                progressUIView.backgroundColor = AppColorTheme.SapphireBlueOpac
                bringSubview(toFront: progressUIView)
                bringSubview(toFront: self)

                    self.frame = rectCell

                #if DEBUG
                    backgroundColor = UIColor.red.withAlphaComponent(0.2)
                #endif
            }

            count += 1
        }
    }
}```
And this is the ViewController 
```
import Firebase
import Foundation
import JTAppleCalendar
import UIKit
class MonthlyPracticeChartViewController: UIViewController {
    var dates: [String]?
    var monthlyProgressDocument: MonthlyProgressDocument?

    @IBOutlet var calendarView: JTACMonthView?
    var monthlyProgressDocuments: [MonthlyProgressDocument]?
    override func viewDidLoad() {
        super.viewDidLoad()
//        calander?. = self as? UICollectionViewDelegate
        print("dates ", dates ?? [])
        print("monthlyProgressDocuments ", monthlyProgressDocuments ?? [])
    }
    

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        calendarView?.scrollDirection = .horizontal
        calendarView?.scrollingMode   = .stopAtEachCalendarFrame
        calendarView?.showsHorizontalScrollIndicator = true
        calendarView?.minimumLineSpacing = 0
        calendarView?.minimumInteritemSpacing = 0
        calendarView?.allowsRangedSelection = true
        calendarView?.allowsMultipleSelection = true
        calendarView?.cellSize = CGFloat(Float(calendarView?.frame.size.width ?? 0.00) / 7)
        calendarView?.backgroundColor = UIColor.clear.withAlphaComponent(0.0)

    }
   
}

extension MonthlyPracticeChartViewController: JTACMonthViewDataSource {
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let startDate = Date().startOfMonth()
//        let startDate = formatter.date(from: "2018 01 01")!
        let endDate = Date().endOfMonth()
//        let endDate = Date()
        return ConfigurationParameters(startDate: startDate, endDate: endDate)
    }
}

extension MonthlyPracticeChartViewController: JTACMonthViewDelegate {
    //date//cell
    func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! DateCell
//        cell.setUpCell(label: cellState.text, progressDate:  dates , progress: monthlyProgressDocuments[indexPath.row] ?? MonthlyProgressDocument())
        var column: Int = 0
        let row: Int = Int(indexPath.row / 7)
        if (indexPath.row > 0) && (row > 0) {
            column = Int(row % indexPath.row)
        }
        cell.setUpCell(label: cellState.text, progressDate: dates ?? [], progress: monthlyProgressDocuments ?? [], cellCount: indexPath.row, cellRow: row, cellColl: column, cellState: cellState, cellSize: calendar.cellSize)
        cell.dateLabel.text = cellState.text
        configureCell(view: cell, cellState: cellState)
    }

    func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
//        if (indexPath.row > 7) {
        var row: Int = 0
        let column: Int = Int(indexPath.row / 7)
        if (indexPath.row > 0) {
         row = Int(7 % indexPath.row)
        }
        print("indexPath.row ", indexPath.row)
        print("column ", column)
        print("row ", row)
        cell.dateLabel.text = cellState.text.trimmingCharacters(in: .whitespacesAndNewlines)
        cell.setUpCell(label: cell.dateLabel.text ?? "", progressDate: dates ?? [], progress: monthlyProgressDocuments ?? [], cellCount: indexPath.row, cellRow: row, cellColl: column, cellState: cellState, cellSize: calendar.cellSize)
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return cell
    }
    //header
    func calendar(_ calendar: JTACMonthView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTACMonthReusableView {
        let formatter = DateFormatter()  // Declare this outside, to avoid instancing this heavy class multiple times.
        formatter.dateFormat = "MM-yyyy"
        
        let header = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: "DateHeader", for: indexPath) as! DateHeader
        header.monthTitle.text = formatter.string(from: range.start)
        return header
    }
    //in/out dates
    func calendarSizeForMonths(_ calendar: JTACMonthView?) -> MonthSize? {
        return MonthSize(defaultSize: 35)
    }
    func configureCell(view: JTACDayCell?, cellState: CellState) {
        guard let cell = view as? DateCell  else { return }
        cell.dateLabel.text = cellState.text
        handleCellTextColor(cell: cell, cellState: cellState)
    }
    func handleCellTextColor(cell: DateCell, cellState: CellState) {
//        if cellState.dateBelongsTo == .thisMonth {
//            cell.dateLabel.textColor = UIColor.black
//        } else {
//            cell.dateLabel.textColor = UIColor.gray
//        }
        if cellState.dateBelongsTo == .thisMonth {
            cell.isHidden = false
        } else {
            cell.isHidden = true
        }
    }

    
}```
and Heres a screenshot of the problem 
![Simulator Screen Shot - iPhone 8 - 2019-07-11 at 22 58 34](https://user-images.githubusercontent.com/13573364/61101528-b777a300-a42f-11e9-900b-06b31ed9b7f1.png)

**Comment by patchthecode** [comment]
Honestly, I am not sure how to achieve this.
But I would tell you that this library is a UICollectionView.
Therefore if what you are trying to do can be done with a UICollectionView, then it can also be done with this lib.

**Comment by patchthecode** [comment]
closing this issue. until user responds.
