### ISSUE TITLE
(On Test Branch) Bug on load dates

### ISSUE THREAD

**Issue by victtavares** [patchthecode/JTAppleCalendar#109]
I just updated to the new code on the master and now, the dates are loading out of order at the first time the calendar is loaded, if I scroll to the previous month and come back, it's ordered.

At the first load:
![slack for ios upload png](https://cloud.githubusercontent.com/assets/2566465/17592169/8a1a3392-5fb7-11e6-9856-9282efd03555.jpeg)

After I come back:
![slack for ios upload-2](https://cloud.githubusercontent.com/assets/2566465/17592119/6245694a-5fb7-11e6-921b-fae1640896c8.jpg)

**Comment by patchthecode** [comment]
Can you read this and let me know if it resolves your issue -> https://github.com/patchthecode/JTAppleCalendar/wiki/Message-to-testers-working-on-master-branch.
