### ISSUE TITLE
Setting Delegate/DataSource does not work asynchronusly

### ISSUE THREAD

**Issue by t3mschm2d** [patchthecode/JTAppleCalendar#1092]
**(Required) Version Number:**

**Comment by patchthecode** [comment]
be more descriptive?
i have no idea what this means

**Comment by t3mschm2d** [comment]
I have just been updating the comment, sorry for posting the empty on, that was a mistake.

**Comment by t3mschm2d** [comment]
Update: I figured out, that the Problem I'm facing is caused by my RXSwift handling. So I simply had to call 'calendarView.reloadData()' in the async function. Sorry for opening up this Issue
