### ISSUE TITLE
Same problem. Week scrolls twice

### ISSUE THREAD

**Issue by Evlring** [patchthecode/JTAppleCalendar#1094]
**JTAppleCalendar 8.0.0**

Again the same week is duplicated. The first option is forFirstMonthOnly. As you advised me earlier. And we see that the week starts on Monday, but actually on Thursday. In the second version of forAllMonths. There is no such problem here, but so far one and the same week has been duplicated. Help me please

### .forFirstMonthOnly

```swift
let configurationParameters = ConfigurationParameters(
      startDate: Date() - 3.months,
      endDate: Date() + 8.months,
      numberOfRows: 1,
      generateInDates: .forFirstMonthOnly,
      generateOutDates: .off,
      firstDayOfWeek: .monday,
      hasStrictBoundaries: false
)
```

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/29180327/61451978-6a318f00-a963-11e9-8ad3-9f4d9f86d1bd.gif)

### .forAllMonths

```
let configurationParameters = ConfigurationParameters(
      startDate: Date() - 3.months,
      endDate: Date() + 8.months,
      numberOfRows: 1,
      generateInDates: .forAllMonths,
      generateOutDates: .off,
      firstDayOfWeek: .monday,
      hasStrictBoundaries: false
)
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29180327/61451974-67cf3500-a963-11e9-8c0c-9497cd9a716f.gif)

**Comment by patchthecode** [comment]
The first version is the way to do 99% of week view calendars. So let me debug this one.
Now you said that the problem with it is 
> And we see that the week starts on Monday, but actually on Thursday.

I do not understand what you mean. The language is not in English. So i Do not understand what I am seeing.

**Comment by patchthecode** [comment]
i'll be online today here for 3 hours -> https://gitter.im/patchthecode/JTAppleCalendar
Send a message. If you are online

**Comment by patchthecode** [comment]
I have modified the example on my tutorial website.
Here is how it works.
[MonthToWeek.zip](https://github.com/patchthecode/JTAppleCalendar/files/3414795/MonthToWeek.zip)

Let me know if this works for you

**Comment by patchthecode** [comment]
assuming resolved.
closing issue.
