### ISSUE TITLE
Swift 5 conversion warning still appears in Xcode

### ISSUE THREAD

**Issue by bsweett** [patchthecode/JTAppleCalendar#1095]
**(Required) Version Number:**
8.0.0

## Description
The Swift 5 Conversion warning still appears in Xcode because the podspec defines the swift version as '5' instead of '5.0'. Manually changing the Swift version in the pod project for the JTAppleCalendar target will resolve the problem.

## Steps To Reproduce
1. Run `pod install` on a Swift 5 project. The Pod project will set the Swift Version to 5 instead of 5.0.
2. Notice how the Swift Conversion 5 warning appears in Xcode.

## Expected Behavior
The conversion warning should not appear.

## Additional Context
![Screen Shot 2019-07-18 at 9 47 20 AM](https://user-images.githubusercontent.com/3911202/61462800-48bfab80-a941-11e9-8890-c098429121f0.png)
![Screen Shot 2019-07-18 at 9 47 57 AM](https://user-images.githubusercontent.com/3911202/61462809-4cebc900-a941-11e9-8f96-032c56924def.png)

**Comment by patchthecode** [comment]
Ok.
i'll be fixing al the cocoapod related issues for version 8.0 + over the weekend.

**Comment by patchthecode** [comment]
closing issue.

I'm now maintaining 2 versions of This lib. Version 7+ and version 8+

Latest 7 = 7.1.8 - Will contain bug fixes
Latest 8 = 8.0.1  -- Depracated cocoapods/carthage (use builtin swift package manager for Xcode instead). Will contain bug fixes + new features.

let me know your thoughts.
