### ISSUE TITLE
Tag 8.0.1 issue with Xcode 10.2.1

### ISSUE THREAD

**Issue by yuryks** [patchthecode/JTAppleCalendar#1097]
**(Required) Version Number:**
Current master brunch (tag 8.0.1)

## Description
Could not open project in current stable Xcode version. 

<img width="425" alt="1" src="https://user-images.githubusercontent.com/39466996/61547262-b1974880-aa53-11e9-9dde-70b3aae69782.png">

<img width="423" alt="3" src="https://user-images.githubusercontent.com/39466996/61547627-6d587800-aa54-11e9-9672-84da823cd425.png">

<img width="531" alt="2" src="https://user-images.githubusercontent.com/39466996/61547272-b52acf80-aa53-11e9-919a-aaebd08de91d.png">

## Steps To Reproduce
1) Open in browser: https://github.com/patchthecode/JTAppleCalendar
2) Press Clone or download -> Download ZIP
3) Unzip
4) Try open SampleJTAppleCalendar.xcodeproj

## Expected Behavior
SampleJTAppleCalendar.xcodeproj opens as usual.

**Comment by patchthecode** [comment]
version 8 are made for the new XCode coming out this September.
If you wish to use earlier versions of Xcode, you'll have to use version 7.1.7

**Comment by patchthecode** [comment]
assuming resolved.
If there is anything else you need to know then let me know.
