### ISSUE TITLE
The days of first page of monthDays are not highligted

### ISSUE THREAD

**Issue by Nikoloutsos** [patchthecode/JTAppleCalendar#1098]
**Version i am using:** 
The latest one

**My problem**
I am starting a ViewController, then I make an api call and it returns me some dates. These date must me highligted.

**What I've done**
I have followed the wiki section and i have created a custom cell. 
The dates apart from the first month are showed perfectly but the first month is not.

**The peculiar behavior**
When I swipe left and then right the dates of the first month are highlighted..

**Some pictures**

What I see when I fresh start the ViewController at the first month:
https://prnt.sc/oix479
What I see when I swip left and the right:
https://prnt.sc/oix4ct

I guess this happens because the calendar draw itself faster than my response from the webservice. Is there any way to solve this issue?

**Comment by patchthecode** [comment]
have you tried `calendarView.ReloadData()` after your API returns with the date information?

**Comment by Nikoloutsos** [comment]
Thank you a lot I feel so dump for not finding that useful method.
Have a great day @patchthecode

**Comment by patchthecode** [comment]
Its ok.
havea  good one.
