### ISSUE TITLE
Sample project cannot be opened on Xcode 10.3

### ISSUE THREAD

**Issue by joeljfischer** [patchthecode/JTAppleCalendar#1102]
**(Required) Version Number:** Master branch

## Description
Whenever I try to open the project, I get the following error:

```
The project at '/Users/joel/Downloads/JTAppleCalendar-master/SampleJTAppleCalendar.xcodeproj' cannot be opened because it is in a future Xcode project file format.
```

**Comment by patchthecode** [comment]
Master branch is being prepared to for Xcode 11 (currently in beta).
If you wish to open the sample project, can you try version 7.1.7 tag?

**Comment by joeljfischer** [comment]
I'm currently using 8.0.1 and wanted to play with the sample year view. I can download Xcode 11.

**Comment by patchthecode** [comment]
Alright then.
Keep in mind year view is in progress ok.
It will be fully ready by the time Xcode 11 comes out of Beta. But yes, it currently works :D

**Comment by glennposadas** [comment]
[CalendarSample.zip](https://github.com/patchthecode/JTAppleCalendar/files/3516255/CalendarSample.zip)
For Xcode 10.x users. It uses v8.0 lib.
