### ISSUE TITLE
Multiple months visible Or Show Dates of Single month

### ISSUE THREAD

**Issue by taimur** [patchthecode/JTAppleCalendar#1103]
**(Required) Version Number:**
7.1.7
## Description

I would like to confirm if we can show multiple months in same view and decrease the size between cells. Show the dates of next month in separate section and should not continue in same line.
 
OR

Another option I am trying is to show dates of only 1 month / screen. When user scrolls it will show next / previous month and list dates of that month.

I have attached the calendar design and the one I developed using JTAppleCalendar. 

If someone has implemented it - Kindly share the details. Thanks a lot for your support

Would be very grateful for your kind support.

**Comment by patchthecode** [comment]
> I would like to confirm if we can show multiple months in same view and decrease the size between cells.

Yes his can be done

> Show the dates of next month in separate section and should not continue in same line.

I am not sure what you mean by this. So you have a screenshot?

**Comment by taimur** [comment]
Thanks a lot for the prompt response.
[https://imgur.com/a/KGbHRZP](Ref:Image Dates Visible of single month)

**Comment by patchthecode** [comment]
What yo have there is a vertical scrolling calendar with the next month's header showing on the bottom. Basically you have 2 months on the screen.
This calendar is easy to do with this library.

**Comment by taimur** [comment]
Thanks a lot. I have implemented everything else. In fact thats the screenshot of my app with vertical scrolling calendar in the simulator. I only have to limit the visible dates of current month and then show next month in next section with Month label header on top. Can you give me any hint / clue. Thanks a lot !

**Comment by patchthecode** [comment]
So just to clarify, you WANT your screen to look like the following.

<img width="250" alt="calendararchitecture" src="https://user-images.githubusercontent.com/2439146/62221804-45381580-b380-11e9-8682-a7dfe7e44097.png">

but currently, dates of the 2nd month are shown?

**Comment by taimur** [comment]
Yeah I want my screen to look like the image you shared.

Currently it is like the image below. The dates of next and previous month are visible.

![image](https://user-images.githubusercontent.com/900314/62242960-6256fd80-b3ed-11e9-8f1a-cc11d4887182.png)

**Comment by patchthecode** [comment]
Looks like youre seeing OutDates.
<img width="300" alt="calendararchitecture" src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png">

To get rid of them you can either of 2 things.

1. Make them invisible using the `cellForItem` function
or
2. Do not generate them at all using the `configureCalendar` function.

**Comment by taimur** [comment]
Perfect Thanks a lot. I used the code in the `configureCalendar` . It doesn't show me dates of next month which is exactly what I wanted. But previous month dates are still visible. In case I want to hide it in `cellForItem` - I tried looking for property in `cellState` but cudnt find anythign related to `OutDates`

![Simulator Screen Shot - iPhone X - 2019-08-01 at 08 25 58](https://user-images.githubusercontent.com/900314/62265664-095f8780-b436-11e9-9930-47dd6c4bf3a0.png)

```
let parameters = ConfigurationParameters(startDate: startDate,
                                                     endDate: endDate!,
                                                     numberOfRows: 6,
                                                     generateInDates: .forAllMonths,
                                                     generateOutDates: .off,
                                                     hasStrictBoundaries: true)
```

**Comment by patchthecode** [comment]
you can hide them like.
```swift
if cellState.dateBelongsTo == .followingMonthWithinBoundary {
   cell.isHidden = true
} else {
   cell.isHidden = false
}

**Comment by patchthecode** [comment]
closing issue
