### ISSUE TITLE
Calendar incorrectly starts on wrong date

### ISSUE THREAD

**Issue by ekimia** [patchthecode/JTAppleCalendar#1104]
**(Required) Version Number:** 7.1.7

## Description
Setting the start date to 8/1/2019 is loading dates starting in june (see screenshot)

## Steps To Reproduce
* Set the start date as `2019-08-01 00:00:00 +0000`
* Set the end date to at least a month out

## Expected Behavior
* The first date is the start date - not previous dates

## Additional Context
![image](https://user-images.githubusercontent.com/357513/62334069-f9b66200-b47a-11e9-867b-b3897060e4a0.png)

**Comment by patchthecode** [comment]
can you paste me your `configureCalendar` function?

**Comment by ekimia** [comment]
```
        let endDate = currentDate.dateByAdding(1, .month).date

        return ConfigurationParameters(startDate: currentDate.date, endDate: endDate, numberOfRows: 5, hasStrictBoundaries:true)
```

I think its a timezone issue. Im in california, so if i set the timestamp to `2019-08-01 07:00:00 +0000` all is well.

**Comment by patchthecode** [comment]
closing issue as resolved.
just setup the correct time zone.
You can also configure the Calendar instance that you supply to the library from the `configureCalendar` function.
