### ISSUE TITLE
Cannot find ibCalendarDataSource and ibCalendarDelegate

### ISSUE THREAD

**Issue by MohamedElgharbawy** [patchthecode/JTAppleCalendar#1106]
**(Required) Version Number:** 8.0.0

## Description

Cannot find ibCalendarDataSource and ibCalenarDelegate when following [the tutorial](https://patchthecode.com/jtapplecalendar-home/calendar-from-scratch/)

I followed all the steps, but I can't seem to find it.

[Here is a screenshot of the issue](https://imgur.com/FwEMV0i)

**Comment by patchthecode** [comment]
i guess you found it?
