### ISSUE TITLE
Cell lines are stretched out very far apart

### ISSUE THREAD

**Issue by MohamedElgharbawy** [patchthecode/JTAppleCalendar#1107]
**(Required) Version Number:** 8.0.0

## Description
The cell lines are stretched out significantly if the monthView is tall. Here is a screenshot of the issue.

<img width="250" alt="calendararchitecture" src="https://user-images.githubusercontent.com/2439146/62433206-722e5480-b701-11e9-8383-9e33b13b088c.png">

## Additional Context

I tried adjusting numberOfRows, but the amount of rows in the screen stayed constant, along with their spacing. I am trying to replicate [Apple's official Calendar](https://imgur.com/a/tUC5Wcm), where they have multiple months on the screen at once.

**Comment by MohamedElgharbawy** [comment]
This is my `configureCalendar`:

```swift
extension DeadlineViewController: JTACMonthViewDataSource {
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let calendar = Calendar.current
        let components = calendar.dateComponents([.year, .month, .day], from: Date())
        let startDate = formatter.date(from: String(components.year!) + " " + String(components.month!) + " " + String(components.day!))!
        if(components.month! > 1) {
            let endDate = formatter.date(from: String(components.year!+1) + " " + String(components.month!-1) + " " + String(components.day!))!
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 9)
            
        } else {
            let endDate = formatter.date(from: String(components.year!) + " " + String(components.month!+11) + " " + String(components.day!))!
            
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 9)
 
    }
}

**Comment by MohamedElgharbawy** [comment]
By adding this line, I managed to add more rows to the screen:

`monthView.cellSize = CGFloat(Double(self.view.frame.size.width)/5)`

However, I can't figure out how to reduce the amount of space between the months?

**Comment by patchthecode** [comment]
if you want an example of someone who cloned lots apple calendar functionality, you can check this one for reference --> https://github.com/willard1218/WLAppleCalendar

But for your month space issue, yYou'll have to send me a screenshot of how it looks after you made the adjustment above.

**Comment by MohamedElgharbawy** [comment]
[How would I increase the amount of space between the months?](https://imgur.com/a/YeAEPJG)  This is my current configuration:

```swift
        super.viewDidLoad()
        
        // Position Month View under navigation bar
        monthView.frame = CGRect(x: 0, y: (navigationController?.navigationBar.frame.maxY)!, width: UIScreen.main.bounds.width, height: UIScreen.main.bounds.height - (navigationController?.navigationBar.frame.height)! - UIApplication.shared.statusBarFrame.height)

        // Allows more rows to be displayed at once
        monthView.cellSize = CGFloat(Double(self.view.frame.size.width)/5)
        
    }

    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let calendar = Calendar.current
        let components = calendar.dateComponents([.year, .month, .day], from: Date())
        let startDate = formatter.date(from: String(components.year!) + " " + String(components.month!) + " " + String(components.day!))!
        if(components.month! > 1) {
            let endDate = formatter.date(from: String(components.year!+1) + " " + String(components.month!-1) + " " + String(components.day!))!
            return ConfigurationParameters(startDate: startDate, endDate: endDate, generateOutDates: .off)
            
        } else {
            let endDate = formatter.date(from: String(components.year!) + " " + String(components.month!+11) + " " + String(components.day!))!
            
            return ConfigurationParameters(startDate: startDate, endDate: endDate, generateOutDates: .off)
        }
 
    }```

**Comment by patchthecode** [comment]
1. Thanks for the image of what it looks like. Now can you send me an image of What you want the image to look like? That way i can know how to go from what you have to what you need.

2. The configuration will not help. The config is not the place to setup the layout.
Also, Have you tried the sample app attached to this GitHub? With it you can see exactly what customization you need by playing around with the setting on it.

**Comment by MohamedElgharbawy** [comment]
Imagine an empty row of numbers in between the end of the month and the beginning of the month. That's the amount of space I want in between the months. Right now they are right up against each other, which looks a bit confusing.

**Comment by patchthecode** [comment]
There are a number of ways you can do it.

But one of the easiest is --> Implement a header of height x. An empty blank header.

**Comment by patchthecode** [comment]
closing issue.
Implementing a header will resolve your problem.

**Comment by MohamedElgharbawy** [comment]
How do I implement a header for a vertical view programmatically? Your tutorial is on the old version and is used for horizontal scrolling.
