### ISSUE TITLE
Crash when select date in CalendarView

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#111]
I have this crash log when select date in CalendarView with Horizontal direction and number of rows equals to 1.

` Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete item 11 from section 40 which only contains 7 items before the update'`

<img width="761" alt="2016-08-15 3 16 17" src="https://cloud.githubusercontent.com/assets/324372/17652761/b61ca722-6296-11e6-8671-2036506a0bc9.png">

**Comment by patchthecode** [comment]
Hey thanks for pointing this out.

I have fixed this already on master branch here ->
https://github.com/patchthecode/JTAppleCalendar/issues/107

It will be coming out in the next release. Do you have a requirement to use single row layout right now?

**Comment by mecid** [comment]
Great! Can i use master branch via cocoapods?

**Comment by patchthecode** [comment]
yes you can with the instructions [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#8). However, please know that master branch contains upcoming features and that some things have changed. So please prepare your app for with changes by following the instructions [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Message-to-testers-working-on-master-branch)
