### ISSUE TITLE
TestYearViewViewController cannot be opened on the latest sample project.

### ISSUE THREAD

**Issue by thatnaoki** [patchthecode/JTAppleCalendar#1110]
Version Number: 8.0.1

## Description
I cloned sample project and launched it on my Xcode 11.0 beta 5. When I tapped `YearView Calendar` to open `TestYearViewViewController`, the error below occurred and crashed.

```
Thread 1: signal SIGABRT 
this class is not key value coding-compliant for the key calendarView.
```

The other buttons are just working well.
After that I re-connect all components (such as calendarView, monthLabel, yearLabel) to VC to make sure they connect correctly but the same error occurred.
I still cannot find any other possible reason on IB.

## Steps To Reproduce
I tried few times but it always occurs.

## Expected Behavior
I would like to see how YearView looks like.

**Comment by patchthecode** [comment]
hmm... think think Xcode 11 messed up the sample project.
I just opened and fixed it.
Can you let me know if its working now?

If it is, then you can close this issue. Thanks.

**Comment by thatnaoki** [comment]
Thank you for your quick response!🙏🏼
When I tapped `YearView Calendar` button, the error I got did not occur but, `TestYearViewViewController` showed nothing this time like below.
Do you have any idea for this?
<img src="https://user-images.githubusercontent.com/17538291/62610546-dbe77200-b93e-11e9-9609-997ca93a8265.png" width=200>

In addition, I would like to see the way to solve [this issue](https://github.com/patchthecode/JTAppleCalendar/issues/264).
Actually, this link (https://patchthecode.github.io/CommonQuestions/) is already expired.

**Comment by patchthecode** [comment]
ok. to accomplish this, just decrease the size of the cell.
The smaller the cell size, the more months fit on the screen.
```swift
calendarView.cellSize = x
```

let me check why error is still there on sample project. Just a min

**Comment by patchthecode** [comment]
OK. I forgot to push one file.
Let me know if its fixed now?

**Comment by thatnaoki** [comment]
Thank you very much! Now I can see how YearView works!🙏🏼
And thank you for your explanation about my additional question. I will try!

**Comment by patchthecode** [comment]
@thatnaoki im still messing with the yearView ok.
i am open to suggestions to make it as simple as the month view.

**Comment by thatnaoki** [comment]
@patchthecode Okay! I will consider how we can make YearView more simple🤔
