### ISSUE TITLE
didSelectDate-Method is not working 

### ISSUE THREAD

**Issue by PodalakurPrasanth** [patchthecode/JTAppleCalendar#1111]
**(Required) Version Number:**

**Comment by PodalakurPrasanth** [comment]
i tried many ways but didSelectDate method is not working . please let me know if any solution is there ?

**Comment by patchthecode** [comment]
version?
and do yo have a sample app which reproduces this?

**Comment by PodalakurPrasanth** [comment]
Thank you for given reply i am using latest version of JTAppleCalendar. if you  provide mail id i will send my code. i am looking forward for  your response

**Comment by PodalakurPrasanth** [comment]
JTAppleCalendar Version 8

**Comment by felipeflorencio** [comment]
using swift 5? If yes this is the issue set in your project swift 4.2 and try again

**Comment by patchthecode** [comment]
i suspect he didn't follow the [migration guide](https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/) and forgot to change the name of the functions.

**Comment by PodalakurPrasanth** [comment]
Thank you Patchthecode . it's working fine.
