### ISSUE TITLE
Range selection core data

### ISSUE THREAD

**Issue by Conoize** [patchthecode/JTAppleCalendar#1114]
**(Required) Version Number:**

**Comment by Conoize** [comment]
Hello my problem is that I am not so experienced on swift, already made work the JTAppleCalendar on my App, currently it saves just one given date on core data. I am deciding to change this to a range, but I am having lots of trouble making it work with a for loop and to save on core data. I wanted to know how to print the whole range of days selected on xcode

**Comment by patchthecode** [comment]
calendarView.selectedDates = all the selected dates

**Comment by Conoize** [comment]
Ok I can print the range of days : Found a way of saving each day individually onto the calendar using a for loop as I said before: 

for i in 0..<daysArray.count {
                         let project = NSEntityDescription.insertNewObject(forEntityName: "ProjectCD", into: context)
                        project.setValue(daysArray[i], forKey: "days")
              }
                    do {
                       try managedContext.save()
                   } catch  {
                      print("Could not save. \(error)")
                    }

I truly believe that I am close but when I decide to edit the project (should have the same info as the one that was saved) it shows just the last date of the range only

**Comment by Conoize** [comment]
Ok I can print the range of days : Found a way of saving each day individually onto the calendar using a for loop as I said before:

for i in 0..<daysArray.count {
let project = NSEntityDescription.insertNewObject(forEntityName: "ProjectCD", into: context)
project.setValue(daysArray[i], forKey: "days")
}
do {
try managedContext.save()
} catch {
print("Could not save. (error)")
}

I truly believe that I am close but when I decide to edit the project (should have the same info as the one that was saved) it shows just the last date of the range only. But how could I make the range of selected days appear when I decide to edit the info of the project? 🤔

**Comment by patchthecode** [comment]
> But how could I make the range of selected days appear when I decide to edit the info of the project? 

unclear what you are asking

**Comment by Conoize** [comment]
Ok, User has to specify some information for the project he is intending to create, one of the fields is to select a range of days on which this user is working on the project.

This app has a swipe action for the new project that enables the user to edit the info, so first step is to fetch data from Core Data and “overwrite” the data once again.

So this edit window should show the range of days that User selected before while creating the peoject.


The problem is that the 📆 after creating the range of days. It shows me the last day of the whole range selected, not the range itself man


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patchthecode** [comment]
...so basically all you are asking is how to select a range of dates when a user taps a button?

**Comment by Conoize** [comment]
Mmm not exactly, all I am asking is that the calendar to show the whole range of days while on the edition window, as I chose on the projects window before

I dont know if that is a core data problem or a calendar related problem, either way I know that should be the correct approach for the user (he sees the same range of days on the project window as well as the edit window).

Note: Im not an expert on ios developement, this is just a bold move of mine...😞


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patchthecode** [comment]
See, what i am trying to get you to do is break down what exactly you want.

> all I am asking is that the calendar to show the whole range of days

What does this mean? Does this mean that you want the calendar to display a number of selected days right? Or does this mean that you want want some label (other than the calendar) to display this? You need to be clear, because right now you are a little vague.

> while on the edition window, as I chose on the projects window before

So basically, on the screen, you'll tap some button called "EDIT", and then it navigates to a next screen which should display a range of dates. 


Where are the dates saved? In the Database
Where do you want the dates displayed?

**Comment by Conoize** [comment]
The range of dates are saved onto core data, and I want the dates (all) to be displayed on the edit window , right now I only get to display just one date (last date of the dates selected)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patchthecode** [comment]
Ok. Since you want dates which are saved in core data to be displayed on a window (and not on the calendar itself), then your question relates entirely to core data. I'll have to tell you that i know nothing about core data; it is not my expertise.

**Comment by Conoize** [comment]
Yeah I thought so too, all right thanks for the info!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patchthecode** [comment]
cool. Will close this issue then as the original one was answered.
