### ISSUE TITLE
Stylizing calendar issue

### ISSUE THREAD

**Issue by Wh1rlw1nd** [patchthecode/JTAppleCalendar#1116]
Hi,

I am trying to change the text color of dates in calendar, as well as the background color (circular view around current date) but I am actually seeing any property suitable for something like this. Am I missing something ?

Kind regards

**Comment by patchthecode** [comment]
Have you taken a look at the tutorials on patchthecode.com ?

**Comment by patchthecode** [comment]
closing. assuming resolved.
