### ISSUE TITLE
Fatal error: Index out of range

### ISSUE THREAD

**Issue by ortys** [patchthecode/JTAppleCalendar#1118]
**(Required) Version Number:** 7.1.6

## Description
I have a calendar into a view. It was ok yesterday but today if I enter into the view with the calendar the app crash. The error is: Fatal error: index out of range

## Steps To Reproduce
Code is:
```swift  
 var giornodioggi = ""
 override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        self.dataSource = self
        if let firstViewController = orderedViewControllers.first{
            setViewControllers([firstViewController], direction: .forward, animated: true, completion: nil)
        }
        
        //metodipagecontrol
        self.delegate = self
        configurePageControl()
        
        let customDateFormatter = DateFormatter()
        giornodioggi = customDateFormatter.weekdaySymbols[Calendar.current.component(.weekday, from: Date())]
```

## Additional Context

**Comment by patchthecode** [comment]
is this happening on 7.1.7?

**Comment by patchthecode** [comment]
also, can you let me know:
1. on which line it is crashing
2. can you paste the error log

**Comment by patchthecode** [comment]
Closing issue until user responds.
Also, please update to 7.1.8

Will re-open issue after you respond. Until then i'll assume this was resolved.

**Comment by ortys** [comment]
Problem solved with this:
`let index = Calendar.current.component(.weekday, from: Date()) // this returns an Int
  giornodioggi = Calendar.current.weekdaySymbols[index - 1] // subtract 1 since the index starts at 1
        `

**Comment by patchthecode** [comment]
awesome.
