### ISSUE TITLE
Fatal error: Index out of bounds

### ISSUE THREAD

**Issue by vanyok3000** [patchthecode/JTAppleCalendar#1119]
**(Required) Version Number:** 7.1

## Description
Calendar crashes when I try to show days from April to August 2019 using Japanese calendar.
This happens, because April, 2019 is the 31st year of the Heisei era, but August, 2019 is already the 1st year of the Reiwa era.

## Steps To Reproduce
1. Go to device settings and select Japanese calendar.
2. In app's calendar select months from April, 2019 to May, 2019

## Expected Behavior
Calendar should show April, 0031 and May, 0001
## Additional Context

**Comment by patchthecode** [comment]
please update to 7.1.8 and let me know if fixed

**Comment by vanyok3000** [comment]
@patchthecode It's still crashes.

**Comment by vanyok3000** [comment]
@patchthecode 7.1.8 requires 10.0 deployment target. We can't update because we still need to support iOS 9.0

**Comment by patchthecode** [comment]
man... you still support iOS 9? 
I decided to drop support for 9 because, well... who is still using that?
Ok, let me re-think and see if I can make a fix.

**Comment by patchthecode** [comment]
Do you have a deadline when you will stop supporting version 9?

**Comment by patchthecode** [comment]
will close this issue. 
I cannot support iOS 9 because the support range will too broad 9, 10, 11, 12, 13.

But if you need this library to support 9, you can fork this library and modify the code portions that limits OS 9. It should not be many lines of code.

**Comment by patchthecode** [comment]
Maybe if someone can help me support the older versions, the help would be appreciated.
