### ISSUE TITLE
Unexpectedly found nil exception while selecting a cell

### ISSUE THREAD

**Issue by shayanjalil** [patchthecode/JTAppleCalendar#112]
Hello,

I love this calendar, it's very customizable and super easy to use and understand.

I'm facing one issue though, when I select a cell, I get this exception 'unexpectedly found nil while unwrapping an Optional value'. This exception is thrown before the 'didSelectDate' delegate method is called.

The cell selection works fine when I do it on the initial month that is displayed. But whenever I swipe to another month and then make a selection, the above exception is thrown.

Here is how I set up the calendar

`self.calendarView.dataSource = self`
`self.calendarView.delegate = self`
`self.calendarView.registerCellViewXib(fileName: "CalendarCellView")`
`self.calendarView.direction = .Vertical`
`self.calendarView.cellInset = CGPoint(x: 0, y: 0)`
`self.calendarView.allowsMultipleSelection = false`
`calendarView.reloadData() {
            self.calendarView.selectDates([self.dateToday], triggerSelectionDelegate: false)
            self.calendarView.scrollToDate(self.dateToday, triggerScrollToDateDelegate: false, animateScroll: false, preferredScrollPosition:UICollectionViewScrollPosition.Top, completionHandler: nil)
        }`

These are my Data Source and Delegate Methods

`// MARK: - Calendar Data Source
    
    func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar)
    {
        let formatter = NSDateHelper.getDateFormatterWithFormat("dd/mm/yyyy")
        
        let firstDate = formatter.dateFromString("01/01/2003")
        let secondDate = formatter.dateFromString("01/12/2020")
        let numberOfRows = 4
        let calendar = NSCalendar.currentCalendar()
        
        return (firstDate!, secondDate!, numberOfRows, calendar)
    }
    
    // MARK: - Calendar Delegate
    
    func calendar(calendar: JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date: NSDate, cellState: CellState)
    {
        (cell as! CalendarCellView).setupCellBeforeDisplay(cellState, date: date)
    }
    
    func calendar(calendar: JTAppleCalendarView, isAboutToResetCell cell: JTAppleDayCellView)
    {
        (cell as! CalendarCellView).backgroundColor = helper.getColorForCalendarCellNonSelected()
    }
    
    func calendar(calendar: JTAppleCalendarView, didScrollToDateSegmentStartingWithdate startDate: NSDate, endingWithDate endDate: NSDate)
    {
        let formatter = NSDateHelper.getDateFormatterWithFormat("MMM yyyy")
        let currentMonth = formatter.stringFromDate(startDate)
        
        self.monthTitleLabel.text = currentMonth
    }

    func calendar(calendar: JTAppleCalendarView, canSelectDate date: NSDate, cell: JTAppleDayCellView, cellState: CellState) -> Bool
    {
        return true
    }
    
    func calendar(calendar: JTAppleCalendarView, canDeselectDate date: NSDate, cell: JTAppleDayCellView, cellState: CellState) -> Bool
    {
        return true
    }
    
    func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState)
    {
        print("")
        (cell as! CalendarCellView).setSelected(date, state: cellState)
    }
    
    func calendar(calendar: JTAppleCalendarView, didDeselectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState)
    {
        (cell as! CalendarCellView).deselectCell()
    }`

I created a simple .xib for my dateCell and just placed a single label in it.

Can you please tell me what is causing the exception to be thrown. I can't figure it out. 

I'm using swift 2.2 and Xcode 7.3.1 and JTAppleCalendar verion 4.1.4

**Comment by shayanjalil** [comment]
I'm sorry for being in a hurry. I found out what I was doing wrong. In the collection view didDeselectItem delegate method it is mentioned that if the month view is switched, the cell may be nil. That's why I was getting the exception.

**Comment by patchthecode** [comment]
Great. Glad you like the lib. 
And awesome you found the issue  😄

**Comment by IfyNdu** [comment]
lol sorry for being a pain but how exactly did you sort this out? i'm having the exact same issue

**Comment by patchthecode** [comment]
@IfyNdu in which version are you experiencing this issue?
6.0.0 ?

And on which line of code are you getting this
