### ISSUE TITLE
Setting `allowsRangedSelection` to false causes unexpected selection behaviour

### ISSUE THREAD

**Issue by adam-alphero** [patchthecode/JTAppleCalendar#1122]
**(Required) Version Number:**
v8.0.0 (Present in 8.0.1 and master branch also)

## Description
When `JTACMonthView.allowsRangedSelection` is set to false (its default) its didSet sets the collection view property `allowsMultipleSelection` to true, which shouldn't and it therefore causes unexpected behaviour.

## Steps To Reproduce
When setting up the calendar do: `calendarView.allowsRangedSelection = false`

## Expected Behavior
That setting `allowsRangedSelection` to false would not allow ranged selection

## Additional Context

**Comment by patchthecode** [comment]
fixed on master branch

**Comment by Accenture-Diksha** [comment]
This issue still persists in version 8.0.2.

**Comment by patchthecode** [comment]
can you try master branch?
