### ISSUE TITLE
Carthage will not build last version (8.0.1)

### ISSUE THREAD

**Issue by Dean151** [patchthecode/JTAppleCalendar#1125]
**(Required) Version Number:** 8.0.1

## Description
Carthage do not find shared framework to build

## Steps To Reproduce
```
github "patchthecode/JTAppleCalendar" == 8.0.1 >> Cartfile
carthage update --platform iOS
```
Output:
```
*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/patchthecode/JTAppleCalendar/issues/new
```

## Expected Behavior
JTAppleCalendar should build with carthage

## Additional Context
I do not use beta version of Xcode, and I have the final version of carthage.
I run Catalina tough, but I don't think it's related ;-)

**Comment by dbmrq** [comment]
+1

**Comment by patchthecode** [comment]
yea. i broke the build and didnt know how to fix it.
So i got some help form this request -> https://github.com/patchthecode/JTAppleCalendar/pull/1142

I will look at it this afternoon after work

**Comment by patchthecode** [comment]
merged.
carthage should be working again.

If it is still broken let me know.
If it works, then have a good one.

**Comment by dbmrq** [comment]
Perfect, thank you! 🥳
