### ISSUE TITLE
Error IOS 13 Xcode 11 beta 6

### ISSUE THREAD

**Issue by johnlietzke** [patchthecode/JTAppleCalendar#1129]
v 8.0.0

## Description
Calendar layout is not of type JTAppleCalendarMonthLayout.
There was an error in this code section. Please contact the developer on GitHub
Assertion failed: file /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/JTAppleCalendar/Sources/JTAppleCalendar/JTACMonthActionFunctions.swift, line 43
2019-09-08 10:49:41.795812-0700 Transit[23704:811842] Assertion failed: file /Users/johnlietzke/Library/Mobile Documents/com~apple~CloudDocs/Xcode Projects/Transit/Pods/JTAppleCalendar/Sources/JTAppleCalendar/JTACMonthActionFunctions.swift, line 43

## Steps To Reproduce
Index and run
## Expected Behavior
Calendar populates

**Comment by patchthecode** [comment]
how did you create your calendar. via code? or storyboard.

**Comment by johnlietzke** [comment]
Storyboard.  It compiles correctly but then crashes with the error when the calendar is opened in the app.  I updated my code and class for version 8.

**Comment by johnlietzke** [comment]
I was able to get rid of the error and get calendars to work by disintegrating and cleaning all pods then reinstalling them.  I don’t have an explanation but it worked.

Thanks for the response.

John

**Comment by patchthecode** [comment]
cool.
I'll close this issue then. I'll keep this in mind for the next person that has this problem.
