### ISSUE TITLE
Adding day tags to header (MTWTFSS)

### ISSUE THREAD

**Issue by danielhaan** [patchthecode/JTAppleCalendar#113]
Hello!

I have been looking for a propper calendar implementation for swift for a while, and I was very pleased when I stumbled on this framework.

I have been able to set it up almost as I desire, however, I am having an issue figuring out how to add the typical M T W T F S S letters at the top of each column.

Just like the guy who did the purple calendar.

I could easily just place the labels until it fits, but I want to make sure, that it works for different screen sizes.

Any help is appreciated! Thank you very much!

**Comment by patchthecode** [comment]
ok will check this out in the morning.

**Comment by patchthecode** [comment]
The calendar does not provide headers. You will need to do this your self. This means you can customize it to your linking.

If you want the size of the labels to match the size of the calendar for any device size, then why not use the same method you used you have used for the calendar?
I assume you might be using auto layout constraints?

In the example code attached to this project, I have a calendar there with 7 labels added inside a simple stackview. The Day labels stretch correct to any device size. If you need more help on this let me know.

**Comment by danielhaan** [comment]
Thank you!
