### ISSUE TITLE
How can I find the ibCalendarDataSource and ibCalendarDelegate?

### ISSUE THREAD

**Issue by iamcastlemin** [patchthecode/JTAppleCalendar#1130]
**(Required) Version Number:** 8.0.1

## Description
I am currently following the tutorial, but I cannot find the ib Calendar Data Source and ib Calendar Delegate to connect to the View Controller subclass. My case is very similar to 

https://github.com/patchthecode/JTAppleCalendar/issues/1106

but there wasn't an answer to it since the person who asked closed the thread. Can anybody help me out with this issue?

**Comment by iamcastlemin** [comment]
> * Did you remember to set the class as JTACMonthView
> * Did you remember to set the module as JTAppleCalendar? (XCode sometimes blank out this field)

It worked! Your the best Jay :)

**Comment by patchthecode** [comment]
awesome. closing this issue.

**Comment by fury21** [comment]
Hi!
Pls rename class and module names in tutorial.

=====
Calendar from scratch.
Using story board

1. Drag a UICollectionView unto the screen. Change its class and module to **JTAppleCalendarView** and **JTAppleCalendar** respectively.

Correctly set both the height and width constraints. Constraints are needed for the library to determine cell size.
=====

https://patchthecode.com/jtapplecalendar-home/calendar-from-scratch/

**Comment by patchthecode** [comment]
@fury21 the tutorials are for version 7.

I have not done a tutorial for version 8. Because of lack of time. I am swamped with projects.
But i will get to it eventually
