### ISSUE TITLE
Unable to select DateCells

### ISSUE THREAD

**Issue by GodriXx** [patchthecode/JTAppleCalendar#1131]
**Version Number: 7.1.8**

## Description

Unable to select some cells after selecting a range and scroll between months

## Steps To Reproduce
* Select a range
* try to extend that range (implemented in my code) OR scroll to another month and try to select new range
* Some cells are not selectable, and didSelectDate is not triggered at all, some other cells in the same month are fine.

## Expected Behavior

* Simply DateCell selected/ trigger `didSelectDate`

## Additional Context

I've tried disabling `allowsMultipleSelection` and `isRangeSelectionUsed`, this allowed me to do single date selection without issues, enabling those parameters will cause those bugs

I've added lots of code inspired of your sample range selection; the calendar now is able to select one single range, and edit each extremity

below you can see how selection is done, the more I go through pages, the more I'm unable to select cells.

![ScreenRecording_09-13-2019 14-07-20 2019-09-13 14_50_44](https://user-images.githubusercontent.com/6039072/64863797-fe536600-d635-11e9-9718-358a48cd3401.gif)

I already implemented `shouldSelectDate`, and it's working as intended, the problem is none of the delegate methods are called, already debugged them, this happening for some cells as I said

```
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
        let startDate = Date().lastTwelveMonth.startOfMonth
        let endDate = Date()
        if startDate < date && endDate > date {
            return true
        }
        return false
    }
```

I've already inspected answers like in this thread, same issue as him https://github.com/patchthecode/JTAppleCalendar/issues/1109#issue-477593930

**Comment by patchthecode** [comment]
taking a look.
I'll try to reproduce this. Will keep you posted

**Comment by patchthecode** [comment]
Do you have a sample app demonstrating this issue? It would help me a lot.

**Comment by GodriXx** [comment]
Yes oc, I will try to isolate the code and send it to you in max 24h

**Comment by GodriXx** [comment]
Here is my sample code,
Keep in mind that the calendar should select only **one single range**, allow user to change start and end date by selecting first **From** or **To** cells at the bottom, then select new start or end date, my sample implements already those features
Thanks for the library and your valuable help :)
[NPSCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/3621403/NPSCalendar.zip)

**Comment by patchthecode** [comment]
I took a look at your code.
I think your longPress gesture that is attached to the calendar is eating up all the taps.

You can try this to confirm ->
Try selecting on your calendar. And when selection does not work any more like you have shown, go to this function and put a break point inside it

```swift
@objc func didStartRangeSelecting(gesture: UILongPressGestureRecognizer) {
```

then head back to the calendar date that is not being selected. Then do a Longpress gensture.
You will see that this function gets called.
I think the longpress gesture is consuming the taps before it gets to the calendar.

Let me know.

**Comment by GodriXx** [comment]
> I took a look at your code.
> I think your longPress gesture that is attached to the calendar is eating up all the taps.
> 
> You can try this to confirm ->
> Try selecting on your calendar. And when selection does not work any more like you have shown, go to this function and put a break point inside it
> 
> ```swift
> @objc func didStartRangeSelecting(gesture: UILongPressGestureRecognizer) {
> ```
> 
> then head back to the calendar date that is not being selected. Then do a Longpress gensture.
> You will see that this function gets called.
> I think the longpress gesture is consuming the taps before it gets to the calendar.
> 
> Let me know.

Thanks for your quick reply,

I already got the same idea and tested the longPress, also removed it completely, same issue,
the longPress is not depending of the standard collectionView actions, I've tested it again today as you described it

However, when I removed the longPress, and tried to select cells with issue, the action is retained by the scroll of the collection or the scene

**Comment by patchthecode** [comment]
ok, i'll now start investigating the didSelect function you wrote.
On first glance of it, it looks more complex than it needs to be (im not sure yet, but it appear so).

Just to confirm, you are just trying to a regular 2 tap range selection right?
--> that is, select 1st date, select 2nd date, and then all the dates in the middle should be selected?

**Comment by patchthecode** [comment]
Ok. I am very puzzled by this bug.
Still investigating.

I have stripped every thing out of your project. Its like UICollectionView refuses to receive any more taps. Checking on this some more.

**Comment by GodriXx** [comment]
> ok, i'll now start investigating the didSelect function you wrote.
> On first glance of it, it looks more complex than it needs to be (im not sure yet, but it appear so).
> 
> Just to confirm, you are just trying to a regular 2 tap range selection right?
> --> that is, select 1st date, select 2nd date, and then all the dates in the middle should be selected?

Yes you are right



> Ok. I am very puzzled by this bug.
> Still investigating.
> 
> I have stripped every thing out of your project. Its like UICollectionView refuses to receive any more taps. Checking on this some more.

I even used the Debug View Hierarchy, thought maybe some invisible views are appearing above the calendar, maybe my UIView on my DateCell is causing this issue, but no, everything seems OK

**Comment by patchthecode** [comment]
The puzzling thing is. I do not do anything weird under the hood.
It is just a barebones UICollectionView.
I am still investigating this

**Comment by GodriXx** [comment]
> The puzzling thing is. I do not do anything weird under the hood.
> It is just a barebones UICollectionView.
> I am still investigating this

It looks like the calendar is loosing delegate configuration, which I already investigated, but, do you have any code in the library that cancel it in any time ?

**Comment by patchthecode** [comment]
I gave up trying to debug your code.
It had too many Dispatch.async  too hard to track.

re-wrote the code to something simpler.
Is this bug still happening in this code?

[NPSCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/3626489/NPSCalendar.zip)

**Comment by GodriXx** [comment]
> I gave up trying to debug your code.
> It had too many Dispatch.async too hard to track.
> 
> re-wrote the code to something simpler.
> Is this bug still happening in this code?
> 
> [NPSCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/3626489/NPSCalendar.zip)
> 
> If it is resolved, then i suspect it is something happening in all those closures.

For a single range selection, it's working, but I will add the missing code to update cells on the bottom, and the possibility to edit beginning and ending of the range on the fly, and will update you,

As I said, this problem is occurring when I try to change the extremity of the range

**Comment by patchthecode** [comment]
Thanks. Will wait.

**Comment by GodriXx** [comment]
Hello **patchthecode**
I can confirm now that this issue is gone, I've added missing behavior to this sample, still needs more work to complete a total functioning app, now I'm able to :
- select single range
- select which extremity to edit (**From** or **To**) and stretch the range or reduce it

Now, this will takes me a little more time to finish it, due to customer tasks priorities, but I will post here the final sample for whom needs it

It turned out that I've abused of using thread management, Dispatch blocks, however, selecting a big range (1 year) now takes up to 2 seconds, but no memory increasing

**Comment by patchthecode** [comment]
Yea, i wish i knew where the bug was happening though, but asyc closures are hard to debug.
Glad you got it working.

In terms of big range selection. I guess your comment here https://github.com/patchthecode/JTAppleCalendar/issues/787#issuecomment-531171020 didnt work?

**Comment by patchthecode** [comment]
closing.
If big range selection is another issue, then lets tracke it on #787

**Comment by GodriXx** [comment]
> Yea, i wish i knew where the bug was happening though, but asyc closures are hard to debug.
> Glad you got it working.
> 
> In terms of big range selection. I guess your comment here [#787 (comment)](https://github.com/patchthecode/JTAppleCalendar/issues/787#issuecomment-531171020) didnt work?

Hello patchthecode,

My comment in the other thread was a part of the solution, second part was to block certain code to be excuted by filtering it with `.userInitiated`, on of your answers in another thread helped me discovering it, 
keeping triggering delegate method for `didSelectCell` will create a big memory consumption that can easily rise to over 200Mb (350Mb on simulator from 40Mb) for a one year range selection.
