### ISSUE TITLE
Missing Package Product

### ISSUE THREAD

**Issue by jigneshKCTS** [patchthecode/JTAppleCalendar#1133]
I Simply Downloaded the librabary and pbx file changed the compatibility version to support the xcode 10+

Got following error

Showing All Messages
:-1: Missing package product 'JTAppleCalendar', please fix package resolution errors before building (in target 'SampleJTAppleCalendar')

**Comment by patchthecode** [comment]
.....
1. What version?
2. downloaded using Cocoapods? /Carthage? / SwiftPackageManager? / Manually?

**Comment by patchthecode** [comment]
I will close this issue.
I do not think you followed the installation mentioned [here](https://patchthecode.com/jtapplecalendar-home/installation/).

You can install via Cocoapos, Carthage, or SwiftPackage manager. These 3 makes installation easy for you. 
It sounds like you manually dragged the files into your project. If you are going to manually install this lib into your project, it is expected that you are used to that sort of thing. If you are doing it manually as i suspect, there you do not have to import a library as you are doing. Again, a manual install should be done if you are used to that sort of thing.
