### ISSUE TITLE
Have ideas?

### ISSUE THREAD

**Issue by fuyunmanbu** [patchthecode/JTAppleCalendar#1136]
![Snip20190920_1](https://user-images.githubusercontent.com/16368126/65288923-3f3e0400-db7b-11e9-9d57-9d91466b0236.png)

**Comment by patchthecode** [comment]
ideas on what?

**Comment by fuyunmanbu** [comment]
There are no good programs for the events in the picture.

**Comment by patchthecode** [comment]
I do not understand what you are asking.
Are you asking me if JTAppleClanedar can make a calendar like the picture above?

**Comment by fuyunmanbu** [comment]
yes

**Comment by patchthecode** [comment]
yes, JTAppleCalendar can create it.

**Comment by fuyunmanbu** [comment]
What are the ideas, what should I do?

**Comment by patchthecode** [comment]
You can do many things.
What specifically do you want to do?

**Comment by fuyunmanbu** [comment]
I have seen it, but it seems that I can't customize the collectionViewlayout

**Comment by patchthecode** [comment]
You need to be specific.
Customize the layout to do what?

**Comment by fuyunmanbu** [comment]
Put a head view on each row of dates to display multiple events

**Comment by patchthecode** [comment]
this shows you an example of how to create events.
https://patchthecode.com/jtapplecalendar-home/adding-events/

That example adds only one event.
You can just change it to add multiple events.

**Comment by fuyunmanbu** [comment]
The content of this event needs to be displayed on multiple cells. It seems that the custom cell cannot be implemented.
![Snip20190920_2](https://user-images.githubusercontent.com/16368126/65313577-2ce9b780-dbc7-11e9-9cf1-bb479b833a79.png)

**Comment by patchthecode** [comment]
Ok. You are correct.
I thought that this view was simply multiple Yellow cells spanned across 7th, 8th, 9th, 10th.
But I see now that that the chinese(?) letters are spanning multiple cells.

The only response to you I have is this.
Do you know how to accomplish this on a regular UICollectionView? --> To have a view that spans multiple cells? If you know how to do this with a UICollectionView, then you should also be able to accomplish this with this library.

let me know.

**Comment by fuyunmanbu** [comment]
You have a good implementation idea, I don't have a good idea at present.

**Comment by patchthecode** [comment]
Same here. I do not know how to do this on a normal UICollectionView.
But if you ever find out, let me know and I will implement it into this library.
Will close this issue for now ok.

**Comment by fuyunmanbu** [comment]
Look at YMCalendar, you can use the custom UICollectionReusableView implementation, including custom UICollectionViewLayout, but JTAppleCalendar can not customize UICollectionViewLayout, I hope you can add this function as soon as possible

**Comment by patchthecode** [comment]
Whrre does https://github.com/matsune/YMCalendar  implement multiple spanned events? I do not see it in any of their images.

**Comment by fuyunmanbu** [comment]
![Snip20190920_2](https://user-images.githubusercontent.com/16368126/65318471-39bed900-dbd0-11e9-9d46-9c81bb15dc4b.png)
I didn't look at the details of the implementation, but I observed that his implementation is probably like this.

**Comment by patchthecode** [comment]
Can you share the link of that screen shot? I am not seeing it on his repository

**Comment by patchthecode** [comment]
Also i will say one thing, The text is not crossing over multiple cells, therefore I still think he has not done it. But send me the link for that screenshot, i will take a look.

**Comment by fuyunmanbu** [comment]
This is the appropriate adjustment I downloaded and you can adjust the scope of the event here.
![Snip20190920_6](https://user-images.githubusercontent.com/16368126/65319183-a090c200-dbd1-11e9-9bec-2b9c11d0143c.png)
