### ISSUE TITLE
how can I  limit date  to detail date ? for example , I only  want show Date of end month before 2019-9-20, not all month

### ISSUE THREAD

**Issue by Tonigt** [patchthecode/JTAppleCalendar#1137]
```swift
func endOfMonth(for date: Date) -> Date? {
        guard
            let comp = dateFormatterComponents(from: date),
            let day = self.range(of: .day, in: .month, for: date)?.count,
            let retVal = Calendar.formatter.date(from: "\(comp.year) \(comp.month) \(day)") else {
                return nil
        }
        return retVal
    }
```

**Comment by patchthecode** [comment]
in the `cellForItemAt` function

```
func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
   let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
   // if date > 2019-9-20 {
   //     myCustomCell.isHidden = true
   // } else {
   //    myCustomCell.isHidden = true
   // }
   return myCustomCell
}
```

**Comment by Tonigt** [comment]
> in the `cellForItemAt` function
> 
> ```swift
> func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
>    let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
>    // if date > 2019-9-20 {
>    //     myCustomCell.isHidden = true
>    // } else {
>    //    myCustomCell.isHidden = true
>    // }
>    return myCustomCell
> }
> ```

thanks ，very much ，but this way is only treat the symptoms but not the root cause

**Comment by patchthecode** [comment]
If you are looking for the Library to stop generating cells at the exact endDate you set, then this library was not built like this.

Currently, it begins at the start of a month, and ends at the end of a month.
What you are asking for is a update to the library.
This is already asked for by other people. It will be done once I get the time.

**Comment by Tonigt** [comment]
Looking forward to the arrival of this version, and thank you for your contribution




------------------ 原始邮件 ------------------
发件人: "JTAppleCalendar"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 下午5:23
收件人: "patchthecode/JTAppleCalendar"<JTAppleCalendar@noreply.github.com>; 
抄送: "lonely"<1984701289@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [patchthecode/JTAppleCalendar] how can I  limit date  to detaildate ? for example , I only  want show Date of end month before 2019-9-20, notall month (#1137)




If you are looking for the Library to stop generating cells at the exact endDate you set, then this library was not built like this.
 
Currently, it begins at the start of a month, and ends at the end of a month.
 What you are asking for is a update to the library.
 This is already asked for by other people. It will be done once I get the time.
