### ISSUE TITLE
Calendar scrolls to start date when resizing it's height

### ISSUE THREAD

**Issue by vaibhav-nickelfox** [patchthecode/JTAppleCalendar#1138]
**(Required) Version Number:** 
8.0.0

## Description
JTAppleCalendar is in UITableViewCell. For scenarios when there are only 5 weeks in month, I require some specific height of calendar and for 6 weeks we require some other height. I've tried the way given in example i.e. update calendarView frame then reload calendar and update height constraint of collection view. Neither of them helped. I tried to resize the height of tableView Cell. But when used tableView.begainUpdates() and tableView.endUpdates() calendar scrolls to start date.

## Steps To Reproduce
Update height of tableView cell in which JTAppleCalendar is there. when resizing using tableView.begainUpdates() and tableView.endUpdates() calendar scrolls to start date passed in configuration.

**Comment by vaibhav-nickelfox** [comment]
@patchthecode any help?

**Comment by patchthecode** [comment]
sorry. Missed this.
Is there any chance that the tableView cell is being re-drawn?

Can you paste the code you used for the tableview cell resize?

**Comment by vaibhav-nickelfox** [comment]
No there are no chances of re-drawn of tableView cell.

This is the delegate method which triggers begainUpdates() and endUpdates()
`    func updateCalenderDetails(month: CalendarMonth, rowsCount: Int) {
        self.monthLabel.text = month.monthString
        if self.calendarRowCounts != rowsCount {
            self.calendarRowCounts = rowsCount
            self.tableView.beginUpdates()
            self.tableView.endUpdates()
        }
    }
`

This is how I'm resizing tableView cells. There are only two cells. First is having JTAppleCalendar and second us having a button of height 158

`func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        let cellModel = self.presenter.cellModel(at: indexPath)
        switch cellModel {
        case _ as CalendarTableCellModel:
            let height = self.calendarRowCounts == 6 ? extendedCalenderHeight : shortCalenderHeight
            return CGFloat(height)
        case _ as TakeTestButtonTableCellModel:
            return takeTestButtonHeight
        default: return 0.0
        }
    }`

**Comment by patchthecode** [comment]
OK sorry i misread your original question.
Here is what is happening.

Any thing that you do to the calendar that changes its layout **will** cause it to be redrawn.
In your case, you are resizing it. Therefore, I have to redraw the cells. If i redraw the cells, then the oldLayout goes away. This causes the calendar to reset back to first date.

The proper way to prevent this from happening is to just reload the calendar with an anchorDate.
For example this
```swift
    // [code which resizes the calendar]
    let date = calendarView.visibleDates().monthDates.first!.date // Grab a date you want to snap to after a reload
    calendarView.reloadData(withAnchor: date) // reload the calendar with this as the anchor date
```

Let me know if this works for you.

**Comment by vaibhav-nickelfox** [comment]
It worked. Thank you so much. I really appreciate your help. You're champ. 👍🏻

**Comment by patchthecode** [comment]
awesome.
