### ISSUE TITLE
Can I have two columns per day?

### ISSUE THREAD

**Issue by zenhouse** [patchthecode/JTAppleCalendar#1139]
**(Required) Version Number:**
8.0.1

## Description
I'm looking to make a calendar app that can display events in 2 columns per day in month mode and export it to a pdf file. Is this possible?

**Comment by patchthecode** [comment]
show me a screen shot or some image of what you want it to look like.
i cant visualize what you just said.

**Comment by zenhouse** [comment]
I have attached an example. I want to make a task based calendar that has two columns per day as shown in the attachment.Each column would have a column title and list of task.



Hopefully this is possible.

Thanks,
John

**Comment by patchthecode** [comment]
I do not know where you have sent this attachment. But I am not seeing it on github .
Try sending it here directly? It doesnt look like sending it by email works

**Comment by zenhouse** [comment]
[IMG_7844.HEIC.pdf](https://github.com/patchthecode/JTAppleCalendar/files/3639270/IMG_7844.HEIC.pdf)

**Comment by zenhouse** [comment]
Ok just attached it to github.

**Comment by patchthecode** [comment]
<img width="287" alt="Screen Shot 2019-09-22 at 8 32 07 AM" src="https://user-images.githubusercontent.com/2439146/65387250-79daa480-dd13-11e9-8a3b-2651279c20f7.png">

Yes this is possible.
This calendar cell is a UICollectionView cell and you have full control of it. Therefore you can design pretty much anything you can do with a regular UICollectionViewCell --> Basically, you can design anything you want.
