### ISSUE TITLE
Cells displaying faulty information - "Today" cell is shown everywhere seemingly randomly

### ISSUE THREAD

**Issue by danielhaan** [patchthecode/JTAppleCalendar#114]
Hello. I found another problem, which may be a bug with the way cells are setup before being displayed.

I have followed your example code, and in my Cell class I compare the cell's date with today, and if they are the same day, I set the label to be red, and add an additional label with the text "today" for testing purposes.

![screen shot 2016-08-21 at 01 12 00](https://cloud.githubusercontent.com/assets/12447089/17834354/ed663a40-673c-11e6-8ea1-7d0f880a491a.png)

However, when I run the application, several cells are shown with this modified look. When set a breakpoint inside the "isToday" if statement, it only stops the execution once. (Once per time the current month is swiped to as well). As you can see in the following screenshots, a lot of "random" cells also have the "today" label, but their font isn't changed to red?

![img_5090](https://cloud.githubusercontent.com/assets/12447089/17834361/3108119c-673d-11e6-9e0c-f509236683e0.PNG)
![img_5089](https://cloud.githubusercontent.com/assets/12447089/17834360/310711de-673d-11e6-9da7-adceeae3e3da.PNG)

Here is the code for the date comparison and the xib for the cell, in case it proves usefull.

![screen shot 2016-08-21 at 01 13 09](https://cloud.githubusercontent.com/assets/12447089/17834363/7ac57ca2-673d-11e6-910d-9062094111ba.png)
![screen shot 2016-08-21 at 01 12 27](https://cloud.githubusercontent.com/assets/12447089/17834364/7ac9a49e-673d-11e6-8bb4-0c0282529ffb.png)

I want to thank you many times for the help, I have starred your project and will follow your github account as appreciation!

Thank you!

**Comment by danielhaan** [comment]
Ok, I just tested some more, and the date comparison (the uncommented one) was accepting arbitrary dates with a 24 hour range in between, so I reverted to the commented one. It is however the standard NSCalendar method for comparing 2 dates, so I assume it is working as intended :)

**Comment by patchthecode** [comment]
ok. will check this out in the morning.

**Comment by patchthecode** [comment]
I do not think your problem is in the date comparison function.
I do not know your code, but I suspect that you are doing something like:

```swift
If dateIsTodaysDate() {
   setColorOfTextToRed()
   todayLabel.hidden = false
}
```

but are you missing the else part?

```swift
else {
   setColorOfTextToBlack()
   todayLabel.hidden = false
}
```

The date cells are exactly like a UITableViewCell. They are being reused, so you need to setup the cells properly every time. Let me know if this resolved your issue.

**Comment by danielhaan** [comment]
I was calling "return" in the function, so that it wouldn't modify the today stuff more. I have formatted it like so instead, so it makes more sense:

```
    func configureTextColor(cellState: CellState) {
        //If cell is today cell
        if isToday {
            dayLabel.textColor = UIColor.whiteColor()
            addCircle(self, color: Palette.red)
            self.bringSubviewToFront(dayLabel)
        }
        else {
            if cellState.dateBelongsTo == .ThisMonth {
                dayLabel.textColor = normalDayColor
                
            }
            else {
                dayLabel.textColor = outSideMonthColor
            }
        }
        
    }
```
However, this makes no difference. I am still getting the weird extra cells with a red circle, even though the cells, where it isn't today, the label is black, and not white, as one would expect in the above code.

I'll try some more stuff, and post an update, if I find more information

**Comment by patchthecode** [comment]
can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by danielhaan** [comment]
Thank you so much!
It works flawlessly now.

It makes sense, that seeing as the cells are reused, you need to remove stuff you added to them.

Cheers! I'll post a cool screenshot, when the app is completely done.

**Comment by patchthecode** [comment]
awesome!
It's great when people post their work to inspire others. 👍
