### ISSUE TITLE
Add Carthage support again, because of SPM limitations

### ISSUE THREAD

**Issue by aboudou** [patchthecode/JTAppleCalendar#1140]
** Version Number: 8.0.x**

## Description

Version 8 of JTAppleCalendar is available with SPM only. This a problem because SPM supports only "Debug" and "Release" build configurations (source : https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#setting-the-build-configuration and https://forums.developer.apple.com/thread/119327).

We use some other build configs to access different API endpoints, and with this build configs, JTAppleCalendar can't be found because SPM doesn't build it.

SPM is a great idea, but for now it is actually too limited to be usable in some cases. That's why it could be a good idea to add Carthage support again.

Thanks.

**Comment by patchthecode** [comment]
understood.
i'll do it.

**Comment by aboudou** [comment]
Thanks very much !

**Comment by patchthecode** [comment]
ok. It may be my lack of understanding on how carthage works. But I am having trouble re-implementing it back into the project. I'll have to take a look at it again in sometime, unless someone more knowledgeable than I gives me a hand.  

Added the help wanted flag in the mean time till i get back to it.

**Comment by aboudou** [comment]
If I understand the last 7.1.7 version (https://github.com/patchthecode/JTAppleCalendar/tree/1d9e3d0b4d8fbd0649da8cb6c9f1de2374c51cde), you need to add a JTAppleCalendar.xcodeproj project (Framework template).

I'll try to make it and do a pull request in the next days.

**Comment by patchthecode** [comment]
closing issue.
merged.

**Comment by aboudou** [comment]
Thanks :)
