### ISSUE TITLE
Spacing between each month and set frame to show 1 month / section 

### ISSUE THREAD

**Issue by taimur** [patchthecode/JTAppleCalendar#1141]
**(Required) Version Number:**

## Description
Can I control spacing between dates of each month and show 1 month in each section. Next month start with a gap. There's way to control spacing between cell but I want to increase / decrease spacing between each month.

 I tried this but i didnt work as expected.

calendarView.cellSize = 70.0
calendarView.scrollingMode = .stopAtEachCalendarFrame

```


```

**Comment by patchthecode** [comment]
Yes you can.
Try the sample app attached with this project.
Tap on `Calendar layouts demonstration`

And mess around with the spacing, the inset, and the cell inset buttons. Im sure you'll get a setting you want.

**Comment by patchthecode** [comment]
closing issue.
let me know.
