### ISSUE TITLE
a slight delay when I select a date on my calendar.

### ISSUE THREAD

**Issue by SauronRules** [patchthecode/JTAppleCalendar#1143]
I'm using JTAppleCalendar Version 8.0.2.

I'm currently following the tutorials on your website on selecting dates. I'm using the same line of code as the tutorial but a delay occurs after I pressed a date. 

I'm running it on IOS 13, and my xcode version is 11.0 (11A420a)

This is my CalendarViewController class

    @IBOutlet var calendarView: JTACMonthView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        calendarView.calendarDataSource = self
        calendarView.calendarDelegate = self
        calendarView.allowsRangedSelection = true
        calendarView.rangeSelectionMode = .continuous
        calendarView.scrollingMode = .stopAtEachCalendarFrame
        calendarView.scrollDirection = .horizontal
    }
    
    func configureCell(view: JTACDayCell?, cellState: CellState) {
        guard let cell = view as? DateCell  else { return }
        cell.dateLabel.text = cellState.text
        handleCellTextColor(cell: cell, cellState: cellState)
        handleCellSelected(cell: cell, cellState: cellState)

    }
    
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        let startDate = formatter.date(from: "2019 05 01")!
        let endDate = Date()
        return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 5, generateOutDates: .tillEndOfRow, firstDayOfWeek: .sunday, hasStrictBoundaries: false)
    }
    
    func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
        cell.dateLabel.text = cellState.text
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return cell
    }
    func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! DateCell
        cell.dateLabel.text = cellState.text
        configureCell(view: cell, cellState: cellState)
    }
    
    func handleCellTextColor(cell: DateCell, cellState: CellState) {
        if cellState.dateBelongsTo == .thisMonth {
            cell.dateLabel.textColor = UIColor.black
        } else {
            cell.dateLabel.textColor = UIColor.gray
        }
    }
    
    func handleCellSelected(cell: DateCell, cellState: CellState) {
        if cellState.isSelected {
            cell.selectedView.isHidden = false
        } else {
            cell.selectedView.isHidden = true
        }
    }
    
    func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
    }

    func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
    }

**Comment by patchthecode** [comment]
There are sample code at the bottom of each tutorial.
Can you paste me the link of the toturial you used? I will download the sample code and see if there is a delay in there/

**Comment by SauronRules** [comment]
Yes, definitely. 
https://patchthecode.com/jtapplecalendar-home/regular-selection/ 
I've followed the tutorial and apply it to run it on my app. I didn't add anything else apart from changing the size of the slectedView and the date cell in the story board. I've ran the sample code and there was no delay in that app. At first, I thought the problem was because of the changes I made in storyboard, so I basically copied the sample app to my project. After I tried that, the delay still occurs.

**Comment by patchthecode** [comment]
i am running the sample code now, and i do not see a delay.
When i tap the date, it correctly selects.

by "delay", do you mean that you want selection to happen on tapDown (when your finger hits the screen) instead of tapUp(when your finger lifts off the screen)?

If this is the case, then implement what ever logic you need in the **willSelect** delegate function instead of the **didSelect** delegate function.

Let me know if this works for you.

**Comment by patchthecode** [comment]
correction: the **shouldSelect** (not willSelect)

**Comment by patchthecode** [comment]
I am unable to edit that last comment.
Ignore the part about will select. I think i gave you incorrect information

Can you just confirm if you want selection on tapDown instead of tapUp ?

**Comment by SauronRules** [comment]
I'd love for the selection to be on tapDown.

**Comment by patchthecode** [comment]
This library gets all its behaviour from a UICollectionView.  Therefore, if you know how to get this done for a UICollectionView, then this will be the same method to do it for this library.

Will close this issue. Let me know if you're still stuck
