### ISSUE TITLE
Calendar offset when view first loads after updating to 8.0

### ISSUE THREAD

**Issue by bryancaragay** [patchthecode/JTAppleCalendar#1144]
**(Required) Version Number:**
8.0.2

## Description
After updating from 7.x.x to 8.0.2, the calendar is offset upon first load. This is after only making the needed delegate method name changes, so no code has actually changes functionality-wise since before the update.

When I tap or scroll at all on the calendar, the offset fixes itself, but only after some interaction has occurred.

## Steps To Reproduce
For context, i'm not using any special features of the calendar view, simply creating a calendar and configuring as such: 

`return ConfigurationParameters(startDate: startDate, endDate: endDate, generateInDates: .forAllMonths, generateOutDates: .tillEndOfGrid)`

## Expected Behavior
The calendar should focus the current month in-bounds and not need a tap to re-center.

## Additional Context
This screenshot shows a selected date, and i'm using `scrollToDate()` which seems has maybe been changed? The functionality before scrolled to the month that contained that date. Now it's scrolling specifically to that date.

<img src="https://user-images.githubusercontent.com/17282887/65792458-6c655600-e129-11e9-9d5d-96aecdcd05a8.PNG" width="400" />

**Comment by bryancaragay** [comment]
@patchthecode Wondering if you have any input on this. I can't tell if this is a config problem or a bug, but if it's the latter, i'm willing to look for a fix.

**Comment by patchthecode** [comment]
probably the default scroling mode in has changed.
can you explicitly set it instead?

```swift
calendarView.scrollmode = .stopAtEachFrame 
```
It think this is the syntax. I do not have the library infront of me right now
let me know

**Comment by bryancaragay** [comment]
Looks like that worked!
