### ISSUE TITLE
Can it parse ics files?

### ISSUE THREAD

**Issue by zenhouse** [patchthecode/JTAppleCalendar#1145]
**(Required) Version Number:**
8.0.2
## Description
Does this framework support parsing ics files? If not, can you recommend a cocoa pod for that will parse ics files? I would deeply appreciate it :)

**Comment by patchthecode** [comment]
Unfortunately, it cannot.
I am not a good person to suggest a cocoapod because I have never interacted with ics files before.

**Comment by zenhouse** [comment]
Ok, thanks.
