### ISSUE TITLE
Vertical line between cells that cannot be killed with calendarView.minimumInteritemSpacing = 0

### ISSUE THREAD

**Issue by Opryatnov** [patchthecode/JTAppleCalendar#1147]
**Version Number: 8.0.2**

#I have a vertical line between cells that cannot be killed with `calendarView.minimumInteritemSpacing = 0`#

#it is necessary to select the date range and fill the entire selected range with any color, and make the background color of the collection view different from the painted color#

#vertical line between cells not displayed when set to 0 in method `calendarView.minimumInteritemSpacing` # 

#a temporary solution is to set the left and right indentation of the view, which plays the role of a selector in -1# 

[https://monosnap.com/file/gHRpgqp098KH9veyPssyKvlenNn9cG](url)

**Comment by patchthecode** [comment]
This issue is a UICollectionView issue.
Does this help?

<img width="784" alt="screen shot 2018-08-29 at 8 25 05 am" src="https://user-images.githubusercontent.com/2439146/44797956-3be96c00-ab65-11e8-84c2-b1556520f26b.png">

**Comment by Opryatnov** [comment]
Thank you for response!
I think, that it isn't a UICollectionView issue, because I set background color for month section and different cell background color. In that case I don't have any offsets. But when I added some view on my cell I had the problem that I described above

**Comment by patchthecode** [comment]
can you let me know what the width of you calendar is?
You can pause you simulator, and go to the UI debugger. Then click on the calendar, and tell me the size of the frame width.

**Comment by Opryatnov** [comment]
Yes, i can:
Pls:
UIWindow: W - 414, H - 896
CalendarView: W - 414, H - 697.33
https://monosnap.com/file/eQzQgwoV2NRFwPjrAUiBRy8xDg6yjn

**Comment by patchthecode** [comment]
as a test can you set the width to 413.98 and see if the lines go away?
This is just a test.

**Comment by Opryatnov** [comment]
I tried to reduce the width to the specified size - it got even worse, all dates in the range began to be separated by vertical lines. I use for tests (iphone 8, iphone Xmax)

**Comment by Opryatnov** [comment]
> as a test can you set the width to 413.98 and see if the lines go away?
> This is just a test.
I tried to reduce the width to the specified size - it got even worse, all dates in the range began to be separated by vertical lines. I use for tests (iphone 8, iphone Xmax)

**Comment by Opryatnov** [comment]
> as a test can you set the width to 413.98 and see if the lines go away?
> This is just a test.

I tried to reduce the width to the specified size - it got even worse, all dates in the range began to be separated by vertical lines. I use for tests (iphone 8, iphone Xmax)

**Comment by patchthecode** [comment]
is you app open?
if possible can you give me a sample app with code which reproduces what you are seeing?

**Comment by mkchoi212** [comment]
I'm also experiencing this issue with the below code segment in my `viewWillAppear`

```swift
calendar.minimumInteritemSpacing = 0
calendarWidthConstraint.constant = view.frame.width -  view.frame.width.truncatingRemainder(dividingBy: 7)
calendar.cellSize = calendarWidthConstraint.constant / 7
```

**Comment by jappleseed69** [comment]
I'm also experiencing this issue with the below code segment in my `viewWillAppear`

```swift
calendar.minimumInteritemSpacing = 0
calendarWidthConstraint.constant = view.frame.width -  view.frame.width.truncatingRemainder(dividingBy: 7)
calendar.cellSize = calendarWidthConstraint.constant / 7
```

**Comment by jappleseed69** [comment]
Nevermind! The issue was that my selectedView wasn't filling up the entire day cell!

**Comment by patchthecode** [comment]
@Opryatnov assuming this issue is resolved.
If it is not, then please respond to the last question asked to you.
I will re-open this issue when you do.
