### ISSUE TITLE
 when you try to allocate a large range of dates, the application freezes for a minute, then sags and selects a range

### ISSUE THREAD

**Issue by Opryatnov** [patchthecode/JTAppleCalendar#1150]
**Version Number: 8.0.2**

#Vertical scroll of calendar! On display i see current date, if i set start date like current date and endDate like one year before, in function selectDates(from: startDate!, to: endDate!), my application 
freezes, hangs after a few minutes and displays the selected date range. How can I get rid of a hang?#

#Calendar start from 2018.01.01  and end of 2019.12.31 
show current date on display
Add action to select range
let startDate = self.formatter.date(from: "2018 10 01")
            let endDate = self.formatter.date(from: "2019 10 01")
            self.calendarView.selectDates(from: startDate!, to: endDate!)#

#
what can be done so that the interface does not slow down when trying to highlight a large range#

**Comment by patchthecode** [comment]
does this help?
```swift
calendar.selectDates(dateRange, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
```

**Comment by Opryatnov** [comment]
Thank's, this method is working! Your calendar is cool!

**Comment by patchthecode** [comment]
awesome. 
will close this issue.
and thanks.
