### ISSUE TITLE
Calendar Displays Some Days Out of Order After End of Each Month

### ISSUE THREAD

**Issue by zenhouse** [patchthecode/JTAppleCalendar#1151]
**(Required) Version Number:**
8.0.2

## Description
After following the "Calendar from Scratch" I built my project and noticed that calendars showing in the view were not in order after the end of each month. 

I thought I didn't do something right so, I downloaded the sample project and built and ran it out of the box, and it too had the same issue, See example.

## Steps To Reproduce
1. Build and run sample test project
2. Scroll past the end of each month and see calendar days are no longer in oder.

## Expected Behavior
Each month should show correct number of days (in sequential  order) for each month 
<img width="380" alt="Screen Shot 2019-10-03 at 8 06 09 AM" src="https://user-images.githubusercontent.com/45663179/66139311-0d825f80-e5b5-11e9-83ce-510911b90652.png">
shown.

## Additional Context
Please advise if there is a work around or if I need to perform additional configurations for this work as expected.

**Comment by patchthecode** [comment]
what is the link for the sample test project?

**Comment by patchthecode** [comment]
oops. Nevermind

**Comment by patchthecode** [comment]
This is not a bug. 

Follow to other [tutorial](https://patchthecode.com/jtapplecalendar-home/designing-the-calendar/) to see that this is -->

<img width="600" alt="Screen Shot 2019-10-03 at 12 22 11 PM" src="https://user-images.githubusercontent.com/2439146/66145305-8e9f1e00-e5d8-11e9-9081-9af484639108.png">
