### ISSUE TITLE
Once again, a date in the range of both the start date and end date is highlighted

### ISSUE THREAD

**Issue by Opryatnov** [patchthecode/JTAppleCalendar#1152]
**(Required) Version Number:**
Version Number: 8.0.2

##Description
I made a selection of the date range according to the example 2tapRangedSelection, 
and if the end date of the month in the range falls at the end of the week, and the start date of the next month falls at the beginning of the week, then these dates are excessively highlighted as start dates and end dates 

## Steps To Reproduce
**i use this func:**
    func handleCellSelected(cell: DateCell, cellState: CellState) {
       
        switch cellState.selectedPosition() {
        case .left:
            cell.selectedView.isHidden = !cellState.isSelected
            cell.periodSelectedView.isHidden = false
            cell.dateLabel.textColor = UIColor.white
            cell.periodLeftConstraint.constant = cell.bounds.width / 2.0
            break
        case .middle:
            cell.periodSelectedView.isHidden = false
            break
        case .right:
            cell.selectedView.isHidden = !cellState.isSelected
            cell.periodSelectedView.isHidden = false
            cell.dateLabel.textColor = UIColor.white
            cell.periodRightConstraint.constant = cell.bounds.width / 2.0
            break
        case .full:
            cell.selectedView.isHidden = false
            cell.dateLabel.textColor = UIColor.white
            break
        default:
            break
        }
    }
## Expected Behavior
How can I fix this problem?
## Additional Context
link: https://monosnap.com/file/O7bPQnEA0zMQpZGKcrflRh36fz7jC1
Configuration: ConfigurationParameters(startDate: startDate!, endDate: endDate!, generateInDates: .forAllMonths, generateOutDates: .tillEndOfRow)

**Comment by patchthecode** [comment]
Does this help?
```swift
calendarView.rangeSelectionMode = .continuous
```

**Comment by Opryatnov** [comment]
Thnk's, is working, the issue can be closed!
