### ISSUE TITLE
 How to prohibit choosing dates in the future after the current day?

### ISSUE THREAD

**Issue by Opryatnov** [patchthecode/JTAppleCalendar#1153]
**(Required) Version Number:**
8.0.2

## Description
there are no properties in the function `if  cellState.dateBelongsTo == .thisMonth`  that could display different dates in the future, which are larger than the current day  haven't properties for dates  
## Steps To Reproduce
```
func handleCellTextColor(cell: DateCell, cellState: CellState) {
        if  cellState.dateBelongsTo == .thisMonth {
            cell.dateLabel.textColor = UIColor.black
            cell.isHidden = false
        } else {
            cell.isHidden = true
        }
    }
```

**.thisMonth and other properties unsuitable**

**Comment by patchthecode** [comment]
To prevent selecting a date, use the shouldSelectDate delegate.

```swift
func calendar(_ calendar: JTACMonthView, shouldSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) -> Bool {
   if date > someFutureDate {
      return false    
   } else {
      return true
   }
```

**Comment by patchthecode** [comment]
closing this issue. Let me know if still stuck

**Comment by Opryatnov** [comment]
Thnk, it working
