### ISSUE TITLE
Layout Attributes Ignored.

### ISSUE THREAD

**Issue by devMoxie** [patchthecode/JTAppleCalendar#1155]
**(Required) Version Number:** 
8.0.2
iOS 13
Xcode 11.1

## Description
I'm testing out toggling the calendar layout between month, 5 day, day views. All layouts have the same height, full screen height. I do this by updating the cellSize property to 0, calendarView.frame.width/5 and, calendarView.frame.width. I also call reload(withAnchor) and change the numberOfRows between 1 and 6 in the same manner as the [tutorial](https://patchthecode.com/jtapplecalendar-home/week-view-month-view/). The app runs correctly and the cells act accordingly but I get the following message in the console when I toggle to a new layout: 

`2019-10-09 09:41:19.614569-0600 ChangingCalendarViewTest[6275:707237] [CollectionView] Layout attributes <UICollectionViewLayoutAttributes: 0x7fc5be029db0> index path: (<NSIndexPath: 0xdda98ad697218945> {length = 2, path = 46 - 3}); frame = (24178.6 1; 80.8 806); were received from the layout <JTAppleCalendar.JTACMonthLayout: 0x7fc5bbc01b00> but are not valid for the data source counts. Attributes will be ignored.`

This leads me to believe that I am doing something incorrect or there is a minor bug. The idea is to display more detailed cell content dependent on the size of the cell. 

## Steps To Reproduce
See the code [here](https://github.com/devMoxie/ChangingCalendarViewTest)

## Expected Behavior
No console message.

**Comment by patchthecode** [comment]
I just had time to check this issue today.
unfortunately, the only code you have in that source is relating to the issue you are experiencing is.

```swift
    @IBAction func segmentDidChange(_ sender: Any) {
        switch segmentedControl.selectedSegmentIndex {
        case 0:
            numCalendarRows = 1
            calendarView.cellSize = calendarView.frame.width
        case 1:
            numCalendarRows = 1
            calendarView.cellSize = calendarView.frame.width / 5
        case 2:
            numCalendarRows = 6
            calendarView.cellSize = 0.0
        default:
            print("default")
        }
        calendarView.reloadData(withAnchor: selectedDate, completionHandler: nil)
    }
```
I cannot tell anything from this.
Is it possible you can update the code to provide a minimal sample runnable app with the issue?

**Comment by devMoxie** [comment]
Thanks for the initial look. I'll try to update the sample app when I have time. I'll close this for now and try to get back to it.
