### ISSUE TITLE
[Carthage] no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by mock123** [patchthecode/JTAppleCalendar#1159]
## Version Number
8.0.2

## Description
I tried to update the JTAppleCalendar library to 8.0.2 via Carthage. However, it errored out as follows:
` "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS`

### The error log:
```
$ carthage update --no-use-binaries --platform iOS
*** Fetching JTAppleCalendar
*** Checking out JTAppleCalendar at "8.0.2"
*** xcodebuild output can be found in blahblahblah.log
*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes 
for any of the platforms: iOS

If you believe this to be an error, please file an issue 
with the maintainers at https://github.com/patchthecode/JTAppleCalendar/issues/new
```
## Steps To Reproduce
```
$ carthage update --no-use-binaries --platform iOS

or

$ carthage update --platform iOS
```
## Additional Context

I would say I am having the same issue below:
https://github.com/patchthecode/JTAppleCalendar/issues/120

**Comment by patchthecode** [comment]
:/ 

This should have fixed it.

https://github.com/patchthecode/JTAppleCalendar/pull/1142

It is still broken?

**Comment by mock123** [comment]
Yes, it seems like the error still exists.

My environment:
```
Xcode 11.1
Carthage 0.33.0
mac OS Catalina (version 10.15)
```

**Comment by mock123** [comment]
Although I also tried to update it without `--platform iOS`, the error still occurs.

```
$ carthage update
*** Fetching JTAppleCalendar
*** Checking out JTAppleCalendar at "8.0.2"
*** xcodebuild output can be found in blahblahblah.log
*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes
```

**Comment by patchthecode** [comment]
hmm.. ok will look today

**Comment by patchthecode** [comment]
as explained by @aboudou  on the merge request

I'll  have to tag  new release for carthage to work without explicitly using "master". Till then, use this.

```
github "patchthecode/JTAppleCalendar" "master"
```

I just tested it and it works.
Closing this issue now.
