### ISSUE TITLE
JTAppleCalendar Integrating with SwiftUI

### ISSUE THREAD

**Issue by AndreaMiotto** [patchthecode/JTAppleCalendar#1161]
**(Required) Version Number:** 8.0.2

## Description
I'm trying to implement a Calendar in UIKit and then importing it into SwiftUI.
I've successfully extended the calendar view controller with the SwiftUI protocols.
But I  can see only the background of the month collection. The day cells don't appear on screen.
Should I conform even the views to the SwiftUI protocols?
How can I do to make it work in SwiftUI?

## Steps To Reproduce

I've extended the controller of the example given in the wiki as follow:

```swift

import SwiftUI

struct CalendarViewControllerRepresentation: UIViewControllerRepresentable {

  func makeUIViewController(
    context: UIViewControllerRepresentableContext<CalendarViewControllerRepresentation>) -> CalendarViewController {

    UIStoryboard(name: "CalendarView", bundle: nil)
      .instantiateViewController(withIdentifier: "CalendarViewController")
      as? CalendarViewController ?? CalendarViewController()
  }

  func updateUIViewController(
	_ uiViewController: CalendarViewController,
	context: UIViewControllerRepresentableContext<CalendarViewControllerRepresentation>) {

  }

}

#if DEBUG
struct CalendarViewControllerPreviews: PreviewProvider {
  static var previews: some View {
	Group {
		CalendarViewControllerRepresentation()
		CalendarViewControllerRepresentation()
			.environment(\.colorScheme, .dark)
	}

  }
}
#endif
```

And than I've used it on a SwiftUI view.

## Expected Behavior

I should see the calendar days with the rest of the storyboard, but I can't.

**Comment by sarahtipton** [comment]
Hi Andrea,
I'm running into this same issue and I was wondering if you could tell me what you did to fix it? I expect it is something silly that I've overlooked.

Thanks!
