### ISSUE TITLE
Calendar doesn't update on Click

### ISSUE THREAD

**Issue by GefaketHD** [patchthecode/JTAppleCalendar#1162]
**(Required) Version Number: v8.0.2**

## Description
I just updated to XCode 11 and tried to run my before working app. It DOES open, but when I click on a date, nothing happens. Neither does the selection change, nor does ist even recognize my touch. Are there some things we have to watch out for? Does it work with SwiftUI yet?
I got it to show with a UIViewControllerWrapper.

`struct CalendarViewControllerWrapper: UIViewControllerRepresentable {

    typealias UIViewControllerType = CalendarViewController

    func makeUIViewController(context: UIViewControllerRepresentableContext<CalendarViewControllerWrapper>) -> CalendarViewControllerWrapper.UIViewControllerType {
        return CalendarViewController()
    }

    func updateUIViewController(_ uiViewController: CalendarViewControllerWrapper.UIViewControllerType, context: UIViewControllerRepresentableContext<CalendarViewControllerWrapper>) {
        // (Do I have to write something here? For updating the thing?)
    }
}`

## Steps To Reproduce
I don't know the exact steps to reproduce, because I wasn't able to figure out, what I am doing wrong now. The project was working before... :/

## Expected Behavior
The dots change colors and highlight the touched cell.

## Additional Context
I'm creating the thing completely via code, so no storyboard, just programatically.

EDIT: the edits are because i tried to make the code show correctly...

**Comment by AndreaMiotto** [comment]
probably related to:  https://github.com/patchthecode/JTAppleCalendar/issues/1163

**Comment by GefaketHD** [comment]
Solution: https://github.com/patchthecode/JTAppleCalendar/issues/1163#issuecomment-544895713
