### ISSUE TITLE
Touch does not trigger with SwiftUI

### ISSUE THREAD

**Issue by AndreaMiotto** [patchthecode/JTAppleCalendar#1163]
Hi,
I'm trying to implement a calendar in SwiftUI, I'm having an issue with the touch event.
It does not start, here is the example repo already configured for you: https://github.com/AndreaMiotto/SwiftUI-JTAppleCalendar

**Comment by GefaketHD** [comment]
I have the related issue.
In my case it does this:
If I touch a day, it doesn't select it right away, but when i scroll to a different month and back to the original one.
(Touch day -> Nothing happens. Scroll back and forth, previously touched day is selected now.)

--> So it does recognize the touch, but doesn't trigger the `calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState)`

**Comment by AndreaMiotto** [comment]
yes, exactly the same of mine

**Comment by AndreaMiotto** [comment]
Fixed!

The delegate method has a different signature from the one in the example project! The example project in the wiki should be updated at version 8.0.2

Updates the func signatures with:

```Swift
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
		configureCell(view: cell, cellState: cellState)
	}

	func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
		configureCell(view: cell, cellState: cellState)
	}

```

The `indexPath: IndexPath` part was missing

**Comment by GefaketHD** [comment]
Working for me too. Thank you!
Can be closed I think.

**Comment by patchthecode** [comment]
Everyone who is trying to use version 8+ please look at which function signatures have changed -> 

https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

Will close this now.
