### ISSUE TITLE
Start date in configureCalendar don't Work

### ISSUE THREAD

**Issue by LucaVaccaDeveloper** [patchthecode/JTAppleCalendar#1167]
**(Required) Version Number:7.1.7

## Description
In the configureCalendar func  I have set the startDate like "2019 01 01"  but when I debug it, I see the startDate link 2018-12-31 23:00:00 +0000 and not the date that I have set.

## Expected Behavior
I expect to have 2019 01 01 like startDate
## Additional Context
Here is a image demo
<img width="1680" alt="Schermata 2019-10-26 alle 18 51 28" src="https://user-images.githubusercontent.com/41347745/67623186-d2c1bf00-f822-11e9-8475-35839540c54e.png">

**Comment by patchthecode** [comment]
dont depend on the debug print statement.
the debug print start has its own built in Date formatting.

You will see this problem more if you live in the east. 
To see the correctly printed date, use a DateFormatter.

See discussion here: https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
will close this issue.
let me know if youre still stuck.
