### ISSUE TITLE
Month is showing on more than one page

### ISSUE THREAD

**Issue by shbedev** [patchthecode/JTAppleCalendar#1168]
**(Required) Version Number:**
8.0.2
## Description
First of all, thank you for your amazing work!

I have encountered an issue when configuring the calendar with the following parameters:

**numberOfRows: 5
generateInDates: .forAllMonths
generateOutDates: .tillEndOfRow**

Then when I am scrolling in the calendar, some months are showing on more than one page, you can see this behavior in the GIF picture.

## Steps To Reproduce

1. Configure the calendar with the following configuration parameters:

```
func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let startDate = formatter.date(from: "1930 01 01")!
        let endDate = formatter.date(from: "2099 12 31")!
        
        return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 5, generateInDates: .forAllMonths, generateOutDates: .tillEndOfRow)
    }
```

2. Scroll in the calendar and some months will show you like 2 pages.

## Expected Behavior

Each month to show as one page.

## Additional Context

![Screen Recording 2019-10-26 at 22 36 59](https://user-images.githubusercontent.com/9465997/67625056-af5a3c80-f841-11e9-863d-5a2a45b6fb2e.gif)

**Comment by patchthecode** [comment]
ok. You do not want a 5 row calendar.
You want a 6 row calendar.

But you want it to be flexible such that:
1) when a month has 6 rows: it should display 6
2) when a month has 5 rows: it should display 5

To accomplish this, you already have it correct setting --> **tillEndOfRow**

Therefore, please remove the 5, and set it to 6.

**Comment by shbedev** [comment]
> ok. You do not want a 5 row calendar.
> You want a 6 row calendar.
> 
> But you want it to be flexible such that:
> 
> 1. when a month has 6 rows: it should display 6
> 2. when a month has 5 rows: it should display 5
> 
> To accomplish this, you already have it correct setting --> **tillEndOfRow**
> 
> Therefore, please remove the 5, and set it to 6.
> Your problem should be resolved.
> 
> Setting it to 5 will behave correctly as you see it.
> i.e. If a month has 6 rows, it will truncate it at the 5th and put the remainder on the other screen.
> 
> Closing this issue. Let me know if you are still stuck.

Thank you for your quick response, you explained it well, I appreciate it.

**Comment by shbedev** [comment]
Thank you for your quick response, you explained it well, I appreciate it!
