### ISSUE TITLE
No such module 'JTAppleCalendar'

### ISSUE THREAD

**Issue by 1130ibo** [patchthecode/JTAppleCalendar#1172]
Using JTAppleCalendar (8.0.2)

I am a beginner to Xcode and Swift, so I'm hoping I'm doing something obvious wrong. I am trying to follow the tutorial. I setup the Podfile and got to the step where I need to make a new class. when I type "import JTAppleCalendar" I get an error: No such module 'JTAppleCa..." ... also another error, saying that SWIFT 5 is not supported..

**Comment by 1130ibo** [comment]
screenshot
https://ibb.co/NYHBX19

**Comment by 1130ibo** [comment]
zip files
https://we.tl/t-7P6zKDyHCQ

**Comment by romain64** [comment]
Did you open the project using the .xcworkspace, not the .xcodeproj ? .xcodeproj only contains the main project; .xcworkspace includes all your pods including JTAppleCalendar.

**Comment by patchthecode** [comment]
@1130ibo  is this still an issue?
Have you tried hitting CMD + B ?

**Comment by 1130ibo** [comment]
Yes, I open the White looking file, not the blue looking file.
I open it, then I can see the "No such module" red comment. When I press CMD+B, I get "Build Failed" and 2 build time errors:
1. calendar workspace issue: swift version 5 is unsupported
2. Calendar issue: no such module 'JTAppleCalendar'

**Comment by 1130ibo** [comment]
does the zip with my files work for you guys/girls?

**Comment by patchthecode** [comment]
No, the zip file is not working for me. I cannot download it.
Can you zip the file and drop the zip file into this chat box? 
That way it will be on github here, and i can download it

**Comment by 1130ibo** [comment]
/Users/ibo/Desktop/Calendar/Archive.zip

not sure if that worked... we transfer files here, will be deleted in a week: https://we.tl/t-yaUcLoGytx

**Comment by patchthecode** [comment]
Hi, I just looked at your file.
Your class on the InterfaceBuilder should not be JTAppleCalendarView, it should JTACMonthView.

[Archive.zip](https://github.com/patchthecode/JTAppleCalendar/files/3849474/Archive.zip)

**Comment by 1130ibo** [comment]
I see. I was following the wiki, and that's what's pictured. Your suggestion however fixed it, yes, thank you very much.
Now the build still fails but it's because the issue below. I'm new to Apple products, can you help me? Does this error mean that JTAppleCalendar is written in Swift 5 and my XCode is old and only supports 3, 4, 4.2?

:-1: SWIFT_VERSION '5' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'JTAppleCalendar')

**Comment by patchthecode** [comment]
What version of xcode do you have?

**Comment by 1130ibo** [comment]
I have Version 10.1 (10B61)

**Comment by patchthecode** [comment]
Getting back to this.
This lib does support swift 5.

It sounds like an issue with cocoapods/xcode or probable do a clean build? I am not sure.
Hopefully this is still not an issue for you. Closing this as the is not really an issue directly relating to the library and the original issue was resolved.

**Comment by patchthecode** [comment]
If the 2nd issue is still a problem lets track it on a new issue.
