### ISSUE TITLE
Programmatically select date?

### ISSUE THREAD

**Issue by zenhouse** [patchthecode/JTAppleCalendar#1176]
**(Required) Version Number:**
8.0.2
## Description
I'm unable to figure out how to programmatically select a date on the calendar as if the user touched that particular date on the screen. Essentially, I want to set a default date when the app opens to Today's date. To be clear it would be like programmatically calling the didselectDate delegate method. Is there a way to do this?

**Comment by patchthecode** [comment]
```
calendarView.selectDate(theDate)
```

Closing issue now.
let me know if anything else

**Comment by romain64** [comment]
Got an error with 8.0.0  `Value of type 'JTACMonthView' has no member 'selectDate'` and had to use the following instead:

```
calendarView.selectDates([theDate])
```

**Comment by patchthecode** [comment]
yes. i think i made a mistake. you are correct.
