### ISSUE TITLE
Dependency "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by kamil-tomaszewski** [patchthecode/JTAppleCalendar#1177]
**Version Number:** 8.0.2

## Description
While trying to use the latest version of JTAppleCalendar via Carthage the build fails with the following message: `*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS`

## Steps To Reproduce
Simply add `github "patchthecode/JTAppleCalendar"` to cartfile and run carthage
 
## Expected Behavior
The build should succeed

**Comment by patchthecode** [comment]
Use master branch for now until i release 8.0.3
`github "patchthecode/JTAppleCalendar" "master"`

closing this issue.
let meknow if youre still stuck.
