### ISSUE TITLE
Issue Setting Background in setupCellBeforeDisplay from CloudKit

### ISSUE THREAD

**Issue by jfo713** [patchthecode/JTAppleCalendar#118]
There's probably a simple solution to this - I'm a pretty new developer.

I'm trying to set my cell background color by syncing it with CloudKit - I have 3 different types of dates in my CloudKit record, and have written a function to sort them into 3 different arrays of [NSDate]. Then in a separate function, cellState.date == an object in one of the arrays, it will set the appropriate background color. It works correctly the first time the calendarView loads, but then when I scroll to the next month, it begins coloring cells that don't have dates in the CloudKit array, and will keep doing that when I scroll back to the initial month. Screenshots below (first 'August' is correct, September and second August aren't). Also shots of my code - `func configureBackgroundColor` gets called inside of `func populateClasses(cellState)`, and `func populateClasses(cellState)` is called inside of `setupCellBeforeDisplay`. I think I've just misunderstood how the calendarView implements the cellView...

I really appreciate any help you can give me, and definitely want to say thanks for making this awesome library! I'm really loving it!
<img width="381" alt="screen shot 2016-08-23 at 2 28 02 pm" src="https://cloud.githubusercontent.com/assets/19805456/17907614/608529f8-6942-11e6-8d3d-b049c5f3eede.png">
<img width="377" alt="screen shot 2016-08-23 at 2 28 16 pm" src="https://cloud.githubusercontent.com/assets/19805456/17907619/60a31314-6942-11e6-847b-1cd75250cbea.png">
<img width="377" alt="screen shot 2016-08-23 at 2 28 27 pm" src="https://cloud.githubusercontent.com/assets/19805456/17907616/609db9be-6942-11e6-8d1a-5d6f72f7963e.png">
<img width="379" alt="screen shot 2016-08-23 at 2 28 38 pm" src="https://cloud.githubusercontent.com/assets/19805456/17907615/609c75c2-6942-11e6-9932-18617dfe97fc.png">
<img width="710" alt="screen shot 2016-08-23 at 2 33 51 pm" src="https://cloud.githubusercontent.com/assets/19805456/17907618/60a20366-6942-11e6-9226-2f017f36a0ec.png">
<img width="424" alt="screen shot 2016-08-23 at 2 34 13 pm" src="https://cloud.githubusercontent.com/assets/19805456/17907617/609f8d3e-6942-11e6-8541-7e972b8a362a.png">

**Comment by patchthecode** [comment]
Would [this](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#9) be of help to you?

**Comment by jfo713** [comment]
Thanks - that definitely helped, and sorry about not taking a closer look at the FAQ. I've been going through your delegate methods and a few other people's calendars, and am trying to understand where I define/access the dequeueReusableCellIdentifier set up on the collection view used for the CalendarView. Do I need to define a custom CalendarView class that inherits from JTAppleCalendarView, and then implement that on my ViewController, or can it all be done within the ViewController file? Thanks again for helping with basic questions.

**Comment by patchthecode** [comment]
Can you let me know what you are trying to do?
I do not think you have access to that identifier.
you can join me [here](https://gitter.im/patchthecode/JTAppleCalendar) if youre online.

**Comment by patchthecode** [comment]
Issue resolved over chat. If you have any other problems, create a new issue.
