### ISSUE TITLE
unable to select date (Day cell) at JTACMonthView

### ISSUE THREAD

**Issue by zero-tolerance0** [patchthecode/JTAppleCalendar#1181]
**(Required) Version Number:**
version 8.0.2 (commit 8a7c543) (latest)

## Description
I followed this example when doing my Calnedar: https://github.com/patchthecode/JTAppleCalendar/blob/master/SampleJTAppleCalendar/Example%20Calendars/ViewController.swift
I reached some working behavior of calendar,  please see img attached
![123aq](https://user-images.githubusercontent.com/23029886/69025176-296c8400-09f0-11ea-8f77-6661468d1da4.png)

However, i am not able to select date.

I could not set up delegates and datasources fromStoryboard, but i did that by code inside ViewDidLoad
_calendarView.calendarDelegate = self
calendarView.calendarDataSource = self_

## Expected Behavior
i expect to select date and push View Controller to Details.
Also I want to style each month according to image attached.
## Additional Context
<img width="288" alt="Screen Shot 2019-11-18 at 10 21 41 AM" src="https://user-images.githubusercontent.com/23029886/69024989-4ce2ff00-09ef-11ea-9d2d-d964470a8780.png">

Attaching ViewController in txt and zip formats.

[MonthViewController.swift.zip](https://github.com/patchthecode/JTAppleCalendar/files/3856820/MonthViewController.swift.zip)
[MonthVC.txt](https://github.com/patchthecode/JTAppleCalendar/files/3856821/MonthVC.txt)

**Comment by patchthecode** [comment]
your did select date function is not the same function signature as the one in the link you provided.
