### ISSUE TITLE
Incorrect month title

### ISSUE THREAD

**Issue by omerbaskurt** [patchthecode/JTAppleCalendar#1183]
**(Required) Version Number:**
8.0.0

Hi, a few of our users reported that the month title does not correlate with the calendar. So when they looking at the month of November they see the title of October. The title was always 1 month behind. I tried to reproduce the issue but I'm always getting the correct title regardless of the device. Do you have any idea what might trigger this problem? 

I'm using this code to update the title and call it in didScrollToDateSegmentWith:

```
func setupViewsOfCalendar(from visibleDates: DateSegmentInfo) {
        guard let date = visibleDates.monthDates.first?.date else {
            return
        }
        self.formatter.dateFormat = "MMMM"
        self.month.text = self.formatter.string(from: date) 
}
```

Edit: Horizontal scrolling with paging enabled

**Comment by patchthecode** [comment]
will look at this at end of day

**Comment by patchthecode** [comment]
Do you know the region your users live in that experience this issue?

**Comment by omerbaskurt** [comment]
Thanks for the reply. Canada, Edmonton

**Comment by patchthecode** [comment]
i just updated my text above.

**Comment by patchthecode** [comment]
To try to reproduce, you can try to set you device to say --> HongKong region.
If you are seeing -1day issue, then i think my suspicion is correct.

**Comment by omerbaskurt** [comment]
You were right, that was the issue. Thanks a lot

**Comment by patchthecode** [comment]
cool. Alright then closing this.
Just update your `formatter` to match the region of your user's phone.
Let me know if still stuck.

**Comment by omerbaskurt** [comment]
I was setting it like this: 
```
formatter.timeZone = Calendar.current.timeZone
 formatter.locale = Calendar.current.locale
```
Isn't it the correct way?

**Comment by patchthecode** [comment]
Haha, i dont know honestly.
I can build this library, but i have not built an international app before.
Until i do this, i cannot give you a confident answer.

**Comment by patchthecode** [comment]
We have had an indept discussion about this here --> https://github.com/patchthecode/JTAppleCalendar/issues/252

I also have all the debugging i did.
I cant look at it now (im at work)
Let me know if it helps.
If not, i will re-look this.

**Comment by omerbaskurt** [comment]
I've apparently overwritten it somewhere in the code. Thank you so much again. I was trying to figure this out for the last couple of days.

**Comment by patchthecode** [comment]
cool awesome 🎊
