### ISSUE TITLE
Months representation 

### ISSUE THREAD

**Issue by ZhannySunny** [patchthecode/JTAppleCalendar#1185]
JTAppleCalendar (8.0.2)

Hello. I've followed to your tutorial and stopped on headers. My calendar shows months till November. Can you say how can I solve this problem?

![issue-min](https://user-images.githubusercontent.com/17294536/69409414-1846ae80-0d33-11ea-9cb5-4af3d86e2c5e.gif)

**Here's code**

`import UIKit
import JTAppleCalendar

class ViewController: UIViewController {
    
    
    @IBOutlet weak var calendarView: JTACMonthView!
    @IBOutlet weak var constraint: NSLayoutConstraint!
    
    
    var numberOfRows = 6
    let formatter = DateFormatter()
    var testCalendar = Calendar.current
    var generateInDates: InDateCellGeneration = .forAllMonths
    var generateOutDates: OutDateCellGeneration = .tillEndOfGrid
    //var prePostVisibility: ((CellState, CellView?)->())?
    var hasStrictBoundaries = true
//    let disabledColor = UIColor.lightGray
//    let enabledColor = UIColor.blue
//    var monthSize: MonthSize? = nil
//    var prepostHiddenValue = false
//    var outsideHeaderVisibilityIsOn = true
//    var insideHeaderVisibilityIsOn = false
    
    override func viewDidLoad() {
        super.viewDidLoad()
    
        calendarView.scrollDirection = .horizontal
        calendarView.scrollingMode   = .stopAtEachCalendarFrame
        calendarView.showsHorizontalScrollIndicator = false
        
        // Do any additional setup after loading the view.
    }
    
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        
        let visibleDates = calendarView.visibleDates()
        calendarView.viewWillTransition(to: .zero, with: coordinator, anchorDate: visibleDates.monthDates.first?.date)
    }
    
    
    @IBAction func toggle(_ sender: Any) {
        
        if numberOfRows == 6 {
            self.constraint.constant = 58.33
            self.numberOfRows = 1
            UIView.animate(withDuration: 0.2, animations: {
                self.view.layoutIfNeeded()
            }) { completed in
                self.calendarView.reloadData(withAnchor: Date())
            }
        } else {
            self.constraint.constant = 350
            self.numberOfRows = 6
            
            UIView.animate(withDuration: 0.2, animations: {
                self.view.layoutIfNeeded()
                self.calendarView.reloadData(withAnchor: Date())
            })
        }
        
        
    }
    

}

extension ViewController: JTACMonthViewDataSource {
    
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        let startDate = formatter.date(from: "2019 01 01")!
        let endDate = Date()
        
        
        if numberOfRows == 6 {
            
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: numberOfRows)
            
        } else {
            
            return ConfigurationParameters(startDate: startDate,
                                           endDate: endDate,
                                           numberOfRows: numberOfRows,
                                           generateInDates: .forFirstMonthOnly,
                                           generateOutDates: .off,
                                           hasStrictBoundaries: false)
        }
        
        
    }
    
    
}

extension ViewController: JTACMonthViewDelegate {
    
    
    func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
        
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
        
         self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        
        return cell
        
    }
    
    func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        
        configureCell(view: cell, cellState: cellState)
        
    }
    
    
    func configureCell(view: JTACDayCell?, cellState: CellState) {
        
        guard let cell = view as? DateCell  else { return }
        cell.dateLabel.text = cellState.text
        handleCellTextColor(cell: cell, cellState: cellState)
        handleCellSelected(cell: cell, cellState: cellState)
    }
    
    func handleCellTextColor(cell: DateCell, cellState: CellState) {
        
        if cellState.dateBelongsTo == .thisMonth {
            cell.dateLabel.textColor = UIColor.black
        } else {
            cell.dateLabel.textColor = UIColor.gray
        }
    }
    
    func handleCellSelected(cell: DateCell, cellState: CellState) {
        
        if cellState.isSelected {
            cell.selectedView.layer.cornerRadius =  13
            cell.selectedView.isHidden = false
        } else {
            cell.selectedView.isHidden = true
        }
    }
    
    func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
        
        configureCell(view: cell, cellState: cellState)
        
    }
    
    func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        
        configureCell(view: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTACMonthView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTACMonthReusableView {
        
        let formatter = DateFormatter()  // Declare this outside, to avoid instancing this heavy class multiple times.
        formatter.dateFormat = "MMM"
        
        let header = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: "DateHeader", for: indexPath) as! DateHeader
        header.monthTitle.text = formatter.string(from: range.start)
        return header
    }
    
    func calendarSizeForMonths(_ calendar: JTACMonthView?) -> MonthSize? {
        return MonthSize(defaultSize: 50)
    }`

**Comment by ZhannySunny** [comment]
I found my error. Instead of **let startDate = formatter.date(from: "2018 01 01")** I did "2019 01 01".

**Comment by patchthecode** [comment]
its a good thing you found the error. 
Because from what you said above, I was thinking something totally different.
