### ISSUE TITLE
need  code example

### ISSUE THREAD

**Issue by hell4opt** [patchthecode/JTAppleCalendar#1187]
StoryBoard bad practice ( for me

**Comment by patchthecode** [comment]
Which part in doing it by code are you stuck on?

**Comment by hell4opt** [comment]
> Which part in doing it by code are you stuck on?

i am noob, i need full example project on code, without storyboard)

**Comment by patchthecode** [comment]
i am sorry, but i will not be able to help with this.
If you have created any program already with code before, then creating this with code will be simple.
All you need to do is look at the names of the properties that you set on storyboard, and then do the exact thing in code. 
https://github.com/patchthecode/JTAppleCalendar/issues/892
This page is a start.
