### ISSUE TITLE
JTAppleCalendar not running right?

### ISSUE THREAD

**Issue by Distance-MJ** [patchthecode/JTAppleCalendar#1188]
*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/patchthecode/JTAppleCalendar/issues/new

**Comment by patchthecode** [comment]
i guess you are building this lib with some sort of CI tool.

1. What command are you using to build?
2. What version of the lib are you using?

**Comment by Distance-MJ** [comment]
I use Carthage, v8.0.2

**Comment by patchthecode** [comment]
put this as  your carthage

```
github "patchthecode/JTAppleCalendar" "master"
```

**Comment by ekimia** [comment]
yep same here. Could use another tag whenever you get the chance @patchthecode

**Comment by patchthecode** [comment]
8.0.3 will be released over weekend which should resolve this.

**Comment by patchthecode** [comment]
released 8.0.3
This should fix the carthage tag
let me know if it is still an issue
