### ISSUE TITLE
JTAppleCalendarView can not call method init(frame: CGRect)

### ISSUE THREAD

**Issue by fogisland** [patchthecode/JTAppleCalendar#119]
Really strange, I'm using the latest version 5.0.1,  `init(frame: CGRect)` is clearly overrided in JTAppleCalendarView.swift. However when I call `JTAppleCalendarView.init(frame: CGRectZero)`, error is announced as below:
` Incorrect argument label in call (have 'frame:', expected 'coder:')`.

( I tried the code in the example project, this issue still exists )

**Comment by patchthecode** [comment]
Hmm. ok, can you let me know the end goal or what you are trying to achieve?

I am unsure why you are calling `JTAppleCalendarView.init(frame: CGRectZero)`

**Comment by patchthecode** [comment]
If thats what youre trying to do however, can you do this and tell me if it works?

Inside the `JTAppleCalendarView.swift` file, you will see the function 
```swift
init(frame: CGRect)
```
can you change it to the following?
```swift
public init(frame: CGRect)
```

If it works I will add that enhancement in the next release. But in the mean time, you will have to use it with that modification.

**Comment by fogisland** [comment]
Yes it works after adding `public` to the `init` method, I should have figured out the swift access control problem myself...thanks a lot !

I need to call `JTAppleCalendarView.init(frame: CGRectZero)` because I construct the UI all by pure code with some auto layout framework(snapkit), I don't like use storyboard/xib.

**Comment by patchthecode** [comment]
Understood. I'll make it public in the next release.
