### ISSUE TITLE
Carthage Build Error

### ISSUE THREAD

**Issue by farhanjailani** [patchthecode/JTAppleCalendar#1190]
**(Required) Version Number:**

## Description
/usr/bin/xcrun xcodebuild -workspace /Users/FarhanJailani/Documents/mobile-client-app/Goomo/Carthage/Checkouts/JTAppleCalendar/JTAppleCalendar.xcworkspace -scheme JTAppleCalendar\ iOS -configuration Release -derivedDataPath /Users/FarhanJailani/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/JTAppleCalendar/7.0.6 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/8q/8066_wt93s37mncfm9brwyr00000gq/T/JTAppleCalendar SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/FarhanJailani/Documents/mobile-client-app/Goomo/Carthage/Checkouts/JTAppleCalendar)User defaults from command line:
    IDEArchivePathOverride = /var/folders/8q/8066_wt93s37mncfm9brwyr00000gq/T/JTAppleCalendar
    IDEDerivedDataPathOverride = /Users/FarhanJailani/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/JTAppleCalendar/7.0.6

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos13.2
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

note: Using new build system
note: Planning build
note: Constructing build description
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'JTAppleCalendar iOS' from project 'JTAppleCalendar')
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'JTAppleCalendar iOS' from project 'JTAppleCalendar')

** ARCHIVE FAILED **
## Steps To Reproduce
this happens when I build the JTAppleCalendar using Carthage
## Additional Context
Im new to iOS development, any help is appreciated.

**Comment by patchthecode** [comment]
put this as  your carthage

```
github "patchthecode/JTAppleCalendar" "master"
```

**Comment by patchthecode** [comment]
released 8.0.3
This should fix the carthage tag
let me know
