### ISSUE TITLE
No luck building 8.0.2 with Carthage on iOS

### ISSUE THREAD

**Issue by kohlab** [patchthecode/JTAppleCalendar#1191]
**(Required) Version Number:**

8.0.2

## Description

Errors updating JTAppleCalendar to 8.0 with Carthage

## Steps To Reproduce

1.  Update Cartfile with:
github "patchthecode/JTAppleCalendar" ~> 8.0

2. Run "carthage update --platform iOS"

## Expected Behavior

Clean build.  Got this instead:

*** Fetching JTAppleCalendar
*** Checking out JTAppleCalendar at "8.0.2"
*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/patchthecode/JTAppleCalendar/issues/new

**Comment by patchthecode** [comment]
released 8.0.3
This should fix the carthage tag
let me know if it is still an issue

**Comment by kohlab** [comment]
Wow, that was fast!  Yep, all fixed now.  Thank you.

**Comment by patchthecode** [comment]
awesome. 🍻
