### ISSUE TITLE
Is there any way ,that I can add  footerview  for each month section

### ISSUE THREAD

**Issue by Mahesh-iOS** [patchthecode/JTAppleCalendar#1192]
**(Required) Version Number:**
8.0
## Description
Is there any way ,that I can add  footerview  for each month section
## Steps To Reproduce
Not able to add footerView
## Expected Behavior
Should be able to add footer view like as Header view 
## Additional Context
Please make it available these functionality

**Comment by patchthecode** [comment]
Not with this current version. no one had asked for it before until 6 days ago :/  here --> https://github.com/patchthecode/JTAppleCalendar/issues/1189

So i will have to have an upgrade for this.
Lets track this issue on the link above.
Closing this one.

BTW, what calendar do you have? Horizontal or Vertical?

**Comment by Mahesh-iOS** [comment]
Vertical calendar
With both header and footer

**Comment by patchthecode** [comment]
OK understood. i'll track this on the other issue mentioned above

**Comment by vadimleonov** [comment]
@patchthecode Hi! Do you have any updates with the footer?

I'm looking for a possibility to create the same weekly calendar as the iPhone have:
![image](https://user-images.githubusercontent.com/35032429/82119526-0268f200-9788-11ea-9daa-b9f810ffda52.png)

**Comment by patchthecode** [comment]
This is being tracked here -> #1189
I didnt have the time to work on it.
Im not sure if that developer implemented it
