### ISSUE TITLE
Date isn't accurate when having indate and outdate for a month view.

### ISSUE THREAD

**Issue by jcbriones** [patchthecode/JTAppleCalendar#1193]
**(Required) Version Number:** JTAppleCalendar (8.0.3)

## Description
I was trying to get the exact date for every cell through cellForItemAt function and the **cellState.date** returns date that are incorrect.

## Steps To Reproduce
Check the `Date` object before January 1, 2018 in the same month view (which contains previous month and next month). The date for dates before Jan 1, 2018 is set to December N, 2018 instead of year 2017 because it is the previous year. The same thing for month of December calendar view and shows the last few dates in December to reflect the year after.

## Expected Behavior
This should post the correct dates of the previous year if date shown before jan 1. The same thing for December and the upcoming year.

**Comment by patchthecode** [comment]
How are you trying to get the date?
What code are you using in there?

**Comment by jcbriones** [comment]
just `cellState.date` inside `func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {`

**Comment by jcbriones** [comment]
Try this 
```swift
let monthDayYearFormatter = DateFormatter()
monthDayYearFormatter.dateFormat = "EEEE, MMMM d, YYYY"

func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
    print(monthDayYearFormatter.string(from: cellState.date), cellState.dateBelongsTo)
}
```

**Comment by patchthecode** [comment]
Ok. One quick question. Are you living in the East? (need to know your region)

**Comment by jcbriones** [comment]
Yes I am.

**Comment by patchthecode** [comment]
ok, then i believe that your problem is the time zone of your date formatter.
```swift
monthDayYearFormatter.timeZone = // set it to your time zone
monthDayYearFormatter.locale = // set it to your local
```

then try printing again

**Comment by patchthecode** [comment]
try setting it to this
```swift
monthDayYearFormatter.locale = Calendar.current.locale
monthDayYearFormatter.timeZone = Calendar.current.timeZone
```

**Comment by jcbriones** [comment]
I tried setting the timezone as well but it doesn't make sense for 3 days difference. This is what I get for December.

**Comment by jcbriones** [comment]
> ```swift
> monthDayYearFormatter.locale = Calendar.current.locale
> ```

Will try this now. Wait

**Comment by patchthecode** [comment]
Do you have a same of the code?

**Comment by jcbriones** [comment]
Hmmm, weird but I tried using this
```
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .none
        dateFormatter.timeZone = Calendar.current.timeZone
        dateFormatter.locale = Calendar.current.locale
```

**Comment by patchthecode** [comment]
and did it work?

**Comment by jcbriones** [comment]
Yeah it actually did. But if I used the dateFormatter.string(from: dateHere) it doesn't work with the timeZone in place.

**Comment by jcbriones** [comment]
But anyway thanks it worked now.
