### ISSUE TITLE
https://patchthecode.com is not opening. Please check it.

### ISSUE THREAD

**Issue by commando24** [patchthecode/JTAppleCalendar#1194]
<img width="1294" alt="Screenshot 2019-12-12 at 3 28 02 PM" src="https://user-images.githubusercontent.com/15805487/70702413-09309c00-1cf4-11ea-8d4d-dd1e8533d108.png">

**Comment by patchthecode** [comment]
it should be back up now.

**Comment by commando24** [comment]
@patchthecode its still not opening.

**Comment by patchthecode** [comment]
it is up right now :( 
What region are you from?  I will report this to the webhost.

**Comment by commando24** [comment]
Thanks man. 
This was happening due to my companies firewall.
