### ISSUE TITLE
How to get the contentSize of JTACMonthView after reloading

### ISSUE THREAD

**Issue by LeeSen11** [patchthecode/JTAppleCalendar#1198]
**(Required) Version Number:** 8.0.2

## Description
i use JTACMonthView to show only one month calendar, when i change the month date, i cannot find the way to fetch it's contentSize.  So, i try to use numberOfItems(inSection:) to get the item numbers, then calculate it's height, it works. but i wonder if there is an convenient way to get it's contentSize

**Comment by patchthecode** [comment]
hmm.. sorry for the late reply. Im back to work now.
Can you let me  know what you are ultimately trying to do? 

If you let me know the whole problem then  i may have a better way than fiddling with numberOfItems in section.

**Comment by patchthecode** [comment]
closing this until user responds.
