### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by dbmrq** [patchthecode/JTAppleCalendar#120]
Hey, [once upon a time](https://github.com/Mozharovsky/CVCalendar/issues/267#issuecomment-204848700) you said you wish I'd find bugs in your library… well, you should be careful with what you wish for, haha.

I just decided to give it a try and I use Carthage. I see it's not "officially" supported (there aren't instructions in the readme and repo doesn't have that little badge), but a few people mention using it on other issues, so I gave it a try anyway and this is what I got:

```
*** Skipped building JTAppleCalendar due to the error:
Dependency "JTAppleCalendar" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/patchthecode/JTAppleCalendar/issues/new
```

**Comment by patchthecode** [comment]
Ah you remember! haha :) 

Well, for carthage support.. hmmm.
I think there is just one change i need to make for that. Making it shared or something like that.
I'll look into it.

**Comment by patchthecode** [comment]
Support has been added.
You'll have to use the master branch since the 5.0.1 release does not support it.

useage: `github "patchthecode/JTAppleCalendar" "master"`

**Comment by dbmrq** [comment]
Works like a charm, thank you! 🎉

**Comment by codeslubber** [comment]
This did not work for me. Same error, trying to build iOS only? adding master did not fix it..

**Comment by patchthecode** [comment]
yes, this just recently broke again.
will fix over the weekend.

**Comment by waterskier2007** [comment]
@patchthecode any update on this?
