### ISSUE TITLE
Date selection or highlight in JTACCellMonthView

### ISSUE THREAD

**Issue by subhashgithub** [patchthecode/JTAppleCalendar#1200]
I am able to display a year view using JTACYearView but would like to highlight a few dates displayed in JTACCellMonthView. I don't see any interfaces to make the selection of dates and please let me know if this feature is supported or I have to implement the date selection logic myself.

**Comment by patchthecode** [comment]
in this function
```swift
    func calendar(_ calendar: JTACYearView, monthView: JTACCellMonthView, drawingFor rect: CGRect, with date: Date, dateOwner: DateOwner, monthIndex index: Int) {
        f.dateFormat = "d"
        let dateString = f.string(from: date)
        
        let paragraphStyle = NSMutableParagraphStyle()
        let font = UIFont(name: "HelveticaNeue", size: 8)!
        
        
        paragraphStyle.alignment = .center
        dateString.draw(in: rect, withAttributes: [
            NSAttributedString.Key.font : font,
            NSAttributedString.Key.paragraphStyle: paragraphStyle
        ])
    }
```

we use this line 
```swift
dateString.draw(in: rect, withAttributes: [
            NSAttributedString.Key.font : font,
            NSAttributedString.Key.paragraphStyle: paragraphStyle
        ])
```

to draw in the label.
You can also draw in images such as your highselection image.  Will this work for you?

**Comment by subhashgithub** [comment]
Thank you for the response. 

I wrote my selection logic inside this method and it is working.

**Comment by MrShafiee** [comment]
Hi @patchthecode, but this function which you mentioned not be called in my code!
`func calendar(_ calendar: JTACYearView, monthView: JTACCellMonthView, drawingFor rect: CGRect, with date: Date, dateOwner: DateOwner, monthIndex index: Int) {
        f.dateFormat = "d"
        let dateString = f.string(from: date)
        
        let paragraphStyle = NSMutableParagraphStyle()
        let font = UIFont(name: "HelveticaNeue", size: 8)!
        
        
        paragraphStyle.alignment = .center
        dateString.draw(in: rect, withAttributes: [
            NSAttributedString.Key.font : font,
            NSAttributedString.Key.paragraphStyle: paragraphStyle
        ])
    }`

I follow the example code but nothing changed, I will see the year title and month title but the days are not visible in year view.

![1111](https://user-images.githubusercontent.com/19608549/85437961-a9ad2600-b58b-11ea-81fb-aaf7ebc7e0e3.png)

what should I do? do you have any suggestion?

**Comment by MrShafiee** [comment]
Just To be document for future:
If you have custom cell you should implement UIView inside it which inherit from _JTACCellMonthView_!

But after that I faced with this crash error: UICollectionViewFlowLayoutBreakForInvalidSizes
```
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
JTAppleCalendar was compiled with optimization - stepping may behave oddly; variables may not be available.
```

I created break point but it doesn't help, @patchthecode  do you have any idea?
