### ISSUE TITLE
Not correct selected position for Cell (CellState.selectedPosition())

### ISSUE THREAD

**Issue by gymbay** [patchthecode/JTAppleCalendar#1202]
**Version Number: 8.0.2**

## Description
If month ends on Sunday that method selectedPosition() on CellState returns .right for 31 and .left for 1, although this dates in range and for logic is .middle.
![Снимок экрана 2019-12-27 в 15 28 31](https://user-images.githubusercontent.com/59281730/71517097-97447f00-28bd-11ea-98ce-c4e0230bc3a3.png)

## Steps To Reproduce
Select period where middle date be Sunday and end of month.

## Expected Behavior
Expected only two balls, but here they're four.

**Comment by patchthecode** [comment]
`calendarView.rangeSelectionMode = .continuous`

**Comment by gymbay** [comment]
It's worked for me, thx.
