### ISSUE TITLE
v8.0.3 or v8.0.2 on iOS 13.2.3 or 12.1.4 range selection totally broken with no error message.

### ISSUE THREAD

**Issue by wangdu1005** [patchthecode/JTAppleCalendar#1209]
**(Required) Version Number:**
v8.0.3 v8.0.2

## Description
After upgrade to 8.0.2 and 8.0.3 to support swift 5.1 on iOS Device 13.2.3 & 12.1.4 will totally not able to range select.

Even though download Official Sample Project which also has same issue.

## Steps To Reproduce
Install official sample, go to range selection demo.

## Expected Behavior
Expect can success to select the range date.

## Additional Context
![IMG_4FA895FD551F-1](https://user-images.githubusercontent.com/6514810/72518057-71dcdc80-388f-11ea-87bf-15cd70bb5d19.jpeg)

**Comment by patchthecode** [comment]
which official example did not work?
I tried this one and there is nothing wrong with it -> https://patchthecode.com/jtapplecalendar/2tapRangedSelection.zip

I tried on iOS 13.3 simulator and it works.
Are you saying that it does not work specifically on 13.2.3 ?

**Comment by wangdu1005** [comment]
I didn't try 13.3, because many user not upgraded to it yet.
And YES, it did has issue on 13.2.3 and 12.4.1.
I also try the demo line you provided, and has more serious issue that it will crash if I re-selected range multi times. The difference of your demo with another official demo /master/SampleJTAppleCalendar. is that your demo can select range, but will crash and with wired duplicate range selection under the calendar. Another demo is totally not selectable of range feature.

This attachment is your official demo running on my real iPhone XR iOS 13.2.3.
![Screen Shot 2020-01-20 at 11 20 57 AM](https://user-images.githubusercontent.com/6514810/72696628-ee193d80-3b77-11ea-8abe-9afe1870ba83.png)

![IMG_0054](https://user-images.githubusercontent.com/6514810/72696719-55cf8880-3b78-11ea-825f-65fbe682a08f.PNG)

**Comment by patchthecode** [comment]
The demo is just an example for you to go by. If it crashes then you might have to fix or help me fix because this would be a logic error.

However, the error of it totally being unselectable, now this would be a bug that i have to fix.
Can you paste the link of which demo was not selectable?

**Comment by wangdu1005** [comment]
Thanks for your reply, here is the issue sample address. Please check it out.

https://github.com/patchthecode/JTAppleCalendar/blob/master/SampleJTAppleCalendar/Example%20Calendars/TestRangeSelectionViewController.swift

**Comment by patchthecode** [comment]
Sorry for the late reply, but i was caught up.
You are using verion 8, but you didnt change the funciton signatures.

Here they are -> https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/
Please change all the function names.

**Comment by kikikiktai** [comment]
> Sorry for the late reply, but i was caught up.
> You are using verion 8, but you didnt change the funciton signatures.
> 
> Here they are -> https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/
> Please change all the function names.

I got the same issue, already changed all function signatures but the range selection is still broken. ![IMG_0562](https://user-images.githubusercontent.com/17467668/76889844-4a22e880-68c1-11ea-8c12-5eb1aa492823.jpg) 

I even tried renaming your outdated demo (https://github.com/patchthecode/JTAppleCalendar/blob/master/SampleJTAppleCalendar/Example%20Calendars/TestRangeSelectionViewController.swift) but it doesn't work too.

I'm currently on iOS 13.3 with JTAC 8.0.3 installed.
