### ISSUE TITLE
didScrollToDateSegmentStartingWith

### ISSUE THREAD

**Issue by ialqwaiz** [patchthecode/JTAppleCalendar#121]
Hello,

I've built my calendar in a monthly style. Above that, I've added a label for the month.
I tried to use 'didScrollToDateSegmentStartingWith' to update the month when the section changes but it didn't fire at all. I'm not sure if I'm doing that the right way.

1- how can I know when the section has changed (to the next month)
2- What 'didScrollToDateSegmentStartingWith' is used for?
3- What is the right way to update the month label

Thanks.

**Comment by patchthecode** [comment]
hmm. ok.

1. What version of the calendar are you using?
2. Did you just update from a version 4.something to 5.something?
3. What is the name of the delegate function? You said it was `didScrollToDateSegmentStartingWith`, but can you write out the **full** function?

**Comment by ialqwaiz** [comment]
1. The version is (5.0.1)
2. I just tried this function in the current version
3. This is my code:

```
func calendar(calendar : JTAppleCalendarView, didScrollToDateSegmentStartingWith date: NSDate?, endingWithDate: NSDate?) {
        print("segment changed..")
        updateMonthLabel()
    }
```

- The scrolling is done by swiping right and left. The "segment changed.." is note printed in the console.

Thanks.

**Comment by patchthecode** [comment]
So, i am a bit confused now. Is it working now?
Is the label changing?

try printing the date. If printing the date works, then all is fine right?

**Comment by patchthecode** [comment]
You have not responded for 2 days. I will assume this issue is resolved.  If it is not, feel free to re-open this issue.

**Comment by ialqwaiz** [comment]
Sorry for the delay, I just saw the reply.

I tried to check if it fires at all or not. as in the code above, I put `print("segment changed..")` command inside the function but it wasn't printed when I swiped the calendar, meaning that that function wasn't fired at all.

Thanks for your time.

**Comment by patchthecode** [comment]
You are using an incorrect function if it is not called.

you said you are using this:
```swift
func calendar(calendar : JTAppleCalendarView, didScrollToDateSegmentStartingWith date: NSDate?, endingWithDate: NSDate?)
```

When it should be this:
```swift
func calendar(calendar: JTAppleCalendarView, didScrollToDateSegmentStartingWithdate startDate: NSDate, endingWithDate endDate: NSDate)
```

That is why I asked you if you gust upgraded from a version 4.something to 5.something.

**Comment by ialqwaiz** [comment]
Thanks for that.
I'll try it today and come back with the result.
