### ISSUE TITLE
Cell not selected right away on tap

### ISSUE THREAD

**Issue by seancze** [patchthecode/JTAppleCalendar#1211]
**(Required) Version Number:** Latest should be 8.0.3, just installed it yesterday

## Description
Hi, I was following the tutorial on implementing 'Regular Selection' to the calendar. However, upon running XCode, the cell's background does not change to red upon selection. Instead, what occurs is that after scrolling to the next month and scrolling back to the previous month, the cell's background changes to red / shows that it has been selected.

## Steps To Reproduce
I've attached the code within my extension viewController for JTACMonthViewDataSource, JTACMonthViewDelegate which should be exactly the same as that in the tutorial

    func handleCellTextColor(cell: DateCell, cellState: CellState) {
       if cellState.dateBelongsTo == .thisMonth {
          cell.dateLabel.textColor = UIColor.black
       } else {
          cell.dateLabel.textColor = UIColor.gray
       }
    }
    
    func handleCellSelected(cell: DateCell, cellState: CellState) {
        if cellState.isSelected {
            cell.selectedView.layer.cornerRadius =  13
            cell.selectedView.isHidden = false
        } else {
            cell.selectedView.isHidden = true
        }
    }
    
    func configureCell(view: JTACDayCell?, cellState: CellState) {
       guard let cell = view as? DateCell  else { return }
       cell.dateLabel.text = cellState.text
        handleCellTextColor(cell: cell, cellState: cellState)
        handleCellSelected(cell: cell, cellState: cellState)
        print("Cell selected")
    }
    
    func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
    }

    func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState) {
        configureCell(view: cell, cellState: cellState)
    }
    
    
    func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
       configureCell(view: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
       let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
       self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
       return cell
    }

## Expected Behavior
Like the tutorial in Regular Selection

## Additional Context
I'm not sure if this could be the issue but I've made a reference outlet from the calendarView in storyboard to my code so that I can change the size of the calendarView programmatically

    @IBOutlet weak var myCalendar: JTACMonthView!
        myCalendar.autoresizingMask = .flexibleWidth
        myCalendar.contentMode = .center
        myCalendar.frame = CGRect.init(x: 0.0, y: detailsStackView.frame.minY, width: UIScreen.main.bounds.size.width, height: detailsStackView.frame.size.height)

**Comment by seancze** [comment]
Yes, I've been referencing the code throughout.
Specifically, I followed these 2 links
https://patchthecode.com/jtapplecalendar-home/calendar-from-scratch/
https://patchthecode.com/jtapplecalendar-home/regular-selection/

**Comment by patchthecode** [comment]
hmm, do you have a sample app which reproduces this that i can run?
provide one and i will take a look.

The code in the example on the website works. So i want to see what specifivally in your sample app is doing this.

**Comment by seancze** [comment]
Here you go, thank you!

[calendarTrial.zip](https://github.com/patchthecode/JTAppleCalendar/files/4089740/calendarTrial.zip)

As mentioned, the application only shows that the cell has been selected once you have scrolled down to the next month and scrolled back to the previous view.

**Comment by patchthecode** [comment]
you migrated to version 8+
but you didnt follow up on the function name changes. You are still using version 7+ functions.

follow all the function changes here -> https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

specifically for this  case, your didSelect function should be changed to this ->
```swift
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
        configureCell(view: cell, cellState: cellState)
    }
```

**Comment by patchthecode** [comment]
will close this issue.
