### ISSUE TITLE
Cell selection problems after select Large range of dates

### ISSUE THREAD

**Issue by egonza26** [patchthecode/JTAppleCalendar#1214]
**Version Number: 8.0.2:**

## Description

After selecting a Large range of dates, the cell selection brokes, and it only works for some cells. Debugging the app I notice that sometimes the calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) is not called at all. The delegate works again when I tap a date that is inside the range selection.

The didSelect function already has set the triggerSelectionDelegate as false.

I also follow the "2 Tap Ranged Selection" example as base for my project.

## Steps To Reproduce

1. Select at least a range date of two dates.
2. Try to select another data out of the range.

## Expected Behavior

The selected range should be deselected and the date tapped should look as selected.

## Additional Context

Here are my didSelectDate and shouldSelectDate functions.

```
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {
        let order = Calendar.current.compare(viewModel.currentDate, to: date, toGranularity: .day)
        guard order == .orderedAscending || order == .orderedSame else { return }

        if let startDate = viewModel.startDate {
            viewModel.endDate = calendar.selectedDates.last
            calendar.selectDates(from: startDate, to: date, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
        } else {
            viewModel.startDate = date
        }

        configureSelectedDates()
        configureCell(view: cell, cellState: cellState, date: date)
    }
```

```
func calendar(_ calendar: JTACMonthView,
                  shouldSelectDate date: Date,
                  cell: JTACDayCell?, cellState: CellState,
                  indexPath: IndexPath) -> Bool {
        if twoDatesAlreadySelected
            && cellState.selectionType != .programatic
            || viewModel.startDate != nil
            && !calendarView.selectedDates.isEmpty
            && date < calendarView.selectedDates[0] {
            viewModel.startDate = nil
            let retval = !calendarView.selectedDates.contains(date)
            calendarView.deselectAllDates()
            return retval
        }

        return true
    }
```

**Comment by patchthecode** [comment]
That should select function looks extremely complex.
The two tap selection example works as expected.

Can you provide a buildable sample app that reproduces this?
I have a number of sample apps to check over the weekend.

**Comment by egonza26** [comment]
Hi, thanks for the response.

The problem was in the `prepareForReuse()` that I use in my custom cell.

I'm gonna close the issue. Thank you.
