### ISSUE TITLE
How to highlight today

### ISSUE THREAD

**Issue by fury21** [patchthecode/JTAppleCalendar#1218]
**(Required) Version Number:**
8.0.3

## Description
I need to highlight today in the calendar, and even that the selection or deselection does not matter

## Steps To Reproduce
```swift
func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {

<some code>
        
        if testCalendar.isDateInToday(date)  {
            cell.contentView.cornederRadius(borderWidthAndColor: (width: 2, color: .red))
        }
        
        return cell
    }
```
## Expected Behavior
The today's cell is highlighted always

## Additional Context
But several different cells are radnom highlighted and when I switch to another month this happens too

**Comment by patchthecode** [comment]
> The today's cell is highlighted always

But what is actually happening?

**Comment by fury21** [comment]
A'm add print to func 
        if testCalendar.isDateInToday(date)  {
            print("\nDATE: ", date)
            cell.contentView.cornederRadius(borderWidthAndColor: (width: 2, color: .red))
        }

And that's what I got in console:
DATE:  2020-02-05 21:00:00 +0000
DATE:  2020-02-05 21:00:00 +0000
DATE:  2020-02-05 21:00:00 +0000

and in display аfter loading:
![image](https://user-images.githubusercontent.com/30409500/73944073-fc4eb400-4902-11ea-81be-d6a84851cca3.png)

After I changed the month to the next and back:
![image](https://user-images.githubusercontent.com/30409500/73944098-0a043980-4903-11ea-9094-4449731fc5d5.png)

**Comment by patchthecode** [comment]
This calendar is a UICOllectionView.
Cells are reused.
Therefore your code should be 
```swift
if testCalendar.isDateInToday(date)  {
   cell.contentView.cornederRadius(borderWidthAndColor: (width: 2, color: .red))
} else {
   // Remove the selection
}
```

**Comment by fury21** [comment]
Facepam)) Ok, i edit my code:
 if testCalendar.isDateInToday(date)  {
            cell.contentView.cornederRadius(borderWidthAndColor: (width: 2, color: .red))
        } else {
            // Cose reusable cell
            cell.contentView.cornederRadius(borderWidthAndColor: (width: 0, color: .red))
        }

It looks good, but for now, in January 2020, today is still highlighted

**Comment by patchthecode** [comment]
i do not understand what you said. Do you have an image with the new problem.

**Comment by fury21** [comment]
The current day in the current month is displayed correctly, but why is the same day shown in the last month?

Current moth
![Снимок экрана 2020-02-07 в 10 33 53](https://user-images.githubusercontent.com/30409500/74010038-965f3c80-4995-11ea-9ec7-7a67f559f322.png)

Previous month
![Снимок экрана 2020-02-07 в 10 34 06](https://user-images.githubusercontent.com/30409500/74010040-98290000-4995-11ea-9413-a347d1649288.png)

**Comment by patchthecode** [comment]
Because it is today's date.
If you do not want it to be displayed in the `outDates` or `inDates`, then just add this to your condition:

```swift
if testCalendar.isDateInToday(date) && cellState.dateBelongsTo == .thisMonth  {
   cell.contentView.cornederRadius(borderWidthAndColor: (width: 2, color: .red))
} else {
   // Remove the selection
}
```

**Comment by patchthecode** [comment]
you can close this issue if resolved.
