### ISSUE TITLE
Calendar of months only

### ISSUE THREAD

**Issue by PNepikov** [patchthecode/JTAppleCalendar#1219]
First, i would like to thank you for your calendar!
I beg your pardon, i have a question, not a issue
Is it possible to make a calendar of months only?
![Screenshot 2020-02-07 at 14 14 44](https://user-images.githubusercontent.com/37261789/74025375-daae0500-49b4-11ea-82dc-4ec313d33a2e.png)

thanks for your reply

**Comment by patchthecode** [comment]
No. But this can be done very very easily with a simple UICollectionView.
This lib handles the other types of month views.

**Comment by PNepikov** [comment]
Thank you for your advice
