### ISSUE TITLE
Unable to set the CalendarView delegate

### ISSUE THREAD

**Issue by pisupatis** [patchthecode/JTAppleCalendar#122]
Hi,
I have created the JTAppleCalendar.framework and imported it into my sample project.

The calendar view gets created but the JTAppleCalendarViewDelegate methods are not fired.

I did set the `calendarView.delegate = self and calendarView.datasource = self` and defined the `extension ViewController:JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource`.

Apparently, the data source methods are fired but not the view delegate methods where the dates are populated in the cells. Due to this the calendar view show only 1s for all the dates.

Any clue what am I missing here? Your support is much appreciated.

Thanks in advance!!

**Comment by patchthecode** [comment]
If you are online, can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
If you are unable to join chat, did you just update from a lower version 4.something? 

The method will always fire. It will only _not_ fire if you have the wrong name for the delegate method. You will have to tell me the full name of the function you are using for the delegate method.

**Comment by pisupatis** [comment]
Hi,
Thank you for your quick response. Yes, the delegate methods are old ones not the ones from Swift 3 branch. I didn't realize the function signature changes in the Swift 3 branch.

Really appreciate your quick response. This library is really awesome 💯 👍 

Best regards!!

**Comment by patchthecode** [comment]
ah yes, XCode made a bunch of changes for the signatures of swift 3. 
Cheers.
