### ISSUE TITLE
How to page calendar with button in reuseable headerView?

### ISSUE THREAD

**Issue by AcousticBlue** [patchthecode/JTAppleCalendar#1221]
**8.0.2**

## Description

Currently my calendar scrolls with swiping - however, I'd like to add the capability to move one month via buttons on the reusable header as in below

<img width="282" alt="Screen Shot 2020-02-10 at 4 00 08 PM" src="https://user-images.githubusercontent.com/2185926/74194183-6c6c7b00-4c1e-11ea-9fd7-d46b523066ac.png">

would i just use a protocol and refreshWithDates? or can i access the paging directly

Thanks,

**Comment by patchthecode** [comment]
```swift
calendarView.scrollToSegment(.next)
calendarView.scrollToSegment(.previous)
calendarView.scrollToSegment(.start)
calendarView.scrollToSegment(.end)
```
