### ISSUE TITLE
Time issues by week

### ISSUE THREAD

**Issue by iyinin** [patchthecode/JTAppleCalendar#1222]
![IMG_0141](https://user-images.githubusercontent.com/44601211/74250474-99f01c00-4d25-11ea-86de-31d55adf5167.jpg)

**Comment by iyinin** [comment]
let parameters = ConfigurationParameters(startDate: startDate!,
                                                endDate: endDate!,
                                                numberOfRows: 1,
                                                calendar: Calendar.current,
                                                generateInDates: .forAllMonths,
                                                generateOutDates: .off
                                                firstDayOfWeek: .monday,
                                                hasStrictBoundaries: false)

**Comment by patchthecode** [comment]
This is the correct setup for a single row calendar

**Comment by patchthecode** [comment]
closing this issue.
Let me know if other problems.
