### ISSUE TITLE
Don't refresh selection in calendar

### ISSUE THREAD

**Issue by Legasquare90** [patchthecode/JTAppleCalendar#1223]
**(Required) Version Number:** 8.0.3

## Description
When I tap in one day cell in a calendar, the cell is not shown as selected. However, if I scroll calendar after tap the cell, and then I return to scroll to the day tapped, this cell it's now marked. I suppose that there is some issue refreshing the view after select a cell. 

Also, the methods `func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState)` and `func calendar(_ calendar: JTACMonthView, didDeselectDate date: Date, cell: JTACDayCell?, cellState: CellState)` are not called.

You can reproduce this in your own test project, is happening exactly same

**Comment by patchthecode** [comment]
sounds like you upgraded to version 8+
but didnt change the function name.

From version 7 to version 8, the version names have been changed.
see the name changes here -> https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

closing this issue. Let me know if you are still stuck.

**Comment by Legasquare90** [comment]
I change the name of the methods like you mention in the migration guide, but it also fails. Check **your own project**!! In **your project** fails!! Check the test project and you can prove the issue about the selected cells.

While this fails, I'm going to continue using the last 7.1 version

**Comment by patchthecode** [comment]
I have many sample projects.
In which project does it fail? Can you tell me where to find the project you ran?

**Comment by Legasquare90** [comment]
Yes! From the master branch, open the "SampleJTAppleCalendar" project, and run it in Xcode (iPhone 8 simulator; iOS 13.3). Select "Range selection" option, and select one date; this date is not marked, but if you move from another month and return to the first, the date is now marked.

I record a video showing this and attached to this message

[Grabación de pantalla 2020-02-14 a las 14.52.06.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/4204713/Grabacion.de.pantalla.2020-02-14.a.las.14.52.06.mov.zip)

**Comment by patchthecode** [comment]
The code that you see in there is also not updated to the latest version.
If you do the same solution i mentioned above, it works correctly.

Can you paste me the didSelect and didDeselect code of your app?

**Comment by Legasquare90** [comment]
Ehhh... But, in your code, the name methods are changed as you specified in the first comment, and XCode shows that JTAppleCalendar is in the version 8.0.3 according to Swift Package Dependencies. So, actually, the code of your example is updated...

I'm sorry, but I can't paste my code due to NDA :(

![Captura de pantalla 2020-02-17 a las 13 34 26](https://user-images.githubusercontent.com/11866917/74654438-8f50df00-518a-11ea-841e-7a82586b2ad2.png)

**Comment by patchthecode** [comment]
i do not understand why there is so much confusion...
i posted the link to the renamed functions.
the renamed function is this

```swift
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath)
```

the old function is this
```swift
func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState)
```

The function names are different. `indexPath` is missing in one.
Even in the code image sample you pasted, the function name in there is  not changed.
I am confused by what you are asking. (unless i miss something?).

**Comment by Legasquare90** [comment]
Ohhhh!!! I see the confusion now... My fault, I'm sorry. I didn't see the change in indexPath parameter; reading your migration guide, I think that you only rename the functions, not that you added a new parameter (maybe, can you improve the documentation?)

I will try it again when finish other tasks that I have and comment you the result. Thanks!!

**Comment by patchthecode** [comment]
awesome haha.
yea, its easy to miss.
once i get the time, i'll make it clearer in the documentation.
