### ISSUE TITLE
Can I have one column and vertical scrolling?

### ISSUE THREAD

**Issue by pxc052** [patchthecode/JTAppleCalendar#1224]
Is it possible to make calendar with 1 column and vertical scrolling.
![Screen Shot 2020-02-13 at 9 25 41 AM](https://user-images.githubusercontent.com/30617030/74396216-e598e780-4e43-11ea-85af-0fb5e2a98dd1.png)

I have changed calendar width to 100 and scrollDirection to vertical, but the cell still display horizontally and overlap each other.

**Comment by patchthecode** [comment]
unfortunately no.
7 columns minimum
