### ISSUE TITLE
Calendar Crashes at runtime

### ISSUE THREAD

**Issue by mvargas7476** [patchthecode/JTAppleCalendar#1225]
[RWJH Magnet.zip](https://github.com/patchthecode/JTAppleCalendar/files/4200626/RWJH.Magnet.zip)

**(Required) Version Number:**

## Description
Trying to design an app that displays a calendar of events for a school. I have set up everything that I think I need, using the steps online. However I have a problem with the ibOutlets connecting to the view I believe. If I disconnect those pieces then the code runs but doesn't display anything. I have emailed you about this issue and not I am finally posting it on Git. Thank you so much!

## Steps To Reproduce
I have attached the .zip file of the app
## Expected Behavior
Expecting to display the calendar dates, with the 4 events that are in there. I have not downloaded the school's calendar yet. although I do have the link.

**Comment by patchthecode** [comment]
you forgot to set the module of your class on story board
<img width="262" alt="Screen Shot 2020-02-18 at 9 00 53 AM" src="https://user-images.githubusercontent.com/2439146/74742795-3ede8d80-522d-11ea-9502-47b44d035854.png">
