### ISSUE TITLE
JTACMonthView.scrollToDate() doesn't take into account month header

### ISSUE THREAD

**Issue by rayx** [patchthecode/JTAppleCalendar#1229]
## Version Number

Master branch

## Description

I followed steps on [wiki](https://github.com/patchthecode/JTAppleCalendar/issues/944) to create an "inside month header". Then I followed the suggestion [in a discussion](https://github.com/patchthecode/JTAppleCalendar/issues/944) to use scrollToDate() to scroll to today on App startup:

    class CalendarViewController: UIViewController {
        @IBOutlet weak var calendarView: JTACMonthView!
     
        override func viewDidLoad() {
            super.viewDidLoad()
            calendarView.scrollToDate(Date(), animateScroll: false)
        }
    }

It worked but scrolled down a bit more than it should and make the month header disappear on screen (I tried setting animatedScroll to true or false, it didn't change the behavior). I managed to correct the behavior by passing a hardcoded offset:

    - calendarView.scrollToDate(Date(), animateScroll: false)
    + calendarView.scrollToDate(Date(), animateScroll: false, extraAddedOffset: CGFloat(-50))

(I doubt if there is a good way to calculate an accurate offset value. I got it by experiments, starting from the height of header section).

I wonder why scrollToDate() doesn't take into account header? A bug?

**Comment by patchthecode** [comment]
it should have stopped at the header.
Have you tried the sample project here? https://patchthecode.com/jtapplecalendar/headers.zip
It correctly stops at the header.

This sample is a Horizontal calendar.
To make it vertical, go to the viewDidLoad function and change the first line to this
```swift
calendarView.scrollDirection = .vertical
```

**Comment by rayx** [comment]
@patchthecode Thanks for your quick response. The sample project worked fine indeed. So I compared its code with mine and found it was this line that made the difference:

    calendarView.scrollingMode   = .stopAtEachCalendarFrame

I debugged my code and found the variable value is `.none`. Adding the above line fixed the issue. 

But that confused me a bit, because although I didn't set that property before, I set `isPagingEnabled` to true and got similar behavior (except the issue I reported). So I searched the code and found the following in `JTACMonthView.setupNewLayout()`:

        #if os(iOS)
            if isPagingEnabled {
                scrollingMode = .stopAtEachCalendarFrame
            } else {
                scrollingMode = .none
            }
        #endif

I think this issue is the code doesn't work as expected. The above code is executed when `JTACMonthView` is instantiated. On the other hand, however, `isPagingEnabled` property is usually set in view controller's `viewDidLoad()`. At that time, all sub views (including `JTACMonthView`) have been instantiated. That means, `isPagingEnabled` is always `false` in above code. 

Note: in my case I set `isPagingEnabled` in IB by using KVO and got the same issue (`JTACMonthView.isPagingEnabled` value wasn't used in above code).

So I think this is a minor bug? I'm not sure if it's possible to move the above code to another function and execute it after user set `isPagingEnabled`? Otherwise it's perhaps better to remove it since it's useless and modify tutorial to ask user to set `scrollingMode` explicitly? Just my thoughts (I'm new to iOS development).

**Comment by patchthecode** [comment]
Due to recent events, I am not getting back to this.

.stopAtEachFrame - behaves as expected.  It respects the frame of each month. It will scroll a whole frame to a month with its header included.

.none - also behaves as expected. None will not respect the months frame. It will only respect the date. Therefore scrolling to date with a scrollingMode of *none* will scroll to the date and not the header.

If you want to get the effect you desire, then do this
```swift
calendarView.scrollingMode = .stopAtFrame
calendarView.scrollToDate( Date() )
calendarView.scrollingMode = .none
```
```

**Comment by rayx** [comment]
Hi @patchthecode Thanks for the explanation. My point was not that `.stopAtEachCalendarFrame` and `.none` didnt' work as expected, but JTCalendar Code didn't translate `isPagingEnabled` property value (set by user) to them. Thai said, it's nit at most. Feel free to close the question if you'd like.

**Comment by patchthecode** [comment]
Ah.
I understand now.

So are you saying that the library should also respond to when a user manually sets the value `isPagingEnabled` ?

**Comment by rayx** [comment]
Yes, that's what I meant. I brought the issue up because I thought the following code in JTACMonthView.setupNewLayout() intended to do that but didn't work.

    #if os(iOS)
        if isPagingEnabled {
            scrollingMode = .stopAtEachCalendarFrame
        } else {
            scrollingMode = .none
        }
    #endif

**Comment by patchthecode** [comment]
I think this issue is now fixed to your liking.
If you set the following on `ViewDidLoad()`
```swift
calendarView.isPagingEnabled = true 
```

The calendar should respect it and set it to `stopAtEachCalendarFrame`

**Comment by patchthecode** [comment]
Thanks for helping me understand this.
