### ISSUE TITLE
API to check if date is today

### ISSUE THREAD

**Issue by rayx** [patchthecode/JTAppleCalendar#1231]
## Version Number:

Mater branch.

## Description

I read [here](https://github.com/patchthecode/JTAppleCalendar/issues/474) there used to be `JTACMonthView.isDateInToday()` method to check if the value of `CellState.date` is today, but I can't find it in latest code. I wonder what's the current API to do it?

I'm currently using this workaround in my code:

    if cellState.date == Calendar.current.startOfDay(for: Date()) {
        ...
    }

**Comment by patchthecode** [comment]
You check if a date is today using Swifts `Calendar` class.
This lib does not provide this function as it is already available in Swift framework.

In the response you pointed to, i was simply replying to the person's code.
He probably attached a protocol method unto the calendar to do what i just described above under the hood.

**Comment by rayx** [comment]
What you said makes sense to me. The reason why I asked was because the date in JTACCalendar is a bit special in that it doesn't contain hour, minute and second components. They are always set to 0 in the code. In my opinion, this is implementation details that should be encapsulated by API. That said, I don't have strong opinion on this but just wanted to check if I was missing something. I'll close the issue.
