### ISSUE TITLE
Toggling between week view and Month View

### ISSUE THREAD

**Issue by sbowl001** [patchthecode/JTAppleCalendar#1232]
**(Required) Version Number:  8.0.2**

## Description
My month view has indates, and as weekview doesn't support indates, that setting is off. Toggling between month view to a week view works as expected. 
However, when I click from week view to month view, the indates that are supposed to be showing on month view disappear. 
## Steps To Reproduce
This is code that I have that may be related to the issue: 
``` @IBAction func toggleMonthView(_ sender: Any) {
        if numberOfRows == 6 {
            self.calendarViewHeightConstraint.constant = 58.33
            self.numberOfRows = 1
            UIView.animate(withDuration: 0.5, animations: {
                self.calendarView.layoutIfNeeded()
            }) { completed in
                DispatchQueue.main.async {
                    self.calendarView.reloadData(withAnchor: Date())
                }
                
            }
        } else {
            self.calendarViewHeightConstraint.constant = 350
            self.numberOfRows = 6
            
            UIView.animate(withDuration: 0.5, animations: {
                self.view.layoutIfNeeded()
                DispatchQueue.main.async {
                    self.calendarView.reloadData(withAnchor: Date())
                }
                
            })
        }
    }
}
extension CalendarMainViewController: JTACMonthViewDataSource {
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        let startDate = formatter.date(from: "2020 01 01")!
        let endDate = Date()
        if numberOfRows == 6 {
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: numberOfRows, generateInDates: .forAllMonths,generateOutDates: .tillEndOfRow)
        } else {
            return ConfigurationParameters(startDate:    startDate,endDate:endDate,numberOfRows: numberOfRows,generateInDates: .forFirstMonthOnly,generateOutDates: .off,hasStrictBoundaries: false)
        }
    }
}```
## Expected Behavior

## Additional Context

**Comment by patchthecode** [comment]
have you looked at the toggle week/month example?

**Comment by sbowl001** [comment]
Yes, I based it off that one.

**Comment by patchthecode** [comment]
Does the error that you are seeing happen on that sample project as well?

**Comment by sbowl001** [comment]
Yes, I just downloaded again to make sure I hadn't messed up something on the code.  On the sample project from the tutorial I can see the same behavior.  The original month view has inDates, after the toggle it goes to weekview, but upon toggling again to come back to the monthview the inDates disappear

**Comment by sbowl001** [comment]
These screenshots are from the sample project. 
![Screen Shot 2020-03-06 at 8 34 50 PM](https://user-images.githubusercontent.com/32507035/76084027-f7584f80-5fe9-11ea-9cf5-4b6d9246e3df.png)
![Screen Shot 2020-03-06 at 8 34 57 PM](https://user-images.githubusercontent.com/32507035/76084034-fcb59a00-5fe9-11ea-8e64-2de147a81da0.png)

**Comment by patchthecode** [comment]
ok. i will check this out over the weekend.

**Comment by sbowl001** [comment]
Thanks!

**Comment by sbowl001** [comment]
Any luck by chance?

**Comment by patchthecode** [comment]
Real sorry about this.
Events made me late to this.
I hope you are not still experiencing this issue.

relooking at it now.

**Comment by patchthecode** [comment]
When i download the sample project. I do not experience this.
Here is the image

<img width="300" alt="calendararchitecture" src="https://user-images.githubusercontent.com/2439146/79981590-eddc5700-8472-11ea-8920-f63c5c4c61e1.gif">

**Comment by patchthecode** [comment]
closing this until user responds.
Assuming it is resolved.
