### ISSUE TITLE
Touch down deselects old date, touch up selects new date; causes unwanted behavior with long tap

### ISSUE THREAD

**Issue by rvirta** [patchthecode/JTAppleCalendar#1233]
**(Required) Version Number:** 8.0.2

## Description
When long tapping an unselected date, the selected date deselects itself for an instant and then selects itself again. This causes the date selected indicator view to flash off, which doesn't look very good.

## Additional Context
It seems that touch down gesture deselects the currently selected date, and touch up selects the new date. This seems to cause the flashing with long taps. Is this intended behavior, and if it is, is there a setting to change it?

![calendar](https://user-images.githubusercontent.com/13588210/76173306-06d0c780-61a7-11ea-8850-d5a3499a170e.gif)
It's hard to see in the video, but in the first part I long tap another cell and the selected cell flashes. In the second part I've disabled the long press recognizer and click down on the new date (previously selected date's indicator disappears), and when I release the click the new date is selected.

I subscribe to isSelected in the cell to set the indicator views:
```
override var isSelected: Bool {
        didSet {
            if self.isSelected == true {
                daySelectedIndicator.isHidden = false
            } else {
                daySelectedIndicator.isHidden = true
            }}}
```

**Comment by patchthecode** [comment]
Read problem #2 on this link and let me know if maybe this applies? https://github.com/patchthecode/JTAppleCalendar/issues/553

**Comment by rvirta** [comment]
Thanks, I'll look into it.
If cellState.isSelected is preferred, is there a way to access it from inside the cell's class? I haven't figured that out yet.
Thanks again!

**Comment by rvirta** [comment]
I don't know if there's a better way, but I now pass the cellState on to the cell subclass when setting up, displaying, selecting and deselecting, and subscribe to self.cellState.isSelected in stead of self.isSelected, and it solved the problem.
Thanks!

**Comment by patchthecode** [comment]
@rvirta thats the thing. I have been awaiting input from the community for a better solution for a long time. Still waiting 😅

**Comment by patchthecode** [comment]
glad your problem is fixed however. Will close this.
