### ISSUE TITLE
Deselected cell's UI doesn't always get updated

### ISSUE THREAD

**Issue by rs658726** [patchthecode/JTAppleCalendar#1234]
**(Required) Version Number: 8.0.3**

## Description
I  have configured my calendar to select a single date (no multiple dates/range selections allowed). I also have paging enabled. 

When I select a date, the previously selected date doesn't always get updated, so I end up with 2 cells highlighted. It seems to be a problem with cellState.

## Steps To Reproduce
1. Select an outdate (from next month for example)
2. Scroll to next month - selected date becomes part of current month.
3. Select a different date from the same month. You'll notice that previously selected date doesn't get deselected.

## Expected Behavior
Since I'm using a single selection calendar view, I expect a single cell highlighted when I make a selection.

**Comment by patchthecode** [comment]
Are you sure you are not seeing outDates/inDates ?
and if not,
have you followed the selection tutorials? There is a sample app there with simple selection on patchthecode.com

**Comment by rs658726** [comment]
Hey, thanks for getting back to me.

I have looked at the tutorial and my code seems to be accurate. 

I'm not sure if my description of the issue is clear so here it is again:
For a single selection calendar where paging is enabled, select an outdate from the current month of March -- April 2 for example. Then swipe to next month (April). You'll notice that April 2 is highlighted as expected. Now select a date in current month (April 14 for example); you'll end up with 2 dates highlighted (April 2 and 14) which is an incorrect behavior.

**Comment by patchthecode** [comment]
Can you paste me your didSelect function and your willDisplayfunction?

**Comment by rs658726** [comment]
Sure, here it is:

`    func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "DateCell", for: indexPath) as! DateCollectionViewCell
        
        cell.dateLabel.text = numberFormatter.string(from: NSNumber(value: Int.parse(from: cellState.text)!))
        
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelected(view: cell, cellState: cellState, at: indexPath)

    }
`

`    func calendar(_ calendar: JTACMonthView, didSelectDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {

        combine(date: date, time: timePicker.date)
        handleCellSelected(view: cell, cellState: cellState, at: indexPath)
        handleCellTextColor(view: cell, cellState: cellState)
    }`

`    func handleCellSelected(view: JTACDayCell?, cellState: CellState, at indexPath: IndexPath) {
        guard let validCell = view as? DateCollectionViewCell else { return }
        
        if cellState.isSelected && cellState.date >= today && cellState.dateBelongsTo == .thisMonth {
            validCell.selectionView.isHidden = false
            validCell.selectionView.backgroundColor = themeColor
            validCell.selectionView.layer.cornerRadius = cellSize/2
        } else {
            validCell.selectionView.isHidden = true
            if let cell = calendar.cellForItem(at: indexPath) as? DateCollectionViewCell {
                cell.selectionView.isHidden = true
            }
        }
    }
    
    func handleCellTextColor(view: JTACDayCell?, cellState: CellState) {
        guard let validCell = view as? DateCollectionViewCell else { return }
        if cellState.isSelected && cellState.date >= today && cellState.dateBelongsTo == .thisMonth {
            validCell.dateLabel.textColor = .white
        } else if cellState.isSelected && cellState.date >= today && cellState.dateBelongsTo != .thisMonth {
            validCell.dateLabel.textColor = themeColor
        } else if cellState.date >= today && cellState.dateBelongsTo == .thisMonth {
            validCell.dateLabel.textColor = UIColor(named: "0x000000")
        } else if cellState.date >= today {
            validCell.dateLabel.textColor = UIColor(named: "0xA0A0A0")
        } else {
            validCell.dateLabel.textColor = UIColor(named: "0xD4D4D4")
        }
    }`

**Comment by patchthecode** [comment]
I think your bug is in the willDisplay function.

```swift
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "DateCell", for: indexPath) as! DateCollectionViewCell
```

You should not dequeue a cell inside there. You already have a cell instance from the function.

**Comment by rs658726** [comment]
Good catch! Works as expected now. Thank you.

**Comment by patchthecode** [comment]
awesome. 🎉
