### ISSUE TITLE
Issue with single date selection

### ISSUE THREAD

**Issue by ohthatsjhall** [patchthecode/JTAppleCalendar#1237]
**(Required) Version Number:** 8.0.3

## Description
`calendar.deselectAllDates()` has no effect once a new date is selected. `calendar.allowsMultipleSelection = false` is ignored. 

I can confirm that I am on 8.0.3 and I am using the updated delegate methods.

**Comment by ohthatsjhall** [comment]
I've been stuck on this issue for about 6 hours and solved it seconds after I posted. It works like that sometimes....

**Comment by patchthecode** [comment]
haha. cool
