### ISSUE TITLE
Duplicate Dates when in Week Mode

### ISSUE THREAD

**Issue by alexjameslittle** [patchthecode/JTAppleCalendar#1238]
**(Required) Version Number:** 8.0.3

## Description
When configuring the calendar for week view (one row) as shown in your example with the exact parameters, there is duplicated dates being created. 

in `willScrollToDateSegmentWith` outputting `visibleDates.monthDates` gets this output...clearly there is duplicate dates here:

[https://gist.github.com/alexjameslittle/a313b82e8d6f62aa4090340a31e2b5e4](url)

<img width="397" alt="Screenshot 2020-03-26 at 15 10 19" src="https://user-images.githubusercontent.com/25927944/77662663-10627980-6f74-11ea-8a77-747795ec67ab.png">

## Steps To Reproduce
`return ConfigurationParameters(startDate: startDate,
                                           endDate: endDate,
                                           numberOfRows: 1,
                                           generateInDates: .forFirstMonthOnly,
                                           generateOutDates: .off,
                                           hasStrictBoundaries: false)`

## Expected Behavior
There should not be duplicated dates

**Comment by patchthecode** [comment]
do you have a sample app reproducing this?

**Comment by alexjameslittle** [comment]
I believe it's to do with the formatting of dates, we can close this...I'm using SwiftDate library, when formatting in a sample app without SwiftDate it works as expected :) Will try in my main project now

**Comment by patchthecode** [comment]
awesome. cool.
