### ISSUE TITLE
How can I use pod file for Swift 3?

### ISSUE THREAD

**Issue by xoniq** [patchthecode/JTAppleCalendar#124]
Hi!

I want to install this calendar using cocoapods, but is the Swift 3 branch also available?
If not; what is de best practice to install the Swift 3 version?

**Comment by patchthecode** [comment]
Swift 3 branch is available.

but its not an official release yet.
To use it, put this in your podfile.



`pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'Swift3'`

**Comment by xoniq** [comment]
Thanks! That was what I was looking for. I'm quite new to pod files (previously just dragged stuff from source, but is time-wasting) and didn't know how to use it on a Git branch.

**Comment by patchthecode** [comment]
cool. cheers 👍
