### ISSUE TITLE
App is crashing when running without xCode

### ISSUE THREAD

**Issue by mirazambem** [patchthecode/JTAppleCalendar#1240]
Good morning guys))

I really need your help right now, I have created Xcode project using Russian 1C software and when I am trying to run ios app using x code it's running no problem, but when I try to run from the iPhone itself is crashing

Below is the link to Xcode project

https://drive.google.com/open?id=1soSV2h4LNmb-ARrr79N-3FPgr0SOrq2k

Thanks, fo help beforehand

**Comment by patchthecode** [comment]
`using Russian 1C software `
What is this?  

And also, what does the crash log say?

**Comment by mirazambem** [comment]
Hey) correct this is Russian 1C, problem is that i cant see crash logs on the phone

**Comment by patchthecode** [comment]
I do not know what the russian 1C is.

Also, you will need to have a crash analytic in your app.
Because with crash logs, there is no way i can tell you what happened.

**Comment by patchthecode** [comment]
Closing this until further user input.
If you have any logs let me  know and i will reopen this.

It is impossible to tell what happened if the only info I have is --> "a crash happened"
