### ISSUE TITLE
Is there scroll limits ?

### ISSUE THREAD

**Issue by dbyst** [patchthecode/JTAppleCalendar#1242]
Hi guys.
I draw calendar for 5 years.
Is there way to limit calendar scrolling to some date ?
For example, because of some conditions I want let user to scroll only till the end of first year.
Not more.

Thanks.

**Comment by patchthecode** [comment]
something like this date boundary?
https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by dbyst** [comment]
@patchthecode 
Works Perfectly.
Thank you!
