### ISSUE TITLE
Black Screen displaying when running code

### ISSUE THREAD

**Issue by Kardee12** [patchthecode/JTAppleCalendar#1243]
JTAppleCalendar (8.0.2)

After following your Youtube tutorial, I am recieving a black screen for where I want my calendar to be. I am not sure how to fix this, or what else to do.
![image](https://user-images.githubusercontent.com/11431755/79031101-7c86d500-7b51-11ea-8299-2f086dab9659.png)

**Comment by patchthecode** [comment]
Do you have any error logs?

**Comment by patchthecode** [comment]
closing this until user responds
