### ISSUE TITLE
Calendar days out of sync with the right day of the week

### ISSUE THREAD

**Issue by pkuzia** [patchthecode/JTAppleCalendar#1244]
**Version Number:**
JTAppleCalendar (8.0.3)
## Description
After changing TimeZone calendar days become out of sync with the right day of the week.
I read issues in this topic and the solutions always was setting TZ in Calendar Configurator.
Unfortunately, it doesn't work in my case.

My calendar:
<img width="359" alt="Zrzut ekranu 2020-04-14 o 13 26 22" src="https://user-images.githubusercontent.com/26796889/79255848-42863d80-7e87-11ea-973a-046b52d1df50.png">

Apple calendar:
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-14 at 13 33 50](https://user-images.githubusercontent.com/26796889/79256211-e2dc6200-7e87-11ea-8bfe-889a78a0b2e0.png)

## Additional Context
The instance of calendar:

```
▿ gregorian (fixed)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "fixed"
  ▿ locale : Optional<Locale>
    ▿ some :  (fixed)
      - identifier : ""
      - kind : "fixed"
  ▿ timeZone : America/New_York (autoupdatingCurrent)
    - identifier : "America/New_York"
    - kind : "autoupdatingCurrent"
    ▿ abbreviation : Optional<String>
      - some : "GMT-4"
    - secondsFromGMT : -14400
    - isDaylightSavingTime : true
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1
```
ConfigurationParameters:

```
var gregorian: Calendar {
  var calendar = Foundation.Calendar(identifier: .gregorian)
  calendar.timeZone = TimeZone.autoupdatingCurrent
  return calendar
}

let formatter = DateFormatter()
  formatter.dateFormat = "yyyy MM dd"
  formatter.timeZone = gregorian.timeZone
  formatter.locale = gregorian.locale
  let startDate = formatter.date(from: "2019 01 01")!
  let endDate = startDate.adding(.year, value: 10)
  return ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: gregorian)
```

What can help?

**Comment by patchthecode** [comment]
awesome.
