### ISSUE TITLE
Dates start on row two

### ISSUE THREAD

**Issue by leeprobert** [patchthecode/JTAppleCalendar#125]
I am seeing six rows as expected, but the dates start on row two, leaving me with a blank row and a missing date at the end. I have followed the tutorial to the letter. I've also tried to add a header but that hasn't shown at all. I am pulling from Cocoapods using the GIT method. Should I grab a particular version?
![img_1344](https://cloud.githubusercontent.com/assets/151336/18167726/0967f38a-704a-11e6-841c-260c346a18bb.PNG)

**Comment by patchthecode** [comment]
Would [this](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#6) be your problem?

**Comment by leeprobert** [comment]
I'm loading the ViewController as an embed in a container within another ViewController on the Storyboard. The vertical height is the same as the nav-bar space, but unchecking 'Adjust Scroll View Insets' didn't fix it. Trying some other things.

**Comment by leeprobert** [comment]
Also, I threw in some background colours on the views and the space is happening inside my JTAppleCalendarView and not in the parent ViewControllers View.

**Comment by patchthecode** [comment]
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by leeprobert** [comment]
This was resolved and was the issue with turning off the 'adjust scroll view insets' on the parent view controller. It has to be set on the View Controller referenced by the embed container AND also in the View controller hosting the container.
