### ISSUE TITLE
scrollToDate() sets wrong cellState.dateBelongsTo making selected date an outdate of the next month

### ISSUE THREAD

**Issue by Shliferd** [patchthecode/JTAppleCalendar#1250]
7.1.8 - version

So, I am scrolling to 1st of April 2020 using scrollToDate() method and the selection is right, but date owner of cellState.dateBelongsTo is incorrect, setting me the selected date to an outdate of the next month. Visible dates are 29-Mar <-> 4-Apr

**Comment by Shliferd** [comment]
.

**Comment by patchthecode** [comment]
I guess this issue was related to timeZone?
