### ISSUE TITLE
Settings a new ConfigurationParameter after reloadData(withAnchor:) or reloadData() doesn't reload the data with new dates

### ISSUE THREAD

**Issue by jcbriones** [patchthecode/JTAppleCalendar#1252]
**(Required) Version Number:**
8.0.3

## Description
Setting a new ConfigurationParameter on JTACMonthViewDataSource.configureCalendar(_ calendar:) does not set new dates. I tried reloadData function call after setting the new dates but it still doesn't work for some reason.

## Steps To Reproduce
1. Set-up calendar view delegate and datasource.

2. Use this in configureCalendar
```
func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        return ConfigurationParameters(startDate: startDate, endDate: endDate, generateInDates: .forAllMonths, generateOutDates: .tillEndOfRow, hasStrictBoundaries: true)
    }
```

3. Change the new startDate and EndDate to be something that is out of bounds between the old start and end date.

4. Reload the data using reloadData() or reloadData(anchor:)

5. After reloading the view doesn't change the dates as it was probably already set.

## Expected Behavior
After reloadData function call is called, it should reload the entire calendar view if it's out of bounds of the original startDate and endDate.

**Comment by jcbriones** [comment]
Looks like it's caching the configurationparameters. Is there a way to disable this? I saw something like this
startOfMonthCache
endOfMonthCache
etc..

**Comment by patchthecode** [comment]
Looking at this now.

**Comment by jcbriones** [comment]
Actually forget about this bug. I notice that I am running the change of start date and end date in a different thread that's why sometimes it works and sometimes it doesn't. I put to run with a sync call and it works everytime. This is an issue in my code not the plugin. Thanks

**Comment by patchthecode** [comment]
awesome

**Comment by kajensen** [comment]
I also experienced this issue when a reload was called multiple times in quick succession (don't recall this being an issue.. _before_?)
