### ISSUE TITLE
stopAtEachSection and no outdates for 1 row results in bug on scrolling

### ISSUE THREAD

**Issue by Shliferd** [patchthecode/JTAppleCalendar#1253]
v 7.1.8
This my config for 6 rows:

`ConfigurationParameters(startDate: startDate, endDate: endDate,
                                           numberOfRows: numberOfRows, generateInDates: .forAllMonths,
                                           generateOutDates: .off, firstDayOfWeek: .sunday)`

and this one for 1 row:

`ConfigurationParameters(startDate: startDate,
                                           endDate: endDate,
                                           numberOfRows: numberOfRows,
                                           generateInDates: .forFirstMonthOnly,
                                           generateOutDates: .off,
                                           firstDayOfWeek: .sunday,
                                           hasStrictBoundaries: false)`

The first case it's working perfect, but on the second the scroll is faulty and i scroll backwards and forward dates are presented. In cellForRowAt visibile dates are not changing, the same month dates are present. The scroll is set to stopAtEachSection. If I set the scroll mode to stopAtEachCalendarFrame the scroll it's working, but each time i scroll content insets are changing, for backwards the content inset is changed to right, the opposite for forward scroll...

**Comment by Shliferd** [comment]
Still wierd behavior for stopAtEachSection

**Comment by ZhangDihan** [comment]
I also encountered this problem, is there any way to solve it?

**Comment by Shliferd** [comment]
Hey, yes, I’ll add a solution as a comm in gitHub. But I talked with the patchcode and I think it’s resolved in version >= 8.0

**Comment by AndreiMatea** [comment]
As a workaround since someone asked me you can set **scrollingMode = .stopAtEachSection** in a setup method before the calendar view is loaded and upon layoutSubviews() method of your calendar view you change the scrolling mode as:

`    override func layoutSubviews() {
        super.layoutSubviews()
        
        calendarView.layoutIfNeeded()
        calendarView.scrollingMode = .stopAtEachCalendarFrame
    }`

Take care that you may need to **reloadData()** on your calendar view in order to scroll to the desired selected date after changing scrolling mode.
