### ISSUE TITLE
Weird behavior when trying a horizontal swipe on a vertical calendar

### ISSUE THREAD

**Issue by idavidgeo** [patchthecode/JTAppleCalendar#1254]
**(Required) Version Number:** Version 8

## Description

1. Set scroll mode to stop at each calendar frame.
2. Set scroll direction to vertical
3. Try multiple horizontal swipes
The odd behavior is it scrolls up and stops at an illegal location.
See video for better explanation. 

Screen recording video link: https://streamable.com/qs0dw0

Here are my configs:

        calendarView.scrollingMode = .stopAtEachCalendarFrame
        calendarView.scrollDirection = .vertical
        
        ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: self.calendar, generateOutDates: .tillEndOfRow)

**Comment by patchthecode** [comment]
I am seeing a corner radius effect.
There is no extra code like this in this library.

Do you have any corner radius code in your project?

**Comment by idavidgeo** [comment]
It's just how a modally presented view behaves. When it senses the view being dragged, it adapts to the rounded edges of the iPhones display.

It there a way to somehow add another gesture recognizer in addition to the calendar view vertical one?

**Comment by idavidgeo** [comment]
Nvm, I've added a pan gesture recognizer to the view of the modal, and it's eating up all the horizontal swipes. So that fixes the odd vertical scrolling behavior.

Regardless, If you think this is worth looking into, I think it has to do with the modally presented view, and a vertical scrolling calendar that stops at every frame.

**Comment by patchthecode** [comment]
I will investigate. But if someone can help looking into this i'd be grateful.

**Comment by patchthecode** [comment]
closing issue.
It seems like you have said.
Thanks.
