### ISSUE TITLE
Crash JTACCellMonthView

### ISSUE THREAD

**Issue by longhoang2984** [patchthecode/JTAppleCalendar#1255]
Hi all, I have an issue with JTACCellMonthView because it crash with line 
`let numberOfDaysInCurrentSection = month.sections.first!`

Step: Because I set up calendar view by programmatically so I create Xib file and inherit from JTACMonthCell, copy set up calendar in year view example.

Any solutions for it?

**Comment by patchthecode** [comment]
...Can i first ask why you didnt fill out the template?
There are questions there that needs to be answered in order for me to help you.

**Comment by longhoang2984** [comment]
Because it have no specific step, just create an example by programmatically but the crash had happened, it crash when the month list was create after draw.

**Comment by patchthecode** [comment]
i meant questions such as which version of the library you are using?
I hope your problem is resolved.
If it is not then feel free to re-open this.
