### ISSUE TITLE
crash on layoutIfNeeded()

### ISSUE THREAD

**Issue by Shliferd** [patchthecode/JTAppleCalendar#1256]
(Required) Version Number: 7.1.8

It occurs for iOS <= 12.4

**Description:**

If the scrolling mode is set to `.stopAtEachCalendarFrame` and call `layoutIfNeeded()` in `layoutSubviews()` the method `targetPointForItemAt(indexPath: sectionIndexPath)` within `JTAppleCalendarView` class returns a `CGPoint(x: NaN, y: 0)` crashing the app. It should return 0 instead of NaN as for iOS 13.

**Workaround:**

Set the calendar initial scrolling mode to `scrollAtEachSection` and change the scrolling mode to `stopAtEachCalendarFrame` in `layoutSubviews()` after `layoutIfNeeded()`.

**Comment by patchthecode** [comment]
Hmm.
So just to be clear, this does not happen in version 8?

**Comment by patchthecode** [comment]
CLose due to no response.
