### ISSUE TITLE
Crash on release build on a few specific devices

### ISSUE THREAD

**Issue by thuca1992** [patchthecode/JTAppleCalendar#1259]
**(Required) Version Number:**
Tried on both 8.0.3 and 7.1.7
## Description
The app is crashed when open calendar view in iphone 5 and ipad version 10.3.4 with release build while debug build worked nicely. With other devices, it worked well on both debug and release build.
## Steps To Reproduce
Open the calendar view.
## Expected Behavior
Not crashed.
## Additional Context
Main Thread got a yellow warning.

The log printed not much info:

"Thread 1: EXC_BAD_ACCESS (code=2, address=0x4cb308)
0x4cb308: subeq  r11, r12, r0, ror #6
    0x4cb30c: .long  0x0155b8c1                ; unknown opcode
    0x4cb310: addseq r0, r4, r12, ror r0
    0x4cb314: .long  0x176b26b0                ; unknown opcode
    0x4cb318: addseq r0, r4, r1
    0x4cb31c: subeq  r11, r12, r0, lsr r3
    0x4cb320: subeq  r11, r12, r8, lsr #6
    0x4cb324: subeq  r11, r12, r8, asr #6"

"error: memory read failed for 0x1400"

**Comment by patchthecode** [comment]
Although this crash happens on when you open the calendar view, this error log does not even look calendar related.

Can you show me a screen shot of what that view looks like?

**Comment by thuca1992** [comment]
Hi @patchthecode, Thank you for your fast response.
Today I have tried to download the source code and I found the line that makes the app crashed. Please see the attached image. Could you please help me check. Appreciate it. 

[https://drive.google.com/open?id=12G_UsU7SA-QLk-wb24PhWDEqNRgcVr9W](url)
