### ISSUE TITLE
The delegate scrollDidEndDecelerating may be called at wrong time

### ISSUE THREAD

**Issue by iceboxi** [patchthecode/JTAppleCalendar#1260]
**(Required) Version Number:**
v8.0.3  
## Description
I will clean view with delegate 
````
func scrollDidEndDecelerating(for calendar: JTACMonthView)
````
but I found out after scrollDidEndDecelerating, there should be called but not when sometimes
````
func calendar(_ calendar: JTACMonthView, willScrollToDateSegmentWith visibleDates: DateSegmentInfo)
func calendar(_ calendar: JTACMonthView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo)
````
## Steps To Reproduce
May happen in every times user drag calendar with short and soft finger move
## Expected Behavior
I think didScrollToDateSegmentWith delegate should be call after scrollDidEndDecelerating
## Additional Context
I look at the file JTACScrollViewDelegates.swift, and I found out scrollDidEndDecelerating are not be trigger by scrollviewdelegate scrollDidEndDecelerating, I think this method
````
public func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool)
````
with the decelerate bool is point

I will send a pull request to explain this issue

**Comment by patchthecode** [comment]
I have merged the issue
https://github.com/patchthecode/JTAppleCalendar/pull/1261
Closing this.
Thanks.
