### ISSUE TITLE
ERROR. 'JTAppleCell' is unavailable: 'JTAppleCell' has been renamed to 

### ISSUE THREAD

**Issue by Machosh** [patchthecode/JTAppleCalendar#1263]
'JTAppleCell' is unavailable: 'JTAppleCell' has been renamed to '_TtC15JTAppleCalendar11JTACDayCell'

I just simply import and made collectionView, cell Class, then this erorr occured.
Any solution?

 - Xcode version 11.4.1
 - install via cocoapod.(v8.0.3)
 - Swift 5
 - Target Platform : iOS v12.4
 - other pods : Alamofire, SwiftyJSON, RxCocoa, Moya, RxOptional

here's my code.

---

import UIKit
import JTAppleCalendar

class DateCell : JTAppleCell { _-> error occured here._
    
}

---

**Comment by patchthecode** [comment]
sounds like you just updated.
Isnt XCode telling you what to update to?

BTW here is the migraiton guide https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

**Comment by Machosh** [comment]
yea i didnt read properly.. sry
