### ISSUE TITLE
Force each date cell be Square

### ISSUE THREAD

**Issue by SajjadKharrazi** [patchthecode/JTAppleCalendar#1268]
i want to create an infinite vertical calendar scroll.
so with these lines of code, i handled width property and it works well:

```
let windowWidth = UIScreen.main.bounds.width
let cellSize = (windowWidth / 7).rounded(.down)
self.calendar.cellSize = cellSize
self.calendarWidthConstraint.constant = CGFloat(cellSize * 7)
```

also i set 4pt space between each row with this:

```
self.calendar.minimumLineSpacing = 4
self.calendar.minimumInteritemSpacing = 0
```

but now i want to force every date cell be Square. how can i do that?

in Debug View Hierarchy ( iPhone SE ), it shows frame of each cell: `(0 0; 45 37.5)` and it's not square

![image](https://user-images.githubusercontent.com/7239983/81617716-34322f80-93fb-11ea-9d23-4f8bd0157f3b.png)

**Comment by patchthecode** [comment]
i will look into this more this weekend.

So basically, you have a vertical calendar, and you want the cell to be a perfect square right?
If yes, then i'll respond to you over this weekend.

**Comment by SajjadKharrazi** [comment]
yes that's right. tnx

**Comment by SajjadKharrazi** [comment]
could you see it?

**Comment by patchthecode** [comment]
Getting to this in a bit.

**Comment by kYunevich** [comment]
@patchthecode Similar problem (

**Comment by patchthecode** [comment]
@SajjadKharrazi  sorry for the late reply. I now have time to look at this.

```swift
 var frame = attrib.frame.insetBy(dx: minimumInteritemSpacing, dy: minimumLineSpacing) 
```

Are you saying that it should be this instead?

```swift
 var frame = attrib.frame.insetBy(dx: minimumInteritemSpacing / 2, dy: minimumLineSpacing / 2) 
```

Can you explain to me why this is so?
> because you inset minimumLineSpacing to the frame and so it will reduce 2x

Note: believe it or not, even though i wrote this library, I am not good at math.

**Comment by patchthecode** [comment]
The reason why i am asking for an explanation from you is because i do see that it is off by 2x. But i do not understand the reason why.

**Comment by patchthecode** [comment]
The code to make a perfect square on a vertical calendar should be this
```swift
calendarView.cellSize = (calendarView.frame.width / 7) + 4
calendarView.scrollDirection = .vertical
calendarView.minimumLineSpacing = 4
calendarView.reloadData()
```

But because it is off by 2x, then the code should be this
```swift
calendarView.cellSize = (calendarView.frame.width / 7) + 8
calendarView.scrollDirection = .vertical
calendarView.minimumLineSpacing = 4
calendarView.reloadData()
```

But i need to understand why it is off by 2x before i implement this small fix.

**Comment by SajjadKharrazi** [comment]
now i use version `8.0.3` with these configures:
```swift
let windowWidth = UIScreen.main.bounds.width - 32 // 32 for 16 leading and trailing margin
let cellSize = (windowWidth / 7).rounded(.down)
self.calendarView.cellSize = cellSize
self.calendarWidthConstraint.constant = CGFloat(cellSize * 7)

self.calendarView.minimumLineSpacing = 4
self.calendarView.minimumInteritemSpacing = 0
```


![image](https://user-images.githubusercontent.com/7239983/83029077-7daf8b00-a047-11ea-8985-adcb0316377a.png)

as you can see in picture, it reduces 2x offset from top and bottom and so `height: 54 - 4 - 4 = 46`

----------------------------------------------

but if i use my fork version and use this commit number: `cfb1bca73d68d4f41eae524e0371a64ebc77cb86` from branch `hotfix/minimumLineSpacing-problem-for-square-cell` which was removed thsese lines of code:

```swift
if minimumInteritemSpacing > -1, minimumLineSpacing > -1 {
        var frame = attrib.frame.insetBy(dx: minimumInteritemSpacing, dy: minimumLineSpacing)
        if frame == .null { frame = attrib.frame.insetBy(dx: 0, dy: 0) }
        attrib.frame = frame
}
```

from `Sources/JTAppleCalendar/JTACMonthLayout.swift` file, so result will be like this:


![image](https://user-images.githubusercontent.com/7239983/83029946-7fc61980-a048-11ea-8b67-976db4d2de53.png)
 
so as you can see, it is Square and has width and hight 54. but it has no lineSpacing between dates in calendar ui.

i think instead of set inset to each cell, we must implement standard line spacing with CollectionView behavior

**Comment by patchthecode** [comment]
Understood.
I will need to update the library.

But in the mean while, can you let me know if the following code works for you?
Use the 8.0.3 _unmodified_ version.

```swift
let windowWidth = UIScreen.main.bounds.width - 32 
let cellSize = (windowWidth / 7).rounded(.down)
self.calendarView.cellSize = cellSize + 8 // I added an extra 4 with off by 2x
self.calendarWidthConstraint.constant = CGFloat(cellSize * 7)

self.calendarView.minimumLineSpacing = 4
self.calendarView.minimumInteritemSpacing = 0
```

**Comment by SajjadKharrazi** [comment]
yes, it works

![image](https://user-images.githubusercontent.com/7239983/83056850-54085b00-a06b-11ea-8c6c-075332d94c52.png)

**Comment by patchthecode** [comment]
ok, now that i know what works, i know how to fix.

**Comment by patchthecode** [comment]
Ok so the mistake was mine.
I used inset.
According to the documentation, you were correct. Inset is by 2x
<img width="991" alt="Screen Shot 2020-05-27 at 5 19 07 PM" src="https://user-images.githubusercontent.com/2439146/83073349-4ab4c980-a03e-11ea-8890-b3227aa64411.png">


Therefore, i just need to do a divide by 2 fix and problem will be solved.

**Comment by patchthecode** [comment]
closing.
Fixed and pushed to master
