### ISSUE TITLE
Is it possible to preselect dates in one color and have user selected dates in another?

### ISSUE THREAD

**Issue by michaeldebo** [patchthecode/JTAppleCalendar#1271]
Does your calendar support like 6 dates being preselected? If so, I presume it's possible to have the preselected dates in one color and the user selected date in another, no?

Much appreciated,
Mike

**Comment by patchthecode** [comment]
yes you can.

```swift
calendarView.selectDates([array of dates])
```

and.. you can create the date cells to like dinosaur if you wanted.

**Comment by michaeldebo** [comment]
Hi thanks for the response. I have been unable to figure out how to color
preselected dates one color and user selected dates another. It seems that
by selecting dates it's calling the did select item function, which is the
same one used for user selection. How do I make separate colors for each
given they both use the same function?

**Comment by michaeldebo** [comment]
Also when I preselected today and tomorrow, only tomorrow shows up. When I
remove tomorrow, then today shows. How do I fix this?

**Comment by patchthecode** [comment]
Have you checked out any of the examples on patchthecode.com ?

**Comment by michaeldebo** [comment]
I have. I'm now having trouble getting the collection view to respond to
being selected appropriately. I tap on say 17 and 4 gets selected. The
preselected dates disappear and show up based on me tapping other cells.
It's currently not working at all.

**Comment by michaeldebo** [comment]
Could these problems with the ui not reflected the selections that I make
be related to me trying to implement  the callendar as part of a tableview
cell?

**Comment by patchthecode** [comment]
Do you have an example app that demonstrate the problems you are experiencing?
I'd prefer you submit a minimum (non bloated app) that demonstrates the problem.

**Comment by michaeldebo** [comment]
I appreciate your help. This demonstrates the problem. Let me know if there
are any questions I can answer.

**Comment by patchthecode** [comment]
You are replying by email to a github message.
Attachments does not work this way.
You'll have to attach it to the issue directly on github.

**Comment by michaeldebo** [comment]
[ReplicaOfProblem.zip](https://github.com/patchthecode/JTAppleCalendar/files/4646555/ReplicaOfProblem.zip)
