### ISSUE TITLE
cell sellected/should selected not called

### ISSUE THREAD

**Issue by alexvaiman** [patchthecode/JTAppleCalendar#1275]
using the latest version 8.3
how to reproduce? 
make a very basic design - background view of some color for selected date, clear on not selected date.  give a 1 year range for the calendar, 19.5.20 -  19.5.21
preselect programmatically few selected dates. (lets say 3 dates)

run the app, and just start selecting dates , at some point you will notice that some of the cells(dates), not responding to selections, the relevant delegates are no being called none, after some investigation i actually noticed only 2 delegate being called after all .

    func calendar(_ calendar: JTACMonthView, didHighlightDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {}
    func calendar(_ calendar: JTACMonthView, didUnhighlightDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {}

can you please help? do you need my very basic example? i can send it via email.
 *edit link to sample project
https://easyupload.io/y74eg2

**Comment by patchthecode** [comment]
I ran your app.
Have you tried debugging it?
And if yes, can you let me know what you tried?

**Comment by alexvaiman** [comment]
not really(not the lib it self), only my code, witch is very basic - put breakpoints on all  delegates(nothing was called), then just started to look a little bit at lib source found the this two delegate, and have tested to see if at least they are being called (they do).
func calendar(_ calendar: JTACMonthView, didHighlightDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {}
func calendar(_ calendar: JTACMonthView, didUnhighlightDate date: Date, cell: JTACDayCell?, cellState: CellState, indexPath: IndexPath) {}

**Comment by patchthecode** [comment]
Its not a problem with the lib.
Its your code.

Have a look at your cell code in your prepareforreuse.

**Comment by alexvaiman** [comment]
thanks - I will do it, and if solved, i will put an update - to close the issue.

**Comment by patchthecode** [comment]
.....i'll just tell you.

Look at the documentation for `prepareForReuse`

```
Discussion

The default implementation of this method does nothing. However, when overriding this method, it is recommended that you call super anyway. Subclasses such as UICollectionViewCell override this method and use it to perform relevant actions. So if your subclass descends from UICollectionViewCell or some other intermediate class, calling super ensures that your class gets the parent’s behavior.
When a view is dequeued for use, this method is called before the corresponding dequeue method returns the view to your code. Subclasses can override this method and use it to reset properties to their default values and generally make the view ready to use again. You should not use this method to assign any new data to the view. That is the responsibility of your data source object.
```

You didnt call 
```
super.prepareForReuse()
```

**Comment by patchthecode** [comment]
Let me know it if it now works.

**Comment by alexvaiman** [comment]
thank you very much, for the quick help.

**Comment by alexvaiman** [comment]
thanks! it was indeed the problem!
