### ISSUE TITLE
The calendar doesn't resize itself when you put it inside of a UISplitViewController as master controller.

### ISSUE THREAD

**Issue by deniszhukov** [patchthecode/JTAppleCalendar#128]
The calendar doesn't resize itself when you put it inside of a UISplitViewController as master controller.
It shows additional columns (more than 7 days) if it was bigger in storyboard designer or shows less columns if it was smaller.

<img width="400" alt="1" src="https://cloud.githubusercontent.com/assets/12587571/18280699/d09adf68-740e-11e6-97b3-f010651db3bc.png">

In landscape orientation you have the same problem. 

<img width="400" alt="2" src="https://cloud.githubusercontent.com/assets/12587571/18280754/1413bc38-740f-11e6-92a5-d8772841ed21.png">

Reloading doesn't help.

That's what I used for reloading

self.calendarView.reloadData()
self.calendarView.scrollToDate(NSDate(), triggerScrollToDateDelegate: false, animateScroll: false) {
    let currentDate = self.calendarView.currentCalendarDateSegment()
    self.setupViewsOfCalendar(currentDate.dateRange.start, endDate: currentDate.dateRange.end)
}

I'm using the latest version of calendar 5.0.1.

I'm attaching your example that I've put inside of UISplitViewController, without any changes, just to show the problem.

[JTAppleCalendar-master (UISplitView problem).zip](https://github.com/patchthecode/JTAppleCalendar/files/457113/JTAppleCalendar-master.UISplitView.problem.zip)

Thanks in advance.

**Comment by patchthecode** [comment]
Will look into this in a bit

**Comment by patchthecode** [comment]
Ok. the issue is resolved.
I can provide you a patch, before the official release.

**Comment by patchthecode** [comment]
This bug is related to https://github.com/patchthecode/JTAppleCalendar/issues/148

**Comment by patchthecode** [comment]
Issue is fixed.

**Comment by deniszhukov** [comment]
Thanks, I think I'll wait for the next official release.

**Comment by patchthecode** [comment]
@deniszhukov one thing to note. The next official release will be in swift3.
So if you need something in swift2, then let me know.
cool.
