### ISSUE TITLE
There is Error  in JTAC Months  view 

### ISSUE THREAD

**Issue by amralkhayat** [patchthecode/JTAppleCalendar#1282]
hello,
After I have updated  new version of the pod show this error appear , when I run calendar.
![Screen Shot 2020-06-27 at 3 36 45 AM](https://user-images.githubusercontent.com/33759960/85911806-c2396c80-b827-11ea-8976-7304bdb236b4.png)

**Comment by patchthecode** [comment]
Is there anything in the error log that tell you anything about the crash?

**Comment by amralkhayat** [comment]
After i have updated the pod take  me directly this error , without any description, even if i have added break point to tell me where is error exactly take me to this page also

**Comment by patchthecode** [comment]
This sounds like dirty builds..
Have you tried doing a CMD + SHIFT +K to clean the project?
Also delete the Build folder and the Index folder.
And try again?

**Comment by amralkhayat** [comment]
I have did that, and  show me this message 
![Screen Shot 2020-06-27 at 8 37 08 PM](https://user-images.githubusercontent.com/33759960/85929571-3589bf80-b8b6-11ea-9e38-58e37f86a73e.png)

**Comment by patchthecode** [comment]
Ok this is more helpful.
What version did you update from?

If you updated from version 7 to version 8, then have you done the changes?
--> https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

**Comment by p-nicolaou** [comment]
@amralkhayat can you share your Podfile setup?

**Comment by patchthecode** [comment]
I'm setting the flag to `waiting for user response`.

In the mean time i am closing this as I assume it has been resolved.
