### ISSUE TITLE
Problem when changing color title the day of month and out of month

### ISSUE THREAD

**Issue by ganhxecanh** [patchthecode/JTAppleCalendar#1283]
I having some problem when set the color title the day of month and out of month with a custom calendar cell. I 've try to config it with if else in cellForItemAt but does not work. The first appear it 's not right but then if scroll it 's ok. How can i fix it?

**Comment by patchthecode** [comment]
we have examples of the code on patchthecode.com
Start by taking a look there.

Also providing some source code would help me identify a problem.
