### ISSUE TITLE
Is it possible to select dates from recurrence rule?

### ISSUE THREAD

**Issue by marcossimas** [patchthecode/JTAppleCalendar#1285]
**(Required) Version Number:**
8.0.2

## Description
I’d like to select dates from recurrence rule.
I have options to set recurrence (ie. every week, every tuesday...)
Recurrence rules are formatted as defined in the iCalendar RFC.

Example rule: RRULE:FREQ=DAILY;COUNT=30;INTERVAL=1;WKST=MO

Calendar should read the rule and select date accordingly.

Thanks.

**Comment by patchthecode** [comment]
The function we have to select dates is 
```swift
calendarView.selectDates(theArrayOfDatesToSelect)
```

Therefore if you have some rule, then create a function that uses that rule to generate dates according to your rule.
Add those dates to an array.
then select it using the function above.
