### ISSUE TITLE
content height is different from calendar view height.

### ISSUE THREAD

**Issue by dan007b3** [patchthecode/JTAppleCalendar#1286]
**8.0.3**

## Description
So when I create my calendar with constraints to the iPhone safe area the content is taller than the frame of the calendar. which means that you have to scroll vertically to see all the content. 

## Steps To Reproduce
Create regular calendar with constraints to safe areas

## Expected Behavior
Content height should be equal to calendar frame height
[Screen Recording 2020-07-09 at 18.16.23.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/4898064/Screen.Recording.2020-07-09.at.18.16.23.mov.zip)

**Comment by patchthecode** [comment]
Sorry for the late reply.
But I am not able to reproduce this.

A faster way would be if you provide me a bare minimum sample app which reproduces this issue.
And in addition, plesae let me know

1. what simulator you used?
2. What Xcode verison?
