### ISSUE TITLE
Last week of the month and first week of the next are repeating itself in week mode

### ISSUE THREAD

**Issue by VladimirVasic994** [patchthecode/JTAppleCalendar#1288]
8.0.2
**(Required) Version Number:**

## Description
My calendar control in week mode when scrolled shows the same week twice.
My settings for calendar control is: 
numberOfRows: 1,
generateInDates: .forAllMonths,
generateOutDates: .tillEndOfRow,
firstDayOfWeek: .monday,
hasStrictBoundaries: true

## Steps To Reproduce
Scroll to 31 July and scroll to the left while in week mode
## Expected Behavior
You should see the first week of August that is the same as last week of July

**Comment by patchthecode** [comment]
screenshot?

**Comment by VladimirVasic994** [comment]
<img width="286" alt="Screen Shot 2020-07-23 at 9 28 57 AM" src="https://user-images.githubusercontent.com/45670840/88476898-34db5c00-cf3c-11ea-9139-a2973da4d377.png">
<img width="284" alt="Screen Shot 2020-07-23 at 9 29 11 AM" src="https://user-images.githubusercontent.com/45670840/88476893-30af3e80-cf3c-11ea-8cbb-9f0346cd85b5.png">

**Comment by patchthecode** [comment]
This is the correct way to setup a single row calendar -> https://github.com/patchthecode/JTAppleCalendar/issues/581
