### ISSUE TITLE
Week View (one row only)

### ISSUE THREAD

**Issue by mazurio** [patchthecode/JTAppleCalendar#129]
Hi @patchthecode 

I am trying to use JTAppleCalendar with a weekly view (one row only) as this is what I had in my app. Having a month view makes sense for iPhone 6 and 6+ but it's too big for iPhone 4 and iPhone 5.

My problem is that you can have a week which starts with "29, 30, 31, 1, 2, 3, 4" but if you scroll left you will get "5, 6, 7, 8, 9, 10, 11".

Any idea how can I get rid of those extra cells?

I had:

```
    func configureVisibility(cellState: CellState) {
        if cellState.dateBelongsTo == .ThisMonth {
            self.hidden = false
        } else {
            self.hidden = true
        }
    }
```

In my CellCode but this makes the row to be empty so users have to scroll through empty space which is just a bad UX.

Any pointers?

This is an awesome library btw.

Thanks.

**Comment by patchthecode** [comment]
You would be talking about this -> https://github.com/patchthecode/JTAppleCalendar/issues/56

This is currently being worked on and is the final upgrade for this calendar.
It will allow a user to enable/disable the `in-date` and `out-date` cells.

**Comment by patchthecode** [comment]
Btw, just to clarify, 
When you say "get rid" of the cells, do you mean to make them hidden? or do you mean to make them not generated?

If they are hidden, there will be some space there which indicates that they are there, but are just invisible,
If however, they are not generated, then there will be no space there. Following cells will be generated right next to each other with no space.

**Comment by mazurio** [comment]
HI @patchthecode 

I meant - not generated.

**Comment by mazurio** [comment]
I have read https://github.com/patchthecode/JTAppleCalendar/issues/56 but it's still quite confusing how I would like to achieve this.

Also any dates for the release? :)

**Comment by patchthecode** [comment]
yesterday it was 45% completed. Today Its 85% completed.
I can't predict a release though. I will have to test it.

In terms of how you will be able to achieve this, it will be simple.

I will give you an option to turn inDates either`on` or `off` 
and
I will give you an option to turn outDates either`on` or `tillGrid` or `tillRow` 

<img width="373" alt="screen shot 2016-09-07 at 3 17 33 pm" src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png">

An outDate of `tillRow` will stop the outdate generation at date `5`
An outDate of `tillGrid` will stop the outdate generation at date `12`

The different between the 2 outdates are that `tillGrid` will always generate a 6x7 grid of dates.
`tillRow` however will only generate outdates to fill the row. This means that if you use `tillRow`, some of your months will have 4 row, or 5 rows, or 6 rows, depending on how many days are in the month i.e your number of rows per month can change. With `tillGrid` you will always have a fixed 6 rows per month (like it is currently done now in version 5.0.1)

the function I will modify is this one
```swift
func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar, generateInDates: Bool, generateOutDates: OutDateCellGeneration)
```
So all you have to do is simply tell that function if you want indates/outdates generated or not. Thats it.

**Comment by mazurio** [comment]
That's brilliant - is the branch DynamicGeneration? I don't mind taking a look too. Thanks for all hard work!

**Comment by patchthecode** [comment]
Edited my explanation above to include `off` for outdates

**Comment by mazurio** [comment]
Hi @patchthecode , any update on pushing the changes? Thanks, Damian

**Comment by patchthecode** [comment]
yes.
pushing in 2 mins :)

**Comment by mazurio** [comment]
Awesome stuff! @patchthecode

**Comment by patchthecode** [comment]
Keep in mind. Other functionality might be broken ok. Its just the configure function that works, and displays the dates for now.

**Comment by mazurio** [comment]
No worries, I will give it a try and thanks for letting me know - looking forward to stable version too.

**Comment by patchthecode** [comment]
Yea. fixing the other functionality is easy and should be done quickly.
The hard part is complete.

**Comment by mazurio** [comment]
Hi @patchthecode 

It looks good apart this bit:

```
    func configureCalendar(calendar: JTAppleCalendarView) -> (
            startDate: NSDate,
            endDate: NSDate,
            numberOfRows: Int,
            calendar: NSCalendar,
            generateInDates: Bool,
            generateOutDates: OutDateCellGeneration) {

        let firstDate = formatter.dateFromString("2015 01 01")
        let secondDate = NSDate()
        let aCalendar = NSCalendar.currentCalendar()

        return (startDate: firstDate!,
                endDate: secondDate,
                numberOfRows: numberOfRows,
                calendar: aCalendar,
                generateInDates: false,
                generateOutDates: OutDateCellGeneration.tillEndOfRow)
    }
```

If OutDateCellGeneration is set to off then when you scroll to next month - some dates are missing on Monday, Tuesday, Wednesday? 👯 

Looking forward to release as my app is quite dependant on this library. Thanks for all hard work!

**Comment by mazurio** [comment]
Also (attaching screenshots), when OutDateCellGeneration is set to tillEndOfRow:

<img width="423" alt="screen shot 2016-09-11 at 19 18 00" src="https://cloud.githubusercontent.com/assets/6534301/18419504/833f92d2-7854-11e6-9c84-b32277165f0c.png">

We scroll right and see:

<img width="423" alt="screen shot 2016-09-11 at 19 18 02" src="https://cloud.githubusercontent.com/assets/6534301/18419505/8a7f5bae-7854-11e6-9f2d-116c101c7d8a.png">

**Comment by patchthecode** [comment]
Yes, I'm working on that last part. Vertical works well, but I found this bug yesterday. Working on it.

**Comment by mazurio** [comment]
HI @patchthecode - Any update? Thanks for all your hard work again :)

**Comment by patchthecode** [comment]
Hmm. Ok hey, maybe it might be best if you try another calendar in the mean time if this will impact your work.

I can only work on this project after my own work at the end of the day :)
It is sort of my blow-off-steam-from-work project.

I'm still coding that last part.

Currently vertical calendar works in all modes with the new code.
Horizontal calendar works in all modes except the one you want -> which is no in-Dates and no out-dates.

The reason this one is a little more complicated is it breaks the concept of sections and months. This is because since there are no buffer days (in/out days) it will not be a predefined grid. Therefore calculating where the cells will be is a little difficult. 

I also have to make it work for all 1, 2, 3, and 6 row modes. Every time I think i cracked it, I see a bug in another mode. Will try fixing it for about 2-3 more days before asking for help.

**Comment by patchthecode** [comment]
Ok, i think I might have made a break through. 
The code is still messy, but I think it works. Will push to master branch in about 3 hrs

**Comment by patchthecode** [comment]
@mazurio hey, we're thinking of making that branch converted to swift 3. My work is moving over to that swift version.

**Comment by mazurio** [comment]
Hi @patchthecode 

Thanks for updates - been busy for last few days so couldn't reply.

I'm fine with Swift 3.

How are the updates going?

**Comment by patchthecode** [comment]
Check it out.
I think its working. The code has already been committed. Currently, i'm running more tests for bugs. I haven't found any yet as of yesterday.

**Comment by mazurio** [comment]
Is it the one for Swift3 or DynamicGeneration?

**Comment by patchthecode** [comment]
DynamicGeneration
