### ISSUE TITLE
Load more in Calendar

### ISSUE THREAD

**Issue by Mahesh-iOS** [patchthecode/JTAppleCalendar#1292]
## I want to implement _load more_ functionality in the calendar per year.  Basically I want to show dates from the _distant past_ to the _distant future._ Once I start scrolling and reached to end of the year, I have to show **load more** for loading the upcoming year.

**Comment by Mahesh-iOS** [comment]
@patchthecode Please guide me, if you have any idea on above feature

**Comment by patchthecode** [comment]
hmm
first, let me know
is it a problem if you just load all the years at once?

**Comment by Mahesh-iOS** [comment]
I don't have any problem at all. But the moment, when I used start date and end dates as distant past and distant future, Initially Calendar is loading after some time (5sec to 8sec). In addition to that, at a time, I want to show one-year dates in Calender,

**Comment by Mahesh-iOS** [comment]
HI, I am done with Load more in the Calendar. Thank you

**Comment by kailezhao** [comment]
> HI, I am done with Load more in the Calendar. Thank you

May I ask how you achieved it
