### ISSUE TITLE
Can't select next month's dates

### ISSUE THREAD

**Issue by mkeshnoda** [patchthecode/JTAppleCalendar#1293]
**Version 8.0.3**

## Can't select next month's dates programmatically

`calendar.selectDates(from: date, to: dates.last!, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)`

This is what i do. Let's say user tapped on 14th and it selects 15th 16th 17th etc. **But when it comes to selecting the next month, it just doesn't work**. I think the reason for that is for each month is a cell in my collection view... When this edge-case happens, i think i shouldn't be doing hard-coded stuff to select dates from next month. Is there any practical way to fix this? 

<img width="371" alt="Calendar_bug" src="https://user-images.githubusercontent.com/25078625/93229732-94f1c000-f77f-11ea-80c4-2652f23ed7c7.png">

## It supposed to look like this
<img width="376" alt="Screen Shot 2020-09-15 at 18 18 45" src="https://user-images.githubusercontent.com/25078625/93230045-ed28c200-f77f-11ea-8089-b5e5e8fb61b4.png">

**Comment by patchthecode** [comment]
So basically, you are saying that this function does not work?
```swift
calendar.selectDates(from: date, to: dates.last!, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
```

**Comment by patchthecode** [comment]
> I think the reason for that is for each month is a cell in my collection view...

Ok, help me understand.
Why do you have each month to be one cell in your collection view?

**Comment by mkeshnoda** [comment]
> > I think the reason for that is for each month is a cell in my collection view...
> 
> Ok, help me understand.
> Why do you have each month to be one cell in your collection view?
> There should just be one `JTACMonthView`. This JTACMonthView is a collectionView.
> This view will display all the months as needed.

Okay i knew the problem was having cell for each month. Like you said JTACMonthView was the solution. Thank you!!!
