### ISSUE TITLE
iOS 14 - Days are shifted by one day

### ISSUE THREAD

**Issue by mavris** [patchthecode/JTAppleCalendar#1294]
**(Required) Version Number: 8.0.3**

## Description
Days in iOS 14 are shifted by one day. I am the only one facing this issue?
## Steps To Reproduce
![Screenshot 2020-09-29 at 5 21 23 PM](https://user-images.githubusercontent.com/3520168/94571048-3432af00-0278-11eb-8398-6cb5344d92ed.png)

## Expected Behavior
Today is (29th of September) is Tuesday but the iOS 14 shows it as Wednesday.
## Additional Context
Everything is OK for iOS 13

**Comment by patchthecode** [comment]
What do you have set as the first day of the week?  is it monday?

**Comment by mavris** [comment]
It was the default value. After I set it to `.monday` it was ok
