### ISSUE TITLE
Assertion failure in -[UICollectionViewData validateLayoutInRect:]

### ISSUE THREAD

**Issue by ahmedtalaatshaker** [patchthecode/JTAppleCalendar#1295]
**(Required) Version Number:**
  pod 'JTAppleCalendar', '~> 8.0.2'

## Description
there is a crash on IOS Version less than 13 while showing a view contains  "JTAppleCalendar" view

Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UICollectionViewData.m:447

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x2817cac00> {length = 2, path = 0 - 0}'

**Comment by ahmedtalaatshaker** [comment]
> **(Required) Version Number:**
> pod 'JTAppleCalendar', '~> 8.0.2'
> 
> ## Description
> there is a crash on IOS Version less than 13 while showing a view contains "JTAppleCalendar" view
> 
> Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UICollectionViewData.m:447
> 
> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x2817cac00> {length = 2, path = 0 - 0}'

**Comment by patchthecode** [comment]
Do you have a sample app with the bare minimum code that reproduces this?
