### ISSUE TITLE
Warning: Conversion to Swift 5 is available

### ISSUE THREAD

**Issue by dbyst** [patchthecode/JTAppleCalendar#1296]
Version Number: 8.0.3

Framework is awesome ! And works as expected ! Thank you !

Not sure whats wrong, but in my Xcode 12.2 I have warning Conversion to Swift 5 is available.
And it's suggest to  convert JSAppleCalendar.

Any ideas what's wrong ?
Thanks

<img width="312" alt="Screenshot 2020-10-05 at 16 38 28" src="https://user-images.githubusercontent.com/5080130/95086612-5d948480-0729-11eb-97bc-71a919a3f8a0.png">
<img width="720" alt="Screenshot 2020-10-05 at 16 38 24" src="https://user-images.githubusercontent.com/5080130/95086616-5f5e4800-0729-11eb-94c0-83cf88995c6a.png">

**Comment by ryanholden8** [comment]
Seems to be same issue as here: https://developer.apple.com/forums/thread/697832

Looking for a solution..

**Comment by patchthecode** [comment]
this should be resolved by now.
