### ISSUE TITLE
How to prevent selecting days from previous and future month?

### ISSUE THREAD

**Issue by antonijap** [patchthecode/JTAppleCalendar#13]
http://d.pr/i/116ff/1wbV1vYo
This is a calendar that is in April.

I want to disable user from selecting a date/s in May (or March) which is in light grey colour. How do I do that?

**Comment by patchthecode** [comment]
It's pretty much the same as any UIView.
You can disable a cell by setting `userInteractionEnabled` of the CalendarCell to true or false.

`userInteractionEnabled = false` 

Let me know if this works for you

**Comment by antonijap** [comment]
This works. Thanks!
