### ISSUE TITLE
Setting Starting Date?

### ISSUE THREAD

**Issue by ro6inhoddie** [patchthecode/JTAppleCalendar#130]
If I want to set up the calendar to start up at a certain date (which is different than the startDate/EndDate boundary), how can i do that? without having to scroll to date, animately. 

thanks

**Comment by patchthecode** [comment]
just scroll to the date un-animatedly

have you look at the full list of parameters of the `scrollToDate` function?
```swift
public func scrollToDate(date: NSDate, triggerScrollToDateDelegate: Bool = true, animateScroll: Bool = true, preferredScrollPosition: UICollectionViewScrollPosition? = nil, completionHandler:(()->Void)? = nil)
```
