### ISSUE TITLE
Can calendar support presenting unto 5K rows of appointment in one day? Or sub-categorise them into sections? 

### ISSUE THREAD

**Issue by abdulla-khalil** [patchthecode/JTAppleCalendar#1300]
I would like to use this calendar to present unto 5K - 7K rows as appointments of each day, when single day is selected. 

Is there any problems that this calendar would face when dealing with big data? 

Best regards.

**Comment by patchthecode** [comment]
Do you have a screen shot of what this might look like?

**Comment by patchthecode** [comment]
Closing this issue until user responds.
Will re-open till then.

**Comment by abdulla-khalil** [comment]
I did not understand what you mean by "screen shot of what this might look like". If you are referring to the data will be presented; it would be general info like name + number and when clicked, more details would show in another view. 

hope this answers your question,
best regards.

**Comment by patchthecode** [comment]
I asked for a screen shot, because I thought you wanted to display 5k items at once on the screen.
But i now understand what you meant.

There should be no problems.
This calendar have been tested with up to 30k data sets and it was smooth like butter.

**Comment by abdulla-khalil** [comment]
Thanks for your respond and glad to hear that it can perform well with many items.
