### ISSUE TITLE
Feature to filter to a specified set of dates

### ISSUE THREAD

**Issue by robgtsoftware** [patchthecode/JTAppleCalendar#1308]
8.0.3

## Description
Request for info. Is there a way to filter down the dates displayed? For example, if I search for an event, I am interested in displaying only those dates that contain the event of interest so the Month collection view would collapse from the full set of dates to something like:

Jan 2018 (section header)
3     5      14 

Feb 2018

March 2018
1   4   15

## Steps To Reproduce
N/A
## Expected Behavior
N/A
## Additional Context
N/A

**Comment by patchthecode** [comment]
unfortunaty, the calendar wont be able to filter dates like that.
The best it can do is 
1) Makes unwanted dates become invisible
2) Makes unwanted dates become grayed out.

I think i can make it work like how you mentioned, but the creative weird code I will have to do is way outside the boundaries that this lib was designed for haha

**Comment by robgtsoftware** [comment]
Thanks..yeah, I figured this was outside of the scope, but wanted to check. Thanks
