### ISSUE TITLE
WRONG DATE SHOWING in Coratia

### ISSUE THREAD

**Issue by basabendra** [patchthecode/JTAppleCalendar#1309]
**(Required) Version Number: 7.1.8**

## Steps To Reproduce
In Coratia, 1st of Feb is Monday, whereas in JT calender it is showing as Sunday.
Similarly, today is showing monday, but is tuesday.
In India & US, showing correct dates and days.

## Additional Context
I have updated the pod today by 
platform :ios, '10.0'
use_frameworks!

target '<Your Target Name>' do
pod 'JTAppleCalendar', '~>; 7.1'

**Comment by patchthecode** [comment]
https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by basabendra** [comment]
Thanks for your prompt reply. I am using the configuration below. Above link **#252** didn't helped me solve my issue.

`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let startDate = Date(timeIntervalSince1970: TimeInterval(Y))
        
        return ConfigurationParameters(
            startDate: startDate,
            endDate: Date(),
            calendar: .current)
    }`

**Comment by patchthecode** [comment]
Hi, did you look at the link above?
It mentions using a DateFormatter
Are you saying that using a dateformatter doesnt resolve your issue?

**Comment by basabendra** [comment]
Apologies. 
I had hard coded the **weeks** in the header (Su, Mo, Tu, We, Th, Fr, Sa) but forgot to use **firstDayOfWeek: .sunday** in **configureCalendar**.
