### ISSUE TITLE
Editing particular dates

### ISSUE THREAD

**Issue by EAZYE9000** [patchthecode/JTAppleCalendar#131]
Do you have any idea if this is possible? I have a Realm Database with NSDates stored. Is it possible to highlight/change colour of the stored dates on the calendar?
No need to worry about the Realm side, just is there a function or something that pretty much does "For these particular dates, do something, on the calendar" (in this case cell.text to green)
Cheers!

**Comment by patchthecode** [comment]
You can do anything you want with your dates. Literally anything. The design is up to you. Have you seen waht people have made with this library yet --> [here](https://github.com/patchthecode/JTAppleCalendar/issues/2)

**Comment by EAZYE9000** [comment]
Wow, those look amazing. Didn't realize how good you can get it looking. Im still stuck though, how would I go about doing: For NSDate (say the 5th September) change to green on the calendar. So when I open the calender, September 5th is green? OR whatever date it is set as? Also how do I get the cells date value? Cheers!

**Comment by EAZYE9000** [comment]
For example on some of the examples show there looks to be an event on some of the dates. How have they added a yellow circule to indicate theres something on that date on the actual calendar? Cheers!

**Comment by patchthecode** [comment]
Have you tried downloading the example attached to this github project? It gives you an example to start with.
