### ISSUE TITLE
Installation with Swift Package Manager

### ISSUE THREAD

**Issue by kohlab** [patchthecode/JTAppleCalendar#1311]
**(Required) Version Number:** 
8.02

## Description
This is a feature request, not a bug. It'd be great if JTAppleCalendar could be installed with Swift Package Manager. Much easier / cleaner to install this way within Xcode, manages dependencies well. We're getting close to having all our third party libraries installable this way; this is an exception.

**Comment by robgtsoftware** [comment]
Did you get an error when you tried? I have been able to install as a package using Xcode without issue.

**Comment by kohlab** [comment]
Honestly, I hadn't tried since it wasn't document as an installation and I'd just run into issues with other packages. I just assumed it didn't work. 

I just tried now and get this fatal error at runtime:

2021-02-25 05:50:24.478808-0800 MyApp[78061:2589634] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file CountryPickerView/NibView.swift, line 36

This is the line:

2021-02-25 05:50:24.478808-0800 RideHare[78061:2589634] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file CountryPickerView/NibView.swift, line 36

**Comment by kohlab** [comment]
Ah, excellent! I hadn't tried because it wasn't documented as an installation method, and I'd just run into issues with other packages. I just assumed it didn't work. 

Works fine. Thank you.

**Comment by robgtsoftware** [comment]
Cool..FWIW, I have found a lot of projects that don't specifically mention they have support for SPM. The trick is to look for the Package.swift file in the top of the repo. If that is there, you should be good to go.

**Comment by patchthecode** [comment]
Yea sorry about that.
SPM was implemented for some time now.
I really do have to update the documentation.
