### ISSUE TITLE
ReloadData(withanchor: date) doesn't work

### ISSUE THREAD

**Issue by dbyst** [patchthecode/JTAppleCalendar#1315]
**(Required) Version Number:**

8.0.3

## Description
Same issue as here https://github.com/patchthecode/JTAppleCalendar/issues/789
Seems that  anchor date is ignored and calendar scrolls to top after reload.

**Comment by patchthecode** [comment]
Apologies for the late response. 2020 till 2023 has been some interesting years.....
but this has been resolved sometime ago.
Latest version is 8.0.5
