### ISSUE TITLE
Intermittent issue with calendar layout on app launch.

### ISSUE THREAD

**Issue by irisha8787** [patchthecode/JTAppleCalendar#1317]
**Version Number:**
8.0.3

## Description 
Intermittent issue with calendar layout.
Sometimes when I open the page with calendar, it looks like this:

![File](https://user-images.githubusercontent.com/7072587/111854021-714c3580-88da-11eb-9a6f-62752e731b39.jpg)

Switching the screen and going back fixes the issue. 

## Steps To Reproduce
Intermittent. 
I noticed a few times when I open the app, the alignment is all wrong. 
Going back and forward fixes the issue. 

## Expected Behavior
start date is today,
end date is today + 4 months
number of rows: 6

**Comment by patchthecode** [comment]
With errors like this, the best way to get help is to create a barebones minimal app that recreates this issue.
There is no way for me to tell what your app is doing which makes it get in this state.

**Comment by patchthecode** [comment]
closed until response.
