### ISSUE TITLE
Disable Multiple Cells according to Date Array

### ISSUE THREAD

**Issue by SohaibSiddique** [patchthecode/JTAppleCalendar#1319]
Hello All,

I have array with date strings in it I want to disable cells which equal to date string in array.

like date hides in the screenshoot.

is this possible with this library,

![Screenshot 2021-04-25 at 9 21 30 PM](https://user-images.githubusercontent.com/8692719/116001074-368d9980-a60c-11eb-899e-41b41031dc54.png)

**Comment by patchthecode** [comment]
yes, just implement the shouldSelect delegate function.  
And when the cell is tapped check the array to see if it exists in there.
If it exists, then return false else true.

**Comment by SohaibSiddique** [comment]
> yes, just implement the shouldSelect delegate function.
> And when the cell is tapped check the array to see if it exists in there.
> If it exists, then return false else true.

I was asking for dimming the cell not for selecting, btw I achieve this as bellow code 

```
dateFormetter.dateFormat = "yyyy MM dd"
        dateFormetter.timeZone = calender.timeZone
        dateFormetter.locale = calender.locale
        
        let dateString = dateFormetter.string(from: cellState.date	)
        
        for date in availableDates {
            if date == dateString {
                cell.isUserInteractionEnabled = false
                cell.freezeView.isHidden = false
            }
        }
```

I put above code in cellForItemAt

----------------------------------------------

but there is another thing which I want to achieve, I want to change cell color of previous dates, for example today is 25 April and all previous dates cell color should change.

**Comment by vijay12345678910** [comment]
How can I show only two month calendar where user can select dates between them only and the rest of dates looks like unselected or disable

**Comment by patchthecode** [comment]
@SohaibSiddique this is done in the function where you setup your cell.
if the date is 25, set the color, else set another color.
I am not understanding the difficulty in this. I am wondering if i do not fully understand your question.

**Comment by SohaibSiddique** [comment]
> @SohaibSiddique this is done in the function where you setup your cell.
> 
> if the date is 25, set the color, else set another color.
> 
> I am not understanding the difficulty in this. I am wondering if i do not fully understand your question.

got that, its working fine now
