### ISSUE TITLE
Calendar View show next month cell in stack view

### ISSUE THREAD

**Issue by SohaibSiddique** [patchthecode/JTAppleCalendar#1321]
Hello, 

created a view with calendar view when I load this view in stack view it show next month cell, 
but if I directly add calendar view in view controller its working fine, any lead please 

![Screenshot 2021-04-28 at 11 11 05 PM](https://user-images.githubusercontent.com/8692719/116452482-36450680-a877-11eb-9637-c28a8c641507.png)

**Comment by patchthecode** [comment]
doees your stack view have complete correct constraints set? if yes, 
can you provide me a sample app with the problem (with all code removed). A total blank project that recreates this issue.

**Comment by SohaibSiddique** [comment]
> doees your stack view have complete correct constraints set? if yes, 
> 
> can you provide me a sample app with the problem (with all code removed). A total blank project that recreates this issue.

the issue with the constraints i set fix constraint for my view and problem solved, thanks for you response 😊
