### ISSUE TITLE
Can we pass the dates between the start and end date , and that in between date cannot be select as of the outside date .

### ISSUE THREAD

**Issue by vijay12345678910** [patchthecode/JTAppleCalendar#1322]
Hello is there any functionality in which i can pass the dates between the start and end date , and that in between date cannot be select as of the outside date .
And in between dates can be multiple.

**Comment by patchthecode** [comment]
yes,
just implement the shouldSelect delegate function, and you can determine what cells are selectable based on your own criteria

**Comment by vijay12345678910** [comment]
So i have to implement all my logic on the shouldSelect delegate function for my custom functionality. Whether the cell can be selectable or not. 
Is their any other method in which i can pass multiple dates and that date cannot be selectable by the user.

**Comment by patchthecode** [comment]
>  Is their any other method in which i can pass multiple dates and that date cannot be selectable by the user.

I am not sure why you are asking this.  Was the problem resolved when you implemented it in the shouldSelect function?
