### ISSUE TITLE
Conformance of enum 'MonthsOfYear' to protocol 'CaseIterable'

### ISSUE THREAD

**Issue by jolyot** [patchthecode/JTAppleCalendar#1326]
First, thank you for the awesome product.

My proposal is to make `enum MonthsOfYear` conform to the `CaseIterable` protocol.
If a type conforms to this protocol, you can access a collection of all of the type’s cases by using `allCases` property without generating it for yourself. Therefore, [this line](https://github.com/patchthecode/JTAppleCalendar/blob/f643e2c5f4aca5d78ce3840f37996692888e0147/Sources/JTAppleCalendar/CalendarStructs.swift#L278) of the code can be written as follows.

`let allMonthsOfYear = MonthsOfYear.allCases` 

Please consider it.

**Comment by patchthecode** [comment]
or better yet, just do a pull request. I'll merge it.
really tied up with 3+ projects right now.

**Comment by patchthecode** [comment]
closing this.
issue was merged
