### ISSUE TITLE
Wrong Date & stops in August

### ISSUE THREAD

**Issue by benifunk** [patchthecode/JTAppleCalendar#133]
Hi Patchthecode,

thanks a lot for sharing this great calendar. I had downloaded the latest version of your calendar. 
I played around with your example app. 
1.) The label has is always one month back example: The calendar with the label selected 9th of August but output is "Selected dates ---> 2016 09 09".
2.) The calendar only works from January 2016 - till August 2016, I cannot go to September by button or gesture.

Do you have an idea? Thanks a lot,
Beni

**Comment by patchthecode** [comment]
1. Is this issue happening on the sample application?
2. What is your time zone? I have the example app's calendar's time zone configured to GMT.

**Comment by benifunk** [comment]
Hi. The issue happens on the sample app. Currently I am in another time zone. I changed it. And that worked, thanks. But there seems to be a bug, when you are in another time zone and let your week start with monday. Than for example today 10th of september is shown as a friday.
But one thing I still cannot figure out. The Calendar only works till the current month, I cannot scroll to october or to further month. 
Thanks beni

**Comment by patchthecode** [comment]
Yea, the sample code is just a sample. 
I configured it for my time zone.
You'll have to set it up for yours.

In the sample app, The SUN | MON | TUE | WED | THU | FRI | SAT  header is not part of the calendar.
If you  look at the sample app, this is just a simple stack view with labels.
Therefore , if you change the start day to monday, you will need to change that. You can make what ever header you want

**Comment by benifunk** [comment]
Thanks you for your fast reply.
But what´s with that:?

2.) The calendar only works from January 2016 - till September 2016, I cannot go to October (or further) by button or gesture.

**Comment by patchthecode** [comment]
You can set where you want the calendar to start, and to stop.
https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial
