### ISSUE TITLE
How to Scroll months in Calendar with Button in DateHeader 

### ISSUE THREAD

**Issue by SwiftSamples** [patchthecode/JTAppleCalendar#1330]
**(Required) Version Number:**

## Description

I have added two buttons(left and right) in DateHeader cell, here if i click left button i need to move to previous months and if i click right button then months should move to future months

![simulator_screenshot_F734AAC6-A09C-4C43-BF13-B89CF5115305](https://user-images.githubusercontent.com/27500812/124767992-e90ba200-df55-11eb-8659-e1f31bb53f47.png)

    func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {

     let header = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: "DateHeader", for: indexPath) as! DateHeader
    formatter.dateFormat = "MMM yyyy"

    header.monthTitle.text = formatter.string(from: range.start)
    formatter.dateFormat  = "EE"
    let dayInWeek = formatter.string(from: toDate) // "Sun"

    header.rBtn.addTarget(self, action: #selector(connected(sender:)), for: .touchUpInside)
    header.lBtn.addTarget(self, action: #selector(connected1(sender:)), for: .touchUpInside)

    return header
    }
    @objc func connected(sender: UIButton){
    print("testing...")

    }
    @objc func connected1(sender: UIButton){
    print("testing111...")
    }

like above i have connected buttons in header, **here how to write code for scroll months in calendar using buttons, please suggest me**

**Comment by patchthecode** [comment]
```
self.calendarView.scrollToSegment(.next)
```

**Comment by SwiftSamples** [comment]
thanks, if i add `self.calendarView.scrollToSegment(.next)` then its moving to future months.. now if i tap left button then i need to move to its previous months as well.. how to do that..
eg.. if i tap on right button then its moving from july to aug, sep..etc
now i need if i click left button in sep then it has to go back to aug and jul..
please guide me

**Comment by SwiftSamples** [comment]
Thank you, its worked.
i used these two lines in two different buttons 
self.calendarView.scrollToSegment(.next)
self.calendarView.scrollToSegment(.previous)

**Comment by SwiftSamples** [comment]
Thank you, its worked

i used below two lines in two different buttons

     self.calendarView.scrollToSegment(.next)
     self.calendarView.scrollToSegment(.previous)
