### ISSUE TITLE
How to give drop shadow to calendar 

### ISSUE THREAD

**Issue by SwiftSamples** [patchthecode/JTAppleCalendar#1331]
**(Required) Version Number:**

## Description

i want shadow to my calendar, so i have given shadow to `calendarView` like below code in `cellForItemAt` method

      func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
        
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        
                calendarView.layer.shadowColor = UIColor.black.cgColor
                calendarView.layer.shadowOffset = CGSize(width: 0, height: 1)
                calendarView.layer.shadowOpacity = 1
                calendarView.layer.shadowRadius = 1.0
                calendarView.layer.cornerRadius = 10
        
                calendarView.clipsToBounds = false
                calendarView.layer.masksToBounds = false
       }

then am getting like below image if i scroll calendar.. 

here shadow is getting but if you observe in right side u can see the unrelated text(dates of next month) are coming.. how to remove that
how to give perfect shadow to calendar, plz do help

![Screenshot 2021-07-08 at 5 34 16 PM](https://user-images.githubusercontent.com/27500812/124918586-d4d9aa80-e012-11eb-9846-130d9c6f5ba4.png)

**Comment by patchthecode** [comment]
hmm.. this question is getting into UI and is not exactly a calendar question.
I do not know much about UI and designs etc. But if you questions about the calendar, then i know how to do it.
