### ISSUE TITLE
How to show only current week days

### ISSUE THREAD

**Issue by SwiftSamples** [patchthecode/JTAppleCalendar#1332]
**(Required) Version Number:**

## Description

I need to show current month as well as current week both depend on button click, if i click month i need to show total month and if i click week i need to show current week.

 now am able to show total month related stuff in calendar

![Screenshot 2021-07-08 at 7 16 20 PM](https://user-images.githubusercontent.com/27500812/124932799-fe013780-e020-11eb-95c3-6e97ef876894.png)

 **now i need to show current week as well in calendar how?** 

![iPhone 6, 7, 8 Plus GÇô 12](https://user-images.githubusercontent.com/27500812/124932886-0fe2da80-e021-11eb-94a1-7b20e89df933.png)

is it possible with one collectionview cell or do i need to add one more cell plz do guide me here. 

**for current, previous and future months am using below code**

    extension ViewController: JTAppleCalendarViewDataSource {

    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
         let formatter = DateFormatter()
         formatter.dateFormat = "yyyy MM dd"
         let startDate =  formatter.date(from: "2010 01 01")!
         let endDate = formatter.date(from: "2050 01 01")!
         return ConfigurationParameters(startDate: startDate, endDate: endDate)
     }
    }
    extension ViewController: JTAppleCalendarViewDelegate {
    
     func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
        
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        
        if testCalendar.isDateInToday(date) {
            cell.dateLabel.textColor = UIColor.blue
            cell.dateLabel.font = UIFont.boldSystemFont(ofSize: 13.0)

        } else {
            testCalendar.isDateInToday(date) == false
    
        }

        return cell
     }
        func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {

        let header = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: "DateHeader", for: indexPath) as! DateHeader
        formatter.dateFormat = "MMM yyyy"

        header.monthTitle.text = formatter.string(from: range.start)
        return header
    }
    }

**to show current week what is the code, please do let me know**

thanks in advance.

**Comment by SwiftSamples** [comment]
Could you guide.. its urgent!!!

**Comment by patchthecode** [comment]
have you taken a look at the examples on the documentation page? Some of the things you are asking is fullly coded examples showing how its done. --> https://patchthecode.com/jtapplecalendar-home/

**Comment by patchthecode** [comment]
The answer to the question you asked is located on topic (5) on that page above.
