### ISSUE TITLE
The date round is truncated

### ISSUE THREAD

**Issue by mishapushka** [patchthecode/JTAppleCalendar#1337]
<img width="275" alt="Снимок экрана 2021-08-03 в 13 29 09" src="https://user-images.githubusercontent.com/72805598/127972293-e10f88ab-9d1c-447b-9a54-d0e2c248971a.png">

the constraints are set normally. such a problem only from the first week of the month.

can you suggest something?

**Comment by patchthecode** [comment]
can you give some more information on this?   is this the yearView?

**Comment by mishapushka** [comment]
Yes, it is the most) made through a xib file.
I looked at the boundaries and there are all the rules. I raised the element higher and narrowed it, the problem remained the same. The size of the numbers changed, a similar situation. I think it's about the framework. Or something is not configured, but what, I cannot understand. I googled your framework and found no information (

**Comment by mishapushka** [comment]
can you tell me about the solution?

**Comment by patchthecode** [comment]
The best way for me to help with something like this is for you to provide a minimal sample project that produces this error.
A minimal project is a basic barebones project with all other code removed to make things simple.

I need this because UI errors like this can happens for very many reasons.

**Comment by patchthecode** [comment]
closing until i get a response
