### ISSUE TITLE
Weekly calendar days are off by a day when iphone setting region set to France

### ISSUE THREAD

**Issue by rs658726** [patchthecode/JTAppleCalendar#1338]
**(Required) Version Number:**
8.0.3
## Description
When region/timezone are set to France, the weekly calendar is off by a day. For example, today is Friday September 17, it will show as Thursday 17.

## Steps To Reproduce
Set Region/Timezone to France and view the weekly calendar.

**Comment by patchthecode** [comment]
this is the most asked question.
here is the full explanation that this is expected and how why you should be using a date formatter
https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
let me know if still stuck.

**Comment by rs658726** [comment]
I'm still stuck unfortunately. I understand dates need to be formatted when printed, but I think the issue I'm seeing is slightly different.

Here is my code for configuring the calendar:
```
    func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters {
        let endDate = Calendar.current.date(byAdding: .year, value: 100, to: Date().startOfMonth)!
        
        viewModel.dateFormatter.dateFormat = "yyyy MM dd"
        viewModel.dateFormatter.locale = .current
        let startDate = viewModel.dateFormatter.date(from: "2019 01 01")!

        let parameters = ConfigurationParameters(startDate: startDate,
                                       endDate: endDate,
                                       numberOfRows: 1,
                                       generateInDates: .forFirstMonthOnly,
                                       generateOutDates: .off,
                                       hasStrictBoundaries: false)

        return parameters
    }
```

And this is the issue I'm seeing below:
<img width="685" alt="Screenshot 2021-09-30 at 15 51 00" src="https://user-images.githubusercontent.com/44455759/135478651-1f9898b9-4435-405e-a8a6-4d7140c3762f.png">

Today is Thursday September 30th 2021... instead it's showing today as Wednesday September 30th 2021.

**Comment by patchthecode** [comment]
Do you have a sample code i can download?

**Comment by rs658726** [comment]
Yes, here it is: https://www.dropbox.com/s/iwkxmkp2knch21g/JTACWeekViewBug.zip?dl=0

I included the calendar in CalendarView. The delegate methods are in ViewController. Just change the region to France and set the time to Paris time and you should see the issue. Thanks for looking into this.

**Comment by patchthecode** [comment]
wht code do you use to change the region to France and set the time to Paris time ?

**Comment by rs658726** [comment]
If you are on iPhone, you need to go to Settings > General > Language and Region and set it to France. You also need to change the time by going Settings > General > Date and Time > Time Zone = Paris

If you run the project on simulator, on your Mac, go to system preferences and do the same. See screenshots below:
<img width="661" alt="Screenshot 2021-10-03 at 14 28 33" src="https://user-images.githubusercontent.com/44455759/135755805-08bf2e86-955e-484b-a6ca-871218b7f72c.png">
<img width="668" alt="Screenshot 2021-10-03 at 14 21 38" src="https://user-images.githubusercontent.com/44455759/135755809-a96db124-2b4d-4f70-b82f-d7f3e849f88d.png">
<img width="671" alt="Screenshot 2021-10-03 at 14 21 26" src="https://user-images.githubusercontent.com/44455759/135755812-3026edf8-3f68-4230-85de-c8b7b3b15ec9.png">

**Comment by patchthecode** [comment]
Ok. You have a fixed header 

SUN |  MON | TUE  .... etc

When you change the time zone to France, over there monday is considered the first day of the week. So i guess apple is doing this under the hood? (who knows).

Anyway, since you have a **fixed header**, to ensure no "Apple magic" causes your dates to become misaligned, tell JTAppleCalendar that your calendar starts on a **Sunday**.

```swift
        let parameters = ConfigurationParameters(startDate: startDate,
                                       endDate: endDate,
                                       numberOfRows: 1,
                                       generateInDates: .forFirstMonthOnly,
                                       firstDayOfWeek: .sunday,  // <------- Put this here
                                       hasStrictBoundaries: false)
```

**Comment by rs658726** [comment]
Is there any way to have a dynamic header? 

Thank you for looking into this!!

**Comment by patchthecode** [comment]
Yes there is.  But there will be a different look to it as it scrolls with your calendar.

--> https://patchthecode.com/jtapplecalendar-home/
Then scroll to `Headers`

**Comment by rs658726** [comment]
Thank you so much @patchthecode
