### ISSUE TITLE
'JTAppleCalendarView' is unavailable: 'JTAppleCalendarView' has been renamed to '_TtC15JTAppleCalendar13JTACMonthView'

### ISSUE THREAD

**Issue by SwiftSamples** [patchthecode/JTAppleCalendar#1344]
i have installed below version pod in my project

    pod 'JTAppleCalendar', '~> 8.0.2'

**(Required) Version Number:**

## Description

and i am using iOS 14.2 version in xcode...

after successfull installation when i use code then getting errors

 @IBOutlet var calendarView: JTAppleCalendarView!

>'JTAppleCalendarView' is unavailable: 'JTAppleCalendarView' has been renamed to '_TtC15JTAppleCalendar13JTACMonthView'

in my total project i am getting so many errors '`JTAppleCalendarView' is unavailable:` why where am i wrong

please respond quickly.. i am in tooo hurry.. i got stuck here from so long

**Comment by webd4everyone** [comment]
Hii
Were you able to resolve this?

**Comment by patchthecode** [comment]
Its been renamed.
if you have migrated to latst version.
Migration guide is here https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/

Also, please do a CMD + SHIFT + K to clean your Xcode. Somtimes  Xcode doesnt clean well after upgrade and you need to do this.
