### ISSUE TITLE
Update podSpec to 8.0.4?

### ISSUE THREAD

**Issue by criRob** [patchthecode/JTAppleCalendar#1345]
Would it be possible to update the podSpec to 8.0.4 so that at least the warning from Xcode (specifically #1307) would be brought down? Not an important issue, but I'd love to be able to remove the deprecation warnings.

Thanks!

**Comment by waterskier2007** [comment]
Same applies for creating a tag for SPM

**Comment by patchthecode** [comment]
Please send in a PR, and i'll merge.
I am in between many things at the moment.

**Comment by waterskier2007** [comment]
It's not a PR that's needed. Just a tag w/ a new version. The issue is that the current release is almost two years old and doesn't contain recent commits.

**Comment by patchthecode** [comment]
Understood. In that case, i have some account resolving to do.
This account is back by 2 factor auth.
Phone is fried. Please give me some time to resolve.

**Comment by waterskier2007** [comment]
@patchthecode any update?

**Comment by patchthecode** [comment]
finally got access back to my account.
updated the tag.
