### ISSUE TITLE
Issue with Month days

### ISSUE THREAD

**Issue by mdanazhiev** [patchthecode/JTAppleCalendar#1346]
**Version Number: '8.0.3'**

## Description
We have setup the month with the following parameters:
```swift
return ConfigurationParameters(
            startDate: startDate,
            endDate: endDate,
            numberOfRows: 6,
            calendar: Calendar.custom,
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: firstDayOfWeek,
            hasStrictBoundaries: true)
```
Here is the Calendar.custom:
```swift
static var `custom`: Calendar {
        var calendar = Calendar(identifier: .gregorian)
        calendar.locale =  Locale(identifier: "en_US")
        calendar.timeZone = TimeZone(abbreviation: "UTC")!
        return calendar
 }
```
## Steps To Reproduce
When we have time zone somewhere in EU it is working correctly and is showing correct days:
![IMG_2263](https://user-images.githubusercontent.com/36884041/154688485-88af277f-eb4d-420d-bc08-9f37977774b5.PNG)
But if you switch to US/Canada (Toronto, Alaska) we get shown 31st in the February:
![IMG_2264](https://user-images.githubusercontent.com/36884041/154688596-4165e714-79f8-48f3-b3e8-e98260c98211.PNG)
Here are some logs:

> JTACMonthView cellForItemAt date:2022-01-30 00:00:00 +0000, cellState:CellState(isSelected: false, text: "30", dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, date: 2022-01-30 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.sunday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil), indexPath:[0, 35]
JTACMonthView cellForItemAt date:2022-01-30 00:00:00 +0000, shouldHideCellNotInCurrentMonth:false
JTACMonthView cellForItemAt date:2022-01-31 00:00:00 +0000, cellState:CellState(isSelected: false, text: "31", dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, date: 2022-01-31 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.monday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil), indexPath:[0, 36]
JTACMonthView cellForItemAt date:2022-01-31 00:00:00 +0000, shouldHideCellNotInCurrentMonth:false
JTACMonthView cellForItemAt date:2022-01-30 00:00:00 +0000, cellState:CellState(isSelected: false, text: "30", dateBelongsTo: JTAppleCalendar.DateOwner.previousMonthWithinBoundary, date: 2022-01-30 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.sunday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil), indexPath:[1, 0]
JTACMonthView cellForItemAt date:2022-01-30 00:00:00 +0000, shouldHideCellNotInCurrentMonth:true
JTACMonthView cellForItemAt date:2022-01-31 00:00:00 +0000, cellState:CellState(isSelected: false, text: "31", dateBelongsTo: JTAppleCalendar.DateOwner.previousMonthWithinBoundary, date: 2022-01-31 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.monday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil), indexPath:[1, 1]
JTACMonthView cellForItemAt date:2022-01-31 00:00:00 +0000, shouldHideCellNotInCurrentMonth:true
JTACMonthView cellForItemAt date:2022-02-01 00:00:00 +0000, cellState:CellState(isSelected: false, text: "1", dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, date: 2022-02-01 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.tuesday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil), indexPath:[1, 2]
JTACMonthView cellForItemAt date:2022-02-01 00:00:00 +0000, shouldHideCellNotInCurrentMonth:false
JTACMonthView cellForItemAt date:2022-02-02 00:00:00 +0000, cellState:CellState(isSelected: false, text: "2", dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, date: 2022-02-02 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.wednesday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil), indexPath:[1, 3]
JTACMonthView cellForItemAt date:2022-02-02 00:00:00 +0000, shouldHideCellNotInCurrentMonth:false

## Expected Behavior
Not to add 31st to February.

## Additional Context
Any point to where I can look will be really helpful.

**Comment by mdanazhiev** [comment]
CellState:

> (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil)===
===Inspire cellStateFromIndexPath: CellState(isSelected: false, text: "31", dateBelongsTo: JTAppleCalendar.DateOwner.previousMonthWithinBoundary, date: 2022-01-31 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.monday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil)===
===Inspire cellStateFromIndexPath: CellState(isSelected: false, text: "1", dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, date: 2022-02-01 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.tuesday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: nil)===

CellState for selection:

> ===Inspire cellStateFromIndexPath: CellState(isSelected: true, text: "19", dateBelongsTo: JTAppleCalendar.DateOwner.thisMonth, date: 2022-02-19 00:00:00 +0000, day: JTAppleCalendar.DaysOfWeek.saturday, row: (Function), column: (Function), dateSection: (Function), selectedPosition: (Function), cell: (Function), selectionType: Optional(JTAppleCalendar.SelectionType.programatic))===
But actual selection is 18th
![simulator_screenshot_26025421-212A-4AD8-BB6F-2562E266A82C](https://user-images.githubusercontent.com/36884041/154932342-d753c2ae-2a7a-42d2-8d43-148687c97d5b.png)

**Comment by mdanazhiev** [comment]
Closing the issue, the problem was from our side.

**Comment by patchthecode** [comment]
😅 awesome
