### ISSUE TITLE
Calendar moving also up and down inside the view.

### ISSUE THREAD

**Issue by mvorisis** [patchthecode/JTAppleCalendar#135]
Hello. And congrats for your great library. The best calendar is here 👍 

So i've followed the wiki tutorial and also i saw the "example for iOS" that you have inside.

I've setted up the calendar as you say so but I have 1 issue and 1 question.

1 - Issue:

The callendar is moving also up and down inside the view although i have setted up the constrains.

2 - Question:

I'm going to add a bubble with a number inside each cell which by default will be hidden. And i will make a query to my database and take the count of events that happens on each day inside the calendar. Where can i change the label inside that bubble (a view) inside a cellview ???
It should be inside the ViewController or inside the CellView?

thanks a lot for your time!

**Comment by patchthecode** [comment]
I think i will change the example because it seems it is confusing you guys.

For issue # 2 
The calendar is like a UITableView.
In a tableview, `cellForItemAtIndexPath` is where you setup your cell.
In this library, `isAboutToDisplayCell` is where you setup your cell.

For issue # 1, you'll have to show a screen shot or something, Im not sure i understand what you mean.

**Comment by mvorisis** [comment]
ok I fixed issue # 1 I saw that you used stack views but my app is for ios8 and later so I couldn't do with stack view. So I used a simple uiview and put inside it the calendar.
Thanks for your answer

**Comment by ReiVerdugo** [comment]
Hey, I'm having this problem with Swift 3 and Xcode 8. The view can move up and down when scrolling. I tried adding a stack view but that didn't work. 
This didn't happen with Swift 2.2 and Xcode 7. Am I doing something wrong?
Thanks in advance

![simulator screen shot sep 21 2016 10 45 59 am](https://cloud.githubusercontent.com/assets/3844785/18715901/e15dc32a-7fe8-11e6-8efe-6b8125fde9a1.png)

**Comment by mvorisis** [comment]
Did you try to put a uiview and put the calendar inside it?

**Comment by ReiVerdugo** [comment]
Yep, and it didn't work. I tried setting the custom class and even putting the custom clase inside an UIView (and also Stack View). No results so far

**Comment by patchthecode** [comment]
@ReiVerdugo is it possible that you can provide just a sample app with the problem? I would need to recreate this from my end. The calendar should not be bouncing up and down inside the view.

**Comment by mvorisis** [comment]
In my case its working maybe you missed something, tomorrow I will test it with xcode 8 (because I don't have access now).
One more time what I did: Put a UIView setted up the constraints and then I put another uiview which I changed its class to jtapplecalendar and set the constraints top left bottom right to 0 0 0 0

**Comment by ReiVerdugo** [comment]
I've found the error. 
The problem with the view occurs when "Adjust scroll view insets" is checked and the view controller containing the calendar is embed in a navigation controller. I don't know if this happened in previous swift or xcode versions, but this time that seemed to be the cause.
Unchecking "Adjust scroll view insets" will fix it and the view will move up-and-down no more :) 
Thank you all!
