### ISSUE TITLE
How to get the start and end dates of the displayed dates?

### ISSUE THREAD

**Issue by thanhnmit91** [patchthecode/JTAppleCalendar#1350]
[
<img width="373" alt="Screen Shot 2022-04-27 at 9 31 56 AM" src="https://user-images.githubusercontent.com/7372388/165427502-a65bcb21-d535-448d-a78c-d09784fa3ccb.png">
](url)

May I ask, how can I get the start date of 27th and the end date of 7th as shown above. Thanks

**Comment by patchthecode** [comment]
what do you mean by "get" the dates?

**Comment by thanhnmit91** [comment]
I want to get the displayed start and end date to call the api to get the event data from the server.  For example, the picture above shows the 27th to the 7th. You know what I mean?

**Comment by patchthecode** [comment]
The ones that come to mind are the `cellStatusForDate` functions and the `visibleDates` functions.
Remember, there are many variations of these functions, pick one that suites you

**Comment by thanhnmit91** [comment]
I solved it. Thanks very much
