### ISSUE TITLE
How can I select the current date by default

### ISSUE THREAD

**Issue by josepfm** [patchthecode/JTAppleCalendar#1356]
Hello!

I would like to know how I can configure the calendar so that when loading for the first time, by default, the current date is selected.

The configuration is: 

return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: numberOfRows).

Where startDate is before the current date, since I want it to be able to move forward and backward.

**Comment by patchthecode** [comment]
here is an example of how i setup my calendar:

```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        calendarView.register(UINib(nibName: "PinkSectionHeaderView", bundle: Bundle.main),
                              forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader,
                              withReuseIdentifier: "PinkSectionHeaderView")
       
        calendarView.scrollToDate(Date()) // <--- This is what you want
        calendarView.selectDates([Date()])
        
        self.calendarView.visibleDates {[unowned self] (visibleDates: DateSegmentInfo) in
            self.setupViewsOfCalendar(from: visibleDates)
        }
        setupScrollMode()
    }
```

**Comment by patchthecode** [comment]
Close this issue if this works for you.

**Comment by patchthecode** [comment]
Closing this issue as resolved.
If not let me know.
