### ISSUE TITLE
If you reload a date that belongs to a previous month, or a following month (in-dates and out-dates), it does not get reloaded, because the counterpart dates were not searched for.

### ISSUE THREAD

**Issue by deniszhukov** [patchthecode/JTAppleCalendar#136]
Hi, 
Thanks for your awesome calendar!

When I'm calling calendarView.reloadDates(updatedDates) and the date is from another month (for example, if month starts on Wednesday and I need to reload Monday and Tuesday) it doesn't call isAboutToDisplayCell with this NSDate. 

Thanks for your work!

**Comment by deniszhukov** [comment]
It works!
Thank you so much for such a quick reply.

**Comment by patchthecode** [comment]
OK. since it works, i will patch this in the next release.

**Comment by acegreen** [comment]
@patchthecode Hey guys, this issue is happening to me

**Comment by patchthecode** [comment]
What version of the calendar are you using? @acegreen
