### ISSUE TITLE
How to remove cell's border line

### ISSUE THREAD

**Issue by ymatt345** [patchthecode/JTAppleCalendar#1361]
JTAppleCalendar (8.0.4)

I tried to remove cell border line from the SampleJITAppleCalender, however I could not find any codes to create cell border line.
So I create my own code to initialize JTAppleCalendar by copying CellView.xib as follows.   

 override func viewDidLoad() {
        super.viewDidLoad()
        print("viewDidLoad CalenderVC")
        tableView.delegate = self
        tableView.dataSource = self as UITableViewDataSource
        
        let nibName = UINib(nibName: "CellView", bundle:Bundle.main)
        calendarView.register(nibName, forCellWithReuseIdentifier: "CellView")
        calendarView.scrollToDate(Date())
        calendarView.calendarDataSource  = self
        calendarView.calendarDelegate  = self
        self.calendarView.visibleDates {[unowned self] (visibleDates: DateSegmentInfo) in
            self.setupViewsOfCalendar(from: visibleDates)
        }
        calendarView.allowsMultipleSelection = false
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        calendarView.scrollingMode = allScrollModes[6]
        
        selectDate = Date()
        readEventsForThisMonth()
    }

[JTAPPLECalendar ScreenShot]
(https://user-images.githubusercontent.com/25836706/198818808-15dddf08-d258-4a52-b1dd-ea2bb785ae83.png)

Please advise me how to remove the border line from the cells.
Thank you.

**Comment by patchthecode** [comment]
If you want to build a calendar a better bet would be to follow the tutorials here ->

https://patchthecode.com/jtapplecalendar-home/

Click on the `Build a calendar from scratch` tutorial.
At the bottom of each tutorial, there is sample code given there.

BUT
keep in mind that the tutorials are in Version 7.0
So use them as a guide to build your 8.0 calendar.
Dont just copy the code and try to modify it.

**Comment by ymatt345** [comment]
I created from scratch.  The only thing I copied from the sample code was CellView.xib.
There is no code to draw border line in my code and there is no proof to remove border line when I made own.xib.
My development environment is Xcode 14.01 and IOS16.0.  
I think that the SampleJTAppleCalender intentionally draw border line.
So please advice me your hidden method to draw border line.
Best regards.

**Comment by ARGAMX** [comment]
Problem with that border is because it specified in xib file (CellView.xib), which is not common approach.
If you copy-past that xib you will face that border.
To remove it just search for 'layer.borderWidth' in Project to find and the delete that border.

**Comment by patchthecode** [comment]
@ARGAMX is correct.

@ymatt345 sorry i could respond sooner. I'm really tied up between projects and gave you the solution which was to create the project from scratch (no copy and paste 😉 as i wont have the time to go through this many times with everyone.)
