### ISSUE TITLE
didSelectDate is not called if calendar is ambedded in UINavigationController

### ISSUE THREAD

**Issue by DjaberDribine** [patchthecode/JTAppleCalendar#1363]
Version Number: 8.0.4
First thank you for this great library

My problem is  didSelectDate not called (with simple tap) when calendar view is ambedded in  UINavigationController .
on the other hand, didSelectDate is called when  calendar view is not embedded in  UINavigationController.
can you help me please ?

**Comment by patchthecode** [comment]
fastest way for a fix is to create an empty project that recreates the issue.
this helps me solve this a bunch.

**Comment by DjaberDribine** [comment]
Solved, i didn't  connect delegate correctly.
thx

**Comment by patchthecode** [comment]
cool. 
glad its fixed.
