### ISSUE TITLE
Doesn't Compile in Xcode 15

### ISSUE THREAD

**Issue by alex-taffe** [patchthecode/JTAppleCalendar#1369]
**(Required) Version Number:**
8.0.4

## Description
Xcode 15 no longer allows stored properties to be marked unavailable

## Steps To Reproduce
Try compiling with Xcode 15

## Expected Behavior
Compiles properly

## Additional Context
Xcode 15 is still a beta so not an immediate need

![image](https://github.com/patchthecode/JTAppleCalendar/assets/6820226/6830b43c-a139-4fe8-87a2-1093360b3be9)

**Comment by florentmorin** [comment]
I have made a fork if you want. https://github.com/florentmorin/JTAppleCalendar

**Comment by waterskier2007** [comment]
@florentmorin any thoughts on opening a PR for that? Maybe a major version bump is in order for things like this (deprecation removals, etc).

**Comment by nivas96** [comment]
I am still Facing this issue after updating SPM to 8.0.4  @waterskier2007

**Comment by alex-taffe** [comment]
Was fixed in 8.0.5
