### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by ArdaDinler** [patchthecode/JTAppleCalendar#1372]
Version Number: 8.0.3

Hi,

After we upgrade to new Xcode version, 15.0 Beta, we have gotten error below. 

Stored properties cannot be marked unavailable with '@available' inside JTACMonthView file  line number: 66

<img width="825" alt="image" src="https://github.com/patchthecode/JTAppleCalendar/assets/19167046/f6a7a670-225e-4b15-8de1-f8b8524cf02e">

Could you help us please ? 
Best Regards.

**Comment by patchthecode** [comment]
I think this should be resolved in the latest 8.0.5 release

**Comment by ArdaDinler** [comment]
Thank you for response very quickly 👍 💯
