### ISSUE TITLE
Spacing between dates

### ISSUE THREAD

**Issue by Adventura33** [patchthecode/JTAppleCalendar#1373]
**(Required) Version Number:*8.0.4*

## Additional Context
<img width="288" alt="Снимок экрана 2023-06-22 в 11 09 46" src="https://github.com/patchthecode/JTAppleCalendar/assets/49437937/92bcb183-1646-44e6-a4b6-c83e90425018">

**Comment by patchthecode** [comment]
Have you tried out the example project attached with this repository?
