### ISSUE TITLE
Xcode15: Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by havetherain** [patchthecode/JTAppleCalendar#1374]
**(Required) Version Number: 8.0.4**

## Description
 - I ran into this issue while trying to run iOS 17 beta testing in Xcode 15.
## Steps To Reproduce
 - i will just bulid in Xcode 15 for iOS 17 beta 
## Additional Context
<img width="1624" alt="스크린샷 2023-06-23 오후 4 18 08" src="https://github.com/patchthecode/JTAppleCalendar/assets/53065255/41b39423-82c2-45e1-b9e7-7220532c5cc1">

**Comment by werbhelius** [comment]
I have the same problem, have you solved it?

**Comment by patchthecode** [comment]
update to the latest version

**Comment by waseemkhanyes** [comment]
Thanks
