### ISSUE TITLE
 JTACMonthView.reloadData completion handler is not always invoked

### ISSUE THREAD

**Issue by robertcrabtree** [patchthecode/JTAppleCalendar#1375]
**(Required) Version Number:**

8.0.5

## Description

`JTACMonthView.reloadData(withAnchor:completionHandler)` does not invoke the completion handler if reloading is in progress. This creates a problem if we are waiting for the completion handler to be invoked before performing an important task. Nor is there a way to determine if the `JTACMonthView` is currently reloading since `JTACMonthView.isReloadDataInProgress` is not a public property.

## Steps To Reproduce

Call `JTACMonthView.reloadData(withAnchor:completionHandler)` in rapid succession.

## Expected Behavior

`JTACMonthView.reloadData(withAnchor:completionHandler)` completion handler is invoked for every call.

## Additional Context

It sort of makes sense that the completion handler isn't invoked if `reloadData` doesn't actually complete but this is debatable.

At the very least `JTACMonthView.isReloadDataInProgress` should be public so we don't have to track it ourselves.

**Comment by cfoughty7** [comment]
@robertcrabtree and I are team members! In our project, there are cases where we would like the data pipeline to be tolerant of potentially rapid updates, which may result in `reloadData` being called in relatively rapid succession. We have an async await wrapper for this function that wraps the  internal `reloadData` function in a continuation, and limit it to the main actor. This effectively serializes those updates for us, and solves the problem.

Curious if you've considered converting or adding similar functions that are async await?

**Comment by robertcrabtree** [comment]
This is the extension that @cfoughty7 is talking about:

```swift
private extension JTACMonthView {
    @MainActor
    func reloadData(withAnchor date: Date? = nil) async {
        await withUnsafeContinuation { @MainActor continutation in
            reloadData(withAnchor: date) {
                continutation.resume()
            }
        }
    }
}

```

Because your `JTACMonthView.reloadData` bails without calling the the completion handler when `isReloadDataInProgress` is true, we can't call `continutation.resume()` in our async wrapper. We only discovered this because it resulted in a memory leak.

**Comment by patchthecode** [comment]
Can you change this code and let me know if it works for you?

if it does, then i'll create a proper fix later on.

Inside the `JTACInteractionMonthFunctions.swift` file you will see the following function 
```swift
reloadData(withAnchor date: Date? = nil, completionHandler: (() -> Void)? = nil)
```

replace the first line of code in that function

```swift
if isReloadDataInProgress { return }
```

with this code instead

```swift
        if isReloadDataInProgress {
            calendarViewLayout.delayedExecutionClosure.append {[weak self] in
                guard let _self = self else { return }
                completionHandler?()
            }
            return
        }
```

This will correctly add the completion handler to the delayed execution. This should have the effect of still reloading the calendar once, but all subsequent reloads _before_ the reload completes will be added to a queue.

_After_ the single reload completes, all the queued up completion handlers will be called.

Let me know if this works.

**Comment by patchthecode** [comment]
Also, Swift's new `Actors`.

hmm.. That would make my code a whole lot cleaner. Since it came out, I never had a chance to go through it.

**Comment by robertcrabtree** [comment]
I'll give it a go on Monday or Tuesday and let you know how it goes 😉

**Comment by patchthecode** [comment]
the code has been commited to master branch
