### ISSUE TITLE
Calendar crashing on iOS 17

### ISSUE THREAD

**Issue by dhawanheena26** [patchthecode/JTAppleCalendar#1379]
UIKitCore                      0x198c58 -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:]
  UIKitCore                      0x163520 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:]
  UIKitCore                      0x1d7a5c -[UICollectionView dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:]

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<string>**8.0.4**</string>
</plist>

Calendar crashes on iOS 17 beta on line dequeueReusableSupplementaryViewOfKind - month header view

App should not crash

**Comment by patchthecode** [comment]
is this production or dev?

i need more log info.
The ones you posted is not sufficient to tell me anything.

Also, we have 8.0.5 version for the latest iOS.
let me know

**Comment by dhawanheena26** [comment]
We created a sample project to replicate this with version 8.0.5

Issues faced on this sample project: 
1.   assert(false, "You have implemted a header size function, but forgot to implement the `headerViewForDateRange` function") - This causes crash, though we have implemented all required methods (size methods)

<img width="1792" alt="MicrosoftTeams-image (24)" src="https://github.com/patchthecode/JTAppleCalendar/assets/17591306/41038672-0ded-4e23-81a4-c4fb7e40f7df">

After commenting this assert function
2. tried to implement calendarSizeForMonths but when I do, the app crashes with error "Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for layout attributes for supplementary view UICollectionElementKindSectionHeader in section 4 when there are only 0 sections in the collection view'"

<img width="1792" alt="MicrosoftTeams-image (23)" src="https://github.com/patchthecode/JTAppleCalendar/assets/17591306/d9bbb86f-1a27-46d9-b4f9-87342600f016">

 Zip file for sample project : 
[headersCrash.zip](https://github.com/patchthecode/JTAppleCalendar/files/12377156/headersCrash.zip)

**Comment by patchthecode** [comment]
According to the code you gave me, you didnt implement the function.

You have implemented this:
```swift
private func calendar(_ calendar: JTACMonthView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTACMonthReusableView? {
// code ....
}
```
But the real function should instead be this:
```swift
func calendar(_ calendar: JTACMonthView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTACMonthReusableView {
// code ...
}
```

**Comment by patchthecode** [comment]
1. remove the `private` and set it as internal
2. remove the optional return `JTACMonthReusableView?` and make it non optional `JTACMonthReusableView`
