### ISSUE TITLE
YES JTApplecalendar supports swift3. Read here for details.

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#138]
Swift 3 branch is available.

but its not an official release yet.
To use it, put this in your podfile.

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'Swift3'
```

**Comment by nouellette** [comment]
I'm seeing two errors with the Swift3 branch. I made the changes locally and it appears to work as intended.

![image](https://cloud.githubusercontent.com/assets/6297832/18530038/a32425d6-7a9d-11e6-919b-fdf6ece12f5a.png)

**Comment by patchthecode** [comment]
Thanks. Is it possible you can do a pull request? I will merge your changes.

**Comment by dbmrq** [comment]
@patchthecode I know you have a lot on your plate, but just so you know, the `swift3` branch apparently doesn't support carthage. Since you're making some big changes it might not be worth it to deal with this yet, I'm guessing the latest version will have to be converted to Swift 3 from scratch. Anyway, I'm looking forward to that. Then I'll work on adding swiftlint and the rest of the stuff we mentioned before.

**Comment by patchthecode** [comment]
@dbmrq the branch im making the changes on called `DynamicGeneration`.

have completed the code to do the in-dates and out-dates. I hope there are no bugs etc. heh.
You you mentioned swiftlint etc. If you are working on this, could you let me know the swift files you are working on so that there will be no conflicts?

**Comment by alexpja** [comment]
I submitted a pull request [here](https://github.com/patchthecode/JTAppleCalendar/pull/139)

**Comment by patchthecode** [comment]
@alexpja thanks. merged

**Comment by antonijap** [comment]
I tried to use `pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'Swift3'` in my Podfile. It generated this:

<img width="574" alt="screen shot 2016-09-17 at 14 28 16" src="https://cloud.githubusercontent.com/assets/12565719/18608192/2be3e1c6-7ce3-11e6-92da-d75ebb385057.png">

Should I wait until you release it officially or...?

**Comment by patchthecode** [comment]
When I did the first conversion, it was XCode 8 Beta. It seems that there are many changes when XCode final release came out. I can do a conversion today.

**Comment by antonijap** [comment]
Perhaps. I removed a pod, then did a pod install. After that included a pod, again pod install and some errors disappeared. But I get missing files from this and some other pods.

**Comment by alexpja** [comment]
@antonijap might be just your project. I made a new project with the Swift3 branch being the only pod and had no issues.

**Comment by antonijap** [comment]
I managed to fix every error but Calendar is behaving very strange. I checked delegate and a datasource methods and discovered that I have `NSDate` instead of `Date` so I changed that but of course then I am not complying to those mandatory methods... Which brings more errors. I'm gonna cry.

**Comment by patchthecode** [comment]
@antonijap Im doing a renewed up date right now.
Should take be another 2 hrs or so. one sec.

**Comment by antonijap** [comment]
Should I update my pod now, do I need to change something in my Podfile?

**Comment by patchthecode** [comment]
Do a pod update now.
I just pushed it.

**Comment by phillippaik** [comment]
Hello! First of all, thank you for your time with this code! Second of all, I am installing the pods using the "pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'Swift3'" line. When I go to the files to "update to Swift 3" I get a bunch of error mentioned by antonijap initially. I uninstalled the podfile and then reinstalled as well. Thank you in advance for your time :D

**Comment by patchthecode** [comment]
Are you using  XCode 8 official release. With iOS 10 swift 3?

**Comment by phillippaik** [comment]
Yes, swift 3 with iOS10 XCode 8

**Comment by antonijap** [comment]
I solved my problem with deleting pods and podfile and then installing it again

**Comment by patchthecode** [comment]
Yes i was wondering the same thing. Because @antonijap bug included the line that says
`use of undeclared type IndexPath`

IndexPath is not an undeclared type in swift, which makes me wonder what would happen did you did a Xclode `clean`, then delete the pods and re-installed. Also, delete you `DerivedData` and `Build` folder. Then rebuild ?

**Comment by phillippaik** [comment]
Ohh! I think I just had to press "build" after seeing the list of errors after conversions. After pressing it, it built it with no errors.

BUT, I have another error for the protocols, sorry to keep bugging you on this! :/

`class CalendarViewController: UIViewController, JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate{

    @IBOutlet weak var calendarView: JTAppleCalendarView!
    override func viewDidLoad() {
        super.viewDidLoad()
        self.calendarView.dataSource = self
        self.calendarView.delegate = self
        self.calendarView.registerCellViewXib(fileName: "CellView")
        // Do any additional setup after loading the view.

    }
    
    func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar) {
        // You can set your date using NSDate() or NSDateFormatter. Your choice.
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let firstDate = formatter.date(from: "2016 01 05")
        let secondDate = NSDate()
        let numberOfRows = 6
        let aCalendar = NSCalendar.current // Properly configure your calendar to your time zone here
        return (startDate: firstDate! as NSDate, endDate: secondDate, numberOfRows: numberOfRows, calendar: aCalendar as NSCalendar)
    }

    func calendar(calendar: JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date: NSDate, cellState: CellState) {
        (cell as! CellView).setupCellBeforeDisplay(cellState: cellState, date: date)
    }
}
`

it says "CalendarViewController does not conform to JTAppleCalendarViewDataScource protocol but I followed all the instructions on the tutorial.

**Comment by patchthecode** [comment]
The tutorial is not yet converted to swift3.
So there is a change you are using the wrong function names. Swift 3 changed most of the function names. Make sure your function names are EXACTLY as it is in the library.

**Comment by phillippaik** [comment]
@patchthecode 
Hi, ok, last time :/ I'm sorry for bugging you, I've been at this 3 days and I still don't get what I'm doing haha. I'm not very close I believe, I got it to load but my last problem is that the dates don't fill up.

It shows the list of "DateTextGoesHere" multiple times without conforming to my "numberofrows" guidelines

```

class CalendarViewController: UIViewController{
    @IBOutlet weak var calendarView: JTAppleCalendarView!

    override func viewDidLoad() {
        super.viewDidLoad()
        self.calendarView.dataSource = self
        self.calendarView.delegate = self
        self.calendarView.registerCellViewXib(fileName: "CellView")
    }
}
extension CalendarViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
    func configureCalendar(_ calendar: JTAppleCalendarView) -> (startDate: Date, endDate: Date, numberOfRows: Int, calendar: Calendar) {
        // You can set your date using Date() or NSDateFormatter. Your choice.
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        let firstDate = formatter.date(from: "2016 01 05")
        let secondDate = Date()
        let numberOfRows = 4
        let aCalendar = Calendar.autoupdatingCurrent // Properly configure your calendar to your time zone here
        
        return (startDate: firstDate!, endDate: secondDate, numberOfRows: numberOfRows, calendar: aCalendar)
    }
    
    
    func calendar(calendar: JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        (cell as! CellView).setupCellBeforeDisplay(cellState: cellState, date: date as Date)
    }
}

```
my xib is created by "User Interface" then "View" then linking everything to my "CellView.swift"

```

import Foundation
import JTAppleCalendar

class CellView: JTAppleDayCellView {
    @IBOutlet var dayLabel: UILabel!
    var normalDayColor = UIColor.black
    var weekendDayColor = UIColor.gray
    
    
    func setupCellBeforeDisplay(cellState: CellState, date: Date) {
        // Setup Cell text
        dayLabel.text =  cellState.text
        
        // Setup text color
        configureTextColor(cellState: cellState)
    }
    
    func configureTextColor(cellState: CellState) {
        if cellState.dateBelongsTo == .thisMonth{
            dayLabel.textColor = normalDayColor
        } else {
            dayLabel.textColor = weekendDayColor
        }
    }
}

```

**Comment by patchthecode** [comment]
@phillippaik i missed your last message.
I didnt realize you responded.

If your issue is unresolved, then open a new issue.
If your matter is urgent, then join me in chat here -> https://gitter.im/patchthecode/JTAppleCalendar

I'm closing this issue, as swift3 has now been merged with master branch

**Comment by vasant-indpro** [comment]
![simulator screen shot - ipad pro 9 7-inch - 2018-05-10 at 14 13 01](https://user-images.githubusercontent.com/31093499/39861199-7f95ef14-545d-11e8-8c76-1677c1986b55.png)


Here is my screenshots. 

I am using latest version of JTAppleCalendar which is 7.1.5, If I add stackView in cell, scrolling isn't smooth(There is jerk while switching between cell) at all, I have tried using just multiple labels, still I experienced the same issue. If I delete all the stackview/Views and keep one or two labels, reduces the amount of jerk.

Could you please suggest me, how my can be designed to reduce the jerk? Thanks!

**Comment by patchthecode** [comment]
@vasant-indpro can you open this under a new issue?

In the new issue, please paste your `cellForItem` code and your `willDisplayCell` code.
