### ISSUE TITLE
Crashlytics Reports 100% Crash Rate in iOS 17

### ISSUE THREAD

**Issue by BCWoodard** [patchthecode/JTAppleCalendar#1380]
**(Required) Version Number: 8.0.4**

## Description
Our implementation of Firebase Crashlytics is reporting a 100% crash rate in JTAppleCalendar v.8.0.4 on iOS devices running iOS 17 (currently in beta). 

The crash does not appear to be device specific. Crashlytics reports it occurring on both iPhone 12 Pro Max and iPhone 14 Pro devices.

The crash is occurring here:

**JTACInteractionMonthFunctions.swift - Line 230
JTACMonthView.reloadData(withAnchor:completionHandler:) + 230**

## Steps To Reproduce
This is a recently discovered issue and is happening in our PROD environment so we have not had the opportunity to investigate further and outline the steps to reproduce. 

With the pending release of iOS 17 we thought it best to alert the JTAppleCalendar team sooner rather than delay.

## Expected Behavior
n/a

## Additional Context
The stack trace from Crashlytics:

Crashed: com.apple.main-thread
0  xxxxxxxxx                      0x79d8d8 JTACMonthView.reloadDelegateDataSource() + 4379826392 (<compiler-generated>:4379826392)
1  xxxxxxxxx                      0x790c14 JTACMonthView.reloadData(withAnchor:completionHandler:) + 230 (JTACInteractionMonthFunctions.swift:230)
2  xxxxxxxxx                      0x6cadb4 TelemedCalendarView.setupCalendarView() + 103 (CalendarView.swift:103)
3  xxxxxxxxx                      0x6cb300 @objc TelemedCalendarView.draw(_:) + 105 (TelemedCalendarView.swift:105)
4  UIKitCore                       0x15ae90 -[UIView(CALayerDelegate) drawLayer:inContext:] + 508
5  QuartzCore                    0x68d78 CABackingStoreUpdate_ + 204
6  QuartzCore                    0x68ca0 invocation function for block in CA::Layer::display_() + 64
7  QuartzCore                    0x68158 -[CALayer _display] + 1636
8  QuartzCore                    0x67470 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 412
9  QuartzCore                    0x6d8a0 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 464
10 QuartzCore                    0x66b90 CA::Transaction::commit() + 648
11 QuartzCore                     0x66838 CA::Transaction::flush_as_runloop_observer(bool) + 88
12 UIKitCore                        0xaad64 _UIApplicationFlushCATransaction + 52
13 UIKitCore                        0xaa87c _UIUpdateSequenceRun + 84
14 UIKitCore                        0xa9f6c schedulerStepScheduledMainSection + 144
15 UIKitCore                        0xaa028 runloopSourceCallback + 92
16 CoreFoundation             0x37acc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
17 CoreFoundation             0x36d48 __CFRunLoopDoSource0 + 176
18 CoreFoundation             0x354fc __CFRunLoopDoSources0 + 244
19 CoreFoundation             0x34238 __CFRunLoopRun + 828
20 CoreFoundation             0x33e18 CFRunLoopRunSpecific + 608
21 GraphicsServices           0x35ec GSEventRunModal + 164
22 UIKitCore                        0x22f300 -[UIApplication _run] + 888
23 UIKitCore                        0x22e93c UIApplicationMain + 340
24 UIKitCore                        0x451e3c keypath_get_selector_hoverStyle + 14728
25 xxxxxxxxx                       0x810c main + 4371874060 (TelemedPatientAPI.swift:4371874060)
26 ???                                   0x1cb3d8d44 (Missing)

**Comment by patchthecode** [comment]
Have you tried updating to 8.0.5 which fixes latest ios 17 issues?
if yes let me know.

**Comment by BCWoodard** [comment]
Thanks! I have a ticket in place to update to 8.0.5. Once that is complete and we've tested, I'll post an update.

**Comment by BCWoodard** [comment]
Hi @patchthecode, 

I've updated to JTAppleCalendar version 8.0.5 in the project. When I run in an iPhone 14 Pro simulator (running iOS 17), I consistently encounter an assertion error in the following location:

**File Name:** JTACMonthlyActionFunctions.swift

**Function:** setupMonthInfoDataForStartAndEndDate(with config: ConfigurationParameters? = nil) -> CalendarData 
(line 124)

**Failure:** assert(false, "Error, your start date cannot be greater than your end date\n") 
(line 135)

When I view the output in the console for 'validConfig', I see that 'validConfig.startDate' == 'validConfig.endDate':
```
validConfig = (JTAppleCalendar.ConfigurationParameters?) some
startDate = (Foundation.Date) 2023-08-31 20:44:51 UTC	
endDate = (Foundation.Date) 2023-08-31 20:44:51 UTC	
numberOfRows = (Int) 1
```

Here is a screenshot from Xcode with the assertion failure and the console output:

![Screenshot 2023-08-31 at 15 51 14](https://github.com/patchthecode/JTAppleCalendar/assets/3208545/f7452530-7c30-480e-bcb3-fccb1671a502)

When I change the simulator to iPhone 14 Pro running iOS 16.4 I do not encounter the assertion failure and am able to complete scheduling as expected.

Just spitballing, but I wonder if speed improvements in iOS 17 are somehow too fast for the .nanosecond level of granularity used when calculating the comparison value?

**Comment by patchthecode** [comment]
Are you setting the startdate to be equal to the enddate?

**Comment by BCWoodard** [comment]
@patchthecode We're not intentionally setting the dates equal (and we don't see this happening in iOS 16.4) but will do some more investigation on our side. We are wondering if there might be some speed improvements in iOS 17 that are causing this behavior when the granularity is set to .nanosecond.

**Comment by patchthecode** [comment]
Thanks, let me know. Because i put a specific guard there to make sure the startdate is not more than the end date.  If there is some nanosecond magic error, then let me know. Currently im still on OS 16 for now. I'll be updating soon.

**Comment by BCWoodard** [comment]
@patchthecode 

We found the issue and it is with our code. As you suggested, we were inadvertently setting the startDate == endDate because we were setting the endDate using a **TimeInterval** like this:
`endDate = endDate.timeIntervalSince1970 > startDate.timeIntervalSince1970 ? endDate : startDate.addingTimeInterval(1)`

When we use the **Calendar** API to set the endDate, then the the assertion in our Unit Test passes in iOS 17:

![Screenshot 2023-09-12 at 08 58 26](https://github.com/patchthecode/JTAppleCalendar/assets/3208545/4b16747e-ace0-4a23-8e04-4fedbaaaa9cd)

Thanks for your patience as we investigated!

**Comment by patchthecode** [comment]
Awesome 👍  
have a good one!
