### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available' error on Xcode 15

### ISSUE THREAD

**Issue by tommyming** [patchthecode/JTAppleCalendar#1381]
**(Required) Version Number:**
8.0.5

## Description
The project uses the library cannot build on Xcode 15, iOS 17.

## Steps To Reproduce
Import the library to any project and try to build it.

## Expected Behavior
Build failure as Swift 5.9 does not support the syntax. This should have happened since Xcode 15 beta.

## Additional Context
Below is a screenshot of the error in `JTACMonthView`.

![Screenshot 2023-09-20 at 11 40 14 AM](https://github.com/patchthecode/JTAppleCalendar/assets/9570653/c779c5d2-b8ad-424b-a555-11b55175e545)

**Comment by Fireroman** [comment]
Same problem... Please help

**Comment by Fireroman** [comment]
> **(Required) Version Number:** 8.0.5
> 
> ## Description
> The project uses the library cannot build on Xcode 15, iOS 17.
> 
> ## Steps To Reproduce
> Import the library to any project and try to build it.
> 
> ## Expected Behavior
> Build failure as Swift 5.9 does not support the syntax. This should have happened since Xcode 15 beta.
> 
> ## Additional Context
> Below is a screenshot of the error in `JTACMonthView`.
> 
> ![Screenshot 2023-09-20 at 11 40 14 AM](https://user-images.githubusercontent.com/9570653/269151951-c779c5d2-b8ad-424b-a555-11b55175e545.png)

Temporary solution - install the 8.0.5 version of this framework.

**Comment by Fireroman** [comment]
@tommyming Temporary solution - install the 8.0.5 version of this framework.

**Comment by patchthecode** [comment]
Im confused.
8.0.5 is supposed to be the solution, and not a temporary one.

however, this issue's original poster says that he's using 8.0.5

@tommyming can you confirm?

**Comment by tommyming** [comment]
@patchthecode 
I have wrongly typed the version to 8.0.5, should be 8.0.4. Let me close the issue real quick.
And I agree that 8.0.5 is a solution, instead of a temporary one.

Tested on Xcode 15, works fine with the project I'm using.

Sorry for the confusion and thanks for that!
