### ISSUE TITLE
Error - Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by veram1996** [patchthecode/JTAppleCalendar#1382]
I am getting an error
<img width="833" alt="Screenshot 2023-09-25 at 3 35 05 PM" src="https://github.com/patchthecode/JTAppleCalendar/assets/63897149/cfdb919e-12ce-4540-a2e3-c683b6838695">
<img width="151" alt="Screenshot 2023-09-25 at 3 36 40 PM" src="https://github.com/patchthecode/JTAppleCalendar/assets/63897149/4865f815-457d-47b3-ae57-f30b6d920bd0">

**Comment by dhawanheena26** [comment]
+1
Xcode - 15 
issue : Stored properties cannot be marked unavailable with '@available'
Issue with line 
    @available(*, unavailable, renamed: "allowsRangedSelection")
In class 
JTACMonthView

**Comment by doodahdayz** [comment]
You might try updating the Swift Package for the calendar to the latest version... When I did that this issue went away.

**Comment by patchthecode** [comment]
update to the latest version.
8.0.5
closing this now.
