### ISSUE TITLE
Xcode 15 Error "Stored properties cannot be marked unavailable with '@available"

### ISSUE THREAD

**Issue by dostoich** [patchthecode/JTAppleCalendar#1383]
**(Required) Version Number:**
8.0.4

## Description
Hi Team, I am getting the following error in XCode 15 - "Stored properties cannot be marked unavailable with '@available'"
The reason for this error is the following line of code -  @available(*, unavailable, renamed: "allowsRangedSelection")

Please advise

**Comment by zlata96** [comment]
Same error :(

Fix please

**Comment by dostoich** [comment]
@zlata96 thank you. This fixed my issue.

**Comment by kanyaneepromma** [comment]
i got [!] CocoaPods could not find compatible versions for pod "JTAppleCalendar":
  In Podfile:
    JTAppleCalendar (= 8.0.5)

None of your spec sources contain a spec satisfying the dependency: `JTAppleCalendar (= 8.0.5)`.

**Comment by patchthecode** [comment]
@kanyaneepromma you might want to do a project clean and rebuild.

because If you open a brand new project, and install this cocoapod, it builds correctly.
So i suspect, you need to do a clean and rebuild.
