### ISSUE TITLE
Additional line of days in previous month if use cellState.dateBelongsTo for cells hide or style

### ISSUE THREAD

**Issue by mrsnow-git** [patchthecode/JTAppleCalendar#1387]
**(Required) Version Number:**

8.0.5

## Description
Simpliest config from tutorial and simple (with default generation) setup for in-out dates (cellState.dateBelongsTo, hide or anything else - doesn't matter).

Have problem with some months - one more row added to previous month, but not at all moths pairs. See the screen:

![IMG_2852](https://github.com/patchthecode/JTAppleCalendar/assets/4985460/8f397a85-2127-4e76-a764-3dde3d5143de)

Possibly I can do something wrong - but there is no place to do mistake - all code is about 20 lines of code.

## Steps To Reproduce

Simple calendar config from tutorial
Simple (with default generation) setup for in-out dates (hide or anything else - doesn't matter)

## Expected Behavior

Now additional line of week added to previous month.

**Comment by patchthecode** [comment]
Show me your config function

**Comment by mrsnow-git** [comment]
> Show me your config function

<img width="679" alt="Снимок экрана 2023-10-23 в 17 26 21" src="https://github.com/patchthecode/JTAppleCalendar/assets/4985460/8c923284-6b85-4894-8435-aef60ea5a635">

**Comment by patchthecode** [comment]
ConfigurationParameters has many parameters for you to configure the look of the calendar.

It doesnt just have startDate and endDate.
Do a CMD + Click into that class to see all the options that are available to you.

You should see the `generateOutdates` parameter.

<img width="529" alt="Screenshot 2023-10-23 at 10 28 12 AM" src="https://github.com/patchthecode/JTAppleCalendar/assets/2439146/0059d2f2-a53d-4ad4-8e7f-fad2234847f7">


Play around with it to see if it has the value you need. Try `tillEndOfRow`

**Comment by mrsnow-git** [comment]
tillEndOfRow helps, thank you

but why this value is now a default? all default values and setup from your tutorial - why in this simple case it has some default value what brings not "standard" calendar month behaviour?

what tillEndOfGrid really mean and what is the case of use for it?
