### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by saeedCodium** [patchthecode/JTAppleCalendar#1388]
The issue happened after opening the project in Xcode 15.0 , our minimum target is 10 and we can not increase it ,
the error happened here 
`@available(*, unavailable, renamed: "allowsRangedSelection")`
`Stored properties cannot be marked unavailable with '@available'`

**Comment by patchthecode** [comment]
Have you upgraded to the latest version?

**Comment by saeedCodium** [comment]
I could not install 8.0.5 

`[!] CocoaPods could not find compatible versions for pod "JTAppleCalendar":
  In Podfile:
    JTAppleCalendar (= 8.0.5)

Specs satisfying the `JTAppleCalendar (= 8.0.5)` dependency were found, but they required a higher minimum deployment target.`

but the 8.0.4 installed successfully

**Comment by patchthecode** [comment]
the deployment target was raise from 10 to 11

https://github.com/patchthecode/JTAppleCalendar/commit/718f0ab68ba0fcd2bc134f6e9d30edc1b9b038e1

Are you still surporting 10 ?

**Comment by saeedCodium** [comment]
oh so that is the case I think , but how it can run successfully in Xcode 14 with the same version ?

**Comment by patchthecode** [comment]
You want Xcode 14 with version 8.0.5? or 8.0.4?

**Comment by saeedCodium** [comment]
Its running success in Xocde 14 with 8.0.4 but the same project won't run success in Xcode 15, and showing that error

**Comment by patchthecode** [comment]
Unless my info is incorrect (and it certainly can be) -> Why are we still supporting deployment target 10?

https://stackoverflow.com/questions/75383283/what-is-the-minimum-deployments-version-we-must-set-for-ios-after-april-2023-in

Can you increase the deployment target in your app, then do a Project Clean. Then try installing version 8.0.5?

**Comment by saeedCodium** [comment]
the thing is that we can not increase the minimum target but right now its ok with Xcode 14 and also if i delete this line 
`@available(*, unavailable, renamed: "allowsRangedSelection")`
I also can run successfully the project on Xcode 15 as well

**Comment by saeedCodium** [comment]
I also increased the minimum target to 12 the issue still happening 
`@available(*, unavailable, renamed: "allowsRangedSelection")`
only with deleting this line the issue would be solved

**Comment by patchthecode** [comment]
understood. Yes, the version 8.0.5 simply deleted that line of code. 8.0.5 doesnt have any major fixes over 8.0.4

All it has is that line deletion to make the error go away. Closing this now. Thanks.
