### ISSUE TITLE
reload data doesn't work

### ISSUE THREAD

**Issue by amirchoupanneadj2** [patchthecode/JTAppleCalendar#1390]
**(Required) Version Number:**
8.0.5

## Description
I'd like to handle available and unavailable dates when  availableDates array  is empty.
I tried using reload data, but when call this function whole calendar will be gone.

 ```swift
 private var availableDates: [Date] = [] {
     didSet {
         calendar?.reloadDates(availableDates)      
     }
}

func calendar(_ calendar: JTACMonthView, willDisplay cell: JTACDayCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
   guard let cell = cell as? CalendarCollectionViewCell else { return }
   if availableDates.contains(date) {
      cell.handleAvailable()
   } else {
      cell.handleUnavailable()
   }
   cell.handleSelection(cellState: cellState)
}
    
func calendar(_ calendar: JTACMonthView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTACDayCell {
   let cell: CalendarCollectionViewCell = calendar.dequeueReusableCell(for: indexPath)
   cell.setContent(cellState)
   return cell
}
```
Do you have any idea why when I use reloaddata calendar will be gone or how I can handle unavailable dates when array is empty?

**Comment by behzadardehei** [comment]
Hi there,
In that case please add a breakpoint on
`func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters` 
And make sure ConfigurationParameters is correct ofter reloadData()

**Comment by patchthecode** [comment]
@amirchoupanneadj2 Im sorry but i am unclear what you are trying to say with "available dates". This seems to be your private variable that you manage yourself?

**Comment by amirchoupanneadj2** [comment]
> Hi there, In that case please add a breakpoint on `func configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters` And make sure ConfigurationParameters is correct ofter reloadData()

Thanks for your help man
