### ISSUE TITLE
Month view display incorrectly when endDate <= Oct 1582

### ISSUE THREAD

**Issue by testluminpdf** [patchthecode/JTAppleCalendar#1392]
**(Required) Version Number:**
8.0.5
## Description
When config JTACMonthView with endDate <= Oct 1582, the day cell display incorrect day.
## Steps To Reproduce
1. Download latest source from github repo: https://github.com/patchthecode/JTAppleCalendar
2. Open file SampleJTAppleCalendar.xcodeproj
3. In xcode, open file ViewController.swift
4. In method `configureCalendar(_ calendar: JTACMonthView) -> ConfigurationParameters`, change config startDate and endDate from: 
```
        let startDate = formatter.date(from: "2018 01 01")!
        let endDate = formatter.date(from: "2020 12 01")!
```
to
```
        let startDate = formatter.date(from: "1582 01 01")!
        let endDate = formatter.date(from: "1583 12 01")!
```
## Expected Behavior
The day cells should display correct day and correct order
## Actual Behavior
The day cells should display incorrect day and incorrect order
Here is a screenshot:
![Simulator Screenshot - iPhone 15 Pro Max - 2024-01-26 at 11 02 35](https://github.com/patchthecode/JTAppleCalendar/assets/124034863/8565a41e-da3f-4e34-9763-3c6ac725184b)
As you can see the day display as 1, 2, 3, 4 then suddenly jump to 15 and so on. Also with strict boundary turn on but some how the days of November also are displayed in this section.
## Additional Context
You can set startDate and endDate arbitrary as you like as long as startDate <= Oct 1582 you'll always reproduce the issue

**Comment by patchthecode** [comment]
How is it supposed to look like?

**Comment by testluminpdf** [comment]
As you can see the day display as 1, 2, 3, 4 then suddenly jump to 15 and so on => the day should display as 1,2 ,3 4, 5, 6, ... And no day of Nov is display in the same section with Oct

**Comment by patchthecode** [comment]
Dont worry, your users wont go that far back 👍

**Comment by testluminpdf** [comment]
Hi in my case users usually choose time in this range so would you mind fixing this?

**Comment by patchthecode** [comment]
you do not have that use case.
and, no and do not want to fix it 😊

However,
 if you carefully explain to me your use valid use case, I will fix it immediately.

**Comment by patchthecode** [comment]
i guess i can close this issue because we both know what happened in the past on that particular date :D
