### ISSUE TITLE
Issue when using @IBDesignable

### ISSUE THREAD

**Issue by antonijap** [patchthecode/JTAppleCalendar#14]
Hi,

@IBDesignable is not working when I add your pod into my Podfile. I don't know how is that related but without calendar this works, with a calendar I get build failed and can't use @IBDesignable, @IBInspectable features and I am not using this on a view that holds a calendar, it is another view.  Do you have any idea what is causing this?

**Comment by antonijap** [comment]
I can ignore this one. I have some weird Xcode problems as usual.

**Comment by patchthecode** [comment]
Alright then, i assume it was fixed?
But yea, IBDesignable and IBInspectable should not affect the calendar. If you need any other help, you know where to find me.
