### ISSUE TITLE
Swift 2.3 support 

### ISSUE THREAD

**Issue by tizaks** [patchthecode/JTAppleCalendar#144]
Hey,

I can see some brief mentions of this, but wanted to check in to see where I could point Carthage to so I can get my project up and running with Swift 2.3. We have plans to move to Swift 3, but it's not something we can do immediately and we'd really like to continue using this project in the meantime.

If there's not currently support in the project, is there anything I can do to help?

Thanks!

**Comment by patchthecode** [comment]
Yea currently there is no swift 2.3
If you help that would be awesome. 
Simply create a branch called `swift2.3`
Do your conversion there and push the branch.
I will do a merge.

Its getting too much for me to maintain swift 2 and swift 3 haha.

**Comment by tizaks** [comment]
Seems like #145 will resolve this. Thanks.
