### ISSUE TITLE
JTAppleCalendar (5.0.1): cellState.text vs cellState.date

### ISSUE THREAD

**Issue by ialqwaiz** [patchthecode/JTAppleCalendar#147]
Hello,
I'm working on a monthly view calendar and I've noticed that cellState.text returns different day than cellState.date (one day in difference). Here is my code:

```
func calendar(calendar : JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date:NSDate, cellState: CellState){
        print("\(cellState.text) ## \(cellState.date)")
    }
```

The result is: 

```
3 ## 2015-10-02 14:00:00 +0000
4 ## 2015-10-03 14:00:00 +0000
5 ## 2015-10-04 14:00:00 +0000
6 ## 2015-10-05 14:00:00 +0000
7 ## 2015-10-06 14:00:00 +0000
8 ## 2015-10-07 14:00:00 +0000
9 ## 2015-10-08 14:00:00 +0000
```

Please advise if I'm doing it wrong or if anything can be done in this regard.
Thanks

**Comment by patchthecode** [comment]
What was the issue?

**Comment by patchthecode** [comment]
Im interested to know what the problem was so that I know how to respond when it pops up again

**Comment by ialqwaiz** [comment]
I was not using the proper NSCalender I guess. After using a date formatter with the proper local I was able to print the date correctly using that date formatter.  :)

**Comment by patchthecode** [comment]
Thank you. I'll note to mention this if anyone else is experiencing this same issue
