### ISSUE TITLE
Calendar not fixed within view...

### ISSUE THREAD

**Issue by davidseek** [patchthecode/JTAppleCalendar#148]
I've used the Calendar in a couple of Views now... In my current View the calendar is not fixed within the View... This behavior is completely random. If I terminate the App 30% the Calendar is set perfectly. 70% like that...

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17073950/18800711/b900b61a-81de-11e6-98fa-fe45af1ea064.gif)

The Code that creates and populates my Calendar is the same as in the Test project.

`    

        calendarView.delegate = self
        calendarView.dataSource = self
        calendarView.registerCellViewXib(fileName: "CellView")
        
        // Enable/disable the following code line to show/hide headers.
        calendarView.registerHeaderViewXibs(fileNames: ["PinkSectionHeaderView", "WhiteSectionHeaderView"]) // headers are Optional. You can register multiple if you want.
        
        // The following default code can be removed since they are already the default.
        // They are only included here so that you can know what properties can be configured
        //_____________________________________________________________________________________________
        calendarView.direction = .Horizontal                                 // default is horizontal
        calendarView.cellInset = CGPoint(x: 3, y: 3)                         // default is (3,3)
        calendarView.allowsMultipleSelection = true                         // default is false
        calendarView.firstDayOfWeek = .Sunday                                // default is Sunday
        calendarView.scrollEnabled = true                                    // default is true
        calendarView.scrollingMode = .StopAtEachCalendarFrameWidth           // default is .StopAtEachCalendarFrameWidth
        calendarView.itemSize = nil                                          // default is nil. Use a value here to change the size of your cells
        calendarView.rangeSelectionWillBeUsed = false                        // default is false
        
        //calendarView.userInteractionEnabled = false
        
        //#############
        calendarView.backgroundColor = UIColor.uIColorFromHex(0x191919)
        //#############
        //_____________________________________________________________________________________________
        
        // Reloading the data on viewDidLoad() is only necessary if you made LAYOUT changes eg. number of row per month change
        // or changing the start day of week from sunday etc etc.
        //calendarView.reloadData()
        
        // After reloading. Scroll to your selected date, and setup your calendar
        calendarView.scrollToDate(NSDate(), triggerScrollToDateDelegate: false, animateScroll: false) {
            let currentDate = self.calendarView.currentCalendarDateSegment()
            self.setupViewsOfCalendar(currentDate.dateRange.start, endDate: currentDate.dateRange.end)
        }
        `

I have set the Constraints of the View to:

<img width="145" alt="screen shot 2016-09-23 at 10 42 38 pm" src="https://cloud.githubusercontent.com/assets/17073950/18800770/1a6269e4-81df-11e6-83c8-30ba545008db.png">

Help is very appreciated.

**Comment by davidseek** [comment]
PS I did `pod update` just 1-2 days ago. So everything should be up to date. Also I'm not forcing any version by using `pod 'JTAppleCalendar'`

**Comment by patchthecode** [comment]
Can you try setting the scroll inset adjustments to false?

--> https://github.com/patchthecode/JTAppleCalendar/issues/31#issuecomment-222337818

**Comment by davidseek** [comment]
Not helping. Unfortunately. Compiled the App 4 times. 3 times with Bug. 1 time without.

**Comment by patchthecode** [comment]
can you join me here -> https://gitter.im/allemattio

**Comment by patchthecode** [comment]
Updated link -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Issue was resolved. Will change the code logic.
