### ISSUE TITLE
Manipulating cell properties explicitly

### ISSUE THREAD

**Issue by itsjc** [patchthecode/JTAppleCalendar#15]
In my isAboutToDisplay method, I manipulate a property of my cell based on some factor (Hide or Unhide a view of the cell).

However, I'm not finding a way to unhide this view of a specific date explicitly.

Unhiding this view is not the same as selecting it. There's selecting a date and then there are the dates with this view unhidden.

So, when the user commits an action, I want to unhide this view of a specific cell (date) but will not be able to because the calendar does not go through isAboutToDisplay again.

Does this make sense?

The calendar loads and some views have a green view unhidden. If the user commits an action ,  I want to set the date in which the action was committed to green (ie unhide the green view); however, unhiding this green view is different than "selecting".

Thanks for your help man

**Comment by patchthecode** [comment]
If you have made changes to the view of a cell, and you want those changes to be reflected, then do the same thing as you would do for a UITableView. Simply call the following function:

`calendarView.reloadData`

Does this work for you?

**Comment by itsjc** [comment]
let's say the calendar has been completely created.

Now, I want to unhide the green view from the cell that is for example 04/05/2016 because the user did something that means that should be green.

That's what I mean.

My isAboutToDisplay has an array of dates which I set to green. This 04/05/2016 will now be part of that array. Does calendarView.reloadData go through the isAboutToDisplay all over again?

Cause if it does that sounds like it would work.

**Comment by patchthecode** [comment]
`calendarView.reloadData()` causes the calendarView to reload its data source. It will call the `isAboutToDisplay` function all over again for all the dates that are visible on the screen

**Comment by itsjc** [comment]
That seems like it would work. Thank you man. The speed in which you respond to these requests is crazy. You will get far bro. I can't thank you enough. Not as much for the help with the project as much as for responding so fast.

**Comment by patchthecode** [comment]
Thanks man! 
Just leave a Star ★ on this project if you like it :)
I want it to be # 1
Have a good one.

**Comment by itsjc** [comment]
No doubt it will be. I'm referring anyone who needs a calendar here. Thanks for your support

**Comment by patchthecode** [comment]
Cool cool.
Have an awesome day :)

**Comment by itsjc** [comment]
Just wondering, how long have you been doing ios?

**Comment by patchthecode** [comment]
Been at it since 2011. Its been a great.
