### ISSUE TITLE
Select separate dates

### ISSUE THREAD

**Issue by bizibizi** [patchthecode/JTAppleCalendar#150]
Is it possible for select(highlight) separate dates? For example 1, 5, 13, 14, 18. I want to select dates in which was custom event

**Comment by patchthecode** [comment]
Yes. you can select any date you want.
You can do anything you want. This library is a UICollectionView.  You can build it however you want.

**Comment by patchthecode** [comment]
`calendarView.allowsMultipleSelection = true`
