### ISSUE TITLE
How to add HeaderView for Showing current Month? and how to set background color for today's date? 

### ISSUE THREAD

**Issue by smitaAcellere** [patchthecode/JTAppleCalendar#151]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

IF YOU ARE USING THE OFFICIAL RELEASE VERSION, FOLLOW THE FOLLOWING 4 INSTRUCTIONS:
________________________________________
1. Are you using the latest version of JTAppleCalendar? Latest version is currently 5.0.1
2. Did you leave a ★ rating on this repository if you like it? Yea.. I kinda need that. Get's me all pumped to answer questions/bugs.
3. Did you check the Wiki page to see if your question is already answered? --> https://github.com/patchthecode/JTAppleCalendar/wiki
4. If you just upgraded from 4.1.4 to 5.0.0, you might want to look at these changes --> https://github.com/patchthecode/JTAppleCalendar/wiki/Message-to-testers-working-on-master-branch

IF YOU ARE INSTEAD USING THE TEST MASTER BRANCH VERSION, THEN PLEASE VISIT THIS LINK ->

https://github.com/patchthecode/JTAppleCalendar/wiki/Message-to-testers-working-on-master-branch

**Comment by patchthecode** [comment]
Have you taken a look at the sample app attached to this project?

**Comment by smitaAcellere** [comment]
@patchthecode  Thank you for your reply. If possible can you please share project's link? I am not getting it.

**Comment by patchthecode** [comment]
The project's link is.. right here :/

**Comment by patchthecode** [comment]
clone it at this address -> https://github.com/patchthecode/JTAppleCalendar.git

**Comment by smitaAcellere** [comment]
@patchthecode  Thank you 👍
