### ISSUE TITLE
Bug on cellState and bubbleView. A full state bubble view is shown between range selections.

### ISSUE THREAD

**Issue by citedjade** [patchthecode/JTAppleCalendar#153]
## 1. BubbleView not be shown(?) if it is deselected and selected in a short time.
For example, 6 Sep(Start Date) should have a bubbleView after deselected and selected ( in a short time)
![2](https://cloud.githubusercontent.com/assets/22003024/19011757/c110fdac-87d2-11e6-8040-d8a4b7b6509b.png)

It is mainly because fade out animation is still running and not completed ? Hence I add a boolean to check the next Tap-able Time . But this design is really not good :((

## 2. the cellState.selectedPosition at row: 0, coloumn:0  is .Left/.Full , but not .Middle that I want. 
Please see gifs for details:
The main different occurs at  01/12/2016 of type1 and 01/01/2017 of type2
### 1. I love it because buddleView only appear at startdate&enddate.
![demo1](https://cloud.githubusercontent.com/assets/22003024/19012977/acac38d0-87f6-11e6-94e2-d0c8ad5eb355.gif)
### 2. can be better at 01/01/2017 (row:0, column:0), it should not have a bubbleView.
![demo2](https://cloud.githubusercontent.com/assets/22003024/19012978/afa17744-87f6-11e6-80a8-55bf761deba0.gif)

**ps. .allowsMultipleSelection & .rangeSelectionWillBeUsed = true
pss. I love JTAppleCalendar! My demo project will be published on gitHub and/or cocoapods soon.**

**Comment by patchthecode** [comment]
Ok, i for your #.1 point, the demo was just a sample code to show you what can be done.
The animation is just some random animation i stole from CVCalendar. But you can put what ever animation you want with what ever code you want. I admit there are some issues with the animation of the bubble view of the sample code. But that's the thing. My job was to create a library which allows you to make the calendar. My job was not to make a fancy calendar. :) 
Tell you what, I will try and improve the sample code, but right now, my main focus is on fixing the calendar library bugs.

For you bubble view error, i think youre right A bubble should not appear at that date. I will look into that issue in a while.

**Comment by patchthecode** [comment]
Can i see the code you use to determine if a cell is to be a full, middle, right, left ?

**Comment by patchthecode** [comment]
10 days has passed since this was opened. I will consider the issue as resolved.
If you are still experiencing this, then you are welcome to re-open it.
