### ISSUE TITLE
Binary operator '==' cannot be applied to operands of type 'CellSate.DateOwner' and '_'

### ISSUE THREAD

**Issue by Norton73** [patchthecode/JTAppleCalendar#154]
I get the above error in the following code.

        func configureTextColor(cellState: CellState) {
                if cellState.dateBelongsTo == .ThisMonth {
                    dayLabel.textColor = normalDayColor
                } else {
                    dayLabel.textColor = weekendDayColor
            }
        }

**Comment by patchthecode** [comment]
It will be helpful if you give me more information.
Version?
iOS10? 
Swift2? 3? 
etc etc etc

**Comment by patchthecode** [comment]
Also, are you experiencing this error in the sample application attached to this project?

**Comment by Norton73** [comment]
Thanks for your reply.

I fixed it. Turns out it was a problem with Swift 3.

**Comment by patchthecode** [comment]
cool.

**Comment by patchthecode** [comment]
Also consider leaving a star rating if this library has helped you. Ratings are needed. Thanks :)

**Comment by amrx06** [comment]
and how did you fix it? it would be nice for people having the same issue, thx

**Comment by patchthecode** [comment]
@amrx06 Ok, i will ask you the same question i asked originally.

Version?
iOS10? 9?
Swift2? 3?
Where are you getting the error?
etc etc etc

**Comment by amrx06** [comment]
Thanks for the quick answer! 
JTAppleCalendar 6.0.1
iOS 10
Swift 3

`    func configureTextColor(cellState: CellState) {
        if cellState.dateBelongsTo == .ThisMonth { //error here : CellView.swift:23:36: Binary operator '==' cannot be applied to operands of type 'DateOwner' and '_'
                dayLabel.textColor = normalDayColor
        } else {
                dayLabel.textColor = weekendDayColor
        }
    }
`

I must say I'm completely new to iOS development and Swift, I used to develop in C++ or php. So spend time on this only if it's beneficial to other users.

**Comment by patchthecode** [comment]
@amrx06 why do you have `.ThisMonth` instead of `.thisMonth` ?

**Comment by amrx06** [comment]
don't know, maybe it occurred while converting fro swift 2 to swift 3. 
Thanks it builds now.
