### ISSUE TITLE
Question about registerxib of cell

### ISSUE THREAD

**Issue by light1874** [patchthecode/JTAppleCalendar#155]
Hello! I found that the cellview.xib must be in MainBundle for loading.

But because my cellView.xib would be combined with some resources into other bundle (or put it on other folder). How can I load the cellView.xib if it is at other place? or which part of code can I override for loading?

**Comment by patchthecode** [comment]
ok. A user recognized this as a problem and have submitted a pull request to enable every one to choose their bundle.

--> https://github.com/patchthecode/JTAppleCalendar/pull/152

The change has been merged to the `swift3` Branch already. What version are you using?

1. The official release?
2. The master branch?
3. the swift3 branch?

**Comment by light1874** [comment]
Thanks patchthecode! I am using official release 5.0.1 ,Xcode 7.3.1 and Swift 2.2

**Comment by patchthecode** [comment]
Hmm.. this update is on the swift3 branch :/ 

I wasn't gonna go back and fix up older versions.
Is it possible that you can look up the change he did here --> https://github.com/patchthecode/JTAppleCalendar/pull/152/commits/367e1bcd60fe54635300ffa1992c414db63bf95b

And see if you can implement it?
If not, then the other option would be to wait until I get to it, which mike take another week or so.

His changes are clear in that file, but If you do not understand it then let me know.

**Comment by patchthecode** [comment]
4 days have passed. I have heard no response. I will assume the issue was resolved.
Please re-open this again if you still need help.
