### ISSUE TITLE
Common Questions Page

### ISSUE THREAD

**Issue by cevanish12** [patchthecode/JTAppleCalendar#156]
Small problem with the Common Questions Page. 

![screen shot 2016-10-03 at 9 42 37 pm](https://cloud.githubusercontent.com/assets/6393310/19060012/7650bb36-89b2-11e6-8042-6a71e0b72374.png)

So under 3, it should say that it should implement 
```swift
func calendar(calendar : JTAppleCalendarView, sectionHeaderSizeForDate dateRange: (start: NSDate, end: NSDate), belongingTo month: Int) -> CGSize
```

and not 

```swift
func calendar(calendar: JTAppleCalendarView, sectionHeaderSizeForDate date: (startDate: NSDate, endDate: NSDate)) -> CGSize 
```

**Comment by patchthecode** [comment]
Thanks man. I am in the middle of updating the wiki right now.
It's gonna be a lot better.
Thanks for pointing this out.

**Comment by cevanish12** [comment]
No worries. Thanks for the hard work.
