### ISSUE TITLE
Header for each month

### ISSUE THREAD

**Issue by edopelawi** [patchthecode/JTAppleCalendar#16]
Hi! First of all, let me tell you that this project is **magnificent**, it might be the latest calendar library that I'll try for creating my iOS apps :)

I got a simple question, is there a way to add a header view for each month? I want to make my calendar a non-paging one, and the empty space between the months seems kinda off... Is it possible to do this now?

Thank you! :)

**Comment by patchthecode** [comment]
Ok trying to understand one part of what you said.

1. What did you mean by `the empty space between the months`?
2. Can you maybe give me a screenshot with a rough drawing of where you'd like the header to be?

With these 2 pieces of info and can think up a solution.

**Comment by patchthecode** [comment]
Also, Basically, what kind of header are we looking at? text/image/... ?

**Comment by edopelawi** [comment]
Right. Here's a screenshot:

<img width="302" alt="screen shot 2016-05-11 at 08 30 51" src="https://cloud.githubusercontent.com/assets/5947111/15167428/081d806c-1753-11e6-8a42-1b4ec18003e9.png">

The "empty space" that I meant was the area where I put the red text. I wanted to add a similiar UIView with the top header (MAY 2016) between there... what do you think?

**Comment by patchthecode** [comment]
Ok. i see the problem.
I guess you have vertical scrolling enabled.
And, you have the monthOut dates visibility to be false. 

Alright, currently it has no headers. But I was going to do an update for it anyway. Will work on something when i get back.

**Comment by edopelawi** [comment]
Yes, I changed the scrolling mode to vertical and hide the dates besides `.ThisMonth`. I forgot to tell you that, my apologies 😅

I see... hey, what if I try to implement it myself and shoot some pull requests when I'm done? I need it to be done this week - and you can focus on other enhancements. If you don't mind, of course 😉

**Comment by patchthecode** [comment]
Sounds ok. Pulls are always welcomed.
Be warned though. Although I am not the best coder in the world, I have been said to be a code Nazi.
The goal of this project is to literally make it the best calendar ios swift control on github. Crazy right? :)

I already had section headers coming in the next upgrade, but sure help will always cut down dev time.

**Comment by patchthecode** [comment]
Implementation completed for vertical scrolling.
just doing last minute testing.

horizontal scrolling to be done.

**Comment by patchthecode** [comment]
Updated to version 3.0.0 which should resolve this. Let me know how if it solved it.

**Comment by edopelawi** [comment]
Apologies for the late response, but I'm currently occupied with my own project 😅 I'm currently using my own patch to add the header in my own fork 😄 I'll try to check it this weekend, is that okay?

That being said, I found that result of delegate's `calendar(_:, canSelectDate:, cell:, cellState:)` method is not used, since the place where it's called (in `collectionView(collectionView:, shouldSelectItemAtIndexPath indexPath:)`, I recall) always returns `true` instead of using the result. I could create a pull request if you want to, but I afraid my fork deviates too far away from the original 😬 and it wouldn't hard to fix that bug, IMO 😄

**Comment by patchthecode** [comment]
Alright. cool. And thanks for finding the other one. I'll track it on this issue https://github.com/patchthecode/JTAppleCalendar/issues/24
Closing this one

**Comment by patchthecode** [comment]
Hmm. By the way, I went through all your commits on your fork.
It seems all of the bugs you have fixed, I have worked on and fixed.

Also worked on performance issues on device. Thanks for all the help thus far.

**Comment by edopelawi** [comment]
Whoa you read my fork? That's pretty cool! :) keep up the good work man!
