### ISSUE TITLE
ObjC version?

### ISSUE THREAD

**Issue by bestman0809** [patchthecode/JTAppleCalendar#164]
Hello.

I am very interested in your code. I would like to use your code in my ObjC code that already exist.

Do you have any ObjC version instead of Swift?

Or How i can use your Swift code in my ObjC code?

Thanks,
Jin.

**Comment by patchthecode** [comment]
Hey, i'm sorry to tell you but, there will be no objc version as it will be too much for me to maintain. If you are trying to implement with Objc, you may have to try this on your own. I think someone did it before, but I do not know how difficult it was
