### ISSUE TITLE
How can i get cell frame by CGPoint in calendar view?

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#168]
How can i get cell frame by CGPoint in calendar view? I need this function to implement Peek and Pop with 3D Touch.

**Comment by patchthecode** [comment]
you can get the cell frame by using `cellState.cell`
You can then inspect the frame.

**Comment by mecid** [comment]
@patchthecode but how can i get CellState?

**Comment by patchthecode** [comment]
in your `isAboutToDisplayCell` function, you have the `cellState` parameter

**Comment by mecid** [comment]
@patchthecode but i need to access cellState information from UIViewControllerPreviewingDelegate methods.

**Comment by patchthecode** [comment]
I am not understanding the situation properly.
can you join me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
@mecid 

I am not understanding the situation properly.
can you join me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
then have you tried this function? -> `public func cellStatus(for date: Date) -> CellState? `

**Comment by patchthecode** [comment]
fixed https://github.com/patchthecode/JTAppleCalendar/commit/c873c81295bbde11484f92f50cd7cc91f33a76d3

**Comment by mecid** [comment]
Thanks!
