### ISSUE TITLE
Master branch using swift 2?

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#169]
I have error like this when using library from master branch.

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by patchthecode** [comment]
Master Branch is now on swift3

Version 5.0.1 is the last version that will use swift2.
Are you able to look at the function that I created on master branch, and then put the method in your 5.0.1 library?

**Comment by mecid** [comment]
@patchthecode  I am using swift3, but i can't build app with master branch. This works only with Swift3 version.

**Comment by patchthecode** [comment]
Master branch has now been officially released as version 6.0

What errors are you getting on build?

**Comment by mecid** [comment]
@patchthecode i understand you.
I have errors from first comment when using master branch.

**Comment by patchthecode** [comment]
OK, are you using and other pods that is *not* swift3? Maybe thats a possible reason for the error?

Also. Can you do what you error message says? It says to click on [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version.

This should show you which files are the problem files. Let me know if these work?

**Comment by mecid** [comment]
Problem fixed. This was cocoapods issue.

**Comment by patchthecode** [comment]
cool 👍
