### ISSUE TITLE
`calendar` parameter is missing in example project

### ISSUE THREAD

**Issue by artemkalinovsky** [patchthecode/JTAppleCalendar#170]
Please, update Example project for version 6.0.0 🙏
For example, there's new parameter `calendar` in  `ConfigurationParameters` initializer

**Comment by patchthecode** [comment]
The example project is up-to-date with version 6.0.1

That `calendar` parameter was supposed to be deleted in version 6.0.0, but i forgot to delete it when i released it. I'll be releasing the 6.0.1 patch to fix this over the weekend.

**Comment by artemkalinovsky** [comment]
thx!👍

**Comment by patchthecode** [comment]
Ok, I just had a user who wanted to make a persian calendar. Therefore I will keep this value in the new version.

I will change it to an identifier however. So, i'll close this issue now.
