### ISSUE TITLE
I am looking for a calender where i can remove the weekends and just show the weekdays (5-day view) & which can also support 3-day view as in google calender. Can you help me create such a thing using your component 

### ISSUE THREAD

**Issue by Manjuprashanth** [patchthecode/JTAppleCalendar#171]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

IF YOU ARE USING THE OFFICIAL RELEASE VERSION, FOLLOW THE FOLLOWING 4 INSTRUCTIONS:
________________________________________

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.0
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. If you just upgraded from version 5.0.1 or from the swift3 branch, function names have changed. So please make sure they match.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Can you just put a screenshot here so that i can have an idea of what youre looking for? I do not know about google calendar. And I'm not sure what it looks like

**Comment by Manjuprashanth** [comment]
PFA ,

So when I say 5 day view I should be able to skip the weekends & show only
weekdays .

**Comment by patchthecode** [comment]
Hmm.. Ok, currently, this is not possible.
You are asking that I do not generate weekends.. hmm.. 

This will mean I will have to do a code upgrade to make this possible, as this cannot be done right now.

**Comment by Manjuprashanth** [comment]
Correct ,hmm., If you by any chance include this feature anytime soon let me know :)

**Comment by patchthecode** [comment]
@Manjuprashanth I will. And i will think about it. Right now it would mean a total change in calculations. But I will think about it in future.

**Comment by Manjuprashanth** [comment]
Sure thanks :)

**Comment by pranav1605** [comment]
@patchthecode Is this feature available?

**Comment by pesama** [comment]
Do we have an update on this feature?
