### ISSUE TITLE
Option for Persian/Jalali Calendar?

### ISSUE THREAD

**Issue by vahids** [patchthecode/JTAppleCalendar#173]
I made some change in source code and It's changed to Persian calendar and Right to Left.
I just want to know is it OK if I change some code in this framework?

**Comment by patchthecode** [comment]
It is ok.
But I need to know the changes you have made so that it will be in future updates of this library forever.

You can do this in two ways. Pick one.

1. You can tell me here and I will add it.
or
2. You can create a pull request, and I will merge it

**Comment by vahids** [comment]
I choose 1, because I made change static

JTAppleCalendarSwift.swift
line 177
change 
from: 
    var cal = Calendar(identifier: .persian)
to: 
    var cal = Calendar(identifier: .gregorian)

It's Changed calendar to Persian.

To change it from LeftToRight to RightToLeft:

Add in Line 282:
    var scalingTransform : CGAffineTransform!
    scalingTransform = CGAffineTransform(scaleX: -1, y: 1);
    cv.transform = scalingTransform

and in ViewController in calendar func add this lines end of function:
    var scalingTransform : CGAffineTransform!
    scalingTransform = CGAffineTransform(scaleX: -1, y: 1);
    myCustomCell.transform = scalingTransform

I don't have any idea how you want make it dynamic and switchable.
easy way is add this post in tutorial.
Thanks :-)

**Comment by patchthecode** [comment]
Thanks for the code help. Let me think on this. If I cant do it in code, I will add your post as a tutorial. Thanks!

**Comment by vahids** [comment]
U welcome body, Thanks to your nice job. 👍

**Comment by patchthecode** [comment]
There is one thing I need to know so that you do not have errors.
Does the Persian/jalali calendar have the same in-dates/out-dates like the gregorian calendar?

<img src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png" width="300">

**Comment by vahids** [comment]
I don't understand your question, 
It's a screenshot of current month in Persian/Jalali calendar.
and today is 30.


![screenshot of simulator 10 21 16 3 14 pm](https://cloud.githubusercontent.com/assets/1405424/19601105/b0e28580-97b4-11e6-865f-4ce7c2ff94f9.png)

**Comment by patchthecode** [comment]
Ok, i cant read your calendar. But is every thing ok with it? If all is well, then great!

Also, I have found a way to add it to the code.
I will let you know shortly

**Comment by vahids** [comment]
Yes, I checked a year with time.ir (Persian data/time reference) calendar and It's currect.

**Comment by patchthecode** [comment]
Awesome.

**Comment by vahids** [comment]
owww, new issue :-/

I make an inside header but It's mirrored :D
Because of   this lines:
var scalingTransform : CGAffineTransform!
scalingTransform = CGAffineTransform(scaleX: -1, y: 1);
myCustomCell.transform = scalingTransform

![screen shot 2016-10-21 at 6 14 13 pm](https://cloud.githubusercontent.com/assets/1405424/19602468/37777240-97ba-11e6-902d-da53e6604f1e.png)

**Comment by vahids** [comment]
HoHaa 🗡 
I found solution.
I have to add

        var scalingTransform : CGAffineTransform!
        scalingTransform = CGAffineTransform(scaleX: -1, y: 1);
        headerCell?.transform = scalingTransform

in end of 
func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) 

too. So this cell will be mirrored and will be done :D

**Comment by patchthecode** [comment]
Hey, so I made an update specially for you. 😎 
I want you to test it to see if it works when you have the time.

Ensure you save your changes first because doing a `pod install` will get rid of your changes to the library.


To test the new feature, do the following:

1) Put this in your `Podfile` 
```   
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```
2) Then run `pod install`.


To use is all you have to do is this:
```
calendarView.changeVisibleDirection(to: .rightToLeft)
```

Let me know if it works.

**Comment by patchthecode** [comment]
@vahids Let me know if it works.

**Comment by vahids** [comment]
Yes working like charm, Great Work!
Just a question I want to put month name in header But I didn't find property to return month or date.

Thanks again. 👍

**Comment by patchthecode** [comment]
You have dates.
You are the one to come up with the names of the month.

When ever you scroll the calendar, this delegate function is called
```swift
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo)
```

With this function you have a variable called `visibleDates`
This tells you the visible dates that are on the screen. From these dates, you can know the month.
Take a look at the sample project attached to this project.
I have code in there that shows you an example of how to get the names of the month.

If you need help, then let me know.

**Comment by patchthecode** [comment]
let visibleInDates = visibleDates.inDates
let visibleOutDates = visibleDates.outDates
let visibleMonthDates = visibleDates.monthDates

<img src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png" width="300">

**Comment by vahids** [comment]
I found it, but it return Gregorian dates. I know I can convert it to Persian and find the month name.
Is it right solution ?

**Comment by patchthecode** [comment]
its returning gregorian dates even though you used `.persian` ?

**Comment by vahids** [comment]
I use .persian in configureCalendar > parameters > calendar

but It print gregorian date
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo){
        print(visibleDates.monthDates)
    }

BTW, It's easy to convert with DateFormatter

**Comment by patchthecode** [comment]
ok do you know how to print a persian date?

I thought that when ever you do this -->

let aDate = Date()

I thought you only got one type of dates. I did not know there is a way to return Persian dates.

**Comment by vahids** [comment]
You right there is not any type or return Persian Date.
It should be converted to local foramt
```swift
        let today = visibleDates.monthDates[1]
        let persian = Calendar(identifier: .persian)
        let formatter = DateFormatter()
        formatter.dateStyle = DateFormatter.Style.long
        formatter.calendar = persian as Calendar!
        formatter.locale = NSLocale(localeIdentifier: "fa_IR") as Locale! // "fa_IR" stands for Persian "ar_??" stands for Islamic ...
        let date = formatter.string(from: today as Date)
        
        print(date)
```

**Comment by patchthecode** [comment]
Cool cool. So all is well now? :D ?

**Comment by vahids** [comment]
Yes, Thank YOU!

**Comment by patchthecode** [comment]
awesome

**Comment by vahids** [comment]
hmm.. new issue 😄 
when I use .rightoleft calendar will be mirrored if rotate screen.

**Comment by patchthecode** [comment]
xD ... i didnt think about that

**Comment by patchthecode** [comment]
@vahids I just made a change. Let me know if orientation bug is now resolved.
I have put the changes on master branch.

**Comment by vahids** [comment]
I don't know what's going on
after updating to xcode 8.1 I have this error:


/Users/vahid/Desktop/PersianCal/Pods/JTAppleCalendar/Sources/JTAppleCalendarView.swift:848:48: Binary operator '>=' cannot be applied to operands of type 'Date' and 'Date!'

this line of code:
if !(firstDayOfDate >= self.startOfMonthCache &&

So, I could not test direction.

**Comment by patchthecode** [comment]
Oh. Yea. that is an XCode bug. 
You need to update to JTAppleCalendar version 6.0.1 to fix this.
Once fixed, you can close this issue :]

**Comment by Kalvin126** [comment]
Did not want to make a new issue but it seems `var orientation` is `internal` protected. Shouldn't it be `public`/`open`?

**Comment by Kalvin126** [comment]
ah. Nevermind I see `public func changeVisibleDirection`

**Comment by AwesDea** [comment]
Did u changed something again? I can't use `changeVisibleDirection `  function.

**Comment by patchthecode** [comment]
@AwesDea it is been changed to a final name that i will not change again.

I have changed it to the same name as the one inside a UICOollectionView. This helps everyone in that they would not have to remember any custom names that i makeup anymore.

The name of the variable under the UICOllectionView is this ->

```swift
calendarView.semanticContentAttribute = ....
```

This is now the same name provided by Apple

**Comment by AtrinNoori** [comment]
hey 
thanks for the amazing library it helps a lot 
although I have an issue with it 
and it is that 
the first six month of the Persian calendar has 31 days 
and the second 5 months has 30 days 
and for the last month it is 29 days but every 4 years in has 30 days 
and I don't know how to implement it 
I used Date formatter for The Persian Calendar but it was no good (first screenshot)
and I don't know why but when I use current date or "Date()" 
it is not exact (2nd Screenshot)
as u can see it says that today is the 22nd of the month but actually It is the 31 first of the month 

<img width="980" alt="screen shot 1396-06-31 at 07 09 26" src="https://user-images.githubusercontent.com/30023387/30728428-fe22e372-9f64-11e7-9545-4ac98414edb4.png">

<img width="977" alt="screen shot 1396-06-31 at 07 11 15" src="https://user-images.githubusercontent.com/30023387/30728464-428d9d22-9f65-11e7-9ef6-6706725e6b1c.png">

**Comment by patchthecode** [comment]
@AtrinNoori you also have to give the library a calendar instance setup for persian.

```swift
let myCalendar = Calendar(identifier: .persian)
myCalendar.timeZone = ....
myCalendar.locale = ....

let params = ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: myCalendar)
```

**Comment by mohammad19991** [comment]
How can use the `ReadingOrientation` it's not in `JTAppleCalendarView`.
I installed 'JTAppleCalendar', '~> 7.1' via Cocoapods.

**Comment by patchthecode** [comment]
@mohammad19991 calendarView.semanticContentAttribute ?

I think that is the name of the variable for UICollectionsViews

**Comment by mohammad19991** [comment]
yea I ended up using `calendarView.semanticContentAttribute`, Thanks.
