### ISSUE TITLE
How can i get visible date range in synchronous way?

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#174]
I have code like this:

```swift
   func previewingContext(_ previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController? {
        guard let cellState = calendarView.cellStatus(at: location) else { return nil }
        guard statisticsCollection?.statistics(for: cellState.date)?.averageQuantity()?.doubleValue(for: HKUnit.heartRate()) ?? 0 > 0 else { return nil }
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        guard
            let detailsVC = storyboard.instantiateViewController(withIdentifier: "Details") as? DayDetailsViewController
            else { return nil }
        
        // hack to force load view hierarchy
        let _ = detailsVC.view
        detailsVC.day = cellState.date
        
        if let frame = cellState.cell()?.frame {
            previewingContext.sourceRect = CGRect(
                x: frame.origin.x,
                y: frame.origin.y - CGFloat(Calendar.current.component(.month, from: cellState.date) - 1) * calendarView.frame.height,
                width: frame.size.width,
                height: frame.size.height
            )
        }
        
        return detailsVC
    }
```

I need convert location CGPoint to CalendarView point.

**Comment by patchthecode** [comment]
Ok. i'm need more clarification.

1. Your Question title says one thing
2. But `I need convert location CGPoint to CalendarView point.` says another thing
3. I can follow what you are trying to accomplish in your code

Can you describe to me what you are trying to accomplish?
Sorry if i didnt understand your question.

**Comment by mecid** [comment]
@patchthecode I have location: CGPoint with values x = 100, y = 200 for example.
But calendarview frame height is more than 4000 px. I need to convert CGPoint it term of calendar view, so i need to know which date is visible to calculate location in term of calendarview.

**Comment by patchthecode** [comment]
In order to know which dates are visible, you have to use the `visibleDates` function. 

You said that you wanted a synchronous version instead of the asynchronous version.
I can make it for you.

But before I make it, can you tell me a reason why the asynchronous one does not work for you?

**Comment by patchthecode** [comment]
@mecid 
In order to know which dates are visible, you have to use the `visibleDates` function. 

You said that you wanted a synchronous version instead of the asynchronous version.
I can make it for you.

But before I make it, can you tell me a reason why the asynchronous one does not work for you?

**Comment by patchthecode** [comment]
I have added a synchronous version of `visibleDates` 
it is on `master` branch

**Comment by mecid** [comment]
@patchthecode because i need to use it in delegate method which is synchronous.
