### ISSUE TITLE
[Question] is there a dayView in this Calendar?

### ISSUE THREAD

**Issue by AsimNet** [patchthecode/JTAppleCalendar#177]
Dears,

is there a dayView in this Calendar? and if it's not, is it easy to implement one?

thanks

**Comment by patchthecode** [comment]
It is extremely easy. 
the "dayView"  is basically like a normal UITableViewCell.
You get if design it however you want.
Join here if you got more questions -> https://gitter.im/patchthecode/JTAppleCalendar
