### ISSUE TITLE
I have a user with issue "cannot find swift declaration for this class" on release build only. Can anyone direct me to why this is happening?

### ISSUE THREAD

**Issue by aparkerryan27** [patchthecode/JTAppleCalendar#178]
Hi, I'm not sure if this is a valid issue for others, but I'm having a problem with the framework itself in another project of mine, where it is not being recognized and I'm getting the error "cannot find swift declaration for this class" an issue that only appears when building for release, and it work fine without any errors of the simulator. It is very confusing for me as I've looked through the valid architectures (they appear to match), checked the attached binary and frameworks/library lists to make sure it was on there, and I still don't understand the issue or a solution. Any ideas?

**Comment by patchthecode** [comment]
Have you checked the following? 
1. http://stackoverflow.com/questions/29851550/myclass-is-unavailable-cannot-find-swift-declaration-for-this-class-release-b
2. http://stackoverflow.com/questions/35030199/myclass-is-unavailable-cannot-find-swift-declaration-for-this-class
3. http://stackoverflow.com/questions/32312489/bridging-header-issue-myclass-is-unavailable-cannot-find-swift-declaration
4. There is also a discussion in the comments section of this page with your same error --> http://artsy.github.io/blog/2015/01/04/cocoapods-and-frameworks/

Let me know if any of those helped?

**Comment by aparkerryan27** [comment]
Yes I have checked those, and the only one that left me with a possible option (after checking all of them), was that there needed to be a seperate build for the simulator and for the device build. Is this something you already had planned for? I saw two frameworks both for ios, should i use one for build and one for testing?

**Comment by patchthecode** [comment]
Ok. honestly, youre the first user of this library that has mentioned this error. I will be very interested to see what the solution you come up with is, so that I would be able to help others.

I am not sure that the settings for the release build would have anything to do with this framework (within your project). But like i said, i will have to research this, because this is new to me.

Are you using cocoapods to install this? or Carthage?

**Comment by aparkerryan27** [comment]
I currently just drag and dropped the framework file in to my project, but I'm going to switch to cocoa pods and let you know what happens. Thank you for helping me, I'm very new to the whole framework thing and I probably just messed something up...

Thanks,
   Parker

**Comment by patchthecode** [comment]
@aparkerryan27 yes, if you just drag and drop the library into your project, you have to know all the the setting etc manually. I am not 100% good and manually setting this thing up. What i'll do is look into manually setting it up and then put it in the tutorial to help others. Up to this point, I just use cocoapods and carthage

**Comment by aparkerryan27** [comment]
Im now using cocoapods, following the instructions in the tutorial, and I'm getting the error: 
 [!] Unable to find a specification for `JTAppleCalendar (~> 6.0)`
But I don't know where this could be coming from either....

**Comment by jaredalexander** [comment]
@aparkerryan27 your pod file should look like:

pod 'JTAppleCalendar, '~> 6.0.1'

**Comment by aparkerryan27** [comment]
Sorry, but that didn't seem to work either.
[!] Unable to find a specification for `JTAppleCalendar (~> 6.0.1)`

**Comment by patchthecode** [comment]
@aparkerryan27 can you join me here? --> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
@jaredalexander @aparkerryan27 
ok we confirmed that it was something to do with cocopods on his system. He's working to resolve this now.
