### ISSUE TITLE
Selecting a date should also select its FollowingMonthWithinBoundary or PreviousMonthWithinBoundary counterpart and vice versa

### ISSUE THREAD

**Issue by N1c0L4z3R** [patchthecode/JTAppleCalendar#18]
Hello,

I'm trying to do a range selection. Everything works fine except when I try to select multiple dates. 
Dates from the previous or next month, displayed in the current month view are not being selected when I call calendarView.selectDates([dates]).
Also, selecting (by tapping) a date from FollowingMonthWithinBoundary or PreviousMonthWithinBoundary won't select the date on the month it belongs.

On the screenshots I selected April 1st as start date and May 10 as end date and I'm selecting all the dates between with calendarView.selectDates method.
![img_1701](https://cloud.githubusercontent.com/assets/9932908/15329394/9474d9f2-1c26-11e6-9d4d-b02d2972fbf1.PNG)
![img_1702](https://cloud.githubusercontent.com/assets/9932908/15329395/948253de-1c26-11e6-92fe-b62d66e0e89c.PNG)

Is there any solution/workaround to achieve this please?

**Comment by patchthecode** [comment]
Looking into this to see if i understand your problem. one sec.

**Comment by patchthecode** [comment]
Ok, i get what you're saying.

Selecting a date should also select its `FollowingMonthWithinBoundary` or `PreviousMonthWithinBoundary` counterpart?

**Comment by N1c0L4z3R** [comment]
Yes that's exactly what I want to do with calendarView.selectDates()
Is it possible please?

**Comment by patchthecode** [comment]
It will be possible after i put in the next update. Should be in by this Saturday worst case or by end of day today best case.
I had forgot to include that code actually. In making the calendar I cant think of every scenario unless you guys point it out.

**Comment by N1c0L4z3R** [comment]
Thank you very much for updating the library! 

For the month displayed on the cell, I did it in the setupCellBeforeDisplay of the CellView.
The xib is the same, only the label is being displayed on 2 lines instead of 1.

```
		let cal: NSCalendar = NSCalendar.currentCalendar()
		let comp: NSDateComponents = cal.components([.Day], fromDate: cellState.date)

		if comp.day == 1 {
			let monthFormatter = NSDateFormatter()
			monthFormatter.dateFormat = "MMM"

			let attributedString = NSMutableAttributedString()
			attributedString.appendString(monthFormatter.stringFromDate(cellState.date), color: UIColor.darkGrayColor(), font: .buttonTextBoldFont())
			attributedString.appendString("\n\(cellState.text)", color: UIColor.darkGrayColor(), font: .termsOfUseFont())
			dayLabel.attributedText = attributedString
		}
```
Hope it helps a bit ;)

**Comment by patchthecode** [comment]
Thanks. I'll continue with the fix i mentioned above, and the update coming for this Saturday.

**Comment by patchthecode** [comment]
updated to version 3.0.0
Let me know if its still an issue. Or we can close this one.

**Comment by N1c0L4z3R** [comment]
Hello! 
Thank you for the update I'm going to check and I'll let you know!

**Comment by patchthecode** [comment]
updated to version 3.0.1 to fix  a small visual bug i missed

**Comment by N1c0L4z3R** [comment]
Hi again. 
Thank you so much!! It's working great! 

I only have one issue now, you commented "init(frame: CGRect)" and the only initializer left is "init?(coder aDecoder: NSCoder)". 
This is good if you are working only with XIB or storyboards, but since in my team we are doing everything in code, this optional initializer is driving me crazy and require me to unwrap the variable everywhere in my code.
Could you add a simple init or uncomment the init(frame: CGRect) line 389 please? :) 

Also do you want me to open a new issue for this? 
I think it could be a nice improvement to make the lib 100% independent from xib.
Thank you for your time and your great lib!

**Comment by patchthecode** [comment]
Ok. Open a new issue for this. I will look into it in the mean time.

**Comment by patchthecode** [comment]
Oh that init! haha. I commented it out to look into something. I forgot to uncomment it.
Uncomment it from your end. I will do a patch release after i work out a visual bug i'm working on.

In the mean time, just open a new issue for this. thanks!
