### ISSUE TITLE
GamingYoutube by me evens

### ISSUE THREAD

**Issue by evens121** [patchthecode/JTAppleCalendar#181]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

IF YOU ARE USING THE OFFICIAL RELEASE VERSION, FOLLOW THE FOLLOWING 4 INSTRUCTIONS:
________________________________________

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.0
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. If you just upgraded from version 5.0.1 or from the swift3 branch, function names have changed. So please make sure they match.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by evens121** [comment]
http://www.media.tv?/mediaTVNetwork/http://www.Doctype.com?/Elgato-Avea-Adroid-EyeTV-network-For-IpadTouch-Power’s-by-iOS-hp-cloud-Companies-links-with-A-Googlemaps-in-all-the-Dells-smart-Drives-computers-upgrades-for-TV’s-apps-wifi’s-in-links-to-all-myself-Accounts-Banks-online-myAccounts-publics-Accounts-and-bank’s-Accounts-online-in-public-accounts-linked-in-to-all-myself-Banks-into-My-Business-onlines-in-Public’s-Accounts-Too/Elgato-Network/https://gaming.youtube.com/watch?v=IjQ_1C6xfUc&mweb=1/Gamingyoutube-live-Broadcastin-playlists-autoplay-links-flashplayers-on-my-youtube-channels/Digital-3D-HD-directvNetwork/Links-Xfinity-x1-platforms-live-connection-it-is-now-update-for-use-Haiti.net/http://www.Doctype.com?/http://www.media.tv?/https://gaming

**Comment by patchthecode** [comment]
Invalid issue.
