### ISSUE TITLE
Binary operator >= can't be applied to operands of type 'Date' and 'Date!'

### ISSUE THREAD

**Issue by bryantm1123** [patchthecode/JTAppleCalendar#182]
Hi,

I've just updated to Xcode 8.1 and Swift 3, and I'm seeing this compiler error in JTAppleCalendarView.swift and UserInteractionFunctions.swift:

`Binary operator '>=' cannot be applied to operands of type 'Date' and 'Date!'`

In JTAppleCalendarView.swift, the errors are in the pathsFromDates function, and in UserInteractionFunctions.swift, in the firstDayOfDate comparison with startOfMonthCache. 

I cloned and am able to build the example project from the master branch. But starting a new project, installing 6.0.0 with Cocoapods, I'm seeing these compiler errors.

Thanks in advance for any help or advice,
Matt

**Comment by patchthecode** [comment]
This problem has been resolved. The latest version of this library is 6.0.1

**Comment by bryantm1123** [comment]
Great, thanks for your time Jay!

**Comment by patchthecode** [comment]
@bryantm1123 youre welcome
