### ISSUE TITLE
Adjustable Outdates for All Past Dates

### ISSUE THREAD

**Issue by aparkerryan27** [patchthecode/JTAppleCalendar#183]
For my project, a booking application, the user can only select today's date, or dates in the present. Is there a way to adjust the outdates in order to make them encompass all days before the present? And on a further note, can the outdates be made unselectable UIViews?

**Comment by patchthecode** [comment]
ok. Lets talk here. I do not understand what you mean -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Basically, Outdates are fixed.
Outdates are based on what you find on a real calendar. These cannot be adjusted.

If you are trying to prevent dates from being selected, then have you looked at the tutorial here-> https://patchthecode.github.io/DateCellConfiguration/

The main tutorial page is here -> https://patchthecode.github.io/

**Comment by aparkerryan27** [comment]
Basically my goal was to change all of the dates before the current date to unselectable dates, in order to prevent the customer from booking in the past. I did this by changing these two functions, just thought posting this might make a possible alternative easier for someone trying to do it in the future.

`
func configureTextColor(_ cellState: CellState) {
       
if cellState.isSelected {
            dayLabel.textColor = textSelectedColor
        } else if cellState.date.timeIntervalSince1970 < Calendar.current.startOfDay(for: Date()).timeIntervalSince1970
{
            dayLabel.textColor = unSelectableColor
}
 else
 if cellState.dateBelongsTo != .thisMonth 
         {
            dayLabel.textColor = previousMonthTextColor
        } else {
            dayLabel.textColor = textDeselectedColor
        }
    }
`

and 

`
func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        (cell as? CellView)?.setupCellBeforeDisplay(cellState, date: date)
        if date.timeIntervalSince1970 >= Calendar.current.startOfDay(for: Date()).timeIntervalSince1970{
            cell.isUserInteractionEnabled = true
        } else {
            cell.isUserInteractionEnabled = false
        }
    }
`

**Comment by patchthecode** [comment]
@aparkerryan27 this is exactly the way to do it.

Just compare the date. And if it is a date that you want disabled, then `cell.isUserInteractionEnabled = false` will do the trick.

**Comment by glennposadas** [comment]
Or handle it at **didSelectDate** delegate, like so:

`    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
        
        // Won't let dates before current date be selected
        
        let currentDate = Date()
        let formattedCurrentDateString = formatter.string(from: currentDate)
        let startDate = formatter.date(from: formattedCurrentDateString)!
        
        if date <= startDate {
            return
        }
        
        handleCellSelection(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        
        print(formatter.string(from: date))
    }
`

**Comment by patchthecode** [comment]
@glennposadas Its been some time since i last answered this question.

I think another way to handle this is by using the the following delegate function:
```swift
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleDayCellView, cellState: CellState)
```

**Comment by glennposadas** [comment]
Hi @patchthecode , just experienced a bug in my code above. I managed to select a date past the current date. yikes. So I copied my implementation to the delegate function you gave. Will edit my code above.
