### ISSUE TITLE
Crash during calendar initialization (ver. 6.0.1, Xcode 8.1)

### ISSUE THREAD

**Issue by artemkalinovsky** [patchthecode/JTAppleCalendar#184]
[calaccessd-2016-10-11-112832.crash.zip](https://github.com/patchthecode/JTAppleCalendar/files/561860/calaccessd-2016-10-11-112832.crash.zip)

**Comment by artemkalinovsky** [comment]
Fixed, that line caused the issue:           
` currentDate = calendar.date(byAdding: addingDateComponents, to: currentDate)!`

**Comment by patchthecode** [comment]
cool
