### ISSUE TITLE
How to deselect cell on second tap?

### ISSUE THREAD

**Issue by leo150** [patchthecode/JTAppleCalendar#185]
Let's say user selects specific day on calendar and cell shows selection view like in [tutorial](https://patchthecode.github.io/DateCellConfiguration/). How can I deselect this cell on second tap?

Is it even possible? I'm not sure but I guess that [UserInteractionFunctions.swift](https://github.com/patchthecode/JTAppleCalendar/blob/master/Sources/UserInteractionFunctions.swift):396 has some logic that blocks deselection behaviour.

**Comment by patchthecode** [comment]
This calendar operates much like a UITableView. 
Have you tried enabling multi selection?

```swift
calendarView.allowsMultipleSelection = true
```

**Comment by leo150** [comment]
Thanks for quick response! It's partly what I need. How can I deselect all other dates when user selects some specific date?

**Comment by leo150** [comment]
Ok, now I get it. In `didSelectDate`: 
`calendar.selectDates(calendar.selectedDates.filter({ $0 != date }))`
