### ISSUE TITLE
Cell status at method returns cellstate with nil cell.

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#186]
Cell status at method returns always cellstate with cell == nil

**Comment by patchthecode** [comment]
OK, hey one thing. Whenever you list issues, it will be helpful if you can reproduce this error in the sample application. I do not have your app, so I would not be able to determine why it is always returning nil for you.

On the sample application the `func cellStatus(at point: CGPoint)` works as expected.

Can you provide some more information on what you are trying to do, and what failed?
Is the cell you are tying to find on/off the screen? 
Is it possible you can reproduce this error on the sample application?

**Comment by mecid** [comment]
@patchthecode same problem with your sample app. 
Just add this extension to your ViewController.

`extension ViewController: UIViewControllerPreviewingDelegate {
    func previewingContext(_ previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController? {
        guard let cellState = calendarView.cellStatus(at: location) else { return nil }
        
        if let cell = cellState.cell() {
            print(cell.frame)
        }
        
        return nil
    }
    
    func previewingContext(_ previewingContext: UIViewControllerPreviewing, commit viewControllerToCommit: UIViewController) {
        self.navigationController?.pushViewController(viewControllerToCommit, animated: true)
    }
}`

And register in viewDidLoad()

`registerForPreviewing(with: self, sourceView: calendarView)`

**Comment by patchthecode** [comment]
I have added the code.
Can you tell me where you are calling 
```
calendarView.cellStatus(at: CGPoint(x: 100, y: 5))
```
from ?

I have added that code in a button and it works. It correctly tells me the cell that is at point 100, 5

**Comment by mecid** [comment]
@patchthecode As you see in my code, this method called in previewingContext, when you deep touch on Cell.

**Comment by patchthecode** [comment]
@mecid ok. I have never worked with 3d touch. And I do not have a 3d-touch device. So I do not have any idea how to fix this.

Is it possible that you can debug the library, and see where the code is failing? I will not be able to test this, unless you know of a way for me to use 3d-touch on the simulator.

**Comment by patchthecode** [comment]
It has been 19 days and no response since. I will close this issue.
If this is still a problem, then we can always always re-open this issue.
