### ISSUE TITLE
Changing ReadingOrientation to rightToLeft cause some UI issue with landscape

### ISSUE THREAD

**Issue by eladschwartz** [patchthecode/JTAppleCalendar#187]
Hi,

I changed the ReadingOrienation to right to left: 
 calendarView.changeVisibleDirection(to: .rightToLeft)

On first load the view looks ok in portrait, but when i'm in landscape that's what happened: 

![img_0090](https://cloud.githubusercontent.com/assets/15890483/19929747/8fff557a-a10d-11e6-8574-e41807863367.PNG)

and  now portrait has the same issue:

![img_0091](https://cloud.githubusercontent.com/assets/15890483/19929784/b94a8a12-a10d-11e6-842d-1ed51babeadc.PNG)

**Comment by patchthecode** [comment]
yea i know about that bug.
it's a small fix i have to do. WIll fix this over the weekend.

**Comment by eladschwartz** [comment]
Cool, 10x!!!

**Comment by patchthecode** [comment]
By the way, are you changing the direction for a eastern type calendar?

**Comment by eladschwartz** [comment]
no, didn't know I needed to do that.

**Comment by patchthecode** [comment]
@eladschwartz I was just wondering why you were changing the direction. But I realized when i looked at your screenshots.

**Comment by patchthecode** [comment]
@eladschwartz I have made a change on master branch. Can you test it and let me know if your issue was resolved?
