### ISSUE TITLE
Support looking up indexPath by point

### ISSUE THREAD

**Issue by tschmitz** [patchthecode/JTAppleCalendar#188]
There are times when I'd like to be able to look up what IndexPath corresponds to a given CGPoint. (For example, I might do that so that I can add a long press gesture to the calendar view and figured out which cell the user long pressed on.) 

Ordinarily I could use `UICollectionView.indexPathForItem(at point: CGPoint)` but in this case the UICollectionView instance isn't exposed. It'd be great to either expose the underlying UICollectionView, or to provide a convenience method that allows me to pass in a point and get back an index path.

**Comment by patchthecode** [comment]
like this?
```
calendarView.cellStatus(at: CGPoint(x: someXValue, y: someYValue
```

**Comment by tschmitz** [comment]
Yep, exactly!

**Comment by patchthecode** [comment]
I am deliberately trying to hide that under-working from the developer. If a feature is needed that isnt already provided, I will try to make it easier to access.

**Comment by patchthecode** [comment]
btw, you can find **all** user functions from the file `UserInteractionFunctions.swift`
check it out. I'm sure it has functions you might not have already seen.

**Comment by tschmitz** [comment]
Ahh, I see it in there now - thanks!
