### ISSUE TITLE
didScrollToDateSegmentWith() gets called twice on every swipe to next/previous month

### ISSUE THREAD

**Issue by skipadu** [patchthecode/JTAppleCalendar#189]
1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.1
* Yes, I have the latest version 6.0.1
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
* It may have been discussed in the issue #102, but not sure if it is the same.
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
* I looked, but didn't find help from there

---

I currently have UIView which have the label for the month, like in the example code.
But when swiping the month back or forth, **didScrollToDateSegmentWith** will be called twice on every time. This is no affecting my functionality, but I thought it should be called just once.
So, is it intended to call it twice?

Thanks for this great component, really offers versatility to make it look just like I want.

**Comment by patchthecode** [comment]
@skipadu youre right. Thanks. looking into this.

**Comment by patchthecode** [comment]
I have now fixed this.Thanks. 
It will be included in next release.
