### ISSUE TITLE
Problem with scrollToDate

### ISSUE THREAD

**Issue by Norton73** [patchthecode/JTAppleCalendar#190]
I have set up the calendar and everything is working fine. With the following code:

    override func viewDidLoad() {
        super.viewDidLoad()
        self.calendarView.dataSource = self
        self.calendarView.delegate = self
        self.calendarView.registerCellViewXib(fileName: "CellView")
        self.viewDidLayoutSubviews()
        
        let currentDate = self.calendarView.currentCalendarDateSegment()
        self.setupViewsOfCalendar(startDate: currentDate.dateRange.start as NSDate, endDate: currentDate.dateRange.end as NSDate)
        
        weekDays.textColor = UIColor(red: 0.658, green: 0.741, blue: 0.749, alpha: 1.0)
    }

I get this screen:

![screenshot 1](https://cloud.githubusercontent.com/assets/14325728/20034419/a9e131b4-a411-11e6-860d-55f4208bde27.png)

I have the TODAY button using the scrollToDate function that works fine.

    @IBAction func todayButton(_ sender: AnyObject) {
        let date = NSDate()
        calendarView.scrollToDate(date as Date)
    }

The calendar range needs to go back several months so the user can see their history but I want to open the calendar on the current date. When I add scrollToDate in ViewDidLoad.

    override func viewDidLoad() {
        super.viewDidLoad()
        self.calendarView.dataSource = self
        self.calendarView.delegate = self
        self.calendarView.registerCellViewXib(fileName: "CellView")
        self.viewDidLayoutSubviews()
        
        let date = NSDate()
        calendarView.scrollToDate(date as Date, triggerScrollToDateDelegate: false, animateScroll: false)
        
        let currentDate = self.calendarView.currentCalendarDateSegment()
        self.setupViewsOfCalendar(startDate: currentDate.dateRange.start as NSDate, endDate: currentDate.dateRange.end as NSDate)
        
        weekDays.textColor = UIColor(red: 0.658, green: 0.741, blue: 0.749, alpha: 1.0)
    }

I get this:

![screenshot 2](https://cloud.githubusercontent.com/assets/14325728/20034482/5ef6c9c8-a413-11e6-8883-522add9e228c.png)

I can't figure out how to prevent it from messing up the cells. Any help would be greatly appreciated.

**Comment by patchthecode** [comment]
ok. looking into it

**Comment by patchthecode** [comment]
What version of the calendar are you using ?

**Comment by Norton73** [comment]
I am using 5.0.1

I have been going through trying to figure out why I have self.viewDidLayoutSubviews() in there but I'm not sure. I have taken it out and it hasn't effected the app at all.

**Comment by Norton73** [comment]
Can you think why having the code in the TODAY button wouldn't cause a problem but having it in ViewDidLoad would?

**Comment by patchthecode** [comment]
@Norton73 yes. It is a race condition bug that I have fixed. This bug has been fix in later versions. The bug exists in version 5.0.1 and below.

Basically whats happening is that the calendar is being scrolled to before it calculated the size of the cells. This forces it to get the default size (which is huge). It does calculate the correct size after loading, but because the bad sizes have been cached, it thinks that it already has the correct sizes and does not re-calculate.

Try using the workaround code:
```
delayRunOnMainThread(0.1) {
            calendarView.scrollToDate(date as Date, triggerScrollToDateDelegate: false, animateScroll: false)
        }

func delayRunOnMainThread(_ delay: Double, closure: @escaping () -> ()) {
    DispatchQueue.main.asyncAfter(
        deadline: DispatchTime.now() +
            Double(Int64(delay * Double(NSEC_PER_SEC))) /
            Double(NSEC_PER_SEC), execute: closure)
}
```

**Comment by Norton73** [comment]
Great. Thanks very much for your reply.

I will give the workaround a shot.

**Comment by Norton73** [comment]
That code worked perfectly with one small change.

self.self.calendarView.scrollToDate(date as Date, triggerScrollToDateDelegate: false, animateScroll: false)

I am new to swift but I haven't seen the double "self" before. Don't know if it is a glitch in my code that required it but it works with the line like that.

Thanks again for your help.

**Comment by Norton73** [comment]
Sorry. Clicked the wrong button. Not sure if it is my place to close the thread.

**Comment by patchthecode** [comment]
Nah its cool. you can close it.
And double self? ok... something weird is going on here :/
I have never seen this  before either
