### ISSUE TITLE
Accessing custom cell

### ISSUE THREAD

**Issue by doodahdayz** [patchthecode/JTAppleCalendar#191]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

IF YOU ARE USING THE OFFICIAL RELEASE VERSION, FOLLOW THE FOLLOWING 4 INSTRUCTIONS:
________________________________________

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.1
**Yes**
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
**Not that I can find... the changes for Swift 3 have left the state of examples confusing**
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

I am stumped...  I have created the calendars and all is fine... I am downloading a ICS file that I want to parse and then set an indicator on each date cell if I have info regarding that date.  I thought I could just call calendarView.reloadData() and when it reloads the cells I could then set the indicator on the custom cell.   When I call reloadData() I am getting an exception in configureCalendar ....  I was surprised that reloadData() caused configureCalendar() to be called....

**Comment by doodahdayz** [comment]
I have the following delegate function:

    public func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let firstDate = formatter.date(from: "2016 11 01")
        let secondDate = formatter.date(from: "2017 12 31")

        let configParms = ConfigurationParameters(startDate:firstDate!,
                                                  endDate: secondDate!,
                                                  numberOfRows: 6,
                                                  calendar: Calendar.current,
                                                  generateInDates: .forAllMonths,
                                                  generateOutDates: .tillEndOfGrid,
                                                  firstDayOfWeek: .sunday);
        return configParms
    }
The exception I get is:
**fatal error: unexpectedly found nil while unwrapping an Optional value**
This is showing up on the first parameter.  

Thanks for your quick response!  I am very impressed with your library...  I think once the fallout from Swift 3 dies down and if you can get examples that are more in tune with the latest version that you will have many people using your code.

**Comment by patchthecode** [comment]
I think my examples were in tune with my code. It is fully written swift3 😄 
But if you find places where I missed in my examples then show me :] and i'll fix it.

By the way, you are getting error on which variable? is it the `firstDate` variable ?
I'm at the computer right now, so join me here -> https://gitter.im/patchthecode/JTAppleCalendar because i dislike slow chatting xD
