### ISSUE TITLE
Works with swift 3?

### ISSUE THREAD

**Issue by Naim08** [patchthecode/JTAppleCalendar#192]
Hi,

Is there a version for swift 3?

Thank You
Naim

**Comment by patchthecode** [comment]
This calendar is for swift 3.

**Comment by Naim08** [comment]
Hi, 

Thanks for your quick reply dude. So when I install JTAppleCalender using cocoapods, and then open xcworkspaces, it prompts me to convert it to swift 3? Do I just avoid that all together?

Thank You

**Comment by patchthecode** [comment]
This should not be happening.
Join me here -> https://gitter.im/patchthecode/JTAppleCalendar
