### ISSUE TITLE
Two Months side by side

### ISSUE THREAD

**Issue by roarapps** [patchthecode/JTAppleCalendar#193]
Is it possible to create a calendar with 14 columns? e.g. two months side by side?

**Comment by patchthecode** [comment]
@roarapps yes

**Comment by patchthecode** [comment]
Have you looked at the [Common questions](https://patchthecode.github.io/CommonQuestions/) section in the documentation?
If this fixes your issue then you can close this one :]

**Comment by roarapps** [comment]
Yes thanks, was going through the documentation trying to figure it out 👍

**Comment by patchthecode** [comment]
@roarapps nice :] 
I think the first one should solve the problem

**Comment by patchthecode** [comment]
Also, if you like the library. Dont forget to leave a star rating! It will be much appreciated.
If you have any further questions, you can open a new issue request.
