### ISSUE TITLE
Unknown class _TtC12CalendarTest19JTAppleCalendarView in Interface Builder file.

### ISSUE THREAD

**Issue by nikolalukovic** [patchthecode/JTAppleCalendar#195]
Hi,

I was trying to make a demo with your calendar app; i was following your instructions on https://patchthecode.github.io/MainTutorial/ but i get this weird error where it says that JTAppleCalendarView is not in Interface Builder file. I've been using Carthage to get your library and i'm using the latest version of both. Here's the full project:

[CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/586132/CalendarTest.zip)

**Comment by patchthecode** [comment]
I looked at your `UIView` on the story board. 
You have a wrong module listed for the view.

It should be this instead:
<img width="277" alt="screen shot 2016-11-11 at 8 55 12 am" src="https://cloud.githubusercontent.com/assets/2439146/20223070/9eead150-a7ec-11e6-87fc-d9212ba7f52a.png">

**Comment by nikolalukovic** [comment]
Oh geez, i've been trying to get this to work whole day. I feel so stupid :( 
Thank you so much for a quick reply!

**Comment by patchthecode** [comment]
Haha, Its ok man. We all make simple mistakes. Its cool. Have a good one. 👍

**Comment by vijay2pvk** [comment]
Hi,
I have 2 issue when using your framework

1) collectionview not scrolling horizontally
2) JTAppleCalendarView is not listing while setting the custom class

Can you please let me know what mistake i am doing

[SampleCalendarApp.zip](https://github.com/patchthecode/JTAppleCalendar/files/2856827/SampleCalendarApp.zip)
