### ISSUE TITLE
Need to recognise single tapping and double tapping events of an user whenever he taps on a particular day label.

### ISSUE THREAD

**Issue by Krishnarjun-Banoth** [patchthecode/JTAppleCalendar#198]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

IF YOU ARE USING THE OFFICIAL RELEASE VERSION, FOLLOW THE FOLLOWING 4 INSTRUCTIONS:
________________________________________

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.1
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Upgrade complete. 

You can test it by putting the master branch in your `Podfile` like this:

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```

Then do a pod install.
To try out the new feature, follow the tutorial here:
https://patchthecode.github.io/AddingGestures/

Let me know if it works for you

**Comment by Krishnarjun-Banoth** [comment]
Thank u for your assistance.

**Comment by Krishnarjun-Banoth** [comment]
hi sir, its working absolutely fine to recognise single and double tapping events, but when did that current selected date is getting 1 day less than the actual selected date, that is if i choose 24-11-2016 date label, then i am getting 23-11-2016 as date value in didSelectDate method, same thing happening with double tapping also.

**Comment by patchthecode** [comment]
can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar
