### ISSUE TITLE
Feature to get events based on single tapping and double tapping on a date label

### ISSUE THREAD

**Issue by Krishnarjun-Banoth** [patchthecode/JTAppleCalendar#199]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

IF YOU ARE USING THE OFFICIAL RELEASE VERSION, FOLLOW THE FOLLOWING 4 INSTRUCTIONS:
________________________________________

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.1
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
I see that you have re-opened this.
Does the feature not work?

**Comment by Krishnarjun-Banoth** [comment]
yeah actually i did not seen it on issues section, so i thought that something went wrong thats way i re-opened it.

**Comment by patchthecode** [comment]
I had already completed your feature request and i closed your issue.
You can find the close issue and the instructions on how to use you new feature here -> https://github.com/patchthecode/JTAppleCalendar/issues/198

**Comment by patchthecode** [comment]
You can find closed issues by clocking on this
<img width="596" alt="screen shot 2016-11-15 at 9 24 51 am" src="https://cloud.githubusercontent.com/assets/2439146/20316149/9191a6e2-ab15-11e6-8f45-a861095e44bc.png">
