### ISSUE TITLE
Start day of week

### ISSUE THREAD

**Issue by djxmax** [patchthecode/JTAppleCalendar#20]
Hi, first, thanks for you library. It saves me lot of hours.

For my app, I try to put monday as the first day of week. I use : 
`self.calendarView.firstDayOfWeek = DaysOfWeek.Monday`

But nothing append. Sunday stay the first day of week, even after a `reloadData()`
But it work with the demo app...
I use the last version of calendar (2.1.2)

But maybe there is a thing that I misunderstand ?

Thanks !

**Comment by patchthecode** [comment]
Using 
`self.calendarView.firstDayOfWeek = .Monday` should work.

Can you tell me this:

1. is it Vertical or horizontal scrolling?
2. Is paging enabled?
3. Is number of rows per week = 6? or something else

You need to give me enough information so that i can re-create your scenario

**Comment by djxmax** [comment]
I finally found a solution: 
I add `calendarView.numberOfRowsPerMonth = 6` and now it works.
So maybe there is a problem with the default value.

Thanks for your help ;)

**Comment by patchthecode** [comment]
Thank you. I will look into this.
The default date should work out of the box. Testing this now.

**Comment by patchthecode** [comment]
Never mind. I have recreated the issue. Thanks for letting me know of this. Will fix the default value.

**Comment by patchthecode** [comment]
When you change the first day of week, you are supposed to do a `calendarView.reloadData()`
But this was failing because I left out one line of code that marked the calendarView as `layoutNeedsUpdating = true`

Its a one line code fix.  Will push this fix to the next version coming this weekend. In the mean time, continue using your method.

**Comment by djxmax** [comment]
OK, thanks for your help !
