### ISSUE TITLE
Have ability to have calendar's with endOfGrid outDate, without other month's dates in the same section

### ISSUE THREAD

**Issue by roarapps** [patchthecode/JTAppleCalendar#200]
Hello,

Something strange is happening, in your example code, if you configure the calendar with the following parameters (where Date == November) - When you scroll to February 2017, the calendar seems to become out of sync because there should be an empty 5th row. This however is shown as populated. 

This only happens if Headers delegate methods are off. If i have a 0px height header, then 4 rows are correctly generated.

        let lastYear = Calendar.current.date(byAdding: .year, value: -1, to: Date())
        let nextYear = Calendar.current.date(byAdding: .year, value: 1, to: Date())
        
        let startDate = lastYear
        let endDate = nextYear
        
        let parameters = ConfigurationParameters(startDate: startDate!,
                                                 endDate: endDate!,
                                                 numberOfRows: 5,
                                                 calendar: testCalendar,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .tillEndOfRow,
                                                 firstDayOfWeek: firstDayOfWeek)
        return parameters

**Comment by patchthecode** [comment]
ok checking it out now.

**Comment by patchthecode** [comment]
@roarapps was this the behavior before? Or are you now noticing this

**Comment by roarapps** [comment]
I just noticed it now (only started implementing recently). It took me a while to figure it out as I wanted my month to always start at '1' but when i had certain configuration options set, the outdates weren't generated as outdates, I can't remember exactly what i had set so i tried to replicate this issue on your example code.

It seems to be a combination of things but when the header is on, there is no issue

**Comment by patchthecode** [comment]
@roarapps join me here --> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
@roarapps ok after the discussion, I have thought of a better solution.
I will implement it tonight.
and it wont feel hacky 😉

**Comment by patchthecode** [comment]
Setting this as an enhancement.

**Comment by patchthecode** [comment]
The feature is complete.
The change from your end that you have to do in order to make is happen is... nothing 👍 
It should not just work as expected. 

I will be releasing version 6.0.3 to in a day or two.
in the mean time you can test the master branch.

**Comment by roarapps** [comment]
Amazing! THanks, i'll test this out shortly

**Comment by roarapps** [comment]
Looking good :) 👍

**Comment by patchthecode** [comment]
cool.
