### ISSUE TITLE
How to select date range with two touches?

### ISSUE THREAD

**Issue by talalt** [patchthecode/JTAppleCalendar#203]
I need to select date range with two touches - first will be first date, and second will be last. When I try call selectRange() function after second touch it hangs, because he try to select all date cells in range, and make an infinity cycle. Please, give me some hint. Thanks!

**Comment by patchthecode** [comment]
ok. can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
without you providing more information, I will not know what you have done with your code

**Comment by talalt** [comment]
ok, i"ll join now

**Comment by patchthecode** [comment]
User selected date inside the did select delegate (without disabling delegate triggers). Therefore this causes an infinite loop. This is expected. Closing this issue now.
