### ISSUE TITLE
Hi, would like to know can this library support Xcode 7.3 and Swift 2.0 ?

### ISSUE THREAD

**Issue by Kishou** [patchthecode/JTAppleCalendar#204]
I did try to clone and build, but found a lot of errors, seems like incompatible code version.

**Comment by Kishou** [comment]
I did try to clone and build, but found a lot of errors, seems like incompatible code version.

**Comment by patchthecode** [comment]
Version 5.0.1 was the final version to support Swift 2.
You would need to put this version in your pod file.

One thing though, why swift 2? :/ 
5.0.1 version is good, but there are many changes and bug fixes I made in version 6.0 and upwards/

**Comment by Kishou** [comment]
I see thanks, well we are still encouraged to use the older version swift here, since the app that we build is almost completed. So we need to continue finishing them using the older swift. 

Thanks for the response.

**Comment by patchthecode** [comment]
cool
