### ISSUE TITLE
cell issue

### ISSUE THREAD

**Issue by DKalachniuk** [patchthecode/JTAppleCalendar#205]
Hi, i'm using the latest library, Thank you! 
I set up range selection and have one small issue. In the screenshot you can see line between cells

Do you have an idea where it comes from? 
cellInset is CGPoint(x: 0, y: 0)
and my selectedView is exactly from tutorial

Thank you

![simulator screen shot 23 nov 2016 14 22 02](https://cloud.githubusercontent.com/assets/2156751/20563292/3d0e2a0e-b188-11e6-9f0d-89cf4647362b.png)

**Comment by patchthecode** [comment]
Yes, thats the only bug in this library i do not know how to fix.
I need help on it. I believe it has something to do with iOS and fractional values.

Have you seen the issue that was created for this?
CUrrently, the work around is this -> 
<img width="975" alt="screen shot 2016-11-23 at 8 18 02 am" src="https://cloud.githubusercontent.com/assets/2439146/20569648/a9e12c18-b155-11e6-9952-ba3342bca77e.png">

So set the cell inset to some very small fractional value until the line disappears.
try maybe (-0.5, -0.6)  ?

**Comment by DKalachniuk** [comment]
@patchthecode nope(
but my friend @alickbass proposed to do the width of the calendar should be divisible by 7 without remainder

![simulator screen shot 23 nov 2016 17 33 45](https://cloud.githubusercontent.com/assets/2156751/20570202/ff02c844-b1a2-11e6-8877-a7f46c4ca3ca.png)


thank you for quick response!

**Comment by patchthecode** [comment]
Awsome. Glad the work around works for you.
I will look into that solution you mentioned.
Btw, If you like the library feel free to leave a star ★ rating on Github. It will be much appreciated.
Have a good one.

If your issue is resolved, you can close now 👍

**Comment by zhanswift** [comment]
@DKalachniuk  Hi. Can you show you code. I need to do like in you example. I need see cell size settings and select rows. Thank you.
