### ISSUE TITLE
set start date after calendar load

### ISSUE THREAD

**Issue by yumsmools** [patchthecode/JTAppleCalendar#206]
Hi there

Thanks for a great control

I'm setting startdate and enddate 1 year either side of today. and school to today when the calendar appears, but the scroll performance is not too great.  So I decided to make the start date today and set the proper start date after the calendar appears.  Is there an easy way to do this?

Thanks

Imran

**Comment by patchthecode** [comment]
Hey. I have set start and end date to be 100 years.
And performance is great on an old iPhone 4s.

Can you tell me what you are doing in your 
```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {

}
```

?

**Comment by yumsmools** [comment]
yeah  nothing too much

`    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        setGregorianMonth() // display month
        setHijriMonth() // display hijri month

        let myCell = cell as! CalendarCell
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        myCell.gregorianDay.text =  cellState.text
        myCell.setupHijriDay(date: date)
        
        // Setup text color
        myCell.configureTextColor(cellState: cellState)  // simply set colors for each day displayed
    }
`

**Comment by patchthecode** [comment]
Ok I see the first problem.

If you have a 6-row calendar, then you have 42 cells.
This means that the code you have there will be called for every of the 42 cells that is on the screen.

You have instanced a `DateFormatter` in there. 

```swift
let formatter = DateFormatter()
```

`DateFormatter()` instances [is already known to be a performance  downer](http://stackoverflow.com/questions/8832768/why-is-allocating-or-initializing-nsdateformatter-considered-expensive). And you are instancing it 42 times, **plus** every time you do a scroll you are also instancing it. Your formatter should not be initialized in there. Can you move it out of that function? Your performance will be increased by more than 90% guaranteed.

Also, can you tell me what is in your `configureTextColor(cellState)` function? That is another place for potential lag issues.

**Comment by patchthecode** [comment]
@yumsmools

**Comment by yumsmools** [comment]
Hi there.

Ok,  Fixed.  I moved the formatter out and I also set it to not animate the scroll and it worked like a charm.

Thanks

Imran

**Comment by patchthecode** [comment]
Awesome. Glad I could help.

**Comment by patchthecode** [comment]
@yumsmools one last thing. You could have left the scroll animate. If the scrolling is still not smooth, then there is something wrong in the code somewhere again.
But if you removed the scroll animation just because of preference, then no worries. The design is up to you.

**Comment by marktrobinson** [comment]
> cache your colors

These colours are cached already...

    // Some convenience methods to create colors.  These colors will be as calibrated as possible.
    // These colors are cached.
    
    open class var black: UIColor { get } // 0.0 white
