### ISSUE TITLE
Suggestions on how to split calendar when a day is tapped

### ISSUE THREAD

**Issue by alphire** [patchthecode/JTAppleCalendar#207]
Hi guys,

I need some suggestions on how to make the calendar split at a tapped location similar to how the real Apple calendar functions. The weeks below the tapped day move down out of sight while the selected week moves to the top of the calendar just under the header revealing a new view in the middle. I have one idea that consists of creating two calendars and animating them in a way where they seamlessly transition so it feels like one, but this seems quite complicated and un-elegant. I'm hoping there is an simpler way. 

If anyone has any suggestions, please post them. Thanks.

**Comment by patchthecode** [comment]
Ok. Thinking about this now

**Comment by patchthecode** [comment]
OK, I was wondering, do you already have the animation code to split a `UIView` at a tapped location?

**Comment by alphire** [comment]
No, been pretty busy so I haven't had a chance to play with it. What are you thinking?

**Comment by patchthecode** [comment]
Well the thing is, I believe the animation code is done without it having to do anything with the calendar from what I have seen. So i was asking you, how would you do you splitting animation on just a regular UIView?

**Comment by alphire** [comment]
Ok so this is what I found in terms of splitting a view: [UIView Split Transition](http://stackoverflow.com/questions/30462159/uiview-split-transition)

It basically takes a screenshot of the view and then cuts it half before sending each part in opposite directions. I think I could probably make this work, but once again its not very elegant and would require two calendars.

The other option I came across was doing something like this: [Expandable Table View Cells](https://blog.pivotal.io/labs/labs/expandable-uitableviewcells)

I've tried to familiarize myself with your calendar's code, but its a little overwhelming for me. Is this sort of thing possible to implement the way you've structured the calendar?

**Comment by patchthecode** [comment]
If you let me know which part if the calendar you need. Or what objects you need, then i would be able to help you. I do not know much about animation, so you might have to tell me what you need. The calendar is a simple `UICollectionView` in grid style.

Im available here in about 2 hrs or so -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Closing as animation is out of scope of this calendar project.
Animation can be done on the UIView.

**Comment by patchthecode** [comment]
@alphire I have found a way to do your splitting animation. 
If you are still interested, I will show you.

**Comment by alphire** [comment]
Yeah definitely still interested. Do you have some example code or just a general idea?

**Comment by patchthecode** [comment]
I have actual code.
Download the sample project attached to this project.

then just change the code in the following function to look like this:

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
        handleCellSelection(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        calendar.fold(withTransparency: true, completionHandler: { 
            self.calendarView.isHidden = true
        }, inDirection: .closed)
    }
```

**Comment by alphire** [comment]
Sorry for the late reply. I tested it out and its pretty cool. How can I implement it in my own project?

**Comment by patchthecode** [comment]
@alphire i just did that as an example :/

Like I was telling you before, the animation is totally separate from the Calendar.
That animation code was one I just randomly found online.
If you want to do animation, you need to have the animation code already done. Once you have the animation code, then you can apply it to any view (including the CalendarView). 

But just know that the animation is not part of the calendar.
If you want to implement the animation into the calendar, then just take the code that I have done and add it to your code.

**Comment by alphire** [comment]
Ok thanks man, I appreciate your help
