### ISSUE TITLE
Delegate and Datasource Setup Issue

### ISSUE THREAD

**Issue by syjk129** [patchthecode/JTAppleCalendar#208]
I'm currently on Xcode 8.1 with Swift 3 and I'm reimplementing the Calendar into a new project, but I'm getting an error when I call
`self.calendarView.dataSource = self`
`self.calendarView.delegate = self`

I get the error 
> Cannot assign value of type 'CalendarViewController' to type 'JTAppleCalendarViewDataSource?'

and 

> Cannot assign value of type 'CalendarViewController' to type 'JTAppleCalendarViewDelegate?'

Also, when I call
` func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters { `
I get the error
> Use of undeclared type 'ConfigurationParameters'

I followed the steps exactly and also used the Swift 3 branch in the podfile. I am not very experienced with Swift so any help would be great.

**Comment by patchthecode** [comment]
Ok, so in order not to confuse anyone else, i deleted the swift3 branch.
The latest version of `JTAppleCalendar` is already in swift3.

Your pod version should say `6.0`

**Comment by syjk129** [comment]
Thanks for the quick response. That removed some errors but the 

> Cannot assign value of type 'CalendarViewController' to type 'JTAppleCalendarViewDataSource'

still persists. Any ideas?

**Comment by patchthecode** [comment]
Chat here is too slow.. join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Incorrect branch `swift3` has now been deleted.
User also had issue with pod not being installed on system.
Pod worked when he created a new project however.
User will move every thing over to new project clone.
