### ISSUE TITLE
can I get JTAppleDayCellView from JTAppleDayCell? 

### ISSUE THREAD

**Issue by vuevrn** [patchthecode/JTAppleCalendar#209]
Hello

I have made a calendar like this, with dots are selected dates, blue color cell is for current date.
![simulator screen shot nov 24 2016 3 19 47 pm](https://cloud.githubusercontent.com/assets/10462847/20593748/8b185810-b259-11e6-855d-031b3ac2c930.png)

Now my question is, I need to choose from the selected dates, and show the same date selected on the calendar as well, with multiple selection allowed. as of now I have applied a gesture like this ->https://patchthecode.github.io/AddingGestures/

the problem is I ain't getting the cellView object from there. How can I get cellView / JTAppleDayCellView from cellState. 

Right now I am doing this 

let cell = cellState.cell() inside gesture event

but the cell is always returning nil, if I ain't into the correct direction please lead me to one.

awesome library.

Thanks.

**Comment by patchthecode** [comment]
OK two things are happening here.
1. First, What are you trying to do originally?

I do not understand what you mean by this `I need to choose from the selected dates, and show the same date selected on the calendar as well`

**Comment by vuevrn** [comment]
No.

I already have the selected dates. They are shown with dots beneath the dayLabel. Now the task is to select any of them.

You may understand from below

Its like I will select some date, the days when I am available from my device. 
Now you will look into my profile from your device where calendar will already show the dates I had selected. 
And from these dates only, you have to select any of the date when "we will meet".

Hope you understand. If you do so, kindly lead me into this.

Thank you.

**Comment by patchthecode** [comment]
@vuevrn can you join me here? https://gitter.im/patchthecode/JTAppleCalendar
If youre not there in 10 mins. I'll be asleep haha.
I'll have to look into it in the morning.
