### ISSUE TITLE
Add Objective C implementation

### ISSUE THREAD

**Issue by voodoo-mobile** [patchthecode/JTAppleCalendar#21]
Please, pretty please.
I know there's a way to use swift code inside objective C project, but it usually gets pretty ugly.

**Comment by patchthecode** [comment]
Haha. I thought about it. But man, I thought that Swift was the way forward. I don't think I will be doing a swift implementation. Maybe if someone does it for me and does a pull request. But as for now, I do not have the time since this is just my little blow-off-steam-from-work project :)

**Comment by voodoo-mobile** [comment]
Ok, I'll go ahead and try to find the least disgusting of Objective C implementations then :) Thanks anyway - for the reply and for apparently great work.

**Comment by patchthecode** [comment]
Thanks. Its all good.

**Comment by dreamBegin** [comment]
any updates?

**Comment by patchthecode** [comment]
on ObjectiveC?
Not really.

Managing this is already a lot for me.
Maybe someone can do a pull request.

**Comment by dreamBegin** [comment]
i wish somebody's me, but i myself got stuck. anyways appreciate your time Sir @patchthecode
