### ISSUE TITLE
Wrong selected NSDate

### ISSUE THREAD

**Issue by dbyst** [patchthecode/JTAppleCalendar#210]
Hi guys . Thanks for a great calendar.

I've faced with issue that delegate returns me wrong date in 
- (void)didSelectDatesWithStartDate:(NSDate *)startDate endDate:(NSDate *)endDate {
For example if 2016-11-17 selected,  it returns 2016-11-16 22:00:00 +0000.

What might be a problem ?

Thanks.

**Comment by patchthecode** [comment]
Ok, first thing. What version of the calendar are you using?

the `didSelectDate` function looks like this
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState)
```

**Comment by haketputek** [comment]
I also have the same problem, I'm using version 5.0.1 (just because our project can't migrate to swift 3.0 yet). Can you please check where I can edit the library so we can get the correct date? And thanks for the great calendar!

**Comment by patchthecode** [comment]
@haketputek join me here https://gitter.im/patchthecode/JTAppleCalendar

**Comment by dbyst** [comment]
I'm using 6.01. Application is on Objective C, so I created a bridge.

didSelectDate looks like this
 - (void)didSelectDatesWithStartDate:(NSDate *)startDate endDate:(NSDate *)endDate

**Comment by patchthecode** [comment]
sounds like youre in an eastern region.
@dbyst ok, use the following as the calendar that you provide to the `configureCalendar` function.

```swift
var calendar = Calendar.current
calendar.timeZone = TimeZone(secondsFromGMT: 0)
```

**Comment by patchthecode** [comment]
This bug was fixed

To test the master branch with your current project do this:
Go to your pod file, and change your JTAppleCalendar pod to this:
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```
Then do a:
```
pod install
```

**Comment by dbyst** [comment]
Sure, will take a look, and let you know. Thanks.

**Comment by patchthecode** [comment]
Alright then. Closing this issue as it is fixed.
If this is still a problem. We can re-open this.
