### ISSUE TITLE
Question - scrolling to wrong offset

### ISSUE THREAD

**Issue by roarapps** [patchthecode/JTAppleCalendar#211]
Hello,

Have an interesting one, i have my calendar set up to display 1 year either side of today. Everything is great, the calendar loads to today when i show it.

I have calendarView.allowsMultipleSelection = true, so user can select and deselect dates.

Issue -
1) User selects date
2) User scrolls back a month (either via button action, or swipe)
3) I invoke deselectAllDates
4) User scrolls forward a month
5) Instead of going forward a month, it goes forward a month but last year.

Strangely, i can only replicate this on the iPad and not iPhone. This only happens when i invoke deselectAllDates.

I will look further into this tomorrow, do you know why this may be happening? I will need to step through code tomorrow but if you had a good place for me to start it would be helpful.

**Comment by patchthecode** [comment]
So you're saying that when the user does step `#4`, it scrolls backward a whole year instead of just scrolling forward normally? join me here if you are able to do so -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by roarapps** [comment]
Yup, im just about to head off to bed. I'll try to take a look tomorrow and provide more information. However, i may only get time to look at it on Monday.

**Comment by patchthecode** [comment]
@roarapps alright then. I'll check with you later then.
I wish i could at least re-create it now though.

**Comment by roarapps** [comment]
Just some notes to remind me when i look at this again -

It scrolls backwards to the start of the calendar + 1 month. This seems like when i go Next, it thinks the current month is the start month.

It only happens if i have a date, or dates selected

It only happens one time, i have to reinit to replicate again.

**Comment by patchthecode** [comment]
one thing to try.
Put this in your podfile, and let me know if this issue is also happening on the master branch.

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```
Then do a:
```
pod install
```

**Comment by roarapps** [comment]
Okay, i'll try this in the afternoon (UK time) and report back

**Comment by roarapps** [comment]
Hello, I was already on the master branch. I will try to replicate the issue using your example app to make sure its not anything obvious i'm doing wrong and report back

**Comment by patchthecode** [comment]
@roarapps ok if youre on master. Do a `pod install` because I had made some changes

**Comment by roarapps** [comment]
Okay, haven't managed to replicate on your example project but on my project i've commented all excess code out so it's just the calendar view with basic code left. 

I've did a pod install as well, if this line is commented out, there is no issue
"// If this cell is already selected, then deselect it
deSelectTheDate(sectionIndexPath)"

Just trying to figure out exactly where its going wrong.

**Comment by patchthecode** [comment]
alright. let me know.
If its happening with yours, and not mine, then maybe its an issue i am not seeing.

Can you tell be what you are doing in your viewDidLoad?
Paste your code here. It might be possible you are scrolling to a date and something isnt getting called on time? But I need to see your code to find out.

**Comment by roarapps** [comment]
The only difference between our code now is that I have a splitview controller, but can't see how that would affect anything.     


override func viewDidLoad() {
        super.viewDidLoad()
        
        self.navigationItem.title = "Calendar"
        calendarView.dataSource = self
        calendarView.delegate = self
        calendarView.registerCellViewXib(file: "CalendarCellView") // Registering your cell is manditory
        
        calendarView.scrollingMode = .stopAtEachCalendarFrameWidth
        calendarView.cellInset = CGPoint(x: 0, y: 0)
        calendarView.scrollToDate(Date())
        
        calendarView.allowsMultipleSelection = true
        
        dateFormatter.dateStyle = .medium
    }

**Comment by patchthecode** [comment]
join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by roarapps** [comment]
Sorry missed that message and was working on something else today, i will jump on that channel tomorrow

**Comment by roarapps** [comment]
Can you supply an email where i can send a zip of an example project with this defect

**Comment by patchthecode** [comment]
patchthecode@gmail.com

**Comment by patchthecode** [comment]
@roarapps 

Hey man.
I updated the code. Can you do a `pod install` to get the latest master branch code?

**Comment by patchthecode** [comment]
By the way, sometimes `pod install` fails to get the latest code. This is something I have noticed (or maybe i am not good at cocopod specs?)

Anyway, in case you do a pod install and your code still is not fix, delete the `JTAppleCalendar` pod and then run a `pod install` again to make sure 100% that you the updated code fix.

**Comment by roarapps** [comment]
Same issue, i deleted the pod and cleaned project. Its definitely getting the latest. I emailed you the splitview controller project, were you able to replicate on there using iPad sim?

"Installing JTAppleCalendar (6.0.4)
Generating Pods project"

**Comment by patchthecode** [comment]
Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Yes i able to replicate the issue.
And resolved it with the fix.
Your code now works as expected. 
join me here -> https://gitter.im/patchthecode/JTAppleCalendar
