### ISSUE TITLE
Wrong initial position with NavigationBar

### ISSUE THREAD

**Issue by tatimagdalena** [patchthecode/JTAppleCalendar#213]
I've put a JTAppleCalendarView in my view controller with the desired constraints, did all the basic setups in my code, and got the result that I wanted. I've set different background colors to be easier to understand where the calendar actually is: (left is my simulator, right is my storyboard)

<img width="671" alt="withoutnavigation" src="https://cloud.githubusercontent.com/assets/8851349/20752986/4e7f143e-b6eb-11e6-9c0a-19a483a1996a.png">

The thing is: when I try to embed my view controller in a Navigation Controller, the calendar position gets messed up:

<img width="717" alt="withnavigation" src="https://cloud.githubusercontent.com/assets/8851349/20753054/9f1328fe-b6eb-11e6-9c9f-3fb4bc5747c3.png">

All I did was adding up the navigation bar (my view has the same constraints and my view controller is with the same code). Also tried changing my constraint to the top for a constraint relative to the middle of the screen, and still got the same result. Also tried building the view controller with the navigation bar from the beginning, and the same behaviour occurs.

It seems like it is setting an inset at the top of it's own view that is the size of the navigation bar. I can also scroll it vertically in this case, in this blank (gray) space, even if I set the horizontal calendar.

Is there a workaround for it?

**Comment by tatimagdalena** [comment]
Just found a related issue #135, and solved this! Would be nice to have this on the documentation, so others can quickly solve this.
Thanks anyway!

**Comment by patchthecode** [comment]
But I have this in the documentation here 😞 

https://patchthecode.github.io/CommonProblems/

**Comment by tatimagdalena** [comment]
Oops... my bad, didn't see it! Maybe you could make a note about that on the tutorial? I started from there and it was confusing doing all the steps as mentioned and not getting the right result.

**Comment by patchthecode** [comment]
Alright. I'll update this today!
