### ISSUE TITLE
Current set date resets on Screen orientation

### ISSUE THREAD

**Issue by Nidhee** [patchthecode/JTAppleCalendar#214]
Hello,

I am scrolling calendar to current date. But when orientation changes it rests calendar to some other date randomly. Guide me how to handle this

IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.0.2
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Which version of the calendar are you using?
I have recently push version 6.0.3 which should have fixed this issue.

**Comment by Nidhee** [comment]
I am using version 5.0.1, as this is latest for swift 2. How could I handle this issue using version I am using ?

**Comment by patchthecode** [comment]
Yea.. that issue was fixed in 6.0.3
hmm....

join me here if youre able to: https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Issue resolved.

On orientation change, user scrolled to the desired date.
[Note]: This issue is already fixed in later versions of JTAppleCalendar.
