### ISSUE TITLE
Is there a function that I could call to count how many days I have selected ? 

### ISSUE THREAD

**Issue by athemer** [patchthecode/JTAppleCalendar#215]
Hi Jay, thanks for making this awesome calendar.

I have trouble counting how many days I have selected :/ 
Is there a function that I could call to tackle this problem ?

I am new to programming and self-learning is really a pain in the ass.

thank you so much.

**Comment by patchthecode** [comment]
For future reference, all the functions that a user is able to do is easily located in the file: `UserInteractionFunctions.swift`.

have you tried this? :D 
```swift
let numberOfSelectedDays = calendarView.selectedDates.count 
```

**Comment by athemer** [comment]
Hi Jay, 
Thanks, this is exactly what I need.

**Comment by patchthecode** [comment]
@athemer glad it worked.
If this calendar is useful to you, then feel free to leave a star ★ rating on github. It wil be greatly appreciated. Thanks!
