### ISSUE TITLE
Semantic versioning? 6.0.3 broke scrollToPreviousSegment

### ISSUE THREAD

**Issue by MoridinBG** [patchthecode/JTAppleCalendar#217]
Why are breaking changes introduced in patch versions???
Obviously, there were some significant changes in the segmenting code, but this should not be introduced in such a way...

As a reminder, here it is how it is supposed to work:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

**Comment by patchthecode** [comment]
Yea i know about semantic versioning.
but honestly.. i forgot about that code change. ☹️ 
Hopefully its not too bad a fix.

**Comment by MoridinBG** [comment]
Hey, I am not mad!
Quite the opposite, you are doing an awesome job with this library!
I was just a bit irked when the project stopped building even though I only update patch or minor (:

**Comment by patchthecode** [comment]
Ok its cool. But you're right. I'll look more closely next time. Thanks man.

**Comment by bryantm1123** [comment]
Just to save folks some time:

`calendarView.scrollToSegment(SegmentDestination.previous)`

`calendarView.scrollToSegment(SegmentDestination.next`

**Comment by patchthecode** [comment]
updated @bryantm1123 's code.
