### ISSUE TITLE
Does the component support a day view?

### ISSUE THREAD

**Issue by squaredonut** [patchthecode/JTAppleCalendar#218]
For some reason I can't seem to see any existing issue or any doco that indicates it does? A day view as in it shows a listing of the times of the day from 12am - 12pm, in half an hour increments, similar to the one in the apple calendar app.

**Comment by patchthecode** [comment]
@squaredonut what do you mean by a dayView? Do you have a screen shot of what you are looking for?

**Comment by squaredonut** [comment]
Like this

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkcuvKwvLXZ04-mybSg_PHXxt-ogOUdyDHGL_NCe9t-O1QrNNCsRPp404_Ag

**Comment by patchthecode** [comment]
Oh. sorry.
yea, its not able to do this.
When building this library, I didnt think it would be good to put this feature in as I think I can be placed in a separate library.

I believe that it is a totally different library/control/view that can expand in its own way.
What do you think?

**Comment by squaredonut** [comment]
@patchthecode yeah definitely sounds like a good idea if it becomes hard to abstract the controls API accomodate, both layouts.

Admittingly I'm not that experienced at all with iOS development, so wouldn't know the exact approach with authoring something similar to this.

**Comment by patchthecode** [comment]
@squaredonut yes, Same thing I was saying. I think the 2 controls should be separate. The API would be different, and cramming them both together would seem odd.

I would consider creating a separate control, but this would be some time in the future. Sorry the library could not be of help to you man. But if ever you do start using it, leave a star rating if you like it :)

I'll get to work on that other control some time in the future.
