### ISSUE TITLE
Proper way to reload calendar and redraw date views?

### ISSUE THREAD

**Issue by alexclst** [patchthecode/JTAppleCalendar#22]
In the app I'm building with this right now I need to be able to reload the calendar view on a certain interval, the basics of that I understand (NSTimer plus the ```.reloadData()``` function for reloading the calendar data when needed). However, since I'm coloring today differently from every other day I can see that something is not quite right, because in a test app I set up to debug this (so that my much more complex codebase wouldn't complicate things while debugging this specific bug) I'm reloading data anytime I tap a date in the calendar, and in some seemingly randomly selected order of dates different dates get the today coloring, too, or actually even just, say, the new background color but not even the new text color. I've also played around with ```.reloadDates()``` and that only made things react stranger, where the first tap-to-reload things seem normal, then a different seemingly random order of dates getting today colors ensues for the second and beyond tap-to-reloads (though after first writing this I now see that this method just improperly colors a different date as today on the second tap, then things seem normal). I get the feeling I'm not explaining this clearly... I can share my test project with you if you'd like. Any idea what is going on with regard to why the calendar view's implementation of ```.reloadData()``` is making the calendar view draw dates in the weird way I'm trying to describe in plain language? Any help would be greatly appreciated.

**Comment by alexclst** [comment]
I think I may have figured this out on my own... The core of the issue seemed to be cell reuse, and not accounting for the not-today case in the date view drawing.

**Comment by patchthecode** [comment]
Your explanation was a little confusing haha. But no worries.
Share your project. I can take a look.

**Comment by patchthecode** [comment]
`ReloadData()` will reload all the dates on the calendarView
`ReloadDates()` will only reload the specific dates you provide

If you want a dateCell to change color whenever a user taps a specific date, then use the following delegate method: 
```swift
func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState)
```

So whenever the user taps the date-Cell you will know which date was tapped. And you will have the cell that they tapped as well. For there, just change the color to what ever you want

**Comment by cooderatgit** [comment]
Hi, I am not sure whether I am intruding here. Please advise if so. My question is related, where I want the label text color to change when user taps; the didSelectDate delegate would recognize the tap only after the finger is shifted. However, I want the color to change when user starts pressing on the cell, much like with a button. How will I be able to do that? Thanks
