### ISSUE TITLE
repeating dates when scrolling to previous/next week using week mode (1 row)

### ISSUE THREAD

**Issue by alfianlosari** [patchthecode/JTAppleCalendar#220]
Hi, thanks for creating this awesome library. It is really simple to setup, high performance, and really customizable.

I am trying to set calendar to display weekly view by creating configuration parameter like this.
```swift
let parameters = ConfigurationParameters(
    startDate: startDate, 
    endDate: endDate, 
    numberOfRows: 1, 
    calendar: Calendar.current, 
    generateInDates: .forAllMonths,
    generateOutDates: .tillEndOfRow, 
    firstDayOfWeek: .sunday)
```
![screen shot 2016-12-06 at 8 12 23 am](https://cloud.githubusercontent.com/assets/6789991/20909046/c4332284-bb8b-11e6-85c8-f3a986c72efc.png)

The issue occurs when i try to scroll to previous week to the end of the month or scroll to next week to the beginning of the month. The date of the week is being repeated so i have to scroll 2 times to advance or go back to the week i want to scroll to.

Do you have any suggestion on how to fix this behavior

Thanks

**Comment by patchthecode** [comment]
Yes, this behavior is expected.

The repeating dates you are seeing are inDates and outDates.
You are used to seeing them on a 6-row calendar here:
<img width="286" alt="image" src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png">

When you have single row set to **on**, then you will see these inDates and outDates.
I see that you have your **inDates** set to show for all months, and your **outDates** is set to show till the end of grid for single row. 

For single row, set your outDates to off and your problem should be resolved.

Spread the word about the calendar :)
Cheers man.

**Comment by patchthecode** [comment]
I will add a section to the tutorials so explain all these things to people

**Comment by alfianlosari** [comment]
Thanks for the explanation. I hope you will continue to maintain this great library!

**Comment by patchthecode** [comment]
Thanks man. If you know anyone that can help translate the documentation into other languages, let me know. If not, its cool. I'll keep maintaining it. Have a good one. 🍺
