### ISSUE TITLE
When setting start and end date difference very large, it takes lag to open view controller 

### ISSUE THREAD

**Issue by Nidhee** [patchthecode/JTAppleCalendar#221]
Hello, 

I have kept, start date 50 years back from current date and end date 50 years forth from current date at time of calendar configure. And inside onViewLoad(), i have scrolled to current date. 

My issue is, View controller having calendar is taking some time (approx 2-4 sec lag) for opening. If I change start and end time 2 years back and forth from current date. It opens View controller smoothly. 

It gives lag when tested on real device, on simulator it is working okay.

Please guide me what should I do.

**Comment by patchthecode** [comment]
What device are you using?
I will look into this now.

**Comment by Nidhee** [comment]
I am testing on iphone 5s (IOS version 9.3.2)

**Comment by angelbetancourt** [comment]
Same issue, I'm using iPhone 5 . Any answer ?

**Comment by patchthecode** [comment]
@angelbetancourt yes, the solution is for me to code an update.
The work around for now is to decrease your range.
I am actively working on the fix.

Just to confirm, how large is your date range?

**Comment by angelbetancourt** [comment]
@patchthecode  sorry I didn't answer. My range is 1960 - 2017. Any thought so far ?

**Comment by patchthecode** [comment]
I have updated to version 7.0
Your dates should load a whole lot faster.
Let me know if this is still a problem for you

**Comment by meanreaksmey** [comment]
When I selected range between 2017 to 2018 it load select very slow. Could you help me?

**Comment by patchthecode** [comment]
@meanreaksmey youre  selecting a whole year of dates?

**Comment by meanreaksmey** [comment]
@patchthecode  Yes I selecting a whole.

**Comment by patchthecode** [comment]
hmm.. someone has already opened an issue for this.
I have to make the code a bit different for this.
This is work in progress.

**Comment by meanreaksmey** [comment]
@patchthecode  yes thanks you. do you have any that work faster when i selecting across year?

**Comment by patchthecode** [comment]
@meanreaksmey currently i do not. I will have to investigate. But if any one wants to do a pull request they can also do this. (in case i am to slow on this update)

**Comment by meanreaksmey** [comment]
@patchthecode Thanks you I'm looking to hearing from you soon. :)
