### ISSUE TITLE
Highlight current date

### ISSUE THREAD

**Issue by jesse-cohen** [patchthecode/JTAppleCalendar#224]
Hey Jay,

Trying to highlight the current date using a UIView following the selected date example. Is this to do with cellState.date from within willDisplayCell or am I missing something?

Thanks

**Comment by patchthecode** [comment]
join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
I will now add the information discussed to the tutorial. This way, it will also help others.
Thanks.
