### ISSUE TITLE
enhancement - link to gist.github.com with search for JTAppleDayCellView

### ISSUE THREAD

**Issue by johndpope** [patchthecode/JTAppleCalendar#225]
The styles shown in the issue are amazing. 
When I download and compile it's like a dogs breakfast. 
Perhaps you could help people to choose a style by pre-defining a search to gist where people can upload their own styles. 

https://gist.github.com/search?utf8=%E2%9C%93&q=JTAppleDayCellView

**Comment by patchthecode** [comment]
so basically an area where people can find already setup cells, with their code etc?
That actually sounds like an awesome idea.

I'll think of something over the weekend. Thanks man.

**Comment by patchthecode** [comment]
btw, the sample app looks bad because I am better at library building than designing. :)

**Comment by patchthecode** [comment]
will track this in projects
