### ISSUE TITLE
Sending Date to Server to retrieve data.

### ISSUE THREAD

**Issue by HumayunKaleem** [patchthecode/JTAppleCalendar#226]
Hey,

I searched about this but couldn't get a sufficient response. I have a database in which events are stored in calendar. Now after logging in i would like to retrieve by sending the month and ID. How do i send the CalendarMonth to server? I have tried CurrentCell Selected method but doesn't seem to work. I am going to tap on the date and show the description in UITableView. Has anyone done similar to this and can guide?

**Comment by patchthecode** [comment]
I do not understand what you are asking.

Are you trying to accomplish this?
1. User taps on date
2. Date is sent to server

?

**Comment by HumayunKaleem** [comment]
Hey thanks for the prompt reply. At first when the calendar loads the current month data from the server is loaded and when it selects the date of the current month then it shows the information in the Table View. 
And
When the user taps on other months and select the other dates then that data should be loaded from the server.

P.S bear with me as I am new to this stuff :(

**Comment by patchthecode** [comment]
When a user taps on a date, the `didSelectDate` functions gets called.
You can get the date from there.

Can you tell me which part specifically you are stuck on?

**Comment by HumayunKaleem** [comment]
How to get only Month and Year? I will let you know where i am stuck.

**Comment by patchthecode** [comment]
from the date.
you have the *date*.
With this you can extract the day, month, year

**Comment by patchthecode** [comment]
closing issue.
If you are still having problems with this. Then reopen this question.
