### ISSUE TITLE
White line within calendar

### ISSUE THREAD

**Issue by oddpandadesign** [patchthecode/JTAppleCalendar#227]
First point - amazing project. 

I am trying to remove a white line that is appearing within the calendar view. I have highlighted this by making each cell black as below:

<img width="365" alt="screen shot 2016-12-13 at 09 35 48" src="https://cloud.githubusercontent.com/assets/6759173/21134982/ff674754-c117-11e6-8e51-df96d69b0b97.png">

I am doing the following to resize the cells:

```
        calendar.itemSize = 50
        calendar.cellInset = CGPoint(x:0, y:0)
```

Using autolayout then view is pinned to the side. How can I go about removing that white line. Is only an issue as I draw a line between selected view and that line appears!

The real life example

![simulator screen shot 13 dec 2016 09 45 18](https://cloud.githubusercontent.com/assets/6759173/21135192/e3ccbe1a-c118-11e6-857e-24791ad22c0d.png)

**Comment by patchthecode** [comment]
yes, this is the only bug i cant fix. It is an iOS issue with floating point numbers.
The work around is posted in the open issues here -> https://github.com/patchthecode/JTAppleCalendar/issues/26

simply set the inset to some small negative number.

```
calendarView.cellInset = CGPoint(-0.2, -0.2)
```

**Comment by patchthecode** [comment]
I also noticed that your selected view is not a perfect circle: 
<img width="305" alt="screen shot 2016-12-13 at 2 51 06 am" src="https://cloud.githubusercontent.com/assets/2439146/21137595/17a913d0-c0df-11e6-96d8-147124556538.png">

Please set the corner radius to be around 1/2 of the width of the UIView.

**Comment by patchthecode** [comment]
Also, if this project has been helpful to you, please consider giving a star rating and spread the word. Thanks :D

**Comment by oddpandadesign** [comment]
Much appreciated. Thanks and good spot!

**Comment by patchthecode** [comment]
Cool man and thanks for the support.
That calendar looks awesome by the way. Reminds me of one i saw on AirBnb.
