### ISSUE TITLE
Bad Exec Error...

### ISSUE THREAD

**Issue by cbwilliamsnh** [patchthecode/JTAppleCalendar#23]
I'm getting a EXC_BAD_ACCESS error when trying to set the delegate to my controller

I also don't see JTAppleCalendar as one of the choices on the Class Inspector. I see the classes in the attached screenshot.

Am I doing something wrong? Using latest Xcode.
<img width="335" alt="screenshot 2016-05-23 18 15 27" src="https://cloud.githubusercontent.com/assets/8007059/15486272/7bcbfe6c-2112-11e6-876d-3719b6c1d68b.png">

Here's a screen shot of the error:

<img width="1425" alt="screenshot 2016-05-23 18 23 16" src="https://cloud.githubusercontent.com/assets/8007059/15486412/731440da-2113-11e6-852d-13a312996660.png">

**Comment by cbwilliamsnh** [comment]
Oddly enough, when I implement my code as in the example (with the calendar delegates in an extension) it works.

Why would it not work with the view controller directly implementing the delegate classes for the calendar?

**Comment by patchthecode** [comment]
Ok, i am trying to understand your problem.

I just took the same project attached here on github.
I removed the extension and set everything up in the ViewController like so:

```swift
class ViewController: UIViewController, JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
...
}
```
Then i moved all the functions that was in the extension, into the `viewController` just like you did.
And when i run the app, it works.  So try and help me understand where your problem is:

1. What version of the framework are you using?
2. Are you installing it using cocoapods? or something else.

If you are using the latest version and you are using cocoapods to install the calendar. Then...

3. did you look at [the quick tutorial](https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial) on how to set it up?

You have correctly imported `JTAppleCalendar` in your viewController class.
But, on your interface builder file (as shown in the tutorial), your calendarView should be a subclass of `JTAppleCalendarView`

**Comment by cbwilliamsnh** [comment]
Here's what I did.

- installed using cocoapods
- followed the tutorial in the documentation
- had everything in my view controller class (did not use an extension)
- I thought I had all the class types properly set

Crashed as shown in screens.

Changed the source/delegate to be in an extension exactly as in the
tutorial. Everything worked.
On Mon, May 23, 2016 at 10:40 PM JTAppleCalendar <notifications@github.com>
wrote:

> Ok, i am trying to understand your problem.
>
> I just took the same project attached here on github.
> I removed the extension and set everything up in the ViewController like
> so:
>
> class ViewController: UIViewController, JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {...
> }
>
> Then i moved all the functions that was in the extension, into the
> viewController just like you did.
> And when i run the app, it works. So try and help me understand where your
> problem is:
>
>    1. What version of the framework are you using?
>    2. Are you installing it using cocoapods? or something else.
>
> If you are using the latest version and you are using cocoapods to install
> the calendar. Then...
>
>    1. did you look at the quick tutorial
>    <https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial>
>    on how to set it up?
>
> You have correctly imported JTAppleCalendar in your viewController class.
> But, on your interface builder file (as shown in the tutorial), your
> calendarView should be a subclass of JTAppleCalendarView
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/23#issuecomment-221151754>
>
-- 
Chuck

**Comment by patchthecode** [comment]
I just did what you said. And it works.
So here's what, can you upload a bugged copy of your project on github so that i can take a look?

**Comment by cbwilliamsnh** [comment]
I can do that tomorrow.

Chuck
On Mon, May 23, 2016 at 10:55 PM JTAppleCalendar <notifications@github.com>
wrote:

> I just did what you said. And it works.
> So here's what, can you upload a bugged copy of your project on github so
> that i can take a look?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/23#issuecomment-221153670>
>
-- 
Chuck

**Comment by patchthecode** [comment]
Alright. I will appreciate it. Thanks. 
Upload it once you are able to do so

**Comment by cbwilliamsnh** [comment]
Ok, now it works without the extension, so I can only conclude that I was
doing something else wrong.

Chuck

On Mon, May 23, 2016 at 11:01 PM, JTAppleCalendar <notifications@github.com>
wrote:

> Alright. I will appreciate it. Thanks.
> Upload it once you are able to do so
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/23#issuecomment-221154413>
>



-- 
Chuck

**Comment by patchthecode** [comment]
Ok thanks. Closing this issue.
Have a good one

**Comment by yillivs** [comment]
I got the same thread error at runtime. I followed the tutorial and did not get any errors until testing.

**Comment by patchthecode** [comment]
@yillivs can you upload a copy of your bugged project here?
