### ISSUE TITLE
How to implement previous & next month buttons

### ISSUE THREAD

**Issue by jonfabris** [patchthecode/JTAppleCalendar#230]
I searched through all the examples, tutorials, and sourcecode and cant for the life of me figure this out.

calendarView.scrollToDate(myDate)

Will scroll you to a particular date, but how do you determine what is the current month being shown in the Calendar? Examples refer to this function: currentCalendarDateSegment() but I can't find that function anywhere.

thanks

**Comment by patchthecode** [comment]
```
self.calendarView.scrollToSegment(.next)
self.calendarView.scrollToSegment(.previous)
```

**Comment by patchthecode** [comment]
and `currentCalendarDateSegment()` ? what version of the calendar are you using

**Comment by patchthecode** [comment]
And it is in the example application.
you can find the month you are on by using the function
```
let visibleDates = calendarView.visibleDates()
```

**Comment by jonfabris** [comment]
Thanks!

**Comment by patchthecode** [comment]
@jonfabris if this

**Comment by huffmann** [comment]
Hello @patchthecode  -  

I tried using .scrollToSegment function but I get an error message saying that said function is not member or JTAppleCalendarView

So I checked in the example, and this function is part of an extension in UserInteractionFunctions.swift which doesn't ship with the library.   

Is that how its supposed to be done? through an extension? 

Thanks for your help,  I'm really digging the library

**Comment by patchthecode** [comment]
@huffmann 
Ok i assume that you use cocoapods to install this library?
Every file is shipped with the library.
And yes it is done through an extension. That is how it supposed to be done.

If you cannot find the function, then you must be using an old version of the calendar.
Are you using the latest version? 6.0.5

**Comment by huffmann** [comment]
Hello @patchthecode 

Yeah I installed through cocoapods but it installed an older version.  Now on 6.0.5 its working! Thanks! 

BUT I am setting triggerScrollDelegate to true, and noticed it only triggers the first time I press the button but not on the subsequent touches. Definitely worth having a look at because this delegate is very useful for updating UI.

**Comment by patchthecode** [comment]
@huffmann yea.. thats actually a bug introduced in 6.0.5 accidentally.
fixing this now

**Comment by patchthecode** [comment]
@huffmann can you test it and tell me if it works?

Put this in your pod file 
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```

Then do a `pod install` on console, and let me know if the fix worked.

**Comment by huffmann** [comment]
@patchthecode   Yes it did!    Should I keep it like this on the podfile?  O wait for a new commit and change it to how it was?

**Comment by patchthecode** [comment]
@huffmann well, the code you have now will become a new official release in about 1 week.

if you leave your podfile like this, then you will be using master branch.
You will have the very latest (but not all the time fully tested code).
but I try to test it as much as possible before committing. If youre more comfortable waiting for the official release, then you can use the current master branch, but change it back to 6.1.0 when i release it.

**Comment by ARGAMX** [comment]
not working anymore
`Value of type 'JTAppleCalendarView' has no member 'scrollToSegment'`

**Comment by patchthecode** [comment]
checked out the migration guide?
https://patchthecode.com/jtapplecalendar-version-8-0-0-migration-guide/
