### ISSUE TITLE
Reduce number of columns?

### ISSUE THREAD

**Issue by f3rr13r** [patchthecode/JTAppleCalendar#231]
Hey there!

Have been playing around with this awesome repo today for an app that I am developing. Loving the feel and ease of use, neat scrolling capabilities and the limitless design flexibility that it offers, but would love to know what the best way to modify the column count down so that it displays only 5 cell's across (as each cell is intended to be a tappable UIImageView (with the date and day of week being specified as label on top). Understandably this will satisfy with the 6 row limit for most rows, but will come up short during months with 31 days as it will need that extra 7th row. The app will not require any day initials as all day and date information will be provided inside the cells themselves.

Don't imagine that this is by any means a common issue, and so would not be expecting any changes to be made on my behalf, but any information about changes that I would need to make to the existing code, where and what type of thing would be really awesome.

Thanks for your time.

Harry

**Comment by patchthecode** [comment]
I have not really looked into the changes needed for a 5 column calendar, so honestly, i would not even know where to begin to explain it to you.

But the concept does sound interesting. Can you tell me how your calendar would look if there is an extra day?

**Comment by f3rr13r** [comment]
Thanks for getting back to me! Yeah sure, here is a screenshot example for our current month (but treating the 31st as 'today'. As this calendar is supposed to appear in 'reverse', going down the page from current into the past, it is the 1st December that appears on it's own 7th line, next to empty placeholders. It would be a vertical scroller, allowing users to scroll BACK through months in time and up to current month. Obviously then when new month begins, this would then be the new 'current' month, and the previous month (December in our case) would then be viewable by scrolling down.

<img width="392" alt="screen shot 2016-12-15 at 10 22 33 am" src="https://cloud.githubusercontent.com/assets/22051953/21220374/77660d00-c2b0-11e6-92de-cc6982179833.png">

Sure what I am looking for is bordering on not being what this awesome repo was designed for, but really like it's feel so am going to try and work it in if in any way possible.

Thanks,

Harry

**Comment by patchthecode** [comment]
Ok from the image you have provided, it looks like you're still keeping saturday and sunday.
I thought when you said "5-row calendar", that you were going to remove the weekends. But if what you want is the exact same dates, then It might not be so difficult as i first thought. 

It will be do-able (i think), but not crazy difficult. 
One thing is certain though: I certainly wont be able to look into it right now as I am working on another update for this cal.

**Comment by patchthecode** [comment]
One thing though, since your layout is simple, this might actually be faster to do if you create your own UICollectionView.

**Comment by f3rr13r** [comment]
Okay! This is good news to my ears.

I completely understand if there is a delay in any looking through for solutions on your behalf as this definitely will not be what the majority of those implementing this calendar will be looking for in terms of functionality and styling, but yeah if at any point you are able to chuck any suggestions across then that would be much appreciated. I am playing around with the source code in my own project to find an answer, and will continue to do so in the mean time.

I was actually considering creating a specific collection view for this project to get this done, but having never dealt programmatically with calendars and calendar entries etc before, finding a way of solving the gap in my knowledge seemed like the best way to bridge the problem. Empty entry dates etc seemed to be the crux of my problem and how to overcome it, but i'm sure it's only a matter of time until it clicks in my head haha.

Thanks for all the assistance so far, and any that you can offer going forward.

Best,

Harry

**Comment by patchthecode** [comment]
closing this.
i'll track this here -> https://github.com/patchthecode/JTAppleCalendar/projects/2
