### ISSUE TITLE
select date bug when changing months

### ISSUE THREAD

**Issue by jonfabris** [patchthecode/JTAppleCalendar#233]
Weird things happen when you select a date, then switch months and select a new date, then go back to the old month.
Version 6.0.5

[Screen Recording.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/655095/Screen.Recording.mov.zip)

**Comment by Toddo24** [comment]
Hello Mr I was just wondering if anyone has a great way to get to the new
year with a new job interview for the delay in responding to your site and
I have to be a little bit more TIME TO GET A CHANCE for me and my family
HAS TO OFFER YOU A DECISION TO MOVE TO ANOTHER PARTY FOR THE NEXT COUPLE OF
YEARS AND I HAVE TO GO TO THE NEW YEAR TO GET INTERVIEWING FOR THEIR
VACANCIES in the world of thebest of the best way to get to


On Dec 15, 2016 10:53 AM, "jonfabris" <notifications@github.com> wrote:

Weird things happen when

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/patchthecode/JTAppleCalendar/issues/233>, or mute the
thread

**Comment by patchthecode** [comment]
@jonfabris looking into this. Good catch.

**Comment by patchthecode** [comment]
Do you have have multiple selection on?

**Comment by patchthecode** [comment]
Have you followed the tutorial on how to build the calendar on this site? -> https://patchthecode.github.io/

I do not think this is a bug with the calendar.
Can you show me your 
```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState)
```
function code please so that I can confirm?

**Comment by jonfabris** [comment]
[PickDatePopupVC.swift.zip](https://github.com/patchthecode/JTAppleCalendar/files/655565/PickDatePopupVC.swift.zip)

**Comment by jonfabris** [comment]
func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState)
    {
        let myCustomCell = cell as! CalendarCellView
        
        // Setup Cell text
        myCustomCell.dayLabel.text = cellState.text

        myCustomCell.selectedView.frame = CGRect(x:0,y:0,width:myCustomCell.frame.width,height:myCustomCell.frame.height+1)
        
        myCustomCell.selectedView.setGradientBackground(colorTop:UIColor(hexString: "5c5c5c")!.cgColor, colorBottom:UIColor(hexString: "cfcfcf")!.cgColor)
    }

**Comment by jonfabris** [comment]
Oops, my bad, I fixed it.
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState)
    {
        let myCustomCell = cell as! CalendarCellView
        myCustomCell.selectedView.isHidden = true
        myCustomCell.dayLabel.textColor = dateColor
        // Setup Cell text
        myCustomCell.dayLabel.text = cellState.text

        myCustomCell.selectedView.frame = CGRect(x:0,y:0,width:myCustomCell.frame.width,height:myCustomCell.frame.height+1)
        
        myCustomCell.selectedView.setGradientBackground(colorTop:UIColor(hexString: "5c5c5c")!.cgColor, colorBottom:UIColor(hexString: "cfcfcf")!.cgColor)
    }
    

Although when you select a date and switch months it deselect it, is there a way to keep it selected?

**Comment by patchthecode** [comment]
@jonfabris hey, i think you should follow the tutorial.
It will help you greatly.

https://patchthecode.github.io/

There are some things you are doing that will cause problems.
check out [tutorial1](https://patchthecode.github.io/MainTutorial) and [tutorial2](https://patchthecode.github.io/MainTutorial2)

If you need more help, just reply on this thread.
Also, if this library has saved you lots of coding, consider leaving a star rating :)
Cheers. 🍺

**Comment by jonfabris** [comment]
I went through the tutorial I swear.
I need the date to remain selected even when you switch months.

I think this might be my problem but I can't understand your instructions:
_My views are being randomly repeated across dateCells

To cure your random repeating views -> If you have ever done a UITableView before, then inside the cellForRowAtIndexPath function, you have to reset the cell before it is used right? You will have to remove that circle you have added, or that color you have added. Reset the old text you put earlier, change that image you created etc etc. Therefore you have to do the same thing in your willDisplayCell function._

My best guess was to do this at the top of the function func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState)

let cell = calendar.calendarView.dequeueReusableCell(withIdentifier: "CalendarCellView") as! CalendarCellView
        
But calendarView is inaccessible
