### ISSUE TITLE
Cell State Reuse

### ISSUE THREAD

**Issue by johnyboy6000** [patchthecode/JTAppleCalendar#234]
I have created A very simple sample project below but the cell state text inside "willDisplayCell" seems to return random numbers. I have checked the example projects and the code is the same so I'm lost as to what the issue may be?

```swift
import UIKit
import JTAppleCalendar

class HomeViewController: BaseViewController 

    @IBOutlet weak var calender: JTAppleCalendarView!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        calender.delegate = self
        calender.dataSource = self
        calender.registerCellViewXib(file: "CalenderCell")
    }

}
// MARK: - Calender Delegates
extension HomeViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let currentCalendar = Calendar.current
        let components = currentCalendar.dateComponents([.year, .month], from: Date())
        let startOfMonth = currentCalendar.date(from: components)!
        let yearFromStartOfMonth = currentCalendar.date(byAdding: .year, value: 1, to: startOfMonth)!
        let parameters = ConfigurationParameters(   startDate: startOfMonth,
                                                    endDate: yearFromStartOfMonth,
                                                    numberOfRows: 6,
                                                    calendar: currentCalendar,
                                                    generateInDates: .forAllMonths,
                                                    generateOutDates: .tillEndOfGrid,
                                                    firstDayOfWeek: .monday)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        let calCell = cell as! CalenderCell
        calCell.dateLabel.text = cellState.text

        if cellState.dateBelongsTo != .thisMonth {
            calCell.isHidden = true
        } else {
            calCell.isHidden = false
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {}
 
}
```

**Comment by patchthecode** [comment]
Hey, thanks for filing this.
Are you saying that this is also happening with the sample project?
I am not seeing this :/ 

Is it possible you can send me a zipped copy of your project?

**Comment by patchthecode** [comment]
Also have you followed the tutorial on https://patchthecode.github.io/ ?

**Comment by johnyboy6000** [comment]
Cant send you a copy of code unfortunately. This is all the relevant code, I have read through your guide about 3 times now and no ideas on whats up. I checked the sample project and it seems to work but i can't see a difference between the code supplied and the one copied here?

**Comment by patchthecode** [comment]
Ok. Some thing must be different. 
If its not different in the code, then it has to be different in the project.
If you followed the  tutorial, then can you you would have seen the completed code here ->
https://github.com/patchthecode/CalendarTutorial

Download the code there and work backwards to see what is differe.
Also make sure you have the latest version 6.0.5

**Comment by johnyboy6000** [comment]
Got it sorted by copying your cell files, something is different between them that I can't see and have no time to look ;) Thanks a lot for the quick reply and help, its very appricated! 

Great library keep up the good work.

**Comment by patchthecode** [comment]
Thank you very much. If you like the library, or it has saved you months of coding time, then feel free to leave a star rating here. Thanks. And have a good one.
If you got more questions etc, just mention it here.
