### ISSUE TITLE
JTCalendar problems with translation to swift 3

### ISSUE THREAD

**Issue by thintank** [patchthecode/JTAppleCalendar#236]
Translating the library JTCalendar to swift 3 i get 3 errors which i cannot seam to resolve. One is "Redundant conformance of 'Date' to protocol 'Comparable'". The second one is "Cannot convert value of type 'qos_class_t' to expected argument type 'DispatchQos.QosClass'". The third is "Binary operator '===' cannot be applied to two 'Date' operands" 
Thanks

**Comment by thintank** [comment]
Translating the library JTCalendar to swift 3 i get 3 errors which i cannot seam to resolve. One is "Redundant conformance of 'Date' to protocol 'Comparable'". The second one is "Cannot convert value of type 'qos_class_t' to expected argument type 'DispatchQos.QosClass'". The third is "Binary operator '===' cannot be applied to two 'Date' operands" 
Thanks

**Comment by patchthecode** [comment]
@thintank what version of This library are you using?
The version should be 6.1.0

?

**Comment by patchthecode** [comment]
Also, this is JTAppleCalendar not JTCalendar. possible wrong repository?

**Comment by thintank** [comment]
Yes, it's JTAppleCalendar, my mistake. The version should be automatically the latest installing the pods.

**Comment by thintank** [comment]
From what i know. I could be wrong

**Comment by patchthecode** [comment]
What do you have in your `Podfile`?
Paste it here

**Comment by thintank** [comment]
source 'https://github.com/CocoaPods/Specs.git'
pod 'JTAppleCalendar'

these are the two lines I added to the podfile, reguarding JTAppleCalendar

**Comment by patchthecode** [comment]
Can you try ?

```
pod 'JTAppleCalendar', '~> 6.1'
```

then do a `pod install` and tell me what happens

**Comment by patchthecode** [comment]
If you are still getting errors. Then delete the JTAppleCalendar pod folder.
and reinstall

**Comment by thintank** [comment]
ok thank you i'll try that now

**Comment by patchthecode** [comment]
if it works, you owe me a github star rating for being up at 3:12 AM helping ya 😁

**Comment by thintank** [comment]
Ah ah ah ah ah ah I'm in Italy and here it's a more resonable noon

**Comment by patchthecode** [comment]
ok well let me know how it goes. Im heading to sleep.
laters man.

**Comment by thintank** [comment]
will do! thanks

**Comment by patchthecode** [comment]
so umm... did it work?

**Comment by thintank** [comment]
Still working on it. Somehow the pods got all messed up and I'm working on updating the cocoapod repo

**Comment by patchthecode** [comment]
cool.

**Comment by thintank** [comment]
ok it seems to be working now. i have to implement it correctly and if i have any problems i'll let you know. thank you so much
