### ISSUE TITLE
Help needed setting this up

### ISSUE THREAD

**Issue by chrisverra** [patchthecode/JTAppleCalendar#238]
Hi Jay,

I am trying to set it up using the tutorials.
However xCode can not find the library.

I am on 
- version 6.1.1 of JTAppleCalendar
- xCode 8.2
- Swift 3

![screen_shot_2016_12_21_at_21_11_03](https://cloud.githubusercontent.com/assets/2439146/21404665/2fbf699e-c777-11e6-8051-c04a037cee3a.png)

please advice.

Chris

**Comment by patchthecode** [comment]
can you join me here: https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Or if you cant, then

How did you install this library?
Did you install it using cocoapods?

**Comment by chrisverra** [comment]
lol i forgot to build
