### ISSUE TITLE
calendarView.deselectAllDates() doesn't work when allowsMultipleSelection == false

### ISSUE THREAD

**Issue by deniszhukov** [patchthecode/JTAppleCalendar#240]
Hi Jay,
I'm using latest version (6.1.1) of your calendar.

I wanted to make a datepicker with button to clear date selection. User can select only one date.
When user taps a button to clear date selection I'm calling calendarView.deselectAllDates(), but it doesn't work - date remain selected.

I tested on your example app, and it looks like it works when allowsMultipleSelection == true, but doesn't when allowsMultipleSelection == false.

**Comment by patchthecode** [comment]
Because this was the way i coded it :)
I can make an update for you in a short while.

**Comment by patchthecode** [comment]
One thing however, isnt the current behavior the way a `UIVollectionView` works?

**Comment by patchthecode** [comment]
This has now been fixed on master branch.
Test it by putting this in your pod file
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```

Then run `pod install`

**Comment by deniszhukov** [comment]
I tested it and it works fine.
Even thought, I googled a little bit, and yes, you're right, it looks like that's how UICollectionView works,
I think it's nice that deselectAllDates() now works with allowsMultipleSelection = false, because it was not immediately obvious that it should be used only with multiple selection.

Thank you for your work.

**Comment by patchthecode** [comment]
Cool.
Thanks. 👍
