### ISSUE TITLE
Is it possible to select date range by dragging last date selected  on calendar?

### ISSUE THREAD

**Issue by TimeToCodeIos** [patchthecode/JTAppleCalendar#241]
Hi ,

I have used this calendar for date range selection but now it is working like if I tap on date it gets selected then on another date then first to last date it shows selection ....but now I want it like if I select one date then another then from that 2nd selected date user drag on calendar then that all date should show selected ...
Please help me with this.
Thank you

**Comment by patchthecode** [comment]
Have you checked out how to add gestures in this tutorial?
-> https://patchthecode.github.io/AddingGestures/

look at **fluid range selection**

**Comment by patchthecode** [comment]
I have now added a tutorial in the https://patchthecode.github.io/RangeSelection/ web link on how to accomplish this
