### ISSUE TITLE
How to setup the background color of the calender?

### ISSUE THREAD

**Issue by kevinlee85** [patchthecode/JTAppleCalendar#243]
How to setup the background color of the calendar?
I am playing your example, but cannot change the background color? Where to set up the calendar's background color?

**Comment by patchthecode** [comment]
just go to the storyboard, and click on the calendarView, and change the color to anything you want.
If youre still stuck then you can join me here: https://gitter.im/patchthecode/JTAppleCalendar

**Comment by kevinlee85** [comment]
I have tried, but it not working.

**Comment by kevinlee85** [comment]
![screen shot 2016-12-26 at 10 59 33 am](https://cloud.githubusercontent.com/assets/6616311/21474451/6f88f6d0-cb5a-11e6-8464-db7258b748c1.png)
![screen shot 2016-12-26 at 10 59 40 am](https://cloud.githubusercontent.com/assets/6616311/21474452/6f950a92-cb5a-11e6-917c-a5f64f7f1544.png)
