### ISSUE TITLE
Excuse me, can be calendar month calendar fluid into a week?Calendar below there is a sliding view, for example, you slide into a weekly calendar?

### ISSUE THREAD

**Issue by yu629** [patchthecode/JTAppleCalendar#247]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.1.0
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
我不明白。
I do not understand.

Can you show me an image / picture of what you want the weekly calendar to look like?

**Comment by patchthecode** [comment]
It has been 3 days with no response from you.
Issues that are not bugs will be closed if you are not responsive.
I check Issues every day.

If you still have a question on this, then you can re-open this issue and I will continue helping you.
Cheers. Happy New year! :]
