### ISSUE TITLE
The delegate method will display cell sometimes gets called and sometimes does not, also the cells are not being displayed sometimes while for some cases they are

### ISSUE THREAD

**Issue by mansishah278** [patchthecode/JTAppleCalendar#248]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.1.0
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
I guess it is fixed?

**Comment by patchthecode** [comment]
If this library is useful to you, then consider leaving a star github rating 👍

**Comment by mansishah278** [comment]
Nope. I am trying to dig deep into the problem still

**Comment by mansishah278** [comment]
@patchthecode I don't understand that even if the willdisplaycell method gets called sometimes or not, the cells are not being displayed at all

**Comment by patchthecode** [comment]
Ok, I do not know where you are encountering the problem.
Can you let me know some more information?

1. Are you experiencing this error on the sample project attached to this repository?
2. Did you follow the tutorial on the site -> https://patchthecode.github.io/ . The completed tutorial files are located here -> https://github.com/patchthecode/CalendarTutorial

Maybe you can look into those and let me know where you are experiencing the issue?
Also can you let me know what version of the library you are using?

**Comment by mansishah278** [comment]
@patchthecode yes I have followed the same tutorial for purple calendar
and in the demo project I am not facing issues 
Also while I am checking it as a main VC there is no problem
But when I add the VC as a child VC to some other VC I am facing this issue !! Strange

**Comment by mansishah278** [comment]
@patchthecode To be specific when the VC containing calendar is added as a child to some other VC, the calendar cell height is 0

**Comment by patchthecode** [comment]
@mansishah278 ok i see that you have closed the issue again.
Is it now fixed? Every time you close the issue, you give the impression that it is fixed.

If it is not fixed, then can you tell me your setup?
You said that every thing works fine normally, but it fails when the VC is a child of another VC?
Let me know your setup and please give me enough information so that i can re-create the problem on my end as well.
