### ISSUE TITLE
Unknown Pending

### ISSUE THREAD

**Issue by Bargetor** [patchthecode/JTAppleCalendar#249]
I use 6.1.1  to make my calendar, I use auto layout (SnapKit). but, when I selected the day, the Consoler show this, cause view shake, help me:

```
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {24, 21.5})
pending: bounds from NSRect: {{0, 0}, {0, 0}} to Optional(NSRect: {{0, 0}, {24, 36}})
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {36, 21.5})
pending: bounds from NSRect: {{0, 0}, {0, 0}} to Optional(NSRect: {{0, 0}, {24, 36}})
pending: position from NSPoint: {0, 0} to Optional(NSPoint: {12, 21.5})
pending: opacity from 1 to Optional(0)
pending: opacity from 1 to Optional(0)
pending: opacity from 1 to Optional(0)
pending: bounds from NSRect: {{0, 2317.5}, {335, 562}} to Optional(NSRect: {{0, 2307}, {335, 562}})
```
ps: I did not use the related properties

**Comment by patchthecode** [comment]
Hmm. I think you will need to give me more information on this.
The Library does not give these error messages. 

Do you get these error messages without using snapkit?

**Comment by Bargetor** [comment]
Yes, I use cell xib to have the same result, I just used the snapkit layout calendar view in the view controller

**Comment by patchthecode** [comment]
Are you able to reproduce these error on the sample application attached to this project?

**Comment by patchthecode** [comment]
Or can you give me some information on how to reproduce this on my end?

**Comment by patchthecode** [comment]
It has been 3 days with no response.
I do not believe this error is related to this library.

If you are still experiencing this issue, then please re-open it, and I will continue where we left off.

**Comment by Bargetor** [comment]
sorry, I found the root of the problem, is the result of other project, I will fix it.
and thanks for your time.

**Comment by patchthecode** [comment]
awesome. thanks for replying. Glad its resolved.
