### ISSUE TITLE
Need sanity check for config

### ISSUE THREAD

**Issue by squarefrog** [patchthecode/JTAppleCalendar#250]
I've just spent a couple of hours trying to figure out why my project crashes when I load the calendar. It worked fine up until today (first clue there...).

It turns out I was trying to set `endDate` to something before `startDate`. In my case, this would only happen on the last day of the month, although it was very tricky to debug as the exception is raised far away from where you'd expect it to fail.

I propose a safer solution would be to add an `assert` that `endDate > startDate` at some point once ConfigurationParameters is set.

**Comment by patchthecode** [comment]
That is weird. 
I believe I already have this sanity check in here?

```swift
func setupMonthInfoDataForStartAndEndDate() -> CalendarData {
        var months = [Month]()
        var monthMap = [Int: Int]()
        var totalSections = 0
        var totalDays = 0
        if let validConfig = dataSource?.configureCalendar(self) {
            let comparison = validConfig.calendar.compare(validConfig.startDate, to: validConfig.endDate, toGranularity: .nanosecond)
            if comparison == ComparisonResult.orderedDescending {
                assert(false, "Error, your start date cannot be " + "greater than your end date\n")
                return (CalendarData(months: [], totalSections: 0, sectionToMonthMap: [:], totalDays: 0))
            }
   ...
   ...
}
```

Can you tell me what is occurring to cause the crash to happen?
The run path should have hit that line of logic :/ 
By the way, we are talking about version `6.1.1` right?

**Comment by squarefrog** [comment]
That's correct! So the issue is my code for sure, but because it took me so long to figure out, whereas an assert should have picked it up. 

I previously set the `endDate` to the start of the day of the last day of the month. Of course this failed today when I had the `startDate` as this afternoon. 

So a good test case would be `startDate == "2016-12-31 12:34:56"` and `endDate == "2016-12-31 00:00:00`. 

I'm happy to do some testing tomorrow once the hangover wares off! Happy new year! :tada:

**Comment by patchthecode** [comment]
Alright. Have a happy new year man.
Once your partying is over, let me know what tests you have done so that I can replicate why it did not properly do the assert.
Have an awesome end of yea 🎊 🎉

**Comment by squarefrog** [comment]
OK i've setup a quick project which reproduces the issue [here](https://github.com/squarefrog/CalendarBug). 👍

**Comment by patchthecode** [comment]
OK. I have checked your code.
It seems you used Carthage which compiled the frame work using optimizations.

NSAsserts are ignored it production level (optimized) code.
Therefore you are not alerted of the error.

As an experiment, I did you same project using `Cocoapods` instead of Carthage. And it correctly hits the assert.

**Comment by squarefrog** [comment]
Oh that makes sense! In that case, lets close the issue here. Thanks for looking into it.

**Comment by patchthecode** [comment]
Cheers
