### ISSUE TITLE
EXC_BAD_ACCESS - Simulator is not launching

### ISSUE THREAD

**Issue by shaheer87** [patchthecode/JTAppleCalendar#251]
I did exactly same as in the tutorial part 1 : https://patchthecode.github.io/MainTutorial/
Whenever I run the code, its giving an Error inside the viewDidLoad() - > delegate/datasource 
After the running successfully message, suddenly hit with an EXC_BAD_ACCESS error.
I am using Xcode 8.2.1 and Coded on Swift 3

<img width="1105" alt="screen shot 2017-01-01 at 11 20 14 pm" src="https://cloud.githubusercontent.com/assets/22956821/21582316/f41eadc2-d078-11e6-8d93-823908334993.png">

One more issue that the Example file provided is running without errors but its not invoking the simulator and i don't getting a running calendar. 

```swift
import UIKit
import JTAppleCalendar

class ViewController: UIViewController  {
    @IBOutlet weak var calendarView: JTAppleCalendarView!
   
   override func viewDidLoad() {
        super.viewDidLoad()
        calendarView.delegate = self
        calendarView.dataSource = self
        calendarView.registerCellViewXib(file: "CellView") // Registering your cell is manditory
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

extension ViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
    let formatter = DateFormatter()
    formatter.dateFormat = "yyyy MM dd"
    let startDate = formatter.date(from: "2016 02 01")! // You can use date generated from a formatter
    let endDate = Date()                                // You can also use dates created from this function
    let parameters = ConfigurationParameters(startDate: startDate,
                                             endDate: endDate,
                                             numberOfRows: 6, // Only 1, 2, 3, & 6 are allowed
        calendar: Calendar.current,
        generateInDates: .forAllMonths,
        generateOutDates: .tillEndOfGrid,
        firstDayOfWeek: .sunday)
    return parameters
}

func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
    let myCustomCell = cell as! CellView
    
    // Setup Cell text
    myCustomCell.dayLabel.text = cellState.text
    
    // Setup text color
    if cellState.dateBelongsTo == .thisMonth {
        myCustomCell.dayLabel.textColor = UIColor.black
    } else {
        myCustomCell.dayLabel.textColor = UIColor.gray
    }
}

}
```

**Comment by patchthecode** [comment]
@shaheer87 can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Are you saying that the example project provided is not working?

**Comment by shaheer87** [comment]
Example is running successfully.. but not getting on Simulator in Xcode 8.2.1 
Its not invoking the Simulator

**Comment by patchthecode** [comment]
I am running this version and all is well
![screen shot 2017-01-01 at 10 34 08 am](https://cloud.githubusercontent.com/assets/2439146/21582475/da5f3e76-d00d-11e6-9110-9467c3a8f468.png)

Can you Tell me which version build you are running?

**Comment by shaheer87** [comment]
<img width="578" alt="screen shot 2017-01-02 at 12 31 24 am" src="https://cloud.githubusercontent.com/assets/22956821/21582537/eb6ef11e-d082-11e6-81c5-773d681d93ee.png">
its not 8.2 , its 8.2.1 (8C1002)

**Comment by shaheer87** [comment]
<img width="1167" alt="screen shot 2017-01-02 at 12 34 40 am" src="https://cloud.githubusercontent.com/assets/22956821/21582547/529d00ce-d083-11e6-8430-ef0a642c85e3.png">

**Comment by patchthecode** [comment]
I just downloaded version 8.2.1 and the project is working fine.

When you said that the example is not working, you said that the simulator is not being opened.
Does the simulator open on other XCode projects on your system? 
The fact that the simulator is not opening makes me think that its a problem with your simulator possibly.

Let me know the result when you try running other projects.

**Comment by patchthecode** [comment]
Closing this as it seems to be an XCode issue and not a library issue
