### ISSUE TITLE
How to deselect specific date?

### ISSUE THREAD

**Issue by MrNiceMrGood** [patchthecode/JTAppleCalendar#254]
Hi Jay,
can u help with this.
Maybe missing something, but how can I deselect specific cell/s.

**Comment by patchthecode** [comment]
It depends.

If you have multiselect set to `true`, then simply select the same date again.
If you have multiselect set to `false`, then do the `deselectAllDates` command

**Comment by patchthecode** [comment]
To select a specific date, do the `selectDate` command.

**Comment by MrNiceMrGood** [comment]
Thanks for fast response.
I dont want to deselect all dates, maybe just range of dates.
Is it possible?

**Comment by patchthecode** [comment]
Yes it is.
I assume you have multiSelect set to true?

Then do `calendarView.selectDates(datesYouWantToDeselect)`

**Comment by MrNiceMrGood** [comment]
Hmm...
Got strange thing going on here, when i say deselectAll, it doesn't call didDeselectDate :/

**Comment by patchthecode** [comment]
Mines gets called correctly. What version are you using?

**Comment by MrNiceMrGood** [comment]
Using JTAppleCalendar (6.0.0)
When i deselect by using your function  selectDates() it works fine, it has problem only with deselectAll.
Sry for troubling you but I also have question regarding opening calendar view first time.
Is it possible to show specific date without scrolling to it.
I got pager-like full year calendar, showing month by month.
When i show like december as initial screen, it gets kind a slow.
Thank you for your time.

**Comment by patchthecode** [comment]
@MrNiceMrGood `deselectAll` was fixed on latest master branch patch. There was a bug with it.
Therefore you will have the latest code base if you put this in your `Podfile`
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```
Then do a `pod install`

Now, the calendar should not be slow at all. I have tested it on a slow iPhone 4s and it was blazing fast and smooth. If it is slow then you are possibly doing something wrong.

Can you join me here so we can chat? -> https://gitter.im/patchthecode/JTAppleCalendar
