### ISSUE TITLE
JTAppleCalendarViewDelegate methods are not called after calling ScrollToDate

### ISSUE THREAD

**Issue by ZezhongLi** [patchthecode/JTAppleCalendar#258]
When I called calendar view ScrollToDate, I thought all the related delegate method like didScrollToDateSegmentWith and scrollDidEndDecelerating will be called, but actually not.
Is this a issue?

**Comment by patchthecode** [comment]
This is a newly introduced bug in the last version. It has already been fixed on master branch.
To get the latest code put this in your pod file

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```

and then do a `pod install`

**Comment by patchthecode** [comment]
new version released.
closing this issue
