### ISSUE TITLE
How to put a little circle under the selected number day

### ISSUE THREAD

**Issue by oskarko** [patchthecode/JTAppleCalendar#259]
Hi Jay,

Thanks in advance for your work. It's awesome!.

I'm trying to select some dates adding a little circle red under the number but I haven't seen how to do it. Can you give me some link or example?

Thanks!

**Comment by patchthecode** [comment]
@oskarko Have you looked at the tutorial yet? -> https://patchthecode.github.io/

It tells you how to setup your calendar.

**Comment by oskarko** [comment]
it doesn't show how to do it.

**Comment by patchthecode** [comment]
It shows you how to add a UILabel.
And it shows you how to add a Circular selected `UIView`.

All you have to do is use the same approach, and add another circular little circle as you want.
You can any any view you want to it. You can design the CellView however you want.

Which part do you need help on?
