### ISSUE TITLE
Calendar Grid is not fully 0,0 when set to 0,0 Cell inset. It is off by one pixel when orientation changes. This seems to be an iOS issue. Workaround for now is to set the inset to some negative fractional value if you are experiencing the issue.

### ISSUE THREAD

**Issue by cbwilliamsnh** [patchthecode/JTAppleCalendar#26]
I have a three month calendar (June - Aug, 2016). I've attached three images.

First is how the calendar initially appears, second is when I scroll from June to July and third is when I scroll back to June.

Here's the additional code in my controller:

```
    calendarView.dataSource = self
    calendarView.delegate = self
    calendarView.registerCellViewXib(fileName: "ScheduleCellView")
    calendarView.backgroundColor = UIColor.whiteColor()
    calendarView.cellInset = CGPoint(x: 2, y: 2)

    let currentDate = calendarView.currentCalendarDateSegment()
    setupViewsOfCalendar(currentDate.startDate, endDate: currentDate.endDate)
```

setupViewsOfCalendar is from the tutorial.

<img width="380" alt="screenshot 2016-05-24 10 39 52" src="https://cloud.githubusercontent.com/assets/8007059/15508199/81da8d66-219c-11e6-94f6-e7aa9517b05a.png">

<img width="379" alt="screenshot 2016-05-24 10 40 04" src="https://cloud.githubusercontent.com/assets/8007059/15508205/8623aa74-219c-11e6-95eb-ee633d560936.png">

<img width="380" alt="screenshot 2016-05-24 10 40 20" src="https://cloud.githubusercontent.com/assets/8007059/15508211/8a0d6db4-219c-11e6-88ce-d986bced5d53.png">

**Comment by patchthecode** [comment]
OK. first thing. I update this calendar quite a bit. Which version are you using?

**Comment by cbwilliamsnh** [comment]
Using JTAppleCalendar (3.0.0) // From pod install output

**Comment by patchthecode** [comment]
OK chat here is slow, mind coming here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Note the latest version is 3.0.1
Can you do an update and let me know if it is fixed?

**Comment by cbwilliamsnh** [comment]
It is fixed!

Thank you!

**Comment by patchthecode** [comment]
Hey mind putting that image of you calendar here?
I would really appreciate it. This is a new project and people needs to see what can be done with it.
Can you post that image here? --> https://github.com/patchthecode/JTAppleCalendar/issues/2

**Comment by patchthecode** [comment]
And leave a like! :) its much needed. thanks!

**Comment by cbwilliamsnh** [comment]
Happy to do so (and did!)

Chuck

p.s. do I need to do anything special to support a touch or 3d touch?
Should I add that to the cell and the cell's controller?

love the cocoapod!

On Tue, May 24, 2016 at 1:13 PM, JTAppleCalendar <notifications@github.com>
wrote:

> Hey mind putting that image of you calendar here?
> I would really appreciate it. This is a new project and people needs to
> see what can be done with it.
> Can you post that image here? --> #2
> <https://github.com/patchthecode/JTAppleCalendar/issues/2>
> Wont bug you anymore if you do :]
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/26#issuecomment-221339134>
>



-- 
Chuck

**Comment by patchthecode** [comment]
Touch and 3d touch? heh.. i dont even have an iPhone6 :(
I have not looked into 3d touch, but now that you mentioned it, i'll look into it in a bit. Well.. more like a bit bit.

**Comment by cbwilliamsnh** [comment]
FYI a cellInset of 0,0 still gives sketchy results on the grid display.

**Comment by patchthecode** [comment]
taking a look

**Comment by patchthecode** [comment]
It looks fine on mines

1. Are you free scrolling? or paged scrolling?
2. What happens with inset 0,0?

**Comment by patchthecode** [comment]
Ok i think i see something. It still leaves a space.  It is a line that is off by one pixel.
Is this what you area talking about? 

Fixing this issue now.

**Comment by patchthecode** [comment]
Hmm.. on second thought. I cant tell if it is an error without looking to see if it is on a real device. The line space disappears when i zoom in the iOS simulator by pressing the CMD + 1  or CMD + 2 or CMD + 3 keys.  You will have to tell me specifically what you are seeing

**Comment by cbwilliamsnh** [comment]
default scrolling (so paged?)

inset 0,0 gives results similar to the first image in the original issue.

On Tue, May 24, 2016 at 1:49 PM, JTAppleCalendar <notifications@github.com>
wrote:

> It looks fine on mines
>
>    1. Are you free scrolling? or paged scrolling?
>    2. What happens with inset 0,0?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/26#issuecomment-221345952>
>



-- 
Chuck

**Comment by cbwilliamsnh** [comment]
Could be. I know that only some of the lines show when the inset is 0,0. My
app is portrait only so there is no orientation change.

On Tue, May 24, 2016 at 2:03 PM, JTAppleCalendar <notifications@github.com>
wrote:

> Ok i think i see something. It still leaves a space. It is a line that is
> off by one pixel.
> Is this what you area talking about?
>
> Fixing this issue now. It happens when i do an orientation change.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/26#issuecomment-221348678>
>



-- 
Chuck

**Comment by cbwilliamsnh** [comment]
When inset is 0, 0, this is what I see:

[image: Inline image 1]

Different lines are missing when I scroll the calendar, but the same lines
are missing on each month when I scroll back and forth.

On Tue, May 24, 2016 at 2:07 PM, JTAppleCalendar <notifications@github.com>
wrote:

> Hmm.. on second thought. I cant tell if it is an error without looking to
> see if it is on a real device. The line space disappears when i zoom in the
> iOS simulator by pressing the CMD + 1 or CMD + 2 or CMD + 3 keys. You will
> have to tell me specifically what you are seeing. Looking into it further
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/26#issuecomment-221349570>
>



-- 
Chuck

**Comment by patchthecode** [comment]
not seeing the image

**Comment by patchthecode** [comment]
Tell you what. Set the inset to -1, -1 as a work around. I'll have to look into this after dinner

**Comment by cbwilliamsnh** [comment]
<img width="375" alt="screenshot 2016-05-24 14 12 08" src="https://cloud.githubusercontent.com/assets/8007059/15515575/d368fce2-21bc-11e6-98d3-e536e8cd8467.png">

just for completeness, here's the screenshot.

**Comment by patchthecode** [comment]
Ok, i have found fixed this issue and pushed it to github.
I have not released it in 3.0.2 yet just in case there is something else wrong with  it (i dont think there should be though, i tested it much). Are you able to take a pull of master branch to see if it works for you?

**Comment by cbwilliamsnh** [comment]
I know how to pull the master branch, but not sure what I need to do to
replace the pod with what I pull (I'm a seasoned programmer but still
somewhat new to Xcode, iOS, cocoa pods, etc.)

On Tue, May 24, 2016 at 7:50 PM, JTAppleCalendar <notifications@github.com>
wrote:

> Ok, i have found fixed this issue and pushed it to github.
> I have not released it in 3.0.2 yet just in case there is something else
> wrong with it (i dont think there should be though, i tested it much). Are
> you able to take a pull of master branch to see if it works for you?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/26#issuecomment-221435812>
>



-- 
Chuck

**Comment by patchthecode** [comment]
I understand.
Ok, hmm.. i'm working on another upgrade you see. So i dont want to release another one yet. So here's what, 

do a clone of this repository --> https://github.com/patchthecode/JTAppleCalendar.git
Next, just exchange these 3 files in your local cocoa pod folder, with these 3 files in the repository that you just cloned

The file names are:
1. JTAppleCalendarDelegate.swift
2. JTAppleCalendarFlowLayout.swift
3. JTAppleDayCell.swift

Once you replace these 3 files, you should now have the fix. 
When I do the official release next week, you can just do your regular `pod install` command.

Let me know if the fix worked.

**Comment by cbwilliamsnh** [comment]
Thanks!

I'm working on another (unrelated) issue. As soon as that's solved I'll
give this a try.

Chuck

On Tue, May 24, 2016 at 8:03 PM, JTAppleCalendar <notifications@github.com>
wrote:

> I understand.
> Ok, hmm.. i'm working on another upgrade you see. So i dont want to
> release another one yet. So here's what,
>
> do a clone of this repository -->
> https://github.com/patchthecode/JTAppleCalendar.git
> Next, just exchange these 3 files in your local cocoa pod folder, with
> these 3 files in the repository that you just cloned
>
> The file names are:
> 1. JTAppleCalendarDelegate.swift
> 2. JTAppleCalendarFlowLayout.swift
> 3. JTAppleDayCell.swift
>
> Once you replace these 3 files, you should now have the fix.
> When I do the official release next week, you can just do your regular pod
> install command.
>
> Let me know if the fix worked.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/patchthecode/JTAppleCalendar/issues/26#issuecomment-221437719>
>



-- 
Chuck

**Comment by patchthecode** [comment]
Should be fixed in version 4.0.0

**Comment by hanishassim** [comment]
I'm having the same problem too, I'm on the 4.0.3
![simulator screen shot 23 jun 2016 1 21 12 am](https://cloud.githubusercontent.com/assets/4571502/16276407/cfc5f73a-38e0-11e6-9805-4c9b1ca0774f.png)
You can see there is like a gap there. Note that I've placed the imageview cell and set constraint 0 on all sides, and content mode fill

**Comment by patchthecode** [comment]
@hanishassim is it possible you can give me a copy of your `.xib` file?
You can drag your file and drop it straight into this conversation box on github here. If that is possible for you.

**Comment by hanishassim** [comment]
Sure here it is.
[CalendarDateCell.xib.zip](https://github.com/patchthecode/JTAppleCalendar/files/328513/CalendarDateCell.xib.zip)

**Comment by patchthecode** [comment]
OK taking a look.

**Comment by patchthecode** [comment]
Hmm. It seems ok there. Would it be possible if i could see the bugged project? Or is it private?

**Comment by hanishassim** [comment]
Could you share the screenshot? Sorry but I can't share the project..

**Comment by patchthecode** [comment]
Understood. Hmm. Alright then i'll have to debug this on my end. In the mean time, try setting the inset to (-0.5, -0.5) or (-1, -1) as a work around (you can choose what ever number you like). Will get back to you.

**Comment by patchthecode** [comment]
Ok. I just setup the calendar.
And mine is working properly.
So some questions about your calendar:
1. I see you December 2006 is being over lapped by the the black view. Are you doing anything extra in your configuration?
2. Also, i see in your xib, you're using UIImageViews instead of UIViews. Is every thing ok here?
3. Does this issue happen to the sample calendar project attached here on github?

**Comment by hanishassim** [comment]
1. I removed it, instead using the header for section xib now, no extra config used.
2. I'm using imagviews cause I want to apply calendar like airbnb's, they have date which is not selected, but set as blocked (not available for booking). Is still selectable if want to unbock it (which will remove the image view) .. Hmm is it okay to use the imageviews?
3. It does not happen in the sample cause the selectedView is round and not filling till the edges, so can't see if there is gap or not.

Attached is what I'm trying to achieve, like aribnb:
![iphone 6 plus copy 2](https://cloud.githubusercontent.com/assets/4571502/16325887/a628e530-39f4-11e6-9188-08bac1ec3800.png)

**Comment by patchthecode** [comment]
Alright then, so in order for me the recreate the (0,0) error it seems i have to create a selected background view that is not circular in shape.  I will do as you did and use a UIImageView and fill the cell to see if i can recreate it.

And btw, you can use any view on your calendar. So long as it can be dragged unto the canvas, it can be used.

**Comment by hanishassim** [comment]
thanks noted.

**Comment by patchthecode** [comment]
Closed. 
Changed behavior of calendar.
```swift
if cellInset.x == 0 { cellInset.x = -0.1 }
if cellInset.y == 0 { cellInset.y = -0.1 }
```
