### ISSUE TITLE
Calendar not displaying in UIView #255

### ISSUE THREAD

**Issue by umeshjavastar** [patchthecode/JTAppleCalendar#260]
I am again open this issue with my small empty project, I have already mention my problem in issue #255 .

@patchthecode  Here is code url. Please see this and check what type of error I am facing.

https://www.dropbox.com/s/9kkxpq304upyf8n/DemoCalendar.zip?dl=0

**Comment by patchthecode** [comment]
I think the problem is to do with your you frameSize code.

```swift
    let calendarContainer:UIView = {
        let view = UIView(frame: CGRect(x: 0, y: 106, width: 398, height: 312.333)) // PUT A FRAME HERE
        view.backgroundColor = bgColor
        view.layer.cornerRadius = 6
        view.layer.masksToBounds = true
        return view
    }()
```

**Comment by patchthecode** [comment]
If you still have problems, then I will re-look it again.
If this fixes your issue, feel free to leave a star Github rating. 👍 
Let me know.

**Comment by umeshjavastar** [comment]
Thanks @patchthecode it really helpful for me

**Comment by patchthecode** [comment]
Awesome! glad it worked. Closing this issue now. :)
