### ISSUE TITLE
Change number of rows from 6 to 1 makes calendar display wrong date

### ISSUE THREAD

**Issue by XiangXu** [patchthecode/JTAppleCalendar#261]
Hi,

I am using your fantastic calendar right now, however I got a problem. 

I have a calendar and it has two modes: weekly and monthly view. 

When user first time open the calendar, it shows like below: 
<img width="371" alt="screen shot 2017-01-12 at 02 11 10" src="https://cloud.githubusercontent.com/assets/4528188/21874353/712b3d6c-d86c-11e6-9b02-d33c8e9419d2.png">

When user swipe up on calendar, it will change to weekly view:
<img width="376" alt="screen shot 2017-01-12 at 02 06 35" src="https://cloud.githubusercontent.com/assets/4528188/21874238/c604a1b2-d86b-11e6-8219-275f59a76c0a.png">

As you can see, the date is incorrect now. It changed from 2017 to 2016, but if I swipe down to change calendar back to monthly view, it still displays correct date. I wonder what cause this?  Am I wrong here?

My code: 
```swift
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let startDate = Calendar.current.date(byAdding: .year, value: -1, to: Date())
        let endDate = Calendar.current.date(byAdding: .year, value: 1, to: Date())
        let parameters = ConfigurationParameters(startDate: startDate!,
                                                 endDate: endDate!,
                                                 numberOfRows: numberOfRows, // Only 1, 2, 3, & 6 are allowed
                                                 calendar: Calendar.autoupdatingCurrent,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfGrid,
                                                 firstDayOfWeek: .sunday)
        return parameters
    }

```
This method will be called when user swipe up or down, I change numberOfRows from 1 to 6 or 6 to 1 and then I reload calendar. 
```swift
func updateViewToMonthOrWeek(rows: Int, height: CGFloat) {
        numberOfRows = rows
      
        calendarView.changeHeight(to: height)
        timelineTableView.changeYposition(to: calendarView.frame.height + calendarView.frame.origin.y)
        calendarView.reloadData()
        calendarView.scrollToDate(titleDate)
}
```

**Comment by patchthecode** [comment]
What version of the calendar are you using? 

If you are able to do so, can you join me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
This is expected.
You can refer to the explanation here -> https://github.com/patchthecode/JTAppleCalendar/issues/202#issuecomment-262071517

**Comment by XiangXu** [comment]
Thanks for your reply. 
Yes, I am using the latest version. 
"put this in your pod file ->
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
then do a pod Install"

I save the Date I want to scroll to as titleDate. So in my updateViewToMonthOrWeek methoh:
1. I change calendar row number from 6 to 1 
2. Then I update calendar height 
3. I call reloadDate, it reset the parameters and set the row number to 1.
4. Then I call scrollToDate to let calendar scroll to the titleDate. 

I print out the titleDate, it is 2017.1.12 but after scrollToDate, it is still 2016.3.2. 
Did I do anything wrong or I have to call like below?

**Comment by patchthecode** [comment]
are you online now? 
join me here -> https://gitter.im/patchthecode/JTAppleCalendar
