### ISSUE TITLE
Multiple Months Visible At Once

### ISSUE THREAD

**Issue by vishalvshekkar** [patchthecode/JTAppleCalendar#264]
Hey, this is a wonderful calendar! Much appreciated.

Is there a way to show multiple months at once? Right now, every month section occupies the entirety of the calendar view frame.

I want it much like Apple's iOS Calendar App (See image).

![img_3498](https://cloud.githubusercontent.com/assets/13771106/21962080/2598de3a-db42-11e6-8699-6a85d58dbc2f.PNG)

**Comment by patchthecode** [comment]
It is located in the documentation section here -> https://patchthecode.github.io/CommonQuestions/

If youre still stuck let me know.

**Comment by vishalvshekkar** [comment]
Right! I'm sorry I didn't' check the questions before posting.
Thanks a lot for responding!

It worked well..

**Comment by patchthecode** [comment]
awesome! cool. Have a good one

**Comment by taimur** [comment]
@patchthecode I want to achieve the same thing. Can you please check the common Questions link - Its not working. 

https://patchthecode.github.io/CommonQuestions/

**Comment by patchthecode** [comment]
@taimur link is dead. 

ok. to accomplish this, just decrease the size of the cell.
The smaller the cell size, the more months fit on the screen.

```swift
calendarView.cellSize = x
```
