### ISSUE TITLE
I want to know 'JTAppleCalendar' can do it like this?

### ISSUE THREAD

**Issue by baobao57** [patchthecode/JTAppleCalendar#266]
<img width="274" alt="2017-01-16 6 48 13" src="https://cloud.githubusercontent.com/assets/12264243/21980074/b774891e-dc1c-11e6-851b-fb28c8571e7f.png">

Because I've been using 'JTAppleCalendar' make half the work, I don't want to change into other components

**Comment by patchthecode** [comment]
```swift
let someSmallerDateCellValue = 20
calendarView.itemSize = someSmallerDateCellValue
```

**Comment by baobao57** [comment]
Thank you for your answer. I wish you good luck.
