### ISSUE TITLE
Can not install latest JTAppleCalendar repo using Cocoapods

### ISSUE THREAD

**Issue by Ranganstyles** [patchthecode/JTAppleCalendar#268]
My Podfile looks like,
![screen shot 2017-01-18 at 11 27 32 am](https://cloud.githubusercontent.com/assets/20065602/22052677/95c27b54-dd71-11e6-9d9d-4f8d1ccd7f98.png)

While "Pod install", i'm getting error as
![screen shot 2017-01-18 at 11 11 19 am](https://cloud.githubusercontent.com/assets/20065602/22052698/adede38a-dd71-11e6-9448-0b79b6519c26.png)

I tried every other versions, getting the same error. But by removing version specifier in podfile i can install '5.0.1' that doesn't support swift 3 and also tried swift 3 branch which doesn't exist. 
Please help installing the latest repo.

**Comment by patchthecode** [comment]
what version of cocoapod are you using?

**Comment by Ranganstyles** [comment]
i'm using  CocoaPod 1.1.1

**Comment by patchthecode** [comment]
put this in your podfile and tell me what you get

```
  pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
```

**Comment by patchthecode** [comment]
If this failed as well, then try creating a new project and try installing another cocoapod other than JTAppleCalendar. Does others fail as well?

**Comment by Ranganstyles** [comment]
Other Pods are working Fine. Thank you.
Ok, Latest JTAppleCalender repo for **SWIFT 3** installed successfully, using the Podfile

source 'https://github.com/CocoaPods/Specs.git'
target 'SampleProject' do
  use_frameworks!
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
end

**Comment by sayalilokhande** [comment]
[!] CocoaPods could not find compatible versions for pod "JTAppleCalendar":
  In Podfile:
    JTAppleCalendar (from `https://github.com/patchthecode/JTAppleCalendar.git`, branch `7.0.0`)

Specs satisfying the `JTAppleCalendar (from `https://github.com/patchthecode/JTAppleCalendar.git`, branch `7.0.0`)` dependency were found, but they required a higher minimum deployment target.

when this happen

**Comment by sayalilokhande** [comment]
platform :ios, '8.0'

**Comment by patchthecode** [comment]
Latest version of the calendar is for swift 4.2
what version of swift are you using in your app?

**Comment by sayalilokhande** [comment]
swift 4.1 ---- On Fri, 28 Sep 2018 18:18:02 +0530 JTAppleCalendar <notifications@github.com> wrote ---- Latest version of the calendar is for swift 4.2 what version of swift are you using in your app? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
