### ISSUE TITLE
Sorry, do you guys know any good framework to parse iCal (.ics) file?

### ISSUE THREAD

**Issue by vietstone** [patchthecode/JTAppleCalendar#269]
Sorry. May be this is not the place to ask this question, but I don't know where's better.
Do you know any good framework to parse iCal (.ics) file in Swift 3?
Thank you.
You can close this issue if it's not suitable.

**Comment by patchthecode** [comment]
A good place to ask a question like that is on Slack in the ios dev chat. There are many people there that can help you with this.
I do not know the answer to this question, so i'll close it as it is unrelated. I have asked your question on slack. If they respond then i will tell you the response here. Best of luck

**Comment by vietstone** [comment]
Yes, thank you.

**Comment by patchthecode** [comment]
@vietstone have you tried this one? --> https://github.com/KiranPanesar/MXLCalendarManager
