### ISSUE TITLE
exc_bad_instruction (code=exc_i386_invop subcode=0x0) 

### ISSUE THREAD

**Issue by Zeered** [patchthecode/JTAppleCalendar#270]
I am using 1 row of calendarview
i make it can be clicked and change to the colour i wanted.
but.. i only can do this in a row of the first page when i m running it.
ex. 1 month have 4 weeks.. 
but i only can clicked the first week where is the first preview when i run
when i click at the others it will show the error
at 
let myCustomCell = cell as! cellView exc_bad_instruction (code=exc_i386_invop subcode=0x0)

**Comment by patchthecode** [comment]
can you copy and paste the entire function?

**Comment by patchthecode** [comment]
No response for 5 days. I assume your problem has been resolved.
If this is still an issue for you, then click on the re-open button and I will continue.
