### ISSUE TITLE
How to get number of rows, then the height of the calendar view can be adjusted accordingly

### ISSUE THREAD

**Issue by oyalhi** [patchthecode/JTAppleCalendar#271]
My settings are as follows:
```swift
let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6, // only 1, 2, 3 & 6 are allowed
                                                 calendar: Calendar.current,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .tillEndOfRow,
                                                 firstDayOfWeek: .monday,
                                                 hasStrictBoundaries: true)

```

Depending on the month the calendar has 5 or 6 rows. Exactly what I want.

When there are 6 rows, everything is perfect.

When there are 5 rows, the rows are stretched accordingly (hasStrictBoundaries: true). So instead of this, I would like the calenderView height to shorten by 1 row.

Therefore, I need to be able to read numberOfRows, and change the calendarView height. Is this possible please?

Below are the screen shots:

![simulator screen shot 20 jan 2017 09 50 54](https://cloud.githubusercontent.com/assets/11165954/22139473/e116c8ca-deee-11e6-8e86-00d537dff274.png) ![simulator screen shot 20 jan 2017 09 50 59](https://cloud.githubusercontent.com/assets/11165954/22139474/e11815a4-deee-11e6-953e-2f84a19f96e4.png)

Thank you for the great product btw!

**Comment by patchthecode** [comment]
Currently, I do not tell you how much rows are there per month.
Let me see what I can do.

**Comment by patchthecode** [comment]
After looking at my code again, I realized that I actually do have that feature already.

```swift
let status = calendarView.cellStatus(for: date)!
let forCountForVisibleSection = status.dateSection().rowCount
```

So when you calendarDidScroll is called, I guess you can get the
```swift
calendarView.visibleDates
```

to determine which dates are on the screen. Then from that you can call the other code above to get the number of rows.

**Comment by patchthecode** [comment]
`rowsForSection` was renamed to `rowCount`
Depending on what version of the calendar you are using.

**Comment by oyalhi** [comment]
For some reason didScrollToDateSegmentWith is not being called, neither scrollDidEndDecelerating. Any ideas what I might be doing wrong?

**Comment by patchthecode** [comment]
@oyalhi yes this is a bug that was fixed.

It was introduced. in the latest version.
It is currently already fixed on master branch, and a new version will be released in about a week or so.

If you want the **latest** up-to-date code, put this in your pod file --> 
```
  pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

```

**Comment by patchthecode** [comment]
Latest version has been released. This should no longer be an issue. Closing this now.
