### ISSUE TITLE
Crash "Subrange extends past the end" when continuous range selection

### ISSUE THREAD

**Issue by handioq** [patchthecode/JTAppleCalendar#272]
Hi there one more time :)

I got an error when use [continuous range selection](https://patchthecode.github.io/RangeSelection/) (with long press gesture) on line:

```
rangeSelectedDates.removeSubrange(indexOfNewlySelectedDate..<lastIndex) // fatal error: Array replace: subrange extends past the end

```

**Note:**
It is reproducible when you select days from the right to left direction.

**Completed code**:

```
func didStartRangeSelecting(gesture: UILongPressGestureRecognizer) {
        let point = gesture.location(in: gesture.view!)
        rangeSelectedDates = calendarView.selectedDates
        if let cellState = calendarView.cellStatus(at: point) {
            let date = cellState.date
            if !rangeSelectedDates.contains(date) {
                let dateRange = calendarView.generateDateRange(from: rangeSelectedDates.first ?? date, to: date)
                for aDate in dateRange {
                    if !rangeSelectedDates.contains(aDate) {
                        rangeSelectedDates.append(aDate)
                    }
                }
                calendarView.selectDates(from: rangeSelectedDates.first!, to: date, keepSelectionIfMultiSelectionAllowed: true)
            } else {
                let indexOfNewlySelectedDate = rangeSelectedDates.index(of: date)! + 1
                let lastIndex = rangeSelectedDates.endIndex
                let followingDay = Calendar.current.date(byAdding: .day, value: 1, to: date)!
                calendarView.selectDates(from: followingDay, to: rangeSelectedDates.last!, keepSelectionIfMultiSelectionAllowed: false)
                rangeSelectedDates.removeSubrange(indexOfNewlySelectedDate..<lastIndex) // error
            }
        }
        
        if gesture.state == .ended {
            rangeSelectedDates.removeAll()
        }
    }
```

Now I'm looking for solutions, any suggestions?

**Comment by patchthecode** [comment]
The code in that tutorial is just sample code. You can code it however you want.

But that said, I am unable to reproduce this this error.
You say you just select any date and start dragging to the left?
Can you provide me some more information as to the sate of your calendar?

1. You start selecting with nothing on screen selected? or you start selecting with dates already selected.
2. What does your `configureCalendar` function looks like?
3. Can you reproduct this code in the sample application on this github repository?

Let me know.

**Comment by patchthecode** [comment]
ok. 4 days and no reply. I will assume you have solved the problem. If you still have an issue, then reopen this by clicking on the re-open button. I will respond 👍
