### ISSUE TITLE
Act on nth DayCell easily

### ISSUE THREAD

**Issue by arronhunt** [patchthecode/JTAppleCalendar#273]
I tried researching this but I'm having a hard time finding anything. 

I'd like to be able to reference the nth date cell from `datesDisplaying` in the calendar by index. So, for example, the date cell at index [0] I'd like to add custom style to, etc. Is this possible?

**Comment by patchthecode** [comment]
@arronhunt 
this is possible. In fact, this is how this library was built :D 
I think you are thinking about the problem too hard.

You do not need to get the `nth` cell to customize it.
You have to customize it when it is displayed.

Have you looked at the tutorial here yet? -> https://patchthecode.github.io/
It is very detailed.

If you still need help, then let me know where you are stuck.
You can also join me here -> https://gitter.im/patchthecode/JTAppleCalendar for aquick response

**Comment by patchthecode** [comment]
Btw, i see your website as being a Kick-ass UI & UX Designer -> http://arronhunt.com/
If you end up creating an awesome calendar, then don't be shy in uploading screen shots :D

**Comment by patchthecode** [comment]
It's been 5 days with no response.
I will assume that the issue was resolved.
If this is still a problem then you can re-open the issue.
