### ISSUE TITLE
How to disable vertical bouncing?

### ISSUE THREAD

**Issue by wilsonbalderrama** [patchthecode/JTAppleCalendar#274]
I can't find the way to do it, I only want to use the horizontal scrolling. Thanks, by the way JTAppleCalendar is so great!

**Comment by patchthecode** [comment]
@wilsonbalderrama what version of the calendar are you using? Ther should not be any "bouncing" :/

**Comment by wilsonbalderrama** [comment]
hey @patchthecode thanks for the quick response, I'm using the 6.0.2 version.

I've copied from the README this sentence into my podfile:

pod 'JTAppleCalendar', '~> 6.0'

**Comment by patchthecode** [comment]
Can you put this into your podfile instead? Many fixes have been done.

```
  pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

```

**Comment by wilsonbalderrama** [comment]
I've put it and now I have the 6.1.1 version and still see the vertical bouncing.

![https://media.giphy.com/media/26gsm6SV97EqpMVUY/source.gif]()

**Comment by patchthecode** [comment]
i'll be online for some time today. Can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by wilsonbalderrama** [comment]
I had to apply this solution https://patchthecode.github.io/CommonProblems/, to my root view controller that is a UITabBarController afterwards everything was ok. thank you @patchthecode for pointing me to the link :)
