### ISSUE TITLE
visibleDates call after reloadData with comletionHandler error

### ISSUE THREAD

**Issue by Tsarfolk** [patchthecode/JTAppleCalendar#277]
I'm using 6.1.2 version of JTAppleCalendar

The problem:
I'm using something like this in viewDidLoad()

```
loadDataFromServer {
        self.calendar.reloadData() {
                self.calendarView.visibleDates { (visibleDates: DateSegmentInfo) in
                    .....
                }
        }
}
```

This line of code crashes the app. It worth to mention I was on swift 3.0 and there was no problem, then I updated it to 3.0.2 and JTCalendar too. Since then I got this crash. I attach images of that crash
![2017-01-31 14 21 05](https://cloud.githubusercontent.com/assets/15061918/22463444/ad7c39be-e7c2-11e6-9952-ad0c8d0d9f91.png)
![2017-01-31 14 21 42](https://cloud.githubusercontent.com/assets/15061918/22463446/ad8ce6ce-e7c2-11e6-84fd-10e2da30bc36.png)
![2017-01-31 14 22 08](https://cloud.githubusercontent.com/assets/15061918/22463445/ad89e2c6-e7c2-11e6-9320-3d79ac37dce5.png)

**Comment by patchthecode** [comment]
OK, this should not crash your app.

Your `loadDataFromServer` takes about how many seconds? 
I am trying to re-create this on my end in my example application.
If you can recreate the issue there on the example application, this will be very helpful as well.

But if you cant, its cool. I'm investigating.
Also, I have `swift 3`, not `swift 3.0.2`. I'm not sure of the changes in there yet.
Will have to look into it.

**Comment by Tsarfolk** [comment]
I recreated it
`calendarView.reloadData {
            self.calendarView.reloadData {
                self.calendarView.visibleDates { (visibleDates: DateSegmentInfo) in
                    self.setupViewsOfCalendar(from: visibleDates)
                }
            }
        }`

in the viewDidLoad at example app

**Comment by patchthecode** [comment]
OK. I can re-create the error now. Looking into it

**Comment by patchthecode** [comment]
I think this issue is now fixed from this commit -> https://github.com/patchthecode/JTAppleCalendar/commit/f3685534671d3dc79b1092df6ed37ca13dfbce70

Let me know if you are still experiencing this.
