### ISSUE TITLE
scrollToDate at startup

### ISSUE THREAD

**Issue by handioq** [patchthecode/JTAppleCalendar#279]
Hello.

I'm trying to call scrollToDate in viewDidLoad() and it seems that it does not work:

```
calendarView.reloadData() {
            self.calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: false, animateScroll: false)
        }
```

and i also trying by this way:

```
calendarView.reloadData()
calendarView.scrollToDate(myDate) 
```

the same result..

It seems I'm doing something wrong.

**Comment by patchthecode** [comment]
If you are online now, can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by handioq** [comment]
Oops, it is my bad. It is not bug and fix not needed. Sorry.
I'm just debug this issue and it is my fail with correct usage of reloadData method.

**Comment by patchthecode** [comment]
Alright. Understood. closing the issue now. If you still have problems, then open a new issue :)
