### ISSUE TITLE
scrollToDate animateScroll = false

### ISSUE THREAD

**Issue by ownmas** [patchthecode/JTAppleCalendar#281]
Even if animateScroll = false, there is initially load a first page of calendar and after that it show marked date. I use these function in viewDidLoad/viewWillAppear.

calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: false, animateScroll: false, preferredScrollPosition: nil, completionHandler: nil)

**Comment by patchthecode** [comment]
I think the error you are referring to is this one -> https://github.com/patchthecode/JTAppleCalendar/issues/263

I will close this issue as it is a duplicate. I have not had time to look into it, but it seems to be something related to UIKit. I will look into it.
