### ISSUE TITLE
How to display an icon on the current date?

### ISSUE THREAD

**Issue by f15handch1p5** [patchthecode/JTAppleCalendar#282]
Hi, i'm using Swift and trying to add a small icon to show on the current date/day. I have added the view to my custom date cell and connected the outlets. But i just don't know how to implement the functionality in my ViewController class to show on the specific date. Any help would be much appreciated thanks!

**Comment by patchthecode** [comment]
Hi, just wondering if you have looked at the tutorials presented here -> https://patchthecode.github.io/. It will answer all of your questions.

But to answer you specific question, you simply put a check in side the delegate function

```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
   // You can do something like this
   if date == aDateThatEqualsTodaysDate {
       // Add an icon to the view
   else { 
      // make the icon to the view be empty
   }

}
```
