### ISSUE TITLE
Manually installation

### ISSUE THREAD

**Issue by abara-kedavra** [patchthecode/JTAppleCalendar#284]
Hi! I copied the sources directory into my project, but it doesn't work. "import JTAppleCalendar" -  "no such module "JTAppleCalendar"" - how can I fix it?

**Comment by patchthecode** [comment]
Hey, installing manually is very technical and should be done by people who exactly what to do.
If you decide to go that route then my help in that area is very limited. As I usually use `Carthage` and `Cocoapods` which sets up every thing for me automatically. 

I can investigate for you how this is done manually, but as I am currently between 3 projects, I'm sure that you will find a solution before I even get on it.

Is it possible that you can use either `CocoaPods` (easier to install) or Carthage (a little harder than cocoapods, but still very easy) ?

**Comment by RockGuitarist1** [comment]
Having this same issue, even when using Cocoapods.

**Comment by patchthecode** [comment]
@RockGuitarist1 can you explain?

> EDIT: Got this to work by Build for Testing

I am unsure what you mean

**Comment by RockGuitarist1** [comment]
I could not import JTAppleCalendar, because it would return the same error as the OP. I fixed this by going to Product -> Build For -> Testing.

**Comment by pcolliso** [comment]
You do not need to #import the Module if you are dragging in the source files.

**Comment by kevintorch** [comment]
'SelectionType'  is ambiguous for type lookup in this context... i do i solve it

**Comment by patchthecode** [comment]
in what file is this error?
