### ISSUE TITLE
How to automatically animate/scroll when an in/out date is selected?

### ISSUE THREAD

**Issue by f15handch1p5** [patchthecode/JTAppleCalendar#286]
Hi, how would i initiate an automatic scroll animation when an in/out date was selected ? For example: a user would select an out date on a specific month and it would then scroll/animate for them to the appropriate month. Thanks

**Comment by patchthecode** [comment]
@f15handch1p5 

you use the `scrollToDate` function in the `didSelectDate` delegate function.
