### ISSUE TITLE
Convenient way to get circular cells?

### ISSUE THREAD

**Issue by f15handch1p5** [patchthecode/JTAppleCalendar#287]
Hi, is there a convenient way to get circular cells? I am having trouble doing it through the layer's corner radius property. Thanks

**Comment by patchthecode** [comment]
Can you show me the code you are using to do this?
And can you show me the function where you have the layer code?
I cant say much without seeing code :)

**Comment by f15handch1p5** [comment]
Sure, so specifically i want the selected cell to appear circular when selected. 

`if cellState.isSelected {
            myCustomCell.selectedView.layer.cornerRadius = myCustomCell.selectedView.frame.size.width / 2;
            myCustomCell.clipsToBounds = true;
            myCustomCell.selectedView.isHidden = false;
        } else {
            myCustomCell.selectedView.isHidden = true;
        }`

This is called in both did select cell and will display cell

**Comment by patchthecode** [comment]
Hey, I think what will help you GREATLY is the tutorials --> https://patchthecode.github.io/

Start with part one, and then go to part 2. It tells you every thing you need to do regarding this.

**Comment by patchthecode** [comment]
I will close this issue. But if you still need help on it, just continue the discussion here.
I'm closing this since it is not really a bug.

**Comment by f15handch1p5** [comment]
Yeah i read the tutorials. I wasn't sure whether this could be maybe to do with something how i have got my constraints setup ?

**Comment by patchthecode** [comment]
OK, can you let me know what is the problem you are having when you set it in the layer property?
I think I should have asked this question first.

Lets assume that your selectedView has a width of 50 and a height of 50 in constraints.
Then generally, to get a circle, you will set the layer property to half the size of the selectedView = 25. Half the size.

Can you describe the problem you are having?
