### ISSUE TITLE
Calendar very slow

### ISSUE THREAD

**Issue by alapaches** [patchthecode/JTAppleCalendar#288]
Hi everyone.

I'm just a beginner to swift and to iOS developpement in general. 

JTAppleCalendar is just amazing. This the thing that I've been looking for several months. However, I think I've got an issue.
I've followed the tutorials to create a very simple calendar. But my calendar is way too slow. ( It takes at least 10 or 15 secs to open). I don't know what makes that.

I'm testing my app both on simulator (iPhone 5s) and on my real device (iPhone 5s) as well.

Maybe someone could help me ? If you want, I'll post a bit of my code.

Thank you all. Sorry if I make mistakes, I'm French and started Swift 2 weeks ago :)

**Comment by patchthecode** [comment]
1. What device are you using the calendar on?
2. What is your `start date` boundary and `end date` boundary?

**Comment by alapaches** [comment]
Hi there.

Is it related. Anyway, solved the issue : My end date boundary was up to 2999. So it was completely normal that the calendar took this time to load more than 900 years in it. I'm closing the issue and Thanks for replying me so fast :).

**Comment by patchthecode** [comment]
Haha. Alrighty. Glad it worked out.
But yes, I am working on that fix to increase performance when very many years are loaded.

**Comment by cyrilzakka** [comment]
Hello again. 
I have a split view controller with the main view controller displaying a small calendar and the detail view controller displaying a bigger detailed calendar on the iPad. What are some optimizations I can make in order for both to run smoothly when displayed at the same time?

**Comment by patchthecode** [comment]
@cyrilzakka they both should be running smoothly at the same time.
in order to determine why your calendar is laggy, you will need to paste me your code for `cellForItemAtIndex` function and the code for `willDisplayCell` function.

Please open a new issue to paste this.
