### ISSUE TITLE
Calendar should be able to be instantiated completely in code

### ISSUE THREAD

**Issue by N1c0L4z3R** [patchthecode/JTAppleCalendar#29]
Right now, it seems like there are some limitations when using the library. One of them is that you can't use it without having a xib for the cell file.

I feel like the library should allow the user to use either interface builder or code.

**Comment by patchthecode** [comment]
Sounds like a good idea, but hey, i was wondering. 
You actually WANT to design the cell in code? :-/

**Comment by patchthecode** [comment]
Maybe if you can help me know whats needed to be able to have it in code, i can add it.

**Comment by patchthecode** [comment]
Ok after reading up what the UITableView does, i see they have a method called, registerClass. I think i will adop this so that it will be similar. Thinking on this.

**Comment by patchthecode** [comment]
Ok, i think i have the general idea.
But i cant test it because I am not good at developing cells by code.
If you give me a sample cell (done in code) send it to me and i can test etc. It doesnt have to be anything complex.

**Comment by patchthecode** [comment]
Hey, today i have pushed code to master branch that allows you to create cells with code.

Usage: `calendarView.registerCellViewClass(fileName: "YourProjectName.NameOfYourCellView")`

You must use the `nameOfYourProject` then a `.` followed by the name of your nonXibFile. This is a swfit requirement.


I have not released a version 3.0.2 yet. 
I have pushed it to master branch.
It is still a work in progress, but maybe you can let me know what I'm missing?

**Comment by patchthecode** [comment]
updated to version. 4.0
