### ISSUE TITLE
sectionSpacing

### ISSUE THREAD

**Issue by frios** [patchthecode/JTAppleCalendar#291]
What does sectionSpacing actually affect? I have tried setting it to some high number to see what changes but cannot see any difference.

Thank you

**Comment by patchthecode** [comment]
`sectionSpacing` oops...
Thats a new feature I am adding. It allows you to have a space between month sections.
looks like i accidentally released it with that last build. But you can expect it to do something in the next 2 weeks :)

**Comment by patchthecode** [comment]
This feature has now been added on 7.0.0 Branch.
Closing.

**Comment by renchris** [comment]
I can't find this feature currently. What is sectionSpacing now called by?

**Comment by patchthecode** [comment]
calendarView.sectionInset
