### ISSUE TITLE
cellState.selectedPosition() returns wrong position for May 1st, 2017

### ISSUE THREAD

**Issue by tungfam** [patchthecode/JTAppleCalendar#292]
Sorry for creating another issue.. but I probably found a 'bug' (?): 
I have the range of dates selected 18th April through May 11th (dates doesn't matter, the main thing is that May 1st should be in the range):
![image](https://cloud.githubusercontent.com/assets/17186720/22613931/674eac86-ea85-11e6-92ca-d2da910c1b4b.png)

I have a rule that if  the `cellState.selectedPosition() == .left` and `cellState.selectedPosition() == .right` then it should has a dark blue view (start and end dates). But as you can see the May 1st also is selected (has this dark view). And as I see it falls into the `if selectedPosition() == .left`

And this happens to all the dates that are in the left top corner of the month (for example Jan 1st 2018).

Does it reproduces on your side?

**Comment by patchthecode** [comment]
Ah yes. 
this one was already logged here -> https://github.com/patchthecode/JTAppleCalendar/issues/280

Its a small fix i need to do on my end.
I'll up this over the weekend.
I'll close the issue here and flag it as a duplicate.

**Comment by tungfam** [comment]
@patchthecode got it! thanks a lot. sorry for duplication :)

**Comment by patchthecode** [comment]
It cool man. :]
