### ISSUE TITLE
Different types of date selection

### ISSUE THREAD

**Issue by guillianbalisi** [patchthecode/JTAppleCalendar#293]
I'm creating an app for drug cessation and each day the user is prompted with an alert asking them if they refrained from drug use that day. If they select yes, I want to display a "yes" view in the cell view, and if they select no I want to display a "no" view in the cell view. I know there is calendarView.selectDates however I can't figure out how to select the view that I want to display. Is there a way to do this?

**Comment by patchthecode** [comment]
I do not fully understand what you are trying to do.
But I will ask have you checked out the tutorials on https://patchthecode.github.io/ ?
The tutorials there will help you in what you are trying to accomplish

**Comment by patchthecode** [comment]
After a user selects yes, I would imagine that you have some dataSource that saves which day user said yes and which day he said no. Therefore you would have a datasource that links days to yes/no.

Therefore in your `willDisplayDate` delegate function, all you have to do is check to see if the dateCell being configured, matches a yes/no date in your dataSource. If yes, you attach your yesView, and no, you attach your noView.

**Comment by guillianbalisi** [comment]
Thank you, I figured out how to do it using the `willDisplayCell` delegate function.
