### ISSUE TITLE
Crash in didSelectDate

### ISSUE THREAD

**Issue by frios** [patchthecode/JTAppleCalendar#294]
I have a calendar open to the current month and the current date selected. I implemented a "Today" button with the following code:

```swift
@IBAction func todayTapped(_ sender: UIBarButtonItem) {
   self.calendarView.selectDates([Date()], triggerSelectionDelegate: true, keepSelectionIfMultiSelectionAllowed: false)
   self.calendarView.scrollToDate(Date())
}
```
If I select another date in the same month, then tap "Today", it all works fine. When I scroll to another month, select a day then tap "Today", I get the following crash:

`fatal error: unexpectedly found nil while unwrapping an Optional value`

in

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState)
       let myCustomCell = cell as! CalendarCellView
```

Sure enough, "cell" is nil here. Is this a bug in the protocol?

**Comment by patchthecode** [comment]
This is not a bug.
you did this

```swift
let myCustomCell = cell as! CalendarCellView
```
You have forced unwrapped cell using this -> `as! CalendarCellView`
The cell is declared as this --> `cell: JTAppleDayCellView?`

`cell` is optional. You need to do optional chaining to determine if the cell is nil or not.

something like this
```swift
guard let myCustomCell = cell as? CalendarCellView else {
   return 
}
```

**Comment by frios** [comment]
Yes, I see the problem. Thanks for the clarification. I am curious though why it returns nil rather than the newly selected cell?

**Comment by patchthecode** [comment]
It will return nil if your cell if not visible on the screen.

**Comment by patchthecode** [comment]
By the way, let me just mention this just in case you missed it like many others.
This has the location of the tutorials that will help a lot -> https://patchthecode.github.io/
