### ISSUE TITLE
Show Current day

### ISSUE THREAD

**Issue by alapaches** [patchthecode/JTAppleCalendar#295]
Hello everyone.

I've searched for it but didn't find any clue.

I want to highlight the current day when the calendar loads. I've tried to create another xib and class files but can't manage to do it. 

Do someone knows how to achieve that ?

Many thanks :)

**Comment by patchthecode** [comment]
Information can be found on the tutorials site -> https://patchthecode.github.io

Specific information on coloring the date can be found on his link -> https://patchthecode.github.io/DateCellConfiguration/

Closing this issue now, but if you're still stuck then let me know.
