### ISSUE TITLE
[UI Improvement] Months separated on "cells" & custom design

### ISSUE THREAD

**Issue by dimmdesign** [patchthecode/JTAppleCalendar#296]
Not an issue per se. Rather a mere improvement on this library to support the below design.

![img_0264](https://cloud.githubusercontent.com/assets/886854/22303255/5b3b3f84-e32a-11e6-8427-394c9caae3da.PNG)

On the above image, we can clearly see that each month is separated in its own "cell" with rounded corners and a drop shadow. I achieved the above by using a UICollectionView and UICollectionViewCell. Each cell includes an instance of a JTAppleCalendar with a custom configuration in order to only show one month. 

It would be great if JTAppleCalendar could provide such ability instead of having to create a custom one like I did.

**Comment by patchthecode** [comment]
Alright. I'll get to work on a prototype to accomplish this.
will get back to you in some time

**Comment by dimmdesign** [comment]
@patchthecode For the sake of simplicity I created a stripped down version of my implementation. You Can find the repository here — https://github.com/dimmdesign/CustomCalendar

**Comment by patchthecode** [comment]
@dimmdesign awesome. checking it out now.

**Comment by patchthecode** [comment]
made good progress on this. Expect a massive update in version 7.0.0
Code is ready. Just doing final tests.

**Comment by patchthecode** [comment]
Issue resolved on version 7.0
Releasing Beta version this weekend.
