### ISSUE TITLE
Incorrect position of the first day of the month when InDateCellGeneration is .off

### ISSUE THREAD

**Issue by numen31337** [patchthecode/JTAppleCalendar#297]
In order to make something similar to Apple Calendar and for some other use cases we need to drop first and last days of the month, as on the image above:

![Apple Example](https://s27.postimg.org/mmna0xnwz/topic_calendar_ios.png)

Unfortunately looks like there is some issue with the current implementation because the first day of the month is always displayed as very first day no matter which day of the week it is. This can be seen from the provided example app when switching these modes:

![Issue Example](https://s23.postimg.org/vpc2lto6z/Simulator.jpg)

Is there any solution to resolve this issue and have a static header for a vertically scrolling calendar?

**Comment by handioq** [comment]
Hello.
I don't know exactly, is this is bug or not, but... you can simple hide this inDates without setting .off state.

```
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        let calendarCell = cell as! CalendarCellView
        ...
        if cellState.dateBelongsTo == .thisMonth {
            calendarCell.isHidden = false
        } else {
            calendarCell.isHidden = true
        }
       ...
    }
```

**Comment by patchthecode** [comment]
@numen31337 hey, there is no bug. @handioq has answered the question correctly.

In the situation you have described, if you want to make a calendar like Apple, then you want `inDates` to be generated, **but** you want them to be hidden.

Have you checked out the [Tutorials](https://patchthecode.github.io/) yet? They will explain every thing for you clearly.

The Sample app that I have attached is there to give you an idea of the kind of layouts you can have. With this library you can build any calendar design/layout (as long as it is a grid).

**Comment by patchthecode** [comment]
If you need further help in setting up your design then Let us know. We'll be glad to help.
