### ISSUE TITLE
Calendar selection clicks are one click behind

### ISSUE THREAD

**Issue by cbwilliamsnh** [patchthecode/JTAppleCalendar#30]
I've enabled the calendar for selection.

func calendar(calendar: JTAppleCalendarView, didDeselectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {
        let game = RealmController.sharedInstance.getGameForDate(date)

        if game != nil {
            SwiftLogger.debug(String(format: "Game details: %@, %@, %@", (game?.opponent)!, (game?.date)!, (game?.startTime)!))
        } else {
            SwiftLogger.debug("no game on chosen date")
        }
    }

- The initial click does not hit the above callback.
- Subsequent clicks send the date from the previous click

**Comment by patchthecode** [comment]
wow, i have never seen this one before. I hope its really not an issue. One sec. Looking into it.

**Comment by patchthecode** [comment]
Based on the question you have posted. I see that you have used the **Deselection** method and not the **Selection** one

func calendar(calendar: JTAppleCalendarView, **didDeselectDate** date: NSDate, cell: JTAppleDayCellView?, cellState: CellState)

Maybe that is your issue?

**Comment by cbwilliamsnh** [comment]
Yep! Good catch! 

Serves me right for cutting and pasting without paying attention!
