### ISSUE TITLE
Issue in displaying calendar view (data is not populating into cells)

### ISSUE THREAD

**Issue by saikirangandham41** [patchthecode/JTAppleCalendar#301]
Hi Jay,
This is sai, I am having an issue in displaying calendar in my app. Here I'm attaching a screenshot of my simulator when displaying calendar (View is in red color).
![screen shot 2017-02-10 at 12 05 43 am](https://cloud.githubusercontent.com/assets/18451840/22816056/360abda0-ef25-11e6-900c-6ecd8f23b7f5.png)
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.1.2
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Interesting.
Just wondering, have you looked at the Tutorial here? -> https://patchthecode.github.io/

[Part one is here](https://patchthecode.github.io/MainTutorial)
[Part 2 is here](https://patchthecode.github.io/MainTutorial2)

The tutorials also contain sample code to help you set it up correctly.
Let me know if you still need help.

**Comment by saikirangandham41** [comment]
Followed steps from your tutorial 
-> created cellView.xib and cellView.swift
-> connected to storyboard
->code from your tutorial and etc.,..

**Comment by patchthecode** [comment]
The tutorial has completed code here -> https://github.com/patchthecode/CalendarTutorial
Can you download the code and see maybe what was done wrong on your project?

Or, you can show me the code that you have.
I cannot help much if you do not show me what code you did.

**Comment by saikirangandham41** [comment]
It worked.
Hey thanks for your support

**Comment by patchthecode** [comment]
Awesome! Will close this issue now :)
If you love the lib, then feel free to leave a star rating.
If you have any other questions, then just open a new issue. I'll try by best to answer.
cheers 🍻
