### ISSUE TITLE
WillDisplaySectionHeader gets called twice.

### ISSUE THREAD

**Issue by mrikh** [patchthecode/JTAppleCalendar#302]
I have setup months for the calendar i'm making to be displayed in the "inside header" so that it scrolls along with the swipe gesture in the vertical direction. When the view controller with the view first loads, the `willDisplaySectionHeader` method gets called twice and since I'm using `calendar.visibleDates()` to get the current month to be displayed in the header, the second section so created has the same month, as at that point of time the visible cells are of the initial month and not the second month even when loading the second section. 

So what happens is that the first month is shown in two section headers even though the months inside the dates are of a different month.

Am i missing something here? 

As a workaround I'm getting the month from the center value of the range property provided in `willDisplaySectionHeader`.

**Comment by patchthecode** [comment]
Hmm... is there a reason you are using `visibleDates()` to get the month in there?

```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
   // This funciton has a [date] parameter you can use to find out the current month
   let date = range.start
   let month = testCalendar.component(.month, from: date)
   // Now convert the month Int into a string to be displayed
}
```

**Comment by mrikh** [comment]
I'm using `visibleDates()` as `range.start` contains the value of the previous month that is displayed as well! So for example if I'm displaying the month of March, a few of the dates of February are displayed as well and `range.start` contains that as well. So getting the mid value of the range works fine as a workaround for me.

Actually I haven't changed the `calendarView.itemSize` value at all and thats why i was confused as to why it was calling `willDisplaySectionHeader()` for the **next** section also! The only layouting i've changed would be `calendarView.cellInset = CGPoint(x: 0, y: 0)` and displaying the header in the `headerView` delegates provided

    func calendar(_ calendar: JTAppleCalendarView, sectionHeaderSizeFor range: (start: Date, end: Date), belongingTo month: Int) -> CGSize {
        
        //divide by 7 as including header there will be 7 rows and then multiply to make it more than the height of each row
        return CGSize(width: calendar.bounds.size.width, height: calendar.bounds.size.height/7.0 * 1.5)
    }

  
    func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {

        let calendar = Calendar(identifier: .gregorian)

        var tempArray = [Date]()
        
        var date = range.start
        
        tempArray.append(range.start)
        
        var components = DateComponents()
        
        components.day = 1
        
        while date < range.end{
        
            date = calendar.date(byAdding: components, to: date)!
            
            tempArray.append(date)
        }
        
        tempArray.append(range.end)
        
        setupHeaderCell(forDate: tempArray[tempArray.count/2], sectionHeader: header)
    }`

Apart from the above things, I haven't touched the cell layouting.

**Comment by patchthecode** [comment]
Ok. Something is wrong somewhere.

`var date = range.start` should **only** contain the the start of the month. It should not contain multiple months in the date range.

I think you might be doing something wrong, but i am not sure yet. So let me verify by asking the following:

1. Can you show me your `configureCalendar` function code?
2. What version of the JTAppleCalendar are you using?
3. `let calendar = Calendar(identifier: .gregorian)` is not good. You are creating an instance of a `Calendar()` every time you scroll. `Calendar` is notoriously slow to initialize. This means that your calendar will lag very badly on the device.
4. Have you taken a look at the [Tutorials on this link](https://patchthecode.github.io/) yet? It explains every thing. Take a look at `part1` and `part2` tutorial.

Let me know the answers.
4.

**Comment by mrikh** [comment]
Sure. I would greatly appreciate help in finding the problem as this is the second calendar I've tried after making several changes in other pods to get the UI the way the designer wants it, this pod has been the easiest to implement! 

1.
```

func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let formatter = DateFormatter()
        
        formatter.dateFormat = "yyyy MM dd"
        
        let startDate = Date()
        
        let calendar = Calendar(identifier: .gregorian)
        
        var components = DateComponents()
        
        components.year = 1
        
        let endDate = calendar.date(byAdding: components, to: startDate)!
        
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 6, calendar: Calendar.current, generateInDates: .forAllMonths, generateOutDates: .tillEndOfGrid, firstDayOfWeek: .sunday)
        
        return parameters
    }
    
```

2. I just did a `pod install` this morning so I'm quite sure its the latest,  it was 6.1.2 or something. 

3. Thanks for the tip, I'll keep that in mind when i start cleaning up the class.

4. I actually followed the very same tutorials on that page (Good job, they are quite clear). I even looked at your sample project to figure out if I'm doing wrong but using `didScrollToSegment` and setting up header for that segment was proving to be a problem as i couldn't get the reference to the headerview that is being displayed in that segment inside that delegate.

**Comment by patchthecode** [comment]
I see that you are using different calendar instances in your code.

In the `configureCalendar` function you are using `Calendar.current` in the parameters (which is good). But then in other places, you are using `Calendar(identifier .gregorian)`.

It might be possible that `calendar.current` is giving a different timeZone calendar to `Calendar(identifier .gregorian)`. Therefore if you provide `.current` to the `configureCalendar()` function, but use `Calendar(identifier .gregorian)` to do the calculations in your `willDisplaySectionHeader`, your dates will be incorrect.

Therefore: 
change your configure code to this:
```swift
   func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let startDate = Date()
        let calendar = Calendar.current
        var components = DateComponents()
        components.year = 1
        let endDate = calendar.date(byAdding: components, to: startDate)!
        let parameters = ConfigurationParameters(
            startDate: startDate, 
            endDate: endDate, 
            numberOfRows: 6, 
            calendar: Calendar.current, 
            generateInDates: .forAllMonths, 
            generateOutDates: .tillEndOfGrid, 
            firstDayOfWeek: .sunday)
        return parameters
    }
```

Change your `willDisplayHeader` code to this:
```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
    
        let date = range.start
        let dateString = formatter.string(from: date)

        let headerCell = header as? WhatEverYouCalledYourHeaderCellClass
        headerCell?.title.text = dateString
    }
```

Let me know the results.
Heading to work. Will respond in a bit

**Comment by mrikh** [comment]
Ah yeah, that seems to solve the problem! I completely overlooked using `calendar.current` and just blindly copied the configuration from the tutorial! Sorry for the trouble :D!

**Comment by patchthecode** [comment]
Awesome!
Hey man, if you like the lib, feel free to leave a star github rating ★.
Cheers. 🍻

**Comment by patchthecode** [comment]
One thing i forgot to tell you. Do not initialize a `DateFormatter()` inside the `willDisplaySectionHeader` function.

```
func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
        let formatter = DateFormatter() // <----- DO NO T INIT() THIS IN HERE
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
    
        let date = range.start
        let dateString = formatter.string(from: date)

        let headerCell = header as? WhatEverYouCalledYourHeaderCellClass
        headerCell?.title.text = dateString
    }
```

DateFormatters are also very slow to initialize. Putting it in there will also make your calendar very laggy. Remember that function is called for every header that is displayed. So you will be creating a new formatter every time you swipe. Create this outside the function, and then just use it inside the function by using the variable name.
