### ISSUE TITLE
Deselect rows outside current month

### ISSUE THREAD

**Issue by bitomule** [patchthecode/JTAppleCalendar#303]
I've implemented my own range selection and I've found an issue. If I either use deselectAll or selectDates (already selected) it never deselects dates outside current month. Is there a way to deselect cells outside current month?

**Comment by patchthecode** [comment]
1. What version of the calendar are you using? Master Branch or Latest 6.1.2 release?
2. In your `ConfigureCalendar` function, what is your `startDate` and `endDate`? And are you trying to select a date outside of that range?

**Comment by bitomule** [comment]
1. I've tried last release. Master works, but because it doesn't allow selection before current month (I guess startDate month)
2. startDate is always current Date, so yes, the issue cell is outside my config startDate and endDate

Using master version seems to fix the issue. Thanks.

**Comment by patchthecode** [comment]
@bitomule Cool. 
Well yes, the issue was fixed on master branch. This will be officially released soon.
