### ISSUE TITLE
.dataSource = self

### ISSUE THREAD

**Issue by 16tthoma** [patchthecode/JTAppleCalendar#305]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.1.2
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by 16tthoma** [comment]
When I copy and paste the code of example 1, the lines 
calendarView.dataSource = self
        calendarView.delegate = self

give me an error of 'Can not assign value of type ViewController to type JTAppleCalendarViewDataSource' and etc. When I comment them out and run it, I get the following error 

[JTAppleCalendar.JTAppleCollectionReusableView registerCellViewXibWithFile:bundle:]: unrecognized selector sent to instance 0x7f8d1bc1bab0
2017-02-16 14:12:41.595 Smart Pillbox[2645:98215] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JTAppleCalendar.JTAppleCollectionReusableView registerCellViewXibWithFile:bundle:]: unrecognized selector sent to instance 0x7f8d1bc1bab0'

**Comment by patchthecode** [comment]
Hey can you give some more information?

I do not know what code you have.

**Comment by patchthecode** [comment]
I will assume this issue is resolved.
As I believe the tutorial was not properly followed.
Here is the completed tutorial code -> https://github.com/patchthecode/CalendarTutorial

If you still need help with this. Let me know.

**Comment by skyeyvapor** [comment]
I encountered the same issue, since I tried to build the view in a .xib so I need the method to set delegate and dataSource of object JTAppleCalendar to ViewController like in version 6: calendarView.dataSource = self
calendarView.delegate = self

If I can't set delegate and dataSource via like dragging line to ViewController, is there a coding way to do the same thing?

**Comment by patchthecode** [comment]
@skyeyvapor if youre still up, can you join me here? -> https://gitter.im/patchthecode/JTAppleCalendar
