### ISSUE TITLE
populate cells with data from a database

### ISSUE THREAD

**Issue by Fujitora2304** [patchthecode/JTAppleCalendar#306]
Hey,
At first, thanks for this great library!
I have two questions:
1. I want to populate my calendar cells with data when the app starts. I know this question was asked often before, but I still don't get it, I'm pretty new in Swift programming.

This is my code so far:
I populate an array with data from my database:

`var workoutDates = [Date]()`

```swift
    func getWorkoutDates(){
        let workouts = realm.objects(Workout.self)
        for object in workouts{
            let date = object.day
            workoutDates.append(date)
        }
    }
```

I call the getWorkoutDates() in the viewDidLoad().

After this, I want to call it in the willDisplayCell():

```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        let myCustomCell = cell as! CellView
        
        myCustomCell.dayLabel.text = cellState.text
        
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelection(view: cell, cellState: cellState)
        
        let date = cellState.date
        print(cellState.date)
        print(workoutDates)
        if workoutDates.contains(date){
            myCustomCell.containsWorkoutView.isHidden = false
        }
        else{
            myCustomCell.containsWorkoutView.isHidden = true
            print("Hello")
        }
    }
```

But this isn't working. The containsWorkoutView isn't appearing.

This is my Cell:

```swift
class CellView: JTAppleDayCellView {

    @IBOutlet weak var dayLabel: UILabel!
    @IBOutlet weak var selectedView: UIView!
    @IBOutlet weak var containsWorkoutView: UIView!
}
```
What I'am doing wrong?

2. I want to make the cells from the inDates invisible. I've seen this code in the common questions:

```swift
if cellState.dateBelongsTo == .PreviousMonthWithinBoundary {
    self.hidden = false
} else {
    self.hidden = true
}
```

But in which function should I call this?
Thanks in advance!

**Comment by patchthecode** [comment]
> But in which function should I call this?

This should be placed in the function that configures how your cell look.
Put it in the `willDisplayCell` function

> But this isn't working. The containsWorkoutView isn't appearing.

Because you are doing this
```swift
if workoutDates.contains(date){
   myCustomCell.containsWorkoutView.isHidden = false
} else {
   myCustomCell.containsWorkoutView.isHidden = true
   print("Hello")
}
```

Just because dates are inside of the `workoutDates` array, doesnt mean that it is the same date format that you are comparing it against.

In your `configureCalendar` function, you would have given JTAppleCalendar a `Calendar()` instance. Therefore the dates that JTAppleCalendar gives you will be configured to that Calendar's region settings. 

Question: Are the dates that you are getting from the database and storing in your dataSource of the same format as the date that JTAppleCalendar is giving you?
NSDateFormatter here is your friend. It will fix your problem.

**Comment by Fujitora2304** [comment]
Yes, that was it, it's better now, thanks!
But there is still a problem. I used this extension to compare the dates:

`extension Date{
    struct Calendar {
        static let gregorian = NSCalendar(calendarIdentifier: NSCalendar.Identifier.gregorian)!
    }
    func isInSameDayAs(date: NSDate) -> Bool {
        return Calendar.gregorian.isDate(self, inSameDayAs: date as Date)
    }`

Then I wrote this in my willDisplayCell():

`func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        let myCustomCell = cell as! CellView
        
        myCustomCell.dayLabel.text = cellState.text
        
        if cellState.dateBelongsTo == .previousMonthWithinBoundary {
            myCustomCell.isHidden = true
        } else {
            myCustomCell.isHidden = false
        }
        
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelection(view: cell, cellState: cellState)

        let date = cellState.date
        
        for object in workoutDates{
            if object.isInSameDayAs(date: date as NSDate){
                myCustomCell.containsWorkoutView.isHidden = false
            }
            else{
                myCustomCell.containsWorkoutView.isHidden = true
            }
        }`

Now the view appears from time to time.. It's not always there. Moreover the view appears in the wrong place. It appears at Februar 24 and not at Februar 17, where it should be. Any ideas how I can fix this?

**Comment by patchthecode** [comment]
I could be wrong, but maybe its because your code looks bad here 

```swift
        for object in workoutDates{
            if object.isInSameDayAs(date: date as NSDate){
                myCustomCell.containsWorkoutView.isHidden = false
            }
            else{
                myCustomCell.containsWorkoutView.isHidden = true
            }
        }
```

You are looping through ever object in your `workoutDates` array.
so let's say the first object is `Jan1st` in your workoutDates. And `date` also happens to be `Jan1st` then all is well, and your cell is configured.

BUT, since you are looping, the loop is not yet done. Therefore, lets say the 2nd date inside your `workoutDates` array happens to be Jan2nd, then since `date` still equals Jan1st, your code will now undo the configuration that you have done. I think this is a code problem and not a calendar problem.

why dont you format the dates inside of the `workoutDates` array to be of the exact same format of the `date` that is given to you by JTAppleCalendar?
If you do that then you wont need an extension. All you would now do is:

```swift
if workoutDates.contains(date) {
   myCustomCell.containsWorkoutView.isHidden = false
} else {
   myCustomCell.containsWorkoutView.isHidden = true
}
```

**Comment by Fujitora2304** [comment]
Thanks for the quick answer.
I tried this before, but that doesn't work too. 
This is what I'm doing now, the dates are in the same format:
`    override func viewDidLoad() {
        super.viewDidLoad()
        
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = calendar.timeZone
        formatter.locale = calendar.locale
        calendarView.dataSource = self
        calendarView.delegate = self
        calendarView.registerCellViewXib(file: "CellView")
        calendarView.cellInset = CGPoint(x: 0, y: 0)
        calendarView.visibleDates { (visibleDates: DateSegmentInfo) in
            self.setupViewsOfCalendar(from: visibleDates)
        }
        self.navigationItem.setHidesBackButton(true, animated:false)
        getWorkoutDates()
        print(workoutDates)
    }`

`func getWorkoutDates(){
        let workouts = realm.objects(Workout.self)
        for object in workouts{
            let date = object.day
            let formattedDate = formatter.string(from: date)
            workoutDates.append(formattedDate)
        }
    }`

`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let startDate = formatter.date(from: "2017 01 01")!
        let endDate = formatter.date(from: "2017 12 31")!
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6,
                                                 calendar: self.calendar,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .off,
                                                 firstDayOfWeek: .monday,
                                                 hasStrictBoundaries: true)
        return parameters
    }
`

`    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
        let myCustomCell = cell as! CellView
        
        myCustomCell.dayLabel.text = cellState.text
        
        if cellState.dateBelongsTo == .previousMonthWithinBoundary {
            myCustomCell.isHidden = true
        } else {
            myCustomCell.isHidden = false
        }
        
        handleCellTextColor(view: cell, cellState: cellState)
        handleCellSelection(view: cell, cellState: cellState)

        let date = cellState.date
        let formattedDate = formatter.string(from: date)
        
        if workoutDates.contains(formattedDate) {
            myCustomCell.containsWorkoutView.isHidden = false
        } else {
            myCustomCell.containsWorkoutView.isHidden = true
        }
    }`

It's the same problem as before, the view isn't appearing always and it's in the wrong place.

**Comment by patchthecode** [comment]
If you are online, join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
After looking at your code, the problem is with your constraints.
