### ISSUE TITLE
Missing Days in Calendar 

### ISSUE THREAD

**Issue by prahaladm** [patchthecode/JTAppleCalendar#307]
After following the first part of the tutorial below (screenshot attached) is what I get.

1. Could someone suggest why am I missing several days ?
2. The numbering of the days (day 14, 15 are repeated twice) also seems to be incorrect.

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/4957156/23076052/d1d1f308-f564-11e6-9166-ae028b56cacb.png)

**Comment by patchthecode** [comment]
I think that maybe you didnt follow the tutorial correctly?

Here is the completed code for the tutorial ->>  https://github.com/patchthecode/CalendarTutorial
Let me know if i'm wrong and this turns out to be a real issue
If it does turn out to be a real bug, then we'll need to fix it.
Let me know.

**Comment by patchthecode** [comment]
Also, Can you provide me a zip file of the source code you have done?
Just zip the file, and drag the file into this chatbox to upload it here. Thanks.

**Comment by prahaladm** [comment]
Thank you for your help, I’ve manage to resolve the issue. This is a great calendar library, with a lot of flexibility.

Here is my desired view:
![desiredweekview](https://cloud.githubusercontent.com/assets/4957156/23089883/0ebd704c-f5b7-11e6-984b-9399192d9ec3.jpg)



Here is my current week view
![pastedgraphic-4](https://cloud.githubusercontent.com/assets/4957156/23089917/933f7234-f5b7-11e6-94c6-7f11b93c46d3.png)


1. How can I replace the “Day” text with the Day of the week i.e. (Sunday - S, Monday - M and so on)
2. How can I add selected Date at the Bottom of the week view ?

Thank you for your help!!

**Comment by patchthecode** [comment]
Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
> How can I replace the “Day” text with the Day of the week i.e. (Sunday - S, Monday - M and so on)

If you are trying to replicate the Apple style, then making the header is easy -> https://patchthecode.github.io/Headers/

> How can I add selected Date at the Bottom of the week view ?
This can simply be a UIView that is _outside_ the calendar.

**Comment by patchthecode** [comment]
Since the original issue is resolved, then i'll close this. But if you still need help then keep chatting. I will respond.

**Comment by prahaladm** [comment]
You are awesome, thank you so much.

**Comment by patchthecode** [comment]
Cheers 🍻
