### ISSUE TITLE
Showing event indicator on day cell

### ISSUE THREAD

**Issue by hmleit** [patchthecode/JTAppleCalendar#308]
Hello, Jay. I've seen some people with a similar issue, but I still can't figure out what to do.

I'm using your framework in my app and I'm having trouble with the cell selection.

When I open the calendar, I fetch the events from Core Data and, if the day has events, I show the event indicator on the cell.
The problem is: I'm fetching the events per day, so I was doing that on the willDisplayCell function, but this function is called after handleCellSelection, so I tried doing the same things directly on handleCellSelection, but that didn't work either. Some cells show the selection even though there are no events at the specific day.
The only thing I thought would work is adding a boolean property to the CellState struct called hasEvents, but I can't modify your files.

Here's my code (sorry if it's a bit messy)

```swift
func handleCellSelection(view: JTAppleDayCellView?, cellState: CellState) {
        
        guard let myCustomCell = view as? CellView  else {
            return
        }

        if cellState.dateBelongsTo == .thisMonth {
            myCustomCell.isUserInteractionEnabled = true
            myCustomCell.topLine.isHidden = false
        } else {
            myCustomCell.isUserInteractionEnabled = false
            myCustomCell.topLine.isHidden = true
        }
        
        let dateString = String(describing: cellState.date)
        let separatedStr = dateString.components(separatedBy: " ")
        
        DAO().fetchRecordsByDay(date: String(describing: separatedStr[0]))
        
        if AppData.sharedInstance.recordsByDay.count > 0 {
            recordsSaved.append(separatedStr[0])
        }
      
        if cellState.isSelected && cellState.dateBelongsTo == .thisMonth {
            
            selectedDate = cellState.date
            myCustomCell.selectedView.layer.cornerRadius =  17
            myCustomCell.selectedView.isHidden = false
            myCustomCell.eventIndicator.isHidden = true
            myCustomCell.eventIndicator.backgroundColor = beOkayGreen
            hideGoToRecordsButton()
            
            if recordsSaved.count > 0 {
                
                let cellStateDate = String(describing: cellState.date).components(separatedBy: " ")
                
                for date in recordsSaved {
                    
                    if date == cellStateDate[0] {
                       
                        myCustomCell.eventIndicator.isHidden = false
                        myCustomCell.eventIndicator.backgroundColor = white
                        
                        showGoToRecordsDetailsButton()
                    }
                }
            }
            
        } else {
            
            myCustomCell.selectedView.isHidden = true
            
            if recordsSaved.count > 0 {
                
                let cellStateDate = String(describing: cellState.date).components(separatedBy: " ")
                
                for date in recordsSaved {
                    
                    if date == cellStateDate[0] {
                       
                        myCustomCell.eventIndicator.backgroundColor = beOkayGreen
                        myCustomCell.eventIndicator.layer.cornerRadius = 2.5
                        myCustomCell.eventIndicator.isHidden = false
                    }
                }
                
            } else {
                myCustomCell.eventIndicator.isHidden = true
                hideGoToRecordsButton()
            }
        }
    }


```

**Comment by patchthecode** [comment]
Since many people has asked for this, I think i'll do a video or a posted answer on this.
FOr right now, i'm at work. I'll respond this weekend.

**Comment by hmleit** [comment]
Okay, looking forward to your response. Thank you very much!

**Comment by patchthecode** [comment]
@hmleit if youre online now. Join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Ok. I think i am having a hard time understanding how you want the calendar to be.

> The problem is: I'm fetching the events per day

So just to clarify, do you want the following to happen?

1. User taps a dateCell
2. You want to then fetchInfo from database
3. Update the cellView to reflect what you got from the database

If thats the case, then what you can do is have a dataSource (either an Array or Dictionary for example). If a dictionary (which will be faster), have a  **date** for the _key_ and have the actual **data** as the _value_.

When user taps the cell, then fetch from database and save your data in the dataSource.
Once your download is complete. Then simply do `calendarView.reloadData()` or `reloadDates` to refresh the calendar.

in your `willDisplayCell` function, simply do something like:
```swift
if let validData = dataSource[date] {
   // Then configure the dateCell to show the data
} else {
  // Configure the cell to hide the data
}
```

**Comment by hmleit** [comment]
Okay, I will try doing that. Thank you very much!

**Comment by patchthecode** [comment]
Jus tmake sure that the dates you store in the dictionary are of the same type as the dates you receive from the calendar. You can do this easily with a `DateFormatter`.
If you need further help let me know. Closing this now.
