### ISSUE TITLE
Printing incorrect Date in method didSelectDate

### ISSUE THREAD

**Issue by prahaladm** [patchthecode/JTAppleCalendar#309]
When I try to print the user selected date within the below function, I get a date 1 day lesser than the selected date. This happens even in the [calendar tutorial examples](https://github.com/patchthecode/CalendarTutorial)

Please suggest, How I could fix this issue ?

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleDayCellView?, cellState: CellState) {
        handleCellSelection(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        selectedDate.text = String(describing: date)
        print("Date \(date)")
    }
```

![incorrectdate](https://cloud.githubusercontent.com/assets/4957156/23091659/23733b64-f5e1-11e6-960d-0ff448d0b4f9.png)

**Comment by patchthecode** [comment]
Date is correct.
You just need to format it.
Let me know if the following helps you --> https://github.com/patchthecode/JTAppleCalendar/issues/252

When dealing with `Dates`, printing it to the console will give you incorrect results depending on your timeZone. Never simply `print` a date. The correct way to handle dates is to use `DateFormatters` if you want the correct date printed to console.

**Comment by patchthecode** [comment]
If you still need help on this, I'll be available in the morning.

**Comment by prahaladm** [comment]
Thanks again, I got it working by using the below code:

```
let formatter = DateFormatter()
formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
print("printing current Date\(formatter.string(from: date))")
```
