### ISSUE TITLE
Space Seen when using NavigationBar

### ISSUE THREAD

**Issue by miff** [patchthecode/JTAppleCalendar#31]
Hi,
Does somebody know how to get rid of this strange "top-margin" when use navigationController?

![simulator_screen_shot_28_05_2016_02_06_21](https://cloud.githubusercontent.com/assets/2439146/15624858/5c2d383e-2449-11e6-8a57-805799689efe.png)

Without navigation bar everything is ok.

Thanks,

**Comment by patchthecode** [comment]
1. Are you using version 3.0.1?
2. Are you using headers?
3. Are you doing anything out of the ordinary as shown in the sample app? (the image doesn't say much about the code)
4. Is it possible you can give provide a github same of your bugged calendar?

**Comment by miff** [comment]
Thanks,

1. Yes
2. No
3. No, basically it's copy/paste
4. Horizontal

https://gist.github.com/miff/b6cd6ee11dc04aee6513a1de6f7263c4

**Comment by patchthecode** [comment]
There is nothing wrong with the code you have done. Could you just put the entire project into a test git repository? or a zip file that I can download and run? I suspect your problem is not code related.

**Comment by miff** [comment]
[percal.zip](https://github.com/patchthecode/JTAppleCalendar/files/288031/percal.zip)

**Comment by patchthecode** [comment]
thanks. Checking it out

**Comment by miff** [comment]
Thank you! :)

**Comment by miff** [comment]
One more thing,
I start 'clean' project to be sure is everything ok, but more strange thing:
- The problem above stay the same
- and new one, running in simulator ok, but if you try on actual device throw bunch of errors

Here is attachment
[Period Cal.zip](https://github.com/patchthecode/JTAppleCalendar/files/288049/Period.Cal.zip)

Thanks again

**Comment by patchthecode** [comment]
Hmm. Any chance we can chat here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Hey after looking into your problem, i see this in [Apple Documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/index.html#//apple_ref/occ/instp/UIViewController/automaticallyAdjustsScrollViewInsets)

<img width="729" alt="screen shot 2016-05-28 at 6 32 18 pm" src="https://cloud.githubusercontent.com/assets/2439146/15630883/90e0078c-2502-11e6-8e55-08eae93d4a2c.png">

Is it possible for your app that you can deselect this option only for this viewController?
![scrollvead](https://cloud.githubusercontent.com/assets/2439146/15630895/3556af32-2503-11e6-8eb3-f9997fc8bb8e.png)

This will fix your problem.

**Comment by patchthecode** [comment]
What other errors is the calendar throwing when you run it on the iPhone?

**Comment by patchthecode** [comment]
Also 
```
	override func viewDidLayoutSubviews() {
		super.viewDidLayoutSubviews()
		self.calendarView.frame = self.calendarView.frame // This is not needed
	}
```

**Comment by miff** [comment]
Thanks! :) Solved the strange space.

For other errors, it's only happened  to second project (2nd zip)

Swift cannot find declaration for JTAppleDayCellView class, but errors throw **only** when run on device, in simulators (any) it fine

<img width="546" alt="screen shot 2016-05-29 at 10 37 49" src="https://cloud.githubusercontent.com/assets/469459/15632154/96fdea3a-2589-11e6-8eed-e9d6fbb76d28.png">

**Comment by patchthecode** [comment]
As this is a separate issue lets track it here https://github.com/patchthecode/JTAppleCalendar/issues/32
