### ISSUE TITLE
Start Date for Week View

### ISSUE THREAD

**Issue by prahaladm** [patchthecode/JTAppleCalendar#310]
@patchthecode 

When I set the start date (18th Feb 2017) for the week view (no of rows: 1),  Below is what I get (where it shows start of the month ), but I actually want 18th to be displayed in the week view, How can I do this ?
How can I also have this date pre-selected on load?

![startdateinweek](https://cloud.githubusercontent.com/assets/4957156/23093377/35c2c78c-f607-11e6-8bea-f1280c1b6007.png)

**Comment by patchthecode** [comment]
> How can I also have this date pre-selected on load?

`calendarView.selectDate(date)` inside `viewDidLoad()`

**Comment by prahaladm** [comment]
Your support is is just terrific, thanks again.

**Comment by iOSUser110** [comment]
And if want the selected date to be at first position of the row ??  instead of 3rd position ??

**Comment by patchthecode** [comment]
@iOSUser110  then simply capture the `calendarView.visibleDates` and then select the first one.
