### ISSUE TITLE
Today's date selected

### ISSUE THREAD

**Issue by hmleit** [patchthecode/JTAppleCalendar#313]
Hello, Jay, me again!

I'm having another problem and I would really appreciate your help.
When I open my calendar I want the current day to start selected and then, if I select any other day, the current day's selection will disappear. What's the best way to do this?

Thanks in advance.

**Comment by patchthecode** [comment]
> When I open my calendar I want the current day to start selected

in your `viewDidload` 
`calendarView.selectDates([Date()])`

to handle selection, look at the tutorial [part2](https://patchthecode.github.io/MainTutorial2)
[Part1](https://patchthecode.github.io/MainTutorial) also helps

**Comment by patchthecode** [comment]
Let me know if youre still stuck
