### ISSUE TITLE
No spacing for header, strange z-positions

### ISSUE THREAD

**Issue by m-b-davis** [patchthecode/JTAppleCalendar#314]
I have created a header cell like this 

![image](https://cloud.githubusercontent.com/assets/15704216/23129825/172779c8-f77c-11e6-869b-21ed9b023273.png)

Created a custom class, conformed to JTAppleHeaderView, and registered the xib in viewDidLoad

![image](https://cloud.githubusercontent.com/assets/15704216/23129992/a4268aa8-f77c-11e6-809d-c6e6dd14dbaf.png)

Implemented delegate methods

![image](https://cloud.githubusercontent.com/assets/15704216/23130047/e4445eda-f77c-11e6-880c-4436647c1384.png)

But I can't seem to get any space to show for the header within the calendar:

![image](https://cloud.githubusercontent.com/assets/15704216/23129817/10d951b8-f77c-11e6-996a-9cf3ada1c081.png)

Different months seem to have different z-order of views too

![image](https://cloud.githubusercontent.com/assets/15704216/23129943/72b8579e-f77c-11e6-883f-cffd5bb3f1b4.png)

**Comment by patchthecode** [comment]
Can you send me a zipped copy of that sample code?
you can drag the zip file in this chat box.

**Comment by patchthecode** [comment]
Ok, you have old code, with a newer version of the library.
The names of your functions are from an older version, therefore your functions are not even called.

Look here for the updated function on the tutorial site -> [here](https://patchthecode.github.io/Headers/)

**Comment by patchthecode** [comment]
If you still have issues, let me know.
closing this 👍

**Comment by m-b-davis** [comment]
Ok thank you!
