### ISSUE TITLE
Align header label with first day of the month

### ISSUE THREAD

**Issue by thalissonrosa** [patchthecode/JTAppleCalendar#315]
Hi, is it possible to align a label in the header with the first day of the month? For example:
![screen shot 2017-02-20 at 2 44 55 pm](https://cloud.githubusercontent.com/assets/5844845/23136416/6b5ea9ae-f77b-11e6-9bd7-23ff418aab1a.png)

As you can see, the name of the month is aligned with the first day. 

I found a function called numberOfPreDatesForMonth that I could use to calculate the constraint for the leading offset. I also tried visibleDates(), but I'm getting some duplicate entries on the indates array.

Am I missing something here? Thanks!

**Comment by patchthecode** [comment]
hmm. ok. here are some things.

1. `numberOfPreDatesForMonth` is private. Not reccomended for you to use it :)
2. `visibleDates().preDates` should only give you predates. There should not be duplicate entries in there. (unless you are using an old version of JTAppleCalendar when i didn't fix that problem yet). That said, I am not sure how `visibleDates` can help you here.

It is east to configure the cells that is looks something like this 

![simulator screen shot feb 20 2017 10 21 00 am](https://cloud.githubusercontent.com/assets/2439146/23137381/81b32326-f756-11e6-9bfe-9acd3700c115.png)

You can design the 1st cell any how you want. 
But it seems like you are looking to make a _separate_ label hover above the cell. I'm i correct?

**Comment by patchthecode** [comment]
If this is what you want, I think that you can accomplish it by creating a [Inside Header](https://patchthecode.github.io/Headers/) view with 7 labels in a stack view line this
[  L1 | L2  | L3  | L4  | L5  | L6  | L7  ]

The header will have 7 labels.
Now when you configure the header, find out on what day of the week the 1st day is.
If it is Sunday, then L1 = visible and all others = inVisible.
If it is Monday, then L2 = visible and all others = inVisible. etc etc etc

The labels can have the text of the month :)
This should work.
Let me know what you think of the idea.

**Comment by thalissonrosa** [comment]
I downloaded the example app and made some changes and got this:
![screen shot 2017-02-20 at 4 01 05 pm](https://cloud.githubusercontent.com/assets/5844845/23138454/507f26d0-f786-11e6-9e64-49f54fffc946.png)

Basically, it's just a vertical calendar with itemSize = 40 and scrollingMode = .none. 
When the app is on the same state as the screenshot, visibleDates().preDates contains 8 elements:
![screen shot 2017-02-20 at 4 09 29 pm](https://cloud.githubusercontent.com/assets/5844845/23138586/085e0870-f787-11e6-9f86-584b2e3a7d89.png)

To position the label, I can use your approach or I can change the constraint. My only problem is getting the amount of indates on a given month. Right now I'm using version 6.1.2, am I supposed to be using a newer version?

Thanks!

**Comment by patchthecode** [comment]
Ok. i see why you re getting two types of predates. That is because you have 2 months on the screen (because you made the itemSize smaller).

But you do not need to use preDates to accomplish this. Headers has the delegate function called -> 

```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplaySectionHeader header: JTAppleHeaderView, range: (start: Date, end: Date), identifier: String) {
```

With this, it gives you the `range.start` date for the month, and the `range.end` date.
With this you can know what the date for the month header is.
Once you know the date, you can now do the visibility thing i mentioned above. 

let me know how it goes.

**Comment by patchthecode** [comment]
closing issue. If you still need more help with this, then let me know.
