### ISSUE TITLE
Problem changing device orientation

### ISSUE THREAD

**Issue by dbmrq** [patchthecode/JTAppleCalendar#316]
Hello, Jay. :)

I don't know if I'm missing something, but I'm trying to get my app to support multiple orientations and the calendar won't update properly when the device is rotated.

Here's how it looks at first:

![simulator screen shot 20 de fev de 2017 19 42 18](https://cloud.githubusercontent.com/assets/15813674/23144204/ce621954-f7a4-11e6-82df-e5233fcbbddc.png)

Then I rotate the device and:

![simulator screen shot 20 de fev de 2017 19 42 23](https://cloud.githubusercontent.com/assets/15813674/23144210/d907a54a-f7a4-11e6-8ae6-d6398f34675a.png)

When I scroll to a different date this appears to be fixed, so I'm scrolling at `didRotate()`:

![simulator screen shot 20 de fev de 2017 19 42 32](https://cloud.githubusercontent.com/assets/15813674/23144350/b880e7b8-f7a5-11e6-978e-dd0c20adbf03.png)

But even if it appears to be fixed at first, when I scroll to a different month and try to select a date the calendar breaks again. Any ideas?

**Comment by patchthecode** [comment]
Alright, i'll check this out later

**Comment by patchthecode** [comment]
Will check it once i finish work.
One thing, what is your scrollDirection?
And is it happening on 6.1.2? or masterBranch?

**Comment by dbmrq** [comment]
Horizontal. And it's happening on master. I didn't check 6.1.2, I assumed it's the same in that regard.

**Comment by patchthecode** [comment]
OK. Back. I was working on orientation updates this morning. Just made a push to master branch.

**Comment by dbmrq** [comment]
Uhm, it looks like it's still the same here. :/

**Comment by dbmrq** [comment]
I cloned the master branch and gave it a try in the demo app. The problem doesn't *always* happen, I'm not sure why… but it does happen:

![simulator screen shot 21 de fev de 2017 01 22 03](https://cloud.githubusercontent.com/assets/15813674/23150729/842d3118-f7d4-11e6-8aed-b42cfbbd36c9.png)

To reproduce you can start the sample app, select a date and do `cmd-right` (the command key and the right arrow key together) followed by `cmd-left`. If it doesn't happen, scroll to the next month, select a different date and do it again. And so on, keep scrolling and changing the orientation, eventually it breaks. In my app it happens every time, in the example it only happens sometimes, I'm not sure why.

**Comment by patchthecode** [comment]
ok. checking this now.

**Comment by patchthecode** [comment]
Do i do the `cmd-r` and the `cmd-l` quickly? or does that not matter

**Comment by patchthecode** [comment]
-> https://gitter.im/patchthecode/JTAppleCalendar
If youre free

**Comment by dbmrq** [comment]
I'm there.

But it doesn't matter if the `cmd-r`/`cmd-l` are done quickly… and what's unexpected about the image is that the calendar would settle showing half of each month at the same time, isn't it?

**Comment by patchthecode** [comment]
In this function, can you place a print statement at the end link this?

```swift
func setMinVisibleDate() { // jt101 for setting proposal
        let minIndices = minimumVisibleIndexPaths()
        switch (minIndices.headerIndex, minIndices.cellInfo.indexPath) {
        case (.some(let path), nil):
            lastIndexOffset = (path, UICollectionElementCategory.supplementaryView)
        case (nil, .some(let path)):
            lastIndexOffset = (path, UICollectionElementCategory.cell)
        case (.some(let hPath), (.some(let cPath))):
            if hPath <= cPath {
                lastIndexOffset = (hPath, UICollectionElementCategory.supplementaryView)
            } else {
                lastIndexOffset = (cPath, UICollectionElementCategory.cell)
            }
        default:
            break
        }
        print(lastIndexOffset)
    }
```

It should be saving the last index right before orientation change.
If it is nil, then something is wrong.

**Comment by dbmrq** [comment]
In my app, you mean? I'm using Carthage, so I'll have to include the source
directly. Now I'm going to bed, it's 3 am here and I'll have to be up
early, but I can do it tomorrow if that's alright. How about the demo app,
though? Did it work there?

Em ter, 21 de fev de 2017 às 02:53, JTAppleCalendar <
notifications@github.com> escreveu:

**Comment by patchthecode** [comment]
Yes i am seeing the error there. But I know the reason why it is happening there now.
I just want to confirm if the error I am getting is the same that you are getting.

**Comment by dbmrq** [comment]
Hey, sorry for the delay.
The problem is still happening with the latest commit. I did what you said and the value of `lastIndexOffset` is *not* nil when I change the orientation. Rather, if I just go `cmd-r`, `cmd-l`, `cmd-r`, `cmd-l`,  the value is different almost every time the orientation changes:

```
Optional(([54, 1], __C.UICollectionElementCategory))
Optional(([54, 1], __C.UICollectionElementCategory))
Optional(([52, 6], __C.UICollectionElementCategory))
Optional(([54, 0], __C.UICollectionElementCategory))
Optional(([54, 4], __C.UICollectionElementCategory))
Optional(([54, 4], __C.UICollectionElementCategory))
Optional(([53, 2], __C.UICollectionElementCategory))
```

**Comment by patchthecode** [comment]
Ok. I'll have to share screen with you one last time after work.
Mine does not behave like this.
Will contact you again in about 3.5 hrs

**Comment by dbmrq** [comment]
No problem, thanks for your help. :)

**Comment by patchthecode** [comment]
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
made changes -> https://github.com/patchthecode/JTOrientationTest

**Comment by dbmrq** [comment]
Ok, I'll give it a try soon... but I just took a look at your commit and:

```swift
        guard let completionHandler = completionHandler else { return }
        self.completionHandler = nil
        completionHandler()
```

Why call `completionHandler()` right after setting it to nil? And why the `guard let` in the first place then?

**Comment by dbmrq** [comment]
By the way, I don't even know what's happening there, I just took a quick glance at the code, but I think you could replace those three lines with:

```swift
        completionHandler?()
        self.completionHandler = nil
```

**Comment by patchthecode** [comment]
I did this as safety.
Let me know if my logic is wrong.

```swift
class CustomCollectionView: UICollectionView {
    var completionHandler: (() -> Void)? = nil
    
    override func layoutSubviews() {
        super.layoutSubviews()  // Layout subviews called
        completionHandler?()     // user had a completion handler, that in-turn again calls layoutSubviews. Loop?
        self.completionHandler = nil
    }
}
```
VS
```swift
class CustomCollectionView: UICollectionView {
    var completionHandler: (() -> Void)? = nil
    
    override func layoutSubviews() {
        super.layoutSubviews()       // Layout subviews called
        guard let completionHandler = completionHandler else { return } // If completion handler = nil, then return. If not, then save it in a local variable
        self.completionHandler = nil // Set the class completion handler to nil
        completionHandler()          // Call the local version. If layoutSubviews is again called, then it will be nil
    }
}
```

Let me know if my logic is incorrect

**Comment by dbmrq** [comment]
Oh, ok, I just got the local and global versions mixed up, sorry. I'll try the latest version now.

**Comment by dbmrq** [comment]
Alright, it's looking good so far!

**Comment by patchthecode** [comment]
Ok i will begin making the code neater.
And begin migrating changes to master.

**Comment by dbmrq** [comment]
Awesome, thanks. I just noticed another problem, I think it's better if I open another issue, though, I'll do that now.

**Comment by patchthecode** [comment]
Fixed on latest master branch.
closing.

**Comment by namuthan** [comment]
Hi, I am having the same problem. I followed the [guide](https://patchthecode.github.io/) to create the calendar with ipad. Here are the screen shots of it.

Portrait

![screen shot 2017-04-03 at 4 29 58 pm](https://cloud.githubusercontent.com/assets/6484468/24665701/70412e08-191b-11e7-9381-700cad02ca72.png)

Landscape:

![screen shot 2017-04-04 at 9 44 36 am](https://cloud.githubusercontent.com/assets/6484468/24665742/8a2d518e-191b-11e7-9e8e-ea33689bbf1b.png)

I am guessing you need to call the following whenever the orientation changes but I don't where to add it. 

`        calendarview.collectionViewLayout.invalidateLayout()
`

Also, it is not exposed as api. 

I am using this version of JTAppleCalendar 

`    pod 'JTAppleCalendar', '~> 6.1'
`

Thanks

**Comment by patchthecode** [comment]
@namuthan can you try updating to version 6.1.6 ?

**Comment by namuthan** [comment]
I tried the 6.1.6 version, and the same issue persist.

**Comment by patchthecode** [comment]
@namuthan 
[JTAppleCalendarExample.zip](https://github.com/patchthecode/JTAppleCalendar/files/900863/JTAppleCalendarExample.zip)

I've updated your project with version 7.0
Does it work as expected?

**Comment by namuthan** [comment]
It does work as expected 👍
