### ISSUE TITLE
select multiple dates

### ISSUE THREAD

**Issue by tr03lf** [patchthecode/JTAppleCalendar#317]
Sorry for such a newb question, but i couldn't wrap my head around how to select multiple dates. In the tutorial as well as in the example: whenever i select a second date, the first date gets deselected. Of course i could work around this visually, but as long as `didDeselectDate` is called, the `selectedDates` property of `JTAppleCalendarView` always contains only one item. that doesn't seem like the way it is meant to be...what am I missing here?
I'm working with the latest stable version 6.1.2.

**Comment by patchthecode** [comment]
`calendarView.allowsMultipleSelection = true` 
Will close this.
If you have any further issues, then just ask :)

**Comment by JFSene** [comment]
I need to select 2 dates to send to my server, but I've been struggling to save both dates, is there anywhere an example I can look into?

**Comment by patchthecode** [comment]
as here https://gitter.im/patchthecode/JTAppleCalendar
