### ISSUE TITLE
Code works in simulator. Error on launch on Device

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#32]
From User: @miff

Thanks! :) Solved the strange space.

For other errors, it's only happened  to second project (2nd zip)

Swift cannot find declaration for JTAppleDayCellView class, but errors throw **only** when run on device, in simulators (any) it fine

<img width="546" alt="screen shot 2016-05-29 at 10 37 49" src="https://cloud.githubusercontent.com/assets/469459/15632154/96fdea3a-2589-11e6-8eed-e9d6fbb76d28.png">

**Comment by patchthecode** [comment]
I ran my code on device and it works.
No Errors thrown.

I see that youre not setting up the using cocoapods in the second file you game me?

**Comment by miff** [comment]
Yes, I try only to import JTAppleCalendar.framework in embed binary, but not work on device like I say it. This is my first project that use pods, so i think maybe I use it like just import it, (eg Realm ...)
But now i see that must be set with cocoa pods  :)
