### ISSUE TITLE
Enable scrolling in CalendarView

### ISSUE THREAD

**Issue by gaurav38** [patchthecode/JTAppleCalendar#322]
Hello,

I have followed all the steps in the quick tutorial and my calendar seems to be showing correctly. However, I'm not able to scroll the calendar to other months. Do I have to set some values to enable this?

Thanks,
Gaurav

**Comment by patchthecode** [comment]
you do not have to enable scrolling. It is automatically enabled by default.
can you send me a zip file of the project you have done? You can drag the file into this chat box.

**Comment by gaurav38** [comment]
My project has a lot of pods so here's my repo: https://github.com/gaurav38/Travelogue

**Comment by gaurav38** [comment]
Oh I figured out the issue in my code. I set the configuration parameters to the start and end of the current month. I changed to start of the month to 2 years later and it worked. Thanks for looking into it :)

**Comment by patchthecode** [comment]
Awsome. Glad you figured it out.
