### ISSUE TITLE
How to disable scroll animation for header?

### ISSUE THREAD

**Issue by f15handch1p5** [patchthecode/JTAppleCalendar#326]
Hi, i'm just wandering if there's an easy way to disable the scroll animation for the header, i want to keep the scrolling for the actual cell views themselves, but i just want the month header to update automatically when the user scrolls instead of animating with the cells. How would i go about doing that? Thanks

**Comment by patchthecode** [comment]
The tutorials on the main page explain how to do this -> https://patchthecode.github.io/

Specifically, the tutorial about headers -> https://patchthecode.github.io/Headers
Let me know if you are stlll stuck and i'll help.
