### ISSUE TITLE
Crashing when randomly selecting and de-selecting date.

### ISSUE THREAD

**Issue by Nidhee** [patchthecode/JTAppleCalendar#327]
Hi,

I am using version 6.1.4.
I have hide dates which are not in current month.
Muliple selection of date is disable.

When I am moving forward and backward in months, also selecting an deselecting date. 
It crashes  at -

deleteCellFromSelectedSetIfSelected
fatal error: Index out of range

IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.1.3
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Issue found.
Currently working on a fix.

**Comment by patchthecode** [comment]
Fix done with commit -> https://github.com/patchthecode/JTAppleCalendar/commit/f6e8ec29f8fa18a56bc0a0d1113eae845fbab654

**Comment by patchthecode** [comment]
version 6.1.5 released.
Closing issue
