### ISSUE TITLE
Only 1, 2, 3, & 6 are allowed, Why not 5?

### ISSUE THREAD

**Issue by whoooami** [patchthecode/JTAppleCalendar#328]
like title. Thx.

**Comment by patchthecode** [comment]
if you want 5 rows, then what will you do if the number of rows for a particular month = 6?
and
if you want 6 rows, then what will you do if the number of rows for a particular month = 5?

Therefore the ability to create a dynamic layout is not set by the numberOfRows.
If you want a dynamic layout then in your `configureCalendar` function, set the `generateOutDates` parameter to: `.tillEndOfRow`

**Comment by patchthecode** [comment]
closing this issue, but let me know if you still need help.

**Comment by willard1218** [comment]
I also would like dynamic layout,
But can I let cell of height fixed?

for example:
if the month has 5 rows, then cell height = 50, collectionView = 50 * 5 = 250.
if the month has 6 rows, then cell height = 50, collectionView = 50 * 6 = 300.

**Comment by patchthecode** [comment]
Are you going to change the height of the calendar view's frame when the month has 5 rows?

**Comment by willard1218** [comment]
Yes, I have calendarViewHeightConstraint to adjust my calendarViewHeight.
For example:

```swift
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        // ...
        adjustCalendarViewHeight(higher: (visibleDates.outdates.count < 7))
  }

 func adjustCalendarViewHeight(higher: Bool) {
            UIView.animate(withDuration: 0.25) { [unowned self] in
            let multiplier : CGFloat = (higher) ? 6.0/7 : 5.0/7   
            self.calendarViewHeightConstraint.constant = self.view.frame.width * multiplier
            self.view.layoutIfNeeded()
        }
  }
```

**Comment by patchthecode** [comment]
@willard1218 ok, when the calendar's height change, the cell's height should adjust to what you want?

Currently the cell's height is determined by the height of the calendar (for a horizontal calendar). Unless i misunderstood the real problem you are having?

**Comment by willard1218** [comment]
Yes, just like AppleCalender, the cell's height is fixed,
But calendar's height change when numOfRow change.

And cell's height is always fixed.

**Comment by patchthecode** [comment]
can you join me here? https://gitter.im/patchthecode/JTAppleCalendar
