### ISSUE TITLE
import JTAppleCalendar causes a weird problem

### ISSUE THREAD

**Issue by kaanctn** [patchthecode/JTAppleCalendar#329]
Hi,

I am trying to use JTAppleCalendar but when i import the module, xcode gives me an error about another module "Opening import file for module 'WebKit': Permission denied"
When i delete the line "import JTAppleCalendar" everything works fine.

Have you encountered a similar problem?

Thx.

**Comment by patchthecode** [comment]
Hmm...
1. can you paste me what you are putting in your cocoaPod?
2. can yo do a ` pod --version` on your console and tell me the version?

**Comment by kaanctn** [comment]
Actually i am using carthage. 
I updated carthage to version 0.20.0, i don't know how but this solved my problem.
Sorry for the trouble :)
Thx.
