### ISSUE TITLE
Question about scrolling

### ISSUE THREAD

**Issue by gilgameshex** [patchthecode/JTAppleCalendar#331]
I've read the tutorial about how I want my users to scroll the calendar, however, I am not quite sure about which part of the program I should add the code to. Thank!

**Comment by patchthecode** [comment]
The calendar is already made scrollable.
The only way the calendar will not scroll is:

1. Your `startDate` and `endDate` is in the same month (therefore there is nothing to scroll)

Can you tell me what version of the calendar you are using, and what is the start and end date?

**Comment by gilgameshex** [comment]
@patchthecode, thanks for the reply, I am not quite sure what you mean by version of the calendar, I am currently following your tutorial and I've got to the DateCellConfigurations, the framework is in 6.0, i think. 
My startDate for my program is  '2017 01 01' and my endDate is '2100 01 01'
Thanks

**Comment by patchthecode** [comment]
your calendar should already be scrolling.
if it is not, then can you provide a zipped stripped down version of your project?

You can drag the file inside this chatbox

**Comment by gilgameshex** [comment]
@patchthecode  Thanks for the reply, yes it is scrolling, but I want to change the mode of scrolling 
https://patchthecode.github.io/CalendarScrolling/
However, I don't know where I should put this code.
Thanks!

**Comment by patchthecode** [comment]
the scrolling code can be put in your `viewDidLoad()` function. Let me know if it works.

**Comment by gilgameshex** [comment]
@patchthecode Yes it is working, thanks so much for the framework and your swift reply. :)

**Comment by patchthecode** [comment]
Awesome. closing this issue.
