### ISSUE TITLE
Editable CalendarView (UICollectionView) Content Insets

### ISSUE THREAD

**Issue by iMacHumphries** [patchthecode/JTAppleCalendar#332]
I may be missing something obviously easy, but currently I cannot find a way to edit the underlying UICollectionView Insets.  I am trying to make an offset for the scrollTo(date: ) function so that I can have a transparent Navigation Bar overtop of my calendar view.

Currently looks like this when I try to scroll to today's date:
![image1](https://cloud.githubusercontent.com/assets/10065149/23576524/e1169190-0075-11e7-9225-32cf28df83a7.PNG)

Trying to get it to look like this:
![image2](https://cloud.githubusercontent.com/assets/10065149/23576522/daf2150a-0075-11e7-92ef-cb71dcd339b7.PNG)

I love your calendar!  It is by far the best pod I have ever used, and it blows every other calendar pod out of the water!  

Thanks for your help, 
Ben

**Comment by patchthecode** [comment]
Thank you for the compliment. I want to to be the best on github.

Concerning your issue.
1. Confirming that you have vertical calendar?
2. Which pod version are you using?
3. Have you set a `scrollingMode`? Or are you using the default.
4. Have you set an `itemSize` for the calendar?
5. Are you using the calendar with a UINavigationController? 

I need to know these information in order to replicate your issue.
The calendar should scroll to the date that you want. It should not be hidden behind a view.

**Comment by iMacHumphries** [comment]
1. Yep!
2.  JTAppleCalendar (6.1.2)
3.  set to .none
4. I set the itemSize = calendar.frame.size.width / 7  * 1.62
5. Yep! 

The calendar is setup through interface builder to be the exact same size as the view.

My calendar view is under my navigation bar on purpose (I like the translucent effect), and your calendar library is scrolling to the correct area if there were no navigation bar.

**Comment by iMacHumphries** [comment]
LooLo

**Comment by iMacHumphries** [comment]
it is important to note I have a custom sized navigation bar.  I believe this is throwing off the automatic scroll view inset adjustment.   I also believe if you allow us to edit the underlying collection view contentInsets that should fix the problem.

**Comment by patchthecode** [comment]
alright. I will look at this right now.
just awoke.

**Comment by patchthecode** [comment]
Just one thought have you tried unselecting this?
<img width="264" alt="screen shot 2017-03-04 at 7 39 37 am" src="https://cloud.githubusercontent.com/assets/2439146/23579987/d1c0b21a-00ad-11e7-9c09-17dfa5e92839.png">

Click on the viewcontroller that contains the calendarView and unselect this.
Sometimes you maybe also need to unselect it on the parent view controllers of the view controller all the way up the stack. Can you test this and let me know?

**Comment by iMacHumphries** [comment]
Hey that is a pretty good looking checkbox.  I will check on that later today.  Thanks for looking into this!

**Comment by patchthecode** [comment]
By the way, your headers are always centered. Why not try making the header right above the first of the month like this -> https://github.com/patchthecode/JTAppleCalendar/issues/315

**Comment by iMacHumphries** [comment]
Okay so I tried the layout Adjust Scroll View Insets and It didn't change anything.  Also, I have the header centered over the first day of the month, it just is buggy sometimes, I might need to move the centering logic somewhere other than willDisplaySectionHeader.

**Comment by iMacHumphries** [comment]
Okay so layout Adjust Scroll View Insets unchecked makes February (the first month) hidden under the nav bar and still does not fix scroll to date:

![image1](https://cloud.githubusercontent.com/assets/10065149/23584701/2178a6da-0137-11e7-805c-a9563cc9c10b.PNG)
(I scrolled to the very top in both images)


 With the Adjust Scroll View Insets checked: (you can see feb)
![image1](https://cloud.githubusercontent.com/assets/10065149/23584695/f918c760-0136-11e7-9edd-468917b52731.PNG)


Regardless of Adjust Scroll View Insets checked or unchecked, scrolling to date yields:
![image2](https://cloud.githubusercontent.com/assets/10065149/23584703/323e1478-0137-11e7-8d21-2be1becbe2e3.PNG)


But hey it is 12:06AM and it is now working for March 5th, so that is good.  Just a little messed up for the first week.

**Comment by iMacHumphries** [comment]
By the way this calendar is for a workout app, and each number inside the circle represents how many pushups the user did today.  Obviously I am pretty ripped since I totally did 263 pushups on Feb 23... ;P

**Comment by patchthecode** [comment]
ok. This is happening because you have set your `scrollMode` to `.none`
It scrolled your date correctly. But the problem is the the library does not know that you have a UINavBar there. Hmm.. I i'm looking into the making the inset available as you have said.

Looking into it.

**Comment by iMacHumphries** [comment]
Thanks for looking into that for me, I could see you possibly adding a new ScrollMode that is something like:
```
case nonStopToCell(withResistance: CGFloat, offset: CGFloat?)
```

The design uses nibs and is modeled after Apple's Activity app 😁.

**Comment by patchthecode** [comment]
OK, will work on this on the weekend. I should have an update for you by then.
I'll add an option to set an extra offset on the `scrollToDate` function

**Comment by patchthecode** [comment]
@iMacHumphries i have finished this, but i had one question about the insets.
Couldnt you just make the Calendar view's top to be directly under that header's bottom instead of under it?

**Comment by patchthecode** [comment]
If so, i think i'll remove this feature.
