### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mohammadalijf** [patchthecode/JTAppleCalendar#333]
hi, im using your pod in my project to create a simple calendar and im using latest version.
the problem is when i use instrument to check my leaks i've got lots of memory leak from the pod. 
i also tried the example project still got memory leaks.
the following screen shot is from profiling the example project.
![screen shot 2017-03-05 at 9 48 57 am](https://cloud.githubusercontent.com/assets/7884637/23585077/259ee164-0189-11e7-8985-4ae91a7c249f.png)

**Comment by patchthecode** [comment]
checking this now.

**Comment by patchthecode** [comment]
Leaks fixed -> https://github.com/patchthecode/JTAppleCalendar/commit/f3763723198c89498dfe49706aaaaf51dffbc211

One more leak to fix.

**Comment by patchthecode** [comment]
Seems that the final leak is an [Apple Bug](http://stackoverflow.com/questions/42642249/swift-leak-even-when-unowned-is-used-with-protocol-in-small-code-example).

Looking for a work around now.

**Comment by patchthecode** [comment]
All leaks fixed.

**Comment by mohammadalijf** [comment]
thank you. i will test master branch and report back

**Comment by patchthecode** [comment]
@mohammadalijf I have a weird iss that i am looking into however.

I use XCode 8.3 Beta, iOS 10.3 and there are no leaks.

But When I use Xcode 8.2, iOS 10.2, there are leaks.
Also I found an XCode bug causing the leaks (i have shown you the link above).

I am now looking into why there are leaks for iOS 10.2 Xcode 8.2

**Comment by mohammadalijf** [comment]
still got UIDeviceRGBColor leak which is somehow normal because swift will cache colors for future usage (mostly instrument bug i guess).
also i found some weird leaks when i'm using arrays and dictionaries with Xcode 8.2 
you can find these kind of leaks in pods like Alamofire etc.

i guess we should wait for Xcode 8.3 till we get a totally leak free apps.

**Comment by patchthecode** [comment]
I believe so.
Because I can assure you that Xcode 8.3 with JTAppleCalendar has no leaks.

**Comment by mohammadalijf** [comment]
thank you for such a quick issue fix

**Comment by patchthecode** [comment]
closing issue
released 6.1.6
