### ISSUE TITLE
didScrollToDateSegmentWith is called automatically after didSelectDate

### ISSUE THREAD

**Issue by Nidhee** [patchthecode/JTAppleCalendar#334]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

I am using 6.1.5,
In viewDidLoad method, I have scrolled calendar to current date - 

>  self.jtCalendarView.scrollToDate(Date(), triggerScrollToDateDelegate: true, animateScroll: false)

Which calls delegate didScrollToDateSegmentWith, in which I have API call for events which populates data. 

Now,whenever I select a cell for first time didSelectDate() delegate is called. Inside which I have some computations. After this delegate, didScrollToDateSegmentWith method is called here, I am not able to figure it out why it is called again. And it happens for the first cell I selected after calendar is setup. 

1. Are you using the latest version of JTAppleCalendar? Latest version is currently 6.1.5
2. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
3. Looking for some feature you cant find? Than have you already looked at the *UserInteractionFunctions.swift* file?
It has every function that a user is able to do.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
This bug was fixed on master branch i believe.
Can you test the master branch?

put this in your pod file
`pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'`

then do `pod install`
Let me know if this works

**Comment by Nidhee** [comment]
I update to this pod, got version 6.1.5
didScrollToDateSegmentWith is not calling, when I have scrollToDate inside viewdidload()

**Comment by patchthecode** [comment]
try deleting pod, the run `pod install`
If its still not working after this, then i'll look into this tomorrow.
This should be working correctly.

**Comment by patchthecode** [comment]
try it now.

**Comment by Nidhee** [comment]
okay. Trying

**Comment by Nidhee** [comment]
Its working now !! 👍  
Thank you.

**Comment by patchthecode** [comment]
awsome.
