### ISSUE TITLE
Issue with time zones

### ISSUE THREAD

**Issue by Nemely** [patchthecode/JTAppleCalendar#335]
Hello,

I'm having issue with time zones I believe. When I click on a date in the calendar, say April 15th, the date variable in the didSelectDate function returns April 14th at 11 pm. If I select a date at the end of the month, say April 22nd, I get returned April 21st at 10 pm. What am I doing wrong?

**Comment by patchthecode** [comment]
Many people have asked this.
So I will just leave a link to the discussion here -> https://github.com/patchthecode/JTAppleCalendar/issues/252

Let me know if it has resolved your issue.

**Comment by Nemely** [comment]
Thanks a lot for your help! That was an easy fix!

**Comment by patchthecode** [comment]
You're welcome :)
