### ISSUE TITLE
Issues about headers

### ISSUE THREAD

**Issue by gilgameshex** [patchthecode/JTAppleCalendar#336]
HI, I have a problem about using multiple headers, I have followed the tutorial you created and also your sample code, but I still ended up failing. I have attached a screenshot the code of my header and also the screenshot when the program crashes. Thanks!
** both headers are registered to view controller
<img width="1440" alt="screen shot 2017-03-08 at 10 47 31 am" src="https://cloud.githubusercontent.com/assets/23056172/23701053/00cb5f50-03ed-11e7-86b1-9ccdc7da560b.png">
<img width="1440" alt="screen shot 2017-03-08 at 10 44 04 am" src="https://cloud.githubusercontent.com/assets/23056172/23701052/00caa696-03ed-11e7-8fb5-9490aadf94e9.png">

**Comment by patchthecode** [comment]
can you paste the text of the crash?

**Comment by gilgameshex** [comment]
<img width="1440" alt="screen shot 2017-03-08 at 1 33 27 pm" src="https://cloud.githubusercontent.com/assets/23056172/23705903/cfcf2d98-0403-11e7-8a8b-d62c0e4900ed.png">
Here, thanks!

**Comment by patchthecode** [comment]
Hey, Images are ok for a visual.
But in this case, I need the text so that i can paste it in my logs. 
I can't ype all this :)

**Comment by patchthecode** [comment]
Also, can you paste the code you used to register your header?

**Comment by gilgameshex** [comment]
2017-03-08 10:47:27.790 Calender[2028:63019] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'must pass a valid reuse identifier to -[UICollectionView dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a029d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010798021e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a0932b5 +[NSException raise:format:] + 197
	3   UIKit                               0x00000001087a2a2d -[UICollectionView dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:] + 281
	4   JTAppleCalendar                     0x0000000107387100 _TFC15JTAppleCalendar19JTAppleCalendarView14collectionViewfTCSo16UICollectionView33viewForSupplementaryElementOfKindSS2atV10Foundation9IndexPath_CSo24UICollectionReusableView + 4224
	5   JTAppleCalendar                     0x0000000107387a59 _TToFC15JTAppleCalendar19JTAppleCalendarView14collectionViewfTCSo16UICollectionView33viewForSupplementaryElementOfKindSS2atV10Foundation9IndexPath_CSo24UICollectionReusableView + 137
	6   UIKit                               0x000000010878e444 -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:] + 762
	7   UIKit                               0x0000000108792a84 -[UICollectionView _updateVisibleCellsNow:] + 4841
	8   UIKit                               0x0000000108798725 -[UICollectionView layoutSubviews] + 313
	9   UIKit                               0x0000000107f14ab8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1237
	10  QuartzCore                          0x000000010e3dbbf8 -[CALayer layoutSublayers] + 146
	11  QuartzCore                          0x000000010e3cf440 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	12  QuartzCore                          0x000000010e3cf2be _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	13  QuartzCore                          0x000000010e35d318 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 280
	14  QuartzCore                          0x000000010e38a3ff _ZN2CA11Transaction6commitEv + 475
	15  QuartzCore                          0x000000010e38ad6f _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 113
	16  CoreFoundation                      0x0000000109fce267 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x0000000109fce1d7 __CFRunLoopDoObservers + 391
	18  CoreFoundation                      0x0000000109fb28a6 CFRunLoopRunSpecific + 454
	19  UIKit                               0x0000000107e49aea -[UIApplication _run] + 434
	20  UIKit                               0x0000000107e4fc68 UIApplicationMain + 159
	21  Calender                            0x0000000107296a9f main + 111
	22  libdyld.dylib                       0x000000010bd3068d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by gilgameshex** [comment]
calendarView.registerHeaderView(xibFileNames: ["headerView","febHeaderView"])

**Comment by gilgameshex** [comment]
thanks

**Comment by patchthecode** [comment]
ok based on what you have sent, i can't see the error.
Can you do one thing?
I have a sample app attached to this github project. It has multiple headers implemented.
Can you look at it and see what is different from your code?

**Comment by gilgameshex** [comment]
[Calender.zip](https://github.com/patchthecode/JTAppleCalendar/files/828560/Calender.zip)

I still can't find the mistake, here is my code, thank you very much

**Comment by patchthecode** [comment]
Hey, you didnt follow the tutorials properly 😞 

Also, you had a spelling error for the identifier. You had a "H" instead of a "h" in *header*
Here is your fixed file.
[Calender.zip](https://github.com/patchthecode/JTAppleCalendar/files/828699/Calender.zip)

**Comment by patchthecode** [comment]
closing this issue. 
If you still have problems, then let me know here.
I will respond.
