### ISSUE TITLE
When i update to latest version.（6.1.5）  Appear a problem - 'cellCacheSection does not exist.'

### ISSUE THREAD

**Issue by baobao57** [patchthecode/JTAppleCalendar#337]
When I from `6.1.1` version update to the latest version. 
<img width="334" alt="2017-03-09 2 41 19" src="https://cloud.githubusercontent.com/assets/12264243/23739015/4b9c46bc-04d7-11e7-8baa-63f38f20f74a.png">
I read the assert  message.  but i don't know this problem What is the cause.
<img width="353" alt="2017-03-09 2 40 56" src="https://cloud.githubusercontent.com/assets/12264243/23739147/f7bd815e-04d7-11e7-929a-b5233a84bc96.png">

**Comment by patchthecode** [comment]
if youre online can you join here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
I will need more information.
Can you show me your `configureCalendar` function?

**Comment by patchthecode** [comment]
closing this issue unless for information comes to light.
Version 7.0.0 on separate branch has many fixes and performance enhancements.
