### ISSUE TITLE
Load calendar on month other than the starting month

### ISSUE THREAD

**Issue by jordanw421** [patchthecode/JTAppleCalendar#338]
Hi. Is it possible to load the calendar, such that the initially displayed month is not the same as the month in startDate? 

For ex)

// yyyy MM dd
startDate = "2017 01 01" 
endDate = "2018 01 01"

Is it possible to load the calendar so that the visible month is set to say "2017 05" (May 2017) rather than "2017 01"? I tried simply scrolling to May as soon as the view presents itself, but this doesn't look very clean. 

Note that setting the startDate to "2017 05 01" will not solve the problem because then the user cannot scroll back to earlier months. 

Thanks in advance!

**Comment by patchthecode** [comment]
> Is it possible to load the calendar so that the visible month is set to say "2017 05" (May 2017) rather than "2017 01"? I tried simply scrolling to May as soon as the view presents itself, but this doesn't look very clean.

Have you tried scrolling without any animation?

`scrollToDate(date, animateScroll: false)`

You need to tell me what `this doesn't look very clean.` means

**Comment by jordanw421** [comment]
Ahh geez I feel dumb now. I didn't try turning the animation off, that solves my problem. Too little sleep and I forgot that :/

Sorry for taking your time on this non-issue. Thanks 👍

**Comment by patchthecode** [comment]
Its cool. Have a good one.
 🍻
