### ISSUE TITLE
Enquiries on code

### ISSUE THREAD

**Issue by gilgameshex** [patchthecode/JTAppleCalendar#339]
Hi again, thanks for last time, sorry I actually didn't spot that. 
I just want to ask about the if function of this code
```swift
//size
func calendar(_ calendar: JTAppleCalendarView, sectionHeaderSizeFor range: (start: Date, end: Date), belongingTo month: Int) -> CGSize {
if month % 2 > 0{
```
Can you please briefly explain this so that I can add other variations. Thank you very much

**Comment by patchthecode** [comment]
I just placed that `if` function there as an example.
In your real app, please remove it.

Use your own `if` statement to determine the size of the headers.

So for example you can do something like

```
if date is Jan - 01 - 2017 then 
     make the height 200
else
    make the height 100
``

**Comment by gilgameshex** [comment]
Sorry, I didn't phase the question clearly, i mean the " month % 2 > 0" part

**Comment by gilgameshex** [comment]
Because I am planning to do change in months in header every time I swipe, but does it actually mean that I need to create 12 sets of headers or there are other options available?

**Comment by patchthecode** [comment]
`month` is an integer from `1` to `12` for the months of the year.

`%` -> is the mod operator - You can google about it.

but it basically gives the remainder for `month` / 2
If the remainder is > 0 then i set the month size to a particular value
else
i set the month size to a particular value

is that clearer?

**Comment by gilgameshex** [comment]
yes thank you very much
