### ISSUE TITLE
Question about simplifying code

### ISSUE THREAD

**Issue by gilgameshex** [patchthecode/JTAppleCalendar#341]
Hi, 

I have just finished creating my basic calendar with 12 headers, however that made me do 12 headers. I was just wondering if there is anyway that i could simplify this large chunk of code. 
Here is my code: 
[Calender.zip](https://github.com/patchthecode/JTAppleCalendar/files/835663/Calender.zip)
Thanks!

**Comment by patchthecode** [comment]
Hey, I think you misunderstood something.
Why are you creating 12 headers? 😨

You only need one.
Only create 1 header view, then change the data as needed in the delegate.

**Comment by patchthecode** [comment]
Take a look at the example app attached to this repository. I only have 2 headers, and yet I am able to change the month names.

**Comment by gilgameshex** [comment]
oh

**Comment by gilgameshex** [comment]
started programming not long ago, so don't know the logic of it that well

**Comment by gilgameshex** [comment]
:0

**Comment by gilgameshex** [comment]
Just a question, 

    func setupViewsOfCalendar(from visibleDates: DateSegmentInfo) {
        guard let startDate = visibleDates.monthDates.first else {
            return
        }
        let month = testCalendar.dateComponents([.month], from: startDate).month!
        let monthName = DateFormatter().monthSymbols[(month-1) % 12]
        // 0 indexed array
        let year = testCalendar.component(.year, from: startDate)
        monthLabel.text = monthName + " " + String(year)

is this code representing your switch in months? 

Thanks so much!!

**Comment by patchthecode** [comment]
Yes i use that code to extract the date.
Keep in mind that this is only a example code. You can extract the date however you want.

i first get the start visible date
```
    guard let startDate = visibleDates.monthDates.first else {
        return
    }
```

then i just do regular NSDate functions to find out what month it is
```
    let month = testCalendar.dateComponents([.month], from: startDate).month!
    let monthName = DateFormatter().monthSymbols[(month-1) % 12]
    // 0 indexed array
    let year = testCalendar.component(.year, from: startDate)
    monthLabel.text = monthName + " " + String(year)
```

**Comment by gilgameshex** [comment]
Lost my phone last night so i didn't read it until now 😨, thanks so much, i will give it a try now

**Comment by gilgameshex** [comment]
I tried to use your code with the label in my program, the label didn't change the month

**Comment by gilgameshex** [comment]
I commented out all my header codes as i dont need it temporarily

**Comment by gilgameshex** [comment]
[Calender.zip](https://github.com/patchthecode/JTAppleCalendar/files/836483/Calender.zip)
Here is my calendar

**Comment by patchthecode** [comment]
[Calender.zip](https://github.com/patchthecode/JTAppleCalendar/files/836641/Calender.zip)

Closing this issue as it is has now become unrelated with the calendar.
I believe that most of your problems stem from you are maybe new to swift/xcode. 
All the best in your learning 🍻

**Comment by gilgameshex** [comment]
ok thanks
