### ISSUE TITLE
Show today method

### ISSUE THREAD

**Issue by chrisfngr** [patchthecode/JTAppleCalendar#346]
I am new of SWIFT, thank your wonderful calendar. I want to know how to show today date and show the month of today instead of the startDate. Thanks you

**Comment by patchthecode** [comment]
`calendarView.scrollToDate([theDateToStartWith])`

**Comment by chrisfngr** [comment]
Hi,
 I put that code into viewDidLoad() method, but it give me a error "Expected expression in list of expression" and tell me I should add ',' to separator, what should I do for this error
Thank you.

**Comment by chrisfngr** [comment]
Hi me again
I have fixed this problem, anyway thank you for provide a wonderful calendar :)

**Comment by patchthecode** [comment]
You are welcome.
Have a good day 🍻
