### ISSUE TITLE
Improve code quality by using SwiftLint

### ISSUE THREAD

**Issue by elsesiy** [patchthecode/JTAppleCalendar#347]
Hi Jay, 

great work so far (after being dissatisfied with CVCalendar I guess) 👍  After skimming your code though, I suggest a refactoring and code clean up, i.e. `horizontalStuff()` and `verticalStuff()` in `JTAppleCalendarLayout.swift` aren't really human readable. In addition you definitely can improve the overall quality by using [SwiftLint](https://github.com/realm/SwiftLint) which has some neat rulesets. 

I am planning on using SwiftLint for CVCalendar too!

Cheers, Jonas!

**Comment by patchthecode** [comment]
Thanks for the kind words man.
I will do this.
By the the way, I started using CVCalendar before creating this one. It was great, but my calendar needed a little bit more flexibility, and at the time I didn't have time to learn your code base to create PR requests. So I just rolled my own.
But yes, i will swift lint it in version 7.0.0 (the final major version). Its already almost ready.

**Comment by patchthecode** [comment]
Closing. Moved this to the projects section -> https://github.com/patchthecode/JTAppleCalendar/projects
