### ISSUE TITLE
Compare  date

### ISSUE THREAD

**Issue by chrisfngr** [patchthecode/JTAppleCalendar#348]
Hi I want you give event on a specific date, but I can't use == to compare two dates, but < and > is work well, so how should I do, please give a specific answer, I am not very familiar with  swift.
Thank you

**Comment by patchthecode** [comment]
I appreciate the question, but it is not calendar related.
Does this link answer your question? -> http://stackoverflow.com/questions/39018335/swift-3-comparing-date-objects

**Comment by chrisfngr** [comment]
my code is like this, date id from method argument, today = NSDate(),
let date1 = date
        let date2 = today
        if date1 == date2 as Date{
            print("h")
        }else if date1 < date2 as Date{
            print("s")
        }
i try this code only work when date is early, and also date == today it still print "s", so i am very confused this thing

**Comment by patchthecode** [comment]
http://stackoverflow.com/questions/5540271/how-to-compare-just-dates-not-the-time

**Comment by ArunVicky001** [comment]
@patchthecode : Thanks for the awesome library, Could you please tell how to compare less then  and grater then date cases ? 

        ```
        today = NSDate(),
        let date1 = date
        let date2 = today
        if date1 < date2 as Date{
            print("s")
        }
```
