### ISSUE TITLE
Year view support

### ISSUE THREAD

**Issue by MaikoHermans** [patchthecode/JTAppleCalendar#349]
I was wondering if it is possible to build a "year view" with this library.
I saw that you mentioned somewhere that it was being worked on back in sept 2016.

I was wondering if it is available now since that is exactly what I need

**Comment by patchthecode** [comment]
its not available yet.
I was thinking that i would have to create a new layout for it.
I do not want to clutter the existing framework.
I will do this when im free. But right now, I am very tied-up with multiple projects.
But i'll give this some thought soon

**Comment by patchthecode** [comment]
closing. Moving this to projects section -> https://github.com/patchthecode/JTAppleCalendar/projects

**Comment by patchthecode** [comment]
Enhancement coming.

**Comment by patchthecode** [comment]
Implemented.
Testing on branch -> **YearView**

**Comment by patchthecode** [comment]
merged on master branch

**Comment by MrShafiee** [comment]
Hi @patchthecode , how we can use the year view? i couldn't find any clue on document!
Thanks.

**Comment by patchthecode** [comment]
It is not documented yet.
Never got the time to do it.

But it is running live in the sample project attached to github.
Can you try it and take a look at how to implement it?

It is just as simple as the regular calendar

**Comment by patchthecode** [comment]
If you have more questions, then ask

**Comment by MrShafiee** [comment]
Hi @patchthecode, when I installed  library by pods it will be installed version 7.0.7! but YearView available in version 8, and with iOS 11.2 I faced minimum version error! what is the minimum version of iOS to use version 8?
You didn't put it on master branch?
