### ISSUE TITLE
show current day on viewDidLoad

### ISSUE THREAD

**Issue by akabab** [patchthecode/JTAppleCalendar#35]
Hey, just trying to do `calendarView.scrollToDate(NSDate())` at the end of `viewDidLoad` (after calendar setup) but it's not happening, any idea ?

**Comment by krisanthony** [comment]
I just tried this myself, only way I could get it to work was placing `calendar.selectDates([date])` and then within `didSelectDate` implementation `calendar.scrollToDate(date)`

I'm not 100% sure why, but odd hack - `calendar.scrollToDate(NSDate(), animateScroll: false)` works just fine (and animates)

**Comment by patchthecode** [comment]
Checking this out now.

**Comment by akabab** [comment]
I actually tried to put it in viewDidAppear, it's actually working but not each time, I'm thinking maybe the calendarView did not finished initializing when I receive viewDidAppear call.

**Comment by patchthecode** [comment]
Yea ok i have this issue fixed. Im testing it now to make sure i dont break anything else

**Comment by akabab** [comment]
Great, you're about to push it ?

**Comment by patchthecode** [comment]
I can push it yes. But, I cant do an official release till i test it.
Currently, the new code fix has a crash for individuals using vertical scrolling.

I'm trying to get this all wrapped up by Saturday. fingers crossed.

**Comment by akabab** [comment]
Alright ;) thanks

**Comment by patchthecode** [comment]
Ok. Hey, I've finished testing the latest patch.
In order to fix the concurrency issues, i had to do some changes to the way we do 

`calendarView.numberOfRowsPerMonth = 6`

I have now made it more like Apple's UITableView. The number of rows is now setup in the configure method. I will push this to master branch now. Would you be able to test it from master branch? or are going to wait for release 3.0.2? 

I am pausing the release to handle the other issues, but the fix will be available on master branch.

**Comment by patchthecode** [comment]
Committed and pushed master branch. The example of how to accomplish your task is added to the sample project.
Take a look in the `viewDidLoad()` function.

**Comment by akabab** [comment]
I'm not sure to understand the relation between numberOfRows and the scrollToDate on viewDidLoad. You're not calling scrollToDate in your exemple. Anyway I guess I'm gonna wait for realease, I'm using the pod.

**Comment by patchthecode** [comment]
Ok. My bad, i didnt explain it clearly.  
you are correct. NumberOfRows and scrollToDate and totally unrelated.

However in the next release, there will be a change to the way numberOfRows is setup. So i was just giving you a heads up on the changes to expect.

Your scroll to date issue will be resolved. But you will also have to make one small change on in the configureCalendar function.

I'll Release the update later today. Let me know if anything else is breaking.

**Comment by akabab** [comment]
No problem, thanks!

**Comment by patchthecode** [comment]
updated to version 4.0.0
Update your pod and let me know if you're still experiencing the problem.

You can scroll to your date using the scrollToDate function.
That function has a number of options you can choose from as shown [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions) (Scroll to question 4)

**Comment by akabab** [comment]
Seems to be working! 👯 
Btw, you should remove JTAppleCalendarDelegates.swift line 269 -> print(indexPath)
Be free to close that issue, great job.

**Comment by patchthecode** [comment]
oops... >_< 
yea.. i'll remove it. it must have been late, i forgot to remove it
