### ISSUE TITLE
[7.0 Beta] Selection bug

### ISSUE THREAD

**Issue by quaddef** [patchthecode/JTAppleCalendar#350]
Step 1. Select several days.
<img width="340" alt="screen shot 2017-03-21 at 2 27 04 am" src="https://cloud.githubusercontent.com/assets/5310289/24126781/f8fcf7e0-0de0-11e7-9aaf-d1faecdd5650.png">
Step 2. Deselect one in the middle, in my case it's "9"
<img width="327" alt="screen shot 2017-03-21 at 2 27 20 am" src="https://cloud.githubusercontent.com/assets/5310289/24126802/224a30b8-0de1-11e7-8984-2e8207296686.png">

It happens, because cells after "9" are not updated.
https://github.com/patchthecode/JTAppleCalendar/blob/7.0.0/Sources/UICollectionViewDelegates.swift#L106

My code on which you can test it:

    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState){
        var selectedDates = calendar.selectedDates
        selectedDates.remove(date)
        calendar.deselectAllDates(triggerSelectionDelegate: false)
        
        if selectedDates.count == 0{
            calendar.selectDates([date], triggerSelectionDelegate: false)
        }else{
            if date < selectedDates.first!{
                calendar.selectDates(from: date, to: selectedDates.last!, triggerSelectionDelegate: false)
            }else{
                calendar.selectDates(from: selectedDates.first!, to: date, triggerSelectionDelegate: false)
            }
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState){
        var selectedDates = calendar.selectedDates
        selectedDates.append(date)
        selectedDates = selectedDates.sorted()
        
        if calendar.selectedDates.count != 0 && selectedDates.first != date && selectedDates.last != date{
            calendar.deselectAllDates(triggerSelectionDelegate: false)
            
            if abs(date.timeIntervalSince1970 - selectedDates.first!.timeIntervalSince1970) > abs(date.timeIntervalSince1970 - selectedDates.last!.timeIntervalSince1970){
                calendar.selectDates(from: date, to: selectedDates.last!, triggerSelectionDelegate: false)
            }else{
                calendar.selectDates(from: selectedDates.first!, to: date, triggerSelectionDelegate: false)
            }
        }else{
            handleSelection(cell: cell, cellState: cellState, date: date)
        }
    }

    func handleSelection(cell: JTAppleCell?, cellState: CellState, date: Date) {
        let customCell = cell as! CalendarCell
        
        if date < endDate{
            switch cellState.selectedPosition() {
            case .none: customCell.position = .off
            case .full: customCell.position = .single
            case .left: customCell.position = .left
            case .right: customCell.position = .right
            case .middle: customCell.position = .middle
            }
            
            customCell.isUserInteractionEnabled = true
        }else{
            customCell.position = .disabled
            customCell.isUserInteractionEnabled = false
        }
    }

**Comment by quaddef** [comment]
I've simplified example, deselection doesn't trigger batch updates.

        let dateFormatter = DateFormatter(dateFormat: "dd-MM-yyyy")
        let firstMarch = dateFormatter.date(from: "01-03-2017")!
        let seventhMarch = dateFormatter.date(from: "07-03-2017")!
        calendar.selectDates(from: firstMarch, to: seventhMarch, triggerSelectionDelegate: false)
        calendar.deselectAllDates(triggerSelectionDelegate: false)

<img width="329" alt="screen shot 2017-03-21 at 8 40 38 pm" src="https://cloud.githubusercontent.com/assets/5310289/24161865/ab1b6958-0e76-11e7-83c3-4ad4afa53107.png">

**Comment by patchthecode** [comment]
Let me know is this is fix.

**Comment by quaddef** [comment]
Awesome, works like a charm.
