### ISSUE TITLE
Calendar Day Cell Refresh

### ISSUE THREAD

**Issue by fwhite3443** [patchthecode/JTAppleCalendar#353]
Hi,

I'll start by saying that I'm not sure this if this is a bug/issue with JTAppleCalendar, or if it's an issue with the way I'm trying to use it.  Figured I'd post to see if you have any ideas...

I have a custom calendar cell view (derived from JTAppleDayCellView) that maintains state data and overrides the draw function to draw decals on a cell.

The problem I'm having, is that when the calendar collection is scrolled from month to month, the willDisplayCell function is called as expected for every visible cell in the collection, but the overridden cell draw call is only called for a few cells, if any.

My overridden draw call basically draws multiple dots of varying color in the cell.  What dots and colors it should draw are data driven by the calendar view controller (i.e. updated every time willDisplayCell gets called).  What I'm seeing though, is when I scroll from month to month, the draw call isn't being called, and cells that previously had no dots drawn on them now have dots drawn on them when scrolling away and back to a month.

Here's the basic idea:

willDisplayCell:
```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState)
    {
        let calendarCell = cell as! CalendarCellView
        
        // Configure cell date text and color
        calendarCell.setDateLabelFont(font: Theme.PrimaryFont)
        calendarCell.setDateLabelText(text: cellState.text)
        calendarCell.setDateLabelTextAlignment(align: NSTextAlignment.center)
        if cellState.dateBelongsTo == .thisMonth
        {
            calendarCell.setDateLabelTextColor(color: Theme.CalendarTextColor)
        }
        else
        {
            calendarCell.setDateLabelTextColor(color: Theme.CalendarTextColorInactive)
        }
        
        // Configure cell background color
        calendarCell.setBackgroundType(type: CalendarCellView.BackgroundType.solid)
        if (currentCalendar.isDateInToday(date))
        {
            calendarCell.setBackgroundColor(type: CalendarCellView.BackgroundType.solid, color: Theme.CalendarCellColorSelected)
        }
        else
        {
            // Set the calendar cell color to the same as the calendar view
            calendarCell.setBackgroundColor(type: CalendarCellView.BackgroundType.solid, color: self.view.backgroundColor!)
        }
        
        // Clear any active dots
        calendarCell.clearActiveDots()
        
        // Determine active dots and colors
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        let activityEntries: [ActivityData.Entry]! = appDelegate.activityManager.activityData.getEntries(date: date)
        if (activityEntries != nil)
        {
            for i in 0 ..< activityEntries.count
            {
                calendarCell.setDotActive(index: i, active: true)
                calendarCell.setDotColor(index: i, color: appDelegate.activityManager.activities.get(name: activityEntries[i].name).color)
            }
        }
    }
```

overridden cell draw func (gets called initially for every day, but randomly, if ever, when scrolling between previous/next segments):
```swift
    override func draw(_ rect: CGRect)
    {
        super.draw(rect)
        
        // Draw the gradient
        drawBackground(rect: rect)
        
        // Draw dots
        drawDots(rect: rect)
    }
```

Perhaps there's something I'm missing?  I've tried calling reloadData after scrolling to next or previous segments, and a number of other collection view functions that haven't succeeded in getting the draw call to be reliably called. 

Any thoughts?

Thanks.

**Comment by patchthecode** [comment]
Hey, is it possible you can zip a small project and send it here?
You can drop the zip file into this chat box.
Let me take a look.

**Comment by fwhite3443** [comment]
Not super keen on dropping the zip on a public forum... could email you something?

**Comment by fwhite3443** [comment]
Hey, you can close this out invalid for now if you want.  Once I figure out what's going on, I'll update.  Worst case, I'll throw together a sample project that reproduces the issue when I have time if I can't figure it out.

**Comment by patchthecode** [comment]
ok. Email is here -> Patchthecode@gmail.com
Let me know when you do find updates

**Comment by fwhite3443** [comment]
Okay, figured it out - main issue was needing to call cell.setNeedsDisplay() to force a refresh of the custom draw code.  Since the collection view is re-using cells, the draw(_ rect: ) call only executes the first time a cell is created.

Had a secondary issue that was pretty straightforward, but figure I'll mention it here for completeness.  I also needed to call reload data on the calendar view when navigating back to it from an IBAction segue in order for it to re-display the cells.

**Comment by patchthecode** [comment]
Awesome. Glad it worked.
Other will see the solution you came up with here.
Cheers 🍻
