### ISSUE TITLE
RxDelegateProxy

### ISSUE THREAD

**Issue by jtezanos** [patchthecode/JTAppleCalendar#355]
When attempting to setup Rx with JTAppleCalendar, we run into the issue of #selector referring to a method that is not exposed to Objective-C. Are there any plans to have Rx support or exposing to Objective-C?

**Comment by patchthecode** [comment]
This project is very huge.
And I am only one person.
There is not enough man power to make this available to ObjectiveC.

Which method is it that is not exposed to ObjC ?

**Comment by patchthecode** [comment]
Its been 5 days and no response. Closing this issue.
I will assume this question was resolved. :)
