### ISSUE TITLE
ReloadDates

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#36]
I'm not sure if this is working correctly. I'm trying to scroll to a date, and select it (single selection) not by pressing on the date itself but by gesture. I have other logic in the `didSelectDate` implementation that prevents me from being able to trigger the delegate call.

So I have 
> calendar.scrollToDate(date)
calendar.selectDates([date], triggerSelectionDelegate: false)
calendar.reloadDates([selectedDate])

where selectedDate is the previously selected date, however it is not reloaded, and remains selected. Any ideas?

**Comment by patchthecode** [comment]
Checking this out now.

**Comment by patchthecode** [comment]
I am not understanding what you are trying to accomplish.

Just so i understand this.
You want to:
1. Scroll to a date
2. Select the date with code
3. Reload the selected date

And my question is, why?
If your objective is to select a date and scroll to it, then just do
1. calendar.scrollToDate(date)
2. calendar.selectDates([date], triggerSelectionDelegate: false)

Maybe if you describe an overview of what you are trying to do, then I can help you more.

**Comment by krisanthony** [comment]
I made that more confusing than it needed to be. Basically. I am wanting to scroll to and select a date different than the one already selected. However, with single selection enabled, the previously selected date does not deselect if you have 'triggerSelectedDelegate: false'

**Comment by patchthecode** [comment]
This should be working correctly. 
Tell you what, I will not look into this because I have a new version being released over the weekend. 
I do not see the issue you mentioned occurring in it, so it's possible that the issue is resolved in the new version. Will release it in a couple hours.

**Comment by patchthecode** [comment]
New version released. Reopen this issue if it is still occurring
