### ISSUE TITLE
Need gradeint view on calendar selection

### ISSUE THREAD

**Issue by Saurabhrura** [patchthecode/JTAppleCalendar#360]
![screen 3 choose date-1](https://cloud.githubusercontent.com/assets/24776128/24346480/26f7a0b2-12f2-11e7-89fe-0837c3711149.jpg)

I am in a deep trouble with calendar view and I really need your help for this. Please check the attached image. The thing I need a gradient view for a calendar. By selecting one date and then another will make the select as a gradient. 
 
I followed your code but I am unable to get this done with 100% result. If I use an image it will only work on one date and to cover the whole selection. 
 
I would really appreciate if you can share the logic or a code behind this as this is something on high priority on my project.

**Comment by patchthecode** [comment]
This should be easy to do.

You will need to create some function that creates a gradient color to a view.
So lets say you have 16 dates selected like you have in the image above, this function will create 16 gradient color slots. The color should change slightly with each increasing index. 

Once you have the gradient colors calculated, then you should be able to apply them in the `willDisplayCell` function.

Sounds possible?

**Comment by patchthecode** [comment]
No response for 2 days.
Closing issue.
If you still have questions on this then reopen is this, and i'll continue.
