### ISSUE TITLE
Regression caused by changes made to pull request #359

### ISSUE THREAD

**Issue by anlaital** [patchthecode/JTAppleCalendar#361]
See https://github.com/patchthecode/JTAppleCalendar/pull/359

Current code in master:

```                
let maxYCalendarOffset = max(0, self.calendarView.contentSize.height - self.calendarView.frame.size.height)
let topOfHeader = CGPoint(x: attributes.frame.origin.x,y: maxYCalendarOffset)
```

The modified code is missing the call to `min` from the original code. This makes it impossible to scroll to any offset other than the very end. :)

Fixed code for master:

```
let topOfHeader = CGPoint(x: attributes.frame.origin.x,y: min(attributes.frame.origin.y, maxYCalendarOffset))
```

**Comment by patchthecode** [comment]
oops.
fixing.

**Comment by patchthecode** [comment]
Fixed. Thanks man.
good eye.
