### ISSUE TITLE
xcode 8.3 swift 3 warning

### ISSUE THREAD

**Issue by Alexookah** [patchthecode/JTAppleCalendar#362]
xcode 8.3. warnings in AnimationClass.swift file

AnimationClass.swift:88:47: 'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

```
case .open:
            topRotationAnimation.fromValue = -M_PI_2
            topRotationAnimation.toValue = 0
            break;
        case .closed:
            topRotationAnimation.fromValue = 0
            topRotationAnimation.toValue = -M_PI_2
        }
```

**Comment by patchthecode** [comment]
Hey, is it possible you can create a pull request for this?

**Comment by Alexookah** [comment]
JTAppleCalendar/Example/JTAppleCalendar iOS Example/AnimationClass.swift
its in the example code the issues with -M_PI_2

you want me to try to fix this issue and create a pull request ?

**Comment by patchthecode** [comment]
If you can.
I am unable to do this for the next couple set of days.
But you create one now, I can approve it, and merge it.
If you are unable to do it then, i'll fix in the next several days :)

**Comment by Alexookah** [comment]
created a pull request. :)

**Comment by patchthecode** [comment]
added thanks.
