### ISSUE TITLE
startDate and endDate not on a month boundary?

### ISSUE THREAD

**Issue by UberJason** [patchthecode/JTAppleCalendar#365]
Hi there,

For my current project I'm using `endDate` as `Date()` (i.e. whatever today is - currently April 1), and `startDate` as 2 weeks before `endDate`. I'm noticing that the calendar getting generated starts on March 1 even though `startDate` is somewhere in mid-March and `generateInDates` is set to `.off`. Wondering if this is expected behavior? Are `startDate` and `endDate` intended to be month boundaries, or is it possible to generate a calendar that starts mid-month?

Below is my configureCalendar function:

```
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let endDate = Date()
        let startDate = endDate.subtract(2.weeks)
        
        let parameters = ConfigurationParameters(startDate: startDate,
              endDate: endDate,
             numberOfRows: 2,
            calendar: Calendar.current,
            generateInDates: .off,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: .sunday)

        return parameters
    }
```

**Comment by patchthecode** [comment]
Yes, it is meant to be month boundaries.
If you want to restrict boundaries you can check the visibility of the cell you do not wish to cross, and then simply scroll back.

**Comment by UberJason** [comment]
Thanks for the reply. Can I ask what you mean by "check the visibility of the cell you do not wish to cross, and then simply scroll back"? Do you mean to hide the cells (e.g. isHidden = true or alpha = 0)? I'm confused about the "scroll back" part.

**Comment by patchthecode** [comment]
You know when you make a mental note to respond, and then forget to respond?
My bad.
I'll will provide an example for how you can do this over this weekend.

**Comment by UberJason** [comment]
Much appreciated!

**Comment by patchthecode** [comment]
Here is an example of implementing a boundary on a 6-row calendar.
With this code, the user is not allowed to cross the month of august.

Override this function in your viewController
```swift
func scrollDidEndDecelerating(for calendar: JTAppleCalendarView) {
    let visibleDates = calendarView.visibleDates()
    let dateWeShouldNotCross = formatter.date(from: "2017 08 07")!
    let dateToScrollBackTo = formatter.date(from: "2017 07 03")!
    if visibleDates.monthDates.contains (where: {$0 >= dateWeShouldNotCross}) {
        calendarView.scrollToDate(dateToScrollBackTo)
        return
    }
}
```

**Comment by UberJason** [comment]
Cool, thank you!

**Comment by zhanswift** [comment]
I have error: 

> Binary operator '>=' cannot be applied to operands of type '(date: Date, indexPath: IndexPath)' and 'Date'

**Comment by patchthecode** [comment]
@zhanswift what did you do to get that error?

**Comment by patchthecode** [comment]
@zhanswift ok. which version of the calendar are you using?

**Comment by zhanswift** [comment]
Thank you. Already solved.
