### ISSUE TITLE
How to use this calendar as islamic calendar

### ISSUE THREAD

**Issue by ashokdy** [patchthecode/JTAppleCalendar#366]
I have to use this as Gregorian and also as Islamic, please let me know how can i use it.

**Comment by patchthecode** [comment]
You provide the calendar instance to the `configureCalendar` function.
Therefore you can provide a gregorian calendar if you wish, and you can also provide an islamic calendar if you wish

**Comment by ashokdy** [comment]
can you please provide any snippet?

**Comment by patchthecode** [comment]
Hi, it is not the `startDate` and `endDate` that determine what kind of calendar it is.
It is the calendar instance that you provide which determines this. See below.

```swift
let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: numberOfRows,
                                                 calendar: myCalendar, // <----- provide an islamic calendar instance here
                                                 generateInDates: generateInDates,
                                                 generateOutDates: generateOutDates,
                                                 firstDayOfWeek: firstDayOfWeek,
                                                 hasStrictBoundaries: hasStrictBoundaries)
```

Now i do not know to to create an islamic calendar.
I usually create my calendar like this

```swift
let myCalendar1 = Calendar(identifier: .gregorian)
// or like this
let myCalendar2 = Calendar.current // To automatically pick up which ever region the user is at
```

But i guess you know how to create an Islamic calendar instance?

**Comment by patchthecode** [comment]
Here is an example of one user who did it -> https://github.com/patchthecode/JTAppleCalendar/issues/173

**Comment by patchthecode** [comment]
Closing this issue.
As there has been no response in 3 days.
If this is still an issue, then click on the re-open button of this issue.
I will continue where i left off.
