### ISSUE TITLE
How to add image on particular date from image stored in core data

### ISSUE THREAD

**Issue by abdulKarim002** [patchthecode/JTAppleCalendar#367]
Hello Jay
let me first thank you for all your effort you have done to make and maintain this library and really it awesome save a lot of time, Dude I wanted to set the image on selected date and as per xib cell I have configured the cell with image view but how to add images on a particular date, let say I wanted to add images on 26/01/2017, 14/02/2017, 30/01/2017, how I can achieve this, kindly suggest 

Thank you

**Comment by patchthecode** [comment]
This is easy to do.
in your `willDisplayCell` function, you simply do something like
```swift
if date == theDateThatiWantToCHeckFOr {
   // show image x
}
```

**Comment by abdulKarim002** [comment]
@patchthecode  the issue is i have an array of date to display the images can you plz elaborate 

Thank you for your response..

**Comment by patchthecode** [comment]
can you please join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing. Question was resolved.
