### ISSUE TITLE
Month date showing one day late in every dates of month.

### ISSUE THREAD

**Issue by bhavinmakadia** [patchthecode/JTAppleCalendar#369]
Hi,

I am creating simple calendar application in which i create a buttons to change months. Whenever i change month `didScrollToDateSegmentWith` delegate method will call and in this method i get `visibleDates.monthDates` for current month. When i do `print(visibleDates.monthDates as Any)` i get below response

*[**2017-04-30 18:30:00 +0000**, 2017-05-01 18:30:00 +0000, 2017-05-02 18:30:00 +0000, 2017-05-03 18:30:00 +0000, 2017-05-04 18:30:00 +0000, 2017-05-05 18:30:00 +0000, 2017-05-06 18:30:00 +0000, 2017-05-07 18:30:00 +0000, 2017-05-08 18:30:00 +0000, 2017-05-09 18:30:00 +0000, 2017-05-10 18:30:00 +0000, 2017-05-11 18:30:00 +0000, 2017-05-12 18:30:00 +0000, 2017-05-13 18:30:00 +0000, 2017-05-14 18:30:00 +0000, 2017-05-15 18:30:00 +0000, 2017-05-16 18:30:00 +0000, 2017-05-17 18:30:00 +0000, 2017-05-18 18:30:00 +0000, 2017-05-19 18:30:00 +0000, 2017-05-20 18:30:00 +0000, 2017-05-21 18:30:00 +0000, 2017-05-22 18:30:00 +0000, 2017-05-23 18:30:00 +0000, 2017-05-24 18:30:00 +0000, 2017-05-25 18:30:00 +0000, 2017-05-26 18:30:00 +0000, 2017-05-27 18:30:00 +0000, 2017-05-28 18:30:00 +0000, 2017-05-29 18:30:00 +0000, **2017-05-30 18:30:00 +0000**]* 

This is 5th month and date start with`2017-04-30 18:30:00 +0000` and ends with `2017-05-30 18:30:00 +0000`. It should start with `2017-05-01 18:30:00 +0000` and ends with `2017-05-31 18:30:00 +0000`.

**Comment by bhavinmakadia** [comment]
Also i noticed the all the dates of any month including inDate, outDate, monthDate all these dates are one behind. Might be i am wrong some ware to implementation so i post below my code.

```
class CalendarVC: UIViewController {
@IBOutlet weak var calendarView: JTAppleCalendarView!

let white = UIColor(colorWithHexValue: 0x7a8a95)
    let darkPurple = UIColor(colorWithHexValue: 0x3A284C)
    let dimPurple = UIColor(colorWithHexValue: 0xcbd1d2)
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
calendarView.dataSource = self
        calendarView.delegate = self
        calendarView.registerCellViewXib(file: "CalendarCellView") // Registering your cell is manditory
        calendarView.cellInset = CGPoint(x: 1, y: 1)
    }

override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        calendarView.scrollToDate(Date())
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

**Comment by patchthecode** [comment]
Are the dates one day behind when you print them on the debugger console?
Or are they one day behind when you look at them visually on the screen.

I think the problem you are experiencing is this -> https://github.com/patchthecode/JTAppleCalendar/issues/252
Let me know if your issue is resolved after reading it.

**Comment by bhavinmakadia** [comment]
Actually there were two issue one is for visually and another for debugger console. The visual issue is resolved and that was my problem. I set wrong header of the week day, i set Sunday as a first day in configuration and set my week day header from Monday like Mon,Tue,Wed,Thu,Sat,Sun . So, it was mismatched. I change the start day as Monday in configuration according to my need and it was perfectly solved the issue.

But the second issue is when i scroll the calendar month `didScrollToDateSegmentWith` call and in this method i did `print(visibleDates.monthDates as Any)` and that gives me the console log as above mention in question.

**Comment by patchthecode** [comment]
Your second issue is resolved in that link i showed you here -> https://github.com/patchthecode/JTAppleCalendar/issues/252

Basically simply printing a date to console will give you misleading information.
Do not do it.
Although the date is correct, it might not be always displayed correctly if you simply print it with a print command.
You need to use a **DateFormatter**.

**Comment by bhavinmakadia** [comment]
It's working !!! Thanks for the help. 

People who face similar issue just don't depends on you console log. If you see wrong date in your console log just try with convert date to string with `DateFormatter` then check is it proper or not. Set you time zone to local when you convert date to string.

Super work @patchthecode , Thanks for very interactive and more custom calendar. Will post my calendar screen shot soon.
