### ISSUE TITLE
Hide boundary dates on single row layout

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#37]
Per title, boundary dates don't make sense in single row layout.

**Comment by krisanthony** [comment]
Any news on this?

**Comment by patchthecode** [comment]
Nah. Got tied up a bit with the other issues in the issue section. Will look into this over the weekend hopefully.

**Comment by patchthecode** [comment]
I'm am now tracking this issue here --> https://github.com/patchthecode/JTAppleCalendar/issues/56
So, i'll close this one.
