### ISSUE TITLE
Compilation error when installed via CocoaPods

### ISSUE THREAD

**Issue by anlaital** [patchthecode/JTAppleCalendar#370]
Currently master doesn't compile when installed via CocoaPods. This is caused by the `Podspec` having the following declaration: `s.ios.deployment_target = '8.0'` while the code itself is using `UISemanticContentAttribute` which is available only after 9.0.

![image](https://cloud.githubusercontent.com/assets/2168023/24601054/1e865086-1860-11e7-93f8-4eb32eec088e.png)

**Comment by patchthecode** [comment]
Thanks. Fixing this now!

**Comment by patchthecode** [comment]
Updated and pushed.
