### ISSUE TITLE
tvOS: Selecting last day of a row causes unconditional month switch

### ISSUE THREAD

**Issue by Paul-Geppert** [patchthecode/JTAppleCalendar#371]
Hey,

I am using JTAppleCalendar in an tvOS context. Whenever my calendar has more than one month, one cannot select the last day of a row in the calendar. The first day of week for me is Monday, so one cannot reach Sunday; but also if one change the first day, the problem is still there.
If one tries to select the last day of a row, the calendar changes to the last of its months.

I have an demo application created a demo application [https://github.com/Paul-Geppert/calendarTVOS](https://github.com/Paul-Geppert/calendarTVOS), in which I did the same as stated in the Quick Tutorial [https://patchthecode.github.io/](https://patchthecode.github.io/).

I am using XCode 8.2.1; the problem occurs on simulator as well as on a physical AppleTV.
Is this a bug, or did I something wrong?
Thank you!

**Comment by patchthecode** [comment]
well honestly, youre one of the few TV developers.
Fewer people using it means less mass testing,  therefore more bug potential.

Therefore iOS = very well tested, but not so much for TV os.
I have XCode 8.3 right now, I'll have a look.

I have one question however, what version of the calendar are you using?

**Comment by Paul-Geppert** [comment]
Thanks for your thoughts. This was one of my ideas, it seems to focus on iOS :D
I am using the latest version (6.1.6).

**Comment by patchthecode** [comment]
Ok. thanks, i'll checkout your project in a short while.

**Comment by Paul-Geppert** [comment]
That would be great! If you have any questions, feel free to contact me.

**Comment by patchthecode** [comment]
Well the first question is... how in the world do i use the tvOS simulator. haha.
I am trying to scroll the calendar view but it is not working. I think I'll have to look over some tutorials on how to actually use the simulator.

**Comment by Paul-Geppert** [comment]
Haha, thats a bit tricky. You can use the Apple TV Remote (by Hardware -> Show Apple TV Remote), if you click, the first date should be selected (yellow circle) and a debugPrint appears. You can also use your Enter-key instead of the click on the remote.
If you want to go to the next date, the easiest way (in my opinion) is to use the arrow keys of your keyboard.

**Comment by Paul-Geppert** [comment]
An other thing I noticed but forgot to share it with you: The stored date within a cell seems to be wrong although it shows the right number (like in month December 2016 "29" leads to debugPrint "Selected cell: " 2016-12-28 23:00:00 +0000).

**Comment by patchthecode** [comment]
If youre online now, can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by Paul-Geppert** [comment]
@patchthecode and I had a discussion about the problem and found the following things:

* The Date is not wrong, it is wrong printed. (See: #252)
* The switch to the last month ended by explicitly stating the scroll direction: `calendarView.scrollDirection = .horizontal`
* Then, when reaching the last entry, the split shows two half months 
* This probably comes from the fact, that `is​Paging​Enabled` of `UIScroll​View` is not available for tvOS; that's why there are `#if os(iOS)
            ...
      #endif` checks in the code on corresponding locations

We will both think about solutions, feel free to add your ideas ;)

**Comment by patchthecode** [comment]
closing this. Moving it over to the project section. - https://github.com/patchthecode/JTAppleCalendar/projects
