### ISSUE TITLE
Problems on start with JTAppleCalendarLayoutProtocol

### ISSUE THREAD

**Issue by Apofeozzz** [patchthecode/JTAppleCalendar#373]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.0
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

![screen shot 2017-04-10 at 11 50 24 am](https://cloud.githubusercontent.com/assets/19584788/24853539/1a5ad2be-1de4-11e7-8896-a7fbf1ddd3a9.png)

Got this problem at start.

**Comment by patchthecode** [comment]
Can you Send me the zip file of that project?
You can drag and drop the zip file in this chat box.

**Comment by Apofeozzz** [comment]
[CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/912465/CalendarTest.zip)

**Comment by patchthecode** [comment]
Hmm, you did not setup the project correctly.

first, your `Podfile` should have this
`pod 'JTAppleCalendar', '~> 7.0'`

Next, you should setup your calendar like this -> https://www.youtube.com/watch?v=zOphH-h-qCs

**Comment by Apofeozzz** [comment]
Ok. Thanks. I will try.

**Comment by Apofeozzz** [comment]
This error I got when trying to install version 7.0

![screen shot 2017-04-12 at 12 50 38 pm](https://cloud.githubusercontent.com/assets/19584788/24951964/bbb86c98-1f7e-11e7-8f8e-2fa50018d9c7.png)

**Comment by jaspermohl** [comment]
And if you update your pod repro?

So first:
$ pod repro update

And then:
$ pod install

**Comment by patchthecode** [comment]
@jaspermohl what do you mean it looks odd?

**Comment by patchthecode** [comment]
@Apofeozzz first do this:

`pod update`

then do 

`pod install`

I think your Pods are out of date.
Also do this and let me know

`pod --version`

**Comment by jaspermohl** [comment]
@patchthecode 

Sorry, I see now that the output of Cocoapods formats the line different than it can be in the podfile. I thought the line:
pod install 'JTAppleCalendar', '~>7.0' 
was written as:
pod install 'JTAppleCalendar, (~>7.0)' 
but this is just the way of displaying the output of Cocoapods in the CLI

**Comment by patchthecode** [comment]
@jaspermohl ah. I see. So does it work properly now for you :) ?

**Comment by jaspermohl** [comment]
@patchthecode 
For me it does, love working with your calendar!

**Comment by patchthecode** [comment]
@jaspermohl awesome. Thanks 👍

**Comment by patchthecode** [comment]
closing issue as resolved. Not a problem with calendar.
Problem was with outdated pods.
If any one is still having issues here then let me know.

**Comment by Prashanna7** [comment]
I have the same exact issue, i did the both of the things as mentioned above but still i am getting the error.

**Comment by patchthecode** [comment]
@Prashanna7 can you step through the code and see where the problem originates?

**Comment by Prashanna7** [comment]
I emailed you my whole project as you asked me to do so yesterday, got no response :(

**Comment by patchthecode** [comment]
Answering you on your open issue now.
