### ISSUE TITLE
insey

### ISSUE THREAD

**Issue by eyal88** [patchthecode/JTAppleCalendar#374]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.0
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
I closed it because no question was asked.
I assume this was created by accident? :)

**Comment by eyal88** [comment]
Yes, it was an accident :)
You have done great work here btw!

**Comment by patchthecode** [comment]
Thanks :)
