### ISSUE TITLE
Not able to access collectionView cell

### ISSUE THREAD

**Issue by TimeToCodeIos** [patchthecode/JTAppleCalendar#379]
I want to access collectionview cell which i have selected in range but i am not able to do it can you please suggest ?

**Comment by patchthecode** [comment]
When you select cells, you get access to them in the `didSelect` delegate function.
Can you explain a bit more of what you are trying to do?

**Comment by patchthecode** [comment]
Closing that as 3 days with no response.
If this is still an issue for you then re-open this issue and i'll help.

**Comment by alizainprasla** [comment]
@patchthecode How to access cell of selected dates cell?

For me. i have to access cell unique ID (property) which i add when cell dequeue

**Comment by patchthecode** [comment]
@alizainprasla what version of the app are you using.
And can you tell me how you are trying to access the cell? (what scenario)
