### ISSUE TITLE
Add the ability to set specific starting and ending dates for single row layout

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#38]
Right now it will give the entire month, it would be awesome to be able to set the minimum and maximum dates exactly (or at least go to min/max of given date weeks instead of month)

**Comment by patchthecode** [comment]
Ok. so here is the upgrade I am thinking for this.

For devs who choose:

1. 6-rows per month = 1 section per month
```
 ______
|______|      // There will be no option to limit the range. They already have the option to disable
|______|      // or hide the cells they don't want
|______|
|______|

```

2. 3-rows per month = 2 sections per month
```
 ______     ______
|______|   |______|  // They can limit the scroll for half the month
|______|   |______|
```

3. 2-rows per month = 3 sections per month
```
 ______   ______   ______
|______| |______| |______|  // They can limit up to 2 sections for the month
```
4. 1-row per month = 6 sections per month
```
|______| |______| |______| |______| |______| |______|  // They can limit up to 5 sections
```

Will work on this sometime soon.

**Comment by krisanthony** [comment]
This sounds great looking forward to seeing it in effect! Thank you

**Comment by krisanthony** [comment]
Hey man have you had a chance to look into this anymore?

**Comment by patchthecode** [comment]
Yea man. If you look in the issue section, there are many issues. Plus my own job. Will try looking into this over the weekend.

**Comment by krisanthony** [comment]
No pressure! I have been looking into using FSCalendar in the mean time, but your calendar is much more suited to creating the look I'mAnyway for. I love the idea of cells. Anyway, enjoy your weekend, I will be patient.

**Comment by patchthecode** [comment]
Understood. Enjoy your weekend as well dude.

**Comment by rpbrokaw** [comment]
I am interested in providing a calendar view that shows 3 weeks, regardless of month or sections. The behavior would be non-scrolling and show the current date in the first rows week and then the upcoming 2+ weeks following. Any pointers? Based on this issue, it seems that may be outside of the current design?

**Comment by patchthecode** [comment]
I am having a hard time following your design. You can join me [here in chat](https://gitter.im/patchthecode/JTAppleCalendar) as its faster. If you're unable to join, can you please be specific as to what is "3 weeks" ? How many rows and how many columns? Join chat though, its faster.

**Comment by idilgun** [comment]
I think my question is related to this issue so I'll join in - first thanks for all the great work @patchthecode ! <br>I want to setup functionality to have the user vertically scroll through all dates without having duplicate lines - I understand that most of the logic builds on separating views into months so I'm not sure if this is possible. I could set the visibility of specific cells but then I would have empty spaces.<br><br>To be more clear, indates and outdates for two consequtive months create a duplicate row and turning these off makes the row skip line from the end of first month to the beginning of second month. What I want is continuous cells even though the month changes<br>Again thanks a lot!

**Comment by patchthecode** [comment]
@idilgun ok issue is not related to this question here.
But I think i have a solution for you.
Can you reopen this same question under a new issue?

I will paste the answer to you there.

**Comment by patchthecode** [comment]
will track this in projects
