### ISSUE TITLE
The current date is UTC timezone which is deferent with system timezone?

### ISSUE THREAD

**Issue by kevinlee85** [patchthecode/JTAppleCalendar#382]
The current date is UTC timezone which is deferent with system timezone?
How to populate the system timezone to the calendar?

**Comment by patchthecode** [comment]
```swift
 func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = testCalendar.timeZone
        formatter.locale = testCalendar.locale
        
        
        let startDate = formatter.date(from: "2017 01 01")!
        let endDate = formatter.date(from: "2018 02 01")!

        let myCalendar = // Set up a calendar here with your custom time zone

        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: numberOfRows,
                                                 calendar: myCalendar)
        return parameters
    }

```

**Comment by patchthecode** [comment]
if you still have questions, then join here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by kevinlee85** [comment]
I am using Version6.0, and the calendar's timezone in ConfigurationParameters is correct, but the current time is one day ahead.

**Comment by kevinlee85** [comment]
![screen shot 2017-04-17 at 8 34 23 pm](https://cloud.githubusercontent.com/assets/6616311/25113574/45e34b86-23ad-11e7-816c-6c0839b2ca5f.png)

**Comment by kevinlee85** [comment]
My timezone is PDT which means UTC-7 , then my time is 4-17, but the calendar's today date is 4-18 which I think it UTC time. That means the calendar I set up by parameter is not working.

**Comment by patchthecode** [comment]
ok, 

Can you (from the debugger) do a `po` calendar command to print your NSCalendar instance on the console? 

run this on your console: `po Calendar.current`

Your output should look something like this:

▿ gregorian (fixed)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "fixed"
  ▿ locale : Optional<Locale>
    ▿ some : en_PH (fixed)
      - identifier : "en_PH"
      - kind : "fixed"
  ▿ timeZone : Asia/Manila (fixed)
    - identifier : "Asia/Manila"
    - kind : "fixed"
    ▿ abbreviation : Optional<String>
      - some : "GMT+8"
    - secondsFromGMT : 28800
    - isDaylightSavingTime : false
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1

I need this information so that I know how your date is showing up.

**Comment by kevinlee85** [comment]
(lldb) po Calendar.current
▿ gregorian (current)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "current"
  ▿ locale : Optional<Locale>
    ▿ some : en_US (current)
      - identifier : "en_US"
      - kind : "current"
  ▿ timeZone : America/Los_Angeles (current)
    - identifier : "America/Los_Angeles"
    - kind : "current"
    ▿ abbreviation : Optional<String>
      - some : "PDT"
    - secondsFromGMT : -25200
    - isDaylightSavingTime : true
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1

**Comment by patchthecode** [comment]
ok my time zone is the same as yours :) in Cali
And my dates are showing correctly.
So that means you might be doing something funky?

```
▿ gregorian (fixed)
  - identifier : Foundation.Calendar.Identifier.gregorian
  - kind : "fixed"
  ▿ locale : Optional<Locale>
    ▿ some :  (fixed)
      - identifier : ""
      - kind : "fixed"
  ▿ timeZone : America/Los_Angeles (fixed)
    - identifier : "America/Los_Angeles"
    - kind : "fixed"
    ▿ abbreviation : Optional<String>
      - some : "PDT"
    - secondsFromGMT : -25200
    - isDaylightSavingTime : true
  - firstWeekday : 1
  - minimumDaysInFirstWeek : 1
```

You can join me here if you're up -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by kevinlee85** [comment]
Did you test with version 6?

**Comment by patchthecode** [comment]
Oh sorry.. lol. I forgot.

but just to let you know, is you are using version `6.0`
That bug you are experiencing would have been fixed.

Take a look at the [ChangeLogs](https://github.com/patchthecode/JTAppleCalendar/blob/master/CHANGELOG.md#601) for version 6.1.0
I think i have fixed the issue you are experiencing in there

**Comment by patchthecode** [comment]
I believe the problem is that you are using an older version that does have the bug.
I can help you migrate to later versions if needed.
