### ISSUE TITLE
cellState.date not returning correct date after the calendar being scrolled - 6.1.6

### ISSUE THREAD

**Issue by aznelite89** [patchthecode/JTAppleCalendar#383]
Hi Jay, the cellState.date is only return the correct date if I have not move/scroll the calendar. if scroll to next month or other months, the cellState date is not return the correct date as the CGpoint point to. 

Thanks,
aznelite89

**Comment by patchthecode** [comment]
ok. some questions.

1. is your cal vertical or horizontal?
2. Can you paste me your `configureCalendar` function?

**Comment by aznelite89** [comment]
Hi Jay,

1. my calendar is vertical
2. 
`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let todayDate = Date().startOfDay
        let startDate = todayDate
        let endDate = todayDate + 6.months
        
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 6, calendar: Calendar.current, generateInDates: .forAllMonths, generateOutDates: .tillEndOfRow, firstDayOfWeek: .sunday, hasStrictBoundaries: false)
        
        return parameters
    }`

**Comment by patchthecode** [comment]
ok. will look at this in more detail over the weekend.
But just wondering, any chance you can update to version 7.0

**Comment by aznelite89** [comment]
ok I will try update to version 7.0
