### ISSUE TITLE
Single row weekly calendar has duplicated dates between 2 months

### ISSUE THREAD

**Issue by programus** [patchthecode/JTAppleCalendar#384]
version: 7.0.1

I want a weekly continuous scroll calendar in my project. And I read the document here: 
https://patchthecode.github.io/CalendarLayout/

So I set the configuration as 
```
let parameters = ConfigurationParameters(
    startDate: startDate, 
    endDate: endDate,     
    numberOfRows: 1,
    calendar: Calendar.current,
    generateInDates:  .forAllMonths,
    generateOutDates: .off,
    firstDayOfWeek:   .sunday,
    hasStrictBoundaries: false
)
```

But at the end of every month (at the same time the start of the next month), there are always duplicated dates of the previous month. 
Also, the weekday would be collapsed after these duplicated dates. 

![notice the 30th and 31th](http://i.imgur.com/mOOeCwK.png)
There are two 30th and 31th...

Is this a bug or I misunderstood the document, especially the meaning of `hasStrictBoundaries`?

**Comment by patchthecode** [comment]
Let me know if this helps :)

https://github.com/patchthecode/JTAppleCalendar/issues/143

**Comment by programus** [comment]
Thank you for your reply. I think I got your point. 

After I set the `generateInDates` to `forFirstMonthOnly`, I got exactly what I want. 

![A single row weekly calendar](http://i.imgur.com/XUALxsa.png)

Thank you very much!

It might be better for someone who want a weekly calendar like me if you put a single row weekly calendar configuration example in the document.

**Comment by patchthecode** [comment]
cool. cheers 🍻

**Comment by dipendra-sharma** [comment]
How it will workout if we have static day headers?

**Comment by patchthecode** [comment]
@dipendra-sharma 
this is the setup for a single row calendar -> https://github.com/patchthecode/JTAppleCalendar/issues/581
