### ISSUE TITLE
Can this library be used to create a calendar control for iPad?

### ISSUE THREAD

**Issue by Madhuvanth** [patchthecode/JTAppleCalendar#385]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.1
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Yes it can!! 😄 
closing this issue now :]

**Comment by Madhuvanth** [comment]
Thank you. Sorry, I was sure this was more of a question rather than an issue. But did not know another way to clarify it. Thanks again!

**Comment by patchthecode** [comment]
its cool.

**Comment by Madhuvanth** [comment]
Hello, I followed the steps from your video
<https://www.youtube.com/watch?v=zOphH-h-qCs&t=323s> and everything works
perfectly but for this- I am unable to see all the 6 rows. I will have to
click on one of the cells and then the 6th row of the grid shows up. Only
difference is that, I am developing an app for iPad and so obviously my
simulator is set to iPad.
Resizing height of the UICollectionView or resizing the height/width of the
cell itself does *not* solve the issue.﻿ Can you help please?

**Comment by patchthecode** [comment]
you will have to be a bit more descriptive :)

1. How many rows do you see?
2. What kind of scrolling do you have? vertical or horizontal
3. Do you have your calendar in a hierarchy that is hooked in with a UINavigation controller?

**Comment by Madhuvanth** [comment]
1. How many rows do you see? - 5 as soon as the simulator opens and the 6th row shows up as and when I click on one of the first 5 rows.

2. What kind of scrolling do you have? vertical or horizontal  - Horizontal

3. Do you have your calendar in a hierarchy that is hooked in with a UINavigation controller? - 
Yes.

4. Can you send me a zipped copy of the file you're working on?
After adding the day name (Sun, Mon, Tue etc..) headers now, issue seem to have been resolved. Would have been good to understand what exactly fixed it.

**Comment by patchthecode** [comment]
I do not think your issue is resolved.
i believe that this is the fix for your issue -> http://patchthecode.github.io/CommonProblems/

**Comment by Madhuvanth** [comment]
Ah, maybe the problem is not visible to me right now. Sure, shall implement this.

You're great! I shall also ensure, I have a look at 'common problems' (sorry did not know this exist, am new to GitHub) section before posting an issue.

**Comment by patchthecode** [comment]
its cool. 
let me know if it was fixed.

**Comment by Madhuvanth** [comment]
Hello,

As I said before, the problem (if it still exists) is not visible to me right now. It works perfectly even without unchecking 'Adjust scroll view insets'.

I need your help with another thing am trying to do. Am trying to segue to another view controller on selection of a cell.

Am able to achieve this using the follow steps.

1. Created a segue with an identifier in storyboard
2. In the function 'calendar(didSelectDate ....)',  used performSegue(withIdentifier: .....) 

And segue works perfectly on selection of a cell.

However, what I also need is, pass the selected cell to the destination view controller. I tried using prepareForSegue(...) method but I am unable to figure out how to pass the currently selected cell using prepareForSegue(...) method.

Can you give some ideas please?

**Comment by patchthecode** [comment]
the way you do it should be in the prepareForSegue(...) method.

and you should not pass the cell to the next viewController, you should pass the _information_ of the cell to the next view controller.

There are many sample codes online that is available which shows the process a lot better than i can explain here.

**Comment by Madhuvanth** [comment]
Thank you. That made me realise, all that I need is just the date text in the currently selected cell rather than the cell itself.

But I am actually struggling to find a way to retrieve the currently selected cell (and its properties such as dateLabel etc..) from within prepareForSegue method. Tried casting (posted the code below) the sender argument of the method but it does not seem to work.

/* Code snippet */

override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "showDetail" {
            
            
            let _ = (segue.destination as? UpdateHours)

           /* UpdateHours is class of the destination view controller and
              CustomCell is the model class for the cell within collectionview */

            let detailCell = sender as! CustomCell 
            
            
        }
    }

**Comment by Madhuvanth** [comment]
Fixed this by doing the below:

1. Created a variable and set it to currently selected cell's date label
2. Then passed on the new variable from with prepareForSegue(...) method

Thank you again!!
