### ISSUE TITLE
Swift 2, how to setup the cell? 

### ISSUE THREAD

**Issue by eyzuky** [patchthecode/JTAppleCalendar#388]
Unfortunately, I am  using version 5.0.1.
I am looking for a code example and it seems like there is no code example for Swift 2 at all.
My issue is that I do not understand how to setup the view for the cell. 
I get my crash here:

```swift
    public func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        restoreSelectionStateForCellAtIndexPath(indexPath)
        
        let cell = collectionView.dequeueReusableCellWithReuseIdentifier(cellReuseIdentifier, forIndexPath: indexPath) as! JTAppleDayCell
        
        cell.setupView(cellViewSource) // crash
        cell.updateCellView(cellInset.x, cellInsetY: cellInset.y)
        cell.bounds.origin = CGPoint(x: 0, y: 0)
        
        let date = dateFromPath(indexPath)!
        let cellState = cellStateFromIndexPath(indexPath, withDate: date)
        
        delegate?.calendar(self, isAboutToDisplayCell: cell.view!, date: date, cellState: cellState)

        return cell
    }
```
In a tutorial I found on Youtube, I return the cell in one of the delegate functions. in swift 2 it seems automatic. I do not understand how to set it.
any help is appreciated!

**Comment by patchthecode** [comment]
Have you looked at the tutorials here? -> http://patchthecode.github.io/
Scroll down and look at the documentation for version 6.

then click on these two

<img width="495" alt="screen shot 2017-04-23 at 7 04 32 am" src="https://cloud.githubusercontent.com/assets/2439146/25314145/2868a2f0-27f3-11e7-993f-c1068dde1e0d.png">

Although it is for version 6. It has the closest documentation that is similar to 5.

BTW, Im wondering why youre still on swift 2? :/

**Comment by eyzuky** [comment]
I work for a company that gives app developing services to companies. This App was not developed by me, but I was asked to add a calendar feature.. It is a huge app that is built with Swift 2, and i cannot afford the time to convert it to Swift 3 (actually they already tried to do that but it was too complicated).
thanks for the response, I will check it out

**Comment by eyzuky** [comment]
@patchthecode  Hey, one of my problems were that this function is unresolved in Swift 2 version:

`ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6, // Only 1, 2, 3, & 6 are allowed
            calendar: NSCalendar.current,
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: .sunday)`

So I understand that I may need to return a Tuple instead of that?
I managed to get the calendar to present itself(Yey!) but all the labels are the same (as declared in the UILabel in the xib)

**Comment by patchthecode** [comment]
you can join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Also, you know, why dont you download the example project on github?
I have a sample project attached to every release that i do.

Go here -> https://github.com/patchthecode/JTAppleCalendar/tree/5.0.1

And click on the green download button.
Then open the sample project, and see the code in there and copy it.
