### ISSUE TITLE
The very first scrolling back after view loaded does not work correctly

### ISSUE THREAD

**Issue by programus** [patchthecode/JTAppleCalendar#389]
Version: 7.0.1

I setup my calendar like this: 
```swift
let parameters = ConfigurationParameters(
    startDate: startDate, 
    endDate: endDate,     
    numberOfRows: 1,
    calendar: Calendar.current,
    generateInDates:  .forFirstMonthOnly,
    generateOutDates: .off,
    firstDayOfWeek:   .sunday,
    hasStrictBoundaries: false
)
```

And I want the calendar to show and select current day (2017-04-24) by putting the code in `viewDidLoad()`
```swift
        self.calendarView.scrollingMode = .stopAtEachSection        
        self.calendarView.selectDates([Date()])
        self.calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: true, animateScroll: false)
```

Then, I tried it and get this kind of motion
![first scroll does not work correctly.](http://i.imgur.com/tOsOfyb.gif)

You will find that the first scrolling after the view displayed does not scroll and jump back to the previous section. After the first scrolling, everything works just very well. 

You can find the code I reproduce this problem here: https://github.com/programus/JTAppleCalendar/commit/a19ea670302ebfa1cd7d1866c37bdc6e05a335ea

ps. I checked out the latest master branch, and the problem seems disappeared. Whereas I want to keep using carthage to mange frameworks, do you have any advice better than waiting next release?

**Comment by patchthecode** [comment]
I fix any issue that I find on the master branch.
Since you use Carthage, you can use the master branch.

As for the issue,
Let me double check to see it my self -> https://github.com/programus/JTAppleCalendar/commit/a19ea670302ebfa1cd7d1866c37bdc6e05a335ea

I will respond to you soon.

**Comment by patchthecode** [comment]
closing issue as is fixed on master branch
