### ISSUE TITLE
(VERSION 7) Pre selected dates

### ISSUE THREAD

**Issue by IsabelaLiberatoscioli** [patchthecode/JTAppleCalendar#392]
Hello, I update my library from version 4 to 7. I have a screen which can be used to edit the selected dates. This screen should show the previous dates selected in the calendar when opened, it was working before, but now I am not able to show the selected dates when screen opens. I had this code in my viewDidLoad:

   self.calendarView.selectDates(dates) 

 Already tried using:
   
    self.calendarView.selectDates(dates, triggerSelectionDelegate: true, keepSelectionIfMultiSelectionAllowed: true)

Before the changes, didSelected function was triggered when selectDates was called, but now it is not anymore, am I missing something? When I go to next month, didSelected is triggered and the selected dates appears highlighted on calendar.

**Comment by patchthecode** [comment]
the function names has changed in version 7.0
is the name of the function that you are using this?
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState)
```

**Comment by IsabelaLiberatoscioli** [comment]
Yes it is, I believe it would not even compile if that was wrong.
   Do I need to call some kind of reload or something like this?
  
Thanks

**Comment by patchthecode** [comment]
If it was wrong, it will still compile, because that function is not mandatory.
And no you do not need to call reload.

I can help you more with this on chat here -> https://gitter.im/patchthecode/JTAppleCalendar
But i only will be able to chat after work in about 5hrs

**Comment by patchthecode** [comment]
If you project is very small, and you can zip a copy, then you can send me a copy here. Just drag the zipped project in this chat box. But, if your project is already secret, then you'll have to wait until I finish work for the chatroom.

**Comment by IsabelaLiberatoscioli** [comment]
Hi, I can't send you the project :(
   I will wait you. 
   The screen is pretty simple and everything else is working, when user select or deselect other dates, it all works, the only problem is when opening the screen, some dates have to be shown selected and it is not happening. It was working before. It looks like something is not being triggered. 
   Question: as I call  selectDates(dates) on viewDidLoad, when cellForItemAt runs some of its cellState.isSelected would be true for the dates in select dates? Or it would have to work as version 4 that selectDates(dates) triggered the didSelectDate?

Thanks

**Comment by patchthecode** [comment]
can you put this in your `Podfile` and do a `pod install`

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

If this does not fix the issue, then i'll be on chat after work.
cheers 🍻

**Comment by patchthecode** [comment]
As a comparison Here is the differences between version 4 and version 7's delegate function

version 6
```swift
func calendar(calendar : JTAppleCalendarView, didSelectDate date : NSDate, cell: JTAppleDayCellView?, cellState: CellState)
```

version 7
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState)
```

**Comment by IsabelaLiberatoscioli** [comment]
Hello, sorry, I wasn't able to work on the app yesterday, that's why I didn't reply.
 I'm using the right version of the method, I will now try this branch you suggested.

Thanks

**Comment by IsabelaLiberatoscioli** [comment]
Uhu! With this branch everything works now :-)
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
Thank you very much!

**Comment by patchthecode** [comment]
awesome. Closing this issue now. :)
Have  good one. 🍻
