### ISSUE TITLE
In Range Selection if user select range of 10 month , calendar is taking time to load

### ISSUE THREAD

**Issue by TimeToCodeIos** [patchthecode/JTAppleCalendar#394]
Calendar is taking time in loading when scrolling  and also getting stuck for moment when scroll when user select too long range can you please suggest solution?

**Comment by patchthecode** [comment]
:)
you know.. its very hard to suggest a solution when you have only described the problem in just one short sentence.

Can we at least start with the following?
1. How many dates are you generating (your start date and end date)
2. how are you scrolling? programatic? manual?
3. How many dates are you selecting?
4. What version of the calendar are you using?
 etc etc etc.

I can help you a bit more if you describe the problem in programmer lingo.

**Comment by TimeToCodeIos** [comment]
I am using 6.0.5 version 

 i am using this calendar for selecting trip length so it can be of max 11 months so at that time user will select 11 months.

**Comment by patchthecode** [comment]
Hmm. youre using an older version.
If you look at the [ChangeLogs](https://github.com/patchthecode/JTAppleCalendar/blob/master/CHANGELOG.md), many versions were done after this. They include performance improvements etc.

Is it possible you can update?

**Comment by TimeToCodeIos** [comment]
No because in update you have changed alot and i have implement it with 6.0.5 version like first you have provided HeaderView but now it is changed new version so i am getting alot of errors can you please suggest any other solution??

**Comment by patchthecode** [comment]
Here are some solutions.
1. Update to 7.0 -> if you let me know a time on weekend i can help you convert your project easily.
2. Update to version 6.1.6 -> this version have not changed very much. However i am not sure if the enhancements are made there
3. I will have to take a look at you 6.0.5 version over the weekend, and _hope_ i can come up with a fix in time.

**Comment by TimeToCodeIos** [comment]
Hi,
      Thank you for being such abetting.....It will be more helpful if you can support with **option 3**

**Comment by patchthecode** [comment]
A lot has happened since your post.
The changes since version 6.0.5 is massive. 
I will not have to time to go back to such an older version.
But i will be available to help convert your project to 7.0
There are just too many enhancements done in that version.

**Comment by patchthecode** [comment]
Closing this issue until more user input. It is 22 days since last response.
