### ISSUE TITLE
How to customise number of columns ?

### ISSUE THREAD

**Issue by iOSUser110** [patchthecode/JTAppleCalendar#396]
Can we customise number of columns, like we can customise number of row ,
instead of showing 7 days in week, want to show the last 5 days only in a row as below screenshot

<img width="201" alt="screen shot 2017-04-28 at 4 04 19 pm" src="https://cloud.githubusercontent.com/assets/2657399/25525408/5f8b2ae0-2c2c-11e7-977c-eadb0d4f94ab.png">
 

and also if I select 15 days (start :15 Jan , End : 30 Jan ) , it is showing complete month as active dates, I want only 15 days . means only those which are from start date and end date

This library is very interesting , very helpful to achieve  what we want. Thanks a lot

**Comment by patchthecode** [comment]
1. Unfortunately, it only has a 7 column month for now. But if someone can programatically describe for me how a column of a different number can be achieved i'l be glad to implement it.

2. Concerning the 15 days, it sounds like you just want to implement a [date boundary](https://github.com/patchthecode/JTAppleCalendar/issues/365)?

**Comment by iOSUser110** [comment]
as in my shared UI ,
Can I start the row with 15 April (instead of 1st April )? 
I didn't find solution  for this.

**Comment by patchthecode** [comment]
Simply scroll to April 15.

`calendarView.scrollToDate(theDateWithApril15)`

**Comment by iOSUser110** [comment]
but using this only we can scroll upto the segment which contains date April 15 , 
It is not making April 15 as starting element of visible segment for Week View

**Comment by patchthecode** [comment]
@iOSUser110 what is visible first is based on your scrolling mode -> https://patchthecode.github.io/CalendarScrolling/

Can you try changing your scrolling mode to `.none` ?

**Comment by patchthecode** [comment]
Also, i was thinking, it might be possible to show less columns.

**Comment by patchthecode** [comment]
Closing issue.
If this is still a problem for you then respond here, and I will re-open this.
More than 5 days has passed with no user-input
