### ISSUE TITLE
Deselect all selectedDates

### ISSUE THREAD

**Issue by maryamfekri** [patchthecode/JTAppleCalendar#397]
I wan to reset all the selectedDates, in other word I want to deselect all the selected dates. 
I tried calling :  
`calenderView.deselectAllDates()`  
but this will deselect just the first date . 
what should I call ? and why is it just deselecting my first date, after calling several times this function will remove all dates. but this is not what I wanted. 
Could you please give me some clarification or help me to have the functionality I need .

FYI : the calendar view is in multiple selection mode.

**Comment by maryamfekri** [comment]
okay, I got the solution as below : 
` calenderView.deselectAllDates(triggerSelectionDelegate: false) `

**Comment by patchthecode** [comment]
@maryamfekri 
I am assuming that you are using version `7.0`
calendarView.deselectAllDates()` should work by itself out of the box.

**Comment by maryamfekri** [comment]
No my version is 6.1.6, because of some reasons I cannot update to latest versions and I forgot to tell you my version.
BTW thanks for the quick and accurate responses each time.

**Comment by jasperpogi02** [comment]
I want to deselect previously selected date when user selected a new date.

I am using JTAppleCalendar 7.0.6
with deselection code:
myCalendar.deselectAllDates(triggerSelectionDelegate: false) inside shouldSelectDate function

the problem is I am encountering an infinite loop whenever i call that function

**Comment by patchthecode** [comment]
@jasperpogi02 can you tell me which part is triggering the infinite loop?

**Comment by jasperpogi02** [comment]
if I get it right you are asking for the functions that is runs on the thread. Here it is:

myCalendar.deselectAllDates(triggerSelectionDelegate: false) -> shouldSelectItemAt -> selectDates -> deselect -> myCalendar.deselectAllDates(triggerSelectionDelegate: false) -> .....

**Specific Line of Code that triggered the error:**
![screen shot 2017-08-11 at 12 25 08 pm](https://user-images.githubusercontent.com/5517897/29201356-27148ad8-7e90-11e7-8f37-b803b2a2f14b.png)
![screen shot 2017-08-11 at 12 22 51 pm](https://user-images.githubusercontent.com/5517897/29201323-d71479da-7e8f-11e7-8742-d5aff0ff9cf7.png)

**Thread Screenshots:**
![screen shot 2017-08-11 at 12 23 47 pm](https://user-images.githubusercontent.com/5517897/29201339-fbe8a8a8-7e8f-11e7-9b3e-413c10d2572b.png)
![screen shot 2017-08-11 at 12 23 58 pm](https://user-images.githubusercontent.com/5517897/29201351-15a4c506-7e90-11e7-80e0-3ad2fb229d71.png)

**Comment by jaspergoce** [comment]
please disregard my issue. I have found a new way of doing it. :) thanks....

**Comment by patchthecode** [comment]
was it a library error/?

**Comment by jasperpogi02** [comment]
nope, the error was my brain :)

I am now making use of allowsMultipleSelection variable. Thanks btw. I think we can release our app now. hahaha

**Comment by alizainprasla** [comment]
I am using JTAppleCalendar 6.1.6. On deselect app is crashing

**Comment by patchthecode** [comment]
@alizainprasla 

1. what crash are you seeing? Without information about the crash. I cannot help much.
2. Is it possible you can upgrade your app to version 7 ?

All these issues have been fixed in that version.

**Comment by alizainprasla** [comment]
@patchthecode i am deselecting my range selection in

 **func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleDayCellView, cellState: CellState) -> Bool {**

Delegate. Is there anything i am doing wrong? or should i update to newer version


![screen shot 2017-09-12 at 9 05 31 pm](https://user-images.githubusercontent.com/820419/30336299-3665e0c2-97fe-11e7-8f41-ae4a900ab499.png)
![screen shot 2017-09-12 at 9 05 39 pm](https://user-images.githubusercontent.com/820419/30336298-3661c8de-97fe-11e7-9288-b949360c475a.png)
![screen shot 2017-09-12 at 9 05 50 pm](https://user-images.githubusercontent.com/820419/30336301-36861efa-97fe-11e7-8043-ff96f1a68871.png)

**Comment by patchthecode** [comment]
@alizainprasla updating to a newer version fixes *many* issues.

However, version 7.0 contains breaking changes. 
I can help you migrate if needed.

**Comment by alizainprasla** [comment]
@patchthecode I have change my code to 7+, However by selecting one date. i select range date but i also want to deselect other selected dates. thats what doing these crash.

How to deselect date on my scenario?

**Comment by patchthecode** [comment]
@alizainprasla im back.
If youre up, can you join me here? https://gitter.im/patchthecode/JTAppleCalendar
