### ISSUE TITLE
crowded with cells after second rotation of the view

### ISSUE THREAD

**Issue by j-ice** [patchthecode/JTAppleCalendar#400]
Dear Jay,

thanks for your decent pod! Since v6.1.3 I am observing the following behavior:

I start the calendar in one orientation. All cells were indented as expected.
![jtapplecalendar_orientation1](https://cloud.githubusercontent.com/assets/28293269/25614324/d0473faa-2f31-11e7-969e-34cde255f9fb.png)
After rotating the device in one direction, sometimes the cells are indented as expected, sometimes it is like in this screenshot: 
![jtapplecalendar_orientation2](https://cloud.githubusercontent.com/assets/28293269/25614388/fe39081c-2f31-11e7-8ede-13a4417b79e8.png)
But in both cases I am observing an issue. After rotating the device again to another orientation, the view is crowded with cells at various positions:
![jtapplecalendar_orientation3](https://cloud.githubusercontent.com/assets/28293269/25614402/09270cf6-2f32-11e7-9b4c-bdc1332fc96e.png)

After rotating the device there is a new (since v6.1.3) resizing behavior with a blank screen towards the lower end of the view. Once the resizing is completed the issue occurs.
![jtapplecalendar_orientation2-3](https://cloud.githubusercontent.com/assets/28293269/25615292/acfbb3f0-2f36-11e7-8c2b-2dd54054c034.png)

I can only reproduce this behavior on an iPhone (and iPhone simulator). On the iPad I cannot observe that issue. It occurred first on v6.1.3. Up to v6.1.2 the cells were indented correctly and it worked fine.

Is this the behavior you described at point 4 in "common questions": "My views are being randomly repeated across dateCells"?

Thanks in advance!
János

**Comment by patchthecode** [comment]
the highest version 6 is version 6.1.6

Also, all errors like this has been fix in version 7.
Is it possible that you can update?

**Comment by j-ice** [comment]
Yes, this effect is also there on 6.1.6. It was introduced with version 6.1.13.

Unfortunately, I cannot update to version 7 given the lack of support for iOS 8.
Do you have an easy workaround for that effect? 
Otherwise I would simply stay on v6.1.12 and update to the recent version after increasing my deployment target.

**Comment by patchthecode** [comment]
See the thing is, version 6 is good. But there are issues that needs to be fixed.
This is why i completely re-engineered version 7.0 from the ground up. All issues like this are fixed.

Lets get version 7 compatible for you.
is the compatibility problem because of this variable in the 7.0 library? --> `semanticContentAttribute`

If it is, then I can make version 7 to be iOS 8 compatible for you.

**Comment by patchthecode** [comment]
closing until user responds.
