### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by jlgaustin** [patchthecode/JTAppleCalendar#401]
*****************************************************
UPDATE: I copied the storyboard and ViewController.swift from the iOS example project you provide into my project and tried both pushing and displaying modally and the same failure happens.
*****************************************************
JTAppleCalendar version 7.0.2 installed via cocapods
Swift 3.1, Xcode 8.3.2

I followed the youtube example exactly, double checked twice.   Upon running app crashes with following.

2017-05-02 13:35:10.576 LifeGPS[56788:3363276] *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/UICollectionViewData.m:433
2017-05-02 13:35:22.520 LifeGPS[56788:3363276] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x600000226f40> {length = 2, path = 0 - 0}'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112a17b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000111c68141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112a1bcf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001118023b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000011460a23d __45-[UICollectionViewData validateLayoutInRect:]_block_invoke + 1743
	5   UIKit                               0x00000001146095e9 -[UICollectionViewData validateLayoutInRect:] + 2964
	6   UIKit                               0x00000001145b13ca -[UICollectionView layoutSubviews] + 233
	7   JTAppleCalendar                     0x0000000110b767a4 _TFC15JTAppleCalendar19JTAppleCalendarView14layoutSubviewsfT_T_ + 84
	8   JTAppleCalendar                     0x0000000110b76bf2 _TToFC15JTAppleCalendar19JTAppleCalendarView14layoutSubviewsfT_T_ + 34
	9   UIKit                               0x0000000113d3820b -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1268
	10  QuartzCore                          0x0000000113992904 -[CALayer layoutSublayers] + 146
	11  QuartzCore                          0x0000000113986526 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 370
	12  QuartzCore                          0x00000001139863a0 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	13  QuartzCore                          0x0000000113915e92 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
	14  QuartzCore                          0x0000000113942130 _ZN2CA11Transaction6commitEv + 468
	15  UIKit                               0x0000000113ca0313 _afterCACommitHandler + 272
	16  CoreFoundation                      0x00000001129bd717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x00000001129bd687 __CFRunLoopDoObservers + 391
	18  CoreFoundation                      0x00000001129a2720 __CFRunLoopRun + 1200
	19  CoreFoundation                      0x00000001129a2016 CFRunLoopRunSpecific + 406
	20  GraphicsServices                    0x000000011718ea24 GSEventRunModal + 62
	21  UIKit                               0x0000000113c750d4 UIApplicationMain + 159
	22  LifeGPS                             0x000000010f7bc7e7 main + 55
	23  libdyld.dylib                       0x000000011662965d start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by patchthecode** [comment]
Can you provide an example with this crash?

or  do you experience this crash if you build your own calendar without copying the example?

**Comment by jlgaustin** [comment]
I can't send the actual project code I am using.   I can try to start a new example project and see if I can replicate it.   

Yes I get a crash regardless.   I tried my own implementation first, but basically following the example on youtube, then I downloaded the example code and copied that View controller and storyboard over, that ones crashes in exact same spot.

**Comment by patchthecode** [comment]
I can tell you that if you provide a sample code with the problem, I will fix it right away.

**Comment by patchthecode** [comment]
closing this issue.
If you still have issues with this then do let me know.
But i suspect the library was not correctly hooked up on InterfaceBuilder

**Comment by SteveTIS** [comment]
Good day
I use the same version of Swift & XCode, and got the same error shown above.
 
I am following the replies of "Crash issue #401" , but I did not find the solution for the Crash issue.
Where I could find the solution?

Thank you so much!

**Comment by patchthecode** [comment]
@SteveTIS did you build you projecct from scratch as shown in the video play list? -> [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)  

I have noticed that sometimes when this happens, it is because devs just copy the project. Let me know in which part of the vid tutorials it fails for you. Then i can know at which step a mistake was made.

**Comment by SteveTIS** [comment]
Yes, I built my project from scratch from your video.
I will rebuild new project using your web path

Thanks a lot for your kind reply!
