### ISSUE TITLE
Calendar with 1 row shows next months with incomplete dates

### ISSUE THREAD

**Issue by gabrielrf97** [patchthecode/JTAppleCalendar#402]
Dear Jay, 

First of all, thank you. This pods represents a remarkable job of your part.

Im using 7.0 Version of it to create a calendar, and here's the deal, when I selected the calendar so it will be built with just 1 row, it shows incomplete dates on the following month.

<img width="369" alt="captura de tela 2017-05-02 15 49 49" src="https://cloud.githubusercontent.com/assets/18087251/25633907/1d0d3480-2f4f-11e7-9e17-fb4c10e7d6e1.png">

In this example, I scrolled from the current month, to the next one, and It seems like that, incomplete.

Also tried again, in a simpler project, just to check out if the problem might be in the configuration of the previous project, therefore, I got the same result
<img width="306" alt="captura de tela 2017-05-02 15 55 15" src="https://cloud.githubusercontent.com/assets/18087251/25634111/cc1513ee-2f4f-11e7-8db3-e001a17e1877.png">

I understand that I might have made some mistake, and thats why im coming here for help, although I have been following the 3 tutorials you gave as suggestion.

Best regards, Gabriel.

**Comment by patchthecode** [comment]
Can you paste your `configureCalendar` code for your calendar?

**Comment by gabrielrf97** [comment]
Jay, i checked the issue, isn't the same.
There, he has to scroll twice. In mine, doesn't matter how many times i scroll, cause it shows incomplete dates, anyway, here is my `configureCalendar` code

  ```
  func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
    
        formatter.dateFormat = "yyyy MM dd"
        formatter.locale = Calendar.current.locale
        formatter.timeZone = Calendar.current.timeZone
        
        
        let startDate = formatter.date(from: "2017 01 01")
        let endDate = formatter.date(from: "2018 12 31")
        
        let parameters = ConfigurationParameters(startDate: startDate!,
                                                 endDate: endDate!,
                                                 numberOfRows: 1,
                                                generateOutDates: OutDateCellGeneration.off)
        
        return parameters
    }
```

i've already tried without the `generateOutDates` parameter, but it doesn't make the calendar work properly as well.

Once again, thank you

**Comment by patchthecode** [comment]
If you provide a zip file with the problem here, i can return you a fix in 1 hour.
You can drag the zip file in here.

**Comment by patchthecode** [comment]
I just saw the issue now that im free.
This isnt a bug.
Can you just set the generateInDates to = off ?

**Comment by patchthecode** [comment]
Closing this issue.
If this is still a problem for you then respond and I will continue where I left off.
Have a good one. 🍻
