### ISSUE TITLE
How to set Current month?

### ISSUE THREAD

**Issue by kunass2** [patchthecode/JTAppleCalendar#404]
Please indicate me how to set calendar to show current month? Suppose we have march 2017, and in my calendar start date is january 2017 and end date is december 2017.

Currently it always show me january 2017 on load.

**Comment by ggirotto** [comment]
I use like this: `yourCalendar.scrollToDate(Date.init())`
Dont know if it has a better option @patchthecode

**Comment by kunass2** [comment]
Ok, thanks, and do you know how to reload current visible dates, not a whole calendar?

**Comment by ggirotto** [comment]
calendarUpdate() only reload the visible cells

**Comment by kunass2** [comment]
calendarUpdate() ? What object has that method? Because calendar doesnt have.

**Comment by ggirotto** [comment]
I've edit, its **reloadData** the correct method

**Comment by kunass2** [comment]
ok:) thank you...

**Comment by patchthecode** [comment]
What @ggirotto said is correct.
Although i would just do 
```swift
yourCalendar.scrollToDate(Date())
```
instead of `Date.init()`

Closing this issue as it is resolved.

**Comment by jeffersonsetiawan** [comment]
Hi @patchthecode , when I use the scrollToDate, there was an animation that animate scrolling from the first available month, to the month I want to view it, can we just setup the visible month without animation??

**Comment by patchthecode** [comment]
yes.
every function in this library almost always have a lot optional parameters.

try this
`calendarView.scrollToDate(theDate, animateScroll: false)`

**Comment by jeffersonsetiawan** [comment]
great!! thank you @patchthecode for the fast response!! 👍

**Comment by ajinkya92** [comment]
### How can I add events based on weekdays? My server sends me values such as 1,2,3,4,5,6,7 which corresponds to Mon, Tues, Wed, Thu... If the value is 1 then I want to show a green dot on all Mondays and so on.
Somebody, please help...
