### ISSUE TITLE
selectDates function triggers didSelectDate but doesn't pass the cell object

### ISSUE THREAD

**Issue by seyfeddin** [patchthecode/JTAppleCalendar#406]
Using 7.0.2

When I call

```swift
self.calendarView.selectDates(<Date from monthly dates>, triggerSelectionDelegate: true, keepSelectionIfMultiSelectionAllowed: true)
```

the delegate method doesn't provide the cell object. I need the cell object to change the colors depending on the selection. When I tap on a cell, it works as expected.

**Comment by patchthecode** [comment]
can you just do this?
```swift
self.calendarView.selectDates(<Date from monthly dates>)
```

**Comment by seyfeddin** [comment]
@patchthecode I've tried that, didn't pass the cell again. It sends the correct date and cellState though.

**Comment by patchthecode** [comment]
can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar
