### ISSUE TITLE
Video Tutorial Error with handleCellSelected() - [See updated code here]

### ISSUE THREAD

**Issue by dmholmes** [patchthecode/JTAppleCalendar#409]
In the video tutorial CellState.isSelected is properly used until code is refactored into helper functions. At that point Cell.isSelected is used. This worked for most months until I hit a month where it didn't.

**Comment by patchthecode** [comment]
can you let me know by joining me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
There is an error in the `handleCellTextColor` function. Please replace it with the following code:

```swift
func handleCellTextColor(view: JTAppleCell?, cellState: CellState) {
}
```

**Comment by patchthecode** [comment]
@dmholmes hey, i am trying to remember for which month you were experiencing `cell.isSelected` failure at? In version 7.0.3 i made `isSelected` unavailable for the cell, but some users were using it it seems. So i want to look into the issue a bit deeper.

**Comment by dmholmes** [comment]
IIRC it wasn’t related to a specific month in particular.

**Comment by patchthecode** [comment]
ok thanks. i'll look more into the problem on my end.

**Comment by beajco** [comment]
Same issue here sir.

**Comment by beajco** [comment]
after I update my code base on your given code. I still have the same exp

**Comment by beajco** [comment]
I think it happens when I select a date that is in the current view and the view when I scroll to left or right

Example:
I selected dec 1
and when i Scroll to the left
the cell I selected is still in that view
then if u select another cell. thats the error happens

**Comment by patchthecode** [comment]
what error happens?
