### ISSUE TITLE
ConfigurationParameters.firstDayOfWeek not working when in/out dates are not generated

### ISSUE THREAD

**Issue by popodidi** [patchthecode/JTAppleCalendar#410]
Hi,
First of all, thanks for this great pod.

I am in the version 7.0.2 and I have a problem when calendar is in one row mode.
I aim to make an app where users can switch between week/month mode of the calendar. I call `calendarView.reloadData()` when users switch between modes and return different `ConfigurationParameters` for each.
It seems that the `firstDayOfWeek` parameter I passed when initializing `ConfigurationParameters` is not working.

```swift
/*
 variable I use to store the state of week/month mode
  - true: month mode
  - false: week mode
 */
var calendarIsExpanded: Bool = true
```

JTAppleCalendarViewDataSource
```swift
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let startDate = Date()
        let endDate = Date().addingTimeInterval(100000000)
        if !calendarIsExpanded {
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 1, generateInDates: .off, generateOutDates: .off, firstDayOfWeek: .sunday)
        } else {
            return ConfigurationParameters(startDate: startDate, endDate:
                endDate, numberOfRows: 6, firstDayOfWeek: .sunday)
        }
        
    }
```

And it turns out that when `!calendarIsExpanded`, the `firstDayOfWeek` is always `.monday`.

In month mode, it works nicely.
![simulator screen shot 11 may 2017 3 48 40 pm](https://cloud.githubusercontent.com/assets/8709463/25938318/5e993f84-3661-11e7-9f47-f8566b7aec50.png)

In week mode, you can see there is one day shift from the previous one
![simulator screen shot 11 may 2017 3 48 31 pm](https://cloud.githubusercontent.com/assets/8709463/25938326/6918c16e-3661-11e7-8ebc-3d9eaecf2e01.png)

**Comment by popodidi** [comment]
Oops, there is a typo.
In case you are confused, `Sub` should be `Sun` in the picture.

**Comment by patchthecode** [comment]
Hmm. I think you might misunderstand the inDates/outDates for single row calendars.

I assume the S|M|T|W|T|F|S  header is created by you and is not managed by the calendar right?
So i think the single row configuration should look like this:

```swift
return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 1, generateInDates: .forFirstMonthOnly, generateOutDates: .off, firstDayOfWeek: .sunday)
```

**Comment by popodidi** [comment]
Thanks a lot , it works!

Yes, the headers are not managed by the calendar. Could you please explain me bit that how is the calendar changed by setting `generateInDates: .forFirstMonthOnly`? And to be honest, I really don't have a concrete idea of what `inDates`/`outDates` is in single row calendars 😕

**Comment by patchthecode** [comment]
Ah. well since I have typed it many times this vid will explain -> https://www.youtube.com/watch?v=1Sta3aEo9E4

As well as this issue -> https://github.com/patchthecode/JTAppleCalendar/issues/384#issuecomment-294857340

**Comment by patchthecode** [comment]
Cool 🍻
