### ISSUE TITLE
Error in date

### ISSUE THREAD

**Issue by Zukka** [patchthecode/JTAppleCalendar#412]
I use the latest version of JTAppleCalendar.
I download the sample code and when I click on a calendar date I print the day before, for example I tap on 25 April and in console I see 24 April, I check on Simulator and on device.

IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.2
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
4. Don't just ask a question. Provide enough information so I will be able to recreate the problem you are facing. 
   It would be even better if you provided an example app if possible.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
hey, there is no error in date -> Read you can read more on the issue here https://github.com/patchthecode/JTAppleCalendar/issues/252

Closing this issue. But if you need more help on this then do let me know.
