### ISSUE TITLE
JTAppleCalendar today button problem

### ISSUE THREAD

**Issue by sszi** [patchthecode/JTAppleCalendar#414]
Hi

I am creating a program using JTAppleCalendar.

When I press the today button on the calendar, I move to today's date and I want to draw a border on today's datecell

CalendarView.scrollToDate (Date ()) will show the current month, but I can not draw a border on today's datecell. I want to get cellView of today's date. What should I do?

There is no way I can look at it anymore. 

```swift
func calendar (_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState)
    If sel! .year == displaycell.year && sel! .month == displaycell.month && sel! .day == displaycell.day {
        MyCustomCell.selectedTopView.isHidden = false
        MyCustomCell.selectedBottomView.isHidden = false
        MyCustomCell.selectedLeftView.isHidden = false
        MyCustomCell.selectedRightView.isHidden = false
    }
    //....
}
```

If you give calendarView.reloadData () because it can not be reloaded even though it is displayed, the saved Date [] value becomes strange.

I would like some advice on this.

Thank you.

**Comment by patchthecode** [comment]
What version of the calendar are you using? And is it possible you can use version 7.0?
You can message me here -> https://gitter.im/patchthecode/JTAppleCalendar if youre online

**Comment by BarryBryant** [comment]
I may be misunderstanding the question here, however when I initialize my calendar I scroll to the current month and select the current date. So the calendar automatically appears with the current month shown and the current date cell highlighted. I do this by calling `let todaysDate = Date()` `scrollToDate(todaysDate)` and `selectDates(from: todaysDate, to: todaysDate)`

**Comment by patchthecode** [comment]
inside the `willDisplayCell`

put something like:
```swift
if date == todaysDate {
    // Draw a border around the cell
}
```
