### ISSUE TITLE
issues with Xcode 8.1

### ISSUE THREAD

**Issue by shala7** [patchthecode/JTAppleCalendar#415]
why not work library 6.1.5
with Xcode 8.1

**Comment by patchthecode** [comment]
have you tried version 6.1.6?

or have you updated to version 7.0?

**Comment by karthikallsmart** [comment]
I am also getting same issue. 
why not work library 6.1.5
with Xcode 8.2.1

**Comment by patchthecode** [comment]
Version 7 is the final version of the library. No more major updates will be done after this. It is will be compatible with XCode 8+
We should upgrade to version 7.

I am unable to maintain 2 major versions of this library as I am only one person. But if you guys submit the pull request to make it compatible then I can merge it.
