### ISSUE TITLE
ScrollToDate

### ISSUE THREAD

**Issue by mwurm93** [patchthecode/JTAppleCalendar#416]
Using the ScrollToDate method to scroll to previously selected dates, which, when in the middle of the week, brings me to the middle of the month section. How can I scroll to a specific month (and ensure the whole month is shown, with only indates of the previous month and outdates of the following month showing).

JTAppleCalendar Version 6.0

Thanks for your help,
Mike

**Comment by patchthecode** [comment]
ok.

1. Is your calendar vertical/horizontal?
2. Does your calendar have headers?
3. How many rows does your calendar display? 6, 3, 2, 1 ?

**Comment by mwurm93** [comment]
1. horizontal.
2. yes, month names
3. 6

Thanks

**Comment by patchthecode** [comment]
OK. i am not sure if i understand your question correctly, but the scrolling of the calendar is determined by the scrolling mode of your calendar.

Have you tried the different ones here to see how it affects your scroll to date function?
--> [Scrolling Modes](https://patchthecode.github.io/CalendarScrolling)

**Comment by mwurm93** [comment]
This is the JTCalendarView on the first VC where I have selected June 13-15

![img_0091](https://cloud.githubusercontent.com/assets/6393161/26136089/e08ee172-3a87-11e7-896a-ca0a2115b966.PNG)
.
This is the code I'm running in viewdidload of a second VC with the JTCalendarView to scroll to the selected dates, and the corresponding glitch in the pic below.
{
calendarView.scrollingMode = .nonStopToSection(withResistance: 0.9)

calendarView.scrollToDate(firstSelectedDate!, triggerScrollToDateDelegate: true,       animateScroll: false, preferredScrollPosition: UICollectionViewScrollPosition.left, completionHandler: { (() -> Void).self})
}

![img_0092](https://cloud.githubusercontent.com/assets/6393161/26136093/f0a87dd4-3a87-11e7-8fcb-8138c5361734.PNG)

**Comment by patchthecode** [comment]
can you join me here if youre online? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by telip007** [comment]
I have the same issue, could you help me? :)

**Comment by patchthecode** [comment]
@telip007 which version are you using?
