### ISSUE TITLE
Crashing when loading cell from nib 

### ISSUE THREAD

**Issue by ChanchalW** [patchthecode/JTAppleCalendar#417]
I am working on classes for my generic use to add calendar in popup. When i added cell from nib this crashed and log this:- 

Cell was not of type JTAppleCell
There was an error in this code section. Please contact the developer on GitHub
assertion failed: file /Users/xxxxx/Documents/MyProjectsSwift/xxxx/xxxxx/Pods/JTAppleCalendar/Sources/JTAppleCalendarView.swift, line 239

**Comment by lukasarcevic** [comment]
How did you fix error?

**Comment by patchthecode** [comment]
@lukasarcevic what version of the library are you using, and what error are you experiencing?

**Comment by ChanchalW** [comment]
@lukasarcevic I was using xib and didn't code to load cell from xib. Add your cell in storyboard or load cell from xib. 
Hope this help..

**Comment by lukasarcevic** [comment]
Thanks, that helped!
