### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Henikth** [patchthecode/JTAppleCalendar#418]
Could you please take a look at this ?

macOS Sierra 10.12.5
Xcode 8.3.2 (8E2002)
latest framework 7.0.2
framework installed by Carthage
*tried also with pods

![screen shot 2017-05-17 at 12 24 56](https://cloud.githubusercontent.com/assets/18598842/26149789/e662e8cc-3afb-11e7-80b5-6863fb024c0e.png)
![screen shot 2017-05-17 at 12 24 30](https://cloud.githubusercontent.com/assets/18598842/26149788/e65ffae0-3afb-11e7-86ec-f2a085faa76a.png)

**Comment by patchthecode** [comment]
Have you followed the video tutorials on how to install this? They should help you.
If you have already looked at them and is still stuck, then can you send the a sample project with the crash to my email? patchthecode@gmail.com

**Comment by patchthecode** [comment]
I received you email and have resolved the issue on your gmail.
Basically your XCode did not autofill in the `Module` for the JTAppleCalendar library.
I'll close this issue now.
If you have any further question then let me know.

🍻
