### ISSUE TITLE
Crash when loading Xib files

### ISSUE THREAD

**Issue by stillLife456** [patchthecode/JTAppleCalendar#42]
I'm having an issue with layoutAttributesForElementsInRect loading Xib files. I'm pretty new to swift so this may be a rookie problem, but I can't seem to load headers for the cells. 

<img width="764" alt="screen shot 2016-06-06 at 9 11 09 pm" src="https://cloud.githubusercontent.com/assets/19790450/15845791/4ef7ecf6-2c2b-11e6-9ef5-810553fe5d3b.png">

If I comment out the call to registerHeaderViewXibs in the viewDidLoad it runs fine but no headers. I'm running version 3.0.0

**Comment by akabab** [comment]
Look at your error: it says that your `endSection` < `startSection` which can't be in a Range (aka `...`). The left value has to be lower than the right value

**Comment by patchthecode** [comment]
@stillLife456 I have seen this range error, and have fixed it in later versions. The latest version of the library is version `4.0.0`. Can you try using this and see if your error is resolved?

**Comment by stillLife456** [comment]
Hey, I've updated to 4.0.0 and am now getting a different error. I had to change the signature for configureCalendar to include numberOfRows, but now I'm getting an error in JTAppleCalendar.swift
<img width="795" alt="screen shot 2016-06-07 at 10 22 22 am" src="https://cloud.githubusercontent.com/assets/19790450/15867830/d6e4164e-2c99-11e6-921d-27c23490d570.png">
 The data source is set in my CalnedarViewController and it was working before the update.

**Comment by stillLife456** [comment]
I downgraded back to 3.0.0. The app will run (no issues with dataSource) but back to the range error when trying to load headers.

**Comment by patchthecode** [comment]
OK. i'm back.
When you update to 4.0.0, you will get that error with your `configureCalendar` function. This is because I have changed the way the number or rows are handled. This was needed because of some concurrency issues.

Can you paste me the code for your `viewDidLoad()`? You should not be getting an error telling you that the datasource isnt set.

**Comment by stillLife456** [comment]
When I run this in 3.0.0 it's fine
<img width="785" alt="screen shot 2016-06-07 at 10 36 24 pm" src="https://cloud.githubusercontent.com/assets/19790450/15883808/9cd564fa-2d00-11e6-879e-ec1ca61a2fcd.png">

When I update to 4.0.0, change configureCalendar but nothing in the viewDidLoad I get this
<img width="791" alt="screen shot 2016-06-07 at 10 44 22 pm" src="https://cloud.githubusercontent.com/assets/19790450/15883938/95e02760-2d01-11e6-93e4-ce6c857f251e.png">
It seems from the print statements the the dataSource is being set in the viewDidLoad, but when I try to print just before the error (in JTCalendarView class) I'm getting nil
<img width="778" alt="screen shot 2016-06-07 at 10 54 38 pm" src="https://cloud.githubusercontent.com/assets/19790450/15884113/dd3832d2-2d02-11e6-8604-9262369d1718.png">
I don't get it!

**Comment by patchthecode** [comment]
Are you online now? Any chance we can chat here? 
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Or is there a chance you can just zip the buggy version of your app so i can have a look? You can drop the file in the textBox here.
I am asking this because I cannot re-create your issue

**Comment by patchthecode** [comment]
Btw, looking at your screen shots, it is saying `Data source is not set` because you are probably sending something weird in the configure function.
Can you paste the line of code you are returning from the configure function?

**Comment by patchthecode** [comment]
This chat here is too slow. If you get a change, send me a message on that chat link i sent you above (before i head to sleep, else we'll have to talk tomorrow)

**Comment by stillLife456** [comment]
Hey, sorry I'd already turned in. Here's a zip of my stuff, be gentle, I'm just a student! This is with version 4.0.0. 
[CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/305236/CalendarTest.zip)

I can chat in the evenings Pacific Standard Time. Thanks!

**Comment by patchthecode** [comment]
Well i'm up now. Checking the file now.

**Comment by patchthecode** [comment]
I will advise you to take a look at the tutorial --> [here](https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial)

**Comment by patchthecode** [comment]
I will close this issue. But if you can still chat on here if you need further help. The problem does nto appear to be with the library in this case.

**Comment by stillLife456** [comment]
Hey sorry I didn't get back to you sooner, I had a calculus test today. You
are correct, the problem was with my implementation not with the library.
Thanks for your help, I may have more questions once I have more time to
explore the calendar further.

Thanks,
Don

**Comment by patchthecode** [comment]
Its cool. Best of luck on your test m8.
And yea, any other questions, just open a new issue. *cheers*
