### ISSUE TITLE
The calendar collection is not rendered if it is not shown at the beginning

### ISSUE THREAD

**Issue by jiaweihuo1** [patchthecode/JTAppleCalendar#421]
I have created a calendar collection view in a custom view but I don't want to show the calendar when it is loaded the first time. If I pull down on it, it should increase the height of the view and make it visible. However, if the calendar knows it is not shown in the view at the first time and it doesn't run "cellForItemAt" piece of the code and render the view so it is black. Do you have any idea why this is happening and how could I fix it?

**Comment by patchthecode** [comment]
Hmm.. is it possible you can send a sample app with the problem?
I'm having a difficult time trying to re-create this in my mind/code

**Comment by patchthecode** [comment]
It has been 7 days with no response.
I'll assume you have resolved this issue.
If you still need help on this, then let me know.
