### ISSUE TITLE
didScrollToDateSegment called with different date than scrollToDate

### ISSUE THREAD

**Issue by BarryBryant** [patchthecode/JTAppleCalendar#422]
In `viewDidLoad` I'm programmatically scrolling to the current date. This works great and everything loads correctly, except my labels are showing the first month I have for the calendar. ie, the calendar shows the cells for May 2017, however my labels show January 2017. When I put a breakpoint in `didScrollToDateSegment`, it gets called with the first month I have in the entire calendar, January 2017, rather than the month I'm programmatically scrolling to in `viewDidLoad`. I have the `triggerScrollToDateDelegate` set to true

I read in another post the Library automatically calls `didScrollToDateSegment` on initialization. It appears that this is coming through, but my programmatic call is not triggering the delegate.

**Comment by BarryBryant** [comment]
```
func setUpCalendar() {
        calendar.minimumLineSpacing = 0
        calendar.minimumInteritemSpacing = 0
        let currentDate = Date()
        
        calendar.scrollToDate(currentDate,
                              triggerScrollToDateDelegate: true,
                              animateScroll: false,
                              preferredScrollPosition: nil,
                              extraAddedOffset: 0, completionHandler: nil)
        
        calendar.selectDates(from: currentDate, to: currentDate)
    }
```
The above is called from `viewDidLoad` and is not triggering `didScrolltoDateSegment`

**Comment by patchthecode** [comment]
checking this now.

**Comment by patchthecode** [comment]
@BarryBryant what version are you using?

put this in your pod file and let me know if it works after you do a `pod install`

**Comment by BarryBryant** [comment]
Perfect, I was pointing to 7.0 in the Podfile, and it looks like I had 7.0.1 rather than 7.0.2.

**Comment by patchthecode** [comment]
Awesome. If this issue is resolved, i'll close this now. If you have more questions, then open another issue 🍻
