### ISSUE TITLE
JTAppleDayViewCell not working in swift 3?

### ISSUE THREAD

**Issue by Gurungboi** [patchthecode/JTAppleCalendar#423]
I'm trying to create a english calendar along with nepali calendar to display within a single cell using.
But still no use ... Urgent help
Regards,
Sunil Gurung

**Comment by patchthecode** [comment]
What version of the library are you using?
`JTAppleDayViewCell` exists in version 6 and below.

`JTAppleDayCell` exists in version 7 and above.

Have you looked at the video tutorials? -> https://cocoapods.org/pods/JTAppleCalendar

**Comment by Gurungboi** [comment]
I'm using Version 7 but it stated as use of Undefined Types

**Comment by patchthecode** [comment]
Here is your file
[calendarIOS-master.zip](https://github.com/patchthecode/JTAppleCalendar/files/1015868/calendarIOS-master.zip)

**Comment by patchthecode** [comment]
issue resolved. closing
