### ISSUE TITLE
didSelectDate not selecting dates in all visible sections 

### ISSUE THREAD

**Issue by mateo-kozomara** [patchthecode/JTAppleCalendar#425]
Hi,

Im currently using the calendar version 7.0.2

I followed your tutorials, but im having a strange issue, which your example app doesn't have, but I cannot figure out what setting I have wrong 

![simulator screen shot 19 may 2017 21 12 47](https://cloud.githubusercontent.com/assets/2794448/26263298/82464e0e-3cd8-11e7-89e9-f5686bef2e15.png)

On  the photo above i selected the cell with the red dot in MAY section(photoshoped it in), but it only selected the cell in JUNE section.

Is there a property which enables this? 
Code below is what i use to handle the selection, and if i uncomment the line "calendarView.reloadData()" then both cells in both sections will be selected

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?,cellState: CellState) { 
        handleCellSelected(cell: cell as! CalendarCell, state: cellState)
        handleCellTextColor(cell: cell as! CalendarCell, state: cellState)
        //        calendarView.reloadData()
}
```

**Comment by patchthecode** [comment]
@mateo-kozomara join me here -> https://gitter.im/patchthecode/JTAppleCalendar

i am not quite sure that i understand what the problem is.
are you saying that if you enable the `calendarView.reloadData()` then every thing works as expected?

**Comment by mateo-kozomara** [comment]
thanks for the chat today, but unfortunately my issue remains :(
i dont think that was the issue
