### ISSUE TITLE
Month and Week View Modes

### ISSUE THREAD

**Issue by gvaish** [patchthecode/JTAppleCalendar#427]
I'm using `v7.0.2` and trying to implement a simple calendar that supports `Month View` and `Week View`.

What's the best way to do it?
Is there a sample code / project to look at?

(I'm trying to avoid creating two views with show/hide. Looking for an available solution to avoid doing all computation for date-offset myself.)

##
I tried the following:

1. Initial configuration is default (6 rows) with `generateInDates: .forAllMonths` and `generateOutDates: .tillEndOfRow`
2. On tap of a button, I change the `height` and trigger `reloadData`
3. This causes `JTAppleCalendarViewDataSource.configureCalendar` to be called again which sets the `numberOfRows` to the correct value - `1` or `6`

I would have expected to see only the first week of the current month but it shows the N-th week since the start of the calendar where N = number of months scrolled.

I think what is happening internally is that is keep a track of N (number of swipes) and then based on number lines, `start date to show = start date + (7 * number of lines * N)`.

**Comment by patchthecode** [comment]
Ok what is happening is correct.
I coded it this way because it was not correct to assume that since the developer changed the number of rows, that said developer wants the calendar to be at the same point. Different developers might have different reasons for changing the height.

What you'll need to do is to save the `visible date` that you want to scroll to before reloading data.

You can get tie visible dates like this:
```swift
let theDataWeWantToScrollTo = calendarView.visibleDates().monthDates.first!
// then after changing the configuration
calendarView.reloadData {
    calendarView.scrollToDate(theDataWeWantToScrollTo)
}
```

**Comment by gvaish** [comment]
Almost there. I think there's something funky going on with the frame.

[Week-Month-Modes.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/1024209/Week-Month-Modes.mov.zip)

**Comment by gvaish** [comment]
Never mind. I think setting `animateScroll: false` did the magic.

However, I wonder how easy it will be to add a `slide` animation when switching between the modes...

**Comment by patchthecode** [comment]
I have had developers who have added slide animation etc between modes.
I am not good on animations however. But i'm pretty sure there are many examples online whch can do a smooth animation of a view.

**Comment by patchthecode** [comment]
closing this issue for now.
If you need more help on this then let me know.
But you can find a host of ways to add a sliding animation from [this google link](https://www.google.com/#q=animate+uiview+frame)
