### ISSUE TITLE
Add Custom UIImageView to Date

### ISSUE THREAD

**Issue by ttyguy1** [patchthecode/JTAppleCalendar#429]
Hey, I'm really new to swift and I've been looking all over the web how to had a specific image to a specific date in the calendar. I've found similar post but I don't see any code on how to do this anywhere. I would appreciate it greatly if you can show me how to do this. I love the calendar library! Great work.

**Comment by patchthecode** [comment]
mind joining me here? -> https://gitter.im/patchthecode/JTAppleCalendar
I'll be doing a vid tutorial on this.
I can explain faster if youre online and join the chat room.

**Comment by patchthecode** [comment]
If you need more help on this then let me know.
Closing this issue.
