### ISSUE TITLE
"Bottom border" for each week in calendar

### ISSUE THREAD

**Issue by sahirmemon** [patchthecode/JTAppleCalendar#432]
Hey there, great library! Been really easy to set my calendar up. Just running into one issue right now. I would like to have a "bottom border" for each week in the month and currently I am doing this:
`cell.contentView.addBorder(side: .bottom, thickness: 1, color: UIColor(colorWithHexValue: 0x292C49))`
inside the cellForItemAt. I am getting the desired view however after changing the months few times, I am seeing that the border is being drawn multiple times. Is there a better way to do this? 

Note the `addBorder()` function is an extension to UIView I added. 

<img width="463" alt="screen shot 2017-05-28 at 6 39 47 pm" src="https://cloud.githubusercontent.com/assets/1057097/26532678/b8949cfa-43d5-11e7-8983-f90fdf89e281.png">

<img width="458" alt="screen shot 2017-05-28 at 6 39 59 pm" src="https://cloud.githubusercontent.com/assets/1057097/26532682/bb777276-43d5-11e7-9da8-427c9ac5da5d.png">

Thank you!

**Comment by patchthecode** [comment]
the fastest way to make lines i would think is by changing one of the spacing to 1.

```swift
calendarView.minimumLineSpacing = 1
Or
calendarView.minimumInteritemSpacing = 1
```

This would leave either a vertical or horizontal space. Depending on the background color of your cells (black) and the background color of the calendarView itself (blue)

**Comment by sahirmemon** [comment]
@patchthecode genius! Worked out perfectly.

Thank you!

**Comment by tkirby** [comment]
Value of type 'JTAppleCalendarView' has no member 'minimumLineSpacing'
Value of type 'JTAppleCalendarView' has no member 'minimumInteritemSpacing'

**Comment by patchthecode** [comment]
@tkirby what version are you using?
it should be 7.0.5
