### ISSUE TITLE
displaying dictionary data

### ISSUE THREAD

**Issue by FrancysSosa** [patchthecode/JTAppleCalendar#433]
Hi, I'm facing an issue and most of it I'm sure it is my lack of knowledge, I followed your tutorial and everything is good, but now I need to display a number of cars per day that I have saved on a dictionary on a second label, how do I set this label on the calendar to display the number of cars on that day from my dictionary.
my dictionary is defined like this:  `var cars = [NSDate: Int]()`
when I use `print(cars)` the list with my dates and number of cars are there, just need to connect them to the right date on the calendar.
Thanks in advance and sorry for the noob question.
I'm using version 7.0.2

**Comment by ethanfox** [comment]
I am also looking for a solution to this as well. If anyone could help us out that would be great!

**Comment by patchthecode** [comment]
ok. Video tutorial coming this weekend.
