### ISSUE TITLE
Make library iOS 8 compatible

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#434]

**Comment by patchthecode** [comment]
added to TODO projects

**Comment by Fengson** [comment]
What's the status of iOS 8 support?

**Comment by patchthecode** [comment]
unfortunately, i do not think this will be done.
someone will have to make a pull request. this project alone has gotten very time intensive.

**Comment by patchthecode** [comment]
hey, is easy to do, but im just so very very busy right now.
install the library on your project, and then do a search in the library files for this text:
```
semanticContentAttribute
```
 You should see it appearing 6 times in the library.
Just delete it. and you should be good.

If someone can create a pull request to add the `@availailable 9.0` tags to the code, i will gladly accept it.

**Comment by patchthecode** [comment]
ios8 will now be supported again.
