### ISSUE TITLE
selectDates  acrossing months

### ISSUE THREAD

**Issue by nkphuong** [patchthecode/JTAppleCalendar#435]
First, thank you for your incredible calendar, i very love it

I'm using the 7.0.3 version

My problem is select multiple dates acrossing months 
1. I want to select all the (monday, wednesday, friday) dates from "01/05/2017" to "01/07/2017" with format "dd/MM/yyyy"
2. My screen was
![screen shot 2017-06-03 at 6 36 47 pm](https://cloud.githubusercontent.com/assets/5858327/26753218/b61d2446-488b-11e7-94f2-151fd1a99619.png)
3. I was using` calendarView.selecteDates([the valid dates], triggerSelectionDelegate: true, keepSelectionIfMultiSelectionAllowed: true)`
4. The `didSelectDate` was fired, but only work for the dates on this month (not on the previous or next month)
5. I did some debugging, it seem like the `shouldSelectDate` will return **False** for the date in InDates or OutDates
6. My Calendar Configuration was:
```swift
 func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
       
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2017 01 01")!
        let endDate = formatter.date(from: "2018 12 31")!
        
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate)
        
        return parameters
    }

```
Could you tell me what's wrong?

Thanks for you help

**Comment by patchthecode** [comment]
ok. Looking into it.

**Comment by patchthecode** [comment]
7.0.3 accidentally introduced a bug.
It is being tracked on this issue -> https://github.com/patchthecode/JTAppleCalendar/issues/437
Fixing this right noe.

**Comment by patchthecode** [comment]
put this in your `Podfile`
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```
then run `pod update`
And let me know if your problem is fixed.
If its fix, then I will release version 7.0.4

**Comment by nkphuong** [comment]
thank you!!!
It's work like a charm
You are my hero

**Comment by patchthecode** [comment]
version 7.0.4 released
