### ISSUE TITLE
Selecting dates on 7.0.3

### ISSUE THREAD

**Issue by bigfish2001** [patchthecode/JTAppleCalendar#437]
Love this library, so much better than using Date Picker.  Wondered if there are any breaking changes from 7.0.2 to 7.0.3.  I had some code in viewDidLoad to select initial dates on the calendar that works fine in 7.0.2, but does not select anything in 7.0.3.

Here is the code:
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        if let season = season {
            seasonNameTextField.text = season.desc
            selection = .end
            selectionInstructions.text = "Select the end date"
        }

        monthLabel.alpha = 0.0
        selectedDateLabel.text = ""
        setupCalendarView()

        if let season = season {
            calendarView.selectDates(from: season.startDate, to: season.endDate, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)
        }

    }

    func setupCalendarView() {
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        calendarView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        calendarView.isRangeSelectionUsed = true
        calendarView.allowsMultipleSelection = true
        calendarView.visibleDates { (visibleDates) in
            self.setupCalendarLabels(visibleDates: visibleDates)
            self.updateSelectedDateLabel()
            if self.selection == .end {
                self.calendarView.scrollToDate(self.season?.endDate ?? Date())
            } else {
                self.calendarView.scrollToDate(Date())
            }
        }
    }
```

Thanks,
Bruce

**Comment by patchthecode** [comment]
looking into it

**Comment by patchthecode** [comment]
hmm. Selection works on my sample app.
Can you let me know if you have implemented the function `shouldSelectDate` ?

This upgrade has been made in version 7.0.3
The `shouldSelectDate` funciton is now called with programmatic selection. This was not being done before.

**Comment by patchthecode** [comment]
There are breaking changes. Fixing this right now.

**Comment by patchthecode** [comment]
put this in your `Podfile`
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```
then run `pod update`
And let me know if your problem is fixed.
If its fix, then I will release version 7.0.4

**Comment by bigfish2001** [comment]
I will try it tonight and let you know.  Thank you

**Comment by bigfish2001** [comment]
I tested with the master branch and everything looks great.  Thank you for the great support of this great library

**Comment by patchthecode** [comment]
version 7.0.4 released
