### ISSUE TITLE
Warning from App Store

### ISSUE THREAD

**Issue by kristof4ad** [patchthecode/JTAppleCalendar#44]
Hi, after submission for internal testing I've got that message:
Non-PIE Binary - The executable 'JTAppleCalendar.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

I'm using version 4.0.0
Any Idea what it is about?

Thanks
Kristof

**Comment by patchthecode** [comment]
ok one thing.
I just updated to version 4.0.1

Also, what in the world is a PIE ? :/ 
I'm looking this up now. If you look at my code, i use regular stuff in there. I'm checking this out now.

**Comment by patchthecode** [comment]
Btw, we're already on version 4.0.2

**Comment by patchthecode** [comment]
So was the app rejected?

Here is what i found on PIE.
https://developer.apple.com/library/ios/qa/qa1788/_index.html

Let me know if it helped?

**Comment by patchthecode** [comment]
And here is information on what the PIE is.

https://www.madewithmarmalade.com/blog/announcing-support-position-independent-executables-pie-ios

**Comment by patchthecode** [comment]
Ok. so after reading up on it, i believe i have to update my project's settings to be PIE complaint? I'm not sure how to do this yet, as this is the first time im reading it up and I am occupied at the moment. But i'm sure the fix is a simple settings change in build settings. I will get to it once i am free. Sorry for the inconvenience.

**Comment by kristof4ad** [comment]
OK, great that you found it! Please let me know when you fix it.
Thanks

**Comment by patchthecode** [comment]
Ok so i'm stumped. I read this thread from cocoapods -> https://github.com/CocoaPods/CocoaPods/issues/5453

**Comment by patchthecode** [comment]
Closing this as i believe this has something to do with the project settings from your end? If you have more information on it then let em know, but I couldn't find anything more on this.
