### ISSUE TITLE
[7.0.4] Creating a calendar without a storyboard

### ISSUE THREAD

**Issue by LuckyFA** [patchthecode/JTAppleCalendar#441]
Hey there,

I want to create a Calendar without a storyboard. 
I tried to do it in multiple ways, but I alway get the same errors:
"type 'CalendarViewController' does not conform to protocol 'UICollectionViewDataSource'" and
"type 'CalendarViewController' does not conform to protocol 'UICollectionViewDataSource'"

Sadly, i cant show you any code, because im not allowed to.

**Comment by strike65** [comment]
Have you code like this in your project?

```
extension CalendarViewController: JTAppleCalendarViewDataSource {
    public func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
...
    }
}


extension CalendarViewController: JTAppleCalendarViewDelegate {
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {

...
        return cell
    }

```

**Comment by patchthecode** [comment]
@LuckyFA what @strike65 said is correct. Have you conformed to the 2 protocols?

**Comment by LuckyFA** [comment]
@patchthecode When i add the calendarView to the ViewControllers view, the app always crashes.
I tried it every way of constraints programmatically.

I also can't set 
`calenderView.dataSource = self`
`calenderView.delegate = self`

**Comment by patchthecode** [comment]
I think you should join the chat here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing this issue as it is resolved.
