### ISSUE TITLE
Calendar universal App: iPad version looks weird...

### ISSUE THREAD

**Issue by strike65** [patchthecode/JTAppleCalendar#442]
Hi!

First: Thank you for your nice work.

But I have a problem: Please look at the attached screenshots. Why looks the iPad version so ... weird?

In viewDidLoad() I have

```
        calendarView.minimumLineSpacing = 0.3
        calendarView.minimumInteritemSpacing = 0.3
``` 

![simulator screen shot 8 jun 2017 13 27 16](https://user-images.githubusercontent.com/2091178/26926689-e55b9f64-4c4e-11e7-9e70-fe056caa1fcd.png)
![simulator screen shot 8 jun 2017 13 28 07](https://user-images.githubusercontent.com/2091178/26926702-ecee1ca2-4c4e-11e7-802b-fa2b786f4ee5.png)

**Comment by patchthecode** [comment]
hmm.. Just wondering, does every view in your cell have proper constraints?

**Comment by strike65** [comment]
Yes. Will be back soon... Thanks!

**Comment by strike65** [comment]
Below a test project...


[JTAppleCalTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/1061146/JTAppleCalTest.zip)

**Comment by patchthecode** [comment]
Yea, the problem was your constraints.
In your cell you have put a root view.
And in that root view you have its width and height **fixed**

To fix, please delete all the constraints of the view and instead of making it fixed and centered, make all its leading edges expand to the width and height of the cell.

**Comment by patchthecode** [comment]
Will close this issue, but if you have any more questions, then mention it here and i'll address it.
