### ISSUE TITLE
Show calendar centered at date

### ISSUE THREAD

**Issue by Juanpe** [patchthecode/JTAppleCalendar#443]
Hello!

I'm using **JTAppleCalendar 7.0.2**. I have a problem and I don't know how solve it.

**Scenario**
_Calendar configuration { start Date: June 2017, end Date: December 2017}_

1) Open calendar 
2) User select a date at October 2017 
3) Close calendar

Now, the user needs to modify his selection, so we open the calendar again, and the user needs to scroll until October 2017.

How I can, show the calendar centered in a month? It's possible?

If it is not possible, could be a good solution, to add a new parameters to "**ConfigurationParameters**" struct, like: focusMonth, focusDate or whatever

What do you think? 

Thanks!
Juanpe Catalán

**Comment by patchthecode** [comment]
@Juanpe that feature is already there :)
```swift
calendarView.scrollToDate( theDateYouWantToScrollTo )
```

**Comment by Juanpe** [comment]
Thanks for your answer!
Yes, I know, the problem is the app crash when I follow this steps:
1. Open calendar
2. Select date
3. Close calendar
4. Open again calendar and show selected date with scroll **without animation** (if I animate the scroll, it works fine), the app crash.

**Console output:**
`*** Assertion failure in -[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/UICollectionViewData.m:949`
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for layout attributes for supplementary view UICollectionElementKindSectionHeader in section 1 when there are only 0 sections in the collection view'`

![screen shot 2017-06-09 at 14 46 32](https://user-images.githubusercontent.com/1409041/26976021-76e82c80-4d22-11e7-86a6-1dcd770492d7.png)

The code is:
`self.calendarView?.selectDates([date], triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)`
` self.calendarView?.scrollToDate(date, animateScroll: false)`

Any idea, what is it happening?

Thanks,
Juanpe Catalán

**Comment by patchthecode** [comment]
What version of the lib are you using? 7.0.4 ?
