### ISSUE TITLE
super.layoutSubviews()

### ISSUE THREAD

**Issue by AlexBolot** [patchthecode/JTAppleCalendar#444]
Hello Jay,

I have been following step by step (twice) your tutorial ([https://www.youtube.com/watch?v=zOphH-h-qCs](https://www.youtube.com/watch?v=zOphH-h-qCs)).

But when I compile the code, I have this happening in the JTAppleCalendarView class 
> Thread 1: EXC_BAD_ACCESS (code=2, address=0x7fff52f17dc8)

It seems to be when the super.layoutSubviews() method is called.
And I also noticed the Thread 1 has +9600 calls on this method, when I'm just starting the app...
I think there is an infinite loading loop somewhere... And since I'm new to Swift and Xcode I have a lot of troubles solving this issue

![capture d ecran 2017-06-09 a 14 57 33](https://user-images.githubusercontent.com/16123636/26976481-3c6f7304-4d24-11e7-8412-e0ac98592af3.png)

![capture d ecran 2017-06-09 a 14 57 41](https://user-images.githubusercontent.com/16123636/26976480-3c6eedda-4d24-11e7-9362-56b7d8566888.png)

Here is my project :

[Calendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/1064077/Calendar.zip)

Thank you in advance,

Alex

**Comment by patchthecode** [comment]
If youre having an inf loop. Then you must not be on version 7.0.4 which fixes the problem :D
