### ISSUE TITLE
Elements inside JTAppleCell not clickable

### ISSUE THREAD

**Issue by Montrazul** [patchthecode/JTAppleCalendar#445]
Inside each `JTAppleCell` I have a `UITableView`. I enabled all user interactions but the cells inside the `UITableView` are never selectable.

**Comment by patchthecode** [comment]
JTAppleCalendar is a regular UICollectionView.

Just wondering, if you put a UITableView inside a regular UICollectionViewCell, will the UITableViewCell be clickable?

I tend to think that the UICollectionViewCell wil be capturing all the clicks?

**Comment by Montrazul** [comment]
Yes. It is possible. Actually everything worked in JTAppleCalendar Version 6.1.6 but today I updated to 7.0.4 and since then the clicking isnt possible anymore.

**Comment by patchthecode** [comment]
Oh, i see what you mean.
hmm... join me here? https://gitter.im/LuckyFA

**Comment by patchthecode** [comment]
link updated

**Comment by Montrazul** [comment]
Doesnt seem to be a prolbem with the JTAppleCalendar itself so i close this issue.
