### ISSUE TITLE
Show available dates from database (Firebase).

### ISSUE THREAD

**Issue by avazquezpr** [patchthecode/JTAppleCalendar#447]
First of all, thank you so much for the great project. Made my life way easier... 👍 

I wanted to ask you how you would load dates from a Database (Firebase)? 

In case it helps, Firebase Database stores data as JSON. 

Thanks!

**Comment by avazquezpr** [comment]
I think i found a way to do it, but haven't tested it yet. 

1. Download data from Firebase Database
2. Add data to array
3. Check if date property matches cellState.date inside `calendar(_:cellForItemAt:cellState:indexPath:)`
4. If it matches, display custom graphic in calendar cell. If it doesn't mach, then leave it like it is. 

What do you think?

**Comment by patchthecode** [comment]
sounds good. 
but a dictionary is better.
there will be no looping to match a date in your data source.

**Comment by avazquezpr** [comment]
True! That's even better... Firebase snapshots return a set of key value pairs  👍

**Comment by patchthecode** [comment]
i saw you posted a request for a vid on youtube. Even though you solved it (its easy right?) i'll still do a vid. If you have any more questions, you can open a new request :)

cheers man 🍻

**Comment by avazquezpr** [comment]
@patchthecode Thanks so much for the fast reply's. Great support 👍 

Have a nice day!

**Comment by DigitalJedi3** [comment]
@avazquezpr I see you may have figured this out. I am using patchthecodes calendar to eventually set up users with a work schedule calendar. Right now I have set up logins using firebase and was wondering do I use google calendar api to pull into my app? Do you have a working sample of this calendar being pulled from google that I can see?
