### ISSUE TITLE
From StackOverflow: Show multiple events at JTAppleCalendarView

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#45]
**Muneesh_Chauhan** 

I am implementing JTAppleCalendarView in Swift. How I can show multiple events in Calendar without interaction at Calendar View i.e. Multiple events should be shown on Calendar. 

I am getting some date from server. All date should be show at Calendar as Event (ie. selected).

**Comment by patchthecode** [comment]
Just to be clear: 

1. You have some dated from the server 
2. You want these to be selected when you application runs?

Then you should do this:
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        .......
        .......
        calendarView.allowsMultipleSelection = true
        let datesFromServer = [d1, d2, d3]
        calendarView.selectDates(datesFromServer)
```

This will select all your dates.

**Comment by samuelmgalan** [comment]
Hi
One question: how do i wait for the server response in order to paint events inside the cells before the calendar renders? Or how to manually call `isAboutToDisplayCell` with the new info? Kind of lost.

**Comment by patchthecode** [comment]
Ok, I am just a little confused. Let me know which ones below are wrong.

1. If you do not want the calendar to render (or be visible on the screen) then don't put it on the screen? (if i understand it correctly)
2. If you have a calendar that loads in `viewDidLoad` it will be displayed on the screen. At this point if you already have your dates from the server (in array form), then just call `calendarView.selectDates(datesFromServer)`.  If at this point you do not have the dates from the server yet, then get the dates, and then call `calendarView.selectDates(datesFromServer)` in your completion handler.

If you need more clarification join me in chat here -> https://gitter.im/patchthecode/JTAppleCalendar because texting here can be maddeningly slow. I'll be available there in 2 and a half hours time (from posting this message)

**Comment by samuelmgalan** [comment]
It was not for selecting dates, it was for adding subviews to a cell. But i discover that if i call `reloadData()`the function `isAboutToDisplayCell` its called again and i can add all the new info. 
But thanks anyway ;)

**Comment by patchthecode** [comment]
Ah. ok. i see now. Cool. man.
one thing, if you need to know all the functions you can use with this library, look at the `UserInteractionFunctions.swift` file.
It has ever function you're allowed to do.

**Comment by patchthecode** [comment]
Also, if this lib has helped you in anyway, please leave a start rating :)
