### ISSUE TITLE
How to do selection like this

### ISSUE THREAD

**Issue by zhanswift** [patchthecode/JTAppleCalendar#450]
How to do selection like this? 

![2017-06-12 23 15 51](https://user-images.githubusercontent.com/16617536/27046210-5cc87382-4fc5-11e7-82b8-1cc65d5c461b.png)

**Comment by patchthecode** [comment]
I was wondering, have you followed the tutorial here -> https://patchthecode.github.io/RangeSelection/ ?

The documentation there is for the version 6.0
But it is almost the same for 7.0

The changes are ->
1. the `willDisplayCell` function is now `cellForItemAtIndexPath`
2. the `calendarView.rangeSelectionWinnBeUsed` is now `calendarView.isRangeSelectionUsed`

**Comment by zhanswift** [comment]
I do like this, but I need to do a smooth.

![2017-06-13 0 38 12](https://user-images.githubusercontent.com/16617536/27049347-e19d1774-4fd0-11e7-9791-0174c3320054.png)

**Comment by patchthecode** [comment]
in the code, you will see something like `.middle`, `.left`, `.right` and `.full`.
You need to provide different image based on the type you want to display.

**Comment by zhanswift** [comment]
I do like this, but still not what I need.

<img width="320" alt="2017-06-13 11 50 30" src="https://user-images.githubusercontent.com/16617536/27067803-8a546dc4-502e-11e7-893e-2bbf35f22eca.png">

**Comment by patchthecode** [comment]
Why do you have a circle for `left` and for `right` ?
It should not be a circle.

**Comment by zhanswift** [comment]
Then what should be?

**Comment by patchthecode** [comment]
something like this 
<img width="23" alt="screen shot 2017-06-12 at 11 10 12 pm" src="https://user-images.githubusercontent.com/2439146/27068316-532f94f0-4fc4-11e7-9f2d-b5642c69daa6.png">

Not a circle

**Comment by patchthecode** [comment]
closing this issue.
