### ISSUE TITLE
Sometimes cell come to front if i add some other view on cell,need your help

### ISSUE THREAD

**Issue by TimeToCodeIos** [patchthecode/JTAppleCalendar#452]
Hi,
      I am using 6.0.5 version of your calendar, and i am adding tooltip (using custom tooltipview - ZGTooltipView)on cell but it behaves weird,like some time cell comes to from of tooltipview and after scrolling sometimes it goes to back , i am attaching screenshots here,can you please help me with this,

**Sometimes it looks perfect**
![simulator screen shot 13-jun-2017 10 22 11 am](https://user-images.githubusercontent.com/17156261/27066760-086389ee-5024-11e7-8805-34be99d82136.png)

**sometimes it cuts under headerview**
![simulator screen shot 13-jun-2017 10 22 16 am](https://user-images.githubusercontent.com/17156261/27066779-1e4a5512-5024-11e7-8a01-ea3971b5723f.png)

**Sometimes cell comes to front**
![simulator screen shot 13-jun-2017 10 22 26 am](https://user-images.githubusercontent.com/17156261/27066793-2fe5a056-5024-11e7-8647-ff441e38ec56.png)

Please help me with this

**Comment by patchthecode** [comment]
Hmm. I'm not quite sure how that other library adds values to the cells.
Does this also happen on version 7.0.4?

**Comment by TimeToCodeIos** [comment]
that i didn't checked because i have used 6.0.5 version and coded acordingly so i can't update it now ....can you please check for me once ?

**Comment by patchthecode** [comment]
What I can do is, I can help you convert your project to version 7.
however, i would not be able to check to see how the external library adds views to the cells.

In version 7.0, this library provides the raw UICollectionView to the developer. No extra design code is done under the hood. Everything is up to the dev. 
I can help you convert to version 7.

**Comment by patchthecode** [comment]
I'll close this issue.
But once you have the time, let me know, and i'll help convert.
