### ISSUE TITLE
JTAppleCalendar crashes in DateSegmentInfoFrom

### ISSUE THREAD

**Issue by SyedMuhammadYasir** [patchthecode/JTAppleCalendar#453]
@patchthecode JTAppleCalendar crashes in DateSegmentInfoFrom. InDates, MonthDates, and OutDates are nil.

it is working fine in debug mode but crashes in Release mode. Optimization level is set to none but still no success. Any Help?

Error" JTAppleCalendar was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by patchthecode** [comment]
Hey, let's try to make the questions more developer friendly ok? :)

1. What version of the library are you using?
2. In which function is the crash?
3. What do you do to cause the crash to happen?

**Comment by patchthecode** [comment]
Its been 3 days.
Closing this until more information is provided.
Once you provide the input, i will reopen this.

**Comment by SyedMuhammadYasir** [comment]
What version of the library are you using?
**It is 7.0**

In which function is the crash?
**It crashes in file 'JTAppleCalendarView.swift' in method 'dateSegmentInfoFrom' while calling this 'let retval = DateSegmentInfo(indates: inDates, monthDates: monthDates, outdates: outDates)' with an error 'JTAppleCalendar was compiled with optimization - stepping may behave oddly; variables may not be available'. **

What do you do to cause the crash to happen?
**Well, I have created a new project and add JTAppleCalendar via pods. When I run the application in debug mode it is working fine but when I run it in release mode the application crashes **

**Comment by patchthecode** [comment]
can you con firm that you're using version `7.0.4`?
If you have more questions then can you join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by Moonif** [comment]
I was having the exact issue with my app after following the video tutorial on youtube, I have the latest version of JTApple Calendar, but not the latest version of Xcode 8 (Simulator running iOS 10.0).
I fixed the problem by selecting "Pods" in the project navigator --> JTAppleCalendar in Targets --> Build settings -->Setting optimization level for both Apple LLVM and Swift Compiler to None.

**Comment by patchthecode** [comment]
@Moonif is this a release issue thing? I have never heard of this before.

**Comment by Moonif** [comment]
Yes, the debug build works perfectly fine, the error only appears on release and causes the app to crash, it's a very strange issue.

**Comment by patchthecode** [comment]
I'll look into this,
i hope this is a settings issue.

**Comment by SyedMuhammadYasir** [comment]
@moonif can you please add some more details how to do steps you mentioned above as I am not able to find targets.

**Comment by patchthecode** [comment]
added to project TODo list

**Comment by Moonif** [comment]
Hello,

Just wanted to let you know that this is no longer an issue using the latest version of JTAppleCalendar (As of this date) and latest version of Xcode.

Thank you!

**Comment by patchthecode** [comment]
youre welcome man.
Thanks for letting me and others know.
