### ISSUE TITLE
Scroll to day of week

### ISSUE THREAD

**Issue by telip007** [patchthecode/JTAppleCalendar#455]
Similar to #416 
I have a calendar where I display a week horizontally. Every week starts with Monday (as shown in the image below). But when I scroll to a specific date the week starts with another day (shown in the second image). I have paging enabled and my code for scrolling is as follows:
`scrollToDate(Date.now, triggerScrollToDateDelegate: true, animateScroll: false,
                     preferredScrollPosition: .centeredHorizontally,
                     extraAddedOffset: 0, completionHandler: nil)`
How can I make the calendar scroll to the page but keep the "page" in the [mon, tue, wed, thu, fri, sat, sun] order ?

Images: 
![simulator screen shot 14 06 2017 14 35 13](https://user-images.githubusercontent.com/8666886/27132347-d4f53080-510e-11e7-930d-a51fe76bab33.png)
![simulator screen shot 14 06 2017 14 35 11](https://user-images.githubusercontent.com/8666886/27132349-db94b51e-510e-11e7-8f5c-dcc7e4388a76.png)

**Comment by telip007** [comment]
Solution: Set scrolling mode to `stopAtEachSection`

**Comment by patchthecode** [comment]
hmm. this should have worked without `stopAtEachSection`. `StopAtEachFrameWidth` should work as default.

Can you show me your `configureCalendar` function?
