### ISSUE TITLE
Delegate methods not being called

### ISSUE THREAD

**Issue by prmelehan** [patchthecode/JTAppleCalendar#457]
I'm creating an Application using JTAppleCalendar, and I just upgraded from the 6.0 versions to 7.0.4.

I've followed the tutorial but I've yet to get it to work. I've tried 7.0.0 and 7.0.4.

When I test to see if methods are getting called, I've noticed that the JTAppleCalendarViewDelegate's methods are not getting called, even though I set the delegate.

I'm very confused because in some projects in works ok sometimes, and in other projects it doesn't work at all. In the example code from the tutorial it works fine, but when pasting most of that code in other projects, it doesn't always work.

This is from my main project, delegates are setup, and I have breakpoints (which don't get executed)

![uncalled-breakpoints](https://user-images.githubusercontent.com/12311481/27151675-58ae1bbc-5119-11e7-8889-d3e7e173a9c0.png)

![delegates](https://user-images.githubusercontent.com/12311481/27151676-58b59e46-5119-11e7-80b2-7d7d625f9ab3.png)

When I print the Delegate and DataSource to the console in viewDidLoad, It seems all fine
~~~
▿ Optional<AnyObject>
  ▿ some : <"Project Name Here".CalendarViewController: 0x7fe48ad66a00>


▿ Optional<AnyObject>
  ▿ some : <"Project Name Here".CalendarViewController: 0x7fe48ad66a00>
~~~

Any ideas why?

**Comment by patchthecode** [comment]
Your delegates will not get called if you do not implement them.
You said you updated from version 6. Therefore your functions still look like version 6 functions.

for example, your `cellForItem` function should look like this 
```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell
```

**Comment by patchthecode** [comment]
join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Can you let me know what you used to determine that your functions are not getting called?
i downloaded your project and your functions are getting called correctly. :/

**Comment by prmelehan** [comment]
I was using the built-In Xcode breakpoints, as shown in the screenshot, which weren't being executed. I've tried everything and yet I cannot get the delegate methods to execute in my project, and the calendar won't show in that demo I've provided. I'm royally confused

**Comment by patchthecode** [comment]
that's very weird.
I just ran the project, and it worked.

Can you try placing break points in the `cellForItem` and in the `configureCalendar` function again?
If this doesnt work, then join me here -> https://gitter.im/patchthecode/JTAppleCalendar

Will be available in 1 hr from this time.
cheers 🍻

**Comment by patchthecode** [comment]
Resolved. UILabels were missing constraints
