### ISSUE TITLE
Without pod its not working..

### ISSUE THREAD

**Issue by vikrant88** [patchthecode/JTAppleCalendar#458]
Hello, 
its not working without pods. as per your documentation you have said only drag and drop "source"
folder into your project, But after doing the same and build the code it shows the 200 above error.  
![screen shot 2017-06-15 at 1 22 14 pm](https://user-images.githubusercontent.com/23399233/27171024-b1e14da8-51cd-11e7-81c0-faf94058d3c1.png)
.........and many more

**Comment by patchthecode** [comment]
In every file that you drag and drop, go to the top of the file where imports are, and do `import UIKit`.
