### ISSUE TITLE
Targetting self for dataSource and delegates

### ISSUE THREAD

**Issue by yillivs** [patchthecode/JTAppleCalendar#46]
Hello,

I seem to have an issue on the last real step of the tutorial, which is setting up the dataSource and delegates. I try to set them both to self as is shown in the tutorial and I get an error that "Cannot assign value of type monthViewController(My view handling class name) to JTAppleCalendarDataSource". This is what the troubling section of code looks like.
```swift
import JTAppleCalendar

class MonthViewController: UIViewController {
    
    
    //MARK: Properties
    @IBOutlet weak var calendarView: JTAppleCalendarView!
    
    
    
    //Default UIViewController Methods:
    override func viewDidLoad() {
        super.viewDidLoad()
        
        calendarView.dataSource = self
        calendarView.delegate = self
        
        calendarView.registerCellViewXib(fileName: "CellView") // Registering your cell is manditory
    }

**Comment by patchthecode** [comment]
Does your issue look something like this?

<img width="975" alt="screen shot 2016-06-12 at 5 38 36 pm" src="https://cloud.githubusercontent.com/assets/2439146/15994864/880215e2-30c4-11e6-85e9-00a04427c5bf.png">

**Comment by yillivs** [comment]
Yes exactly like that.

**Comment by patchthecode** [comment]
If it looks like that then, did you follow the step in the tutorial which has this code? 

```swift
extension ViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate  {
    // Setting up manditory protocol method 
    func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar) {
        // You can set your date using NSDate() or NSDateFormatter. Your choice.
        let formatter = NSDateFormatter()
        formatter.dateFormat = "yyyy MM dd"

        let firstDate = formatter.dateFromString("2016 01 05") 
        let secondDate = NSDate()
        let numberOfRows = 6
        let aCalendar = NSCalendar.currentCalendar() // Properly configure your calendar to your time zone here

        return (startDate: firstDate!, endDate: secondDate, numberOfRows: numberOfRows, calendar: aCalendar)
    }
}
```

**Comment by patchthecode** [comment]
Remember, your calendar has to conform to both the **delegate** and the **dataSource** protocol. If it does not conform to the delegate or the datasource, XCode will scream at you :)

**Comment by yillivs** [comment]
I believe so, I wrote this in the class same class as that manages the calendar view.

//MARK: JTAppleCalendarDelegate
    //Required method. Provide startDate,endDate, and a calendar configuration
    //of choice
    func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar){
        
        let formatter = NSDateFormatter()//access to date formatter method
        formatter.dateFormat = "yyyy MM dd"
        
        let firstDate = formatter.dateFromString("2016 05 10")
        let secondDate = NSDate()
        let numberOfRows = 6
        
        let aCalendar = NSCalendar.currentCalendar()
        //return logical calendar for current user
        
        return(startDate: firstDate!, endDate: secondDate, numberOfRows: numberOfRows, calendar: aCalendar)
    }

**Comment by yillivs** [comment]
But examining it currently I notice that I missed this line.

extension ViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate  

Would that have caused this to occur?

**Comment by patchthecode** [comment]
ok, but did you declare anywhere that your class conforms to the protocol?

You should either have this:
```swift
class MonthViewController: UIViewController, JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate { 
...
...
...
}
```

Or this

```swift
extension ViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate 
```

Doing that tells the calendar that: Yes, i conform to your required protocol

**Comment by patchthecode** [comment]
Let me know if your issue is resolved. And if it is, then you can close this issue 👍

**Comment by yillivs** [comment]
That fixed it!

**Comment by patchthecode** [comment]
awesome! Now go build a extremely cool looking calendar and post an image! 
have a good one.
