### ISSUE TITLE
didDeselectDate not called on first tap

### ISSUE THREAD

**Issue by Geekbell** [patchthecode/JTAppleCalendar#460]
I am setting a cell as selected programmatically using this code:

```
if (recurrenceDate as! Date == date) {
                    print("MATCH: ", recurrenceDate)
                    calendarView.selectDates([date])
                    cell.selectedCell.isHidden = false
                    cell.cellLabel.textColor = UIColor.white
                }
```
The following successfully selects the dates from the model:

`calendarView.selectDates([date])`

But the first time I tap on a selected date, didSelectDate is called instead of didDeselectDate. After that first tap the following taps call didDeselectDate as expected. 

Made sure I updated to 7.0.4 but didn't resolve the issue.

**Comment by patchthecode** [comment]
This is odd.
Every thing works as expected in the sample app.
is it possible you can provide a sample app with the bug?

**Comment by Geekbell** [comment]
I will see if I can put a portion of the app in a sample app for you that reproduces the issue.

**Comment by Geekbell** [comment]
[JTCalendartest.zip](https://github.com/patchthecode/JTAppleCalendar/files/1083717/JTCalendartest.zip)

I was successfully able to reproduce the issue in a simple test project. Because of the call in the background to retrieve the data, I am reloading the collectionView once the data is pulled from the server. I simulated this by loading the date array on viewDidLoad() and reloading the table. 

deselecting a table cell never works on the first tap.

Let me know if you need any more info to troubleshoot.

**Comment by Geekbell** [comment]
It gets weirder using the same test app I built above. I included a recording to show the strange behavior. I hope this helps.
![untitled480](https://user-images.githubusercontent.com/3166745/27314878-9e94a06a-5533-11e7-8b44-374c6d90495e.gif)

**Comment by patchthecode** [comment]
Hey, I had a chance to look at you code, and it was interesting...
can you message me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by Geekbell** [comment]
Thanks for fixing my "interesting" code ;)

**Comment by patchthecode** [comment]
Haha. cool man. Closing the issue now.
