### ISSUE TITLE
 terminating with uncaught exception of type NSException (lldb) 

### ISSUE THREAD

**Issue by oeufs** [patchthecode/JTAppleCalendar#461]
Hey Patchthecode, 

Im new to coding so I may be creating a silly mistake but everyone and a while I get the posted error above. I started with your cocoa pod this morning and tried the posted file so I ran with that and as I slowly started to form it into what I needed I got this error. I then decided I was just going to delete it all and restart with your videos, thank you for those by the way, but once I got through it and started to add in secondary labels like in your second video and thats when the error came back. I think its something that I keep missing. If you have the time would you be able to look and see what you can find? 
 
using the latest updated JTAppleCal
swift 3 
latest cocoapods

[calendar.txt](https://github.com/patchthecode/JTAppleCalendar/files/1082788/calendar.txt)

Thank you.

**Comment by patchthecode** [comment]
Hey, it would be nice if you can just zip a sample project with the error?
I will be able to tell you the problem instantly.

**Comment by oeufs** [comment]
[SchedCred.xcworkspace.zip](https://github.com/patchthecode/JTAppleCalendar/files/1083041/SchedCred.xcworkspace.zip)

**Comment by patchthecode** [comment]
@oeufs yuou have send me one file by accident
I think you send me the entire folder?

**Comment by oeufs** [comment]
thats the project file.

**Comment by patchthecode** [comment]
Hey, can you send me the project folder?

An XCode project is not just the one file alone.
There are also the other swift classes that go along with it.

**Comment by oeufs** [comment]
[SchedCred.zip](https://github.com/patchthecode/JTAppleCalendar/files/1083259/SchedCred.zip)
sorry thought you just wanted to project file. Thats the entire folder

**Comment by patchthecode** [comment]
Is your app crashing with this error?
```
2017-06-18 11:43:05.727617-0700 SchedCred[49527:22189303] Unknown class daysTasks in Interface Builder file.
2017-06-18 11:43:05.762211-0700 SchedCred[49527:22189303] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SchedCred.UserCalendarViewController 0x7fdd4bc05980> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key date.'
*** First throw call stack:
```

It actually says why its crashing. You can see it here ->
```
this class is not key value coding-compliant for the key date.'
```

Upon looking at your IB file you can see that there are two things you are not setting correctly.
They are shown with the exclamation marks. You have two of them.

<img width="254" alt="screen shot 2017-06-18 at 11 45 48 am" src="https://user-images.githubusercontent.com/2439146/27263330-b1109f14-541b-11e7-8322-87037be25ac1.png">

It seems you have renamed `month` to `currentMonth` and `date` to `currentDate` but you forgot to delete the outlet on interface builder.

**Comment by oeufs** [comment]
Your awesome!! Thanks, I figured it was a little mistake that I was making but it kept reoccurring. 
Have a wonderful day!

**Comment by patchthecode** [comment]
Have a good one.
cheers 🍻
