### ISSUE TITLE
Show subscribed calendar only

### ISSUE THREAD

**Issue by chrstaerkind** [patchthecode/JTAppleCalendar#462]
Hi,

I am using the latest version of JTAppleCalendar and have successfully created a calendar in my new app. I would now like the calendar to only show entries from a subscribed calendar, i.e. I do not want the user to enter own appointments etc. but only show items created in a calendar that is subscribed to.

Is this possible with JTAppleCalendar - and how?

Thank you so much!!

/Chris

**Comment by patchthecode** [comment]
I am a bit confused thinking on this.

> I would now like the calendar to only show entries from a subscribed calendar [meaning that I want to ] -> show items created in a calendar that is subscribed to.

So basically, do you want to see some sort of `dotView` or some visual indicator on the days that contain events?

**Comment by patchthecode** [comment]
closing until further user inputs
