### ISSUE TITLE
Don't remove selected dates after scroll

### ISSUE THREAD

**Issue by Juanpe** [patchthecode/JTAppleCalendar#463]
Hello!

I'm using JTAppleCalendar 7.0.4. I have a problem and I don't know how solve it.

When user select a range of dates after scroll, not refresh all cells (attach mov)

**Movie steps first selection:**
1. User select start date (22/06/2017)
2. User select end date (24/06/2017)
3. User select another date (21/06/2017), reset the selection 

If you follows these steps, but you scroll the calendar before select the second date and you select a date of next month (for example), and come back to top and select another date, the selection is reset, but not refresh all cells of calendar.

**Movie steps second selection:**
1. User select start date (22/06/2017)
2. User select end date (13/07/2017)
3. User select another date (21/06/2017), not reset the selection 

[calendar.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/1088910/calendar.mov.zip)

Thanks!
Juanpe Catalán

**Comment by patchthecode** [comment]
Will take a look after work :)

**Comment by Juanpe** [comment]
Hi @patchthecode, could you check the question?

thanks!,
Juanpe Catalán

**Comment by Juanpe** [comment]
Hi again, I've downloaded the master branch and work fine...so, when do you think that you could release the next version 7.0.5?

Thanks!

**Comment by patchthecode** [comment]
i'll be doing this is some weeks. In the mean time use the master branch.
I'll close this issue now alright :)
🍻
