### ISSUE TITLE
unusual cell behavior

### ISSUE THREAD

**Issue by timmybea** [patchthecode/JTAppleCalendar#464]
Hi Jay,

I have something unusual happening in a little test project and wanted to get your thoughts. First things first, I am using the latest version 7.0.4. The idea is to programmatically setup the calendar inside a custom view. That way I can add the custom view to the view controller and all of the calendar setup will be inside the custom view (less code in the vc).

At the moment it all seems to be hooked up correctly (print statements show that all of the cells have the correct numbers, but the label seems to be adding behind the cell's view and sometimes the cell doesn't appear to have any text in it. 
here is a link to the test project: https://github.com/timmybea/GiftOrganizer/tree/master/JTCalendarProgrammatic
And here is a screen shot: 
![simulator screen shot jun 20 2017 1 25 49 pm](https://user-images.githubusercontent.com/21972121/27354419-5cfb2aa0-55bc-11e7-8b2a-85a39dfb7468.png)

**Comment by timmybea** [comment]
Ahhhh. Wait a second. I aligned the label with layout constraints and now it all works... Thank you for taking the time to read my enquiry. Sorry for wasting your time!

**Comment by patchthecode** [comment]
Its cool man. 
I actually just read it.
Glad you figured it out.
