### ISSUE TITLE
I would like to get number of rows for the month.

### ISSUE THREAD

**Issue by iamsarathi** [patchthecode/JTAppleCalendar#465]
It would be great if you expose `func numberOfRowsForMonth` for developers. 
So that I can adjust calendar height accordingly.
I'm using Version 7.0.5.

**Comment by patchthecode** [comment]
Acknowledged. I'll look at this over the weekend.

**Comment by patchthecode** [comment]
Fixed on master branch. Will be released in next version -> https://github.com/patchthecode/JTAppleCalendar/commit/502d53d7a815f93e099bb2b81b4c4b6e125b26bb
