### ISSUE TITLE
Setting Row to 1 and scrolling to next month crashes.

### ISSUE THREAD

**Issue by seanrice** [patchthecode/JTAppleCalendar#468]
LOVE THE PROJECT. Absolutely fantastic !!!

Note 7.0.4 still CRASHES w/ fatal error: ... nil while unwrapping ... when Row set to 1 and user scrolls to another month. 

See setupViewsOfCalendar(from visibleDates: DateSegmentInfo) ...
--> let date = visibleDates.monthDates.first!.date

FYI - Setting to 2, 3 and 6 and monthly scrolling works fine here.

**Comment by patchthecode** [comment]
Hey I was wondering why you were force unwrapping a date that could be empty?

Let me know. For your single row calendar, can you tell me if your inDates and outDates are set to be generated?

**Comment by seanrice** [comment]
Hi P. Actually, that's your original sample code from demo video #2... and having reviewed your Example code this morning, i see you ugraded the setupViews method properly. My bad. I have upgraded code and tested: Setting Row to 1 works fine with latest 7.0.4 using guard. Sweet !!!

**Comment by patchthecode** [comment]
awesome
