### ISSUE TITLE
Making rounded ends properly

### ISSUE THREAD

**Issue by antonijap** [patchthecode/JTAppleCalendar#469]
i am using 7.0.4

My app works with series of selections and I would like to have rounded corners on both ends of selected cells. I have UI code but logic for making this bugs me. CellView determines the looks of the cell. For now I am passing date and CellState to manipulate UI. How can CellView determine where are the ends? Any ideas? Tips?

**Comment by patchthecode** [comment]
basically, are you saying that you wished that the `cellState` was attached to the `CellView` ?

like `myCell.cellState.isSelected` etc etc?

**Comment by antonijap** [comment]
Nope. Here is my new design -> http://d.pr/i/i8pEdw/2k3BgPzP

What I want to do is to have rounded selections if a selection is first/last. I really don't have any idea how to approach this problem.

**Comment by antonijap** [comment]
UPDATE

So I have managed to get somewhere but still, everything looks broken.

Here is a part of my ugly code:
```
if state.isSelected {
      let allLefts = CloudManager.instance.periods.map({ $0.startDate })
      let allRights = CloudManager.instance.periods.map({ $0.endDate })
                
      // FIXME: - Add case when only 1 date is in Period
      if allLefts.contains(state.date) {
           leftSelectedView(opacity: 1.0)
            print("Left for \(state.date)")
       } else if allRights.contains(state.date) {
            rightSelectedView(opacity: 1.0)
       } else {
            middleSelectedView(opacity: 1.0)
       }
```

This actually does something with dates I want. Here how it looks:
http://d.pr/i/YrrdMW/230rdnDK

Code for UI:
```
extension UIView {
    func roundCorners(_ corners: UIRectCorner, radius: CGFloat) {
        let path = UIBezierPath(roundedRect: self.bounds, byRoundingCorners: corners, cornerRadii: CGSize(width: radius, height: radius))
        let mask = CAShapeLayer()
        mask.path = path.cgPath
        self.layer.mask = mask
    }
}
```

My questions:
1. Why do cells have a greater height that width (they should be 1:1)? (they look like portrait pill)
2. Do you know why is this rounding thingy not working properly? I tried this code when I've just set up the calendar and it worked.

**Comment by patchthecode** [comment]
1. have you set the cell inset to be zero?
```
calendarView.minimumLineSpacing = 0
calendarView.minimumInteritemSpacing = 0
```

2. Do you have this in your view did load?
```swift
calendarView.isRangeSelectionUsed = true
calendarView.allowsMultipleSelection = true
```

Then when you want to configure your cell, you do this
```swift
if cellState.selectedPosition() == .left {
    // configure the rounded left
} else cellState.selectedPosition() == .right {
...
...
```

**Comment by antonijap** [comment]
I didn't know about this range selection. Thanks! Now it works very nice http://d.pr/i/GbD85t/3XKlfR9g

Just one more thing. If you will watch this gif then you'll see how each section has some padding on the right. Any ideas why this happens? I checked my constraints and they are okay.

**Comment by patchthecode** [comment]
hmm. There should be no padding.
Did you make sure this?

```swift
calendarView.minimumLineSpacing = 0
calendarView.minimumInteritemSpacing = 0
```

Also, have you accidentally set the `itemSize` property on interface builder? or in code?
itemSize should be `nil`.

**Comment by patchthecode** [comment]
closing issue.
let me know if other help is needed.

**Comment by antonijapek** [comment]
Yeah, I still have this problem. Unfortunately, I already did everything you wrote even before I have come here asking fir help. 

So there is weird space on the right side of a calendar where you can see dates in next month

**Comment by patchthecode** [comment]
hmm. I wish you'd send a sample project.
i'll get you those rounded edges

**Comment by antonijap** [comment]
No, don't have a problem with round edges. I have a problem with other problem I addressed here. It is weird spacing on the right side of a calendar where you can see selected day in next month.

http://d.pr/i/de2xy/2PipmaA8

**Comment by patchthecode** [comment]
if the minimum spacing didnt help. Is it possible you can send a small zipped project with all your secret code removed? I just want to see whats wrong with the selection. 
I'm about to release version 7.0.5 over the weekend. I'd love to add what ever fix to your problem in there.

**Comment by antonijap** [comment]
Go to my profile and find Period Flow 💃

**Comment by patchthecode** [comment]
hmm. can you provide me the link? i went [Here](https://github.com/antonijap?utf8=%E2%9C%93&tab=repositories&q=period&type=&language=) but both those repositories seem to have outdated code?

**Comment by antonijap** [comment]
Thanks!

here it is: https://github.com/antonijap/Period-Flow-2/tree/Development

**Comment by patchthecode** [comment]
Ok found it. The scrolling is off because you might have accidentally set this -> 
<img width="762" alt="screen shot 2017-07-22 at 8 38 02 am" src="https://user-images.githubusercontent.com/2439146/28492457-34477ea4-6eb9-11e7-8af7-53bde332213a.png">

Once deleted, every thing works as expected. 🍻

**Comment by antonijap** [comment]
YAAAAY! Only, this time I've got this http://d.pr/i/9ovqQP/1YbAOQEQ

**Comment by patchthecode** [comment]
Oh, thats because there are no constraints setup in the the cell.
Also the constraints of the CalendarView should be different.

Here is a fixed zip file of the solution -> 
[Period-Flow-2-Development.zip](https://github.com/patchthecode/JTAppleCalendar/files/1167602/Period-Flow-2-Development.zip)

Let me know if there is anything else wrong. cheers. 🍻

**Comment by antonijap** [comment]
You are my hero!

**Comment by patchthecode** [comment]
Haha. thanks.
