### ISSUE TITLE
Programmatic way to go to next/previous month

### ISSUE THREAD

**Issue by BaptisteSansierra** [patchthecode/JTAppleCalendar#47]
I'v added arrow buttons to go to next/previous month [(image posted on 18 june),](https://github.com/patchthecode/JTAppleCalendar/issues/2) but it seems there's no way to do this programmatically at the moment ?

I did it adding these funcs in JTAppleCalendarView.swift

`

    public func scrollToNextSection(completion: () -> Void) {
        let cvbounds = self.calendarView.bounds
        let totalSections = monthInfo.count * numberOfSectionsPerMonth
        var page = min(currentSectionPage + 1, totalSections - 1)
        var offsetx = self.calendarView.contentOffset.x
        var offsety = self.calendarView.contentOffset.y
        if self.direction == .Horizontal {
            offsetx = CGFloat(page) * cvbounds.size.width
        } else {
            offsety = CGFloat(page) * cvbounds.size.height
        }
        UIView.animateWithDuration(0.4, animations: {
            self.calendarView.contentOffset = CGPointMake(offsetx, offsety)
            }, completion: { done in
                completion()
        })
    }
    public func scrollToPreviousSection(completion: () -> Void) {
        let cvbounds = self.calendarView.bounds
        let totalSections = monthInfo.count * numberOfSectionsPerMonth
        var page = max(currentSectionPage - 1, 0)
        var offsetx = self.calendarView.contentOffset.x
        var offsety = self.calendarView.contentOffset.y
        if self.direction == .Horizontal {
            offsetx = CGFloat(page) * cvbounds.size.width
        } else {
            offsety = CGFloat(page) * cvbounds.size.height
        }
        UIView.animateWithDuration(0.4, animations: {
            self.calendarView.contentOffset = CGPointMake(offsetx, offsety)
            }, completion: { done in
                completion()
        })
    }
`

But when animating, all the cells from current month disappear... it's not as nice as doing it by scroll...

There's definitely a better option ?!

**Comment by BaptisteSansierra** [comment]
Ok sorry, i missed the funcs scrollToNextSegment / scrollToPreviousSegment, which are doing this very well, but the completion handler was never used, i fixed it that way : 
 
```
    public func scrollToNextSegment(animateScroll: Bool = true, completionHandler:(()->Void)? = nil) {
        let page = currentSectionPage
        if page + 1 < monthInfo.count {
            let position: UICollectionViewScrollPosition = self.direction == .Horizontal ? .Left : .Top
            if let validHandler = completionHandler {
              delayedExecutionClosure.append(validHandler)
            }
            calendarView.scrollToItemAtIndexPath(NSIndexPath(forItem: 0, inSection:page + 1), atScrollPosition: position, animated: animateScroll)
        }
    }
    public func scrollToPreviousSegment(animateScroll: Bool = true, completionHandler:(()->Void)? = nil) {
        let page = currentSectionPage
        if page - 1 > -1 {
            let position: UICollectionViewScrollPosition = self.direction == .Horizontal ? .Left : .Top
            if let validHandler = completionHandler {
              delayedExecutionClosure.append(validHandler)
            }
            calendarView.scrollToItemAtIndexPath(NSIndexPath(forItem: 0, inSection:page - 1), atScrollPosition: position, animated: animateScroll)
        }
    }

```

**Comment by BaptisteSansierra** [comment]
(just created a pull request)

**Comment by patchthecode** [comment]
Just went through your code. Its neat. Its now merged.
Yea i must have missed that one
