### ISSUE TITLE
Waiting for day view and week view 

### ISSUE THREAD

**Issue by hardik99** [patchthecode/JTAppleCalendar#471]
Please add features like day view and week view for calender.

Waiting for updates.

**Comment by patchthecode** [comment]
what is dayView and weekView? got a screenshot?

**Comment by patchthecode** [comment]
closing this issue until further user input.

**Comment by davidseek** [comment]
i assume he is talking about a view to set events for "hours" within a day

**Comment by patchthecode** [comment]
Hmm.. nice feature, but i do not think this library will support it.
I think it will be doing too much on this one control.
Unless maybe you guys can suggest a way to do it without cluttering code? :) 🍻
