### ISSUE TITLE
didScrollToDateSegment method isn't called when the screen is simply dragged

### ISSUE THREAD

**Issue by aaronjedwards** [patchthecode/JTAppleCalendar#472]
I am using v 7.0 and have noticed that the delegate method 'didScrollToDateSegment...' only fires when the view is scrolled and has an acceleration. In other words, unless you 'flick' when scrolling (the calendar continues to scroll after having let go of the screen and then comes to a stop), this method doesn't seem to get called. I am creating a calendar with a continuous scroll without paging and want to change a header in a navigation bar when scrolling to a new month. I have achieved my desired effect, but it is inconsistent due to this method not firing when the view is simply dragged.

**Comment by patchthecode** [comment]
are you using version 7.0.4 ?

**Comment by aaronjedwards** [comment]
Yes, I am.

**Comment by patchthecode** [comment]
Alright, i'll have a look after work

**Comment by patchthecode** [comment]
if you just drag the control, can you put the code in this delegate function instead? Let me know if it works.

`func scrollDidEndDecelerating(for calendar: JTAppleCalendarView)`

**Comment by aaronjedwards** [comment]
I'll take a look at it here in an hour or so and let you know. Thanks for the prompt responses.

**Comment by aaronjedwards** [comment]
Using the suggested delegate method solved the issue. Thanks!

**Comment by patchthecode** [comment]
Awesome. Closing this issue now. 🍻
