### ISSUE TITLE
Trying to highlight current date and change text colour

### ISSUE THREAD

**Issue by fweathers** [patchthecode/JTAppleCalendar#474]
Currently using the newest version 7.0.4

I was trying to highlight the current day and change the colour of the text as well. I have tried 

```swift
if myCalendar.isDateInToday(date) {
   cell.backgroundColor = UIColor.blue
   cell.dateLabel.textColor = UIColor.white
} else {            
   cell.backgroundColor = UIColor.white
}
```

but i end up with random dates highlighted once I have swiped through different months. Also, the text dos not change

**Comment by patchthecode** [comment]
In which function do you have this code?

It should be in your `cellForItemAt` function.

```
if myCalendar.isDateInToday(date) {
   cell.backgroundColor = UIColor.blue
   cell.dateLabel.textColor = UIColor.white
} else {            
   cell.backgroundColor = UIColor.white
   cell.dateLabel.textColor = UIColor.black
}

**Comment by zhanswift** [comment]
I got 

> Value of type 'JTAppleCalendarView' has no member 'isDateInToday'

**Comment by zhanswift** [comment]
I do with this, but now  

    func handleCellCurrentDay(view: JTAppleCell?, cellState: CellState) {
            guard let validCell = view as? CalendarCell else { return }
        
        let currentDay = Date()
        
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "dd MM yyyy"
        
        let currentDateString = dateFormatter.string(from: currentDay)
        let cellStateDateString = dateFormatter.string(from: cellState.date)
        
        if  currentDateString ==  cellStateDateString {
            validCell.selectView.isHidden = false
            validCell.selectView.backgroundColor = UIColor.rgb(red: 232, green: 58, blue: 92)
            validCell.selectView.layer.cornerRadius = 22.5
            validCell.label.textColor = UIColor.white
        } else {
            validCell.currentDaySelectView.isHidden = true
            validCell.label.textColor = UIColor.black
        }
    }

But now I got wrong display of current month

<img width="375" alt="2017-07-04 12 59 50" src="https://user-images.githubusercontent.com/16617536/27818786-044bc984-60b9-11e7-9d30-2f49b4515bf4.png">

**Comment by fweathers** [comment]
I have it in my cellForItemAt function but it doesn't seem to work

> func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
>         let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
>         
>         cell.dateLabel.text = cellState.text
>         
>         if myCalendar.isDateInToday(date) {
>             cell.backgroundColor = UIColor.blue
>             cell.dateLabel.textColor = UIColor.white
>         } else {
>             cell.backgroundColor = UIColor.white
>             cell.dateLabel.textColor = UIColor.black
>         }
>         
>         handleCellSelected(view: cell, cellState: cellState)
>         handleCellTextColor(view: cell, cellState: cellState)
>         
>         return cell
>     }
> 
<img width="432" alt="screen shot 2017-07-06 at 9 04 35 am" src="https://user-images.githubusercontent.com/12614576/27912194-fb0d32a0-6229-11e7-9c23-b8d659d33793.png">

**Comment by patchthecode** [comment]
@fweathers can you zip a small sample project and drop it in the the chat box here so i can have a look?

**Comment by fweathers** [comment]
Unfortunately i am using it in an app for work which i am unable to send over. However, I am going to try and make a quick side project with it to send to you. Thank you for your quick responses

**Comment by patchthecode** [comment]
There is an example video [Here](https://www.youtube.com/watch?v=CQNotydm58s) now to explain this. Does it help?

**Comment by patchthecode** [comment]
Been 7 days. I'll close this issue until further input is provided.

**Comment by fweathers** [comment]
Thanks :-) sorry for the late response. Def helpful.
