### ISSUE TITLE
How I change calendarView.scrollDirection programmatically?

### ISSUE THREAD

**Issue by sahok-shustov** [patchthecode/JTAppleCalendar#475]
Hello. First of all I want to thank for the work done! It is very cool!!!
At the start of the application, scrollDirection is installed in the StoryBoard to .vertical
After in my CalendarMainContriller I assign scrollDirection to .horizontal

"self.calendarView.scrollDirection = UICollectionViewScrollDirection.horizontal"

but scrolling calendar horizontal not working. He remained the same.
Although in console I see true after redefinition self.calendarView.scrollDirection

"print("self.calendarView.scrollDirection == .horizontal    ----------   \(self.calendarView.scrollDirection == .horizontal)")"

**Comment by sahok-shustov** [comment]
Sorry)))
It was necessary to restart the calendar))) Thanks again for your work

**Comment by gsuthor** [comment]
> Sorry)))
> It was necessary to restart the calendar))) Thanks again for your work
Hi,

How did you restart the Calendar? If i close the App and restart it works, but how did u restart programmatically?

**Comment by patchthecode** [comment]
call reload?

**Comment by gsuthor** [comment]
> call reloadData()?

I must have been a little confused that night, that's definitely how it works. Thank you, once again.
