### ISSUE TITLE
Expandable calendar

### ISSUE THREAD

**Issue by lukejones1** [patchthecode/JTAppleCalendar#477]
Any idea how I could implement this feature?

https://github.com/jonathantribouharet/JTCalendar/blob/master/Screens/example.gif

calender shrinks to a single row and scrolls to it once selected.

I tried changing the number of rows when the user taps a date but it seems to act pretty buggy when trying to scroll to the selected date and change to a single row.

I also attempted to modify the cell size but I can't seem to programmatically change the cell height of each cell.  At all times the cell height seems to remain calculated to fit there screen. 

This also caused problems when I tried to hide some of the tableView behind the view and setting the zPosition of -1.  Even though I set the calendar height to 300 pixels, with 250 pixels of the view being covered by another view, it will still try and fit all rows into 50 pixels which seemed a little odd.

**Comment by patchthecode** [comment]
To make an expandable calendar, simply change the height of the calendar frame like you would any other view.

But you will need to explain to me some on what this means. Maybe a gif might explain.

> but it seems to act pretty buggy when trying to scroll to the selected date and change to a single row.

**Comment by lukejones1** [comment]
I'll put together some examples later on

**Comment by lukejones1** [comment]
https://cl.ly/1Z0C0s26083L - This is the issue when decreasing the number of rows from 6 to 1.  I attempt to decrease the number of rows then scroll to the date but when increasing the number of rows to 6 again I can't go back to the original month/section the user was at.

**Comment by patchthecode** [comment]
OK, i saw the gif.
Can you explain to me which part is buggy? I need to know what you want the expected behavior to be before suggesting a solution. Can have you tried scrolling to that date with animation set to false?

Or, if this does not work for you have you tried reloading with the `anchorDate` set to the date you want the calendar to appear at? `anchorDate` is a new feature located on master branch. Let me know if it works for you.

**Comment by lukejones1** [comment]
Managed to solve it! For some reason in my head I was expecting the calendar to scroll to the correct date after increasing the number of rows again but thats obviously not the case.  It seems to I have to scroll again after i set the number of rows and reload the calendar.

Nevertheless, thanks for your help 👍 :)

**Comment by patchthecode** [comment]
awesome man. cool.
