### ISSUE TITLE
Update the tutorial https://patchthecode.github.io/MainTutorial/

### ISSUE THREAD

**Issue by Eriknng** [patchthecode/JTAppleCalendar#478]
The [tutorial](https://patchthecode.github.io/MainTutorial/) is outdated. Are there any possibilities of editing the tutorial so it can be done in latest Swift?

Regards,
Erik

**Comment by patchthecode** [comment]
The tutorial there for is both for version 6 and version 7 -> https://patchthecode.github.io/
Scroll to the bottom to see the version 7 Links.
Does this work for you?

**Comment by Eriknng** [comment]
Thanks for your reply.

I can create a calendar swiftly using the tutorials for version 7. However the tutorial I linked created a calendar with a CellView.xib-file which is what I am interested in.

**Comment by patchthecode** [comment]
@Eriknng yes. Those tutorials you linked to were for version 6.
Many people are still using versio 6, so i left it there until i remove it.
