### ISSUE TITLE
White vertical line in calendar

### ISSUE THREAD

**Issue by HermantoTang** [patchthecode/JTAppleCalendar#480]
Hi, I'm using the latest version (7.0.4) and experiencing issue similiar to #26, #205, #227
Here is the screenshot (using iPhone 5s device)
![img_0614](https://user-images.githubusercontent.com/16204739/28049467-c82b4bf0-6621-11e7-9963-ffab004a3b10.PNG)
And here is my setup
```swift
    func setupCalendarView() {
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        calendarView.allowsMultipleSelection = true
        calendarView.isRangeSelectionUsed = true
        calendarView.cellSize = calendarView.frame.size.width / 7
        
        calendarView.register(
            UINib(nibName:"DatePickerHeader", bundle: Bundle.main),
            forSupplementaryViewOfKind: UICollectionElementKindSectionHeader,
            withReuseIdentifier: "CustomHeader"
        )
        
        let startDate = Date()
        let endDate = Calendar.current.date(byAdding: .day, value: 1, to: startDate)!
        calendarView.selectDates([startDate, endDate])
    }
```

I have a view inside cell for coloring selected date, the view constraint is set to fill the cell (top, left, bottom, right = 0).

I have also tested on iPhone 7 (Simulator) and its working fine
However, iPhone 7 Plus (Simulator) shows ~1px overlap (see the red circle)
![screen shot 2017-07-11 at 10 41 19 am](https://user-images.githubusercontent.com/16204739/28050127-ecc4f55c-6625-11e7-8905-2a4597b778cc.png)

Any advice regarding this issue? Am I missing something?

Great project btw, like it ;)

**Comment by patchthecode** [comment]
That vertical line is the same as you will get if you implement any other UICollectionView.

To get rid of it, simply set the width of the `calendarView` to be something that is divisible by 7 such that the value is not a recurring decimal value.

Look on [This Link](https://github.com/yonasstephen/swift-of-airbnb) on how this guy does it with his collectionView
On that link look for the line that says -> 

```
Things I learn:

    All kinds of things with UICollectionView (didSelect, didHighlight, shouldSelect, shouldHighlight, de/selecting cells programatically, etc.)
    One issue that made me stuck for days was there was tiny pixel gap between date cells that I couldn't remove. I posted the solution here: http://stackoverflow.com/a/42574952/2105910
```

**Comment by HermantoTang** [comment]
I tried to apply the solution, it seems like it only works if the calendar is full width (same as device width)
In my case, calendar is showed like a modal which is why i wrapped calendar inside another view with padding (like the photo in my previous post), it's not working if i divide my wrapper by 7
```swift
// By changing 'view' to my 'wrapperView'
var itemWidth: CGFloat {
    get {
        return floor(wrapperView.frame.size.width / 7)
    }
}
```
And also if i remove my wrapperView and apply full width to my calendar, my header is also resized which make white line appear in left side of my header
![screen shot 2017-07-11 at 5 01 36 pm](https://user-images.githubusercontent.com/16204739/28063273-cc7694e2-665a-11e7-8680-d5d0a63c8a61.png)

**Comment by patchthecode** [comment]
The answer is not to divide by seven. The answer is to set the calendar's width to a size that is divisible by seven without a recurring decimal place.

in your code, can you tell me what is the value of this? -> `wrapperView.frame.size.width`

**Comment by HermantoTang** [comment]
``wrapperView.frame.size.width`` is 315 regardless of devices
I then apply this
```swift
        let gap = wrapperView.frame.size.width - (itemWidth * 7)
        calendarView.widthAnchor.constraint(equalTo: wrapperView.widthAnchor, constant: -gap).isActive = true
        calendarView.cellSize = itemWidth
```

**Comment by patchthecode** [comment]
Hey can you join gme here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by HermantoTang** [comment]
I apply [this](https://github.com/Juanpe/JTAppleCalendar/commit/f3edaa54407c295468caf650e13c73b917ba4deb) as you suggested and its working fine right now. Haven't spot any issue so far

Thanks
