### ISSUE TITLE
Highlight day if the date equal to date in array

### ISSUE THREAD

**Issue by ahmedraad** [patchthecode/JTAppleCalendar#481]
I have an array of object contains bookings

```
class MonthBookings: NSObject {

    var date: Date = Date()    
    var bookings_count: Int = 0
}

var bookings = [MonthBookings]()
```

So I need to check if cell date is equal to some date in bookings array then change cell color for this date in cell.

I have tried this way down below but didn't work:

```
func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleDayCellView, date: Date, cellState: CellState) {
    guard let sfbCell = cell as? SFBCalendarCell else {return}

    let booking = self.bookingsMonths[cellState.row()]

    if booking.date == date {
        sfbCell.dayText.textColor = .red
    } else {
        sfbCell.dayText.textColor = .black
    }
}
```

**Comment by johnharutyunyan** [comment]
Please answer this question , I have same problem for this

**Comment by patchthecode** [comment]
try to use a dictionary inplace of an array  if possible. = less looping
try to compare date strings instead of actual date values. This is easier especially if you format the string without hh:mm:ss

**Comment by johnharutyunyan** [comment]
I have events array which contain Event model (with eventDate property )
I get it from server and want to fill in calendar , but I can't , cuz I have problem with indexPath.
Can you show me example code for better understanding.
Thanks...

**Comment by johnharutyunyan** [comment]
Guys, I solved this problem like this.
I have array of dictionaries with `'date'` // dates are that array which I get from server

// Format Cell Date without 'hh:mm:ss' , e.g 2017-07-15
`let currentDate = CBDateFormatter.getCurrenEventDate(with: cellState.date)`

```
if let dictionary = dates.first(where: { $0["date"] as? String == currentDate }) {
  
   // Do something when equal dates 
   cell.backgroundColor = .red
}
else {
    cell.backgroundColor = .clear
}
```

Thank you so much for fast response

**Comment by RoshaniDias** [comment]
I have the same problem. Where did you implement this?

**Comment by johnharutyunyan** [comment]
You can do it in datasource function

`func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell`

but using in Custom cell class best practice.

For example 

`cell.fill(with: cellState, dates: dates)`

Hope it'll help .
Say me if you have any question

**Comment by RoshaniDias** [comment]
is your 'dates' array Any<Any> type?

**Comment by johnharutyunyan** [comment]
No, like this
`var dates = [Dictionary<String, AnyObject>] () `

**Comment by johnharutyunyan** [comment]
I get it from server , the request manager give me all dates from Server , I parse it like this 

```
 calendarRequestManager.getEventsOnCalendar(with: urlTail,
                                         success: { datesArray in
                                            
                                            var dates = [Dictionary<String, AnyObject>]()
                                            var dateDict = Dictionary<String, AnyObject>()
               
                                            for dictionary in datesArray {
                                   
                                                if let dateString = dictionary["created_date"] {
                                                    
                                                    let date = CBDateFormatter.eventDate(from: dateString as! String)
                                                    dateDict["date"] = date as AnyObject
                                                }
                                                
                                                if let categoryId = dictionary["category_id"] {
                                                    
                                                    dateDict["categoryId"] = categoryId as AnyObject
                                                }
                                                
                                                dates.append(dateDict)
                                            }
                                            
                                            success?(dates)
                                            
                                            
        }, failure: { error in
            
            failure?(error)
        })
```

**Comment by RoshaniDias** [comment]
Thanks,, In my case I am getting start date and end date in the array of dictionaries. And I want to highlight in between dates. Do you have any idea to implement that?

**Comment by ahmedraad** [comment]
@johnharutyunyan you're awesome, thanks for solution

**Comment by johnharutyunyan** [comment]
@RoshaniDias,  I think  better solution is get key / allKeys from dictionary and compare with start and end date.
Let me know if I can help .

**Comment by johnharutyunyan** [comment]
@ahmedraad , you're welcome , thank you too

**Comment by zuaaef** [comment]
@johnharutyunyan @ahmedraad @RoshaniDias i think he put it in this video -> https://www.youtube.com/watch?v=CQNotydm58s

**Comment by johnharutyunyan** [comment]
@zuaaef  cool , thank you!

**Comment by patchthecode** [comment]
closing this issue. If there are still problems here, let me know and i will re-open this and help solve it.
