### ISSUE TITLE
JTAppleHeaderView

### ISSUE THREAD

**Issue by Methos456** [patchthecode/JTAppleCalendar#482]
Version 7.0.4

First I am sort of new to iPhone programming and the JTAppleCalendar is a great learning tool..  I have my calendar looking sort of the way I would like; however, I am trying to use a Header.  I cannot seem to find the class JTAppleHeaderView anywhere in the Pod download.  

Any help is appreciated..

**Comment by patchthecode** [comment]
can you check out the example app attached to this project?

**Comment by Methos456** [comment]
Wow.. That was quick.. thanks!   Some other examples I have seen had the header class of type "JTAppleHeaderView" which I could not locate...   

I will try the the JTAppleCollectionReusableView ..

Thanks Again!

**Comment by patchthecode** [comment]
Cool. closing this issue.
If you still need help here then let me know.
