### ISSUE TITLE
How can i stop the calendar from scrolling passed the end date?

### ISSUE THREAD

**Issue by Dansong00** [patchthecode/JTAppleCalendar#483]
How can i stop the calendar from generating new sections after the end date?

**Comment by patchthecode** [comment]
let me know if this solution works for you -> https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by Dansong00** [comment]
hey @patchthecode thanks for the quick response! i actually saw that solution earlier and implemented it, but the project requirements would prefer a solution where the calendar doesn't scroll back to the start date but rather just stop generating new rows and sections and rather allow the user to simply scroll back up.

**Comment by patchthecode** [comment]
ok. So let me know one thing.
Is it a vertical or horizontal calendar?

Also, one thing, let me know if the following is true.
1. the boundaryd ate solution works
2. but you would not like to see any generated dates behind the boundary

?

**Comment by Dansong00** [comment]
This is a vertical calendar. Yes to both of your other questions. @patchthecode

**Comment by patchthecode** [comment]
Then can you implement the solution, but make one addition.

And date that is after the boundary date, set its `isHidden = true`
That way, it will behave the same, the generated dates after the boundary will not be visible.
Will this work?

**Comment by Dansong00** [comment]
So what happens there is the cells after the end date are hidden but you can still keep scrolling to blank sections.

**Comment by patchthecode** [comment]
@Dansong00 
> but you can still keep scrolling to blank sections.

I do not understand this part. How can you still keep scrolling to blank sections if the boundary code prevents this?  Have you got a quick gif/mov file i can look at, or maybe if you can create a quick sample project with the issue.

**Comment by Dansong00** [comment]
Sorry for the long reply so in the calendar (.... willDisplayCell... ) i set the dateCell to hidden if it's beyond the endDate.  Then what happens is i am able to continue to scroll after the end date at which point an out of index exception occurs which crashes the app.
![image](https://user-images.githubusercontent.com/2747416/28384465-d991a0d4-6c92-11e7-8a35-3eb0bc728e2c.png)

![screen recording 2017-07-19 at 02 52 pm](https://user-images.githubusercontent.com/2747416/28384544-18aa56a8-6c93-11e7-825a-c794aed75a7c.gif)

![image](https://user-images.githubusercontent.com/2747416/28384576-36459e02-6c93-11e7-8f95-c6c2b1c54122.png)

**Comment by patchthecode** [comment]
@Dansong00 how problematic is it for you to upgrade to version 7.0?

**Comment by Dansong00** [comment]
No worries. will upgrade to version 7, hopefully that fixes my issue. will keep this thread updated.

**Comment by patchthecode** [comment]
closing issue.
setting tag to: Awaiting user input

**Comment by patchthecode** [comment]
As an added help to migrating to version 7.0
Here is the full tutorial set -> https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q

**Comment by Dansong00** [comment]
There are a lot of methods that and properties that have been deprecated in version 7 that were available in version 6 and no documentation on version 6 to explain how to transition. i've been having quite a difficult time with the upgrade.

**Comment by patchthecode** [comment]
I'm usually hanging out in here unless i'm asleep. -> https://gitter.im/patchthecode/JTAppleCalendar
Drop me a message, and i'll help.

**Comment by Dansong00** [comment]
hey @patchthecode  i've been dropping in on that link but you seem to respond  here faster haha. managed to set the calendar up with the upgrade, but still have trouble making somethings work. I am trying to use the method pathsFromDate([ ]) and i keep getting a pathsFromDates is inaccessible due to 'internal' protection level compiler error. would greatly appreciate any help in getting that resolved.

**Comment by patchthecode** [comment]
@Dansong00 thats because  pathsFromDate is set to be internal.
Let me know what is it you are trying to accomplish, then i may be able to help.

**Comment by Dansong00** [comment]
@patchthecode in the previous version of this module, i would use the pathsFromDate method to obtain the IndexPath for a given date and from that indexPath i would obtain the section that date belonged to. If there is another way to obtain the section for a given date that would work as well.

**Comment by patchthecode** [comment]
I removed it because I didnt think it would be needed.
What I put for the replacement for section was the date section rage that a particular date belonged to.  

Can you let me know how exactly you used that section number? If i know how it was used, then I would be better able to tell you the replacement.

**Comment by Dansong00** [comment]
I keep track of the section in my calendar. an example of one way i'd use the section is if a user selects a visible date that is in a different section, i would use the collectionview method scrollToItem to snap the user to that section. I also use the scrollViewWillEndDragging method to update my header, and in order to do so i need to know if the section i'm is different from the section i just scrolled from.

**Comment by patchthecode** [comment]
hmm. i guess this is the part i do not understand. Maybe if you join me here we can chat -> https://gitter.im/patchthecode/JTAppleCalendar

But if you want to snap to a date that is in a different section, all you have to do is use the following function -> `calendarView.scrollToDate( theDateYouWantToSnapTo )`

And for the `scrollViewWillEndDragging`, what you had to use was the following delegate function -> `func scrollDidEndDecelerating(for calendar: JTAppleCalendarView)`

Join me on chat, if i wasnt clear.
