### ISSUE TITLE
Calendar load slow

### ISSUE THREAD

**Issue by yeziahehe** [patchthecode/JTAppleCalendar#484]
I use selectDates function in viewDidLoad()，just set unordered Array from year 2015-2017，but it slow。
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        configureCalendarView()
        calendarView.selectDates(historyDateArray)
    }

    func configureCalendarView() {
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        calendarView.allowsMultipleSelection = true
        calendarView.visibleDates { (visibleDates) in
            SafeDispatch.async { [weak self] in
                self?.calendarView.scrollToSegment(.end, animateScroll: false)
                self?.configureViewOfCalendar(visibleDates: visibleDates)
            }
        }
    }
```

**Comment by patchthecode** [comment]
is it still slow if you change this part?

```swift
        calendarView.visibleDates { (visibleDates) in
             self?.calendarView.scrollToSegment(.end, animateScroll: false)
             self?.configureViewOfCalendar(visibleDates: visibleDates)
        }
```

**Comment by yeziahehe** [comment]
SafeDispatch just the func DispatchQueue.main.async.

I remove SafeDispatch then it still slow, then i annotate **calendarView.selectDates(historyDateArray)**, this question will be sloved.

so i think the reason make slow is selectDates, but i don't know why.

**Comment by patchthecode** [comment]
How many dates are you selecting?

**Comment by yeziahehe** [comment]
http://gank.io/api/day/history
This api back data.

Project you can download [repo](https://github.com/yeziahehe/Gank), HistoryViewController you can find selectDates.

**Comment by patchthecode** [comment]
Thank you.
Do you want it faster?
Is this ok?
```swift
calendarView.selectDates(self.historyDateArray, triggerSelectionDelegate: false)
```

**Comment by yeziahehe** [comment]
it has work, but may still a little lag.

so which is the delegate func of triggerSelectionDelegate ?

**Comment by patchthecode** [comment]
I am trying to make it faster.

Is it possible you can select less dates at the start?

**Comment by patchthecode** [comment]
closing this issue until further user input.
