### ISSUE TITLE
How to implement inside headers scrollable? 

### ISSUE THREAD

**Issue by DanteEvil** [patchthecode/JTAppleCalendar#486]
I'm using the latest version and want to have a scrollable inside header for my custom calendar. I've read this example but it seems doesn't work anymore.
https://patchthecode.github.io/Headers/

**Comment by zuaaef** [comment]
@DanteEvil look at the last video in this play list -> [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)

**Comment by patchthecode** [comment]
Let me know if the posted vid answers your question
