### ISSUE TITLE
How to lead to a daily screen with time and events when clicked on a date with events

### ISSUE THREAD

**Issue by etanboga** [patchthecode/JTAppleCalendar#487]
Hello, I am making this app where a user can log feelings whenever he / she wants. The log is written into firebase using a JSON structure like date -> time -> log. I would like to show certain feelings when a user clicks on a specific date. For example clicking on 7/16/17 would lead to a daily screen, like a table view with times of the logs (11.15 AM Happy, 1 PM Hopeful, 6 PM Strong). How can I achieve this through this library?

I looked over every tutorial but could not find much related to adding events. Thanks a lot for this amazing API and I would be really happy if you could reply ASAP as I am working on my app in a bootcamp :)

**Comment by patchthecode** [comment]
just wondering if you looked at the last tutorial on (this play list](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)?

Its called **Common Questions # 1**
It think it has an example on how to load things from a server and displaying them?
If this vid tutorial does not answer your question, then can you let me know on which part you are stuck? I can help further.

**Comment by etanboga** [comment]
I did, and it does have an example, however in that example there is only one event per day, and I will have multiple logs in each day. I am having trouble getting my head around how to implement that, maybe by leading to a different screen? Is there a way to make the calendar lead to a daily view when clicked on a cell?

**Comment by etanboga** [comment]
Update: I fully set up my calendar (the part from the tutorial) and the months do not seem to update as rapidly. If you could help out with that as well, that would be amazing :)

**Comment by etanboga** [comment]
Hello I think I should be good on other issues, however right now the problem is that my scrolling does not work as yours do. I have to manually scroll everywhere whereas in your app, if you scroll between months, it automatically goes to that month. In addition, when I set scroll to today's date, it shows it in between maps. I noticed there was another thread related to this issue, however I couldn't find an answer there. Thanks a lot for the help in advance

**Comment by patchthecode** [comment]
ok i'm @ work right now.
But i can take a quick look if you provide a striped down version of your porject (with no secret company code in it).
If you provide a zipped file of the project i can take a quick look, else i can only look more into it after work in 7hrs

**Comment by etanboga** [comment]
Okay, I will work on it myself until the evening and I will send you the source code for the calendar setup once I come back to home. I think I will be able to fix problems other than the scrolling. Thank you so much for this support!

**Comment by etanboga** [comment]
Hello, sorry I couldn't email you last night, I will send the email you the source code for the calendar part right now

**Comment by etanboga** [comment]
I sent you an email @ patchthecode@gmail.com

**Comment by patchthecode** [comment]
i checked out the file.
This isnt an error.
Based on the image below, please select/deselect the following values of the `JTAppleCalendarView` on your storyboard.

<img width="263" alt="screen shot 2017-07-21 at 7 14 35 pm" src="https://user-images.githubusercontent.com/2439146/28487602-f1a4f5ce-6e48-11e7-8add-5aa1c5c6cd90.png">

**Comment by etanboga** [comment]
I changed it and it works perfectly now, thank you so much for taking the time out of your day to help :)

**Comment by patchthecode** [comment]
Awesome. Cheers mate 🍻
