### ISSUE TITLE
XIb Files

### ISSUE THREAD

**Issue by fweathers** [patchthecode/JTAppleCalendar#488]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.4
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
4. Don't just ask a question. Provide enough information so I will be able to recreate the problem you are facing. 
   It would be even better if you provided an example app if possible.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

Is it still possible to utilize xib files with the new version of the calendar?

**Comment by patchthecode** [comment]
yes it is.

**Comment by fweathers** [comment]
Cool thanks, I used the wrong method with autofill code. But I am having trouble actually viewing the calendar bc I keep receiving an error on the 'setupNewLayout(from: collectionViewLayout as! JTAppleCalendarLayoutProtocol)' in the section for initializes using decoder object

**Comment by fweathers** [comment]
Thank you!!!! Your calendar is GREAAATTTT!!!

**Comment by patchthecode** [comment]
Haha, thank you.
