### ISSUE TITLE
every time I run and build only the month and year is displayed

### ISSUE THREAD

**Issue by hejlyeah** [patchthecode/JTAppleCalendar#489]
I am using the latest version of JTAppleCalendar. Every time I run and build the app the calendar does not appear. I fixed it in another project but then when I wanted to run the same build on a smaller screen size the calendar would either get cut off or not appear. Please help me find a solution please!!!!! Also Please excuse the project name lol
[fuckingBullshit 2.zip](https://github.com/patchthecode/JTAppleCalendar/files/1164541/fuckingBullshit.2.zip)

**Comment by patchthecode** [comment]
I think you need learn some more on your constraints. The problem was that you had a lot of conflicting constraints. Please excuse the project name. I am a Christian.
[JesusSaves5.zip](https://github.com/patchthecode/JTAppleCalendar/files/1164677/JesusSaves5.zip)

**Comment by patchthecode** [comment]
closing this issue. If you still need help on it then let me know.

**Comment by hejlyeah** [comment]
Hey JT,

You are literally a lifesaver. Not quite like your Christian friend Jesus, but a lifesaver all the same:) I am using this calendar to create an app for my high school, and I want the calendar to display events upcoming whether it be a football game or a drama event. I was thinking for every item I would include a title, and a description at the minimum, maybe include another parameter/variable (not sure what Is the proper name) for the time of the event. I am attempting to get that little white dot to appear beneath days that have events. I hope my issue is not again something embarrassing/amateurish as constraints, but all the same I would appreciate some help getting the white dot to appear. The issue still appears on the same workspace you sent me.

I want to have my entire app completed within a week’s time, and I still need to create an activity feed for my initial view controller, a directory with information for students who want to tutor other students, a staff directory, and a page including basic information like our bell schedule and campus map and whatnot. 

Make no mistake I am not asking for your help without giving anything in return. I would be more than happy to support you and your projects through PayPal, you have already been more than helpful and your cocoapods have saved me weeks. 

Let me know to what extent you may be willing to help; if you’d just be willing to help me make the little white dot indicator appear, that’d be awesome— if more, even better :) I am trying to sync my application information with Google firebase, maybe you are familiar? 

I only just taught myself swift app development, so I am doing my best to learn quickly as creating this app will become instrumental in helping me get into a good college. Your help would be more than appreciated

My Skype is Zachary.hejl if you want to reach out that way, and my discord is Hejlyeah.

Thanks for anything you can do to help!! Have a nice day.

Zachary Hejl
zachdhejl@gmail.com

**Comment by patchthecode** [comment]
Haha. OK man.
I dont know how much i can help, because i am extremely tied up right now.
But, I can see what i can do after work today.

In the mean time, have you looked at this video yet? It shows you how to setup the dot views to your app -> it is the very last video [In this Playlist](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)

**Comment by hejlyeah** [comment]
Hey JT, any chance you have time for a Skype today?
