### ISSUE TITLE
Question: Vertical, Seamless Calendar

### ISSUE THREAD

**Issue by Chazzman** [patchthecode/JTAppleCalendar#491]
Hello,

I'm trying to use the component to create a continuous scrolling, vertical calendar like the one found here: [https://github.com/Glow-Inc/GLCalendarView ](url). 

I am able to create a vertical calendar easily enough but I am not able to figure out the right combination of properties to get one month to seamlessly flow into the next month. There's always some sort of break with either in/out days or the new month starting at the beginning of the row even though the month doesn't start on Sunday. 

I've review all the examples that others have provided but don't see anyone doing what I am seeking on doing. I hope that this is doable as I prefer to use this component.

**Comment by patchthecode** [comment]
@Chazzman can you join me [Here](https://gitter.im/patchthecode/JTAppleCalendar)?

**Comment by patchthecode** [comment]
this is easy to do here ->

in your `configureCalendar` function, put this as your configuration parameters:
```swift
let parameters = ConfigurationParameters(startDate: yourStartDate,
                                                 endDate: yourEndDate,
                                                 numberOfRows: yourNumberOfRows,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .off,
                                                 hasStrictBoundaries: false)
```

This will get you your desired config.
Let me know if you are still having problems. Closing this issue now.

**Comment by Chazzman** [comment]
Perfect!!

Thanks much!
