### ISSUE TITLE
dates with events from server not behaving as required while scrolling

### ISSUE THREAD

**Issue by LakshayNagpal** [patchthecode/JTAppleCalendar#492]
Hi Jay,
Thanks for the great library.
I am facing an issue while showing the imageview of a dot for specific dates coming from the fake server as described in your tutorial video. In my calendar, dots are placed perfectly when pressing the next and previous buttons but some of them gets removed when scrolling it back and forth.

I was trying one method in which I was selecting the dates coming from server and then showing dot on the date selected by calling isSelected in Delegate method but got unsuccessful in implementing the same.

If you can check my [code](https://github.com/LakshayNagpal/Calendar-iOS) and suggest the method described above or propose any other solution using predefined libraries of the JTAppleCalendar.

P.S. - I'm running the latest version of JTAppleCalendar.

Thanks!

**Comment by patchthecode** [comment]
your code is perfect.
But you are reusing the same date `formatter` all over your code.

In some places you have changed the date format to "MMMM"
therefore by the time you start scrolling the calendar, your

```swift
cell.dotView.isHidden = !eventsfromtheserver.contains { $0.key == formatter.string(from: cellState.date)}
```

line has a wrong format for your calendar and there for it cant find your dates.
To solve the problem you can do either of 2 things.

1. Use 2 formatters so that it doesnt conflict
2. Or you can put this line of code in your `cellForItem` function

```swift 
        ...
        formatter.dateFormat = "yyyy MM dd"
        cell.dotView.isHidden = !eventsfromtheserver.contains { $0.key == formatter.string(from: cellState.date)}
        ...
```

Then it will work

**Comment by LakshayNagpal** [comment]
Thanks Jay for your swift response!
Can you please tell me how you figure out this problem as it will help me in future for debugging my code quickly and effectively.
Thanks Again :)

**Comment by patchthecode** [comment]
The dots show up he first time.
but then when you scroll, they are removed.

so, just go the the function that handle the dots. And see why this line is failing.
```swift
        cell.dotView.isHidden = !eventsfromtheserver.contains { $0.key == formatter.string(from: cellState.date)}
```

When debugging, print statement is your friend.
```
print(formatter.string(from: cellState.date))
```

Then you will see a wrong date being generated.

**Comment by LakshayNagpal** [comment]
I will keep this suggestion in mind.
Thanks mate!
