### ISSUE TITLE
eventDotView not appearing, error "unwrapping nil value" for startDate and endDate

### ISSUE THREAD

**Issue by hejlyeah** [patchthecode/JTAppleCalendar#493]
Took the project you gave me and added a header and changed layout a little bit. Everything was working fine, now I am getting an error saying that I am force unwrapping a nil value inside my configureCalendar function. Now I know my error is not as stupid as constraints this time. Spent a couple hours on this, sorry to ask you for help again but can you tell me what the hell I am doing wrong? The eventDotView is still not showing as well and Ive watched your video several times to check if I made a mistake. Short for time, please help!!

Thank you!
[JesusSaves5.zip](https://github.com/patchthecode/JTAppleCalendar/files/1167749/JesusSaves5.zip)

**Comment by patchthecode** [comment]
Couple errors.

1. Click on your calendarView in interface Builder. under Size inspector, you'll see `minSpacing` for Lines and Cells = 10. This means your cells have a 10 inset. Therefore you will not see your dot views. This 10/10 happens by default each time you drag a CollectionView unto your interface builder. You can thank Apple for that.
2. you are using the same `formatter` all over your app and are changing its format to sometimes be "yyyy". So either you use different formatters, or put this line inside of your `configureCalendar` funciton. `formatter.dateFormat = "yyyy MM dd"`

Here is the fixed project.
[JesusSaves5.zip](https://github.com/patchthecode/JTAppleCalendar/files/1167909/JesusSaves5.zip) Cheers 🍻

**Comment by hejlyeah** [comment]
JT! You could quite possibly be my favorite person ever. Thanks for all the help man! Take care brother

Zach

**Comment by patchthecode** [comment]
AH thanks. Have a good. one. 👍

**Comment by hejlyeah** [comment]
Hey JT,

How would you feel about skyping me for only a couple hours and helping me learn how to finish up this project for my high school? You really know what you are doing and could save me a lot more of my high school summer. I could try to pay you? Im a pizza delivery driver and bet I could pay you for a few hours. Or if you do not have the patience to teach me, I might persuade you just to pay you to help me finish it? What do you think? I do not mean to continue pestering you, I am just desperate and running out of options as the beginning of the year quickly approaches…

Get back to me, whatever your response is is completely fine I am sure you have a busy schedule as it is anyway. I could become flexible to whatever your schedule looks like although. Anyways, thank you man, thanks for everything already and take care.

Zachary Hejl
zachdhejl@gmail.com <mailto:zachdhejl@gmail.com>

**Comment by patchthecode** [comment]
if i can, i will help. But i can't make any promises.
What ever you're stuck with just ask. I can't promise prompt responses every time though as I an tied up with a couple projects.

**Comment by hejlyeah** [comment]
Thank you!! Whatever you might be willing to help me with would be more than appreciated!

I am attaching a workspace updated with the changes you said to make the last time. Everything works incredibly! Elegantly simple, thank you!

I added a couple things. I was working on an addition to the workspace yesterday: I want there to be a table view beneath my calendar to display a title and string for an event corresponding with the date selected. In a separate workspace nearly in duplicate to the one I am sending you now, I created a custom “Event” class to be affiliated with a date and had that returned from the getServerEvents function. I am stuck with how to get anything to display in the table view,  I am sending you now. In the table view cell I only have a title and description; these two are all I need, but if there are more than two events for a given day I want there to be the proper number of cells as well.

I am doing more research and experimentation currently, I will email you again if I find anything which helps offer a solution to my problem. In the meantime, if you have the time, I know you could knock it out in ten minutes if you chose to. 

I hope I am being clear and hopefully this makes sense. I will keep working and let you know. Thank you JT! Any questions just call or text me (707)291-6600 I will be available anytime you want to talk. 

Thank you!

Zachary Hejl 
zachdhejl@gmail.com

**Comment by hejlyeah** [comment]
Hey JT,

Have you had any time to look at what I am trying to do? Hope I am not being a bother, I have just made no meaningful ground on my end and really am trying to finally move forward from this one challenge I am having. Any luck?

Zachary Hejl
zachdhejl@gmail.com <mailto:zachdhejl@gmail.com>
