### ISSUE TITLE
Adding views to Cell, not working properly

### ISSUE THREAD

**Issue by Saruul-Ulzii** [patchthecode/JTAppleCalendar#495]
Hello,

I am using Version 7.0.4. I want to add events from database on cell, then tried to adding view to cellview. It shows correct cells
![simulator screen shot jul 24 2017 12 10 44 pm](https://user-images.githubusercontent.com/16433495/28507914-6388c362-7071-11e7-8f52-9d5dc96d9f9c.png)

but after scroll up and down, these dots randomly added random cells.
![simulator screen shot jul 24 2017 12 11 01 pm](https://user-images.githubusercontent.com/16433495/28507920-6a870232-7071-11e7-8eb0-bfe86616cace.png)
also added some random cells
![simulator screen shot jul 24 2017 12 11 06 pm](https://user-images.githubusercontent.com/16433495/28507929-75e5580e-7071-11e7-8e77-75f7defa35b7.png)

This is my function to adding dots:

```swift
func setColorfulDots(view: JTAppleCell?, cellState: CellState) {
        guard let validCell = view as? EventCell else {return}
        self.filteredDots = events.filter(
            {
                (json) -> Bool in return
                ((json.dictionaryValue["start_date"]?.date)!.equalToDate(dateToCompare: cellState.date) ||
                (json.dictionaryValue["end_date"]?.date)!.equalToDate(dateToCompare: cellState.date)) ||
                (cellState.date.isGreaterThanDate(dateToCompare: (json.dictionaryValue["start_date"]?.date)!) &&
                cellState.date.isLessThanDate(dateToCompare: (json.dictionaryValue["end_date"]?.date)!))
            })
        countOfCellDots = filteredDots.count
        for (index, perDot) in filteredDots.enumerated() {
            dotViewWidth = (dotWidth * countOfCellDots) + (2 * (countOfCellDots - 1))
            var X = (Int(validCell.width) - dotViewWidth) / 2
            X = X + (dotViewWidth / (countOfCellDots * 2)) + (dotViewWidth / countOfCellDots) * index
            dotView = UIView(frame: CGRect(
                x: X,
                y: Int(validCell.dayLabel.frame.origin.y + validCell.dayLabel.frame.size.height),
                width: dotWidth,
                height: dotWidth))
            dotView.layer.cornerRadius = CGFloat(dotWidth / 2)
            dotView.backgroundColor = hexStringToUIColor(hex: perDot["color"].stringValue)
            validCell.contentView.addSubview(dotView)
            validCell.selectedView.isHidden = false
        }
        filteredDots = []
    }
//Calling from cellForItemAt:
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "eventCell", for: indexPath) as! EventCell
        if cell.dayLabel != nil
        {
            cell.dayLabel.text = cellState.text
            setColorfulDots(view: cell, cellState: cellState)
        }
        return cell
    }
```

**Comment by Saruul-Ulzii** [comment]
@patchthecode, please see this.

**Comment by patchthecode** [comment]
@Saruul-Ulzii you said it shows correct cells.. what is the problem?

**Comment by Saruul-Ulzii** [comment]
@patchthecode pls see pics, correct cells are red-backgrounded, little colorful dots must be in these red-backgrounded cells, after launch 1st pic[2017.07] is correct, but after scrolling another months up and down, these little dots adding another cells, like shown in 2 picture, its mustn't, then returning month 2017.07, now many cells has colorful dots, not only correct red cells.

**Comment by Saruul-Ulzii** [comment]
`
            validCell.contentView.addSubview(dotView)
            validCell.selectedView.isHidden = false
`
1st line is adding dots, 2nd line is showing red background, if little dots added to cell, it must be has red-background, because these 2 line work sametime, there isnt any condition, but now why just adding little dots?

**Comment by patchthecode** [comment]
@Saruul-Ulzii its late here my time. So i will take a look at this in the morning.
But before I take a look at it, have you seen [this video](https://www.youtube.com/watch?v=CQNotydm58s) yet?  It shows you an example how to set up dots and events.

**Comment by patchthecode** [comment]
@Saruul-Ulzii looking at your code, this is not the way you add views to a cell.
I think [this playlist](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q) will help you.

**Comment by jokerham** [comment]
I think you should delete the view added (if any) when dequeue delegate is called, or else it will keep the view when dequeue of the cell that has the view is dequeued.

**Comment by Saruul-Ulzii** [comment]
@patchthecode i watched all tutorial videos. Red-background is like tutorial's selected view. i just want to add views, not toggle with isHidden - true/false, isHidden-false is working properly, then trying to add views, cause i don't know how many dots need to add to cell, then i can't create dot views on cell in storyboard. Its too easy to test your code, you need to add some views to cell on handleCellSelection method in tutorial.

**Comment by patchthecode** [comment]
@Saruul-Ulzii ok, can yu join me here? -> https://gitter.im/patchthecode/JTAppleCalendar

Maybe I might have misunderstood the problem.

**Comment by patchthecode** [comment]
problem resolved. DotViews were being added to the views, but was not being removed.
