### ISSUE TITLE
scrollToDate scrolls to section header

### ISSUE THREAD

**Issue by mwurm93** [patchthecode/JTAppleCalendar#496]
v7.0.4
calendarView?.scrollingMode = .none
calendarView?.scrollDirection = .vertical

The scrollToDate(Date) function scrolls to the section (month) header, not to the row of the (Date).

Thanks!!!
Mike

**Comment by patchthecode** [comment]
put this in your pod file.
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```
run a `pod update`
Let me know if you are still experiencing this.
