### ISSUE TITLE
How to scroll to the next month after showing current month after viewDidLoad(), v7.0.5

### ISSUE THREAD

**Issue by mr618show** [patchthecode/JTAppleCalendar#498]
Hi @patchthecode , 

I am stuck with an issue when scrolling to the next month after initially launching the app , it shows the first month in the range which I have specified instead of the correct next month corresponding to the current month. 

ie. the range which I have is 
```swift
 let startDate = formatter.date(from: "2000 01 01")!
 let endDate = formatter.date(from: "2100 12 31")!
```
After correctly showing the current month/year which July 2017 in the header, when I scrolled to the next month, it jumped to February 2000 instead of showing August 2017.

![issue 1](https://user-images.githubusercontent.com/11971765/28541083-839066ec-706c-11e7-8996-13f2906f12da.gif)

PS: regarding showing the current month/year, I implemented my own function and called it in viewDidLoad() 
```swift
    func setupCalendarView(){
        let date = Date()
        formatter.dateFormat = "yyyy"
        yearLabel.text = formatter.string(from: date)
        formatter.dateFormat = "MMMM"
        monthLabel.text = formatter.string(from: date)
        
    }
```
because `calendarView.scrollToDate(Date())` didn't work for me after trying to implement it from previous solutions. It would throw me the following error 

`-[UIView functionIsUnsafeSafeToRun]: unrecognized selector sent to instance 0x7f8fc5c05890
2017-07-24 12:25:37.393`

Much appreciated if I can also get some help on why scrollToDate didn't work for me.

Thanks,
Rui

**Comment by patchthecode** [comment]
@mr618show is it possible you can send me a sample app with the problem?

I just released version 7.0.5, so its possible I could have caused an error.
Can you send to patchthecode@gmail.com ?

**Comment by mr618show** [comment]
Thanks @patchthecode , I've sent you more detail in the email.

**Comment by patchthecode** [comment]
@mr618show hmm. I just checked my email.. there is nothing there. Could you try resending it?

You can also join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by mr618show** [comment]
hmm, I am not sure why, just resent it and also left a message in the im. Let me know if you have received it.

**Comment by patchthecode** [comment]
Got it. Checking it out now.

**Comment by patchthecode** [comment]
issue resolved.
Small accident in hooking up outlets.
closing this now.

**Comment by mr618show** [comment]
Thank you @patchthecode  very much!
