### ISSUE TITLE
How to change the font of the text on a date cell?

### ISSUE THREAD

**Issue by J-phantom** [patchthecode/JTAppleCalendar#5]
hello 
how can change number format in cellView ?
i want change number 1 ==>۱
thanks??

**Comment by patchthecode** [comment]
Just to confirm,
You want to change font of the number to something else?

**Comment by patchthecode** [comment]
If you want to change the font to something else, then this is easy. JTAppleCalendar does not provide text for you, it only provides you with the date. You have the power to change the font to what ever you want. Have you taken a look at the tutorial yet? It shows you how to set up the text to the cell. If you need more help let me know
