### ISSUE TITLE
update mess

### ISSUE THREAD

**Issue by akabab** [patchthecode/JTAppleCalendar#50]
Had a crash on JTAppleCalendarHorizontalFlowLayout.swift:
line 131 `let requestedColumns = Int(ceil(rect.width / itemSize.width))` because itemSize = (0, 0)

so I updated to 4.0.2, but my view layout is now totally broken, is there something more you added to configure now ? I see you changed a lot of stuff on FlowLayout, it is not stable at all.

**Comment by akabab** [comment]
Else, is there any way to fix the itemSize beeing Zero at that point ?

**Comment by patchthecode** [comment]
looking into it.

**Comment by patchthecode** [comment]
Ok. 
1. Which version did you update from?

2. When you say your layout is totally broken, i need to know what broke.  maybe a quick gif?
Because 4.0.2 has some performance changes to make it scroll very smoothly on your phone.

**Comment by akabab** [comment]
4.0.0 -> 4.0.2

I patched and fixed with `guard itemSize.width != 0 else { return nil }` because `layoutAttributesForElementsInRect` is called before `updateLayoutItemSize` so itemSize is not yet set on first call so `let requestedColumns = Int(ceil(rect.width / itemSize.width))` divided by zero makes the crash

**Comment by akabab** [comment]
But 4.0.2 looks very unstable, uncleaned, with many unused code

**Comment by patchthecode** [comment]
ok you patched 4.0.0 ? or 4.0.2?

**Comment by akabab** [comment]
4.0.0

**Comment by patchthecode** [comment]
hmm. Ok. Aright.

**Comment by patchthecode** [comment]
But
I thought i went through 4.0.2 code with a fine tooth comb.
There are no issues from my end. 
Which code is unused? ...ugh i need details. I dont know where

**Comment by akabab** [comment]
actually it is not even fixing it, sometimes the cells are not drawn.. anyway I might take a deeper look in 4.0.2

**Comment by patchthecode** [comment]
I know youre busy with your project. But any help i can get with this project will be awesome. Since im the sole coder >_<

**Comment by akabab** [comment]
Yeah I was about to propose, will be able to help in a couple of week when I'm back from holiday. I'm leaving tomorrow, and I don't get why this issue popped up from nowhere without updating the lib, it now crash instantly on loading the view..

**Comment by akabab** [comment]
add me on skype `cribier.yoann`

**Comment by patchthecode** [comment]
OK. Before you go.
you mentioned that cells are not being Drawn.
Are you registering cells with a Xib file -> 
```calendarView.registerCellViewXib(fileName: "CellView")``` ?
or 
Are you registering cells with class -> 
```calendarView.registerCellViewClass(fileName: "JTAppleCalendar_Example.CodeCellView")```

**Comment by patchthecode** [comment]
Request sent

**Comment by patchthecode** [comment]
Ok. Bug was due to iOS simulator in an inconsistent state.
Closing this issue.

**Comment by zuaaef** [comment]
If, you're back. Do an update to 4.1.0
I found the issue that was causing this issue.

**Comment by patchthecode** [comment]
If, you're back. Do an update to 4.1.0
I found the issue that was causing this issue.
