### ISSUE TITLE
Async My Calendar

### ISSUE THREAD

**Issue by j3me5** [patchthecode/JTAppleCalendar#500]
I am new to iOS programming. I want the user to tap the calendar button and have it go the the view while loading the calendar data (from a remote .ics file). DispatchQueue.main.async works on my other buttons while loading data but it seems that. When I use that for JTAppleCalendar, it seems like 'func calendar' is being called before viewDidLoad() so my DispatchQueue isn't working.

Right now when I press the calendar button, it has to wait a second or two before it goes to the calendar.

**Comment by patchthecode** [comment]
what version of the library are you using. Version `7.0.5`?

Also i'm not quite understanding the problem.
You want the calendar to start off at a particular date?
If so, then call `calendarView.scrollToDate` in your viewDidLoad function

**Comment by mayurdzk** [comment]
@j3me5  I'd be happy to help you here but I haven't been able to understand the problem completely myself either.
Just a word of caution (if this is what you're trying to achieve and/or don't know this already): Manipulation of any UI on any thread other than the main thread is dangerous.

**Comment by patchthecode** [comment]
closing this until user provides further input.
