### ISSUE TITLE
Type 'UICollectionViewFlowLayout' does not conform to protocol 'JTAppleCalendarLayoutProtocol'

### ISSUE THREAD

**Issue by mayurdzk** [patchthecode/JTAppleCalendar#501]
Hey Jay,

JTAppleCalendar is running into a problem because UICollectionViewFlowLayout doesn't conform to JTAppleCalendarLayoutProtocol due to (as Xcode says) a missing `targetContentOffsetForProposedContentOffset` method. Here's a screenshot detailing the problem:
<img width="1280" alt="screen shot 2017-07-26 at 10 55 58 am" src="https://user-images.githubusercontent.com/10453316/28605861-6fd97e50-71f1-11e7-8a76-f47f1fe4f9f3.png">

Do note that I am running Xcode 9 Beta 4 with the compiler version setting set to Swift 3.2.
Pod version: 7.0.5 (latest at the time, I just ran a pod update JTAppleCalendar)

Also note that I am running a post install script in my podfile. Here's the code:
` post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = ‘4.0’
        end
    end
end `

Thank you in advance for your help.

**Comment by mayurdzk** [comment]
I believe I've solved the issue since `targetContentOffsetForProposedContentOffset(_ proposedContentOffset: CGPoint) -> CGPoint` has been renamed to `func targetContentOffset(forProposedContentOffset proposedContentOffset: CGPoint) -> CGPoint` in UICollectionViewFlowLayout.

Updating the method in your protocol fixes this issue. I'd happy to put in a PR in case you'd like.
Thank you anyway.

**Comment by patchthecode** [comment]
that would be awesome man. I cant do so right now.

**Comment by mayurdzk** [comment]
No problem, I'd be happy to help out. Is there a specific branch you would like me to submit my PR into?
