### ISSUE TITLE
Not sure of best way to handle this

### ISSUE THREAD

**Issue by Methos456** [patchthecode/JTAppleCalendar#503]
Trying to figure out best way to remove space between cells of a selected range.  My cellSize is 40 and my selectedView is 40,40.   minimumLineSpacing is 0 as is minimumInteritemSpacing.

Is it just a matter of adjusting cellSize and selectedView size or do you do custom drawing in the cell.
I am using version 7.0 (see pict below).  Thanks for a great calendar framework!!
 
![img_1599](https://user-images.githubusercontent.com/30130464/28637746-97ae9450-7210-11e7-863c-5f5a2a0f24ba.PNG)

**Comment by patchthecode** [comment]
seems like many devs are making the AirBnb style these days :)

You say the size of your cell is 40x40?
Can you tell me what is the width of your calendar? i need to know is it xxx.xxxxxxx.... ?

**Comment by Methos456** [comment]
I guess it is good that the calendar is recognizable.  I used AirBnb as a guide to practice on ...
If you are referring to the calendar's frame width it is 375.0   I set the cellSize to 40, but to me it looks like the height may be 40, but the width is wider.  When I put a borderLayer of 1 around the cell you can see space between the selectedView and the width of the cell, but the height is fully used.

**Comment by Methos456** [comment]
Thanks for your help on this..  Your solution was way too easy!!  Thanks!
