### ISSUE TITLE
Borders around the days?

### ISSUE THREAD

**Issue by tkirby** [patchthecode/JTAppleCalendar#504]
Is there some example of creating a calendar with 1px borders around the days. I've tried bordering the cells and that results in 2pix intercell borders and 1px outer borders. Tried cell insets with the same result.

I found this question:

https://github.com/patchthecode/JTAppleCalendar/issues/432

which seems like it would work but the methods don't seem to be there  anymore or are inaccessable. I could go in and change the protection level of the internal collection  view but that seems like a pretty bad way to handle something as basic as making the calendar have gridlines. I'm sure I must have missed something?

**Comment by patchthecode** [comment]
which version of the calendar are you using?

**Comment by patchthecode** [comment]
chat here for speed -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by tkirby** [comment]
I didn't specify a version in the podfile so I guess it was pulling old version.

Installing JTAppleCalendar 7.0.5 (was 6.1.6)

fixed it.

**Comment by patchthecode** [comment]
awesome.
