### ISSUE TITLE
super.layoutSubviews() crash

### ISSUE THREAD

**Issue by Codeido** [patchthecode/JTAppleCalendar#505]
- Version library: 7.0.5

Hi!
First of all, thanks for this amazing library. 
I have a crash here:
<img width="1157" alt="schermata 2017-07-28 alle 15 08 36" src="https://user-images.githubusercontent.com/495617/28718552-e9ba8852-73a6-11e7-9298-60dc667a0f2c.png">

The calendarView is in sync with a tableview and when the tableview scrolls very fast, this crash happen!

```
self.compactableCalendar?.calendarView.selectDates(date)
self.compactableCalendar?.calendarView.scrollToDate(date)
```
If i remove this lines of code, the crash disappear.
What do you think may be?

**Comment by patchthecode** [comment]
Can you give me some more information?

You said that the calendar is in sync with a tableView.
I do not fully understand what this means. Screen shots can also help with your description.
I need enough information to recreate the crash on my end.

**Comment by Codeido** [comment]
Is really simple. I have a calendar table view (the section that represents the day, and every cell represent an appointment. If there are no appointments, there is a placeholder cell, then for every day there is always almost one cell).

In the table view method
```
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) 
```
i put 
```
self.compactableCalendar?.calendarView.selectDates(date)
self.compactableCalendar?.calendarView.scrollToDate(date)
```
that allow the calendarView to follow the tableview scroll.
Consider that there is an infinite scroll, on table view and on calendar view, then, when the end of the month is showed (and the end of the month is not on my datasource array), I update the datasource array and reload the calendar view.

Apparently the problem is the selectDates() method. Without seems to be working properly.

**Comment by Codeido** [comment]
I found this https://github.com/patchthecode/JTAppleCalendar/issues/444 but I don't know if it is correlated.

**Comment by patchthecode** [comment]
just noting a couple things. Correct me if i'm wrong.

1. You achieved infinited calendar scrolling by reloading the calendar once it gets to the end of its data. Is this reloading also happening inside the tableView's `willDisplay cell` function?
2. Does the reload happen before or after the following?
   ```swift
   self.compactableCalendar?.calendarView.selectDates(date)
   self.compactableCalendar?.calendarView.scrollToDate(date)
   ```
3. Does the crash happen when a calendar reload is happening? in other words, does the crah only happen once the calendar gets to the end of its data source, and is beginning to get more data?
4. If possible, can you provide a stripped down version of your bug? This is the easiest way for me to solve the problem the fastest.

**Comment by patchthecode** [comment]
also, this link = faster chat times -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
https://files.gitter.im/patchthecode/JTAppleCalendar/P6yI/calendar-view.gif

**Comment by patchthecode** [comment]
is it possible that you can create a sample project with this bug?
I tried and could not recreate it.
[couldNotReproduceBug.zip](https://github.com/patchthecode/JTAppleCalendar/files/1187844/couldNotReproduceBug.zip)

**Comment by patchthecode** [comment]
is this still an issue?

**Comment by Codeido** [comment]
For the moment, resolved using calendarView.scrollToDate(selectedDate, animateScroll: false)
