### ISSUE TITLE
events not displaying in table view

### ISSUE THREAD

**Issue by hejlyeah** [patchthecode/JTAppleCalendar#507]
Jay,

I am confident this workspace should be working but it is not. I have followed all of your advice and come up with this. 

Why is it not working?

[JesusSaves5 copy 4.zip](https://github.com/patchthecode/JTAppleCalendar/files/1185269/JesusSaves5.copy.4.zip)

**Comment by hejlyeah** [comment]
I thought I had it but now I know I do not. Ill send you a PayPal donation if you can help me fix this :)

**Comment by hejlyeah** [comment]
Any help? Please?

**Comment by patchthecode** [comment]
OK, forgot about this.
Will take a look tomorrow afternoon.

**Comment by hejlyeah** [comment]
I LOVE YOU BRO THANK YOU

**Comment by hejlyeah** [comment]
Anything? Sorry I don't mean to pester.

Zach

**Comment by patchthecode** [comment]
Got tied up in work over the weekend man. I'll have to take a look in a bit.
See, i can commit to helping as far as i can, but sometimes i get really tied up.
I'll take a quick look now.

**Comment by hejlyeah** [comment]
Hey Jt,

Any time?😬
Sorry man.. just really lost.

Thanks

Zach

**Comment by patchthecode** [comment]
join the chat -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
issue resolved.
closing this.
