### ISSUE TITLE
Calendar did not load properly

### ISSUE THREAD

**Issue by hanishassim** [patchthecode/JTAppleCalendar#51]
Hi, I can't figure out why the calendar displays this. I followed the tutorial directly but I got this result: 
![simulator screen shot 22 jun 2016 7 05 34 am](https://cloud.githubusercontent.com/assets/4571502/16249360/c9a12f8a-3847-11e6-856d-f2833e8daf73.png)
(The black dot on the side scrolls when I swipe the view)
I have applied the Cell XIB and autolayout constraints and all.

I don't know what I did wrong here.

**Comment by patchthecode** [comment]
Ok. First are you using version 4.0.2?

Then can you do this for me. Reset your simulator. Then after resetting (with you app not running) turn the simulator to landscape mode, then back to portrait mode. 

Now load the app and tell me if your issue was resolved.

**Comment by patchthecode** [comment]
Update 4.0.3 now released.

**Comment by hanishassim** [comment]
Yes, thanks for the swift response!
My problem is resolved, I have updated to 4.0.3
![simulator screen shot 22 jun 2016 10 30 32 pm](https://cloud.githubusercontent.com/assets/4571502/16270439/f4ee608c-38c8-11e6-9a23-1d9d5eee2ae8.png)

**Comment by patchthecode** [comment]
cool. cheers. 👍

**Comment by patchthecode** [comment]
Btw, it looks like youre doing a vertical calendar view. In that case it might look better if you have Headers implemented. But your choice. I'm no design expert so take what i say with a grain of salt.

**Comment by hanishassim** [comment]
I'll try that, thanks!
