### ISSUE TITLE
how to set default cell on load Calendar?

### ISSUE THREAD

**Issue by mojtabadj** [patchthecode/JTAppleCalendar#510]
I use latest version of calendar and version is 7.0.4
I want select default cell with code on load calendar
how to can it?
Thanks

**Comment by patchthecode** [comment]
Please take a look at the final video in this list -> [HERE](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)

It will help you a lot.
Closing this issue.
Let me know if you are still stuck.

**Comment by patchthecode** [comment]
by, the way.Latest version is 7.0.6
