### ISSUE TITLE
Crashes on changing and scrolling the calendar from/in weekview/monthview

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#511]
1. Using version: **7.0.6**
2. Using the latest version: **Yes**
3. This should be a **fresh** issue.
4. Sample App? You can download it from [**here**](https://github.com/hemangshah/DemoJTAppleCalendar-Issue-511).
5. **Description**:

> In my app, I have the functionality of changing the calendar view from month view to week view and vice versa. While being in week view or in month view, a user can also scrolls (changes) to the specific months (next or previous).

**This leads to the crash.** 

**I am not seeing any crash logs except below. It just stopped to the `AppDelegate` file.**

**Here's the crash log:**

```
    libobjc.A.dylib`objc_retain:
    0x10a7e5ce0 <+0>:  testq  %rdi, %rdi
    0x10a7e5ce3 <+3>:  je     0x10a7e5cf5               ; <+21>
    0x10a7e5ce5 <+5>:  js     0x10a7e5cf7               ; <+23>
    0x10a7e5ce7 <+7>:  movq   (%rdi), %rax
->  0x10a7e5cea <+10>: testb  $0x2, 0x20(%rax)
    0x10a7e5cee <+14>: je     0x10a7e5cfb               ; <+27>
    0x10a7e5cf0 <+16>: jmp    0x10a7e67b4               ; objc_object::sidetable_retain()
    0x10a7e5cf5 <+21>: xorl   %edi, %edi
    0x10a7e5cf7 <+23>: movq   %rdi, %rax
    0x10a7e5cfa <+26>: retq   
    0x10a7e5cfb <+27>: leaq   0x55c59e(%rip), %rax      ; SEL_retain
    0x10a7e5d02 <+34>: movq   (%rax), %rsi
    0x10a7e5d05 <+37>: jmp    0x10a7e8ac0               ; objc_msgSend

```

**Comment by patchthecode** [comment]
I tried for quite some time, and could not reproduce your crash.
I even did memory leaks profiling, and there was nothing.
Every thing looked normal.

Here is something crazy -> you just updated to 7.0.6 right? It's possible the crash is related to XCode being silly after the pod update. Hence the reason there are no logs.


1. Do a project clean - CMD + SHIFT + K
2. Delete your generated `Build` for that project 
3. delete your generate `Derived Data` folder for that project
4. re-run your project

If this does not work, I will arrange a time to do a share screen with you to debug it.

**Comment by hemangshah** [comment]
@patchthecode, thank you so much for investigation and as we found that, the issue is possible because of the older version of beta Xcode which I was using. I have tried the sample with the latest beta Xcode and it doesn't crash. So possibly, the issue is in Xcode. I will post back again if I will found the same issue till time closing this.

**Comment by patchthecode** [comment]
awesome. have a good one.
