### ISSUE TITLE
How best to implement hidePrepost() function?

### ISSUE THREAD

**Issue by seanrice** [patchthecode/JTAppleCalendar#512]
JTAC v7.0.6 - iOS 10

JTAppleCalendar works fine here, loads up and scrolls perfectly, but ... was unable to hide the in-out dates and wish to. Then i reviewed Jay's new FAQ guide! Sweet. 
Added --> configureCell(view: cell, cellState: cellState) function ... and called in cellForItemAt method.
Added --> handleCellVisibility(cell: CustomCell, cellState: CellState) function ... to class.
presto!

**Comment by patchthecode** [comment]
haha. i never had an issue opened with a compliment.
Thanks man :)
So there are no problems right?

**Comment by patchthecode** [comment]
closing issue. As there seems to be no problem here

**Comment by seanrice** [comment]
Hey sir! No problems here. i wanted to delete issue, couldn’t, so i rephrased…but forgot to close issue! =) Thanks!! Hope all is well.
Sean

**Comment by patchthecode** [comment]
All is well man.
Have a good one 🍻
