### ISSUE TITLE
How I can increase the height of calendar cell

### ISSUE THREAD

**Issue by vikrant88** [patchthecode/JTAppleCalendar#513]
Hello everyone, I am working on JTAppleCalendar using with swift3.0. Now I want to increase the cellHeight only. I am not able to get any way to increase it. So please guide me how I can do it.

Thanks

**Comment by patchthecode** [comment]
cellSize is modified by 2 things.

1. the height of the calendarView if you have a horizontal scrolling calendar.
2. the width of the calendarView if you have a vertical scrolling calendar.
3. the `cellSize` property on the `calendarView`

Let me know if you are still stuck.
Keep in mind these [video tutorials](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q) help
