### ISSUE TITLE
Programmatic way to load next/previous month

### ISSUE THREAD

**Issue by fweathers** [patchthecode/JTAppleCalendar#516]
I noticed that issue #47 (https://github.com/patchthecode/JTAppleCalendar/issues/47) discussed this issue but when I tried to utilize it, it was not found. Is this still available?

**Comment by patchthecode** [comment]
sure.
```swift
calendarView.scrollToSegment(.next)
calendarView.scrollToSegment(.previous)
calendarView.scrollToSegment(.start)
calendarView.scrollToSegment(.end)
```

There is one thing i forgot to mention.
Every function that a developer is able to do on this calendar is located in the file `UserInteractionFunctions.swift`

It may even real many things you never knew :)

**Comment by fweathers** [comment]
great Thanks!
