### ISSUE TITLE
Taking too much time to come color dots on dates

### ISSUE THREAD

**Issue by iOSUser110** [patchthecode/JTAppleCalendar#518]
It is taking too much time to drawing color dots on cell 
am using calenderView.reloadData() on success of getEvents webservice

I tried to use caledneView.reloadDates(dateArray)
but not working 

And the color dots set in handleCellTextColor method

**Comment by patchthecode** [comment]
Is it possible that it is taking a while to load the dates from your server?

**Comment by patchthecode** [comment]
closing until further user input
