### ISSUE TITLE
layoutIfNeeded invalidates the layout and always scroll to the January first

### ISSUE THREAD

**Issue by win13676** [patchthecode/JTAppleCalendar#519]
I'm using latest version 7.0.6, on ios 10.3, xcode 8.3.3, swift 3.1 
every time invalidateLayout gets called the calendar will scroll to January first
calling layoutIfNeeded usually will call invalidateLayout 

The case I have is I have 2 JT Calendar.
I animate one of the calendar out and hide it.
in the animation block I need to call layoutIfNeeded to animate the constraint changes
as the result the second calendar invalidateLayout got called to handle animation and it scrolls to January first
 
Another case is in your example app on layout demonstration
click right couple of times to go to next few months
click header on, invalidateLayout got called and calendar jump to january

**Comment by patchthecode** [comment]
so do you call `calendarView.layoutIfNeeded`?

**Comment by win13676** [comment]
I called on their parents.
In the parent class I change the calendar constraint and call self.layoutIfNeeded() in the animation block

**Comment by win13676** [comment]
Is it that I should to call scrollToDate every time before I do layout if needed?

**Comment by patchthecode** [comment]
ok this case, it is expected. If you do something that changes the calendar's layout, it will reload the calendar's layout causing it to reset.

you'd need to save the visible date that the calendar is on, and simply scroll back to it.
If you already have the `dateYouWannaScrollBackTo` then just scroll to that date.

or you can even do something like `calendarView.reloadData(withAnchor: dateYouWannaScrollBackTo)`

**Comment by patchthecode** [comment]
Let me know if this resolved your issue?

**Comment by win13676** [comment]
If that's the case then that works, thank you
