### ISSUE TITLE
I am using JTAppleCalender version 7.0

### ISSUE THREAD

**Issue by JailanElMosalami** [patchthecode/JTAppleCalendar#521]
I want to make all date only on Friday and Saturday for all the months with a blue background while the rest with another color without selection.
Also I want to make entries in a specific date when I click on it. Can this be done using JTApple Calendar?

**Comment by patchthecode** [comment]
What is the problem?

**Comment by patchthecode** [comment]
closing issue until further user input

**Comment by JailanElMosalami** [comment]
I have already made an input an hour ago

**Comment by patchthecode** [comment]
I am sorry. I missed it. reading it now, and re-opening

**Comment by patchthecode** [comment]
can you join me here? -> https://gitter.im/patchthecode/JTAppleCalendar
Its faster.

**Comment by patchthecode** [comment]
issue resolved.
