### ISSUE TITLE
Adjusting calendarView frame.height in tableView?

### ISSUE THREAD

**Issue by seanrice** [patchthecode/JTAppleCalendar#527]
Hi Patch & Co.
Quick heightAdjustment question. This code was working fine in Simulators and devices ... UNTIL (cough!) ... we moved the view containing JTAppleCalendar and other sub-views to a TableView for use as Header. Auto-layout barely complained. For design asthetics, we chose to make NavBar & TabBar at bottom opaque. Oh, TableView has 0 cells. It's there for subclasses use.

BUT... the algorithm we used to adjust CalendarView height is generating (high) numbers that instead of scaling down CalendarView to showing only 1 Row ... the calculated heightAdjustment is so large, it hides the entire JTAppleCalendarView. Worse, the results we get in Simulator do NOT match results on actual devices when it comes to the Calendar. I'd like to keep code generic and adjust height based on screensize / number of rows / etc as before. Any suggestions?

    private func resizeToWeekView() {

        heightAdjustment = (CGFloat(numberOfRows-1) * (calendarView.frame.height/CGFloat(numberOfRows)))

        calendarView.frame = CGRect(
            x: calendarView.frame.origin.x,
            y: calendarView.frame.origin.y,
            width: calendarView.frame.width,
            height: calendarView.frame.height - heightAdjustment
        )
        numberOfRows = 1
        calendarView.reloadData()

     }

**Comment by seanrice** [comment]
note: this may be an auto-layout issue. i'll let folks know.

**Comment by seanrice** [comment]
for what it's worth, this adjustment seems to work on my dev device, but Simulators will NOT accurately reflect UI of dev device. 

            let calendarHeightAdjustment = (CGFloat(numberOfRows-4) * (calendarView.frame.height/CGFloat(numberOfRows-1))) + CGFloat(10.8)

**Comment by patchthecode** [comment]
alright. I can look into this.
just to clarify, it works on simulator but fails on device ?

**Comment by patchthecode** [comment]
the best thing would be if you can provide a sample app with the bug? that would be most awesome (if you can).

**Comment by seanrice** [comment]
For clarification... with calendarView in a View in header of Table ... the original heightAdjustment code fails in both Simulator and Device. Adjusted to numOfRuns-2 works in Simulator. Adjusted to -4 and -1 as shown, works on Devices. Wish i could share app, too many obvious concerns. Might be able to do a screen share using Messages on Mac?

**Comment by patchthecode** [comment]
@seanrice sure i am.
can you join me here? https://gitter.im/patchthecode/JTAppleCalendar
chat in here is too slow

**Comment by patchthecode** [comment]
Thanks for the clarification by chat. 
Since this one Turned out to be an autolayout issue, i will close this one.
We'll open a new one for the scroll-to-first-date error when app comes from background.
Cheers 🍻
