### ISSUE TITLE
how to give array of eventDates to calendar

### ISSUE THREAD

**Issue by janardhanmupparaju** [patchthecode/JTAppleCalendar#529]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.6
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
4. Don't just ask a question. Provide enough information so I will be able to recreate the problem you are facing. 
   It would be even better if you provided an example app if possible.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
Have a look at the tutorials [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q).
Take a look at the last video in the tutorial.
