### ISSUE TITLE
UISemanticContentAttribute error 

### ISSUE THREAD

**Issue by Maryom** [patchthecode/JTAppleCalendar#531]
Hi,

Thanks for your repo.

I'm using JTAppleCalendar version 7.0.6, and my app development target is 9.0 as you can see in the image below.

I got the following error:

`'UISemanticContentAttribute' is only available on iOS 9.0 or newer`

Any help ?

<img width="432" alt="screen shot 2017-08-14 at 10 07 07 am" src="https://user-images.githubusercontent.com/3218401/29261507-953417aa-80d8-11e7-8513-8671125f9c37.png">
<img width="653" alt="screen shot 2017-08-14 at 10 04 40 am" src="https://user-images.githubusercontent.com/3218401/29261516-9c1f7348-80d8-11e7-908b-ccfc16bdfe14.png">

**Comment by patchthecode** [comment]
I know your project is target 9.0, but
for what version do you have the **pods**?

**Comment by Maryom** [comment]
1.3.1

**Comment by patchthecode** [comment]
@Maryom can you join me here?
I am unclear on your question -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Clarification made.
Setting the version to at least 9.0 fixed the issue.
