### ISSUE TITLE
willDisplayCell delegate is not found in 7.0.6

### ISSUE THREAD

**Issue by jeewanct** [patchthecode/JTAppleCalendar#532]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.6
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
4. Don't just ask a question. Provide enough information so I will be able to recreate the problem you are facing. 
   It would be even better if you provided an example app if possible.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
in version 7.0.6, JTAppleCalendar is now a UICollectionView.
This was done to make it easier for everybody. If you know how to use a UICollectionView, then you also know how to use this library.

`willDisplayCell` has been replaced with `cellForItemAt` function.

If you have any other questions, ask here. Will respond.

**Comment by patchthecode** [comment]
closing this issue. But if you need any more help on this, then let me know. I'll respond.

**Comment by patchthecode** [comment]
The tutorials should help and let you have an idea of what has changed --> [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)
