### ISSUE TITLE
Arabic localization.

### ISSUE THREAD

**Issue by Samback** [patchthecode/JTAppleCalendar#533]
Arabic localization.
Is it support Arabic localization. If yes, where can I find documentation how to switch on it. 

Regards,
Max

**Comment by patchthecode** [comment]
This library supports all languages.
in the `cellForItemAtDate` delegate function, this is where you setup your cell.

Since you have the date, all you need is a dateFormatter with the locale set to an `Arabic` locale. Then your language will be the locale that you set.

**Comment by patchthecode** [comment]
closing this issue. Let me know if youre still stuck.

**Comment by rs658726** [comment]
Hi @patchthecode , 

I'm not clear on how to get the calendar to display in Arabic. If I set the locale to Arabic in the code, it will be applied to all the other supported languages (English, French, Spanish etc..), which is not what I want. Shouldn't the language be set automatically based on the settings of the phone? 

Thanks,

**Comment by patchthecode** [comment]
I am not understanding what you mean by this

> If I set the locale to Arabic in the code, it will be applied to all the other supported languages 

Arabic will be applied to other languages?

**Comment by rs658726** [comment]
What I'm trying to say is that my app supports multiple languages so I cannot set the locale to one single language. Does this make sense?

**Comment by patchthecode** [comment]
ok.
let me clarify so that i understand.

So you just set your app's locale to Arabic 

** What is expected:** What do you expect the calendar's language to be in?
**What actually happens:** What language do you see the calendar actually presented in?

**Comment by rs658726** [comment]
If I set the language of my phone to Arabic, everything in my app turns to Arabic but the calendar cells. (they also read from left to right instead of right to left which is how Arabic is read)
I would expect the calendar cells to also display in Arabic and from right to left just like everything else in the app.

**Comment by patchthecode** [comment]
hmmm.. I thought I already had an update doing this already.
What version of the calendar are you using?

**Comment by rs658726** [comment]
I'm using version 7.1.7.

**Comment by patchthecode** [comment]
Ok i am unable to test this right now.  Will take a look in some days.

If you need this sooner, then maybe  You can help me debug.  If you have no clue how to debug then ignore the rest of this message.

Do you use cocoapods?  If yes.

1. Here is where I do the check to make sure that the calendar is right-to-left or left-to-right
Look for the **JTAppleClanedar.swift** file and scroll to the following section of code.

```swift
extension JTAppleCalendarView {
    /// A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.
    open override var semanticContentAttribute: UISemanticContentAttribute {
        didSet {
            var superviewIsRTL =  false
            if let validSuperView = superview?.effectiveUserInterfaceLayoutDirection { superviewIsRTL = validSuperView == .rightToLeft && semanticContentAttribute == .unspecified }
            transform.a = semanticContentAttribute == .forceRightToLeft || superviewIsRTL ? -1: 1
        }
    }
}
```
By using breakpoints etc, can you let me know where why it is stuck on Left-to-right

2. For changing the language, go to the following function in your code
```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell  { }
```

Create an DateFormatter and configure it to the language of your system.
For example 
```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell  { 

        let f = DateFormatter()   // Never declare the formatter inside here. This is a heavy class which will cause your cells to lag
        let c = Calendar(identifier: .islamic)
        
        f.calendar = Calendar(identifier: .)
//        f.locale = ??
//        f.calendar = ?
        
        cell.text = f.string(from: myDate)

}
```

**Comment by rs658726** [comment]
Thanks! Will take a look.

**Comment by patchthecode** [comment]
Forgot one last thing, in the configureCalendar function, the `ConfigurationParameters` object, please provide a `Calendar` object to that value.

**Comment by rs658726** [comment]
I was able to change the language. I used number formatter instead. 

```
        numberFormatter.locale = Locale.current
        cell.calendarCellLabel.text = numberFormatter.string(from: NSNumber(value: Int.parse(from: cellState.text)!))
```

**Comment by rs658726** [comment]
I was able to change the swiping direction of the calendar. Unfortunately, it's still laying out the date left to right. What I did was to check the way the view is laid out. If it's laid out from right to left, I force the calendar's semantic attribute to .forceRightToLeft:

```
        if (UIView.userInterfaceLayoutDirection(for: self.view.semanticContentAttribute) == .rightToLeft) {
            calendar.semanticContentAttribute = .forceRightToLeft
        }
```

**Comment by patchthecode** [comment]
Glad you found a solution.
but do you have any idea where i can put that line of code so that it runs automatically?
i'm not too sure where to place it in the library so that it works automatically.

**Comment by rs658726** [comment]
I will have to look into the code tbh. I haven't had a lot of time to do that. I came across the solution a little bit on accident. If I figure it out, I will for sure let you know.
Considering that Apple recently launched the app store in Arabic, I'm sure this feature will be more sought after by developper in the future.

**Comment by patchthecode** [comment]
understood. I'll take a look when i get the chance.

**Comment by rs658726** [comment]
I got it to work. Here is the fix:

First, I check if the interface is laid out from right to left. If that's the case, then I lay out my collectionView from right to left:
```
if (UIView.userInterfaceLayoutDirection(for: self.view.semanticContentAttribute) == .rightToLeft) {
            calendar.semanticContentAttribute = .forceRightToLeft
        }
```

Then in JTAppleCalendarLayout, the following will layout dates from right to left if the calendar is laid out from right to left:
   ```
 override var flipsHorizontallyInOppositeLayoutDirection: Bool {
        return true
    }
```

And that's it. Now your calendar supports right to left layout.

**Comment by patchthecode** [comment]
It was this simple huh.
Thanks so much for looking into this.
It has now been implemented on master branch.

Will close this issue
