### ISSUE TITLE
Is it not support iOS8 any more?

### ISSUE THREAD

**Issue by codwam** [patchthecode/JTAppleCalendar#535]
I import `JTAppleCalendar` using Cocoapods but the version is 6.16 which is different of current version (7.0.6).
How could I found the 6xx version document？

**Comment by patchthecode** [comment]
Do you want to use version 6? Or do you wan to use version 7?

Version 7 no longer supports iOS8.
But if you want version 7 to support iOS8, all you have to make is some very small changes.

**Comment by codwam** [comment]
Could you explain it in detail, now my project's minimum version is 8

**Comment by patchthecode** [comment]
OK I wil explain this to you over the weekend.

**Comment by patchthecode** [comment]
I explained it here-> https://github.com/patchthecode/JTAppleCalendar/issues/434

let me know if this helped.

**Comment by patchthecode** [comment]
ios8 will now be supported again.
