### ISSUE TITLE
Customize Range Selection

### ISSUE THREAD

**Issue by dovanvu1792** [patchthecode/JTAppleCalendar#541]
Hello,
I used newest JTAppleCalendar version, I now, i need to custom calendar like this link
https://cloud.githubusercontent.com/assets/4571502/16706761/ff11073e-45ea-11e6-8d1a-79fc0c15df90.gif
. Anybody give me some suggestions to do this.

**Comment by patchthecode** [comment]
Hi, can you look at the documentation for version 6 and let me know if it helps you?
--> https://patchthecode.github.io/RangeSelection/

Some variable names have changed from version 6 to version 7, but understanding it should be the same. Let me know if this helps

**Comment by dovanvu1792** [comment]
Hi @patchthecode 
Thank for your support. It is done. 
Special thank to topic https://github.com/patchthecode/JTAppleCalendar/issues/538
