### ISSUE TITLE
Scrolling to new section and clicking quickly scrolls you back to the current section.

### ISSUE THREAD

**Issue by Dansong00** [patchthecode/JTAppleCalendar#542]
hey @patchthecode so i noticed a new bug that might be related to some updates you made in the current master branch. when you're in a section and you scroll and quickly click a date in the new section it scrolls you back to current section and does not select the cell. Attached is a gif of what i'm talking about. 

https://cl.ly/2h1y293f2A3b

My calendar configuration is as follows.

```
        let parameters = ConfigurationParameters(
            startDate: startDate,
            endDate: endDate,
            generateInDates: .forFirstMonthOnly,
            generateOutDates: .off,
            firstDayOfWeek: .sunday,
            hasStrictBoundaries: false
        )

        return parameters
```

**Comment by patchthecode** [comment]
Yes, this is a scroll bug. 
Introduced some time ago.
No one created an issue for it, so i forgot to fix it. Looking into it now.

**Comment by Dansong00** [comment]
Any update @patchthecode

**Comment by patchthecode** [comment]
@Dansong00 got really tied up last week. No worries. I havent forgotton about it. i'll give it a good look again this friday.

**Comment by ahmed-sal** [comment]
@patchthecode , @Dansong00 
If you look at this issue #556 , it could be relevant .

**Comment by patchthecode** [comment]
@ahmed-sal thanks.
I think i found the issue. Fixing it on master branch now.

**Comment by Dansong00** [comment]
Thanks patch i'll keep you updated!
