### ISSUE TITLE
Content offset changes when a date is tapped

### ISSUE THREAD

**Issue by amrit42087** [patchthecode/JTAppleCalendar#543]
I am using 'JTAppleCalendar', '~> 6.0.0-beta.1'. When I tap on a date and vaigate to some other view and then came back to the calendar view. I see that the content offset of the calendar is changed a bit. The calendar scrolls down a bit. I am adding a video for the same. I will be great full 
if any one could resolve this issue or let me know the cause for it.
[bug.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/1254225/bug.mov.zip)

**Comment by patchthecode** [comment]
6.0.0 beta 1..
hmm.. the latest version is 7.0.6 
Is there any reason you are using such an old version?

**Comment by amrit42087** [comment]
Yes I had to use this older version due to some reason. I forgot why I had to stick to this version. But I would appreciate if you could figure out the issue.

**Comment by patchthecode** [comment]
After looking at the movie again, it looks like the it should have snapped to the header, and not allow you to slowly drag it in such a way that the header is hidden.

**Comment by patchthecode** [comment]
Have you found a solution to this?
let me know.

**Comment by amrit42087** [comment]
I was able to resolve the issue by updating the library to 7.0.6. But I discovered a new issue. I was not able to give different monthsizes(header height). I wanted the first header to be a bit taller than the others. But the height is same for all cells. Can you let me know the cause for this?

     func calendar(_ calendar: JTAppleCalendarView, sectionHeaderSizeFor range: (start: Date, end: Date), belongingTo month: Int) -> CGSize {
            if !firstCellLoaded {
                firstCellLoaded = true
                return CGSize(width: 50, height: 90)
            }else {
                return CGSize(width: 50, height: 50)
            }
        
        }

**Comment by patchthecode** [comment]
ok open a new issue so that i dont forget it :)
but, let me starting looking into it.

**Comment by amrit42087** [comment]
Sure, Thanks
