### ISSUE TITLE
Strange issue when trying to scroll and select next day, only happening the last week of October

### ISSUE THREAD

**Issue by kboyeldieu** [patchthecode/JTAppleCalendar#544]
Hello,

I have a one row calendar and a button to scroll to the next day and select it. It is working fine, except when I use this button to move to the last week of October (for any year). The method I am calling is the following : 

```
@IBAction func scrollAndSelectNextDay(_ sender: UIButton) {
   let tomorrowDate = Date(timeInterval: 24 * 60 * 60, since: calendarView.selectedDates.first!)
   calendarView.scrollToDate(tomorrowDate)
   calendarView.selectDates([tomorrowDate])
   calendarView.reloadData()
}
```

I join you a gif so that you can see better what my problem is.
![issue](https://user-images.githubusercontent.com/30385311/29749246-8197283c-8b27-11e7-8964-83118fbed787.gif)

Thank you for your help!

**Comment by kboyeldieu** [comment]
Solved it using this line of code instead
`let tomorrowDate = Calendar.current.date(byAdding:.day, value: 1, to: calendarView.selectedDates.first!)`

**Comment by patchthecode** [comment]
cool.
