### ISSUE TITLE
How to adjust the height of calendar view when scroll month to month

### ISSUE THREAD

**Issue by ycheng82** [patchthecode/JTAppleCalendar#545]
I am using the latest build of JTAppleCalendar. For my calendar view, I want the cell height to be fixed. This means the height of calendar view is varied from month to month based on how many weeks that particular month has. How can I adjust the height of calendar view when scroll month to month? What I am currently doing now is:
    I created a NSLayoutConstraint for the height of my calendarView in xib.
    And I added the following codes:
```swift
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        let date = calendarView.visibleDates().monthDates.first?.date
        let status = calendarView.cellStatus(for: date!)!
        let monthRowCount = status.dateSection().rowCount
        if height.constant != CGFloat(monthRowCount * 52){
            height.constant = CGFloat(monthRowCount * 52)
        }
```
But this always scroll the calendar to the first month when this height constraint is updated. Can you please let me know the correct way to update the height of calendar view? Thanks.

**Comment by patchthecode** [comment]
```swift
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
     let date = calendarView.visibleDates().monthDates.first?.date
     let status = calendarView.cellStatus(for: date!)!
     let monthRowCount = status.dateSection().rowCount
     if height.constant != CGFloat(monthRowCount * 52){
         height.constant = CGFloat(monthRowCount * 52)
     }
     calendarView.reloadData(withanchor: date)
}
```

**Comment by ycheng82** [comment]
But when that date is the outdate of previous month, calendarView.reloadData(withanchor: date) will scroll to the previous month. How to handle this situation? Thanks.

**Comment by ycheng82** [comment]
Never mind. I resolved this issue by using:
if height?.constant != CGFloat(monthRowCount * 52){
            height?.constant = CGFloat(monthRowCount * 52)
            calendarView.reloadData(withanchor: calendarView.visibleDates().indates.count > 0 ? calendarView.visibleDates().monthDates.last?.date: date)
        }

**Comment by patchthecode** [comment]
Awesome. Closing this issue now.
