### ISSUE TITLE
Unexpected scrolling only on the Plus model. 

### ISSUE THREAD

**Issue by myurieff** [patchthecode/JTAppleCalendar#549]
Hello there. 
Impressive project!

Sorry I cannot post an example, as the project is a company one, but I'll try to explain the issue as good as I can.

I am using the 7.0.6 version and have a screen displaying the calendar (which is a subview of collectionView). When the collectionView gets scrolled up until a certain point (to the point where only the last week of the calendar is visible) the Calendar gets anchored and scrolled to 5 weeks ago (so that the current week only appears). Check the screenshots of both states below: 

Expanded Calendar: http://imgur.com/a/OBqan
Collapsed Calendar: http://imgur.com/a/O3ln5

This is achieved by turning on & off two constraints - top == collectionView.top and bottom == navigationBar.bottom + calendarHeight. 

So far so good. Everything is working flawlessly on the 4" and 4.7" models. 
But on the Plus model the calendar gets scrolled one more time, about 15pts after it gets anchored. The calendar gets scrolled to contentOffset of (0.0, 0.0). It is like (0.0, 350.0) in expanded state and (0.0, 150.0) in collapsed (and stays that way on the other models, no matter how far you scroll after that).

Thank you in advance!

**Comment by patchthecode** [comment]
OK. i suppose you change the height of the calendar, and then do a `reloadData(withAnchor: date)`

So basically youre saying that the anchorDate's position of wrong on the plus devices?
If this is so, is it possible you can paste the code that you use to change the height and reload the data?

**Comment by myurieff** [comment]
Hey, thank you for replying. I am not reloading any data. I just call 

`if let fiveWeeksAgo = Calendar.current.date(byAdding: .day, value: -35, to: Date()) {
                calendar.calendarView.scrollToDate(fiveWeeksAgo)
            }`

So that the bottom row the calendar becomes the current week. 

Here's a video of the issue: https://streamable.com/ob4pj

Notice how when the calendar gets anchored, the current week is shown, but after a little bit of scrolling further, the unexpected scroll happens.

**Comment by patchthecode** [comment]
hmm. and just to confirm, we are sure that scroll function is not being called twice right?

i'll be up in a couple more hours. Its 4am here.
Will look into it more in a few hours.
i'll be on here once im up -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by myurieff** [comment]
Yes, I've tested everything that came to my mind. The scroll function gets called only the first time the calendar gets anchored. And then when it's time to expand it gets called again to 'restore' its state to what it was like at the beginning. Another thing happening with the Plus after expanding again the calendar its styling gets completely messed up. I think it's something to do with the prepareForReuse thing. 
Screenshot: http://imgur.com/a/LTKPc

It's like I haven't implemented the cellForRow function properly, which I believe is not the case.

**Comment by patchthecode** [comment]
ok lets have a talk once im up.
I'll share screens with you.

**Comment by myurieff** [comment]
Apparently we are in a vastly different regions, so I may not be up, but let me know if I can help with anything 👍

**Comment by patchthecode** [comment]
@myurieff im up. And im on the chat link -> https://gitter.im/patchthecode/JTAppleCalendar
If youre up as well.

**Comment by myurieff** [comment]
Hey, sorry I was unavailable. It's now 10 AM here, so I'll be here for a while, if there's anything 
👍

**Comment by patchthecode** [comment]
Not sure if you found a solution to this. But it be could if i either see you on chat, or maybe if you can provide me a sample project that i can debug.
Will close this issue until you respond. thanks.
