### ISSUE TITLE
How to make Calendar to  select date in range For Example if I click on date 1-8-2017 than click on 15-8-2017 it make color from 1 to 15 

### ISSUE THREAD

**Issue by jeewanct** [patchthecode/JTAppleCalendar#551]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. Please state the version number of this library you are using when you create the issue.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.0.6
3. Is your question already answered in the tutorials and guides —> https://patchthecode.github.io/
4. Don't just ask a question. Provide enough information so I will be able to recreate the problem you are facing. 
   It would be even better if you provided an example app if possible.

Like this project? Consider supporting by leaving a star rating. :)

Thanks,
Jay

**Comment by patchthecode** [comment]
```swift
calendarView.selectDates(from: date1, to: date2,  keepSelectionIfMultiSelectionAllowed: true)
```

**Comment by jeewanct** [comment]
But how to change color of the cell  can you please make video for that

**Comment by patchthecode** [comment]
You change the color of a cell the very same way you'd change the color of a cell in  a UITableView or a UICollectionView.

Inside your `didSelect` function, you change the color of the cell.
I have videos on all these. Here si the full link of all the vids -> [Here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)
