### ISSUE TITLE
Vertical Scroll Bug

### ISSUE THREAD

**Issue by smartyram** [patchthecode/JTAppleCalendar#552]
Library version: 7.0

If user taps anywhere in the top status bar the calendar will scroll to the startDate set in func configureCalendar(_ calendar: JTAppleCalendarView).

Please see video to understand the bug. https://youtu.be/HnR8yBX8Uww

Sample project attached.
[CalenderScrollBug.zip](https://github.com/patchthecode/JTAppleCalendar/files/1278162/CalenderScrollBug.zip)

**Comment by patchthecode** [comment]
good catch. Will fix this.

**Comment by smartyram** [comment]
Thanks!

**Comment by patchthecode** [comment]
in the file called `UIScrollViewDelegate.swift`  look for the function called 

`public func scrollViewDidScrollToTop(_ scrollView: UIScrollView)`

can you change the function to this?

```swift
public func scrollViewDidScrollToTop(_ scrollView: UIScrollView) {
        if scrollView is JTAppleCalendarView {
            scrollViewDidEndDecelerating(self)
        }
    }
```

And let me know if this fixes this?

**Comment by smartyram** [comment]
Thanks for the quick response. Unfortunately that change does not fix it.

`scrollViewDidScrollToTop(_ scrollView: UIScrollView)` is called after the scrolling occurs, so the check `if scrollView is JTAppleCalendarView` does nothing to fix the bug.

**Comment by smartyram** [comment]
Probably check should be done here? 
`scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {`

**Comment by smartyram** [comment]
This fixes the problem.
`    public func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
        return false
    }
`

As per Apple documentation

> Asks the delegate if the scroll view should scroll to the top of the content.
> If the delegate doesn’t implement this method, true is assumed. For the scroll-to-top gesture (a tap on the status bar) to be effective, the scrollsToTop property of the UIScrollView must be set to YES.

So I need to set it to false always? Since I do no want the the scroll-to-top gesture to be effective.

**Comment by smartyram** [comment]
Ok it is not a bug. I fixed it with this in my code.
`calendarView.scrollsToTop = false`

Thanks for all the help. You are faster than paid service! :) Keep up the good work.

**Comment by patchthecode** [comment]
thanks. will close this then.
