### ISSUE TITLE
IMPORTANT: Here are some of the changes in the upcoming version. It may cause some very minor code breaks.

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#553]
# **Problem 1**: UICollectionView cell pre-fetching enables your calendar to scroll smoothly. But some problems arise. 
A case can arise where a cell is already pre-fetched, but is still not yet visible on the screen.
<img width="250" alt="screen shot 2017-09-08 at 2 32 29 pm" src="https://user-images.githubusercontent.com/2439146/30231783-68425b08-94a1-11e7-97ae-5810d12be915.png">

In a case like this, lets say a user selects the `Feb1` outDate. 
<img width="250" alt="screen shot 2017-09-08 at 2 32 29 pm" src="https://user-images.githubusercontent.com/2439146/30232023-92f5d018-94a2-11e7-8679-0a7f620ada76.png">

Then the Feb1st `inDate` on the other month has to also be updated to show a selection.
<img width="368" alt="screen shot 2017-09-08 at 2 34 23 pm" src="https://user-images.githubusercontent.com/2439146/30232114-f334297a-94a2-11e7-97c0-bb40e9347469.png">

Now If the cell is already prefetched, but still invisible, there is no way for JTAppleCalendar library to send you an instance of the already prefetched cell so that it can be updated.
The way I handled this in version 7.0.6 was to call reloadIndexPaths, but this invalidates the layout. In order to save the layout much code was done which caused subtle bugs to form.

According to [Apple documentation ](https://developer.apple.com/documentation/uikit/uicollectionview/1771771-prefetchingenabled), 

> To avoid inconsistencies in the visual appearance, use the
collectionView:willDisplayCell:forItemAtIndexPath:
delegate method to update the cell to reflect visual state such as selection.

Therefore, in the 7.1.0 version of JTAppleCalendar, i'll be forcing you developers to implement this `willDisplay` function sadly. I did not want to do this because I think implementing 2 functions with the same code is silly, but it seems that I was coding against the grain. The contents of this function will be exactly the same as the code located in the `cellForItemAtIndex` function (**except the cell dequeuing part**). Therefore in order to avoid code duplication, you can create a common function that is run by both those functions. 

If a developer can show me how to invalidate an already prefetched, but still hidden cell in a UICollectionView, then we would not have to do this.

Here is an example of what you developers should do when implementing this with a shared function to reduce code:
```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This function should have the same code as the cellForItemAt function
        let myCustomCell = cell as! CellView
        sharedFunctionToConfigureCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
        sharedFunctionToConfigureCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
        return myCustomCell
    }

    func sharedFunctionToConfigureCell(myCustomCell: CellView, cellState: CellState, date: Date) {
        myCustomCell.dayLabel.text = cellState.text
        if testCalendar.isDateInToday(date) {
            myCustomCell.backgroundColor = red
        } else {
            myCustomCell.backgroundColor = white
        }
        // more code configurations
        // ...
        // ...
        // ...
    }
```

OR as developer @boborbt  mentioned below, you can just do all you setup inside the `willDisplayCell` function. And for your `cellForIndexPath` function, simply do this
```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
    let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
    self.calendar(calendar, willDisplay: myCustomCell, forItemAt: date, cellState: cellState, indexPath: indexPath)
    return myCustomCell
}
```

# **Problem 2**: UICollectionViewCell.isSelected may be out of sync.

I am thinking on removing the property of `isSelected` on a cell as it can incorrect.
In the library if the calendar is in single selection mode, if a user selects say `Feb1`, then I also cause its outDate counter part to be selected.

<img width="368" alt="screen shot 2017-09-08 at 2 34 23 pm" src="https://user-images.githubusercontent.com/2439146/30232114-f334297a-94a2-11e7-97c0-bb40e9347469.png">

Here 2 cells will be "selected" even though it is on single selection. I track this magic with the CellState struct. Therefore `cellState.isSelected` will always give you a correct value. But developers are used to using the `Cell.isSelected` property. And this causes confusion when a cell that is supposed to be selected gives an incorrect value. 

Therefore I am going to make the Cell.isSelected property unavailable unless a developer can come up with a good alternative solution. Else, Users should only use the cellState inorder to determine if a cell is selected or not.

**Comment by ahmed-sal** [comment]
For what it's worth, I personally like to create my own `isSelected` variable. I get to call it whatever I want, I play around with it's getters and setters. And it's just part of my UI design. Up to you tho.

**Comment by patchthecode** [comment]
@ahmed-sal thanks for the input. I put it up here so that people can let me know if they are using the `isSelected` property on a cell. If many people complain, then I might try to consider another solution.

I am removing it because of synchronization issues. in some edge cases. 
`cellState.isSelected` however, is managed by myself, and therefore it is always synchronized.

**Comment by santiagoprieto** [comment]
I would rather keep it clean and always use `cellState.isSelected` for JTAppleCalendar instead of apple's presets. This way there's less chance of interference with other stuff as swift and apple kits change. 

You're doing a great job at building the `cellState` for calendar-focused info.

**Comment by seanrice** [comment]
another vote for ♥︎ cellState.isSelected and ditto on the great job.

**Comment by boborbt** [comment]
I am experiencing a bug where some of the visual appearance of my cells get changed (in all the grid) when I select some cells. This happens if I remove all code that handles cell section in my app, and in the debugger I see that just after the selection occurs JTAppleCalendar make a call to `batchReloadIndexPaths`. Can my problem be related to the change outlined in this page? I am on the verge of opening an new issue, should I?

**Comment by patchthecode** [comment]
@boborbt open a new issue. Also, i am up now. will be here for rest of day -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by boborbt** [comment]
@patchthecode I was just noting that, regarding the first problem, in most cases it is not really necessary to create the `sharedFunctionToConfigureCell` function. IMHO it is cleaner and easiest to just call the `calendar:willDisplay` delegate from the `calendar:cellForItemAt` delegate. 

Thanks again for the library and your awesome support.

**Comment by patchthecode** [comment]
@boborbt you know.. that's actually a good idea haha. I wasnt thinking that route, but yes, this will be cleaner.

**Comment by patchthecode** [comment]
Version 7.1 released. closing this issue

**Comment by hemangshah** [comment]
I don't understand how @boborbt solution will work for us? @patchthecode 

Because,

```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
    let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
    self.calendar(calendar, willDisplay: myCustomCell, forItemAt: date, cellState: cellState, indexPath: indexPath)
    return myCustomCell
}
```

As if the delegate is like this,

`  func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) { ... }`

willDisplayCell will only take `JTAppleCell` so we can't pass a custom cell to it. Any info on this?

**Comment by yunikechristina** [comment]
@patchthecode sorry, I'm not really understand about what is 'testCalendar' in your source code? thank you

**Comment by patchthecode** [comment]
@yunikechristina testCalendar is just my sample code. You can remove it and put what every shared code you need.

**Comment by arjunmadgavkar** [comment]
@patchthecode - thanks for this update, spent a few hours trying to figure out what was going wrong, but this solved everything.

I have a question though, **why** can't you use _dequeueReusableCell_ in the willDisplay function? 

This was causing me an error as an unselected cell would appear to be selected, but I don't understand why this is the case.

Thank you 💯

**Comment by patchthecode** [comment]
@arjunmadgavkar This lib is built from a UICollectionView. It behaves the same way.
If you dequeue in that function, you be reusing an old cell that was already used and therefore you'd need to clean up the dequeued cell just like you would for a UICollectionView. But why would you dequeue a cell in there? `WillDisplayCell` is for displaying a cell that is already dequeued.

**Comment by PrincessKimchi** [comment]
Help please I don't really understand. 
![screen shot 2018-07-01 at 7 47 02 pm](https://user-images.githubusercontent.com/40729751/42142993-965dd8aa-7d67-11e8-9df5-97e43afd1c18.png)

**Comment by patchthecode** [comment]
@PrincessKimchi theres a sample project attached to this repository.
check it out for an eample

**Comment by nickdnk** [comment]
willDisplayCell does not get called for me. Delegate and data source are both connected, and the dequeue-function works and is called as it should. willDisplayCell is simply ignored. Any idea why?

**Comment by ajinkya92** [comment]
How can I set events based on weekdays? I server returns me values like 1,2,3,4,5,6,7 instead of weekdays. Now according to this values, I need to set green event dots. if it's 1,2,3 then green event dots will be on Mondays, Tuesdays and Wednesdays...

**Comment by yukinag** [comment]
@patchthecode
 I tried your code but it doesn't work... 
The error says " Cannot convert value of type 'CustomCell.Type' to expected argument type 'CustomCell'　at the line I wrote a ★.
Please tell me how can I fix it.

```import UIKit
import JTAppleCalendar

class ViewController: UIViewController {
    let formatter = DateFormatter()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }
}

extension ViewController: JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource {
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let myCustomCell = cell as! CustomCell
        sharedFunctionToConfigureCell(myCustomCell: CustomCell, cellState: cellState, date: date) ★
    }
    
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2018 01 01")!
        let endDate = formatter.date(from: "2018 12 31")!
        
        let paramaters = ConfigurationParameters(startDate: startDate, endDate: endDate)
        return paramaters
    }
    
    func sharedFunctionToConfigureCell(myCustomCell: CustomCell, cellState: CellState, date: Date) {
        myCustomCell.dateLabel.text = cellState.text
        myCustomCell.backgroundColor = UIColor.white
    }
        
        func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
            let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
            cell.dateLabel.text = cellState.text
            return cell
    }
}

**Comment by patchthecode** [comment]
willDisplay gets called.
it is not called as frequently as a regular UICollectionView or UITableView.
It gets called in certain situations.

**Comment by lukescott** [comment]
I think the root of the issue is updating the appearance of the cell within the controller violates MVC. The cellForItem call is meant to create the cell (view) represented by the data being passed in. The cellForItem's job is to pass that data into the cell. Examples of cellForItem usually have you update the label - this is fine because you are passing data into the cell. But as soon as you start changing the appearance of the cell, you start violating that principle.

The UICollectionView manages the selection state internally. The isSelected property on the cell cannot be trusted because in a moment of time that is how the view is being rendered. It isn't supposed to be your application state (or model). Since UICollectionView can update this state at any time, the appearance can get out of sync if you update the appearance in the controller.

What I typically do is update the appearance in the view itself:

```swift
override var isSelected: Bool {
    didSet {
        updateCellAppearance()
    }
}

updateCellAppearance() {
    if isSelected {
        // ...
    } else {
        // ...
    }
}

updateCell(info) {
    // ...
    updateCellAppearance()
}
```

That way it doesn't matter if the cell gets updated from cellForItem or by the UICollectionView itself - it always stays in sync. The cell also has a prepareForReuse method which allows you to cleanup the appearance of the cell before it is passed into the dequeue method. 

The way I see it JTAppleCalendarView manages the state of the calendar for you. So I think `CellState` should probably be `DateInfo` or something along those lines. It should also probably not be able to return the cell itself, but rather have indexPath on it as an optional (if it is being rendered). You can call cellForItem on the collection view itself. This makes the "state" (or data) not tightly coupled to the view and separates concerns.

**Comment by patchthecode** [comment]
@lukescott 
i didnt understand the last part. What are you suggesting should be changed?

> The way I see it JTAppleCalendarView manages the state of the calendar for you. So I think CellState should probably be DateInfo or something along those lines. It should also probably not be able to return the cell itself, but rather have indexPath on it as an optional (if it is being rendered). You can call UICollectionView.cellForItem on the collection view itself if you need the cell. This makes the "state" (or data) not tightly coupled to the view and separates concerns.

**Comment by lukescott** [comment]
@patchthecode Sorry! I'll see if I can be clearer. The way CellState is designed it mixes concerns. A cell is part of the UI. A date is part of the model (state). It should be "DateState" or "DateInfo". CellState also can return cell. It should have indexPath on it instead.

The problem with "CellState", and having to update the appearance in"willDisplay" and "cellForItemAt" has to do with mixing concerns in MVC. You have view code in the controller, and in the case of CellState, binding the view to the model. If "CellState" was "DateState" or "DateInfo" and had indexPath on it you could lookup the cell in the controller using indexPath (if you needed it).

**Comment by JibakDeveloper** [comment]
```
myCustomCell.dayLabel.text = cellState.text
        if testCalendar.isDateInToday(date) {
            myCustomCell.backgroundColor = red
        } else {
            myCustomCell.backgroundColor = white
        }
```

Thank you for this fix, it helped a lot.

To hopefully save someone else the confusion that I went through with the above code snippet provided in the original post:

_testCalender_ is actually just an instance of _Calendar.current_, and _red_  is _UIColor.red_ (and the white).
