### ISSUE TITLE
Day header not scrolling why?(S,M,T,W,T,F,S)

### ISSUE THREAD

**Issue by sabariswaas** [patchthecode/JTAppleCalendar#555]
![screen shot 2017-09-08 at 1 02 35 pm](https://user-images.githubusercontent.com/31398982/30200803-09b21994-9496-11e7-9d31-a96b58039c4f.png)
I want to scroll day header (S,M,T,W,T,F,S) when scrolling.
![screen shot 2017-09-08 at 1 02 15 pm](https://user-images.githubusercontent.com/31398982/30200804-0acb2532-9496-11e7-91fd-40e9eb0fc698.png)

thanks,
Sabari

**Comment by patchthecode** [comment]
[This video](https://www.youtube.com/watch?v=CQNotydm58s) shows you how to create a scrolling header
