### ISSUE TITLE
cellState of cell in didSelectDate not updated

### ISSUE THREAD

**Issue by jokerham** [patchthecode/JTAppleCalendar#558]
Version is 7.0.6
While debugging didSelectDate function, I have found that the cellState of the cell in the parameter and cellState in the parameter does not match.

![2017-09-10 9 40 50](https://user-images.githubusercontent.com/8528842/30249542-1026769e-9671-11e7-9417-00f22eeb5e33.png)

as you can see the cellState variable shows that isSelected = true, while calendarCell.cellState.isSelected = false.
I am trying to achieve some layout functions in setTheme based on calendarCell variable, but since the status is not update, it does not show correctly.

Do I have to change the state myself?

**Comment by patchthecode** [comment]
you have to use cellState.
Here is a discussion on this -> https://github.com/patchthecode/JTAppleCalendar/issues/553

I am thinking of removing isSelected on the cell.

**Comment by patchthecode** [comment]
closing issue. Let me know if you still need more information on this.

**Comment by jokerham** [comment]
I was not referring to the isSelected of the cell, but the cellState. Just that the cellState on the cell(p) of parameter and the cellState(P) on the parameter differs. I can always resolve it by overriding the cellState of the cell(p) from cellState(P) received.

**Comment by patchthecode** [comment]
I do not understand.
✅ We only have on `cellState` which is given by the function.
❎ We do not have a `cellState` on the cell.

Can you explain some more by joining me here? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Closing again until response.

**Comment by patchthecode** [comment]
Ah thanks for responding.
If you have any other issues, then let me know.
