### ISSUE TITLE
Project for Issue #549

### ISSUE THREAD

**Issue by myurieff** [patchthecode/JTAppleCalendar#559]
Hello :) 

I saw that you've closed #549, so I decided to make a new project and attempt to recreate the issue.
You can download the project here: https://mega.nz/#!JtpHCAbC!MogATISaCidv76uXIRjZX4M-c7WlPS-s5qIhtNVV4qQ. The same exact issue occurs, again, only on the Plus model.

Thank you in advance! If you need anything else, let me know.

**Comment by patchthecode** [comment]
thank you.
checking it out now.

**Comment by myurieff** [comment]
Hey, just to let you know, the issue persists on the iPhone X as well.

**Comment by patchthecode** [comment]
saving project here on github for easier access
Still looking at it.
[calendarscrollbug 2.zip](https://github.com/patchthecode/JTAppleCalendar/files/1307047/calendarscrollbug.2.zip)

**Comment by patchthecode** [comment]
Ok. i think i found the bug.
Working on a fix now.

**Comment by patchthecode** [comment]
Code has now been fixed on master branch.
I dont know if you are using master branch, but there are 2 breaking code changes there. The reason for the change is explained here -> https://github.com/patchthecode/JTAppleCalendar/issues/553

put this in your pod file and run a `pod update`
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

if you need help implementing it, then let me know.

**Comment by patchthecode** [comment]
If for what ever reason you cannot use master branch right now, then you can fix the issue your self.
Head to the `JTAppleCalendarLayout.swift` file and replace this function with this code
```swift
    override func shouldInvalidateLayout(forBoundsChange newBounds: CGRect) -> Bool {
        return
            abs(lastSetCollectionViewSize.height - newBounds.height) > errorDelta ||
            abs(lastSetCollectionViewSize.width - newBounds.width) > errorDelta
    }
```

**Comment by patchthecode** [comment]
closing issue

**Comment by myurieff** [comment]
Thank you so much, man. Everything works flawlessly 👍
