### ISSUE TITLE
How do I know if cell is thisDay 

### ISSUE THREAD

**Issue by willard1218** [patchthecode/JTAppleCalendar#560]
I would like know highlight cell that is thisDay, just like Apple Calendar.
But **dateBelongsTo** of **CellState** haven't **thisDay** value,
So how do I know if cell is thisDay ?

**Comment by myurieff** [comment]
In the project I'm currently working, I just use simple yyyy.MM.dd date formatter to compare cellState.date to Date().

**Comment by patchthecode** [comment]
Dev @myurieff is correct.

If you want to know know if a particular day is `Today` just compare it.
You can compare it with your calendar instance.
```swift
let myCalendar = Calendar.current // You can configure this calendar to your time zone and locale etc
if myCalendar.isDateInToday(myDate) {
   print("This date is Today!")
} else {
   print("This date is not today")
}
```
