### ISSUE TITLE
outDates not choosing the correct orientation case between different months in a selected range

### ISSUE THREAD

**Issue by Hendies567** [patchthecode/JTAppleCalendar#561]
I'm using 7.0.6 and I'm coming into a problem with the continuation of a date range selection between months - concerning outDates. 
I've selected the Dates 4th October to 11th October yet on the September calendar, the 7th October cell appears as a .right orientation, whereas it should be .middle

<img width="373" alt="screen shot 2017-09-11 at 19 52 38 copy" src="https://user-images.githubusercontent.com/26363840/30291522-1fa81de2-972b-11e7-9f9c-22440c906431.png">

This also occurs for me when I've selected a range with a starting point before the outDates of the next month

<img width="375" alt="screen shot 2017-09-11 at 19 49 21 copy" src="https://user-images.githubusercontent.com/26363840/30291591-4b3e102e-972b-11e7-8013-ef36d2cd6884.png">

The 29th October cell here should similarly be a .middle orientation.
Let me know if you need any of my code, or if I'm missing something obvious.

Any help would be appreciated, thanks!

**Comment by patchthecode** [comment]
Is your situation similar to this? -> https://github.com/patchthecode/JTAppleCalendar/issues/391

**Comment by Hendies567** [comment]
Yes! Must've slipped under my radar when I was looking through the issues. It's identical to the problem with the pictured 6th of May orientation

**Comment by patchthecode** [comment]
OK, lets try to track this issue over there.
Currently, this library gives a direct description of the left, middle, right, and full.
The guy over there says some good points as to what it should be, but I have not yet come up with a way to do this without impacting performance.
Now that you have brought it up to my attention again, i'll take a look at it.
But in the mean time, it just might be that you'll have to manage those things your self.
I'll take a look however.

**Comment by patchthecode** [comment]
will close this issue. Lets put all comments over there.
