### ISSUE TITLE
Tableview with notes (JTAppleCalendar V 7.0.6)

### ISSUE THREAD

**Issue by coty10** [patchthecode/JTAppleCalendar#563]
I am building a calendar with notes. So basically what i'm trying to achieve is to show the calendar and beneath it a tableview which will list all the notes for that specific day. The note are stored in core data. So i have two Entity: AgendaNotes AgendaNoteDates

AgendaNotes has a one to many relationship with AgendaNoteDates (so basically every note can have multiple dates)

The point is to get all the note with the dates and show beneath the selected date the list of the note belonging to that specific date. Each time the user select another day/date the tableview will update and show the note for that day if any exist or a simple text if there are no note.

Until now I have set up the calendar:

    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var calendar: JTAppleCalendarView!

    var eventsFromTheServer: [String:AgendaEvent] = [:]

    override func viewDidLoad() {
        super.viewDidLoad()
    DispatchQueue.global().asyncAfter(deadline: .now()) {
         let serverObjects = self.getServerEvents()
         for (date, event) in serverObjects {
            let stringDate = self.formatter.string(from: date)
            self.eventsFromTheServer[stringDate] = event
        }

        DispatchQueue.main.async {
            self.calendar.reloadData()
        }
    }

Here is where I handle the cell selection:

     func handleCellSelection(cell: CalendarCell, cellState: CellState) {
        let cellDateString = formatter.string(from: cellState.date)
        for (title, event) in eventsFromTheServer {            
            if title == cellDateString {
                 func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> 
    UITableViewCell {
                    // Dequeue Cell
                    let cell = tableView.dequeueReusableCell(withIdentifier: "CalendarAgendaCell", for: indexPath) as! CalendarAgendaCell
                    //Fetch model object to display
                    configuringCell(cell: cell, indexPath: indexPath)
                    // Return cell
                    return cell
                }
            }
        }
    }
     func configuringCell(cell: CalendarAgendaCell, indexPath: IndexPath) {
        let myEvent = myEvents[indexPath.row]
        cell.configureCell(agendaEvent: myEvent)
    }
       // Cell Configuration Functions
    func configureCell(cell: JTAppleCell?, cellState: CellState) {
        guard let myCustomCell = cell as? CalendarCell else {return}

        handleCellSelection(cell: myCustomCell, cellState: cellState)
        handleCellEvents(cell: myCustomCell, cellState: cellState)
    }
    func handleCellEvents(cell: CalendarCell, cellState: CellState) {
        formatter.dateFormat = "dd MM yyyy"
        cell.dotImage.isHidden = !eventsFromTheServer.contains { $0.key == formatter.string(from: 
    cellState.date)}
    }
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, 
    cellState: CellState) {
        selectedDate = date
        configureCell(cell: cell, cellState: cellState)
        calendar.reloadData()
        tableView.reloadData()   
    }
And here my extension to get the values:

    extension CalendarVC {
    func getServerEvents() -> [Date:AgendaEvent] {
        var myEvent: AgendaEvent!
        var eventDate: Date!
        for event in myEvents {
            for date in (event.agendaDates as? Set<AgendaDate>)! {
                let eventDates = date.agendaDates
                eventTitle = event.agendaTitle
                eventDesc = event.agendaDescription
                eventDate = eventDates
                myEvent = event
            }
        }

        formatter.dateFormat = "dd MM yyyy"
        let eventDateString = formatter.string(from: eventDate)
        formatter.dateFormat = "dd MM yyyy"
        return [formatter.date(from: eventDateString)! : myEvent ]
       }
    }

Obviously I have implemented the JTAppleCalendarViewDataSource and the JTAppleCalendarViewDelegate.

This is the first time I'm using JTAppleCalendar and I haven't been able to find any help in the doc. Unfortunately it seems I cannot understand where my mistake is, so even a small pointing in the right direction will be really appreciated!

**Comment by coty10** [comment]
I have fixed this... i'm getting my event data from Core data so there's no need to use in the viewdidload the DispatchQueue.global().asyncAfter... there's no need also of the extension getServerEvents. I'll loop through my events with a simple for loop:
    var selectedDate: Date!
    var eventDate: Date!
    var myTempEvent: AgendaEvent!
    var myEventDate = [String]()
    var myTempEvents = [AgendaEvent]()
    var myEvents = [AgendaEvent]()

     func getEventDates() {
        for event in myEvents {
            for date in (event.agendaDates as? Set<AgendaDate>)! {
                let eventDates = date.agendaDates
                eventDate = eventDates
                formatter.dateFormat = "dd MM yyyy"
                let eventDateString = formatter.string(from: eventDate)
                myEventDate.append(eventDateString)
            }
        }
    }

then i configure my table cell like this:
        func configuringCell(cell: MyCell, indexPath: IndexPath) {
        for dates in calendar.selectedDates {
            for dateOfEvent in myEventDate {
                formatter.dateFormat = "dd MM yyyy"
                let dateToCompare = formatter.string(from: dates)
                if dateOfEvent == dateToCompare {
                    let myEvent = myTempEvents[indexPath.row]
                    cell.configureCell(agendaEvent: myEvent)
                } else {
                    
                }
            }
        }
    }
configuring cell func is called in cellForRawAt (tableView).

then i have a func to retrieve all the events associated with the data:
     func agendaEventsWithDate(date: Date) -> NSFetchRequest<AgendaEvent>
    {
        // create a fetch request that will retrieve all the AgendaEvents.
        let fetchRequest = NSFetchRequest<AgendaEvent>(entityName: "AgendaEvent")
        
        // set the predicate to only keep AgendaEvents where the related AgendaDate's date matches the passed in date.
        let cal = Calendar.current
        let startOfDay = cal.startOfDay(for: date)
        print(selectedDate)
        let endOfDay = cal.date(byAdding: .day, value: 1, to: startOfDay)!
        

        fetchRequest.predicate = NSPredicate(format: "SUBQUERY(agendaDates, $a, $a.agendaDates >= %@ AND $a.agendaDates < %@).@count > 0", startOfDay as NSDate, endOfDay as NSDate)
        
        return fetchRequest
    }

and finally i call this in the didSelectDate func of the calendar
        func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        selectedDate = date
        configureCell(cell: cell, cellState: cellState)
        calendar.reloadData()
        myTempEvents = try! context.fetch(agendaEventsWithDate(date: selectedDate))
        tableView.reloadData()
    }

**Comment by patchthecode** [comment]
Thats good man. 
I was gonna get to this over some weekend. But I had to fix other issues first as they were more damaging. I'll note the work as reference.
