### ISSUE TITLE
How to use JTAppleCalendar in iOS 11, XCode 9?

### ISSUE THREAD

**Issue by Adelmaer** [patchthecode/JTAppleCalendar#564]
Hello, my app need to be released in iOS 11. (minimum deployment target)
I've been using JTAppleCalendar 7.0.4 (installed via CocoaPods with pod 'JTAppleCalendar', '~> 7.0') while i've been developing the app with iOS 10 Xcode 8.
Now i've opened app in Xcode 9, converted to Swift 4 and changed deployment target to iOS 11 and I see errors related to JTAppleCalendar.
Can't you tell me please how to migrate or update your calendar to make it work in iOS 11 project?
Is it available at the moment? Should I convert JTAppleCalendar Target to Swift 4?

**Comment by patchthecode** [comment]
the latest version is compatible.
There are some changes which fixes some errors on version 7.0.4 
You need to add one extra function, and I think the name of one variable has changed.

Latest version is on master branch.
You can join me here (after my work time) to help with changes if you like -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by Adelmaer** [comment]
Thanks for answer and invitation, but should I convert the pod to Swift 4 or not? ( It's the first time i'm migrating to another Swift version, that's why I don't clearly understand how to update pod. ) As long as I understand your answer, I need to update my pod to 7.0.6 with with pod 'JTAppleCalendar', '~> 7.0.6 and not update the pod to Swift 4 ?
![screen shot 2017-09-13 at 20 32 27](https://user-images.githubusercontent.com/4399252/30391627-cdd1c902-98c2-11e7-8528-1c9f4db0da4f.png)

**Comment by patchthecode** [comment]
Yes.
Its asking you to update to swift4 because 7.0.4 is not swift 4 compatible.

If you update to 7.0.6, then it will not ask you this, because 7.0.6 _is_ swift 4 compatible.

i am currently updating 7.0.6 on master branch. After I release it, it will become version 7.1.0
But since you need your project right now, then update to 7.0.6

After you update, just do a check to see if every thing is ok and is as behaved in 7.0.4
And let me know.

**Comment by Adelmaer** [comment]
Just updated my pod to 7.0.6 with: pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
![screen shot 2017-09-13 at 21 11 58](https://user-images.githubusercontent.com/4399252/30393659-843d221c-98c9-11e7-83e8-bc1bcc2a7cf3.png)

iOS Deployment target is set to iOS 11.
In issue navigator it still showing me Swift 4 issue, asking me to convert JTAppleCalendar to Swift 4.
![screen shot 2017-09-13 at 21 19 26](https://user-images.githubusercontent.com/4399252/30393723-acb046a2-98c9-11e7-955f-6fe462eb2320.png)

**Comment by patchthecode** [comment]
Try converting and let me know if any code has changed.
I do not think any code should be changed. Try it and let me know.

**Comment by Adelmaer** [comment]
Converted, everything is Ok now, thanks! Solved!

**Comment by patchthecode** [comment]
awesome.
