### ISSUE TITLE
Dynamic height based on number of weeks in month

### ISSUE THREAD

**Issue by jefflopes** [patchthecode/JTAppleCalendar#566]
I'm sure this must be a FAQ, but I've read a bunch of the other issues and the wiki and I haven't been able to figure it out...

How do I dynamically size JTAppleCalendar based on the number of weeks in the month? I'm using generateOutDates: .tillEndOfRow, but it still leaves an empty row at the button of the view.

**Comment by jefflopes** [comment]
You can see the extra space under the rows in this screenshot from view debugger:

<img width="245" alt="screen shot 2017-09-14 at 3 33 57 pm" src="https://user-images.githubusercontent.com/54537/30451927-3e55b6ee-9962-11e7-9979-2b60edce400c.png">

**Comment by patchthecode** [comment]
`generateOutDates: .tillEndOfRow` shoulw work.

What version of the app are you using?
And if possible, to make things faster can you zip a sample project and drag it in this chat box?
Delete the derivedData and debug folders to make it smaller.

**Comment by jefflopes** [comment]
@patchthecode Thanks for the reply. I'm using 7.0.6. I'll see if I can factor this code out into a small sample project and report back.

**Comment by patchthecode** [comment]
alright thanks. will wait.

**Comment by jefflopes** [comment]
@patchthecode Here you go. Pod install, build, and run and you should see the calendar with the empty row at the bottom. Thanks for the help! 

[JTAppleCalendarHeightIssue.zip](https://github.com/patchthecode/JTAppleCalendar/files/1304571/JTAppleCalendarHeightIssue.zip)

**Comment by patchthecode** [comment]
@jefflopes just checked it out. You have not configured your constraints correctly in the `CalendarView.xib` file.

**Comment by jefflopes** [comment]
@patchthecode Thanks for looking. Are you able to be more specific? I just double checked the constraints in both xibs and I did notice I had a 1:1 ratio constraint that might have been the problem but after removing it it's still not working. Were you able to get it working in that project? 

Here's an updated version of the project with simplified constraints (ie, the 1:1 ratio constraints removed): 

[JTAppleCalendarHeightIssue.zip](https://github.com/patchthecode/JTAppleCalendar/files/1304758/JTAppleCalendarHeightIssue.zip)

**Comment by patchthecode** [comment]
My apologies man.
Investigating it some more. I may might have judged this issue too quickly.
Taking a 2nd look.

**Comment by patchthecode** [comment]
i looked at your code, and i saw this -> 
`calendarCollectionView.allowsDateCellStretching = false`

This will make your cells not stretch the meet the bottom of the calendar.
Therefore, with it enabled, you will see the space you are seeing.
Remove this code to get rid of the space.

The size of the cells are determined by the height of the calendar view. 
If you want your cells to be a perfect square, then make the calendar's size 1:1 like you had it originally.

**Comment by jefflopes** [comment]
@patchthecode That's not exactly what I'm trying to do. I'd like to have fixed cell width/height and fixed spaced between the cells, which would require the calendar view itself to change height based on the number of rows. Is that possible?

**Comment by patchthecode** [comment]
@jefflopes can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing as issue was resolved over chat.

**Comment by hartjosh** [comment]
I am also trying to do the same and I am running into the same issue.  Could you comment on how you fixed the dynamic calendar view height based on the number of week rows being presented for the month?

**Comment by patchthecode** [comment]
@hartjosh here is an example of a project with JTApplecalendar using dynamiv height -> 
https://github.com/patchthecode/WLAppleCalendar

How it helps.

**Comment by drouston** [comment]
@patchthecode the WLAppleCalendar project does have the functionality but is there any explanation or guidance on how to implement exactly? After much tinkering I'm still unclear on the exact code and ib constraint settings to mimic the behavior in the WL project file.

If I need to open a new issue let me know. Also, the link in your last is broken. Found the page on a google search. https://github.com/willard1218/WLAppleCalendar
