### ISSUE TITLE
Best practice to adjust Monday - Sunday header?

### ISSUE THREAD

**Issue by seanrice** [patchthecode/JTAppleCalendar#567]
7.0.6
Today i decided to turn off hasStrictBoundaries to create continuous dates in 1-row setup. Now I'm looking for a solution to adjust weekday headers. 

Logically, given date, one needs to know the 'count' of days shifted when GeneratedInDates and GeneratedOutDates are off for 1-row –– and use this to adapt weekday headers. How?

Background -- Basically, i'm going from monthly to weekly view ... from 6 rows to 1 row ... and while generateInDates and generateOutDates is set .forAllMonths and .tillEndOfGrid for monthly view, these are OFF for 1-row view. Everything looks great, except for my weekday headers.

**Comment by patchthecode** [comment]
Ah. The default configuration for a 1-row calendar is this

```swift
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 1,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .off,
                                                 hasStrictBoundaries: false)
```

`.forFirstMonthOnly` is used to generate the offset in the columns. And with strict boundaries set to false, it will snap right next to the previous months.

Let me know fi this helped.

**Comment by seanrice** [comment]
ha! i just figured the "forFirstMonthOnly" part out ... was upgrading a class with elaborate code when it hit me... to try ". forFirstMonthOnly" ... and that did the trick. returned here to sheepishly but gladly admit the ease of solution. Thanks Patchman !!!

**Comment by patchthecode** [comment]
youre welcome :)
