### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 3.2

### ISSUE THREAD

**Issue by Matiaz** [patchthecode/JTAppleCalendar#569]
*Using the latest version: 7.0.6

Was using the library version 7.0.4 with Xcode8 and was working fine, then I updated Xcode to Xcode9 and now it throws an error that says: **Module compiled with Swift 3.1 cannot be imported in Swift 3.2** 
I'm using Xcode 9GM and the library JTAppleCalendar 7.0.6 and also Carthage 0.25.0.

I tried reinstalling Carthage, updating the library, etc. Nothing works. Any ideas? Thanks

**Comment by patchthecode** [comment]
ok. looking into it.

**Comment by patchthecode** [comment]
Hmm, I am not sure if there is some setting you're not configuring correctly?

I just created a new project. And followed the instructions [Here](https://www.youtube.com/watch?v=SSFXzNXzn2k&index=2&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q).
And it installed and worked. I am also using XCode 9GM swift 4. And it worked.

Here is the sample app i created. 
[CartExample.zip](https://github.com/patchthecode/JTAppleCalendar/files/1315019/CartExample.zip)

Just do a `carthage update` on the example and it should work fine. Let me kow.

**Comment by patchthecode** [comment]
Will close this issue until user responds.
Label set to `Awaiting User Input`
