### ISSUE TITLE
extension of  CalendarViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate

### ISSUE THREAD

**Issue by nikpocuca** [patchthecode/JTAppleCalendar#570]
Hi , 

It is asking me to provide another function, I've been following your video tutorial but you only have two protocols outlined in the video. I cloned your project and implemented everything correctly. Could you resolve this issue?

Here is the code: 

`  func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: 
    Date, cellState: CellState, indexPath: IndexPath) {
        <#code#>
    }
`

I already have these two defined 

    ` func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: 
      CellState, indexPath: IndexPath) -> JTAppleCell {
     
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: 
        indexPath) as! CustomCell
        
        cell.dateLabel.text = cellState.text
        
        return cell

    }
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from:"2017 01 01")
        let endDate = formatter.date(from: "2018 01 01")
        
        let parameters = ConfigurationParameters(startDate: startDate!, endDate: endDate!)
        return parameters
    }

`
Why is it asking me to conform to another protocol? 

Thanks

 - Nik

**Comment by patchthecode** [comment]
You must be  using the latest master branch code.
Yes, in the update to come, i will be forcing every one to implement the `willDisplayCell` function.
The reason is explained here -> https://github.com/patchthecode/JTAppleCalendar/issues/553
