### ISSUE TITLE
Migration from v6 to v7: runtime error

### ISSUE THREAD

**Issue by boborbt** [patchthecode/JTAppleCalendar#571]
Hi,
   I'm trying to migrate a project from version 6.1 to version 7.0.6. I've fixed the compilation errors mainly adopting the JTAppleCell as the cell of the calendar and fixing the calendar::: delegate method (btw, is there any migration guide?). My problem now is a runtime error (`Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`)  at line: 

https://github.com/patchthecode/JTAppleCalendar/blob/48c5fbbc025010f94a80807463523ffda0c639ce/Sources/JTAppleCalendarView.swift#L98 

due to the fact that `collectionViewLayout` is not initialised. I believe that JTAppleCalendarView manage its own collectionView and thus I do not understand how can fix the problem in my code. Any suggestion would be of great help.

Thanks in advance,
    Roberto

**Comment by patchthecode** [comment]
Are you dong all your things through code?
or though interface builder?

If through interface builder, this [video list](https://www.youtube.com/watch?v=SSFXzNXzn2k&index=2&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q) will help you much.

If doing through code, then can you paste to me how you are declaring your calendar?

**Comment by boborbt** [comment]
Hi Jay, thanks for your support.

The main window is setup via interface builder (IB). I also used IB to place the JTAppleCalendarView inside the window. The main setup of the view is then done in code as follows:

```swift
    func setupCalendarView() {
        calendarView.calendarDelegate = self
        calendarView.calendarDataSource = self
        calendarView.register(UINib(nibName:"DayCellView", bundle:nil), forCellWithReuseIdentifier: "DayCellView")
        calendarView.scrollingMode = .stopAtEachCalendarFrameWidth
        calendarView.isScrollEnabled = true
        calendarView.selectDates([Date()])
        calendarView.scrollToDate(Date(), triggerScrollToDateDelegate: true, animateScroll: false, preferredScrollPosition: nil, completionHandler: nil)
    }
```

To the best of my understanding though the above function is never called since the app does not even get to execute the didLoad method in the main ViewController. Maybe something is not hooked up correctly in IB? I did follow your videos and, as far as I can tell, things appear to be correct. Do you have any guess about why the collectionViewLayout does not get initialised? Any suggestion about how to attack the problem?

**Comment by boborbt** [comment]
Some progress here: in IB I removed the calendar view from the main view and added a new collection view. Then I followed your video instructions to configure it. Now the didLoad method get called but I have access errors the first time I try to access any of the properties of the calendarView. Does it ring any bell to you? 

*Note*: I've also tried to change the outlet variable removing the "weak" modifier just to be sure that the object would not get dealloced by error and the problem does not change...

**Comment by boborbt** [comment]
I solved this issue (the behaviour is still not correct, but at least it launches). 

To anybody interested my solution consisted in:
- removing the JTAppleCalendarView I created with v. 6 of the library and inserted a CollectionView instead; then I followed the video tutorial to configure it;
- the access error (EXC_BAD_ACCESS) was due to not having properly spelled the name of JTAppleCalendarView in the interface (or of its module).

**Comment by patchthecode** [comment]
Sorry man. i just had a chance to see your responses.
If you need to contact me faster you can do so here -> https://gitter.im/patchthecode/JTAppleCalendar

Ok, you said the behavior is still not correct.
Can you let me know? I'll be around for a while.

**Comment by boborbt** [comment]
No problem. I just tried to contact you on gitter but you are no longer on-line (I am also 22h late in answering you 😊).

I've  made a video about it that I attach to this message (it is a zip since github does not allow me to attach a .mov file.

As you can see in the video, I have different stylings for the cells depending on whether the cells are outside the current month (they are hidden), before today (they are greyed out), or else (they then assume the default, not dimmed visual). In the video I show that even though the stylings are correct upon start, they are lost (everything is displayed in its default visualisation) as soon as I click on the bottom row or in case I change the month. Also, in the last few seconds in the video, I show that the visualisation is correct while I transition from month to month, but it gets the incorrect one as soon as I finish the drag gesture.

I tried to remove all the calendarDelegate code with the exception of the `configureCalendar(_ :)` and of the `calendar( _:, cellForItemAt date:, cellState:, indexPath: )` methods and the behaviour is still present. I am rather confident in assuming that it is something occurring outside my code (either because I misconfigured something or I lack some delegate method).

Here is the `calendar( _:, cellForItemAt date:, cellState:, indexPath: )` method:

```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "DayCellView", for: indexPath)
        let dayCell = cell as! DayCellView
        dayCell.colorEmphasis = .dim
        dayCell.isEmphasized = cellState.isSelected
        dayCell.label.text = cellState.text

        if cellState.dateBelongsTo != .thisMonth {
            dayCell.colorEmphasis = .hidden
        } else if date.before(day:Date()) {
            dayCell.colorEmphasis = .dim
        } else {
            dayCell.colorEmphasis = .normal
        }

        let calendar = Calendar.current
        dayCell.isToday = calendar.isDateInToday(cellState.date)

        let shifts = shiftStorage.shifts(at: cellState.date)
        dayCell.marks = options.shiftTemplates.templates(for: shifts).flatMap({ $0 })
        return dayCell
    }
```

[t-shift-problem.zip](https://github.com/patchthecode/JTAppleCalendar/files/1324789/t-shift-problem.zip)

Thanks in advance.

**Comment by patchthecode** [comment]
ok i'll check this out now.

**Comment by patchthecode** [comment]
resolved with master branch code. 
Master branch will become version `7.1.0`.
closing issue.
