### ISSUE TITLE
Sth is wrong with the dates after 6 November 2017.

### ISSUE THREAD

**Issue by kunass2** [patchthecode/JTAppleCalendar#572]
This is my calendar:

<img width="380" alt="screen shot 2017-09-20 at 04 20 42" src="https://user-images.githubusercontent.com/9480650/30639200-2498722a-9dbb-11e7-8b19-5cc91792b12e.png">

I arrange it like this:

    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let startDate = DateFormatter(type: .date, utcTimeZone: true).date(from: "01.01.2017")!
        let endDate = DateFormatter(type: .date, utcTimeZone: true).date(from: "01.01.2025")!

        return ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: Calendar.currentUTC, firstDayOfWeek: .monday)
    }

When I tap on the day, I display controller and set a date I tapped like this:

This is for 1 November
<img width="349" alt="screen shot 2017-09-20 at 04 23 12" src="https://user-images.githubusercontent.com/9480650/30639296-85950098-9dbb-11e7-8519-f38234d30487.png">

for 3 November:

<img width="352" alt="screen shot 2017-09-20 at 04 23 22" src="https://user-images.githubusercontent.com/9480650/30639318-9783c118-9dbb-11e7-85c6-c4cbb031a46d.png">

For 5 November:

<img width="360" alt="screen shot 2017-09-20 at 04 23 35" src="https://user-images.githubusercontent.com/9480650/30639337-a60fb1ec-9dbb-11e7-8ff7-612e137136a5.png">

For 6 November:

<img width="368" alt="screen shot 2017-09-20 at 04 23 40" src="https://user-images.githubusercontent.com/9480650/30639342-ae505532-9dbb-11e7-8f85-de9f3df03500.png">

As you can see the SAME dates are displayed for 5th and 6th November. Why?

What is wrong with that date?

Assuming. Everything is fine for the dates before 6th November, and everything is off after 6th November. Why?

**update:**

That critical date is different for every time zone I use. For example: 

Warsaw (+0200) the date is 30 October
Chicago (-0500) the date is 6th November

**Comment by patchthecode** [comment]
i guess you realized why?

**Comment by kunass2** [comment]
yes, the problem was related to sth else...
