### ISSUE TITLE
Scroll to date bug

### ISSUE THREAD

**Issue by CaptainHunter** [patchthecode/JTAppleCalendar#573]
Scroll to date doesn't seem to be working as I expected it to.

I am able to scroll to get the calendar to scroll, however the selected date kept ending up on the left (first column) causing the day positioning to be screwed.

`calendarView.scrollToDate(Date())`

**Comment by patchthecode** [comment]
@CaptainHunter what is your scrolling mode?

calendarView.scrollingMode = ?

**Comment by CaptainHunter** [comment]
I am using version 7.0.3 and I assume that my scrollingMode is none (default?) since the attribute isn't touched.

**Comment by patchthecode** [comment]
can you update to version 7.0.6 ?

**Comment by CaptainHunter** [comment]
hi it is okay, I think I have got it sorted by setting the scrolling mode.
Thanks anyway :)

`calendarView.scrollingMode` = .stopAtEachSection`

**Comment by patchthecode** [comment]
I'd prefer you updated to 7.0.6
but its cool you resolved it.
closing this issue.
