### ISSUE TITLE
Unexpected errors when moving project to Xcode 9.

### ISSUE THREAD

**Issue by kunass2** [patchthecode/JTAppleCalendar#575]
<img width="1224" alt="screen shot 2017-09-27 at 14 41 42" src="https://user-images.githubusercontent.com/9480650/30913929-29f34042-a392-11e7-9029-c24f8253b7f4.png">

This is what I try to resolve. Any help?;)

**Comment by patchthecode** [comment]
put this in `pod file`

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

Then do a `pod update`

The is the latest version to be released
Read here for changes that happened on this version -> https://github.com/patchthecode/JTAppleCalendar/issues/553

**Comment by patchthecode** [comment]
If you need more help on the issue, talk to me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by kunass2** [comment]
But another case, when I try to scroll to date:

    calendarView.scrollToDate(today, animateScroll: false)

then in version `7.0.6` it jumps, but it wasnt like this before in version 7.0.4. What should I do now?

**Comment by patchthecode** [comment]
In this code, you have removed the scrolling animation.
```
calendarView.scrollToDate(today, animateScroll: false)
```

What happens if you do this instead?
```
calendarView.scrollToDate(today, animateScroll: true)
```

**Comment by kunass2** [comment]
Hi, sorry for delay;(

The animation makes difference because of `animateScroll` parameter. My calendar starts in January 2017 and finishes in December 2025. When view is loaded, there January 2017 is loaded in the first time. And the user see how the calendar jumps or animate to current September 2017.

Before latest version (I mean 7.0.4, now it is 7.0.6) the user after view is loaded see immediately Spetember 2017 WITHOUT any jump or animation. Why now calendar jumps after view is loaded? I need to set calendar to the current date immediately to the user after view is loaded. Why it happens?

**Comment by kunass2** [comment]
It is because of latest version. When I force cocoapods to install version 7.0.4 then everything is fine. Please take a look into this.

**Comment by patchthecode** [comment]
If you are online, can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing issue.
Awaiting sample app as mentioned in chat.
