### ISSUE TITLE
cells are not showing

### ISSUE THREAD

**Issue by athemer** [patchthecode/JTAppleCalendar#577]
HI, JayT

Thanks for the wonderful library you create!

Geez, Can't believe I failed at the very first video...

So I did exactly as the first video told us to do, but my cells are not showing.

I inherit my CalendarViewController from a customBaseViewController of my own, 
which handle things like navigationItems and Controller lifeCycle 
Would that be an issue?

I am using version 7.0.5 with Xcode9 by the way. 

Is there any chance that you might point out what might went wrong? 

please kindly let me know if you need more information on this.

Thank you so much

p.s constraints are set to what needs to be set

**Comment by athemer** [comment]
okay, I just realize I forgot to add : 
```
calendarView.calendarDelegate = self
calendarView.calendarDataSource = self
```
But your tutorial works without these two lines of code :/ 
How?

**Comment by patchthecode** [comment]
I have connected the delegate and the dataSource in the video on interface builder.
And usually if your cells are invisible, it is because sometimes developers forget to set constraints on their cells.

**Comment by patchthecode** [comment]
closing issue.
Let me know if this did not resolve your issue.
