### ISSUE TITLE
cellState.date Timezone issue

### ISSUE THREAD

**Issue by HusamAamer** [patchthecode/JTAppleCalendar#578]
v7.0.6

I noticed that CellState.date is giving date always in UTC but with timezone shifting, here is an example :

when: Region with timezone: Africa/Bamako @UTC
`print(Date())` //2017-10-01 08:00:00 +0000
`print(cellState.date)` //2017-10-01 00:00:00 +0000

when: Region with timezone: Asia/Baghdad @UTC+3
`print(Date())`                // 2017-10-01 08:00:00 +0000
`print(cellState.date)` // 2017-09-**30 21:00:00** +0000 <-- **Notice the time shifting here** 
 it should give (2017-10-01 00:00:00 +0000) or (2017-**09-30** **21:00:00** **+3**)

Thanks for sharing your calendar ❤️

**Comment by patchthecode** [comment]
OK.
The calendar gives you dates in the format you provided in this function.

```
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
   // configure your custom calendar here configured to your time zone and locale
   let myCalendar = Calendar(identifier: .gregorian)
   myCalendar.timeZone = // myTimeZone
   myCalendar.locale = // myLocale

   let parameters = ConfigurationParameters(startDate: 
      startDate,
      endDate: endDate,
      calendar: myCalendar)
   return parameters
}
```

also, whenever you print dates to the console, never print the raw date. Always use a `DateFormatter`. The formatter should also be in the same format as the calendar you provided in the function above.

```
let formatter = DateFormatter()
formatter.dateFormat = "yyyy MM dd"
formatter.timeZone = myCalendar.timeZone
formatter.locale = myCalendar.locale
formatter.calendar = myCalendar

print(formatter.string(from: myDate)
```

Explanation given here -> https://github.com/patchthecode/JTAppleCalendar/issues/252
```

**Comment by HusamAamer** [comment]
@patchthecode  Thanks for explanation, I've corrected the code yesterday and everything is fine now 👍

**Comment by patchthecode** [comment]
Asweome. Closing this issue.
