### ISSUE TITLE
Scrolling To A Date Between Start And End Dates Shows A Jumbled Month

### ISSUE THREAD

**Issue by muddlegeist** [patchthecode/JTAppleCalendar#579]
Currently using JTAppleCalendar 7.0.6 with Xcode 9.0 in a project set up to use Swift 3.2

Hi, Jay.  I'm rather new to JTAppleCalendar but have so far found it to be the tool I've been hoping for to get my current project done.

The issue I'm trying to solve involves setting up a calendar with a date range from a year ago to a year into the future and starting the calendar showing the current month.

```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters
    {
        let today = Date()
        let oneYearPreviousDate = Calendar.current.date(byAdding: .year, value: -1, to: today)
        let oneYearLaterDate = Calendar.current.date(byAdding: .year, value: 1, to: today)
        
        let startDate = oneYearPreviousDate ?? Date()
        let endDate = oneYearLaterDate ?? Date()                              

        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 4,
            calendar: Calendar.current,
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfGrid,
            firstDayOfWeek: .sunday)
        return parameters
    }
```

...

`self.jtCalendarView.scrollToDate(Date(), animateScroll: false)`

When I do this (using the above code) the calendar moves to show the current month, but the day cells are jumbled in both sequence and indates/outdates.

![screen shot 2017-10-03 at 4 06 34 pm](https://user-images.githubusercontent.com/3871224/31150016-b0456eb2-a857-11e7-93aa-ed98d7a036bd.png)

When I page off of the month and then back it displays without an issue.

One thing I'm noticing is that today is the 3rd, and the 3rd is set as the first day in the month when the calendar first scrolls to my requested date of today.  Is this expected behavior?  Should I be calculating what the first day in the inDates should be to display the current month and request a scroll to that date?

Many thanks for any insight you can give me.  I really am very grateful to have this library to use.

Here's an example app based on your YouTube tutorial which shows the issue: https://github.com/muddlegeist/TJCrappleXalendarBonk

**Comment by patchthecode** [comment]
OK. will be off work soon.
Will look at this in a bit.

**Comment by patchthecode** [comment]
you setup your calendar in code.
Therefore you need to set its scrolling mode.
```swift
self.jtCalendarView.scrollingMode = .stopAtEachCalendarFrameWidth
```
This will tell the calendar where to stop scrolling.
Because you didnt set it, the library set it to `stopAtEachCalendarFrameWidth` by default but only after you have already scrolled to the date.

**Comment by patchthecode** [comment]
closing issue now

**Comment by muddlegeist** [comment]
@patchthecode This fixes it for me and it works perfectly now.  Thank you so much for looking at this.  Expect some screenshots of my calendar feature soon.

**Comment by patchthecode** [comment]
@muddlegeist awesome :) 
cheers 🍻
