### ISSUE TITLE
Type ViewController does not conform to protocol 'JTAppleCalendarViewDataSource'

### ISSUE THREAD

**Issue by yillivs** [patchthecode/JTAppleCalendar#58]
I'm sure this isn't too tough of a fix. Around the section where you need to include the protocols to display the calendar I copy paste the extension and both its methods. My code looks like this:

    extension CalendarView: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate  {  
        func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate,     numberOfRows: Int, calendar: NSCalendar) {
     
        let formatter = NSDateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        let firstDate = formatter.dateFromString("2016 01 05")
        let secondDate = NSDate()
        let numberOfRows = 6
        let aCalendar = NSCalendar.currentCalendar() 
        return (startDate: firstDate!, endDate: secondDate, numberOfRows: numberOfRows, calendar: aCalendar)
    }
    func calendar(calendar: JTAppleCalendarView, isAboutToDisplayCell cell: JTAppleDayCellView, date: NSDate, cellState: CellState) {
        (cell as! CellView).setupCellBeforeDisplay(cellState, date: date)
    }

I get the error that is in the title on the exact line of the extension. Any idea why that could be?

**Comment by patchthecode** [comment]
Is the name of your view Controller called -> `ViewController` ? or is it called `CalendarView`

In your code, the viewController called `CalendarView` conforms to the datasource protocol. I do not see where your viewController called `ViewController` conforms to the protocol. Do you have the code for that?

**Comment by patchthecode** [comment]
Closing issue. It does not seem to be calendar related.

**Comment by amrx06** [comment]
You copied the code of the example #1, I've got the same error when building. 

You need to add this method (copied from the iOS example available on GitHub) :
`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let startDate = formatter.date(from: "2016 10 01")!
        let endDate = formatter.date(from: "2016 12 01")!
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: numberOfRows,
                                                 calendar: testCalendar,
                                                 generateInDates: generateInDates,
                                                 generateOutDates: generateOutDates,
                                                 firstDayOfWeek: firstDayOfWeek)
        return parameters
}`

**Comment by patchthecode** [comment]
@amrx06 i have now fixed the main tutorial. It was missing a `,` comma symbol. The error is now gone from the tutorial

**Comment by rayutsabdeep3** [comment]
Hello, I found the error, however, I did exactly same like you did in your tutorial.
my code,
extension ViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate{
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {

    formatter.dateFormat = "dd-mm-yyyy"
    formatter.timeZone = Calendar.current.timeZone
    formatter.locale = Calendar.current.locale

    let startDate = formatter.date(from: "01-01-2000")!
    let endDate = formatter.date(from: "31-12-2030")!

    let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate)
    return parameters
}

func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
    let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
    cell.dateLabel.text = cellState.text
    return cell
}

**Comment by patchthecode** [comment]
@rayutsabdeep3 if you do not explain to me in detail your error, then i cannot help much.

1. I do not know what your error is.
2. I do know know what version you upgraded from or what version you are currently using.

**Comment by rayutsabdeep3** [comment]
Apologies. 
Type ViewController does not conform to protocol 'JTAppleCalendarViewDelegate' is the error.
and I am using calendar 7.0
XCode 8 and swift 3

**Comment by patchthecode** [comment]
The 2 major changes in version 7.1.1
were posted on the main page :(
Here is the link to it.

https://github.com/patchthecode/JTAppleCalendar/issues/553

Let me know if this explains it for you.
When ever you get an error like that, XCode suggests the fix for you. Implement the function that XCode is suggesting for you. Click on the red error bubble, and you should see a box that says `Fix`. Click on fix, and it should put in the missing function for you.

Then fill in that function with the information found here -> https://github.com/patchthecode/JTAppleCalendar/issues/553

**Comment by chriseenberg** [comment]
First of all, thank you so much for all the effort you put into this!

Thanks! This solved it for me :)

Kind regards Chris

**Comment by patchthecode** [comment]
Awesome. cheers man 🍻

**Comment by onvika** [comment]
Hi, I got this error too.
First, I followed the instructions and I thought it was fixed
this is the code
import UIKit
import JTAppleCalendar

class CalendarioViewController: UIViewController
{

    var calendarioView: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    


}

extension CalendarioViewController: JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource
{
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath)
    {
        // This function should have the same code as the cellForItemAt function
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "customCell", for: indexPath) as! CalendarCell
        
        cell.dateLabel.text = cellState.text
    }
    
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters
    {
        let formatter = DateFormatter()
        formatter.dateFormat =  "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2016 10 01")!
        let endDate = formatter.date(from: "2016 12 01")!
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate)
        return parameters
    }
    
  
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell
    {
            let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "customCell", for: indexPath) as! CalendarCell
        
            cell.dateLabel.text = cellState.text
        
        return cell
    }

  
    
}



Aaand now when I launch the App I'm getting this error
2018-06-26 07:56:55.448430+0200 TFG[14829:6963573] Unknown class JTAppleCalendarView in Interface Builder file.
2018-06-26 07:56:55.467665+0200 TFG[14829:6963573] -[TFG.CalendarioViewController collectionView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x7fb2c9609820
2018-06-26 07:56:55.486283+0200 TFG[14829:6963573] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TFG.CalendarioViewController collectionView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x7fb2c9609820'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001079671e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000106ffc031 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001079e8784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKit                               0x00000001089636db -[UIResponder doesNotRecognizeSelector:] + 295
	4   CoreFoundation                      0x00000001078e9898 ___forwarding___ + 1432
	5   CoreFoundation                      0x00000001078e9278 _CF_forwarding_prep_0 + 120
	6   UIKit                               0x000000010926ce60 -[UICollectionViewData _updateItemCounts] + 403
	7   UIKit                               0x000000010926f772 -[UICollectionViewData numberOfSections] + 22
	8   UIKit                               0x0000000109245467 -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 537
	9   UIKit                               0x00000001092477db -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 136
	10  UIKit                               0x0000000109240104 -[UICollectionViewFlowLayout prepareLayout] + 272
	11  UIKit                               0x000000010926d0a9 -[UICollectionViewData _prepareToLoadData] + 156
	12  UIKit                               0x000000010926d956 -[UICollectionViewData validateLayoutInRect:] + 53
	13  UIKit                               0x0000000109203620 -[UICollectionView layoutSubviews] + 260
	14  UIKit                               0x00000001088047a8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1515
	15  QuartzCore                          0x000000010df65456 -[CALayer layoutSublayers] + 177
	16  QuartzCore                          0x000000010df69667 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	17  QuartzCore                          0x000000010def00fb _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 343
	18  QuartzCore                          0x000000010df1d79c _ZN2CA11Transaction6commitEv + 568
	19  UIKit                               0x000000010874f269 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 141
	20  CoreFoundation                      0x0000000107909b0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	21  CoreFoundation                      0x00000001078ee2db __CFRunLoopDoBlocks + 331
	22  CoreFoundation                      0x00000001078eda84 __CFRunLoopRun + 1284
	23  CoreFoundation                      0x00000001078ed30b CFRunLoopRunSpecific + 635
	24  GraphicsServices                    0x000000010d803a73 GSEventRunModal + 62
	25  UIKit                               0x0000000108735057 UIApplicationMain + 159
	26  TFG                                 0x0000000104101887 main + 55
	27  libdyld.dylib                       0x000000010bd81955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by patchthecode** [comment]
Your very first error says

**Unknown class JTAppleCalendarView in Interface Builder file.**
This means something is wrong there. Make sure your calendar instance on story board has these 2 values set correctly 

<img width="319" alt="screen shot 2018-06-26 at 12 41 11 pm" src="https://user-images.githubusercontent.com/2439146/41935392-65b8e9ec-793e-11e8-9875-4d2684b2adb0.png">
