### ISSUE TITLE
Not Returning A Value For Number Of Items In Section

### ISSUE THREAD

**Issue by geoffreygonzales** [patchthecode/JTAppleCalendar#582]
Hello Jay!

Thanks for writing this for us; Im a noob and to have to build a calendar myself would suck
Ill buy you many many coffees when I'm rich form using your calendar

Heres the console print out of the issue :

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[iOSProject.ViewController collectionView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x102209500'

Heres the project :

https://github.com/geoffreygonzales/Honeydew

Thanks for your time!
Theres no rush, I wanted to get this to you before the weekend.

**Comment by patchthecode** [comment]
2 problems.

1. You left the module nil
<img width="259" alt="screen shot 2017-10-06 at 9 18 18 pm" src="https://user-images.githubusercontent.com/2439146/31304679-e758758a-aadb-11e7-967d-c25eaefecbb0.png">

2. You set the wrong delegates
<img width="266" alt="screen shot 2017-10-06 at 9 18 53 pm" src="https://user-images.githubusercontent.com/2439146/31304684-fa2e446e-aadb-11e7-9446-2920ead4fa7f.png">

After fixing this it will work.
Closing this issue.
let me know if youre still stuck.

**Comment by geoffreygonzales** [comment]
Hey thanks very much!

I missed that part in the tutorial
