### ISSUE TITLE
`calendar(_:, didScrollToDateSegmentWith:)` is not called 

### ISSUE THREAD

**Issue by artemstepanenko** [patchthecode/JTAppleCalendar#583]
Hello guys. I'm using the most recent version (7.0.6) of the library.
I change content offset of the calendar by using `func setContentOffset(_ contentOffset: CGPoint, animated: Bool)`. It works fine. But my problem is that the delegate method `func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo)` is not called.

Thanks,
Artem.

**Comment by patchthecode** [comment]
@artemstepanenko yes that delegate is called when you scroll with the scroll functions, or when you physically scroll with your hand.

Can you let me know what you are trying to do by setting the contentOffset this way?
I can provide you a good solution.
Are you trying to offset the calendar to a particular date?

**Comment by artemstepanenko** [comment]
@patchthecode thanks for the response. In my implementation of the calendar besides scrolling, you can switch between months also by tapping previous/next buttons. Since `JTAppleCalendarView` is inherited from `UICollectionView` I shift a content offset by using a `UIScrollView`'s method – `func setContentOffset(_ contentOffset: CGPoint, animated: Bool)` – programmatically. Unfortunately, once the animation is done I don't get `func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo)` called, which leads to a problem that I can't update UI due to the change.
Please let me know if you need more details. Thank you.

**Comment by patchthecode** [comment]
@artemstepanenko 

```swift
calendarView.scrollToSegment(.next)
calendarView.scrollToSegment(.previous)
calendarView.scrollToSegment(.start)
calendarView.scrollToSegment(.end)
```

Does this fix your issue?
By the way, if you want to know all the functions that is calendar is able to do, 
then look in the file called `UserInteractionFunctions.swift`
I stuffed all the user functions in there.

**Comment by artemstepanenko** [comment]
@patchthecode yes, it helps, thank you.

**Comment by prashannajeet27** [comment]
@patchthecode How can we refresh the calendar to show the past/future months using JTAppleCalendarView.

**Comment by patchthecode** [comment]
refresh? calendarView.ReloadData ?
