### ISSUE TITLE
First day of the week ignored

### ISSUE THREAD

**Issue by Nonouf** [patchthecode/JTAppleCalendar#584]
JTAppleCalendar version: 7.0.6

I'm building a seven day calendar using your library and I'm facing a small issue. it looks like a bug to me, but maybe I just misconfigured the calendar.

![screen shot 2017-10-09 at 17 38 02](https://user-images.githubusercontent.com/2992866/31348776-a48aef96-ad18-11e7-8366-ebab4622982f.png)

Basically, when I launch my app, I select and scroll to today with a `preferredScrollPosition` to `.centeredHorizontally`. I always want today to be in the center of the screen and then I want the paging to keep this range. For example, for today I should have a week starting last Friday and finishing on Thursday.
When I select another date, the calendar automatically scroll and a different day as first day of the week is used by the calendar (as if the value I've set is ignored), which I don't want.

I've also tried to not use `preferredScrollPosition` and instead scroll to the first day of the week (as of today would be friday), but the behaviour is still the same.

See attached video:
[scroll_bug.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/1369188/scroll_bug.mov.zip)

Here is the configure function (I'm using DateTools for the date, so please ignore the calculation):
```swift
  func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
    let startDate = Date() - 2.years
    let endDate = Date() + 2.years
    let params = ConfigurationParameters(startDate: startDate,
                                         endDate: endDate,
                                         numberOfRows: 1,
                                         generateInDates: .off,
                                         generateOutDates: .off,
                                         firstDayOfWeek: getFirstDayOfTheWeek())

    return params
  }
```
`getFirstDayOfTheWeek()` is just a function I'm using to define what day is the first day of the week in order to have today always centered. For example, as of Monday, the first day of the week would be last friday.

Playing around with the `generateInDates` and `generateOutDates` I realise that this scrolling only happen when they are off. Setting other values fix the scroll, but I get generated values, which I don't want.

**Comment by patchthecode** [comment]
acknowledged. I'll look at it after work in about 7hrs.

**Comment by patchthecode** [comment]
Ok. from the video, it looks like you have a fixed frame scrolling mode?

Can you set your scrolling mode to = .none ?
See documentation here --> https://patchthecode.github.io/CalendarScrolling/

**Comment by Nonouf** [comment]
Thanks for the quick reply.

`calendarView.scrollingMode = .none` does fix the "auto scroll", but as the option states I loose the paging on the collection view, which I don't want.

You'll find below a zip with the test project I'm using. It'll be easier for you to have a look.
[CrowdCalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/1369637/CrowdCalendarTest.zip)

The exact behaviour I'm trying to accomplish is:
* I instantiate the calendar with a range (usually very large like 4 years)
* The calendar needs to only show 7 days
* The calendar needs to support paging 
* The default date is today and it needs to be centered so for today for example, I will see Monday the 9th of October in the center of the screen and the 7 days will look like that: F, S, S, **M**, T, W, T
* When I swipe it needs to go to the next/previous week and select the current selected date plus/minus one week

To be honest, I think your library is pretty good and I can accomplish all of what I need with it (which I did), except that I have this bug I don't really understand. I'll try to look a bit deeper in the lib tomorrow if I can find the reason of the issue.

**Comment by patchthecode** [comment]
@Nonouf by the way, the correct setup for a single row calendar is this --> https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by patchthecode** [comment]
I will think on the followup information yo have provided after work.

**Comment by Nonouf** [comment]
Oh thanks! This actually fixes my issue :)

**Comment by patchthecode** [comment]
awesome.
glad it worked.
Will close this issue now.
If you have anymore questions, just ask. 👍

**Comment by patchthecode** [comment]
I had one more question for you
According to you video, I see that your header is also scrolling with the cells (it is not a stationary header).

Therefore, when you get to the end of a month are you seeing a "gap" where it offsets for the next month?

**Comment by Nonouf** [comment]
Sorry for the delay.

I see what you're talking about, but I'm actually not using any header. Each cell contains the day (number) and a short version of the weekday (date format `EEEEE`). That's why it scrolls with it and it's the behaviour I need. Thanks for the advice anyway :)

Really good library, well done! 👍

**Comment by patchthecode** [comment]
awesome.
cheers 🍻
