### ISSUE TITLE
Simple Way To Write Infinite Scrolling?

### ISSUE THREAD

**Issue by geoffreygonzales** [patchthecode/JTAppleCalendar#585]
hello,

was gonna send an email but your thing said just open an issue

anyway I've been writing stuff to calculate new start and end dates, but was wondering if there was a simple way to

1 write infinite scrolling to the future and past
2 when view did load setting the content offset of the calendar view to the date of today
3 call a function to scroll to a date

I've also forked the file; I'm not that good at coding yet but as I was reading through it I've been spellchecking the comments to have you pull later :)

thanks jay

**Comment by geoffreygonzales** [comment]
https://github.com/geoffreygonzales/Honeydew

I think the solution would be to use anchor date but idk how to implement it :(

**Comment by patchthecode** [comment]
1.  **write infinite scrolling to the future and past**
This calendar does not have infinite scrolling by default, but there are some developers who have implemented it in their projects

2. when view did load setting the content offset of the calendar view to the date of today
In your view did load, simply call 
`calendarView.scrollToDate(myDate)`
and if you dont want any animation, call 
`calendarView.scrollToDate(myDate, animateScroll: false)`

3. **call a function to scroll to a date**
Do the same thing as in question # 2

**Comment by geoffreygonzales** [comment]
thank you

I have a function that automatically sets start and end date 
a at runtime 
b whenever an individual lifts their scrolling finger && the content offset is close to the start or end

after that, would it be best to call

calendarView.reloadData()

and then 

calendarView.scrollToDate(currentDateInView, animateScroll: false)
?

**Comment by patchthecode** [comment]
how about `calendarView.reloadData(withAnchor: myDate)` ?

**Comment by geoffreygonzales** [comment]
perfect perfect perfect thank you very much.

also :
on initial configuration of the calendar, where you set start and end dates, is there a similar way to load at a specified date? 

1 when the app loads initially, the dates and other configurations are set,
2 then the view shows (briefly the start date month)
3 then, since I call scrollToDate(toDate, animateScroll : false) - it shows the specified date.

is there a way to skip / set step 2, for the initial launch of the app? (since if I call reload data here it crashes)

**Comment by patchthecode** [comment]
@geoffreygonzales 
sounds like a bug to me.

Can you put this in your `Podfile` and do a `pod update` ?

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

This version will be release in about a week or so.
Keep in mind that it will force you to implement the `willDisplayCell` function
This issue explains how you should setup the `willDisplay` cell and the `cellForItem` function in this master branch -> https://github.com/patchthecode/JTAppleCalendar/issues/553

Let me know if step 2 goes away when you scroll to date on `viewDidLoad()`

**Comment by geoffreygonzales** [comment]
I'm getting this error when running pod update

[!] There are multiple dependencies with different sources for `JTAppleCalendar` in `Podfile`:

- JTAppleCalendar (from `https://github.com/patchthecode/JTAppleCalendar.git`, branch `master`)
- JTAppleCalendar

**Comment by geoffreygonzales** [comment]
this not a primary issue for me, as the 100ms view of the `startDate` of the calendar before the `scrollToDate` is not even seen by individuals, as the calendar is initially hidden until toggled

so no pressure :)

I have another question about setting the site and position of the calendar programmatically:
I call this when view did load

```
func setCalendarSizeAndPosition()
{    
      // Get Screen Properties
      let screenWidth = UIScreen.main.bounds.width
      let screenHeight = UIScreen.main.bounds.height
                    
      // Set Size And Position Properties
      let calendarWidth = screenWidth * 0.85625
      let calendarHeight = screenHeight * 0.630281690140845
                    
      let calendarX = (screenWidth / 2) - (calendarWidth / 2)
      let calendarY = screenHeight * 0.419014084507042
                    
      // Set The Global Variable For Resting The Calendars Resting Y Position
      calendarRestingPosition = calendarY
                    
      // Set Calendar Size And Position
      calendarView.frame.size.width = calendarWidth
      calendarView.frame.size.height = calendarHeight
                    
      calendarView.frame.origin.x = calendarX
      calendarView.frame.origin.y = calendarY
}
```

this is the behavior I experience

1 when this function is called on view did load, it does not resize or reposition the calendar (I assume the size and position is captured by JTAppleCalendar)
2 I have a button that calls again `setCalendarSizeAndPosition()` this resizes and repositions the calendar successfully 
3 at the end of 1nd scroll, when finger is lifted off the screen, the calendar does not resize or reposition
4 at the end of the 2nd scroll, when finger is lifted off the screen, the calendar resizes itself to the size set in interface builder
(I also notice an sharp decrease in performance in the scroll smoothness)

I use `setCalendarSizeAndPosition()` for easily working across devices for a design. 
Worst case - ill just go through each device and set their size and width

**Comment by patchthecode** [comment]
will look at this when i awake in the morning.

**Comment by geoffreygonzales** [comment]
I pushed a project that recreated the bug

1 try with the ```label.text = ""``` commented out
2 try with ```label.text = ""``` left in

watch the console

hope this helps :)

**Comment by patchthecode** [comment]
@geoffreygonzales Hey, may i get a link to that project?

**Comment by geoffreygonzales** [comment]
oops I thought I pasted it

https://github.com/geoffreygonzales/calendar-test

**Comment by geoffreygonzales** [comment]
I thought of a work around after a beer
ill just set in interface builder that the origin is below the screen, so theres no confusion of the y position when the view get loaded :)

**Comment by geoffreygonzales** [comment]
I made another branch called `branch2`

it initially sets the y position of the calendar below the view, and the buttons show and hide it fine
but when its shown then scrolled - it blips out.

**Comment by patchthecode** [comment]
The calendar is a `UICollectionView` subclass. It behaves exactly the same as a UICollectionView would. I looked at you code, but I couldnt understand it very well.

Are you just trying to show and hide the calendar?

**Comment by geoffreygonzales** [comment]
Oh really? I thought I was being simple 

I’m trying to accomplish

1 calculate the size and width of the calendar and it’s days of week and it’s container based on the uiscreen.main.bounds.height on the initial app load
2 calendar initially below / hidden on the app load
3 button that animates it up from the bottom
4 button that animates it down
5 selecting a date returns a date object

the main issue I’m running into is after animating it up from the bottom, and then scrolling - it calls layout sub views and goes all crazy

thanks for the support so far!

**Comment by patchthecode** [comment]
> the main issue I’m running into is after animating it up from the bottom, and then scrolling - it calls layout sub views and goes all crazy and it docent scroll it just hides below the screen. Is that what you mean by the layout gets invalidated? because it’s position and size were changed and saved below the screen?

No. By invalidation I meant this -> [From Apple docs](https://developer.apple.com/documentation/uikit/uicollectionviewlayout/1617728-invalidatelayout)

If your calendar is hiding below the screen, then maybe there is something in the code doing this?
The library doesn't have any animation or default moving of frames.

For instance, i did a inspect on your views.
The calendar's Y position is well beneath the height of the size of your view.

<img width="1512" alt="screen shot 2017-10-14 at 5 32 13 pm" src="https://user-images.githubusercontent.com/2439146/31580488-e4805960-b105-11e7-8b5f-4c7255e0b502.png">

I think you need to double check by how much exactly you are moving the calendar's frame.
The image above was taken from your branch 2 code.

**Comment by geoffreygonzales** [comment]
I solved animating it up and down. I put it in a sub view and then I animate the sub view :)

We’re you able to run and try scrolling on branch 2?

**Comment by patchthecode** [comment]
Yes. I posted the image of the results on branch 2. Above.
The calendar was hidden making it impossible to scroll.

**Comment by geoffreygonzales** [comment]
Could you use the buttons to animate it up and down?

**Comment by patchthecode** [comment]
I just did.
The result is the same. The calendar is hidden.
I will close this issue for now, as it seems to be errors with the hiding of the calendar and not related to the calendar directly.

But yes you can inspect your calendar by clicking on at the bottom of the screen.->
<img width="489" alt="screen shot 2017-10-15 at 12 27 45 pm" src="https://user-images.githubusercontent.com/2439146/31588278-6241a888-b1a4-11e7-8f0e-ca48d10ec42b.png">

**Comment by geoffreygonzales** [comment]
I pushed an update on branch2 if you want to check out the scrolling
