### ISSUE TITLE
How to disable date selection

### ISSUE THREAD

**Issue by Sachin-Raut** [patchthecode/JTAppleCalendar#586]
Hi Jay,

I am selecting date range (for e.g. 12 October to 18 October) & I want to enable date selection only between this date range. That is I want to disable dates which are not in the date range.

Could you pls help in achieving this functionality.

Thanks 
Sachin

**Comment by patchthecode** [comment]
@Sachin-Raut this calendar is a UICollectionView.
So it is done in pretty much the same way.

implement the following function.

```swift
calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
}
```
