### ISSUE TITLE
Select an entire row of dates: the week

### ISSUE THREAD

**Issue by AndreaMiotto** [patchthecode/JTAppleCalendar#588]
Hi, in my calendar, when the user select a day, he will select all the entire week.

I know ho to retrieve the row.

I was thinking to use a for loop a select all the cells in that row, but I'm having problem to build the ItemPath.

Any Tips?

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        let row = cellState.row()
        print(row)

}
```

**Comment by patchthecode** [comment]
I am guessing this is you -> [Here](https://stackoverflow.com/questions/46770815/ios-swift-selecting-a-cell-i-want-to-select-the-tire-row#46770815) ?

I answered the question there for you.

**Comment by patchthecode** [comment]
I see you have selected the answer as correct. So i'll paste the same answer here, then close this issue.


ou can use 2 techniques to break the loop.

**First:**
```swift
calendarViewselectDates(from: starOfTheWeek, to: endOfTheWeeK, triggerSelectionDelegate: false)
```

By setting triggerSelectionDelegate to false, your delegate function didSelect will not be called.

**Second:**

If you are using MasterBranch code (which i'll be releasing in a week or so), you can know whether or not your selection is programmer initiated vs user initiated. You know this by --> cellState.
```swift
if cellState.selectionType == .programatic {
   // ignore stuff        
} else {
   // Do stuff
}
```
You can put this if statement in your shouldSelect function.

**Comment by kukurokie** [comment]
I don't quite get the first solution, coz after doing the selectDates, nothing happens for me.

    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        self.calendarView.selectDates(from: date.startOfWeek(), to: date.endOfWeek(), triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)
    }

**Comment by patchthecode** [comment]
@kukurokie you are calling selectDates inside didSelectDates.

This then deselect the date as soon as it is selected.

**Comment by kukurokie** [comment]
I moved selectDates inside an action for a button but it only selects one date and that's the last date based from the (from and to) parameters. 

For example: the startDate is 2018 Jan 01, endDate is 2018 Jan 07 - the only one that is selected is 2018 Jan 07.

**Comment by kukurokie** [comment]
I moved selectDates inside an action for a button but it only selects one date and that's the last date based from the (from and to) parameters.

For example: the startDate is 2018 Jan 01, endDate is 2018 Jan 07 - the only one that is selected is 2018 Jan 07.

**Comment by patchthecode** [comment]
@kukurokie do you have calendarView.allowsMultiselect = true ?

**Comment by kukurokie** [comment]
Now it works when adding that, thank you.

When I add deselectAllDates every time I select a new row of dates, it's working when I'm only selecting on the current month but when I have move to another month then selecting a new dates, it didn't deselect the previous selected dates.

Example: Select dates August 19-25, 2018 -> Select dates August 12-18, 2018 (it deselects the dates 19-25 which is right) -> move to another month -> Select dates September 2-8, 2018 -> Checked the previous month and it didn't deselect all the previous selected dates.

**Comment by kukurokie** [comment]
Thanks for that.

**Comment by kukurokie** [comment]
How come when using selectDates then using .dateBelongsTo == .thisMonth to those dates returns wrong result?

**Comment by patchthecode** [comment]
@kukurokie not quite sure what youre asking.
But if it is unrelated to this pages issue, you may need to create a new one.
