### ISSUE TITLE
how to display range selection

### ISSUE THREAD

**Issue by AndreaMiotto** [patchthecode/JTAppleCalendar#589]
Hi, I was trying to accomplish the range selection like you did in you tutorial here: https://patchthecode.github.io/RangeSelection/

Can you tell me how did you set up the layout to accomplish that continuous row with rounded corners? Not the logic, just the layout part :D

**Comment by AndreaMiotto** [comment]
yes, I understood that, but I was looking for any help in the design part :D

**Comment by patchthecode** [comment]
I do not understand what you mean. The design part is is totally up to you.

You cells can have a view called `selectedView`.
Then if the `cellState.selectedPosition() == .middle`, then you would make youre selectedView a square. And if your `cellState.selectedPosition() == .left` or `.right` you would make your selected view into a circle.

The designing is exactly as you would do for any other normal UICollectionView. Nothing is extra special about the calendar. The only thing the different is that the library provides a ready made calendar layout for you.

Which part of the design are you stuck on?

**Comment by patchthecode** [comment]
assuming issue has been resolved.
Closing issue until user responds.
