### ISSUE TITLE
Cells not showing

### ISSUE THREAD

**Issue by othyn** [patchthecode/JTAppleCalendar#59]
Sorry to be vague, I wouldn't usually ask a question unless I'm really stuck - in which I am. I've tried to debug this, but I'm at a dead end.

The problem is that the cells are just not showing in the calendar - I presume this as I've tried playing with the colours and adding new UI elements to the cell, but nothing is showing. I've checked for layout errors, colouring, etc.. and I can't seem to track down what the issue actually is. I've re-read the tutorial now several times, but cannot seem to see where I have gone wrong.

Please help! :(

**Edit project removed**

![example_cal_no_cells](https://cloud.githubusercontent.com/assets/7256684/16536760/142ae624-3fee-11e6-865e-beb0ebe74db8.png)

**Comment by zuaaef** [comment]
What version are you using again?

**Comment by patchthecode** [comment]
Are you using version 4.1.0 ?

**Comment by patchthecode** [comment]
OK checking out your file. sec.

**Comment by patchthecode** [comment]
You have an Xcode bug.

Steps to fix: 
1) Do a pod install to get the latest version of JTAppleCalendar. Latest version is now 4.1.0
2) Your Xcode is bugged. in 2 places 
  - In your `main.Storyboard`, delete all your views in there and redo them. Reconnect them, everything
  - In your `DateCellView.xib`, delete all your views and redo them, Reconnect them. everything

Your code will be fixed when you do these 2 things.
I have done this for you. Here is your file --> [TimeCard.zip](https://github.com/patchthecode/JTAppleCalendar/files/344332/TimeCard.zip)

**Comment by othyn** [comment]
Thank you so much, you version does indeed work, although I cannot get my version to work at all, despite following the steps to fix several times.

1) I've updated to the latest version of JTAppleCalendar by running `pod update`.
2) I've removed all views/classes/files, pretty much started those sections from scratch and it's still not working. Although, whats interesting is that the cell is *there* in the sense that if you click around on the calendar view, its registering the tap event as its logging the NSIndexPath.

Although, after running a a diff check in FileMerge, I cannot figure out why my project is generating vastly different xml for the storyboard. Your's generates very little in the way of constraints and position information, whereas mine generates a significant amount more.

Any ideas?

I appreciate your help, I'm still very much a beginner with Swift and Xcode, although working with other languages. So please excuse my ineptitude, it annoys me as much as it annoys you - I hate not understanding and would much rather learn from these things as to why they error.

I think I might just start the project again from scratch. It won't take too long to rebuild and will give the project a clear out. I'll make sure to implement the Pods first, get that working, then the rest of the app can follow.

**Comment by patchthecode** [comment]
You dont have to replace every thing. Just the places where you have the weird issue. Here is your bugged file -> 
<img width="1512" alt="screen shot 2016-07-02 at 10 04 33 am" src="https://cloud.githubusercontent.com/assets/2439146/16541652/f97a181e-403c-11e6-9f4c-9d53ba863d2d.png">

You can see that in 
1. You **correctly** have your main view
2. But in 2, the calendarView looks like a ghosted out color. In does  not look like a vivid color like your main view. And when you click on it, you cannot even find it on the canvas in arrow # 5.

Also, you have 2 other ghosted out color views # 2, and # 3. I have no clue what these are. Delete them and recreate them. The same ghosted color can be seen in your cellXib file for your label. Remove it and recreate it. Here is what your corrected Interface builder supposed to look like:

<img width="1543" alt="screen shot 2016-07-02 at 10 00 16 am" src="https://cloud.githubusercontent.com/assets/2439146/16541664/a59f0b36-403d-11e6-8855-09ec27532dd1.png">

You can clearly see:
1. A main view
2. Followed by a non-ghosted colored CalendarView

Also you can clearly see the CalendarView on the canvas (i put it in gray color)

**Comment by patchthecode** [comment]
Closing this issue. Have a good one. If you have any other issues let em know.

**Comment by othyn** [comment]
Thank you so much for going out of your way and providing a very detailed answer, I appreciate it. :)

**Comment by patchthecode** [comment]
Cheers man ^^ 👍

**Comment by othyn** [comment]
I'm really sorry to be a pain, but I've rebuilt the project from scratch. No copying anything across, but the same design layout - but all rebuilt from a new project.

I'm finally at the point that I was at in the previous app, but I have refrained implementing anything until I could get the calendar working. I've just implemented the calendar again and I have the exact same issue as I had originally.

What the hell am I doing wrong?! I'm starting to get angry at myself for not understanding what is going wrong, please find attached the new app. If you don't want to look, that's fine. I'll start from scratch again and see if I can peg down what exactly the issue is.

[timecardnew.zip](https://github.com/patchthecode/JTAppleCalendar/files/344770/timecardnew.zip)

**Comment by patchthecode** [comment]
Take a look at your main.storyboard. You have the same ghosted colored views. 

<img width="232" alt="screen shot 2016-07-02 at 6 56 55 pm" src="https://cloud.githubusercontent.com/assets/2439146/16543386/ee1f2b2c-4086-11e6-8e66-e1f868b90b28.png">

**Comment by patchthecode** [comment]
[Untitled.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/344833/Untitled.mov.zip)

**Comment by othyn** [comment]
Thank you so much for this, I really do appreciate the help a lot.

1. 7.3.1 (7D1014)
2. Yes. They appear as normal views for me, not ghosted:
![screen shot 2016-07-03 at 11 21 09](https://cloud.githubusercontent.com/assets/7256684/16544939/5b3ac5fc-4110-11e6-8899-d08d1870ab9b.png)
which is why I'm not understanding why they are appearing fine for me, but not for you. (background colours for illustrative purposes)
3. Simply dragging a new UIView onto the parent view in the storyboard, then applying auto layout constraints for positioning, exactly the same as you do in the video (amazing by the way, thank you).

So I tried your steps in the video and it's still not working. **BUT**, I had a brain wave. I change the IB's widths at the bottom to make it easier to edit, which after searching SO turns out that this is why the views are ghosted and why the views aren't appearing.

![screen shot 2016-07-03 at 11 43 06](https://cloud.githubusercontent.com/assets/7256684/16545010/e71e644a-4113-11e6-8127-b231b20f77a8.png)

So after setting the labels view property to be displayed on `installed`, instead of depending on the device, it works fine. Right at the bottom on here:

![screen shot 2016-07-03 at 11 43 20](https://cloud.githubusercontent.com/assets/7256684/16545012/ee74c8ce-4113-11e6-92ef-a6ace1460351.png)

changed to this:

![screen shot 2016-07-03 at 11 43 38](https://cloud.githubusercontent.com/assets/7256684/16545020/fa71e5e4-4113-11e6-8b93-3fb9122dec64.png)

> I just feel out of my depth for something I think is slap bang in front of my face.

I feel like a fool and such a simple question to Google: 'xcode ghosted views'. Oh well, fresh head and all.

Thank you so much for you help, you went above and beyond to help me out on this, I really do appreciate it. If you ever require any help with web stuff, I'm a full stack dev by trade, so I could help you out with that in return.

Thanks again & sorry for the inconvenience! 👍

**Comment by patchthecode** [comment]
:) sure man. And thanks. Have a good one. Just another question, what web programming language do you work in?

**Comment by othyn** [comment]
Haha, the least I could do.

Apache as the web server, PHP for backend (Codeigniter/Larvel frameworks), MySQL DB, standard markup/JS for frontend. Usually just run an LAMP stack on an ubuntu server box for the host, gets all the above deployed very quickly, only have to run through a very security hardening actions and its good to go.

Currently looking into Nginx as a webserver as well (each have their own benefits) and React as a new JS based backend, just to broaden my skill set, although I really don't like JS as a language. Find it messy and loose. Although there are alternatives to MySQL that can provide performance benefits, I find it to be solid.

**Comment by patchthecode** [comment]
I also dabble in PHP laravel (homestead) with MySQL. Good to know. I'm weak on front end though. Cool man, thanks for the info. Good to know for future reference. Thanks.
