### ISSUE TITLE
Can't reload dates from incomplete months

### ISSUE THREAD

**Issue by artemstepanenko** [patchthecode/JTAppleCalendar#591]
Hello. Thanks for a great work. The problem I'm experiencing is similar to [this issue](https://github.com/patchthecode/JTAppleCalendar/issues/136) which was closed a year ago.

When I call `func reloadDates(_ dates: [Date])` for a date which doesn't belong to a current month, it's not reloaded: `func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell` is not called.

**UPDATE**

The only problem is that it doesn't reload dates which don't belong to complete months.

Thanks,
Artem

**Comment by patchthecode** [comment]
I gave an answer here. Let me know.
https://github.com/patchthecode/JTAppleCalendar/issues/592

**Comment by patchthecode** [comment]
closing. We will track on #592
