### ISSUE TITLE
Header causes a gap between months

### ISSUE THREAD

**Issue by knn90** [patchthecode/JTAppleCalendar#593]
Hey there, 
Thank you for a great library. But while customizing  the calendar I face this problem. Hope you can help me out.

My Paramameter is:
```swift
ConfigurationParameters(startDate: startDate, endDate: endDate, 
     numberOfRows: 1, 
     calendar: Calendar.current,
     generateInDates: InDateCellGeneration.forFirstMonthOnly,
     generateOutDates: OutDateCellGeneration.off, 
     firstDayOfWeek: DaysOfWeek.monday, 
     hasStrictBoundaries: false)
```
Scrolling Direction: Horizontal

It works fine without the header, but when I add header, it creates the gap between months like this

<img width="573" alt="screen shot 2017-10-17 at 10 04 12 pm" src="https://user-images.githubusercontent.com/15623880/31672569-23e87b04-b387-11e7-95e0-aa1bef6c59e3.png">

Thank you very much

**Comment by patchthecode** [comment]
Let me know if the answer here works for you -> https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by knn90** [comment]
Thank you very much for helping me out. I will close this issue 👍 💯
