### ISSUE TITLE
Selecting date that also appears in previous month's outDates highlights outdate instead tapped cell

### ISSUE THREAD

**Issue by vtcajones** [patchthecode/JTAppleCalendar#594]
I'm using JTAppleCalendar in an iPad app and I have a row of calendars displayed that can be swiped through, so generally three months are visible at once. If I select, say, December 1st, but December 1st also shows up as an outdate at the end of November, the november outdate will be highlighted. Any thoughts?
![img_9d0173154c66-1](https://user-images.githubusercontent.com/1649350/31842629-0c6754fe-b5bd-11e7-89e4-a27b27feeca9.jpeg)

**Comment by patchthecode** [comment]
which version of the library are you using?

**Comment by vtcajones** [comment]
Yeah, selecting both is what I would expect, however it doesn't appear that December 1st proper is being selected, only the December 1st outdate.

**Comment by vtcajones** [comment]
So, it works as expected if I have allowsMultipleSelection = true. I really only want them to be able to have one date selected, so i just wrote some code to deselect the previous date when they pick a new one, works well enough. This library is fantastic, thanks for all your hard work!

One more question actually:

I'm trying to make the "in focus" calendar be in the center of the screen. So, December in the above image. I'm using :
`calendar.scrollToHeaderForDate(currentDate, triggerScrollToDateDelegate: false, withAnimation: true, extraAddedOffset: -offset, completionHandler: nil)` 

to calculate and scroll the month into the center when they pick a date and that works great, however, when swiping it throws it off again. Ideally i'd like to page through the months with the month always being the center of the three visible months.  I'm using 
`calendar.scrollingMode = .stopAtEach(customInterval: offset)`
but it's always off even though the calculation is right. Any thoughts how best to achieve this effect?

Thanks again so much for your help :)

**Comment by patchthecode** [comment]
hmm. that sounds like a bug to me.
With single select this should work as expected.

Can you join chat here? https://gitter.im/patchthecode/JTAppleCalendar

I need to know what version of the library you are using. Once I know the version I can let you know if my master-branch code already has the fix for it (will be releasing master-branch in a couple days).

About the 2nd Question, Let me think about it for a couple mins.

**Comment by patchthecode** [comment]
version 7.1.0 released.
closing this issue.
will continue to look  into the other update for centering the months
