### ISSUE TITLE
any way to make the calendar call didDeselect on the first touch?

### ISSUE THREAD

**Issue by geoffreygonzales** [patchthecode/JTAppleCalendar#595]
hi again jay. the bug form before ended being a weird thing with realm (a framework like core data). go figure

anyway, on the initial load of the calendar, after `configureDates`, id like a date to show as selected, meaning `isSelected = true`.

the thing is, when I set this property manually on a date (I'm doing it for todays date, since when I first load the calendar I have it show today) the thing calls `didSelect`, and on the second touch, its calls `didDeselect`

my goal is to have an initial date show as selected, and then `deselect` when another date is selected. right not I can set it to `isSelected = true`, but since it doesn't deselect, the initial date is never deselected

**Comment by patchthecode** [comment]
hmm.
ok, if you want a date to be selected when a you app loads, you can put it inside of your `viewDidLoad` function.

put this -> 
```swift
calendarView.selectDates(arrayOfDatesYouWantToSelect)
```

**Comment by geoffreygonzales** [comment]
thanks, works like a charm

**Comment by patchthecode** [comment]
awesome.
closing this issue now.

**Comment by geoffreygonzales** [comment]
thanks again

ps:
this is a bug that I have ALREADY worked around by using `.isDecelerating`
I also do not think ill encounter it as ill be using paged scrolling too

or maybe its how I'm implementing realm. not sure, but maybe you'd like to look into it for your own experimentation

`calendarView.scrollToDate(Date)` when the calendar view is still moving / decelerating -> will make the date cells disappear, if the layout constraints had changed after runtime (for example when animated onscreen)

I've gotten 1 crash with about 2 weeks of testing with this bug; the rest of the time it doesn't crash, the dates just disappear. I wish I took a picture of the log, I've been trying to make it crash but it doesn't want to. it said it tried to scroll to a date that didn't exist

**Comment by geoffreygonzales** [comment]
<img width="1552" alt="screen shot 2017-10-21 at 12 21 21 am" src="https://user-images.githubusercontent.com/22163872/31849348-db3472d4-b5f5-11e7-8190-13d8ceab042c.png">

**Comment by geoffreygonzales** [comment]
<img width="1192" alt="screen shot 2017-10-21 at 12 32 19 am" src="https://user-images.githubusercontent.com/22163872/31849468-60162686-b5f7-11e7-8750-0b02dc3c848a.png">
<img width="1148" alt="screen shot 2017-10-21 at 12 32 26 am" src="https://user-images.githubusercontent.com/22163872/31849470-6403ae58-b5f7-11e7-82da-c03cfbd336d0.png">

**Comment by patchthecode** [comment]
ok. can you let me know the steps to reproduce this?
Is it the following?

1. scroll the calendar
2. While the calendar is still scrolling, call the `scrollToDate` command.

Is this how i re-create the bug?

**Comment by geoffreygonzales** [comment]
1 move the rect of the calendar. I have mine hidden and then animate it to a show rect
2 scroll the calendar and _while_ its decelerating :
3a call `scrollToDate`
or
3b move the rect of the calendar to a different position, in my case its hiding the calendar with animation

**Comment by patchthecode** [comment]
investigating.

**Comment by patchthecode** [comment]
can you post me the link to the github of this your project again which shows this issue?
I am trying to close up all my issues before Vacation is over.

**Comment by patchthecode** [comment]
closing issue. until user responds.
