### ISSUE TITLE
Unavailable instance method 'targetContentOffsetForProposedContentOffset' was used to satisfy a requirement of protocol 'JTAppleCalendarLayoutProtocol'

### ISSUE THREAD

**Issue by derick182** [patchthecode/JTAppleCalendar#596]
I get the warning in the title when compiling.

The method is declared in JTAppleCalendarLayoutProtocol.swift

I think should be enough to change the method name in the protocol.

Thanks for Your work

**Comment by repomies** [comment]
I suddenly noticed the same problem, though in my case it's a hard compiler error which breaks the build. It also says `Type 'JTAppleCalendarLayout' does not conform to protocol 'JTAppleCalendarLayoutProtocol'`.

**Comment by repomies** [comment]
Nevermind, the project's Podfile was (rather inexcplicably) defining `platform :ios, '8.0'`. Fixing this allowed an update to the newest library version which works.

**Comment by derick182** [comment]
Anyway I solved for the moment removing targetContentOffsetForProposedContentOffset method from JTAppleCalendarLayoutProtocol.swift since I haven't customised the framework too much

**Comment by patchthecode** [comment]
can you try updating to the latest version 7.1.0 ?
