### ISSUE TITLE
Calendar View scroll to first month when i change height of calendar view

### ISSUE THREAD

**Issue by hoanganhbk94** [patchthecode/JTAppleCalendar#597]
I am using new version of calendar view. When i click a cell in calendar, if the cell has special event, i will change height of calendar view to show detail event. But calendar view scroll to first month. I don't know the reason. Help me, please !!!

**Comment by patchthecode** [comment]
If you change the height of the calendar it will scroll to the first month.
can you show me the code you are using to change the height of the calendar?

**Comment by hoanganhbk94** [comment]
![screen shot 2017-10-23 at 11 46 57 am](https://user-images.githubusercontent.com/14512150/31872710-463b951e-b7e8-11e7-82c3-4bab0ff82ed8.png)
Thanks @patchthecode rep, heightEventViewConstraint is height of detail view. i make auto layout between calendar view and detail view. When height of detail view change => size of calendar view change too. Do you give me a solution to solve this!

**Comment by patchthecode** [comment]
I am not sure what you are trying to do.
But maybe this code below helps?

```swift
UIView.animate(withDuration: 0.25, animations: {
            self.heightEventViewConstraint.constant = (cell as! CalendarCell).isEvent ? 100.0 : 0.0
            self.calendarView.alpha = 0
            self.view.layoutIfNeeded()
        }) { (endVal) in
            
            self.calendarView.reloadData(withanchor: date)
        }
        
        UIView.animate(withDuration: 1, animations: {
            self.calendarView.alpha = 1.0
        }) { (endVal) in
            
            
        }
```

**Comment by hoanganhbk94** [comment]
Thanks for your reply but it isn't working. I upload my project to github.
Do you check for me?

**Comment by patchthecode** [comment]
```swift
UIView.animate(withDuration: 0.25, animations: {
            self.heightEventViewConstraint.constant = (cell as! CalendarCell).isEvent ? 100.0 : 0.0
            self.calendarView.alpha = 0
            self.calendarView.reloadData(withanchor: date)
            self.view.layoutIfNeeded()
        }) { (endVal) in
            

        }
        
        UIView.animate(withDuration: 1, animations: {
            self.calendarView.alpha = 1.0
        }) { (endVal) in
            
         }
```

**Comment by spensko** [comment]
@patchthecode  Hi! Thanks for this great library!

I have the same issue - calendar's superview bottom constraint is attached to some details view which expands on range selection. After selecting of a second date calendar scrolls up to beginning without animations

I've tried code from above but does not work for me

`UIView.animate(withDuration: 0.3, animations: {
            self.detailsHeight.constant = 150
            self.calendarView.reloadData(withanchor: <my_second_date>)
            self.view.layoutIfNeeded()
}`

**Comment by patchthecode** [comment]
@spensko does this demo help you?
It does a resize and does not restart ->
https://github.com/patchthecode/WLAppleCalendar

Let me know

**Comment by spensko** [comment]
@patchthecode demo looks ok but i can't figure out what i need to setup for such behaviour

short video about issue 
https://youtu.be/hELmIM9tvVk

**Comment by patchthecode** [comment]
@spensko 
I looked at the video, But I am not understand how you want the calendar to behave.

**Comment by spensko** [comment]
@patchthecode long story short. if I changing some constraint which cause the calendar to change its height then the calendar resets to the beginning

I will make clean project for tests

**Comment by patchthecode** [comment]
thank you.
Send me the sample test project. I will look into it.
patchthecode@gmail.com

**Comment by spensko** [comment]
@patchthecode sended. in this sample calendar resets after deselection while changing constraint of the blue bottom view

**Comment by patchthecode** [comment]
@spensko 

Ok. I see what you are doing.
You have changed the height of the calendar. 

The will cause the layout to be invalidated.
Which will then cause the calendar to scroll to the beginning. This is normal for any UICollectionView.

Since I am getting many questions on animation, I will do a tutorial on this.

**Comment by spensko** [comment]
@patchthecode since I don't need to animate change of height of the calendar, I've anchored it to bottom of controller and change contentInset. so this issue is resolved for me :)

@hoanganhbk94

**Comment by patchthecode** [comment]
thanks for letting me know.
In the mean time, i'm doing a tutorial on animation and height change, so that people have a clear idea what to do here. Thanks for make me aware of the difficulty.

**Comment by dev-fuad** [comment]
@patchthecode 
Did you make the tutorial?

I'm making a calendar view that change height on PanGesture. And facing the same issue.

**Comment by minseungseon** [comment]
I'm facing similar issues. Is there any code that helped this kind of situation? :)
