### ISSUE TITLE
This should be a question of boundary judgment

### ISSUE THREAD

**Issue by baobao57** [patchthecode/JTAppleCalendar#598]
I downloaded the latest code today, and I found that this before the `SelectionRangePosition` state became not the same as before. But I'm not sure if this is a problem. I felt like I was in use and I had to modify some places in order to make it better if it was a problem and wanted to help it get better

![image](https://user-images.githubusercontent.com/12264243/31874764-88bc4418-b790-11e7-9cb3-d5bb36d30f35.png)

I think the correct should be this: 
```
let dateBefore = self.cachedConfiguration.calendar.date (byAdding: .day, value: -1, to: date)!    
let dateAfter = self.cachedConfiguration.calendar.date (byAdding: .day, value: 1, to: date)!
```

**Comment by patchthecode** [comment]
😄 
My error.
Fixing this now.

**Comment by baobao57** [comment]
I am honored to help you.

**Comment by patchthecode** [comment]
version 7.1.1 released.
closing this issue
thanks for you help very much
