### ISSUE TITLE
Horizontal single row calendar has wrong offset on iOS 10

### ISSUE THREAD

**Issue by Nonouf** [patchthecode/JTAppleCalendar#603]
Version 7.1.1 (but I've seen the bug on a previous 7.0.x version)

On iOS 10, it seems like the content offset is wrong on a single row calendar with horizontal scrolling mode, which result in the calendar being outside of it's visible view and scrollable vertically.

Here is my `JTAppleCalendarView` subclass constructor:
```swift
  override init() {
    super.init()

    backgroundColor = CSColour.primary.rawValue
    showsVerticalScrollIndicator = false
    showsHorizontalScrollIndicator = false
    isPagingEnabled = true
    allowsMultipleSelection = false
    scrollDirection = .horizontal
    minimumInteritemSpacing = 0
    minimumLineSpacing = 0
    calendarDataSource = self
    calendarDelegate = self

    register(SevenDayCollectionViewCell.self, forCellWithReuseIdentifier: cellIdentifier)

    selectToday(isAnimated: false)
  }
```

This is my configure method:
```swift
  func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
    let startDate = Date() - 2.years
    let endDate = Date() + 2.years
    let params = ConfigurationParameters(startDate: startDate,
                                         endDate: endDate,
                                         numberOfRows: 1,
                                         generateInDates: .forFirstMonthOnly,
                                         generateOutDates: .off,
                                         firstDayOfWeek: .monday,
                                         hasStrictBoundaries: false)

    return params
  }
```

Tested on an iPhone 7 on iOS 10, I have a 53.0 height constraints on my calendar. I checked the content offset and I get something like `(40768.0, -64.0)`, which is obvisouly wrong as the y offset should be 0. However, the content size seems to be right (I get something like `(80250.0, 53.0)`).

Here is a video showing what's happening: 
[week_calendar_iOS10_bug.mov.zip](https://github.com/patchthecode/JTAppleCalendar/files/1422371/week_calendar_iOS10_bug.mov.zip)

Note that it works fine on iOS 11.

**Comment by patchthecode** [comment]
Hmm, yea i think iOS10 behave a little differently.
Does this fix your issue? -> https://patchthecode.github.io/CommonProblems/

**Comment by Nonouf** [comment]
It does fix the issue. However, I'm wondering if it's not going to create other issues on the screen I'm building. I guess I'll see.

Thank you! :)

**Comment by patchthecode** [comment]
OK. will close this issue.
If it causes problems for you then do let me know. :)
