### ISSUE TITLE
calling deselectAllDates() causes crash for me in version 7.1.1 however this was not the case in my previous version 6.*.*

### ISSUE THREAD

**Issue by IfyNdu** [patchthecode/JTAppleCalendar#604]
This is an error I receive after deselectAllDates() is called.

![screen shot 2017-10-27 at 15 58 43](https://user-images.githubusercontent.com/15639127/32110601-d033a92e-bb2f-11e7-978d-32e59a77e26b.png)

**Comment by patchthecode** [comment]
version?

**Comment by IfyNdu** [comment]
Version 7.1.1
There is no error text just: THREAD: EXC_BAD_ACCESS

**Comment by patchthecode** [comment]
Alright. I'll look into this over the weekend. 
The project has become larger, i need to update my unittests to prevent these silly mistakes.
Thanks for finding.

**Comment by IfyNdu** [comment]
No worries bro, i'll revert to a previous version for the time being.
Thanks a lot

**Comment by patchthecode** [comment]
ok i finally have a chance to look at this.
I could not recreate the crash.
I wish you can tell me what you did to recreate it?

**Comment by IfyNdu** [comment]
Might be tricky to explain, maybe you could jump on my system (screenshare) for a sec?

**Comment by patchthecode** [comment]
sure, this is my timeZone.
Let me know a time when youre available.

**Comment by IfyNdu** [comment]
Thanks. i'm 7 hours ahead of you.
I'll message you as soon as i get home at about 2pm your time zone.

**Comment by patchthecode** [comment]
@IfyNdu man, im still @ work sadly.
I'll be free in about 4 hrs.

**Comment by IfyNdu** [comment]
Oh okay. I should be up still.

Let me know when you get off work

**Comment by patchthecode** [comment]
https://gitter.im/patchthecode/JTAppleCalendar when ready
