### ISSUE TITLE
[Carthage]uncaught exception of type NSException.

### ISSUE THREAD

**Issue by tanwanjern** [patchthecode/JTAppleCalendar#606]
I'm using 7.1.1 version and install it via carthage. I'm getting this error: libc++abi.dylib: terminating with uncaught exception of type NSException. 

This is my project file:
[FinnTest2.zip](https://github.com/patchthecode/JTAppleCalendar/files/1429460/FinnTest2.zip)

I followed the carthage installation and scratch tutorial from youtube but I got the error so I search it on Issues and found this https://github.com/patchthecode/JTAppleCalendar/issues/375 

After that, I changed some code by following the zip file but get Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) on calendarView.calendarDelegate = self

Sorry for asking the same issues.

**Comment by patchthecode** [comment]
Did you put in the module as `JTAppleCalendar` ?
<img width="261" alt="screen shot 2017-10-31 at 12 04 51 am" src="https://user-images.githubusercontent.com/2439146/32211307-235adc20-bdcf-11e7-90ef-f4d072303386.png">

**Comment by tanwanjern** [comment]
It works! Thanks!
