### ISSUE TITLE
Why willDisplay cell is not called

### ISSUE THREAD

**Issue by dastanbb** [patchthecode/JTAppleCalendar#607]
Hi! 
First of all, thank you for the great UI component! 
Version 7.1.1
I don't understand why **willDisplay cell** function is not called? In demo app it is mentioned that we should duplicate the code from **cellForItemAt**. Could you please explain this? 
Regards,
Dastan

**Comment by patchthecode** [comment]
I explained it on this issue -> https://github.com/patchthecode/JTAppleCalendar/issues/553
Does this help ?

**Comment by dastanbb** [comment]
Thank you! This explains pretty much everything.

**Comment by patchthecode** [comment]
Also, here is when the function is called. In the rare case when the library needs updating.
If it is not implemented you will get this rare error -> https://github.com/patchthecode/JTAppleCalendar/issues/608

Cheers 🍻

**Comment by Mansi4481** [comment]
hi I have the same problem occurring. willDisplay is not getting called here

Version : 'JTAppleCalendar', '~> 7.1'
Code:

extension CalenderTimesheetVC: JTAppleCalendarViewDelegate {
    public func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! DateCell
        self.configureCell(view: cell, cellState: cellState)
    }
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
        self.configureCell(view: cell, cellState: cellState)
        return cell
    }
}
