### ISSUE TITLE
Option to check if ThisMonthOutsideBoundary?

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#61]
Is there an option I am missing to simply disable selection on cells if the date is outside the given calendar boundaries, but inside the current month? I am currently checking against the maxDate and minDates that I pass into configure.

**Comment by patchthecode** [comment]
[Look at the wiki here on question # 1](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions). It explains how you can do that

**Comment by krisanthony** [comment]
It looks like I can check if the date belongs to the current displayed month, the next month outside boundary or previous month outside boundary, but not current month outside boundary. Am I missing something?

**Comment by patchthecode** [comment]
OK. What kind of date are you trying to check for?

Inside boundary = the boundary you have set when you configured the calendar. So if a date falls inside the boundary, then it is within the range you have set.

OutsideBoundary = simply outside your boundaries. 

So let's say you set a range to be `Jan 1 2016` to `Dec 31 2016` then everything within that range would be inside the boundary.  Outside the boundary would be `Dec 2015` (which would only be shown on January 2016 month) and `Jan 1017` (which will only be shown on the Dec 2016 month).

Maybe if you tell me what you're trying to accomplish I can help better?

**Comment by krisanthony** [comment]
How would you check for a date that is in .ThisMonth and inside the boundary?

**Comment by patchthecode** [comment]
.ThisMonth is by definition inside your start end boundary. Have you checked out [the tutorial](https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial) yet? It demonstrates how you can use these properties to configure the different parts of the calendar.

If youre still unclear, let me know.

**Comment by krisanthony** [comment]
Is that true? When I use .ThisMonth it seems to mean any date that is displayed in the current month, not taking into account the boundaries set in configureCalendar.

**Comment by patchthecode** [comment]
ok Let me check this now. Btw, i check my messages and 15-30 mins. So do respond quickly if youre there :)

**Comment by patchthecode** [comment]
Mine works perfectly.
Heres what. Put this in your `didSelect` delegate

```swift
func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {
    print(cellState.dateBelongsTo)
}
````
And look at the print out. Does it correspond to what you are expecting?

**Comment by krisanthony** [comment]
Nope, it is printing .ThisMonth even for dates in this month that are outside the boundary.

**Comment by patchthecode** [comment]
can you join here? -> https://gitter.im/patchthecode/JTAppleCalendar
i'm still not getting it :/ 
send me a message there. Chat here is too slow.

**Comment by patchthecode** [comment]
questions resolved in chat.

**Comment by PedroAnibarro1** [comment]
Hey @patchthecode! So, the dateBelongsTo it's supposed to be .thisMonth only if it is inside my startDate/endDate boundaries right? It is giving me .thisMonth for every cell and not the ones I specified inside the startDate/endDate boudaries.

**Comment by patchthecode** [comment]
@PedroAnibarro1 

no.
here are all of them


Every date on a month has a description:
It either belongs to:
```swift
        thisMonth,
        previousMonthWithinBoundary,
        previousMonthOutsideBoundary,
        followingMonthWithinBoundary,
        followingMonthOutsideBoundary
```

<img width="200" alt="calendararchitecture" src="https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png">
