### ISSUE TITLE
Cell deselect not working after calendarView.selectDates

### ISSUE THREAD

**Issue by sl-62** [patchthecode/JTAppleCalendar#610]
Affected versions: **7.1.0** and **7.1.1**

After programmatically selecting dates using the **calendarView.selectDates** method, the **shouldDeselectDate** delegate method does not appear to work when the user presses on one of the selected dates. Instead the **shouldSelectDate** method appears to be called again.

As a result, it's not possible to deselect the programmatically selected dates.
It looks similar to this previous bug: https://github.com/patchthecode/JTAppleCalendar/issues/67

**Update:**
Sorry just noticed this issue was already posted, not sure how I completely missed it: https://github.com/patchthecode/JTAppleCalendar/issues/609
Although I haven't had any problems with the shouldDeselectDate method when the user selects and then deselects dates. Only when programmatically selecting and then user trying to deselect.

**NB The issue does not appear to affect version 7.0.6.**

**Comment by patchthecode** [comment]
are you available?
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by sl-62** [comment]
Ok I think I've narrowed it down to what's causing the problem. Essentially issue happens when I call the following method in my viewWillAppear:
```
DispatchQueue.main.async {
    self.calendarView.reloadData()
}
```
Let me know whenever you're available to continue discussing this on gitter.

**Comment by patchthecode** [comment]
[Here is my time zone](https://www.timeanddate.com/time/zone/usa/california) 
Im usually up during the day.
I'll take a look into what you have found in the mean time however.

**Comment by patchthecode** [comment]
I got you app by email, but i am unsure of how to replicate what  you need me to see.
Send me message when youre available to talk.

**Comment by patchthecode** [comment]
Nice bug.
Had to find.
Fixing now 🍻

**Comment by patchthecode** [comment]
Can you open your `Podfile`and replace the jtapplecalendar with this?
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```
Then do a `pod update` on terminal. Let me know if this latest master branch fixes your bug.

**Comment by sl-62** [comment]
Perfect!
Thank you for fixing this bug so quickly. The related secondary bug also appears to be fixed now.
And a massive thank you in general for creating such an amazing library!
