### ISSUE TITLE
Creating calendar causes unreadable cells in column view

### ISSUE THREAD

**Issue by chriseenberg** [patchthecode/JTAppleCalendar#611]
Swift version 4.0
Target version: IOS 11.0
JTAppleCalendar version 7.1.1

I've followed the guide for creating a calendar in my project. This is "working" without errors in the console - however, there is a problem with displaying the cells in my collection view as seen below.

<img width="416" alt="screen shot 2017-11-06 at 12 45 16" src="https://user-images.githubusercontent.com/13994371/32439804-ad9ab6e6-c2f0-11e7-8dc8-a7c1024a49eb.png">

To be honest, i have no idea what is causing this. I've implemented the stub methods as suggested in the github post [here](https://github.com/patchthecode/JTAppleCalendar/issues/553). Everything is running with no errors, but still the view seems squashed..

i've used the date range:
`let startDate = dateFormatter.date(from: "2017 01 01")!
let endDate = dateFormatter.date(from: "2017 12 31")!`

Anyone got any pointers to what could be causing this? Is it a bug or am i missing something?

I can provide more code or information if you ask for it ( as i have no clue where to start )

Kind Regards Chris.

**Comment by patchthecode** [comment]
I take it that you found the error causing this?

1. This library has example project attached to it.
2. Also there are video tutorials --> [here](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)
3. Also there are guys who have done sample projects around -> https://github.com/patchthecode/WLAppleCalendar

Let em know if this helps
