### ISSUE TITLE
Crash from xib

### ISSUE THREAD

**Issue by RiuHDuo** [patchthecode/JTAppleCalendar#612]
layout is not init why should you convert to protocol
![image](https://user-images.githubusercontent.com/830134/32479503-bb623b64-c34f-11e7-8c8a-3de571d89769.png)

**Comment by patchthecode** [comment]
Do you have sample application?

**Comment by patchthecode** [comment]
Closing this until user provides more information.

If you need an example -> https://github.com/patchthecode/CalendarTutorial

**Comment by RiuHDuo** [comment]
i find the problem.  i must use collectionview inherit JTAppleCalendar. don't use uiview
