### ISSUE TITLE
Getting date from cellState gives date - 1 day

### ISSUE THREAD

**Issue by chriseenberg** [patchthecode/JTAppleCalendar#613]
1. Swift 4.0
2. 7.1.1

I've followed the videos as explained, and all this works great! Thanks for the easy access to your library.

I have, however, encountered a problem with getting dates out of the calendar again. I've implemented a method on the didselectdate method, where it pushes the selected date to a date array. This works well, but when i print the array of values, it printes this:

>[2017-11-07 23:00:00 +0000, 2017-11-08 23:00:00 +0000, 2017-11-09 23:00:00 +0000, 2017-11-10 23:00:00 +0000]

instead of the actual values which is 2017-11-08, 2017-11-09 etc..
I've setup the dateformatter like so:
```swift
        dateFormatter.dateFormat = "yyyy-MM-dd"
        dateFormatter.timeZone = Calendar.current.timeZone
        dateFormatter.locale = Calendar.current.locale
```
But it still seems to take into account some sort of time zone difference, or lack thereof.

Am i missing something here in the use of the calendar?

I'm ready to give more information if needed.

Kind regards Chris

**Comment by patchthecode** [comment]
Yes, this is an iOS thing. It happens with any iOS calendar library you use.
When ever you print a date to the console. Always use a date formatter to do so.
let me know if this issue here explains it for you? -> https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
you're welcome. 🍻
