### ISSUE TITLE
Delegate Methods - didSelectDate and didDeselectDate

### ISSUE THREAD

**Issue by ymanjuy** [patchthecode/JTAppleCalendar#614]
Version Number : v7.0

Hello first of all I would like to say thank you so much for providing this library. Its very easy to understand and work with it.

Everything was working fine. I tried the library in demo project. It was working fine in demo project. The same code I added to my project. Its loaded perfectly and design is looking as I planned. But the problem is with **didSelectDate** and **didDeselectDate** delegate methods. I have used four delegate methods, namely cellForItemAt, didSelectDate, didDeselectDate & didScrollToDateSegmentWith. The cellForItemAt and didScrollToDateSegmentWith are getting called. But when I select and deselect the above methods are not getting called. So can you please tell me what are the possible things which are causing this problem.

Thanks in advance.

**Comment by patchthecode** [comment]
you know, one of the easiest way to make an error is when people copy code (even if its copied code from a sample project).

Can you try creating a new calendar in your new project? You dont have to go all out and design, just design it enough to see if your didSelect is being called. The didSelect/deselect functions are working on my end. Creating just a sample calendar shouldnt take long since you are just gonna build enough to see if didSelect gets called.

Also, note, the latest version is 7.1.2
Let me know.

**Comment by ymanjuy** [comment]
Sure! I will try! I will let you know asap! Thank you so much for quick response.

**Comment by patchthecode** [comment]
latest is now 7.1.3
Fixed an issue.
closing this issue now.
Let me know if you still encounter any problems.

**Comment by ymanjuy** [comment]
Hey bro! Tried as you said. But no luck. Its working on the other project. In origional project its not at all working. DidSelectDate is not getting called!!

**Comment by patchthecode** [comment]
can you paste both functions?

**Comment by ymanjuy** [comment]
extension ViewController: JTAppleCalendarViewDelegate {
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        cell.dateLabel?.text = cellState.text
        
        handleCellSelected(cell: cell, cellState: cellState)
        handleCellTextColor(cell: cell, cellState: cellState)
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(cell: cell, cellState: cellState)
        handleCellTextColor(cell: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(cell: cell, cellState: cellState)
        handleCellTextColor(cell: cell, cellState: cellState)
    }
}

And function handleCellSelected is : 

func handleCellSelected(cell: JTAppleCell?, cellState: CellState?) {
        guard let validCell = cell as? CustomCell else { return }
        if validCell.dateLabel?.textColor == notAvailableDatesColor || validCell.dateLabel?.textColor == outsideMonthColor {
            return
        }
        if validCell.isSelected {
            validCell.selectedView?.isHidden = false
        } else {
            validCell.selectedView?.isHidden = true
        }
    }

**Comment by patchthecode** [comment]
hmm. your code looks good.
Is it possible you can join the chat here?
I'll be up.

**Comment by ymanjuy** [comment]
Sure! I m ready.

**Comment by ymanjuy** [comment]
On my Parent View Controller, I wrote these lines.

let tap = UITapGestureRecognizer(target: self.view, action: #selector(UIView.endEditing(_:)))
self.view.addGestureRecognizer(tap)

So, these lines were causing problem.

Thanks for your responses bro..!

**Comment by patchthecode** [comment]
ok. cool.
good the problem was figured out.
