### ISSUE TITLE
version 7.1.3 want to know what willDisplay is used for 

### ISSUE THREAD

**Issue by ruwaldl** [patchthecode/JTAppleCalendar#616]
what willDisplay is used for ?

what is cellForItemAt used for ?

**Comment by patchthecode** [comment]
`cellForItemAt` is used the same way as any other UICollectionView or UITableView in iOS.
The video list located here will help you on this -> https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q

`willDisplay` was newly introduced in version 7.1.0. It should contain the same code as the `cellForItemAt` function. The reason why it was implemented and what you need to put in it is explained here -> https://github.com/patchthecode/JTAppleCalendar/issues/553

Let me know if this helped.
