### ISSUE TITLE
Retain Cycle - How can I avoid it.

### ISSUE THREAD

**Issue by thelittlelankanprince** [patchthecode/JTAppleCalendar#619]
Using the latest version. 

I am using your awesome library to create a query band of dates and on selecting (or deselecting) a specific date it fires a query (I am not sure if this is bad design, but it seems to work okay). I am then using a dictionary to count iterations of objects relative to a specific date, which I then want to use to update an array in the collection view. I was wondering how I could update the cells without firing the didselect/diddeselect methods? 

I am using the cal in a UIView that is in a VC. 

Thanks for all your hard work.

**Comment by patchthecode** [comment]
@thelittlelankanprince 
`calendarView.reloadData()` will reload your calendar.
Does it work when you use this?

**Comment by patchthecode** [comment]
Join chat [here](https://gitter.im/patchthecode/JTAppleCalendar) if more help is needed

**Comment by thelittlelankanprince** [comment]
@patchthecode it's just a circular reference. i have an array of objects that updates based on dates being selected or not selected (dates array), but before you select a date i want to identify the quantity of each object per date and then update the cells. The problem is when I update the cells (with reloadData() ) it triggers cell selection even though the cells are not being selected or deselected - I can just a add a view below and update that, but I would rather have the quantity dots on the date cell itself.

**Comment by patchthecode** [comment]
problem resolved with reloadDates() function.
closing this issue
but @thelittlelankanprince please send files to patchthecode@gmail.com
will resolved reloadData()
