### ISSUE TITLE
v7.1.3 How to jump back and forth via years?

### ISSUE THREAD

**Issue by daviddelmonte** [patchthecode/JTAppleCalendar#621]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.3
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hi, this is an amazing work. I have figured how to jump back and forth using month buttons. How would you (or anyone), suggest I implement a control to jump the calendar back or forward by a year?

Many thanks!

**Comment by patchthecode** [comment]
@daviddelmonte 
1. get the current year youre on.
2. generate a date to the 1st of the following year
3. calendarView.scrollToDate(date)

**Comment by daviddelmonte** [comment]
Thanks.. That's great for one year plus or minus.. I need +- 5-10 years..

**Comment by patchthecode** [comment]
@daviddelmonte

1. get the current year youre on.
2. generate a date to the 1st of the next 5 years
3. calendarView.scrollToDate(date)


You can add how much ever years you want. And your code can be anyway you want. Here is an ugly example.
```swift
        guard let anyVisibleDate = calendarView.visibleDates().monthDates.first?.date else { return }
        let calendar = Calendar.current
        let year = calendar.component(.year, from: anyVisibleDate)
        let fiveMoreYears = year + 5
        
        let formatter = DateFormatter()
        formatter.calendar = calendar
        formatter.timeZone = calendar.timeZone
        formatter.dateFormat = "yyyy MM dd"
        let firstDateOfNextFiveYears = formatter.date(from: "\(fiveMoreYears) 01 01")
        print(firstDateOfNextFiveYears)
```

**Comment by daviddelmonte** [comment]
Thanks!! I ended up having a variable that the buttons would increment during a run. I can use that to add/subtract a year at a time..

**Comment by patchthecode** [comment]
cool

**Comment by daviddelmonte** [comment]
Sorry, I should have posted my code...

aYear is an Int..

Code is:
```

   @IBAction func nextYear(_ sender: Any) {
        self.aYear = self.aYear + 1
        //let nextYear = Date().nextYear + aYear
        let nextYear = Calendar.current.date(byAdding: .year, value: aYear, to: Date())
        calendarCollectionView.scrollToDate(nextYear!, animateScroll: true)
       
    }
    
    @IBAction func previousYear(_ sender: Any) {
        self.aYear = self.aYear - 1
        let previousYear = Calendar.current.date(byAdding: .year, value: aYear, to: Date())
        calendarCollectionView.scrollToDate(previousYear!, animateScroll: true)
        
    }
```
