### ISSUE TITLE
didSelectDate date and cellState date is different

### ISSUE THREAD

**Issue by jackywongcw** [patchthecode/JTAppleCalendar#622]
Using the latest version: 7.1.3
Test Device : iOS 9

In     
```
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        print(" selected date = ", date) // prints: selected date =  2017-11-06 16:00:00 +0000
        print("cellstate text = ", cellState.text) // prints: cellstate text = 7
}
```
why are they not the same? is it because of timezone?

for the `configureCalendar` parameter, use:
```
        let parameter = ConfigurationParameters(startDate: formatter.date(from: "2017 01 01")!,
                                                endDate: formatter.date(from: "2017 01 01")!,
                                                numberOfRows: numberOfRows,
                                                generateOutDates: .tillEndOfRow)
        
        return parameter
```

formatter is the same setup as per your tutorial
numberOfRows = 1

Can you please check if you're able to replicate this problem?

**Comment by patchthecode** [comment]
Let me know if this discussion is helpful to you -> https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by jackywongcw** [comment]
Yep. Thanks for the reference. Looks like quite a number of people had the same issue before, my bad for not searching long enough.
Perhaps you can point this out in the tutorial / front page? 

Also, what is the purpose of the "date" and "cellState" parameter in didSelectDate / cellForItemAt? What's the initial intention for it?
AFAIK, date and cellState.date returns the same exact date (before the formatter).

**Comment by patchthecode** [comment]
date = cellState.date

originally, the library just had `date`.  Eventually, i added cellState because there are many other things that that were useful to developers. I didn't want to remove `date` since so many were using it. Therefore, I left `date` there for easy access as this variable was the most accessed. I may consider removing it in future, and just keeping every thing inside cellSate.

**Comment by jackywongcw** [comment]
I see. 
Thanks again for your time taken to reply and your awesome library!

Case close. :)
