### ISSUE TITLE
reloadData unowned reference crash

### ISSUE THREAD

**Issue by hennykat** [patchthecode/JTAppleCalendar#624]
JTAppleCalendar Version: 7.1.3
Swift 4 / XCode 9.1

Crash in: UserInteractionFunctions.swift > reloadData(withAnchor:completionHandler:)
Log: Fatal error: Attempted to read an unowned reference but the object was already deallocated

<img width="1141" alt="screen shot 2017-11-15 at 1 29 56 pm" src="https://user-images.githubusercontent.com/10837699/32856302-06ea3c7e-ca0a-11e7-99f0-a9356c5716e0.png">

Steps to reproduce: 
1. Calendar is created (User navigates to calendar UI where CalendarView nib containing JTAppleCalendar is loaded into view)
2. Calendar is destroyed (User triggers hard UI refresh, removing CalendarView nib from view and deallocating)

*Not consistently reproducible, but has been seen 3 times in the past few days
Presumably, this is occurring because the calendar is destroyed before the calendar reload completion is executed.

**Comment by patchthecode** [comment]
hmm. this is bad. Do you have a sample application that contains this issue?
I would really like to get my hands on that to fix immediately.

**Comment by hennykat** [comment]
Unfortunately I don't have a sample application.  I can try to make one if you need

**Comment by patchthecode** [comment]
Yea. i caught up on another project. I can take a look at this at the least in another 4-5 days.
But if you provide a sample app with it, i can look at it a lot sooner.

**Comment by patchthecode** [comment]
But i already see a fix.
it should be set to `weak` instead of unowned.
I did not foresee your use-case. Weak, will make it nillable and thus it would not crash if its no longer available.

**Comment by hennykat** [comment]
Okay, I will make a sample and get back to you

**Comment by hennykat** [comment]
I can't seem to make a sample application where this is consistently reproducible.  Not sure where to go from here.

**Comment by patchthecode** [comment]
@hennykat its ok, just send the sample app.
I will look through it and judge. I already suspect where it is, your sample app, will help.

**Comment by hennykat** [comment]
Sorry, I already put it up by the time I read this.  Hope this is ok: https://github.com/hennykat/CalendarSample

**Comment by patchthecode** [comment]
ok, i'll check it out over after work.

**Comment by patchthecode** [comment]
replace this in your `Podfile` and do a `pod install`
```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

Let me know if your bug is resolved

**Comment by hennykat** [comment]
The bug seems to be resolved!  I have yet to see the crash happen again.  
Will this change be in the 7.1.5 release?

**Comment by patchthecode** [comment]
yes, it will be in version 7.1.5 once i release it.

**Comment by JettF** [comment]
I ran into this bug as well. Thanks for fixing it. I am actively developing a feature right now, so relying on Master is fine. Looking forward to the 7.1.5 release!

**Comment by patchthecode** [comment]
7.1.5 released
