### ISSUE TITLE
Convert date representation from horizontal to vertical.

### ISSUE THREAD

**Issue by rinkon** [patchthecode/JTAppleCalendar#625]
Hello there,
Thank you for the awesome library. 
I am using 7.0.

I am trying to represent days like the image. Is there any way to do that?

![untitled](https://user-images.githubusercontent.com/7296621/32879613-e2a71c94-cad4-11e7-8ec7-64400c4ef3b8.jpg)

Thanks in advance

**Comment by patchthecode** [comment]
It can create any calendar so long as it is standard. The one you have shown cannot be done.

**Comment by patchthecode** [comment]
closing issue. Hope this helped.
