### ISSUE TITLE
Implementation Issue

### ISSUE THREAD

**Issue by jdkauffman11** [patchthecode/JTAppleCalendar#626]
Hi,

This is probably trivial compared to the other issues here, but I have tried everything I could think of to get this to work and am unable. I have been trying to implement this calendar functionality in an app that I am working on, and I have been following the tutorial [here](https://patchthecode.github.io/MainTutorial/).

I believe to have everything hooked up correctly, but when I segue to this view controller, my application crashes. It crashes on the first line of viewDidLoad() with an error that says Thread 1: EXC_BAD_ACCESS.

I am using the latest version, 7.1.3. The app is using swift 4, and I am running Xcode 9.1.

When I was working on adding the calendar to my project, I noticed a few discrepancies between the tutorial and what Xcode would allow me to do.

One was that JTAppleDayCell was not found, so I switched it to JTAppleCell instead.

Inside the `viewDidLoad()`, calendarView's dataSource and delegate were not available so I used 
```
calendarView.calendarDataSource = self
calendarView.calendarDelegate = self
```

The way that the tutorial registered a cell was also not available (registerCellViewXib) so I used `calendarView.register(UINib(nibName: "DateCell", bundle: nil ), forCellWithReuseIdentifier: "DateCell") `(I renamed my cell 'DateCell' instead of 'CellView')

Finally there were two functions that it required me to implement, and I just implemented them to the point where the project would build. They are as follows:
```
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
}
```
```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell: DateCell = JTAppleCell() as! DateCell
        
        return cell
    }

```

As far as UI, I believe that it is all set up correctly. I have a blank view inside of a view controller and the class for the view is set to JTAppleCalendarView, and the view controllers class is set to my 'SchedulingViewController' which is where I have implemented all of the code from the tutorial.

I set the class for the cell xib as Date Cell which is what I named my custom cell.

If I was going to make a guess, I would bet that one of the changes that Xcode wanted me to make or one of the guesses I made on how something changed is what is causing the app to crash, but any help is appreciated. I will attach the code so that you can see what my class looks like.

I apologize in advance if I made a stupid or obvious mistake. I tried to follow the tutorial as closely as I could, but it seems that some changes were made since it was written.

SchedulingViewController:
```
import UIKit
import JTAppleCalendar
class SchedulingViewController: UIViewController, JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
    
    @IBOutlet weak var calendarView: JTAppleCalendarView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        calendarView.calendarDataSource = self
        calendarView.calendarDelegate = self
        calendarView.register(UINib(nibName: "DateCell", bundle: nil ), forCellWithReuseIdentifier: "DateCell")
        //calendarView.center = CGPoint(x: 0, y: 0)
        
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        
        let cell: DateCell = JTAppleCell() as! DateCell
        
        cell.dateLabel.text = ""
        
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell: DateCell = JTAppleCell() as! DateCell
        
        cell.dateLabel.text = ""
        return cell
    }
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        
        let startDate = formatter.date(from: "2016 02 01")! // You can use date generated from a formatter
        let endDate = Date()                                // You can also use dates created from this function
        let calendar = Calendar.current                     // Make sure you set this up to your time zone. We'll just use default here
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6,
                                                 calendar: calendar,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfGrid,
                                                 firstDayOfWeek: .sunday)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplayCell displayCell: JTAppleCell, date: Date, cellState: CellState) {
        let cell = displayCell as! DateCell
        
        // Setup Cell text
        cell.dateLabel.text = cellState.text
        
        // Setup text color
        if cellState.dateBelongsTo == .thisMonth {
            cell.dateLabel.textColor = UIColor(colorWithHexValue: 0xECEAED)
        } else {
            cell.dateLabel.textColor = UIColor(colorWithHexValue: 0x574865)
        }
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
}

extension UIColor {
    convenience init(colorWithHexValue value: Int, alpha:CGFloat = 1.0){
        self.init(
            red: CGFloat((value & 0xFF0000) >> 16) / 255.0,
            green: CGFloat((value & 0x00FF00) >> 8) / 255.0,
            blue: CGFloat(value & 0x0000FF) / 255.0,
            alpha: alpha
        )
    }
}
```

DateCell:
```
import JTAppleCalendar
class DateCell: JTAppleCell {
    @IBOutlet weak var dateLabel: UILabel!
    
}
```
![1](https://user-images.githubusercontent.com/6621641/32915119-784bdeb2-cadd-11e7-8088-8cf6c2ff504b.png)
![2](https://user-images.githubusercontent.com/6621641/32915120-7861beda-cadd-11e7-8016-5443c8ea9c10.png)
![3](https://user-images.githubusercontent.com/6621641/32915121-787652fa-cadd-11e7-899f-e4208e626808.png)

**Comment by patchthecode** [comment]
Hmm. Sorry, if you are using version 7.0 you are using the wrong tutorials.
Have you seen any of the video tutorials posted on this site?

Here [is the full list](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q).

There is also an update to the videos posted there. The latest version 7.1.3 has an extra function you need to implement (not posted in the videos). It is explained here -> #553 
The function is called `willDisplayCell`

Let me know if these helped. 
If you need questions answered write away, then ask here -> https://gitter.im/patchthecode/JTAppleCalendar

If i'm not asleep

**Comment by jdkauffman11** [comment]
Awesome, the video really helped! I was able to get it running. Thanks so much for your quick reply!

**Comment by patchthecode** [comment]
awesome 🍻
