### ISSUE TITLE
unable to deselect a selected date cell

### ISSUE THREAD

**Issue by shoujs** [patchthecode/JTAppleCalendar#627]
Every time, I select a date which is in the selected state, I mean to deselect it. But the `didDeselectDate` not get invoked, only `didSelectDate` get called. Is that behavior designed as is?

But I think deselecting a date if user select(press) a selected date cell makes more sense to me.

**Comment by patchthecode** [comment]
This is the default behavior of a UICollectionView for iOS. 

If you want you calendar to behave like what you have described, you need to set the following to `true`

```swift
calendarView.allowsMultipleSelection = true
```

**Comment by shoujs** [comment]
Thank you!  Just awared of this.

**Comment by ekchhuon** [comment]
Is it possible if don't need `allowsMultipleSelection` feature? My feature is single selection.

**Comment by ekchhuon** [comment]
> This is the default behavior of a UICollectionView for iOS.
> 
> If you want your calendar to behave like what you have described, you need to set the following to `true`
> 
> ```swift
> calendarView.allowsMultipleSelection = true
> ```
> 
> Let me know if this helps you.

Is it possible if don't need allowsMultipleSelection feature? In my case, my feature is single selection and I get stuck with it.

**Comment by artemlebedko** [comment]
@ekchhuon it can be not good implementation, but it helps me:

`func handleCellSelected(cell: DateCell, cellState: CellState) {
   calendarView.allowsMultipleSelection = cellState.isSelected ? true : false
}
`
