### ISSUE TITLE
Get the cell of current day

### ISSUE THREAD

**Issue by CassianoMouraLeao** [patchthecode/JTAppleCalendar#628]
I need to change the color cell of the current day. Can anyone help me?

**Comment by patchthecode** [comment]
This library is just like any regular UICollectionView. Therefore you'd do the same thing as you would for a collectionView.

in your `cellForItemAtIndexPath` function you have access to your cell.
Check the date to see if is the date that you want, and then configure your cell to suite.
Let me know if this resolves your issue. Closing this for now.
