### ISSUE TITLE
Selecting a date doesn't pull the correct month

### ISSUE THREAD

**Issue by kvw5288** [patchthecode/JTAppleCalendar#630]
I believe I am using version 7.0.6, and I have Swift 4.0. 

The calendar defaults to show January, so when I slide the calendar to February, or any other month, and select a date, it always pulls in January as the month. For example, selecting February 15th on the calendar view, returns January 15 for the label I placed. I remember this was not an issue before, so I am wondering if this was something due to a new version being released.

**Comment by patchthecode** [comment]
Did you recently update to a new version when this issue started happening?

Also note, that the latest version is `7.1.4`
Can you let me know what you have in your `Podfile` for JTAppleCalendar?

For faster reply, join chat here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by kvw5288** [comment]
I just noticed this issue happening. I haven't done anything to change the code for this calendar. Would upgrading to 7.1.4 potentially fix this? I am just not sure where in the code does it recognize that I am changing the month.

In my Podfile, I have: pod 'JTAppleCalendar', '~> 7.0'

**Comment by patchthecode** [comment]
Did you create a new project and copy code or something?
It is not possible that it something changes with absolutely no code changes at all.

When you tap on the say `Feb 16th` you say that what is printed is `Jan 16th`?
Can you paste the code you have for printing the wrong date you are seeing?

**Comment by kvw5288** [comment]
I just watched your video and put the code into my project (about 2 months ago). And correct, if I tap on Feb 16th, what is printed is Jan 16. 

Here is my didSelectDate function

 func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {

        handleCellSelected(view: cell, cellState: cellState)
        handleCelltextColor(view: cell, cellState: cellState)
        let str = date.description
        let index = str.index(str.startIndex, offsetBy: 10)
        let tempDate = str.substring(to: index)
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-mm-dd" //yyyy-mm-dd
        dateObj = dateFormatter.date(from: tempDate)!
        dateFormatter.dateFormat = "MMM d, yyyy"
        dateValue = dateFormatter.string(from: dateObj)
        print("datevalue is: \(dateValue)")
        dateLabel.text = dateValue
        calView.isHidden = true
        count = count + 1
    }

**Comment by patchthecode** [comment]
hmm.. that code looks a bit suspect.
why not just have this?
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCelltextColor(view: cell, cellState: cellState)
        dateFormatter.dateFormat = "MMM d, yyyy"
        dateValue = dateFormatter.string(from: date)
}
```

**Comment by kvw5288** [comment]
I have the extra code to format the output, and to display the calendar based on the press of a button.

Where in the code is it configured so that the datevalue in the didSelectDate knows which month view was selected? I think the issue might lie in that part.

**Comment by patchthecode** [comment]
if you just print the `date` from the `didSelect` function without any formatting, is the date still incorrect?

**Comment by patchthecode** [comment]
considering issue resolved.
It looks like developer code formatting incorrectly.
