### ISSUE TITLE
Cannot load underlying module for 'JTAppleCalendar'

### ISSUE THREAD

**Issue by nstandage** [patchthecode/JTAppleCalendar#631]
Using 7.1.4

Every time I try and import JTAppleCalendar into a swift file I get this error: 

Cannot load underlying module for 'JTAppleCalendar'

Everything installed fine, though I did get this error while installing it even though I have a platform specified:

[!] Automatically assigning platform ios with version 11.1 on target [App Name] because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

I've tried updating and reinstalling, but nothing is working.

**Comment by patchthecode** [comment]
sounds like youre having some cocoapod problems.
The best guide would be on their cocoapod website.

it terms not not loading the module.
Can you take examples from the example code found here? -> https://github.com/patchthecode/CalendarTutorial

**Comment by Frankenstein666** [comment]
I had the same issue, restarting Xcode resolved the issue for me. give it a shot once.

**Comment by nstandage** [comment]
I updated gem, restarted my computer, and it's all working now. Thanks.
