### ISSUE TITLE
Change de backgroundcolor of cell when other cell is selected

### ISSUE THREAD

**Issue by CassianoMouraLeao** [patchthecode/JTAppleCalendar#632]
Hey!
I am trying to change the backgroundcolor of cell when I select other. For example: 
```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        guard let validCell = cell as? CustomCell else{ return }
        validCell.backgroundColor = .white
} 
```

When I touch in cell at November 20 I need to change the backgroundcolor of cell at November 23, 24 and 25.

Anyone can help me?

**Comment by patchthecode** [comment]
The best place to find all the functions that this library can do is in the `UserInteractionFunctions,swift` file.

There is a function there called 
```swift
public func cellStatus(for date: Date) -> CellState?
```

**Comment by CassianoMouraLeao** [comment]
Maybe the method `public func cellStatus(at point: CGPoint) -> CellState? {` resolve it. But how I call this method in my UIViewController?

**Comment by patchthecode** [comment]
Assuming issue is resolved. If not, then reply here.
Closing here.
