### ISSUE TITLE
Trouble deselecting indates and outdates when calendar scrolls

### ISSUE THREAD

**Issue by jdkauffman11** [patchthecode/JTAppleCalendar#633]
When I select the last day of a month, then scroll to the next month, the correct day is shown as selected. However when I select another day, the previous cell appears to remain selected. I have traced this issue to the calendar's didDeselectCell function where the cast `guard let validCell = cell as? DateCell else {return}` appears to fail. If I remove the guard, I can fall through the function but the cell is optional and nil so it doesn't allow me to "deselect" it.

Is there any reason that the cast would fail? The indates and outdates should still be castable to my custom DateCell which implements JTAppleCell. The rest of the functionality works great, its only when I scroll to the future on a selected indate or scroll to the past on an outdate.

Maybe there is another way that I can hide that cell's view?
Any advice is appreciated, Thanks!

**Comment by patchthecode** [comment]
did you implement the willDisplayCell function as shown here? #553

**Comment by jdkauffman11** [comment]
That did indeed solve my problem. I do remember reading that now that you linked it, but I guess I forgot. I appreciate your help and your amazing response time!

**Comment by patchthecode** [comment]
cool. and thanks.
