### ISSUE TITLE
prepare forSegue called before displayForSelectedCell

### ISSUE THREAD

**Issue by nstandage** [patchthecode/JTAppleCalendar#635]
Using 7.1.4

I'm not sure if there's a better place to ask this, but I can't find anywhere else to.
I'm trying to update selectedCellState in my mainVC as soon as displayForSelectedCell is called, so I can then pass it into prepare forSegue. The problem I'm having is that when a cell is selected, prepare forSegue is called before displayForSelectedCell, so the cellState in my secondaryVC gets set to the previous selectedCell.
I think I may be using the wrong method for this (displayForSelectedCell), but I can't find another method that's called before prepare forSegue when a cell is tapped.

Below is a sudo layout of what I'm trying to do:

### mainViewController
**var** selectedCellState: cellState?

**func** displayForSelectedCell(cellState: CellState)
selectedCellState = cellState

**func** prepare(forSegue: segue)
secondVC.cellState = selectedCellState

### secondaryViewController
**var** cellState: cellState

**Comment by nstandage** [comment]
I also tried setting selectedCellState to cellState in didSelecteDate, but that also is called after prepare forSegue.

**Comment by patchthecode** [comment]
hi, this library does not have any function called `func displayForSelectedCell(cellState: CellState)`

Maybe you meant to  implement the `didSelect` function?

**Comment by nstandage** [comment]
Thanks for the help. I needed a manual segue, not one made through Interface Builder.
