### ISSUE TITLE
Crashing on part-deselection of a range of selected dates

### ISSUE THREAD

**Issue by Hendies567** [patchthecode/JTAppleCalendar#638]
We have a solution of your Calendar which had deselection and selection of dates working correctly. Recently, we've found that we cannot deselect mid-way through a range of selected dates.

The process is this:
1) Select a range of dates within the calendar (first date and last date set etc)
2) Click a date within the range (which sets the new last date to the date before the clicked date)

Our code is this (shouldDeselectDate):

```
func calendar(_ calendar: JTAppleCalendarView, shouldDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
        let selectedDates = calendar.selectedDates
        if let indexOfSelectedDate = selectedDates.index(of: date),
            indexOfSelectedDate + 1 < selectedDates.count {
            let datesToDeselect = Array(selectedDates[indexOfSelectedDate..<calendarView.selectedDates.count])
            calendar.selectDates(datesToDeselect)
        } 
        return true
    }
```

xCode returns Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffeee1c0e38)
<img width="768" alt="screen shot 2017-11-28 at 18 59 34" src="https://user-images.githubusercontent.com/26363840/33338621-853c8e74-d46e-11e7-95af-51c588b995dc.png">

Our project version on the 2nd of November (JTAppleCalendar version 7.1.1) worked perfectly with this range de-selection (and no code has been altered since that version).

Any help would be greatly appreciated!

**Comment by patchthecode** [comment]
checking this out.

**Comment by Hendies567** [comment]
Should've specified that in my post, we are currently using 7.1.4. The crash doesn't occur on 7.1.1

**Comment by patchthecode** [comment]
Thank you. Will look into this afterwork today.

**Comment by Hendies567** [comment]
Sorry about that! Thanks for looking into it

**Comment by patchthecode** [comment]
can you paste the code for indexOfSelectedDate ?

**Comment by Hendies567** [comment]
Thanks for looking into it, I've stuck the code into the original above

**Comment by patchthecode** [comment]
ok.
7.1.1 has a bug which was fixed in version 7.1.4
When ever you call the `calendarView.selectDates` function in 7.1.1 it supposed to call the `shouldDeselect` funciton, but it does not.

This has been corrected in version 7.1.4
Therefore when you call `calendarView.selectDates` in version 7.1.4, it calls correctly calls `shouldDeselect`. BUT in that function you again call `calendarView.selectDates` which causes an infinite loop in that function.

to fix it i added a way for you to know when a selection is done programatically or by the user.
therefore, fx your code to this
```swift
    func calendar(_ calendar: JTAppleCalendarView, shouldDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
        if cellState.selectionType == .userInitiated {
            let selectedDates = calendar.selectedDates
            if let indexOfSelectedDate = selectedDates.index(of: date), indexOfSelectedDate + 1 < selectedDates.count {
                let datesToDeselect = Array(selectedDates[indexOfSelectedDate..<calendarView.selectedDates.count])
                calendarView.selectDates(datesToDeselect)
            }
        }
       
        return true
    }
```

**Comment by Hendies567** [comment]
Fantastic! It's done the job 👍 thank you!

**Comment by patchthecode** [comment]
awesome. closing. I got another important scroll bug to fix.
Have a good one. 🍺
