### ISSUE TITLE
when i scroll in my calendar days start missing why is this 

### ISSUE THREAD

**Issue by ruwaldl** [patchthecode/JTAppleCalendar#643]
Hi see below  but when my calendar loads first time its 100% but as i scroll days keep going missing why is this ? 

![screen shot 2017-11-30 at 22 59 18](https://user-images.githubusercontent.com/18304249/33454680-3b753b50-d622-11e7-8d84-5b69fa48f793.png)
![screen shot 2017-11-30 at 22 59 31](https://user-images.githubusercontent.com/18304249/33454684-3eca44bc-d622-11e7-8515-98e8325a488e.png)
![screen shot 2017-11-30 at 22 59 02](https://user-images.githubusercontent.com/18304249/33454686-402d662c-d622-11e7-890e-d7a197c168db.png)

**Comment by patchthecode** [comment]
maybe your calendar is high?
¯\_(ツ)_/¯

**Comment by patchthecode** [comment]
haha.
just kidding.
Can you shoe me your code for your `cellForItem` function ?

**Comment by patchthecode** [comment]
I believe that you are not resetting your cells in that function.
Keep in mind the calendar is a UICOllectionView subclass.
Your cells are being re-used. Just like anyother UICollectionView / UITableView in swift, you have to reset your cells.

closing this issue. let me know if this resolved it.

**Comment by ruwaldl** [comment]
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState , indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarCell", for: indexPath) as! CustomCalendarCell
        cell.dateLabel.text = cellState.text
       handleCellSelected(view: cell, cellSate: cellState)
       handleCellColor(view:cell,cellSate: cellState)
        return cell
    }

**Comment by patchthecode** [comment]
what's in these 2 functions? 
```swift
       handleCellSelected(view: cell, cellSate: cellState)
       handleCellColor(view:cell,cellSate: cellState)
```

Here is the sample code of the examples by the way -> 
https://github.com/patchthecode/CalendarTutorial

**Comment by ruwaldl** [comment]
func handleCellColor(view:JTAppleCell?,cellSate:CellState)
    {
        
        guard let validCell = view as? CustomCalendarCell else {return}
        
        if cellSate.isSelected{
          validCell.dateLabel.textColor = UIColor.blue
        }
        else {
            if(cellSate.dateBelongsTo == .thisMonth){
                validCell.dateLabel.textColor = UIColor.black
            }else {
                validCell.dateLabel.isHidden = true
                
            }
            
       
    }
    }
    func handleBookedColor(view:UITableViewCell?,status:String)
    {
        guard let validCell = view as? SlotTableViewCell else {return}
        
        if status == "available" {
           validCell.bookingColor.backgroundColor = UIColor.green
        }
        else {
          validCell.bookingColor.backgroundColor = UIColor.red
            }
        }
    }

sorry these are what you are missing

**Comment by ruwaldl** [comment]
do i just do a simple reload of my collection view to rest the collection view ?  as you mentioned cant see that in code you provided . did some digging and found this method 
// For instance, it is not enough to only have the first if clause:
if date == someDate {
   configureCellViewInThisWay()
}
// You may also need the else clause to fully reset the cell because cells are being reused.
else {
   configureCellViewInThatOtherWay()
}
https://patchthecode.github.io/DateCellConfiguration/

**Comment by patchthecode** [comment]
```swift
validCell.dateLabel.isHidden = true
```

Where do you have `validCell.dateLabel.isHidden = false` ?

**Comment by ruwaldl** [comment]
i dont have a false . should it be in the else 
like this
if cellSate.isSelected{
      validCell.dateLabel.textColor = UIColor.blue
    }
    else {
        if(cellSate.dateBelongsTo == .thisMonth){
            validCell.dateLabel.textColor = UIColor.black
        }else {
            validCell.dateLabel.isHidden = true
            
        }
else{
    validCell.dateLabel.isHidden = false
}

**Comment by ruwaldl** [comment]
that false looked like it solved it thanks 
any idea how i would go about making past dates in the calendar not selectable but future and current date selectable . 
sorry about all the question still new
