### ISSUE TITLE
scrollToDate causes strange side offset

### ISSUE THREAD

**Issue by InnaChystiakova** [patchthecode/JTAppleCalendar#647]
In my viewDidLoad() I have such a line

`calendarView.scrollToDate(Date(), animateScroll: false)
`

When I load the calendar, I have UI bug as follows (screen below).
After starting to scroll the bug disappears.
I'm using the latest version.
Please, help me to fix it.

<img width="598" alt="2017-12-04 20 21 50" src="https://user-images.githubusercontent.com/9316391/33568958-c7b91e0e-d930-11e7-9c05-a02b8a45630f.png">

**Comment by patchthecode** [comment]
Hi, when saying that there is a bug, you have to also let me know what the bug is.
Because what might be a bug to you, mught be just fine to me.
Your image looks looks perfect. Where is the bug?

**Comment by patchthecode** [comment]
closing until user responds.
