### ISSUE TITLE
Namespace collision

### ISSUE THREAD

**Issue by aizatomar** [patchthecode/JTAppleCalendar#648]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.4
3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.

Version using is 7.1.4.

Unable to use library because there is a namespace collision. "CellState" public struct is clashing with another CellState struct declared elsewhere in the main project. Request to have a JT prefix for CellState public struct in this library. Not sure how much more information I should provide you since it is a common namespace collision problem. Let me know.

**Comment by patchthecode** [comment]
hmm. can you use the fully qualified name to avoid the collision?
`JTAppleCalendar.CellState`

**Comment by aizatomar** [comment]
Is it something like this?
```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: JTAppleCalendarView.CellState, indexPath: IndexPath) -> JTAppleCell
```

If so, I am getting this error
```
'CellState' is not a member type of 'JTAppleCalendarView'
```

**Comment by patchthecode** [comment]
i said `JTAppleCalendar.CellState`
not
`JTAppleCalendarView.CellState`

Let me know if it works

**Comment by aizatomar** [comment]
Ah sorry about that. Was using the autocomplete and there wasn't any autocomplete for `JTAppleCalendar`.

However wow! `JTAppleCalendar.CellState` works! I'll use this then. Thanks!

**Comment by patchthecode** [comment]
awesome. 
Closing this issue now.
