### ISSUE TITLE
How to add event every year like birthday?

### ISSUE THREAD

**Issue by pradeepispv** [patchthecode/JTAppleCalendar#650]
Is there any way to add event for every year in short like birthdays and national holidays?

**Comment by NSMyself** [comment]
You just need to come up with the cell layout you want and have an underlying model that contains the desired event dates. Then, in the cellForItemAt method, just customize the cell if the date matches the one of your event.

**Comment by patchthecode** [comment]
**NSMySelf** is correct. If you follow the video tutorial [HERE](https://www.youtube.com/watch?v=CQNotydm58s), it will show you an example of how events are handled.

**Comment by sarahtipton** [comment]
Hi - a lot of the links to the video tutorials are dead (like this one ^^). Is there somewhere I could see the older videos?
