### ISSUE TITLE
Delegate functions not called

### ISSUE THREAD

**Issue by mayqiyue** [patchthecode/JTAppleCalendar#653]
Environments:
Xcode 9.2
swift 4
JTAppleCalendar 7.1.4 from CocoaPods

codes: 
```swift
    private lazy var calendarView: JTAppleCalendarView = {
        var c = JTAppleCalendarView.init()
        c.register(JTDateDayCell.self, forCellWithReuseIdentifier: NSStringFromClass(JTDateDayCell.self))
        c.register(JTAppleCollectionReusableView.self, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: NSStringFromClass(JTAppleCollectionReusableView.self))
        c.scrollDirection = .horizontal
        c.scrollingMode = .stopAtEachSection
        c.cellSize = self.view.frame.size.width / 7.0
        c.minimumLineSpacing = 0
        c.minimumInteritemSpacing = 0
        c.calendarDelegate = self
        c.calendarDataSource = self
        return c
    }()
```
But the delegate methods:
```swift
    func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {
        let v = JTAppleCollectionReusableView.init(frame: CGRect.init(x: 0, y: 0, width: 100, height: 50))
        v.backgroundColor = UIColor.red
        return v
    }
    
    func sizeOfDecorationView(indexPath: IndexPath) -> CGRect {
        return CGRect.init(x: 0, y: 0, width: 100, height: 50)
    }

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This func not work.
    }
```
not called.

**Comment by patchthecode** [comment]
do you mean all 3 functions are not called? or only the 
```

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This func not work.
    }
```
 is not called?

Also what are you trying to accomplish which led you to the conclosion that it is not called? I can help better if i know the context of what you are trying to accomplish.

**Comment by mayqiyue** [comment]
Thanks for the reply.
All the 3 functions are not called.
Because I set break points on all the delegate functions but only the one: 

    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell 

got called

**Comment by patchthecode** [comment]
@mayqiyue can you zip a sample project with the issue and send to patchthecode@gmail.com?

**Comment by mayqiyue** [comment]
I sent you a email just now.

**Comment by patchthecode** [comment]
Ok. i took a look at your code.
Your functions are not correct. The videos here will help you a lot on how to use the library -> [Here is the the list of all videos](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)

To fix your bug you need to have these functions 
```swift
    func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {
        let v = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: NSStringFromClass(JTAppleCollectionReusableView.self), for: indexPath)
        v.backgroundColor = UIColor.red
        return v
    }

    func calendarSizeForMonths(_ calendar: JTAppleCalendarView?) -> MonthSize? {
        return MonthSize(defaultSize: 50)
    }
```

This will fix your issue.
Let me know if you have anyother questions.

**Comment by mayqiyue** [comment]
Nice，It works. But the will display function is still not  got called.

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This func not work.
    }

**Comment by patchthecode** [comment]
it does get called. But only at special times.
Do not leave that function empty. It is important.
Details on how to implement this function is located here -> #553
