### ISSUE TITLE
calendar rotation issues on iPhone X

### ISSUE THREAD

**Issue by fgrios** [patchthecode/JTAppleCalendar#654]
Using version 7.1.4

I have set up my calendar and it works great on every iPhone and iPad model that supports iOS 9+. The only issue I am having is on the iPhone X using iOS 11.2

Upon first display, the calendar shows up exactly as designed:

![img_0138](https://user-images.githubusercontent.com/6527674/33904541-ad8c3fec-df30-11e7-8545-7fcd40e286c8.PNG)

When I rotate into landscape the calendar still looks pretty good, except that it is slightly clipped on right side:

![img_0139](https://user-images.githubusercontent.com/6527674/33904587-d46e4de4-df30-11e7-925d-eef9d23a6e3c.PNG)

Rotating back to portrait and the calendar is totally messed up:

![img_0140](https://user-images.githubusercontent.com/6527674/33904610-ec7673f8-df30-11e7-8d79-a1a3e8e0b984.PNG)

From this point on, the calendar is never correct.

I have tested this on every other iPhone and iPad model and they rotate properly in to any orientation.

On the iPhone X I currently have constraints set to safe area on leading and trailing sides 9hence the gray bars in the landscape image above.) If I remove safe areas, the rotation is better (it still clips on right side) but then in landscape, the calendar's left edge is under the iPhone X notch.

Any ideas what I should try to get this to rotate and keep the calendar in correct format?

**Comment by patchthecode** [comment]
hmm. Have you done any code for your rotation?
Paste the code you corrently do when you rotate. Thanks.

**Comment by fgrios** [comment]
I have no rotation code. it is all handled by constraints in IB.

**Comment by patchthecode** [comment]
It is behaving normall on my sample application.
Is it possible you can strip you app into a sample app, then send me the zip file with the bug?

**Comment by fgrios** [comment]
This is what I have discovered. If the calendar (and the tableview) are NOT embedded in a splitviewcontroller, then it all rotates fine. When they ARE embedded in a splitviewcontroller, that is when I get the problem.

**Comment by fgrios** [comment]
I have figured out that if I embed my splitViewController inside a container view, then I avoid the problem.

**Comment by patchthecode** [comment]
This may work. But i think i'll still take a look at it.
Thanks for investigating. I will look it up once i am free-er
