### ISSUE TITLE
Installed and having so many errors using latest version of JTAppleCalendar 7.1.4..

### ISSUE THREAD

**Issue by danishiq** [patchthecode/JTAppleCalendar#658]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.4
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by hemangshah** [comment]
@danishiq Please provide the answer to above questions. It's really important for the developer of this library to understand your issue.

**Comment by patchthecode** [comment]
@danishiq yes, please make your question developer friendly.
Saying that you have many errors doesnt tell us anything.

**Comment by patchthecode** [comment]
closing this issue until user provides more information.

but i'll leave you with this link in case you are experiencing the same issue as this guy -> https://github.com/patchthecode/JTAppleCalendar/issues/659#issuecomment-352059382
