### ISSUE TITLE
Version 6.0 ---> 7.14 errors

### ISSUE THREAD

**Issue by CeceXX** [patchthecode/JTAppleCalendar#659]
Hey, I'm using the latest version of JTAppleCalendar and the [CalendarPopUp](https://github.com/orazz/CalendarPopUp) framework, which is based on your library (though version 6.0, not the latest). Any hints on how to fix these issues?

<img width="975" alt="screen shot 2017-12-15 at 10 31 58 am 1" src="https://user-images.githubusercontent.com/10504710/34035902-caa0f762-e183-11e7-8d51-808ed707b158.png">
 
Cheers,

**Comment by patchthecode** [comment]
Yea, the guy who wrote calendar popup, I do not think he updates his library as regularly as I do.
I'd say the best bet is to just use this one as it is easy to create a popup calendar.

Calendarpopup is still using version 6 of JTApplecalendar which is being fazed out.
There is a huge change in version 7 (the final major change).
The tutorials to set every thing up can be found [HERE](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q). 

Version 7 makes the this library a direct subclass of a UICollectionView which makes things very much easier. I have also removed many of the custom names that i used in version 6, and opted to use the default variable/function names that Apple provided to makes things easier on developers.

The tutorials should help you a lot. If youre still stuck, then let me know.

**Comment by CeceXX** [comment]
Thank you ~ I guess I'll need to convert the code of Calendar PopUp manually to the latest version of JTAppleCalendar. Honestly, I don't think I have enough energy to create a new calendar, although I know it's pretty simple with your framework.

**Comment by patchthecode** [comment]
Yea. with version you can create a calendar in 5 mins if you follow the vids.
Best of luck man.

**Comment by orazz** [comment]
[CalendarPopUp upgraded to latest version of JTAppleCalendar](https://github.com/orazz/CalendarPopUp)

**Comment by patchthecode** [comment]
@orazz awesome man :)

**Comment by CeceXX** [comment]
Orazz & Jay you guys da best, thanks so much!
