### ISSUE TITLE
Get current cell by providing point

### ISSUE THREAD

**Issue by tiepvuvan** [patchthecode/JTAppleCalendar#66]
My project currently require show a UIMenuController by hold on a day cell, so I need to find which cell user currently pressed and get frame of it.
Do JTAppleCalendar have a method for find cell by providing point?

**Comment by patchthecode** [comment]
Let me try understand what you want.
You want the frame of the cell. Basically, its `x:y` position so that you can display some menu popup?

**Comment by tiepvuvan** [comment]
Yes, but I couldn't find similar function on your library.

**Comment by patchthecode** [comment]
Ok i have an update coming over the weekend. You will be able to get this information. But let me know exactly HOW you want the cell information.

Can you tell me how you want the frame information of the cell to be gotten? Maybe if you go through the flow from user tapping to developer snatching frame info, I might have a better idea. I don't want to release something only to find out it does not satisfy the requirement.

**Comment by patchthecode** [comment]
Update has been added to master branch.
You can now query the frame of the cell.

**Comment by patchthecode** [comment]
You can now get the current cell. Functionality is now added.

**Comment by patchthecode** [comment]
This feature has now been added in version 4.1.1
cellState.cell = the cell you are looking for.

closing this issue
