### ISSUE TITLE
didSelectDate not called ever

### ISSUE THREAD

**Issue by diogoAntunes** [patchthecode/JTAppleCalendar#660]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. 7.1.4
2. yes
3. 

I have this weird issue where the didSelectDate is not called, but the willDisplay is also not called. The calendar does show properly tough. I also set the delegate and datasource correctly.

```swift

  fileprivate let calendarView: JTAppleCalendarView = {
        $0.translatesAutoresizingMaskIntoConstraints = false
        $0.scrollDirection = .horizontal
        $0.showsVerticalScrollIndicator = false
        $0.showsHorizontalScrollIndicator = false
        $0.isPagingEnabled = true
        $0.backgroundColor = .white
        $0.minimumLineSpacing = 0
        $0.minimumInteritemSpacing = 0
        $0.register(CalendarCell.self)
        
        return $0
    }(JTAppleCalendarView(frame: .zero))


calendarView.calendarDataSource = dataSource
calendarView.calendarDelegate = dataSource

extension CalendarDataSource: JTAppleCalendarViewDataSource {
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        return ConfigurationParameters(startDate: dateFormatter.date(from: "2017 01 01")!, endDate: dateFormatter.date(from: "2017 12 31")!)
    }
}

extension CalendarDataSource: JTAppleCalendarViewDelegate {
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let calendarCell = calendar.dequeueReusableCell(forIndexPath: indexPath) as CalendarCell
        self.calendar(calendar, willDisplay: calendarCell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return calendarCell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        guard let calendarCell = cell as? CalendarCell else { return }
        
        calendarCell.selectedView.isHidden = false
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        guard let calendarCell = cell as? CalendarCell else { return }
        
        calendarCell.selectedView.isHidden = true
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        guard let calendarCell = cell as? CalendarCell else { return }
        
        calendarCell.laDate.text = cellState.text
    }
}
```

**Comment by patchthecode** [comment]
I see that you have a return statement in that function if the cell is nil. Can you verify that the possibly the function is returning on that line of code?
```swift
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        guard let calendarCell = cell as? CalendarCell else { return }
        
        calendarCell.selectedView.isHidden = false
    }
```

Also, will display cell is called only on special instances.
Can you let me know what you are trying to do with that function?

**Comment by diogoAntunes** [comment]
Hey, thank you for such a quick reply :) I implemented willDisplayCell accordingly to #553.

didSelectDate is not called at all, it's not getting called. The only thing I was trying to do is show an overlay view on the cell once the date is tapped. I tough the view was not letting the touches pass, so I even removed the `selectedView` but that didn't help either. I'm doing all of this in code, no .storyboards could that be a problem?

**Comment by patchthecode** [comment]
@diogoAntunes no. this lib works with both storyboards and code.

one thing though, can you remove this? Just a wild guess.
```
        $0.translatesAutoresizingMaskIntoConstraints = false
```

There should be no problems with your code.
If possible can you send a sample app that replicates this problem? Just an empty sample app with no company code in it.

**Comment by diogoAntunes** [comment]
@patchthecode Thank you so much for all your help, specially on a Sunday :) while I was making the sample project for you, I couldn't get it *not to work* so I turned to my project and eventually found the issue, I was presenting the calendar modally and I added a tap gesture to view of the ViewController so it was dismissing on tap's outside the calendar view, the problem with this was that the calendar view taps were being dismissed :)

**Comment by patchthecode** [comment]
Awesome man. Glad you figured it out.
Have a good one 🍻
