### ISSUE TITLE
how to scroll through every date??

### ISSUE THREAD

**Issue by Rumy-hasan** [patchthecode/JTAppleCalendar#661]
Hi,
It's a nice library but I may miss something so asking here.My calendar configuration is here.

```swift
let parameter = ConfigurationParameters(startDate: v!, endDate: Date(), numberOfRows: 1, 
   calendar: testCalendar, 
   generateInDates: generateInDates, 
   generateOutDates: generateOutDates, 
   firstDayOfWeek: firstDayOfWeek, 
   hasStrictBoundaries: hasStrictBoundaries)
```
where 
```swift
  var generateInDates: InDateCellGeneration = .forAllMonths
  var generateOutDates: OutDateCellGeneration = .tillEndOfRow
  var hasStrictBoundaries = true
  let firstDayOfWeek: DaysOfWeek = .sunday
```
so in my 
```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
   print(date)
}
```
I think it may call 730 time with every date.My target is to fetch some data from database according to each date and show them as a bar chart where my presented date is above and related bar is below.the picture is 

<img width="300" alt="n3hqywcwjlert37yfjl72onpipmvc15uv7mazttosg7a8ed5aatbosxual00btd8i4nw6yocnjsg580kmcof_d0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85" src="https://user-images.githubusercontent.com/2439146/34093468-3ad00c76-e37d-11e7-992d-1d749064d975.png">

I printed out date also but it's not the same order but my cell present properly.So how do i get proper date for doing my external work?

**Comment by patchthecode** [comment]
cellForIndexPath is not the place to fetch all the dates all at once.
cellForIndexPath is an Apple Function that will only run for the cells that are on the screen
if you want to load all your dates from your DataSource, you have to

1. Load them out side the cellForIndexPath function
2. Save them in an Dictionary or Array

then,
inside the cellForIndexPath function you will do fetch the data from your Array or Dictionary

**Comment by patchthecode** [comment]
closing issue now. If you have further qeustions, just ask.
