### ISSUE TITLE
i saw the issues 553 but still don't know how to use will display 

### ISSUE THREAD

**Issue by MichaelSun3566** [patchthecode/JTAppleCalendar#662]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.4
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

xcode 9.2 swift 4
i am using 7.1.4 jtapplecalendar
i am the beginner user for swift & xcode 
and i want to make the app that have a calendar
so i tried this jtapplecalendar 
and i saw every video on youtube
then i tried to make calendar like this video:https://www.youtube.com/watch?v=zOphH-h-qCs&t=3s
i fallow every step in video
after i saw the issues 553 that Explanation ：Type 'ViewController' does not conform to protocol 'JTAppleCalendarViewDelegate'
but i still don't know what i have to code in willdisplay
because i code same as cellforitemat but it have Thread 1: signal SIGABRT
this is my last tried to code

```swift
extension ViewController :JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource{
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let mycell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "myCustomCell", for: indexPath) as! CustomCell

        mycell.detaLable.text = cellState.text
    }
    
   
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let mycell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "myCustomCell", for: indexPath) as! CustomCell
         mycell.detaLable.text = cellState.text
        self.calendar(calendar, willDisplay: mycell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return mycell
    }
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat="yyyy MM dd"
        formatter.timeZone=Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2017 01 01")!
        let endDate = formatter.date(from: "2017 12 31")!
        
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate)
        return parameters
    }
```
it still have signal SIGABRT
i search about like one week
but i still don't know how to do

sorry i'm not good at english
but i really try hard to understanding
and i thought this jtapplecalendar is wonderful to the beginner
so please help me

**Comment by patchthecode** [comment]
Your function should look like this.
You should not `dequeue` inside the `willDisplayCell` function.

```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let mycell = cell as! CustomCell
        mycell.detaLable.text = cellState.text
    }
```

**Comment by patchthecode** [comment]
closing issue.
Let me know if it works for you.

**Comment by MichaelSun3566** [comment]
I tried and still have signal SIGABRT
I don't know why.........

**Comment by patchthecode** [comment]
@MichaelSun3566 can you send me the project as a zip file?
patchthecode@mail.com

**Comment by MichaelSun3566** [comment]
Thanks! i got my mistake

**Comment by sambong0113** [comment]
Please tell me how to solve this issue
