### ISSUE TITLE
Disable date selection appears not to work

### ISSUE THREAD

**Issue by chriseenberg** [patchthecode/JTAppleCalendar#665]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
7.1.4

2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.4
Yes.

3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I've implemented a fully functional calendar with all the methods shown in the videos. This works great! But when it comes to disabling certain dates, nothing happens. Therefore, I've tried disabling all dates to see if this works ( no conditional disabling, but disable all dates ). This doesn't seem to work either.

I've tried the following functions found in this [documentation](https://patchthecode.github.io/DateCellConfiguration/) without luck:
```
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
  return false
}
```
and

```
func calendar(_ calendar: JTAppleCalendarView, willDisplayCell cell: JTAppleCell, date: Date, cellState: CellState) {
        let myCustomCell = cell as! CustomCell // CellView is the class you created if you followed the Tutorial
        myCustomCell.isUserInteractionEnabled = false
    }
```
What I'm aiming to achieve is disable all Saturdays and Sundays eventually. The code I tried to run for this to work was:
```
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell, cellState: CellState) -> Bool {
        if cellState.day == .saturday || cellState.day == .sunday {
            return false
        } else {
            return true
        }
    }
```

Am I on the right track or is this a bug?

**Update**
After a quick research I can say that the functions does not even get called. Perhaps I've done something wrong with the declaration ( I'm new in the swift world )
Kind regards Chris

**Comment by chriseenberg** [comment]
Found the solution - finally :) It was an error on my end, though documentation is indeed out of date.
This code worked for me - for future reference for others :)

```
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
        if cellState.day == .saturday || cellState.day == .sunday {
            return false
        } else {
            return true
        }
}
```

Closing the issue.

Kind regards Chris

**Comment by patchthecode** [comment]
ok. Thanks for letting me know.
yes, i will update that documentation.
