### ISSUE TITLE
Getting error 'ViewController' does not conform to protocol 'JTAppleCalendarViewDelegate'

### ISSUE THREAD

**Issue by MarquelH** [patchthecode/JTAppleCalendar#666]
Currently running version 7.1.4 (Was previously running 7.0 but then updated) and going alongside the YouTube video for creating calendar from scratch using JTAppleCalendar. (https://www.youtube.com/watch?v=zOphH-h-qCs)  In the video, I was able to follow all the way up till about 7:20 but once you start conforming to delegate and datasource protocols, you add in the second function and the error that says "'ViewController' does not conform to protocol 'JTAppleCalendarViewDelegate' " I'm assuming goes away for you, but for me it stays and so my build fails. I am also running the newest version of Xcode but am still in Swift 3. I have attached the code with the error.

![screen shot 2017-12-29 at 11 23 53 am](https://user-images.githubusercontent.com/18058194/34441607-dd32464e-ec8a-11e7-9f8d-a18b6bed701a.png)

**Comment by juliensagot** [comment]
I got the same error. I had to implement the following method:
`func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {`

**Comment by MarquelH** [comment]
Just did it, and it works. Thanks
