### ISSUE TITLE
Show only current month dates on each collectionview and hide previous and next month dates from calendar

### ISSUE THREAD

**Issue by karunaveer** [patchthecode/JTAppleCalendar#669]
I am using JTAppleCalendar 7.1.5 version. 

PFA. I dont want to display dates which are mentioned as strike through. 

I tried the following way but it didn't work. Please provide appropriate solution to achieve the same.
   
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This function should have the same code as the cellForItemAt function
        let myCustomCell = cell as! CellView
        configureVisibleCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
        
        if cellState.dateBelongsTo == .thisMonth {
            myCustomCell.isHidden = false
        } else {
            myCustomCell.isHidden = true
        }

    }

![simulator screen shot - iphone 8 plus - 2018-01-02 at 16 16 32](https://user-images.githubusercontent.com/446947/34483593-f805e47a-efd8-11e7-8ce4-04975afcb168.png)

**Comment by patchthecode** [comment]
the code you have provided above is the correct way to do it.
can you show me the code that you have in your `cellForItemAtIndexPath` function?

**Comment by karunaveer** [comment]
Please see the below function

 func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
        configureVisibleCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
        return myCustomCell
    }

**Comment by patchthecode** [comment]
change your code to this:

```swift
 func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
    let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CellView", for: indexPath) as! CellView
     self.calendar(calendar, willDisplay: myCustomCell, forItemAt: date, cellState: cellState, indexPath: indexPath)
    return myCustomCell
 }
```

**Comment by karunaveer** [comment]
If i do so, we are calling our custom method as below from the below function and we are getting the same result. So please share us working code to complete our task.

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This function should have the same code as the cellForItemAt function
        let myCustomCell = cell as! CellView
        configureVisibleCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
    }

**Comment by patchthecode** [comment]
to display 2 months on one page, then just change the cellSize.
try 
```swift
calendarView.cellSize = 20
```

**Comment by karunaveer** [comment]
We are getting 3 months calendar in one page if we set calendarView.cellSize = 20.

Inorder to make 2 months in one page, We are setting myCalender.cellSize = myCalender.frame.size.height / 17 and its working fine.

But the problem is when we scroll up and down we are not getting the dates on colectionview properly (PFA of screen before and after scrolling). The following is the method we are using to customize the cell. Please share if you have any working code for our need so that we can complete our task quickly.
![afterscrolling](https://user-images.githubusercontent.com/446947/34512365-755499d8-f07b-11e7-9268-c683987c5a11.png)
![beforescrolling](https://user-images.githubusercontent.com/446947/34512366-7579ad04-f07b-11e7-92ab-26ec787631da.png)



 func handleCellTextColor(view: JTAppleCell?, cellState: CellState) {
        guard let myCustomCell = view as? CellView  else {
            return
        }
        
        if cellState.isSelected {
            myCustomCell.dayLabel.textColor = white
        } else {
            if cellState.dateBelongsTo == .thisMonth {
                myCustomCell.dayLabel.textColor = black
            } else {
               // myCustomCell.dayLabel.textColor = UIColor.green
                myCustomCell.layer.borderWidth = 0
              //  myCustomCell.isUserInteractionEnabled = false
               // myCustomCell.isHidden = true
              myCustomCell.dayLabel.text = ""
               
                
            }
        }
    }

**Comment by patchthecode** [comment]
OK, you are asking many question in one issue.
Have you taken a loo at any of the tutorial videos? 

They will help you a lot.
the link to all the videos is here. You can skip the vids you are already familiar with -> [LINK](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)
