### ISSUE TITLE
Cell not deselected sometimes

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#67]
Found something. If I selectDates with triggersDelegate false, and then select a date, the previously selected date is not deselected. Are you seeing the same?

**Comment by patchthecode** [comment]
1. Are you setting a cell to be unselectable any where in your app?
2. Are you selecting programitically? or is the user tapping the cells

I suspect since the cells are being reused, I probably forgot to reset the cell. A simple code fix. Looking into it.

**Comment by krisanthony** [comment]
1. I don't think so, can you be more specific?
2. I am selecting programmatically

It does seem like the last cell's state just isn't being refreshed

**Comment by patchthecode** [comment]
issue resolved on branch. Closed.
Cells were not being restored when dequeued. Thus old cells that were marked at disabled were reused for new cells.
