### ISSUE TITLE
self.calendarView.scrollToSegment(.previous) / self.calendarView.scrollToSegment(.next) do not work after rotation.

### ISSUE THREAD

**Issue by amith-ranasinghe** [patchthecode/JTAppleCalendar#670]
I am using the "pod 'JTAppleCalendar', '~> 7.1.5'"

I have to support both iPhone and iPads. The calendar has two buttons to go to previous month and next month I am using them like follows.
```swift
    @IBAction func gotoPreviousMonthAction (_ sender: UIButton) {
        self.calendarView.scrollToSegment(.previous)
    }
    
    @IBAction func gotoNextMonthAction(_ sender: UIButton) {
        self.calendarView.scrollToSegment(.next)
    }
```
This works okay until I rotate the device to from Portrait to Landscape. 

Once the calendar is rotate to Landscape orientation this does not work.  So the next months and previous months do not get updated.

Note: I have also implemented the following method as well.
```swift
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        calendarView.viewWillTransition(to: size, with: coordinator, anchorDate: rotateDate)
    }
```
The rotateDate is getting from the following method
```swift
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        let date = visibleDates.monthDates.first!.date
        self.rotateDate = date
        formatter.dateFormat = "MMMM yyyy"
        monthYearLabel.text = formatter.string(from: date).uppercased()
        self.getJobsForCalendarFromServer(displayDate: date)
    }
```
However the swiping from left to right & right to left work perfectly and it does change the months as expected.

**Comment by patchthecode** [comment]
On which device/simulator type did you encounter this?

**Comment by amith-ranasinghe** [comment]
I am using iPad Air

**Comment by patchthecode** [comment]
replace this in your `Podfile` for JTAppleCalendar.

```
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
```

then do a `pod update` on console.
Let me know if your isssue was resolved. If it is not, I will re-open this issue.

**Comment by amith-ranasinghe** [comment]
The bug seems to be resolved! Thanks for fixing it.

**Comment by patchthecode** [comment]
awesome.
have a good one 🍻
