### ISSUE TITLE
Memory Leak When Scrolling

### ISSUE THREAD

**Issue by DominicMDev** [patchthecode/JTAppleCalendar#671]
Version: 7.1.5

I noticed what I think is a memory leak that happens while scrolling through the calendar. I was able to recreate this in the sample application. When in vertical scrolling mode without stopping at each section, the calendar memory starts creeping up by about 0.1MB increments.

I have done some digging, but have not found the source of the leak yet.

I attached two screenshots. One of before I begin to scroll and one after scrolling for a few minutes.

![before scrolling](https://user-images.githubusercontent.com/32944376/34544751-166da0b4-f09d-11e7-902b-cba78d696e27.png)
![after scrolling](https://user-images.githubusercontent.com/32944376/34544753-1790caf2-f09d-11e7-922f-dd38a25eef62.png)

**Comment by patchthecode** [comment]
Does the used memory continue increasing without bound? Or does it stop at a certain level.

**Comment by DominicMDev** [comment]
If there is a bound, I haven't found it yet. I have tired scrolling for about 3 minutes. I'm going to try to make a UITest that scrolls for a long time.

**Comment by DominicMDev** [comment]
My understanding is that the Xcode Instruments are useful for catching leaks in low-level C API's.
I tried it just to be sure, but it didn't find a leak.

**Comment by patchthecode** [comment]
Thats the thing. I tested this library very much for leaks and have fixed them.
There arent more leaks i found using the `leaks` and `zombies` tool.
If you find any leaks do let me know. But I could not find any more in the code.

**Comment by patchthecode** [comment]
Will close this issue until leaks are confirmed. 
In terms of increasing resources, lets track this here -> https://github.com/patchthecode/JTAppleCalendar/issues/470
