### ISSUE TITLE
My collectionView doesn't show anything

### ISSUE THREAD

**Issue by nickbonny** [patchthecode/JTAppleCalendar#672]
Hi,
I followed this YouTube tutorial step by step: https://www.youtube.com/watch?v=zOphH-h-qCs&t=1s

I'm working with the version  '7.1.5'; but I also tried an earlier version (the 7.0 one) in another project.

My problem is that the collectionView I set up doesn't show the days. In fact I changed the color of the background in my collectionView and when the application runs I can see it, but the cells are not shown. It is just an empty collectionView. 

The only thing different from the tutorial is that Xcode complains about a missing method that I added:

--> func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath)

in this method I copied the same code in cellForItem method.  

Xcode doesn't give me any warnings or errors, id just doesn't work like in the tutorial.
Here is a photo of my empty collectionView:
<img width="401" alt="schermata 2018-01-04 alle 16 26 41" src="https://user-images.githubusercontent.com/14027868/34570440-162ffc3a-f16c-11e7-9178-db633cc2fa4d.png">

Hope I was clear enough

**Comment by patchthecode** [comment]
send me an email with the sample app.
patchthecode@gmail.com

**Comment by patchthecode** [comment]
I just saw your email.

You have a couple places you didnt follow the video 100%

1.  On your story board, your ViewController was called `ViewController`. This should have been called `CalendarViewController`. You have a file-name/ class-name mismatch.  Your file is called `ViewController` but your class is called `CalendarViewController`
2. the idenfitifer for your cell on storyboard is called `CalendarCell` but in your code you called it `CalendarCell`.

Closing this issue.
Hope it helped.

**Comment by oniikal3** [comment]
@patchthecode I'm facing with this issue too with the same version (7.1.5)

I'm sure I have changed custom class to my class name. and checked identifier.

**Comment by oniikal3** [comment]
@patchthecode I fixed because I have problem with constraint. It's show as expected when run an application but it's not show anything in storyboard. I can setup, click as it be but just not show anything when I changed UICollectionView to JTAppleCalendarView.
