### ISSUE TITLE
Scrolling Calendar to latest date will show wrong dates

### ISSUE THREAD

**Issue by siapno01** [patchthecode/JTAppleCalendar#673]
try this 
I made a programmatically calendar using the JTAppleCalendarView

use this as the configuration:
let startdate = formatter.date(from: "2017 02 01")!
let endDate = formatter.date(from: "2018 02 28")!

the in viewDidload, try to reload the calendar and it will show wrong dates in every cell

**Comment by siapno01** [comment]
Im using 7.1.5 version of JTAppleCalendar

**Comment by patchthecode** [comment]
@siapno01 what do you mean wrong dates in every cell?

A screen shot can help.
Are the dates wrong by one date less?

**Comment by siapno01** [comment]
the dates are wrong once you scrollToDate for 1 time only in view did
load..maybe later ai can give the screen shot

**Comment by siapno01** [comment]
this what will show..

**Comment by siapno01** [comment]
when I try to use the startdate and endDate value in tutorial it works
great but when I change the value as I comment above it is not working

**Comment by patchthecode** [comment]
I still do not understand.
You'll have to explain what you mean by `it is wrong`.
Please explain this to me in "programmer language".
Saying that something is wrong is not versy descriptive. 

You'll have to tell me:
1. what is expected
2. what you did
3. how your results differed from what you expected

only then i can know what "wrong" is.

**Comment by siapno01** [comment]
Firs set the configure of calendar like this 



**func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let startdate = formatter.date(from: "2017 02 01")
        let endDate = formatter.date(from: "2020 02 28")

        let parameters = ConfigurationParameters(startDate: startdate, endDate: endDate)
        return parameters
    }**

then try to scroll to current date in viewDidLoad

**override func viewDidLoad() {
        super.viewDidLoad()
        
        calendar.register(CalendarDayViewCell.self, forCellWithReuseIdentifier: CalendarDayViewCell.reuseIdentifier)
        
        calendar.calendarDelegate = self
        calendar.calendarDataSource = self
        calendar.scrollToDate(Date())
    }**

This what will show and see the dates in every cell

<img width="431" alt="screen shot 2018-01-06 at 1 20 44 pm" src="https://user-images.githubusercontent.com/19338814/34636836-8a224d36-f2e4-11e7-9468-578e4150bd33.png">

**Comment by patchthecode** [comment]
If you created your calendar manually, did you remember to put this in your code?

```swift
calendarView.scrollingMode = .stopAtEachCalendarFrame
```

**Comment by siapno01** [comment]
Im sorry i did not put that one.

**Comment by patchthecode** [comment]
Does it work now?

**Comment by siapno01** [comment]
Yes it works good now . thanks a lot . I didnt notice that you need to declare that when you are creating calendar manually . This is noted . 👍
