### ISSUE TITLE
outer two columns don't update properly after month switch

### ISSUE THREAD

**Issue by lx4r** [patchthecode/JTAppleCalendar#674]
Hey,
I'm using JTAppleCalendar version 7.1.5 to build a calendar that the user should use to select a range of dates. I managed to implement this functionality thanks to the good tutorials on the project page but now I'm stuck with a problem:
When I select a range of dates in one month, then go to the next month, select a new date range there (which deselects the first one) and then go back to the first month the selection status (at least visually) of the outer two columns of my calendar isn't updated. For some reason the whole thing works fine if the selection is not in the outer two columns.
Gif of the problem:
![jtapplecalendar_issue](https://user-images.githubusercontent.com/1402895/34621386-36dc6a26-f249-11e7-9b59-17031a7a6dcb.gif)
Gif of working selection (not selection dates for the outer two columns):
![jtapplecalendar_working](https://user-images.githubusercontent.com/1402895/34621397-40e96938-f249-11e7-93a4-b5d0a9d6311f.gif)

Here's my code: [Gist](https://gist.github.com/lx4r/c4d9a0bc434365b7f42a0984ff3e6dcf) (sorry for it not being very sophisticated 😇 )

I hope I included all necessary information.
Thanks in advance for the help! 🙂

**Comment by patchthecode** [comment]
Did you remember to include the `willDisplayCell` function as shown here?
https://github.com/patchthecode/JTAppleCalendar/issues/553

I made a very important warning about this on the main page. 🙃

**Comment by lx4r** [comment]
@patchthecode Thank you so much, adding that function fixed the problem. I'm so sorry for not reading the warning, I thought it only affected people the upgrade from a version prior to 7.1.0 😇 .
Thanks again for the help, you're doing a great job here! 👍

**Comment by patchthecode** [comment]
cool. Have a good one 🍻
