### ISSUE TITLE
Weird layout when minimumLineSpacing and minimumInteritemSpacing are non-zero

### ISSUE THREAD

**Issue by vietstone** [patchthecode/JTAppleCalendar#676]
I'm using version 7.1.5. I'm trying to add line and cell spacing, both to 5
        calendarView.minimumLineSpacing = 5
        calendarView.minimumInteritemSpacing = 5
Then the calendar layout is weird as:
- line and cell spacing become 10
- sectionInset become (5, 5, 5, 5)

**Comment by patchthecode** [comment]
would love to have 2  screen shots: 
1) what was expected
2) what actually happened

**Comment by patchthecode** [comment]
chatting here is faster (if im awake) -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
I think this is expected.
If you set the following code, what will happen is a grid of rows and columns of cells. This is default behavior of UICollectionView.
```swift
calendarView.minimumLineSpacing = 5
calendarView.minimumInteritemSpacing = 5
```

Closing this issue.
But if your question is not properly answered, then please reply.

**Comment by vietstone** [comment]
Sorry for late reply.
What I want is space between rows is 5, space between columns is 5. Like this image:
<img width="551" alt="expected" src="https://user-images.githubusercontent.com/744353/35385082-cdcbedde-01f9-11e8-837c-a724004c1dcb.png">

So I write:
```
        calendarView.minimumLineSpacing = 5
        calendarView.minimumInteritemSpacing = 5
```

But it become as space between rows is 10, space between columns is 10, and padding of 4 edges is 5 as this image
<img width="551" alt="real" src="https://user-images.githubusercontent.com/744353/35385129-f2a3537c-01f9-11e8-9043-88ba67f42989.png">

So to get the expectation, I need to change code as:
```
        calendarView.minimumLineSpacing = 2.5
        calendarView.minimumInteritemSpacing = 2.5
        calendarView.sectionInset = UIEdgeInsets(top: -2.5, left: -2.5, bottom: -2.5, right: -2.5)
```

I think this is not default of UICollectionView.

**Comment by patchthecode** [comment]
This is not UICOllectionView behavior that is correct.
But this is the default behavior that I coded into the library. 
Because for my original project, i wanted it this way. 😀

You're the first to request a change to this. I will have to think up a solution if you need this.
But It wont be very soon, as I am tied up between more than one projects right now.

**Comment by 131e55** [comment]
I think `lineSpacing` and `interitemSpacing` seem like `cellInsets`🤔
