### ISSUE TITLE
how to implement 3x4 year calendar ui?

### ISSUE THREAD

**Issue by hyuntae0117** [patchthecode/JTAppleCalendar#677]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. 
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

My version: 7.1.5

Hello guys!
I'm a newbie iOS developer. I appreciate the cool Calendar library!

I didn't know how to implement the calendar UI before but now I made some progress with your help. Thanks.

I have a question. How do I implement 3x4 year calendar UI?

like this
![2018-01-08 11 38 05](https://user-images.githubusercontent.com/34052475/34657345-723b6524-f468-11e7-81f1-8c590b460c47.png)

I want to make like this: when the user taps the small month calendar list item, then my app shows a bigger and detailed calendar – like the iOS default calendar app!

Thank you!

**Comment by patchthecode** [comment]
Im sorry, but we do not have a year view.
It was something that has been considered but not implemented.
Maybe if someone can submit a request for it, then i will merge it.

**Comment by patchthecode** [comment]
tracked here.
YearView will be implemented
