### ISSUE TITLE
Compilation Issues from Swift 2 to Swift 3

### ISSUE THREAD

**Issue by Zach-Miller123** [patchthecode/JTAppleCalendar#678]
Hi,

I am migrating a project from swift 2 to swift 3. The original pod file used JTAppleCalendar version 5.0.1. I have updated to version 7.0.

During this migration process, I am having trouble resolving the following compilation issues.

*calendarCollection is of type JTAppleCalendarView
1.  calendarCollection.scrollToNextSegment() <- scrollToNextSegment() not recognized
2. calendarCollection.scrollToPreviousSegment() <- scrollToPreviousSegment() not recognized
3. calendarCollection.currentCalendarDateSegment() <- currentCalendarDateSegment() not recognized
4. calendarCollection.registerCellViewXib(fileName: "CalendarCellView") <- registerCellViewXib(fileName:) not recognized
5. calendarCollection.firstDayOfWeek = .monday <- firstDayOfWeek not recognized
6. calendarCollection.cellInset = CGPoint(x: 0, y: 0.3) <- cellInset not recognized

In each of these cases, how might I use the new API to replace these various lines of code?

Any help would be greatly appreciated. Thanks so much!

**Comment by patchthecode** [comment]
```swift
        calendarView.scrollToSegment(.next)
        calendarView.scrollToSegment(.previous)
        calendarView.scrollToSegment(.start)
        calendarView.scrollToSegment(.end)

        calendarView.register(YourNib, forCellWithReuseIdentifier: "YourIdentifier")

        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
```

`calendarCollection.firstDayOfWeek = .monday <- firstDayOfWeek not recognized`
This is now done in the configureCalendar function.
For help on setting up the entire calendar from scratch -> check out [these videos](https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)

**Comment by Zach-Miller123** [comment]
Great, thanks so much!

**Comment by a21220084** [comment]
Finally i found this 💎
