### ISSUE TITLE
In vertical, the bug on the scrollToSegment (.Previous)

### ISSUE THREAD

**Issue by wangyanlong** [patchthecode/JTAppleCalendar#681]
i'm using 7.1.5. When I use  `calendarView?.scrollDirection = .vertical` And then i use `calendarView?.scrollToSegment(.previous)` the result is equivalent to 
`calendarView?.scrollToSegment(.next)`

**Comment by patchthecode** [comment]
:O 
impossible!

ok. will check it out.

**Comment by wangyanlong** [comment]
iPhone X & Simulator

**Comment by patchthecode** [comment]
assuming master branch fix worked. 
closing issue until user responds further.

**Comment by chemise** [comment]
Hi,
After updated the pod I got the same problem. So I took a look quickly.
In case the scrolling mode is vertical and there are no header, the action is to display the next month every time.
To fixe it I replaced the 'else' content on line 461 in UserInteractionFunctions.swift with
`{
                
                fixedScrollSize = frame.height
                let section = CGFloat(Int(contentOffset.y / fixedScrollSize))

                switch destination {

                case .next:
                    yOffset = (fixedScrollSize * section) + fixedScrollSize
                case .previous:
                    yOffset = (fixedScrollSize * section) - fixedScrollSize
                case .start:
                    yOffset = (fixedScrollSize * 0)
                case .end:
                    yOffset = (fixedScrollSize * CGFloat(numberOfSections(in: self) - 1) )

                }
            }`

Thanks for this amazing lib.

**Comment by patchthecode** [comment]
@chemise ive looked at this today. The part i am confused on is this:

If scrolling mode is vertical, and there are no headers, I do make it display the next month.
Do you not want this? Maybe if you clarify the behavior that you need, then i can implement the code you have done.

**Comment by patchthecode** [comment]
closing until further info
