### ISSUE TITLE
Either date could not be generated or delegate was nil

### ISSUE THREAD

**Issue by fmo91** [patchthecode/JTAppleCalendar#682]
I am getting this error and I can't figure out why is it being thrown. I'm using version 7.1.4

My view controller is like this:

```swift

class DaySelectionViewController: BaseViewController {

    // MARK: - Views -
    @IBOutlet weak var calendarView: JTAppleCalendarView!
    
    // MARK: - Life Cycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureCalendarView()
    }
    
    // MARK: - Configuration -
    fileprivate func configureCalendarView() {
        
        calendarView.calendarDelegate = self
        calendarView.calendarDataSource = self
        
        calendarView.scrollDirection = UICollectionViewScrollDirection.horizontal
        
        let cellNib = UINib(nibName: "MonthCalendarCell", bundle: nil)
        calendarView.register(cellNib, forCellWithReuseIdentifier: "MonthCalendarCell")
        
        let headerNib = UINib(nibName: "MonthCalendarHeader", bundle: nil)
        calendarView.register(headerNib, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "MonthCalendarHeader")
        
    }
    
}

// MARK: - JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate
extension DaySelectionViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
        // Implementation details ...
}
```

And I'm adding the calendar to a .xib file where I design the controller's view.

Any idea on how to solve this?

**Comment by patchthecode** [comment]
You have registered a header, but have you implemented the header funcitons?

```swift
func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {
...

func calendarSizeForMonths(_ calendar: JTAppleCalendarView?) -> MonthSize? {
...
}
}

**Comment by fmo91** [comment]
Yes, I've implemented them. But the strange thing here is that the calendar is being shown without crashing, and it looks perfect. The problem arises when I try to scroll the calendar horizontally to show other months: then the app crashes
There is another strange thing that's happening. When I stop the execution with a few breakpoints to inspect the variables, everything seems to be normal, and when I continue the app execution, everything works perfectly. This only happens when I put breakpoints in the code.
Any idea on this? I'm driving crazy

**Comment by fmo91** [comment]
The console log reads this:

```
Either date could not be generated or delegate was nil
There was an error in this code section. Please contact the developer on GitHub
```

**Comment by patchthecode** [comment]
can you provide me a sample app with this problem?
i'll fix.

**Comment by patchthecode** [comment]
The most I can tell you is show you the example app here, so that you can see what you did differently.
That error occurs when your delegate is either nil, or does not conform to the protocol.
I do not have any code from you to work with, so i cannot know your problem. But i can show you my code. -> https://github.com/patchthecode/CalendarTutorial

closing this issue. Let me know if it helped.

**Comment by patchthecode** [comment]
awesome.
