### ISSUE TITLE
Selected cell goes deselected even when return false from other cell's shouldSelectDate

### ISSUE THREAD

**Issue by extremer** [patchthecode/JTAppleCalendar#683]
Hi
First of all, I'm using the latest veresion 7.1.5.

I'm having a problem when I return false from shouldSelectDate for dates out of this month.
I implemented the method like this.

```swift
func calendar(_ calendar: JTAppleCalendarView, shouldSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
  return cellState.dateBelongsTo == .thisMonth 
}
```

When I select a date out of this month, it returns false as shown BUT previously selected date goes deselected still, **while I expect to remain selected.**

Here are the steps assuming **cell A at 2018-01-01** is already selected(isSelected == true) and the scroll is fixed in 2018-01.
1. select **cell B** from last month(**2017-12-31**)
2. A.isSelected goes false here already before shouldSelectDate call(checked in didSet)
2. shouldSelectDate for B is called : returning false
3. A.isSelected goes true again(recovered?)
4. A.isSelected goes false again(???)

finally, both A and B are not selected.

I'm not sure what i'm missing here when shouldDeselectDate is not even called.
Any advices would be appreciated.
Thanks in advance.

**Comment by patchthecode** [comment]
Maybe i am not understanding the problem properly.
Can you provide a  sample app demonstrating it? Please remove all your company secret code.
I'll try to get to it when i can.

**Comment by hartjosh** [comment]
Im getting a nil cell on the didDeselectDate when I pick another date that's not within the same month.

**Comment by extremer** [comment]
@patchthecode 
I'm attaching some demo images. Calander is of 2018 January.

<img width="349" alt="2018-01-19 10 53 21" src="https://user-images.githubusercontent.com/3157870/35153922-ab99912c-fd6b-11e7-8b60-bd5b419e6066.png">
1. select January 19

<img width="348" alt="2018-01-19 10 53 49" src="https://user-images.githubusercontent.com/3157870/35153953-c38af3de-fd6b-11e7-8e29-4437d92165ce.png">
2. select January 17
- which is in January, so works fine

<img width="350" alt="2018-01-19 10 53 58" src="https://user-images.githubusercontent.com/3157870/35153978-d43a4518-fd6b-11e7-91d2-57aa3db32ca1.png">
3. select February 1st
- shouldSelectDate returns false for the date in next month.
At this point, I want January 17 remain selected.

**Comment by extremer** [comment]
@hartjosh In my case, didDeselectDate is not called for the date not in this month when I return false for that date from shouldSelectDate

**Comment by hartjosh** [comment]
I found my issue, i didn't put anything in willDisplayCell, now all is well.

**Comment by patchthecode** [comment]
@extremer so basically you are saying that even though `shouldSelect` returns false, the a sell is still being deselected?

Ok. Can you show me your did select code?
Or join me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by extremer** [comment]
This is my didSelectDate code.

```func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        // set dateLabel
        dateLabel.text = formatDate(date)
        
        // select data
        let data = (cell as? AGCalendarCell)?.data
        selectData(data)
        
        selectedData = (date: date, data: data)      // cache for modification
    }```

What I'm curious is this. "Is it a bug?"
If not, maybe I can just do a workaround like setting OutDateCellGeneration to OutDateCellGeneration.off or something.

**Comment by patchthecode** [comment]
@extremer thats the thing. I am unable to reproduce what you are seeing.

We have a sample application attached to this github. I am trying to get enough information from you to reproduce this issue on the sample application.  But so far, our sample app is working perfectly.

If possible can you either:
1. Chat here -> https://gitter.im/patchthecode/JTAppleCalendar
2. Create a sample app with the issue?

Because I still cannot recreate the issue.

**Comment by patchthecode** [comment]
@extremer Hi, here is my sample applicaiton.

[deselectionBug.zip](https://github.com/patchthecode/JTAppleCalendar/files/1665132/deselectionBug.zip)

Every thing works on it. Can you get that sample application recreate your issue?
I am starting to think that maybe there is some other part in your code that is doing the deselection?

**Comment by patchthecode** [comment]
closing issue as more than 3 days without response. Will re-open once you respond.
I've added the `Awaiting-user-response` tag. thanks.
