### ISSUE TITLE
Scrolling to previous month is unavailable

### ISSUE THREAD

**Issue by ridvank** [patchthecode/JTAppleCalendar#684]
Hi there!
I am using 7.1.5 version of JTAppleCalendar. I am having an issue that when I select a date out of the current month, then scrolling to date by using `calendarView.scrollToDate(date)`. However when I try to go back to previous month by using a button or gesture. I am unavailable to do it as you see in the gif.
Any help would be appreciated!
![error](https://user-images.githubusercontent.com/6060649/35156230-46961cac-fd41-11e7-9dcc-3a7fafdb6c4e.gif)

**Comment by hartjosh** [comment]
what's in your `    public func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {}` method?

**Comment by ridvank** [comment]
Here it is my configureCalendar method
```
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        dateFormatter.dateFormat = "yyyy MM dd"
        dateFormatter.timeZone = Calendar.current.timeZone
        dateFormatter.locale = Calendar.current.locale
        
        let startDate = dateFormatter.date(from: "2018 01 01") ?? Date()
        let endDate = dateFormatter.date(from: "2019 01 01") ?? Date()
        
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate)
        return parameters
    }
```

**Comment by hartjosh** [comment]
where did u put this?  `calendarView.scrollToDate(date)` ?

**Comment by ridvank** [comment]
Inside this delegate method:
```
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        calendarView.scrollToDate(date)
    }
```

**Comment by hartjosh** [comment]
That function gets called whenever you go to a new month, multiple times.  I would only suggest using calendarView.scrollToDate in your viewDidLoad or viewDidAppear so that your user goes to that specific date.  Try removing it from there and implementing it somewhere else.

**Comment by ridvank** [comment]
Is there any efficient way to change the month when selecting a date which is out of current month?

**Comment by hartjosh** [comment]
yes try this:

`    /** Sets up the Next and Previous buttons on the calendar with their actions */
    private func setupButtonActions() {
        previousButton?.addTarget(self,
                                  action: #selector(gotoPreviousMonth),
                                  for: .touchUpInside)
        nextButton?.addTarget(self,
                              action: #selector(gotoNextMonth),
                              for: .touchUpInside)
    }

    /** Goes to the next month on the calendar */
    @objc private func gotoNextMonth() {
        self.calendarView?.scrollToSegment(.next, animateScroll: false)
    }

    /** Goes to the previous month on the calendar */
    @objc private func gotoPreviousMonth() {
        self.calendarView?.scrollToSegment(.previous, animateScroll: false)
    }`

**Comment by ridvank** [comment]
Thanks for your responses!
