### ISSUE TITLE
Wrong date in `cellState` but current `cellState.text`

### ISSUE THREAD

**Issue by vahids** [patchthecode/JTAppleCalendar#685]
I'm using version 7.1.5 -> JTAppleCalendar (7.1.5)

calendar is correct  but when I select a date, the selected date has a wrong date. It's seems like to have a day before of correct date.

I add a break point on `configCell` delegate. the `cellState.date` was wrong there too but `cellState.text` showing correct date.

<img width="1181" alt="datepicker" src="https://user-images.githubusercontent.com/1405424/35192490-dc8416de-fea8-11e7-946a-35622b34c4bc.png">

**Comment by patchthecode** [comment]
i think your issue is this one 
https://github.com/patchthecode/JTAppleCalendar/issues/252

let me know

**Comment by vahids** [comment]
Your God damn right!
Thanks ;-)
```swift
    let formater = DateFormatter()
    formater.dateStyle = .long
    print(formater.string(from: date))

this way to print show the correct date.
