### ISSUE TITLE
Value of type 'JTAppleCalendarView' has no member 'isDateInToday'

### ISSUE THREAD

**Issue by vahids** [patchthecode/JTAppleCalendar#686]
My version is 7.1.5

I want to highlight current day but `isDateInToday' not found.
Did you remove it?

Thanks.

**Comment by patchthecode** [comment]
I never had such a function.
Where are you using it?

**Comment by vahids** [comment]
Sorry I tried to highlight current date and It was my mistake that I called `calendar. isDateInToday()` instead of `Calendar.current. isDateInToday()`

sorry again and Thanks for your mazing customizable lib.
