### ISSUE TITLE
Mirroring Persian / Arabic calendar on changing device orientation 

### ISSUE THREAD

**Issue by vahids** [patchthecode/JTAppleCalendar#687]
I'm using JTAppleCalendar 7.1.5

Hi, I checked Persian/Farsi/Jalali and Arabic/Islamic calendar:

![correct](https://user-images.githubusercontent.com/1405424/35197808-6e65f8b4-fefa-11e7-8311-c8a241e3d772.png)

 all working well except if I change device orientation, calendar will be mirrored:

![Wrong](https://user-images.githubusercontent.com/1405424/35197812-8644d4d2-fefa-11e7-8555-e89e59d21b56.png)

It's not be fixed If I back to first orientation:

![wrong](https://user-images.githubusercontent.com/1405424/35197838-05909334-fefb-11e7-8bc9-688a331ade72.png)

I can handle it by calling `self.calendar.reloadData()` on changing device orientation. 
I just want to share it with you and I'm ready to every kind of test you need for Persian/Arabic calendars. 

It's gone be fixed If I scroll 3 or 4 month and back. seems like it's `UICollectionView` reusable related.

**Comment by patchthecode** [comment]
how do you currently resolve it?
let me know so i record to fix later.

**Comment by vahids** [comment]
I didn't, my application device rotation is locked.
I'll let you know If I fix it later.

**Comment by patchthecode** [comment]
closing issue until response :)
I added the awaiting user-input flag
