### ISSUE TITLE
[SUGGESTION] Community Examples

### ISSUE THREAD

**Issue by d-srd** [patchthecode/JTAppleCalendar#688]
Working with this library has been an absolute pleasure, saving me tons of time I'd have otherwise spent implementing my own calendar. I'd like to give back to the community in some way, and IMHO having more examples would be beneficial for anyone wanting to use this library as it would offer some insight about how it might be implemented.

Therefore, I would like to suggest making a new repository solely for hosting community contributed calendar examples including code, designs, and whatnot. Maybe even just a submodule in this repo would work fine.

What are your thoughts on this? Is it feasible?

**Comment by patchthecode** [comment]
Very feasible. I'm not sure how to create a sub module though.
I can look that up over the weekend. I've just been ery busy over the last 3 months.

**Comment by patchthecode** [comment]
added to tasks.
closing issue.
