### ISSUE TITLE
Calendar Modes (Week and Month)

### ISSUE THREAD

**Issue by diogoAntunes** [patchthecode/JTAppleCalendar#689]
Thank you for all the hard work on this library, it is a lifesaver 👍 

I was trying to create a Month calendar, and a Week calendar, I was looking trough the readme and found out that we suppose to have a week/month mode?

> Week/month mode - show 1 row of weekdays. Or 2, 3 or 6

But upon browsing the source code I'm not sure how is this accomplished, any hints? Thank you

**Comment by d-srd** [comment]
I’ve implemented this. It’s relatively simple. For weekly view: tell your dataSource to use 1 row, no strict boundaries and to generate out dates for first month only. For monthly view: 6 rows, strict boundaries, all out dates. Then just call reloadData on the calendar view after the switch.

**Comment by patchthecode** [comment]
@d-srd is right correct.
I wi was asked about single row calendar so much, i put in in here -> https://github.com/patchthecode/JTAppleCalendar/issues/581
