### ISSUE TITLE
nil unwrap 4.1.1 using selectDates(trigger: false)

### ISSUE THREAD

**Issue by krisanthony** [patchthecode/JTAppleCalendar#69]
Getting a `unexpectedly found nil while unwrapping an Optional value` at line 174 `let index = self.theSelectedIndexPaths.indexOf(oldIndexPath)!`

I am selecting dates with triggerDelegate set to false.

**Comment by patchthecode** [comment]
there in chat?

**Comment by patchthecode** [comment]
Oh damn, i forgot to make it a contitional unwrap >_<
fixing this now

**Comment by patchthecode** [comment]
1. Is multiSelect enabled?
2. When are you selecting the date cells? is it on viewDidLoad()
3. I have more questions to ask.

if youre in chat, then let me know --> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Ok. I have re-created the issue. Checking now.

**Comment by patchthecode** [comment]
I have push a change to master branch. Can you test the master branch?

Change your pod to have this -> 
`pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'`

**Comment by patchthecode** [comment]
Released path. update to version 4.1.2

**Comment by krisanthony** [comment]
yep that was it works great!

**Comment by patchthecode** [comment]
Cheers
