### ISSUE TITLE
Prevent displaying empty row when cells ares divided by months

### ISSUE THREAD

**Issue by kukushi** [patchthecode/JTAppleCalendar#690]
Great work, guys! Its really powerful and easy to use.

I'm using the latest version (7.1.5).
I have been using `cellState.dateBelongsTo == .thisMonth` to determine whether a cell should be display so that the cells and divided by months. The problem is there is always a empty row between two months which I want to get rid of. I have checked the source code but didn't find any hints.
I wonder if there is any way to implement that?

**Comment by patchthecode** [comment]
@kukushi explain empty row?
screenshot might help here thanks.

**Comment by kukushi** [comment]
@patchthecode Thanks for the quick reply.
Here is the screenshot. The areas arrow point to are the empty rows.

![simulator screen shot - iphone 8 plus - 2018-01-24 at 12 22 35](https://user-images.githubusercontent.com/2424654/35314533-cb6db4bc-0101-11e8-9903-3cd163369720.png)

**Comment by patchthecode** [comment]
Oh. thats easy.
in your `configureCalendarFuntion`, just set the `generateOutDates` to  = .endOfRow

**Comment by kukushi** [comment]
It works! Thanks a lot!

**Comment by patchthecode** [comment]
cool.
