### ISSUE TITLE
Localization Months

### ISSUE THREAD

**Issue by enrico07** [patchthecode/JTAppleCalendar#691]
I have a question. I'm using the latest version, is it possible to translate into other languages the month label?

![simulator screen shot - iphone 8 plus - 2018-01-24 at 19 16 09](https://user-images.githubusercontent.com/35777652/35349409-232ad958-013b-11e8-82f8-f4e33a7b8639.png)

**Comment by hartjosh** [comment]
Developers can do this on their own.   This is a great tutorial: https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881

**Comment by enrico07** [comment]
Perfect, thanks.

**Comment by patchthecode** [comment]
closing this issue. as resonved. Thanks guys.
