### ISSUE TITLE
Would You Be Willing To Make The Value For `endScrollTargetLocation` Publicly Accessible?

### ISSUE THREAD

**Issue by DominicMDev** [patchthecode/JTAppleCalendar#692]
**Version: 7.1.5**

Hello,

I was wondering if you could make the value for `endScrollTargetLocation` publicly accessible.

I am working on a calendar that has a banner that displays the month and year while scrolling.
You can see the view fade in and out at the top of the calendar in this GIF:
![calendarscroll](https://user-images.githubusercontent.com/32944376/35352802-f2455ee4-00f9-11e8-9477-96abad8c5e53.gif)

I am using the value of `endScrollTargetLocation` after I changed it to a public internal(set) var in *JTAppleCalendarView.swift*:
`81| public internal(set) var endScrollTargetLocation: CGFloat = 0`

Below is where I am using the variable in my ViewController.

    private func startHandlingYearBanner() {
                timer = Timer.scheduledTimer(timeInterval: 0.1,
                                             target: self,
                                             selector: #selector(handleYearBanner),
                                             userInfo: nil,
                                             repeats: true)
        
        RunLoop.main.add(yearBannerHandlingTimer!, forMode: RunLoopMode.commonModes)
    }
    
    @objc private func handleYearBanner() {
        updateYearBannerText()
        
        let hideBannerOffsetPoint = isScrollingDown() ?
          calendarView.endScrollTargetLocation - 60 : calendarView.endScrollTargetLocation + 60
        
        if ((isScrollingDown() && calendarView.contentOffset.y >= hideBannerOffsetPoint) ||
           (!isScrollingDown() && calendarView.contentOffset.y <= hideBannerOffsetPoint)) {

            hideYearBanner()
        }
    }
    
    private func isScrollingDown() -> Bool {
        return calendarView.contentOffset.y < calendarView.endScrollTargetLocation
    }

Please let me know if you would be willing to either:

- make `endScrollTargetLocation` a public internal(set) var

_or_

- create a publicly accessible computed property on `JTAppleCalendarView` that returns the value of `endScrollTargetLocation`

Thank you.

**Comment by patchthecode** [comment]
I'll relook this over the weekend.

**Comment by patchthecode** [comment]
Got caught up in work. 
If you have used it as public, and it works and is useful to you, then it can be useful to someone else. 
I make this public shortly.

**Comment by DominicMDev** [comment]
@patchthecode When do you think you can get this in a release?

**Comment by patchthecode** [comment]
can this function work for you?
```swift
func calendar(_ calendar: JTAppleCalendarView, willScrollToDateSegmentWith visibleDates: DateSegmentInfo) {}
```

its on public 7.1.6

**Comment by patchthecode** [comment]
assuming resolved. closing issue.
