### ISSUE TITLE
Crash on iPad

### ISSUE THREAD

**Issue by oskarko** [patchthecode/JTAppleCalendar#693]
Hi, I was doing an app for iPhone but before launching it on AppStore I have changed to Universal and now it isn't loading... it crashes!

```swift
// *** JTAppleCalendarView POD
func targetPointForItemAt(indexPath: IndexPath) -> CGPoint? {
        guard let targetCellFrame = calendarViewLayout.layoutAttributesForItem(at: indexPath)?.frame else { // Jt101 This was changed !!
            return nil
        }
        
        let theTargetContentOffset: CGFloat = scrollDirection == .horizontal ? targetCellFrame.origin.x : targetCellFrame.origin.y
        var fixedScrollSize: CGFloat = 0
        switch scrollingMode {
        case .stopAtEachSection, .stopAtEachCalendarFrameWidth, .nonStopToSection:
            if self.scrollDirection == .horizontal || (scrollDirection == .vertical && !calendarViewLayout.thereAreHeaders) {
                // Horizontal has a fixed width.
                // Vertical with no header has fixed height
                fixedScrollSize = calendarViewLayout.sizeOfContentForSection(0)
            } else {
                // JT101 will remodel this code. Just a quick fix
                fixedScrollSize = calendarViewLayout.sizeOfContentForSection(0)
            }
        case .stopAtEach(customInterval: let customVal):
            fixedScrollSize = customVal
        default:
            break
        }
        
        let section = CGFloat(Int(theTargetContentOffset / fixedScrollSize)) <--- HERE
        let destinationRectOffset = (fixedScrollSize * section)
        var x: CGFloat = 0
        var y: CGFloat = 0
        if scrollDirection == .horizontal {
            x = destinationRectOffset
        } else {
            y = destinationRectOffset
        }
        return CGPoint(x: x, y: y)
    }
```

any solution to fix this?

**Comment by oskarko** [comment]
I have changed to pod 7.1.5 and the code changed to

***
func targetPointForItemAt(indexPath: IndexPath) -> CGPoint? {
        guard let targetCellFrame = calendarViewLayout.layoutAttributesForItem(at: indexPath)?.frame else { // Jt101 This was changed !!
            return nil
        }
        
        let theTargetContentOffset: CGFloat = scrollDirection == .horizontal ? targetCellFrame.origin.x : targetCellFrame.origin.y
        var fixedScrollSize: CGFloat = 0
        switch scrollingMode {
        case .stopAtEachSection, .stopAtEachCalendarFrame, .nonStopToSection:
            if scrollDirection == .horizontal || (scrollDirection == .vertical && !calendarViewLayout.thereAreHeaders) {
                // Horizontal has a fixed width.
                // Vertical with no header has fixed height
                fixedScrollSize = calendarViewLayout.sizeOfContentForSection(0)
            } else {
                // JT101 will remodel this code. Just a quick fix
                fixedScrollSize = calendarViewLayout.sizeOfContentForSection(0)
            }
        case .stopAtEach(customInterval: let customVal):
            fixedScrollSize = customVal
        default:
            break
        }
        
        var section = theTargetContentOffset / fixedScrollSize
        let roundedSection = round(section)
        if abs(roundedSection - section) < errorDelta { section = roundedSection }
        section = CGFloat(Int(section)) <--- HERE NOW! section is NAN!!!!
        
        let destinationRectOffset = (fixedScrollSize * section)
        var x: CGFloat = 0
        var y: CGFloat = 0
        if scrollDirection == .horizontal {
            x = destinationRectOffset
        } else {
            y = destinationRectOffset
        }
        return CGPoint(x: x, y: y)
    }
***

it still crashes!

**Comment by patchthecode** [comment]
Help me a bit please.

On what simulator does it crash?
Is it possible you can debug the value the library is crashing on at that point?

**Comment by oskarko** [comment]
Sure, it crashes on iPad air (iOS 10.1) emulator. The value is always 0 / 0 = NaN.

**Comment by patchthecode** [comment]
can you message me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by oskarko** [comment]
I'm in right now

**Comment by oskarko** [comment]
You can close it. I have fixed it. The app needed constraints for iPads too, not iPhone only.

**Comment by patchthecode** [comment]
hmm. ok.
So it was a problem with constraints?
This shouldnt crash the library though. I will do a check againstdivide by 0 errors.
thanks.
