### ISSUE TITLE
Implement SectionHeaders

### ISSUE THREAD

**Issue by csontosgabor** [patchthecode/JTAppleCalendar#694]
Hello!

Thanks for this awesome library.
Is it possible to implement the headers for months? Maybe I missed something, or this version doesn't support this feature?

Also how can I set today's date?

**Comment by patchthecode** [comment]
can this guy's example help you? -> https://github.com/patchthecode/WLAppleCalendar

**Comment by patchthecode** [comment]
also the video here shows you how to implement headers -> https://www.youtube.com/watch?v=CQNotydm58s

Closing this issue now, but if you still need more guidance, then let me know.

**Comment by csontosgabor** [comment]
Thanks for the help! :) And the library. Awesome! :)

**Comment by patchthecode** [comment]
cool.
