### ISSUE TITLE
Change the properties of future cells on a single cell selection

### ISSUE THREAD

**Issue by hartjosh** [patchthecode/JTAppleCalendar#696]
Using 7.1.5.

I want to change the properties of future dates when a user selects a date.  I was looking at the dateRange stuff and I am not sure that will fulfill the requirements for the task I have at hand.  

Practically what I need to do, is after the user taps on a date, is highlight future dates (for shipping and handling purposes).  So user orders something on tuesday and I want to highlight all the days by changing a custom UIView within the calendarCell, and then select the future date (let's say the future date is friday).  Is there an easy way to accomplish this?  Forgive me if this has already been addressed somewhere, I have been going through the resolved tickets looking for something that would help, but was unable to find anything that addressed this specific feature.  Thanks, and thank you for such a stable and customizable library!  :)

**Comment by patchthecode** [comment]
Hmm.
Yes you can highlight future dates.

First, you must have your calendar to enable multiselection. You can do this in your viewDidLoad()
```
calendarView.allowsMultiDelection= true
```
Assuming you have an array of `[FutureDates]` in an array ready,
in your `didSelectDate` function, you can call
```swift
calendar.deselectDates(theOldFutureDates)
calendar.selectDates(theNewFutureDates)
```

This will deselect the old future dates if, select the new future dates that should be selected.
Not sure if this helps?

**Comment by hartjosh** [comment]
Is there a specific way to reload all visible dates?

**Comment by patchthecode** [comment]
Just use.
```swift
calendarView.reloadData()
```

But if you properly implementedthe following funcitons:
1. didSelect
2. didDeselect
3. CellForItemAt
4. WillDisplayCell

Then the library should correctly reload the dates you want **if those dates relate to selection**.
If your future dates are just random dates you chose however, then `calendarView.reloadData` should just reload every thing on the screen (the visible dates)

**Comment by patchthecode** [comment]
closing issue.
