### ISSUE TITLE
cornerRadius isn't creating a circle for the cell background

### ISSUE THREAD

**Issue by mymikemiller** [patchthecode/JTAppleCalendar#697]
I've been following the video tutorial with the latest version and the little yellow circle that's supposed to be in the background of the dates when selected is not properly turning into a circle. 

It seems to have something to do with the combination of cornerRadius and the constraints. I have everything set up as it is in the tutorial and I'm getting a slightly-rounded-cornered-square instead of a circle, and if I increase the cornerRadius, I get a diamond.

This doesn't happen for cells in a normal collection view, just the date cells in the JTAppleCalendarView. Any ideas what's going wrong?

<img width="1406" alt="screen shot 2018-01-28 at 4 23 41 pm" src="https://user-images.githubusercontent.com/2063229/35488624-a5d78e18-0448-11e8-9a97-889053c013d6.png">

**Comment by mymikemiller** [comment]
I figured this out. I wasn't properly setting the minimum line spacing and minimum inter-item spacing, which resulted in the circle getting cut off by the cell:

        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0

**Comment by patchthecode** [comment]
I was gonna get to that today.
Glad you figured it out. cool.
