### ISSUE TITLE
selectDates() doesn't always deselect previous date

### ISSUE THREAD

**Issue by rvirta** [patchthecode/JTAppleCalendar#698]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by rvirta** [comment]
Hi,

I'm using a button to sroll back to today and select today, but I've run into a situation where it leaves the previously selected date also selected, or does not hide the selectedView used to mark selection. The code for the button is simply 
```
@IBAction func toggleButton(_ sender: UIButton) {
        if calendarVisible {
            self.calendarView.scrollToDate(Date())
            self.calendarView.selectDates([Date()])
        }
        else {       
        }   
    }
```
and I don't have any idea what else could be affecting it. It only seems to hapen on this particular date, nowhere else. It's the 29th today, and when 31st is selected and the button is pressed, it leaves the 31st also selected.

Any ideas?
<img width="342" alt="screen shot 2018-01-29 at 3 19 02" src="https://user-images.githubusercontent.com/13588210/35489846-7705614a-04a3-11e8-81a7-4fed61e66121.png">

**Comment by rvirta** [comment]
Version 7.1.5 :)

**Comment by patchthecode** [comment]
Can you paste me your `willDisplayCell` code ?

**Comment by patchthecode** [comment]
closing this issue. As i believe you might have not implemented the `willDisplayCell` function as stated non the main page. Instructions are here -> #553
