### ISSUE TITLE
Selected date in previous month not getting deselected even if user click on a date in other month.

### ISSUE THREAD

**Issue by ThilinaHewagama** [patchthecode/JTAppleCalendar#699]
JTAppleCalendar pod version 7.1.5

**Step 1:** Click on last date of the current month.
**Step 2:** Scroll to next month.
Observation: You can still see a date in last month is selected.
**Step 3:** You select another date in calendar.
Observation: Two dates are selected in same screen. _(Previous's month's selected date not getting deselected)_.

**Preview LINK:** [https://ibb.co/mKTwUG](https://ibb.co/mKTwUG)

**Comment by patchthecode** [comment]
@ThilinaHewagama 
can you show me the source code for your `willDisplayCell` function ?

**Comment by ThilinaHewagama** [comment]
sure. It's empty.
Preview: https://ibb.co/kEDdbw

**Comment by patchthecode** [comment]
can you implement it to this? -> https://github.com/patchthecode/JTAppleCalendar/issues/553
Its important and was stated on the main page 🙃
Let me know if your issue was resolved.

**Comment by ThilinaHewagama** [comment]
That worked! Thank You for your time.
I followed this tutorial, https://www.youtube.com/watch?v=Qd_Gc67xzlw. That's not updated I think.

**Comment by patchthecode** [comment]
Yea its cool.
Its sad i cant just edit the vid and re-upload.
have a good one man.
