### ISSUE TITLE
change dateformatter

### ISSUE THREAD

**Issue by J-phantom** [patchthecode/JTAppleCalendar#7]
hi
how can change date formatter to jalali and change style number ?? 
thanks for help ??

**Comment by patchthecode** [comment]
Have you looked at the tutorial?
CellView.xib

1. Changing the font
Go there and change the font of the text to what ever you want.

2. Changing the date formatter
Look at the delegate setup function 
`func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, calendar: NSCalendar)
`
You provide you own calendar in there. Setup the calendar to what ever you want it to be.

**Comment by J-phantom** [comment]
sorry i want change month name ? but i can not change ??

**Comment by J-phantom** [comment]
I don't want to just change font i want change style ,look a picture 
![unnamed](https://cloud.githubusercontent.com/assets/11584951/14470937/f6bbaf1a-00a0-11e6-85f8-5505c584110a.png)

**Comment by patchthecode** [comment]
Take a look at the tutorial. You can the sign the CellView.xib however you want.
<img width="397" alt="screen shot 2016-04-12 at 11 53 35 am" src="https://cloud.githubusercontent.com/assets/2439146/14471849/4d100772-00a5-11e6-95ba-d9e3daf7f5d3.png">

**Comment by J-phantom** [comment]
yes

**Comment by patchthecode** [comment]
Damn!  that calendar looks awesome!! Hey, can you post up your calendar picture on this link? I want other people to see the cool stuff they can do with it. --> https://github.com/patchthecode/JTAppleCalendar/issues/2

**Comment by patchthecode** [comment]
So have you found a solution to your question now? Or do you still need help

**Comment by patchthecode** [comment]
Hey, if you are able to build your calendar, can i use your image as an example in my documentation?

**Comment by J-phantom** [comment]
yeah .sure

**Comment by patchthecode** [comment]
Cool. when you are finished with you. You can upload the image here -> https://github.com/patchthecode/JTAppleCalendar/issues/2
