### ISSUE TITLE
UIPickerView & JTAppleCalendar

### ISSUE THREAD

**Issue by Nsglidden** [patchthecode/JTAppleCalendar#700]
Hello, 

SUPER great library, I am just beginning to code and I love your tutorials. I do have a question on configuring the calendar. I followed and completed your tutorials, and made a working calendar.
Then, I had an idea.. 

What if I wanted to use a UIPickerView instead of a UICollectionView, that way users could drag until the desired date was in focus?

I attempted to do this and I can't make the UIPickerView custom class the "JTAppleCalendarView" Is there any other way I could accomplish this? 

Thanks,
Nick Glidden

**Comment by patchthecode** [comment]
Hmm. That would not be possible.
That UICollectionView has a `UICollectionViewLayout` under the hood which i use to calculate and change the way the layout looks based on the developers use-case. Without this being present I do not think it can work with a UIPickerView. This is my thought on it.

However, maybe i might be mistaken. Probably if you show me an image of what you are trying to accomplish? But for now, I do not think it is possible.
