### ISSUE TITLE
Is there one delegate callback if the selected dates have changed? Not didDeselectDate and didSelectDate

### ISSUE THREAD

**Issue by georgbachmann** [patchthecode/JTAppleCalendar#702]
Hello,
I am using Version 7.1.5 of JTAppleCalendar
I am wondering if I just didn't see it... There are delegate methods for `didSelectDate` and `didDeselectDate`... but there is nothing like `selectedDatesDidChange` or so, right?

I am asking because:
I have a date selected
Now I select a new date
that triggers the `didDeselect` and then right after that the `didSelectDate`...

I'd be reloading my data with that information, but if I react to both callbacks, I'd have to then reload twice. One time for no more selected date, and then again with the newly selected date...

So it would be cool, to have a delegate callback, if date-selection is done?!?

Or am I simply overseeing something?!?

**Comment by patchthecode** [comment]
hmm. cant we just use `didSelectDate` ?
This function will trigger every time `selectedDatesDidChange`.
Unless i am missing something in your question?

**Comment by georgbachmann** [comment]
Hey there,
but what if the user wants to unselect a date and afterwards there is no more date selected? (Even though I don't yet know how to unselect a date :) cause selecting it again will keep it selected...)
cheers,
Georg

**Comment by patchthecode** [comment]
This calendar was build from a UICollectionView and therefore it has the same properties.
If you want cells to be deselected when you tap them again, you'll have to set multiselection = true.

```swift
calendarView.allowsMultipleSelection = true
```

**Comment by georgbachmann** [comment]
I updated my answer, so your Email-Notification might have been old :) sorry... 
I figured that out already... but still... simply observing `didSelectDate` would not trigger if you unselect the last selected date...

**Comment by patchthecode** [comment]
@georgbachmann ok, i see what you mean.
You want a unified function that detects on if a function is selected, or if a function is deselected.
hmm.. I didnt do this beacause I wanted the lib to be as close to a UICollectionView as possible.

I know dateChange detection  is split into 2 functions, but dont blame me, blame Apple 😅. They dont have a unified funciton detecting changes on their UICollectionView, so i folllowed that pattern.  But in the mean time, we can detect changes in those two funcitons.

Here's an idea. You can create a unified function called 
```swift
enum MyType {
   case selected, deselected
}
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
   self.calendar(calendar, selectionChangedFor: date, cell: cell, cellState: cellState, action: .selected)
}

func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
   self.calendar(calendar, selectionChangedFor: date, cell: cell, cellState: cellState, action: .deselected)
}

func calendar(_ calendar: JTAppleCalendarView, selectionChangedFor date: Date, cell: JTAppleCell?, cellState: CellState, action: MyType) {
    /// put your code here
}

Does this work for you ?

**Comment by georgbachmann** [comment]
Hey @patchthecode ... sure... I do it that way currently :) But it will trigger one reload that would be sensless... but never mind... :)
I already have an idea on how to solve the problem...
Thank you anyway!

**Comment by patchthecode** [comment]
awesome.
i do not think that it has to do a reload needlessly. But if you've solved it. awesome.
closing this issue.
