### ISSUE TITLE
 after i updated to 10.13.1 and update Xcode 9.1 i keep getting Type 'ViewController' does not conform to protocol 'JTAppleCalendarViewDelegate', it didn't do this before i updated help please

### ISSUE THREAD

**Issue by Reecelandry** [patchthecode/JTAppleCalendar#703]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
click on the erroe. XCode should tell you what you are missing in order to conform the protocol.
But i suspect that you are missing the `willDisplayCell`` function mentioned here #553

**Comment by Reecelandry** [comment]
Thanks and what code should go in the 2 methods? The willDisplayCell and
the other one?

**Comment by patchthecode** [comment]
It was explained here in this issue -> #553

**Comment by Reecelandry** [comment]
I was a little confused reading it. could you help me fill out the last
method? here is my code


extension CalendarViewController:  JTAppleCalendarViewDelegate,
JTAppleCalendarViewDataSource{

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell:
JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath:
IndexPath) {

        <#code#>

    }



func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date,
cellState:

    CellState, indexPath: IndexPath) -> JTAppleCell {



    let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier:
"CustomCell", for:

        indexPath) as! CustomCell



    cell.dateLabel.text = cellState.text



    return cell



}

func configureCalendar(_ calendar: JTAppleCalendarView) ->
ConfigurationParameters {

    formatter.dateFormat = "yyyy MM dd"

    formatter.timeZone = Calendar.current.timeZone

    formatter.locale = Calendar.current.locale



    let startDate = formatter.date(from:"2017 01 01")

    let endDate = formatter.date(from: "2018 01 01")



    let parameters = ConfigurationParameters(startDate: startDate!,
endDate: endDate!)

    return parameters

}

}



what do i  put in the <#code#>

**Comment by Reecelandry** [comment]
I downloaded your xcode project and dragged that forder into my project and
i got it to work. Thanks

**Comment by patchthecode** [comment]
awesome. closing this issue :)

**Comment by amank97** [comment]
hello

I seem to be getting the exact same problem and I've looked at the issue that was explained but its still not working. 

I hope to hear from you

**Comment by Reecelandry** [comment]
I have fixed mine. You have to ensure your class name of your calendar
viewcontroller is the same as the extensions at the bottom of the code.

Hope this helped


Reece Landry Vlogs

**Comment by amank97** [comment]
I'm afraid I don't understand. My class name is the same. I just don't know what to put in the function.  What is supposed to go in this function

func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        //code missing
    }
