### ISSUE TITLE
Up to date tutorial for the latest version (7.1.5)

### ISSUE THREAD

**Issue by olufolarin92** [patchthecode/JTAppleCalendar#704]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I have installed the latest version of JTAppleCalendar using Cocoapods (7.1.5) however I can't find a clear error free working tutorial to get the initial calendar running. I have called the three protocol functions and correctly coded them, however the problem always seems to come in the ViewDidLoad() function when setting the dataSource and the delegate to self. I am using a collectionView as was shown in the Youtube tutorials. Any help will be GREATLY appreciated.

**Comment by patchthecode** [comment]
the tutorials online work.
But since the tutorials were done one part of the code was updated.
You need to implement the function called `willDisplayCell`. The instruction were given on the main page of thig github  project. Here it is --> #553

**Comment by olufolarin92** [comment]
Okay, thank you very much for the quick reply. Just for clarification, what is the testCalendar in the if statement,  and where is it defined? (referring to the sharedFunctionToConfigureCell function)

**Comment by patchthecode** [comment]
ok, you can put what ever code you have in there.
But in my sample code, testCalendar = a calendar instance (not the JTAppleCalendar library).

```swift
let testCalendar = Calendar()
```

After you **configure** it, you can use it to find out if the date you have is "today" date.

**Comment by olufolarin92** [comment]
Do you have a zip to the sample code, or something I can run with just a simple configuration so I can compare it with what I have to get to the issue my demo is giving me. Because I updated the protocols but still get the same thread error when I add in calendarDataSource = self and calendarDelegate = self. A basic demo would be greatly appreciated because I'm eager to add this framework to my design, its just taking me unusually long to get my head around

**Comment by patchthecode** [comment]
This guy createed a calendar with this library -> https://github.com/patchthecode/WLAppleCalendar
Also we have a sample project attached to this github repo.
If you still need a simpler sample app. I can create one.
Does it help?

**Comment by patchthecode** [comment]
closing this issue.

Documentation on this is added on main page of github repository.
