### ISSUE TITLE
Need a hint to use CellState.cell

### ISSUE THREAD

**Issue by strike65** [patchthecode/JTAppleCalendar#705]
Hi!

I'm using version 7.1.5.

Maybe a stupid question, but how can I get a cell of the calendar view. I've created a subclass from JTAppleCell (MyCalendarCell). Using

```Swift
let status: CellState = self.calendarView.cellStatus(for: date)
```
returns the cell state as expected. But I'm not be able to get the cell itself. It's highly possible, that I'm doing something wrong due to my lack of knowledge. When I try to get the cell by
```Swift
var cell = status.cell
```

"cell" contains a kind of a function: 
```Swift
(lldb) po cell
(Function)
```

My question is: How can I actually get the cell (as MyCalendarCell) to access some custom properties of the cell. 

Thanks in advance!

**Comment by patchthecode** [comment]
i think it returns a function.
therefore, call 
```swift
let the cell = cell()
```
However, please note that the cell will be `nil` if it is not visible on the screen.

**Comment by strike65** [comment]
Thanks for your quick response. I'll try it tomorrow... Will report the result.

Thanks again!

**Comment by strike65** [comment]
It works. It was so easy. Did not see the forest for the trees.

Thanks!

**Comment by patchthecode** [comment]
awesome.
