### ISSUE TITLE
a willScrollToDateSegmentWith with the parameters of didScrollToDateSegmentWith

### ISSUE THREAD

**Issue by uholland** [patchthecode/JTAppleCalendar#706]
Hi,
I would like to adjust the visible height of the calendar in dependence of the row count of .thisMonth days. But animating this after the scrolling of a month page is done doesn't look tight. So it would be ace if you could call a willScrollToDateSegmentWith as soon as the user releases the touch with the same params as didScrollToDateSegmentWith so that I could start animating earlier. It's just a small detail with a great impact. Any chance? Thanks!
Uwe

**Comment by patchthecode** [comment]
can this example calendar help you? https://github.com/patchthecode/WLAppleCalendar

**Comment by uholland** [comment]
Yes, that's what I want to achieve. But this calendar got exactly the issue I'm talking about. The lower frame starts animating when the scrolling of the calendar is DONE. I want to start the animation the lower frame when user releases the finger on scroll (like the Apple Calendar behaves).

**Comment by patchthecode** [comment]
hmm..
ok, i'm @ work now. let me think on this

**Comment by uholland** [comment]
Awesome, thanks!

**Comment by uholland** [comment]
Hi, did you have some time to think about it?

**Comment by patchthecode** [comment]
Sorry, got very tied up with other projects.
I can put this as an enhancement. But since i'm a little tied up it will take some time.
I just set the enhancement flag to this.

**Comment by uholland** [comment]
Awesome, thank you!

**Comment by patchthecode** [comment]
This has been implemented here -> https://github.com/patchthecode/JTAppleCalendar/issues/760
closing this issue
