### ISSUE TITLE
Ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by kevintorch** [patchthecode/JTAppleCalendar#707]
After installing manually and building...it says 'SelectionType' is ambiguous for type lookup in this context...
how do i solve it

**Comment by patchthecode** [comment]
In what file are you seeing this error?

**Comment by kevintorch** [comment]
CalendarEnums

**Comment by kevintorch** [comment]
in CalendarEnums.swift file

**Comment by kevintorch** [comment]
i solved it... i had 'CVCalendar' installed in my project. and 'CVCalendar' also has the type 'SelectionType'...so thats why it was ambiguating with your 'SelectionType'... so i remove the CVCalendar and it runs perfectly
