### ISSUE TITLE
Calendar is one row too far up

### ISSUE THREAD

**Issue by stkq** [patchthecode/JTAppleCalendar#71]
When I open the calendar, it is scrolled one row too far up. The user has to scroll down in order to get the month displayed correctly.

This is what it looks like initially:
![simulator2](https://cloud.githubusercontent.com/assets/20341573/16728513/a609852e-475e-11e6-8d32-adba80107bca.png)

This is what I want it to look like:
![simulator1](https://cloud.githubusercontent.com/assets/20341573/16728524/b1115bcc-475e-11e6-82b2-6a99aa38eac9.png)

**Comment by patchthecode** [comment]
You know, its kind of difficult for me to tell you anything with the information you have provided. When you ask your question, please ask it in "developer" mode :)

what kind of calendar? horizontal/vertical?
is paging enabled?
what does your viewDidLoad() calendar setup code look like? etc etc etc

give me more information surrounding what you did to get this to happen.

**Comment by stkq** [comment]
Here is some code:
```
        calendarView.direction = .Vertical                       // default is horizontal
        calendarView.cellInset = CGPoint(x: 0, y: 0)               // default is (3,3)
        calendarView.allowsMultipleSelection = false               // default is false
        calendarView.bufferTop = 0                                 // default is 0. - still work in progress on this
        calendarView.bufferBottom = 0                              // default is 0. - still work in progress on this
        calendarView.firstDayOfWeek = .Monday                      // default is Sunday
        calendarView.scrollEnabled = true                          // default is true
        calendarView.pagingEnabled = true                          // default is true
        calendarView.scrollResistance = 0.75                       // default is 0.75 - this is only applicable when paging is not enabled.
        calendarView.itemSize = nil                                // default is nil. Use a value here to change the size of your cells
        calendarView.cellSnapsToEdge = true                        // default is true. Disabling this causes calendar to not snap to grid
        calendarView.reloadData()
//        // After reloading. Scroll to your selected date, and setup your calendar
        calendarView.scrollToDate(NSDate(), triggerScrollToDateDelegate: false, animateScroll: false) {
            let currentDate = self.calendarView.currentCalendarDateSegment()
            self.setupViewsOfCalendar(currentDate.startDate, endDate: currentDate.endDate)
        }
```

**Comment by patchthecode** [comment]
What are your date boundaries?
What does your configureCalendar() code look like?

**Comment by stkq** [comment]
Not really. I made some changes like disabled the header but I did that in the sample project and it was fine. Here is my configureCalendar:

```
    func configureCalendar(calendar: JTAppleCalendarView) -> (startDate: NSDate, endDate: NSDate, numberOfRows: Int, calendar: NSCalendar) {
        let formatter = NSDateFormatter()
        formatter.dateFormat = "yyyy MM dd"
        let firstDate = formatter.dateFromString("2016 01 01")
        let secondDate = NSDate()
        let numberOfRows = 6
        let aCalendar = NSCalendar.currentCalendar()
        return (startDate: firstDate!, endDate: secondDate, numberOfRows: numberOfRows, calendar: aCalendar)
    }
```

**Comment by patchthecode** [comment]
hmm.. this is odd.
If it is working in the sample calendar, and its not working in yours, then something has to be different. I cannot recreate the issue you are facing on my code.

Since your project has just started (and you do not have any secret code in it yet i hope) then is it possible you can zip your project and drop it in this text box so i can have a look?

**Comment by stkq** [comment]
How do I send it directly to you?

**Comment by patchthecode** [comment]
you can just send it to my email. patchthecode@gmail.com

**Comment by patchthecode** [comment]
This will  be closed if no response in 24hrs. I will assume the problem has been resolved.
