### ISSUE TITLE
scrollToDate()

### ISSUE THREAD

**Issue by cvindhani** [patchthecode/JTAppleCalendar#710]
Hi,
I'm using latest pod version 7.1.5 and having issue with scrollToDate() func.
Whenever I'm passing current date into scrollToDate() and calls the func, it's directly jumps into next month of passed current date. I'm unable to determine what's wrong. I'm following steps for do so.
Can you please help me out to get this fixed.?
Thanks in advance.

**Comment by patchthecode** [comment]
do you have a sample app you can provide with this bug? like a zipped file or a github link?
or you can message me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
i guess this was fixed?
cool
