### ISSUE TITLE
Calendar not scrolling in UIView

### ISSUE THREAD

**Issue by ogezue** [patchthecode/JTAppleCalendar#712]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
7.1.5
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
Yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I added the Calendar in a separate XIB File and import it in a ViewContainer to keep my ViewController clean. I needed to import the Cell programmatically as it is not possible inside a XIB file, but this should not matter. The Calendar is displayed correctly and it scrolls programmatically.

But it doesn't scroll under my finger. Everything is like in your demo (first video) and in your sample app. (Interaction enabled, paging, bounces, ...). What can cause this?

**Comment by patchthecode** [comment]
@ogezue 

I'm not sure what problems you faced but.
1. You can implement your calendar with code, or with storyboard, or with XIB
2. You can implement your cells with code, or with storyboard, or with XIB

can you provide me your sample app via a zip file? if you upload it on gitbuh i can fix it for you.

**Comment by ogezue** [comment]
awesome - tank you. I will provide an example later :)

**Comment by ogezue** [comment]
[CalendarTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/1711994/CalendarTest.zip)

@patchthecode I could create a small example and I could figure out that there is a problem with another dependency called "EmptyDataSet-Swift". This one creates a view that is before the calendar-view. My touch doesn't reach the calendarView so this why it is not scrolling. The strange thing is, that  this view is inside the view hierarchy of the calendar collection view.

**Comment by patchthecode** [comment]
@ogezue 

> Another strange thing is why I get 6 rows with this configuration:
Not strange. This library has rows: 1, 2, 3, 6

You want a 4-row calendar? Can you show me a image of what you want the calendar to look like?

**Comment by ogezue** [comment]
My use case is that users need to select a date from a predefined date range (today until 7 to unlimited days). I don't want to waste to much screen size so if I need only 20 days there should be 5 rows if 20 days do not fit exactly into 3 rows if the first day of the week is always fix (linke Monday). Hope you can follow this explanation... Could you figure out the problem with EmptyDataSet?

**Comment by ogezue** [comment]
It seems that the EmptyDataSet problem is caused by EmptyDataSet, so the author will take care of it.

Regarding the row-number problem: Is it possible to get more flexibility and have 4 or 5 rows? And as a plus: Could I define where the month could start if I need only days 20 to 30 of a month? Days 1-19 wouldn't be necessary to be displayed.

**Comment by patchthecode** [comment]
regarding 4-row and 5-row, you will have to show me an image of how you want the months to look with 4 and 5 row.

Take 4 row for example. Please show me an image of how `Jan`, `Feb` and `Mar` will look with 4 row.
Because in my mind this will look unbalanced. But if you can show me how you want it to look, then maybe I can think of something. Having 4 rows on one month, will mean mean that another 2 rows will be hanging somewhere. I cannot visualize it.

**Comment by ogezue** [comment]
My use case is that the user needs to select a date between today and the next 14 days. So with the week starting on Monday I only would nee 2 rows where this fits in. Tomorrow this would nee 3 rows where the days where Monday in first row and the days from Tuesday are not selectable.

With your current solution this is what I have so far. 4 rows that are not needed
<img width="314" alt="bildschirmfoto 2018-02-12 um 10 04 43" src="https://user-images.githubusercontent.com/2361031/36089441-38a89ba8-0fdc-11e8-97bf-7bfd0b27693b.png">


For today my ideal solution would look like this.
<img width="320" alt="bildschirmfoto 2018-02-12 um 10 04 10" src="https://user-images.githubusercontent.com/2361031/36089447-43584f4e-0fdc-11e8-9a0e-48064708eba7.png">

Changing this would mean to have a new mode of your calendar. Currently you are focused on calendar month. The new mode would focus on date ranges with a reference to calendar. In my opinion this would enrich your library.

**Comment by patchthecode** [comment]
Hmm. lets talk some more on this.
I'll be online here here for most of the day -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
closing this issue as problem relates to other library.
I have put an enhancement flag on your other issue.

**Comment by patchthecode** [comment]
4 rows have now been added.
Im experimenting with it.
