### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by kevintorch** [patchthecode/JTAppleCalendar#713]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.
I need infinite scrolling to segments (next and previous)...how do I do this

**Comment by patchthecode** [comment]
This calendar does not come with infinite scrolling out of the box. 
You'll have to build it.

**Comment by kevintorch** [comment]
and how am i supposed to do that?

**Comment by patchthecode** [comment]
if i wrote up the code to tell you how to do it, then i would just put it into this library my self :)
But I didnt have the time to do so. So im hoping on someone to do a pull request.

There a a couple ways it can be done. The only one I can think of right now is, Load up about 20 years of dates. 10 behind the shown screen of the user, and 10 in-front of the shown screen os the user. If the user scrolls close to the end, then load anonther 20 years. 10 before, and 10 behind. That way, the user can scroll forever.

**Comment by patchthecode** [comment]
closing issue.
