### ISSUE TITLE
First day of week based on locale

### ISSUE THREAD

**Issue by rvirta** [patchthecode/JTAppleCalendar#714]
Hi,

How would I go about making the calendar change the first day between monday and sunday based on the users preferences in the iOS calendar?

Thanks!

**Comment by patchthecode** [comment]
paste me your `configureCalendar` function

**Comment by rvirta** [comment]
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale

        calendarStartingMonth = Date().getPreviousMonth().appMonth
        calendarStartingYear = Date().getPreviousMonth().appYear
        
        let startDate = formatter.date(from: calendarStartingYear + " " + calendarStartingMonth + " 01")
        let endDate = formatter.date(from: "2050 12 31")

        let parameters = ConfigurationParameters(startDate: startDate!, endDate: endDate!, firstDayOfWeek: DaysOfWeek.monday)
        
        return parameters
    }

Thanks!

**Comment by rvirta** [comment]
`func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale

        calendarStartingMonth = Date().getPreviousMonth().appMonth
        calendarStartingYear = Date().getPreviousMonth().appYear
        
        let startDate = formatter.date(from: calendarStartingYear + " " + calendarStartingMonth + " 01")
        let endDate = formatter.date(from: "2050 12 31")

        let parameters = ConfigurationParameters(startDate: startDate!, endDate: endDate!, firstDayOfWeek: DaysOfWeek.monday)
        
        return parameters
    }`

Thanks!

**Comment by rvirta** [comment]
```
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale

        calendarStartingMonth = Date().getPreviousMonth().appMonth
        calendarStartingYear = Date().getPreviousMonth().appYear
        
        let startDate = formatter.date(from: calendarStartingYear + " " + calendarStartingMonth + " 01")
        let endDate = formatter.date(from: "2050 12 31")

        let parameters = ConfigurationParameters(startDate: startDate!, endDate: endDate!, firstDayOfWeek: DaysOfWeek.monday)
        
        return parameters
    }
```

Thanks!

**Comment by patchthecode** [comment]
ok. it seems i misunderstood your question.
You have to change this your self.

Did you create your headers using a stack view? If yes, then simply check the users settings. And swap the header in your stack view.

**Comment by patchthecode** [comment]
Assuming issue resolved. Let me know if any further questions.
