### ISSUE TITLE
how to set the first row of the calendar to match the starting date 

### ISSUE THREAD

**Issue by tareq594** [patchthecode/JTAppleCalendar#716]
Hello , 
first of all thanks for this amazing library . 

I am trying to design a calendar that starts from " the current day" and hide the previous days . 
however when I hide the the days before the current day , I could not find a way to set the current day to the first raw . this is problematic specially when the starting day is at the end of the month so it will shift down in the bottom  .

Regards 
Tariq

**Comment by patchthecode** [comment]
can you show me a screenshot of what you want the calendar to look like?

**Comment by tareq594** [comment]
![screen shot 2018-02-11 at 9 00 34 pm](https://user-images.githubusercontent.com/20362860/36077111-27a26b12-0f6f-11e8-8b22-0e4b59c60781.png)
I want the startdate to be in the first raw of the calendar without the first two empty raws . 
What I did here , I hided the cells with date prior to my intended the startdate . however that will result in empty raws before it . 
I hope it's clear now

**Comment by ogezue** [comment]
looks similar to the requirement in this https://github.com/patchthecode/JTAppleCalendar/issues/712
(please scroll down)

**Comment by patchthecode** [comment]
This is currently not possible.
The calendar starts at the first of the month, and ends at the end of the month.
This was an update from the begining i should have done, but never got the time to do.

**Comment by loydbrahn** [comment]
+1 for this enhancement

**Comment by ChengRuipeng** [comment]
+1 for this enhancement

**Comment by EleshKliesen** [comment]
+1 for this enhancement (Is this issue being worked on actively or scheduled for later?)

**Comment by mayqiyue** [comment]
+1 for this enhancement (Is this issue being worked on actively or scheduled for later?)

**Comment by patchthecode** [comment]
scheduled for later, unless someone does that upgrade for me

**Comment by patchthecode** [comment]
I am now beginning to think about this.
There is one thing I am not clear on

![screen shot 2018-02-11 at 9 00 34 pm](https://user-images.githubusercontent.com/20362860/36077111-27a26b12-0f6f-11e8-8b22-0e4b59c60781.png)

If you want the calendar to start off with the start date, then for a:

1. **Horizontal Calendar** - according to this image, the frame of this calendar will only have 4 rows. Can you describe what will happen If I then scroll to the right to see the next month which has a full 6 rows?

2. **Vertical Calendar** - I havent thought of any issues here yet. Focusing on the horizontal firt

**Comment by ogezue** [comment]
What about my suggestion? https://github.com/patchthecode/JTAppleCalendar/issues/712#issuecomment-364864742

**Comment by patchthecode** [comment]
@ogezue ok i just re-read yours.

I think i answered since last year march 2018 :)
The library is no longer restricted to rows 1, 2, 3, 6
it can now do 4 & 5.

I am not sure if it fits your needs now though. Let me know.
