### ISSUE TITLE
Use of undeclared type 'JTAppleCell'

### ISSUE THREAD

**Issue by burzua** [patchthecode/JTAppleCalendar#717]
Hello, I newbie in swift.
I'm install library step by step by instruction with cocoapods
when i try repeat lesson nr1 in tutorials "calendar from scratch"
i have Use of undeclared type 'JTAppleCell' error after creating CustomCell class (in video 1m:25s)
import JTAppleCalendar not work too
 can you help me?

**Comment by patchthecode** [comment]
issue solved.
User builded the project.
closing now.

**Comment by kym3ni** [comment]
same problem, how do we fix this?

**Comment by patchthecode** [comment]
just build the project
CMD + B
Does it build?

**Comment by burzua** [comment]
rebuild project

**Comment by hack765** [comment]
Also try capitalizing the 't' in JTAppleCell. This was the fix for me...
