### ISSUE TITLE
Assertion failure of UICollectionView when using two instances of JTAppleCalendarView

### ISSUE THREAD

**Issue by Dean151** [patchthecode/JTAppleCalendar#72]
Hi !

I currently use JTAppleCalendar 4.1.2 in my project and it's awesome.
Unfortunately, I encounter an issue I don't really understand.

I have two instances of JTAppleCalendarView : the first is a small one, scrollable, and when I tap it, it open modally a view with a big calendar (yes, sounds like weird but there's many more than just a calendar in my view for this iPad app, so I need this modal behavior)

The problem is that as soon as the second big calendar loaded, the first one can't scroll any more without throwing an assertion error without any more information, even if I closed the modal view.

```*** Assertion failure in -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.29.5/UICollectionView.m:3627```

A breakpoint on exceptions show me that the error is triggered by the `collectionView.dequeueReusableSupplementaryViewOfKind` function (line 161) of the file `JTAppleCalendarDelegates`.

Do you have any idea of what can provoque this issue ? Should the correction be in the way I create the two instances of calendarView or is it something provoked by the implementation of the library ?

For more details, my calendars use nibs to load cells and header, witch mean I have 4 nibs for the calendars, 2 for the mini-version and 2 for the big versions. But cells share the class "CalendarCell", and so does the Header to avoir duplication of code.

It will be hard for me to give you my app code since my company policies forbid me to do so, but if it can be of any help, I would gladly take of my time to create a sample code from scratch that reproduce the issue.

**Comment by Dean151** [comment]
It seems like the small calendar tries to load the big header instead of the normal header : 

```NSInternalInconsistencyException, could not dequeue a view of kind:
UICollectionElementKindSectionHeader with identifier CalendarBigHeader - must
register a nib or a class for the identifier or connect a prototype cell in a
storyboard```

Of course I didn't register bigheader to my small calendar, but I can't come to understand how it can be called in the first place. Is there conflicting data between differences instances of calendar views ?

**Comment by patchthecode** [comment]
ok, i'll try putting two calendars on my view and have a look

**Comment by patchthecode** [comment]
If you look at my library code, its all pretty neat...
..all except that one time I was lazy and made a global var outside of the class :<

I know I had to change this, but didn't immediately realize that by putting the variable outside of the class, things will get conflicted if you have multiple calendars on screen.

Fixing this now. For now let's just pretend you never saw this 😁 ...

**Comment by Dean151** [comment]
Nice ! Thanks ! 😄 
I never saw this bug, in fact, what bug are you talking about 😆

**Comment by patchthecode** [comment]
Hey i just pushed a fixed to master branch. Can you test it?

to use it, replace your JTAppleCalendar in your pod file to the following:
`pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'`

**Comment by Dean151** [comment]
I use Carthage, so it will be `github "patchthecode/JTAppleCalendar" "master"`
I test it in the next hour

**Comment by Dean151** [comment]
Works fine with the fix ! Many thanks ! :smile

**Comment by patchthecode** [comment]
Sure. np. I'll leave this issue open till i release new version
