### ISSUE TITLE
Change calendar view background colour.

### ISSUE THREAD

**Issue by amank97** [patchthecode/JTAppleCalendar#721]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hi there, I am using the latest version of the library.

I am unable to make the background colour a gradient or transparent. Is there a easy of changing the background color of the calendar view.

Thanks

**Comment by patchthecode** [comment]
This calendar is a regular UICollectionView.
You change the background color in the exact same way.
What issues are you facing?

**Comment by amank97** [comment]
Oh I didn't know it was that simple, thanks again for the great library.

**Comment by patchthecode** [comment]
awesome cool. closing.
