### ISSUE TITLE
Choosing next date

### ISSUE THREAD

**Issue by jayjohnchiong** [patchthecode/JTAppleCalendar#722]
Using the Latest Version.

Hi. I'm new to swift and decided to use your library but I have a hard time looking for a way to do a "go to next date". Can you help me?

**Comment by patchthecode** [comment]
does this help ?

```swift
        calendarView.scrollToSegment(.next)
        calendarView.scrollToSegment(.previous)
        calendarView.scrollToSegment(.start)
        calendarView.scrollToSegment(.end)
```

**Comment by jayjohnchiong** [comment]
Well, that code is from this month to another month. What I want is like this "Feb 23, 2018" -> "Feb 24, 2018" -> "Feb 25, 2018" and so on if I press a button.

**Comment by patchthecode** [comment]
ok. then just use the 
`calendarView.selectDate` function

Using that function you can select any date.

**Comment by jayjohnchiong** [comment]
Ok. Thanks
