### ISSUE TITLE
Wrong dates getting selected

### ISSUE THREAD

**Issue by wawilliams003** [patchthecode/JTAppleCalendar#723]
Using latest version.

Thanks for creating this awesome library, it really helps. I got an issue when I am loading entry dates from coreData, The entry dates are showing when I set the text color for these dates. But when I try to show a view to highlight these same dates, the view is only highlighting one day. 

This how I am trying to show these dates on the calendar.

```seift
// Show dates with entry
  for entryDates in datesFromCoreData {
            formatter.dateFormat = "yyyy MM dd"
            let  dateToString = formatter.string(from: entryDates)
            if dateToString == formatter.string(from: cellState.date) {
                cell.dateLabel.textColor = UIColor(red: 0/255, green: 128/255, blue: 255/255, alpha: 1)
                cell.entryView.isHidden = false
            print("Entry Dates", dateToString)
           } else {
                cell.entryView.isHidden = true
       }  
```
  
*This is the result *
<img width="282" alt="screen shot 2018-02-23 at 11 49 04 am" src="https://user-images.githubusercontent.com/18673260/36605792-c7cd5506-188f-11e8-9776-28b0346bfff4.png">

As you can see that only the "5th" day is highlighted while all the others are in blue. 

I would like for all the entry dates to be highlighted, thank you!

**Comment by patchthecode** [comment]
where do you have this code located?

**Comment by wawilliams003** [comment]
Thanks for your reply, it's in the cellForItemAt

**Comment by patchthecode** [comment]
ok. Thte cellForItemAt is exactly the same as for a UICollectionView or a UITableView.
It is called for every visible cell on the screen.
Therefore if you should code it using the dataSource/Delegate pattern as for a TableView.

If you put a loop in there that loop will be called for ever cell on the screen.
So lets say your loop has 10 dates, thats 10 loops per 42 cells = 420 loops.

**Comment by wawilliams003** [comment]
I am new to swift so I might be missing the point. All the other dates work correctly, you're saying that I shouldn't run the loop in cellForIndex?

**Comment by patchthecode** [comment]
yes, do not have a loop in there.

```swift
// Show dates with entry
            formatter.dateFormat = "yyyy MM dd"
            let  dateToString = formatter.string(from: datesFromCoreData[indexPath.item])
            if dateToString == formatter.string(from: cellState.date) {
                cell.dateLabel.textColor = UIColor(red: 0/255, green: 128/255, blue: 255/255, alpha: 1)
                cell.entryView.isHidden = false
            print("Entry Dates", dateToString)
           } else {
                cell.entryView.isHidden = true
           }
```

have something like this in there instead

**Comment by wawilliams003** [comment]
Whenever I tried your code above I am getting error **Cannot convert value of type 'Bool' to expected argument type 'Date'**

 formatter.dateFormat = "yyyy MM dd"
     let  containsDate = formatter.string(from: datesFromCoreData.contains(cellState.date))  ** Error on this line**

        if containsDate {
            cell.dateLabel.textColor = UIColor(red: 0/255, green: 128/255, blue: 255/255, alpha: 1)
            cell.entryView.isHidden = false
        } else {
            cell.entryView.isHidden = true
        }

The issue is that, the entryView which I am trying to show for entry dates is only appearing at the first index in the datesFromCoreData array. And that is strange because the dateLabel.text is working fine.

**Comment by patchthecode** [comment]
yea im just typing this from my head, just correct the logical error

```
let  date = datesFromCoreData[cellState.date]
if date != nil { 
        cell.dateLabel.textColor = UIColor(red: 0/255, green: 128/255, blue: 255/255, alpha: 1)
        cell.entryView.isHidden = false
.....
```

**Comment by wawilliams003** [comment]
Thanks for your help, but everything I tried so far isn't working.

**Comment by patchthecode** [comment]
do you have a sample app on github i can take a look at?

**Comment by patchthecode** [comment]
closing until user responds.
Added awaint input flag
