### ISSUE TITLE
Selected cell stays selected for a single selection mode

### ISSUE THREAD

**Issue by alexyak** [patchthecode/JTAppleCalendar#724]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. 7.1.5

I have created a horizontal single line scrolling calendar with a custom selection. When a selection is made on the cell on the next page, the previous one still stays selected because didDeselectDate method is not being called. Any way to make it to be called?

**Comment by patchthecode** [comment]
1. got singleSelect or multi select enabled?
2. have you implemented a didDeselect function?

**Comment by alexyak** [comment]
Yes, for both. Will take a look at the sample.

**Comment by alexyak** [comment]
Ok, I was able to fix the issue by overriding isSelected on the cell and hiding selectedView there.

**Comment by patchthecode** [comment]
awesome :)
