### ISSUE TITLE
Remove the grayed color dates

### ISSUE THREAD

**Issue by jayjohnchiong** [patchthecode/JTAppleCalendar#725]
I have check this question https://github.com/patchthecode/JTAppleCalendar/issues/56 and I saw this https://patchthecode.github.io/CommonQuestions/#1 but the method itemSize cannot be found anymore.

**Comment by patchthecode** [comment]
renamed to `cellSize`.

**Comment by jayjohnchiong** [comment]
I tried this https://patchthecode.github.io/CommonQuestions/#1 and change itemSize to cellSize

and this is cellSize = 20
![screen shot 2018-02-26 at 10 10 58 am](https://user-images.githubusercontent.com/36146249/36650284-8fafd2ca-1add-11e8-8968-952e69dc0f0d.png)

this is cellSize = 40
![screen shot 2018-02-26 at 10 11 19 am](https://user-images.githubusercontent.com/36146249/36650314-b22905ec-1add-11e8-8c73-62eedc90cc34.png)

this is cellSize = 50
![screen shot 2018-02-26 at 10 11 43 am](https://user-images.githubusercontent.com/36146249/36650321-bbd7d168-1add-11e8-9ed8-f388c804b53b.png)

the grayed dates (which is red now since I changed the color) is still there

**Comment by patchthecode** [comment]
Im not sure what you want to do.
CellSize changes the cell size.
But if you want to "remove" the gray colored dates, then simply set their visibility to hidden.

```swift
if cellState.dateBelongsTo == .thisMonth {
   myCell.isHidden = false
} else {
   myCell.isHidden = true
}
```

thats it

**Comment by jayjohnchiong** [comment]
ow thanks. cheers
