### ISSUE TITLE
Google Calendar and Varriables

### ISSUE THREAD

**Issue by NigelWD** [patchthecode/JTAppleCalendar#726]
https://stackoverflow.com/questions/48978897/google-calendar-api-and-var

Could you take a look at this?

**Comment by patchthecode** [comment]
ok. What format are you trying to convert it into fro the calendar?

**Comment by NigelWD** [comment]
I’m trying to convert it into a String

**Comment by patchthecode** [comment]
Does the example on this video help you?
[link](https://www.youtube.com/watch?v=CQNotydm58s&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q&index=6)

It gives you an example of converting dates from a "fake" server and adding it to the calendar.
I did not convert it into a string in that instance, i converted it into a dictionary. I think this should help you.

**Comment by NigelWD** [comment]
It helps a bit, I'm trying to figure out now where in Google's API it allows for me to start converting the data it pulls from the server

**Comment by patchthecode** [comment]
awsome man.
Well i'll close this issue, but let me know if youre still stuck.
cool.

**Comment by NigelWD** [comment]
Could you take a look at this demo project? I'm getting errors all over the place and I can't find my way out of this hole. https://drive.google.com/open?id=1h03tRDWpGcRzPiSzvEG7_A1PcF5kc2Zq

**Comment by NigelWD** [comment]
https://github.com/willard1218/WLAppleCalendar/issues/1 I asked the creator of this calendar (who used your plugin) for some more information on how his calendar works, not sure if you can help me with this but I'm not entirely sure of what to do after his explanations

**Comment by patchthecode** [comment]
I downloaded your code, but it was not even building.
Just wondering, are you new to swift developement? usually i have the time to help, but im caught between multiple projects at the moment.

**Comment by NigelWD** [comment]
Yes I am new to swift development and this is my first major project, sorry for the trouble I understand if you’re busy
