### ISSUE TITLE
Type 'ViewController' does not conform to protocol 

### ISSUE THREAD

**Issue by dannygosain1** [patchthecode/JTAppleCalendar#727]
JTAppleCalendar Version: 7.1.5
Deployment Target: iOS 11.2

Error Message:
Type 'ViewController' does not conform to protocol. Do you want to add protocol stubs

Code:

<img width="880" alt="screen shot 2018-02-26 at 2 27 36 am" src="https://user-images.githubusercontent.com/20171882/36657974-a7b966e2-1a9c-11e8-8153-56910089745a.png">

**Comment by patchthecode** [comment]
remember, dont just take a look at the videos, they may be out of date.
On the main page there is an update. A new function called `willDisplayCell` is added.
You have to correctly implemented.

An explanation of why it was added and how to implement it is located here -> #553

**Comment by patchthecode** [comment]
closing issue.
But let me know if you youre still having trouble.
