### ISSUE TITLE
Stack view is not visible in cell

### ISSUE THREAD

**Issue by heli154** [patchthecode/JTAppleCalendar#729]
Hi. I got a problem that when I add a stack view into cell of calendar view, it does not appear. Could you tell me how to fix. Thank you

**Comment by patchthecode** [comment]
do you have a sample app i can take a look at?
Also, are you sure you have your constraints set correctly?

**Comment by heli154** [comment]
<img width="1073" alt="screen shot 2018-02-28 at 3 49 53 pm" src="https://user-images.githubusercontent.com/25103604/36778402-30cca152-1c9f-11e8-8f91-51ca47dac6a1.png">
<img width="987" alt="screen shot 2018-02-28 at 3 50 24 pm" src="https://user-images.githubusercontent.com/25103604/36778403-3106841c-1c9f-11e8-97ef-f380112bbe1d.png">

i want my stack view look like the first picture but it does not work. Then I try to set constraints like the second picture, it's still not working. I don't know why :(

**Comment by patchthecode** [comment]
i guess this is because you are new to constraints?
upload a sample app on github and i can fix.

**Comment by heli154** [comment]
https://github.com/heli154/ToDoList

I have uploaded my project on github. Could you help me, please. 
Thank you so much

**Comment by patchthecode** [comment]
hmm have you tried opening that project? nothing is buildable. :/
I'll check this again in the morning. Itas already 2am here.

**Comment by heli154** [comment]
I'm sorry. I have uploaded again.
Thank you for spending time to help me

**Comment by patchthecode** [comment]
set this to fill. You currently have it on center.

<img width="753" alt="screen shot 2018-02-28 at 8 35 15 am" src="https://user-images.githubusercontent.com/2439146/36799631-7885a9b8-1c62-11e8-92f8-70fdd326cfda.png">

Closing this issue now. Let me know the results.

**Comment by heli154** [comment]
thank you so much
