### ISSUE TITLE
How to put custom dates on my calendar. I can't figure it out!

### ISSUE THREAD

**Issue by Reecelandry** [patchthecode/JTAppleCalendar#730]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
Have you looked at any of the videos?

**Comment by Reecelandry** [comment]
yes. all

**Comment by patchthecode** [comment]
So which part are you stuck on?
got a sample app on github i can take a look at?

**Comment by patchthecode** [comment]
closing issue until user responds.
