### ISSUE TITLE
Open the calendar to the current month

### ISSUE THREAD

**Issue by ilbordi** [patchthecode/JTAppleCalendar#731]
Hi, is it possible to start the calendar from the current month?
I mean, I have created a start date 
`let startDate = formatter.date(from: "01/01/2018")!`
but I want that the calendar automatically scroll down to the current month (for example now we're in March so I'd like that the the calendar automatically goes to march).
Thanks!

**Comment by patchthecode** [comment]
in viewDiDLoad()

```swift
calendarView.scrollToDate( theDate )
calendarView.scrollToDate( theDate, animateScroll: false )
```

**Comment by ilbordi** [comment]
Thanks, I did not expected it  to be so easy!

**Comment by patchthecode** [comment]
cool.
