### ISSUE TITLE
ConfigurationParameters: A user should be able to set the current date that should be displayed

### ISSUE THREAD

**Issue by DwayneCoussement** [patchthecode/JTAppleCalendar#732]
Version 7.1.5;
put calendar in horizontal mode
- have a range of dates (eg february 2017 until march 2019)
- in a typical scenario you would want to show the current date of today
note that: `calendarView.scrollToDate(Date())` doesn't work; but that it's also not what a user would want
- the datasource should be provided with the current month (which should be provided with ConfigurationParameters) and show it as a first thing.

**Comment by patchthecode** [comment]
Hi, can you let me know what happens when you do 
```swift
calendarView.scrollToDate(theDate)  //or 
calendarView.scrollToDate( theDate, animateScroll: false )
```

This should work correctly.

Just put it in your `viewDidLoad()` function

**Comment by DwayneCoussement** [comment]
Hey, delegation is called correctly, so I can show like a header saying the current month. But the collectionview has like some strange animation (like it does the scroll, but shows like the startDate month). It's the paged horizontal calendar. Due to the limitation I decided not to use the library in the end though.

My calendar was configured like this:

`private let calendarView: JTAppleCalendarView = {
        let calendar = JTAppleCalendarView()
        calendar.register(CalendarCell.self, forCellWithReuseIdentifier: "calendarCell")
        calendar.scrollDirection = .horizontal
        calendar.isPagingEnabled = true
        calendar.showsHorizontalScrollIndicator = false
        return calendar
    }()`

**Comment by patchthecode** [comment]
Its ok. Sorry to see you go.

I think your problem was just one small thing though.
Since you did your calendar manually, I think you had to se the scrolling mode.
```swift
calendarView.scrollingMode = .stopAtEachCalendarFrame
```
All information on the kinds of supported scrolling modes are in the documentation -> 
https://patchthecode.github.io/CalendarScrolling/

All the best. Closing this issue.

**Comment by DwayneCoussement** [comment]
I did try with that scrollingMode, but it just didn't work :-/ I think this might have been a minor bug with that specific configuration.

**Comment by patchthecode** [comment]
We have tested all configurations, and there si no scrolling issue that we know of in configuration.
But maybe we might have missed something.
I know you've already moved on, but if its possible. Send a zip file of the sample-application to patchthecode@gmail.com
If its not possible then its cool.
But im interested to see what went wrong.

**Comment by jdanthinne** [comment]
Hi,
I'm using the `calendarView.scrollToDate( aRange.startDate, animateScroll: false )` to try to display correctly a previously selectedRange in the viewDidLoad.
Unfortunately, I'm using a modal UIViewController appearing from the bottom of the screen, and when the controller is showing, I can see that the scroll is not done yet, then when the UIView is in place at the top of the screen, then the `scrollToDate` is executed. Is there a way to scroll off-screen, before it appears on the screen?

**Comment by patchthecode** [comment]
in what function do you have the scrollToDate ?

**Comment by jdanthinne** [comment]
The famous` viewDidLoad`.
