### ISSUE TITLE
How to set in-date the same as out-date and indicate this.

### ISSUE THREAD

**Issue by Kaisp** [patchthecode/JTAppleCalendar#733]
Hello!

Version: 7.1.5(latest)

I am trying to add the functionality of being able to select same in-date as out-date and to indicate this on the cells. How ever I am not currently able to obtain the feature. Do you have any suggestions as to how to implement this?(I am building a calendar in an airline context so I need to be able to select same outbound date as inbound date.)

Regards,

Kasper Josefsen.

**Comment by patchthecode** [comment]
Hi, i am unclear of what you are asking. Maybe a screenshot of what you are trying to accomplish will help?

**Comment by Kaisp** [comment]
Hi, I figured it out. Thanks anyway.

Regards,
Kasper

On 5 Mar 2018, at 01.25, JTAppleCalendar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, i am unclear of what you are asking. Maybe a screenshot of what you are trying to accomplish will help?

**Comment by patchthecode** [comment]
Have a good one. 🍻
