### ISSUE TITLE
How to display current week for the current day?

### ISSUE THREAD

**Issue by victorchu8** [patchthecode/JTAppleCalendar#735]
Currently using version 7.1.5.
My problem that is never shows the current week but the previous week.
My calendar currently loads like this:
![screen shot 2018-03-07 at 5 57 43 pm](https://user-images.githubusercontent.com/29528613/37127055-32b9da38-2231-11e8-8fb8-e4eb7bb85b8c.png)

Today's date is March 7 so I would like it to show the week like this:
[ 4 5 6 7 8 9 10]

Here is what my code looks like:
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        var dateComponent = DateComponents()
        dateComponent.year = 1
        let startDate = Date()
        let endDate = Calendar.current.date(byAdding: dateComponent, to: startDate)
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate!, numberOfRows: 1, calendar: Calendar.current, generateInDates: .forFirstMonthOnly, generateOutDates: .off, firstDayOfWeek: .sunday, hasStrictBoundaries: false)
        
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        cell.dateLabel.text = cellState.text
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
    }

Thanks!

**Comment by patchthecode** [comment]
did you do this in your `viewDidLoad` ?
```swift
calendarView.scrollToDate( Date() )
```

Also please implement the `willDisplayCell` function as shown here -> #553

**Comment by victorchu8** [comment]
Ok I just implemented both parts you just said and it now looks like this:
![screen shot 2018-03-08 at 10 48 33 am](https://user-images.githubusercontent.com/29528613/37167150-4f3834ba-22be-11e8-800d-dbda21042667.png)

Also here's my code for the extension:

    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        var dateComponent = DateComponents()
        dateComponent.year = 1
        let startDate = Date()
        let endDate = Calendar.current.date(byAdding: dateComponent, to: startDate)
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate!, numberOfRows: 1, calendar: Calendar.current, generateInDates: .forFirstMonthOnly, generateOutDates: .off, firstDayOfWeek: .sunday, hasStrictBoundaries: false)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let calendarCell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarCell", for: indexPath) as! CalendarCell
        sharedFunctionToConfigureCell(calendarCell: calendarCell, cellState: cellState, date: date)
        return calendarCell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let calendarCell = cell as! CalendarCell
        sharedFunctionToConfigureCell(calendarCell: calendarCell, cellState: cellState, date: date)
        
    }
    
    func sharedFunctionToConfigureCell(calendarCell: CalendarCell, cellState: CellState, date: Date) {
        calendarCell.dateLabel.text = cellState.text
    }

Any idea how I would show the week of the date instead of it showing the current date starting from sunday?

So the calendar would be: 
 SUN MON TUE WED THU FRI SAT
[  4       5       6        7      8    9    10  ]

and then it would reset next week so: 

 SUN MON TUE WED THU FRI SAT
[  11     12      13    14     15    16   17  ]

Thanks so much!

**Comment by patchthecode** [comment]
this slipped my mind man. Did you solve it already?

if not, just to clarify, you want to find a way to make your calendar scroll to the next month with a button? I did not understand this last part.

```
So the calendar would be:
SUN MON TUE WED THU FRI SAT
[ 4 5 6 7 8 9 10 ]

and then it would reset next week so:

SUN MON TUE WED THU FRI SAT
[ 11 12 13 14 15 16 17 ]
```

**Comment by patchthecode** [comment]
Assuming this was resolved.
Closing issue.
If not resolved, then reply and I will re-open.

**Comment by kailezhao** [comment]
Thanks!!!
