### ISSUE TITLE
Load events from core data and display in tableview

### ISSUE THREAD

**Issue by amank97** [patchthecode/JTAppleCalendar#737]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.

Hello, I am using the latest version of the JTAppleCalendar. 

I am having a few issues when it comes to comparing the date that is selected with dates from my core data event. Currently, my application is able to display all the events in a table view underneath the calendar but I want it to only show events for the date selected. But I am unsure as to how I should compare the dates. I have seen examples of where people compare the date selected but they don't really make sense or apply to my problem. I tried comparing the date selected and the date value from core data and used NSPredicate to filter but that didn't work. So I would be grateful if you could provide an example of how to load events from core data and filter them based on date selected.

**Comment by patchthecode** [comment]
why dont you convert the date from Coredata into a string, and convert the date that you want to compare against into as string, and then just compare the 2 strings?

You can make sure both strings are of the same format using a `DateFormatter`.
```swift
let formatter = DateFormatter()
formatter.dateFormat = "yyyy MM dd"  // formatter will make all dates look like this
let dateString1 = formatter.string(from: myCoreDataDate)
let dateString2 = formatter.string(from: myOtherDate)

if dateString1 == dateString2 {
   // do this
} else {
  // do that
}
```
