### ISSUE TITLE
reloadData animation paramter

### ISSUE THREAD

**Issue by soorinpark** [patchthecode/JTAppleCalendar#740]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. v7.1.5
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5 yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hi, 

In the UserInteractionFunctions, there is:
```swift
/// Reloads the data on the calendar view. Scroll delegates are not
//  triggered with this function.
/// - Parameter date: An anchordate that the calendar will
///                   scroll to after reload completes
/// - Parameter animation: Scroll is animated if this is set to true
/// - Parameter completionHandler: This closure will run after
///                                the reload is complete
public func reloadData(withanchor date: Date? = nil, completionHandler: (() -> Void)? = nil) {
```

but it doesn't seem like `animation` is a valid parameter for `reloadData` anymore.

Thanks for your awesome work btw!

**Comment by loydbrahn** [comment]
Related to this... Providing an anchordate doesn't cause the calendar to scroll to that date (animated or not). 

So this does not work as it should, according to the docs: 

`calendarView.reloadData(withanchor: anchorDate, completionHandler: nil)`

A temporary workaround I'm using is to scroll to the anchordate in the completion handler (which will do an animated scroll): 

`calendarView.reloadData(withanchor: nil) {
      self.calendarView.scrollToDate(anchorDate)
  }`

**Comment by patchthecode** [comment]
hmm. maybe I broke something. Will check this out soon.

**Comment by patchthecode** [comment]
I made an update on master branch. See this issue for instruction on testing with master branch code to see if your issue is resolved -> https://github.com/patchthecode/JTAppleCalendar/issues/746

**Comment by soorinpark** [comment]
@patchthecode Ok that's what I figured! Can I suggest you remove it from the comments for accuracy? Thanks :)

**Comment by patchthecode** [comment]
@soorinpark cool.
closing this issue now.
I if you got any more questions, just let me know.
We leave comments here on github so leave a record to help other people. More comments = more help.

cheers 🍻

**Comment by MyGuySi** [comment]
@patchthecode Is this available in the latest version on Cocoapods?

I'm using the following but still seeing an animation with the dates sliding in from the side...

```swift
calendarView.reloadData(withanchor: selectedDate)
```

![jun-08-2018 12-10-50](https://user-images.githubusercontent.com/12952977/41155297-48a653da-6b15-11e8-8359-188e67048872.gif)

**Comment by patchthecode** [comment]
@MyGuySi are you using master branch code?

https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by patchthecode** [comment]
If yes, is it possible you can send me that purple sample app?
patchthecode@gmail.com

**Comment by MyGuySi** [comment]
Ah probably not, sorry I didn't see that. I'll update my Podfile and see if that fixes it 👍

**Comment by MyGuySi** [comment]
@patchthecode Yep that's fixed it, guess that fix isn't on Cocoapods yet then. Thanks for the quick response!

**Comment by patchthecode** [comment]
@MyGuySi Youre right.

its not released yet. I will soon though, once i get the some free time.
