### ISSUE TITLE
Can not import JTAppleCalendar in the file

### ISSUE THREAD

**Issue by D2Jgs** [patchthecode/JTAppleCalendar#741]
Followed your video and installed it with coca pods but still cannot import the JTAppleCalendar class to the file

**Comment by patchthecode** [comment]
same project link on github?

**Comment by D2Jgs** [comment]
got it Thanks

**Comment by D2Jgs** [comment]
Could you help me out. I can't get the calendar to display.
I have mailed you a project file.
Thanks.

**Comment by patchthecode** [comment]
fixed.

**Comment by D2Jgs** [comment]
Thank.
Sorry for bothering you.
