### ISSUE TITLE
macOS Version in sight?

### ISSUE THREAD

**Issue by strike65** [patchthecode/JTAppleCalendar#743]
Hi!

Do you plan to port your excellent work for macOS?

Best regards!

**Comment by patchthecode** [comment]
I do.
but the issue is time.
Right now i have one final project to complete before i get back to this lib.

**Comment by strike65** [comment]
Would be great!

Thanks!

**Comment by LOG-TAG** [comment]
please reopen this and tag it as enhancement

**Comment by patchthecode** [comment]
I guess i have been lazy with this because of the news:

https://www.zdnet.com/article/iphone-ipad-mac-apps-merging-apple-sdk-will-create-ios-apps-that-work-on-mac/
