### ISSUE TITLE
How to select date's in range? 

### ISSUE THREAD

**Issue by forafontov98** [patchthecode/JTAppleCalendar#745]
Hi! I use the last version of JTAppleCalendar, but I can't find how I can realize selecting a few dates. Maybe are there some reade project's? Thanks!

**Comment by pavelsmelovsky** [comment]
Hi!

JTAppleCalendarView includes several methods to selecting few dates, or range of dates.

```
public func selectDates(_ dates: [Date], triggerSelectionDelegate: Bool = true, keepSelectionIfMultiSelectionAllowed: Bool = false)

public func selectDates(from startDate: Date, to endDate: Date, triggerSelectionDelegate: Bool = true, keepSelectionIfMultiSelectionAllowed: Bool = false)
```

**Comment by patchthecode** [comment]
the documentation is for old version 6.
But can you figure it out from this? -> https://patchthecode.github.io/RangeSelection/

**Comment by patchthecode** [comment]
Assuming resolved. closing
