### ISSUE TITLE
Content offset reset on bounds changes

### ISSUE THREAD

**Issue by pavelsmelovsky** [patchthecode/JTAppleCalendar#746]
Hello!

### Version
We using actual version of JTAppleCalendar – 7.1.5

### Description
Calendar layout: Vertical

When user select any date in next month then app shows bottom toolbar of navigation controller. As a result, bounds of 'view' (and bounds of calendarView) changes, and layout of calendarView become invalidated. And UICollectionView offset is reset to current month.

I found similar issue (https://github.com/patchthecode/JTAppleCalendar/issues/470). But i don't see any suggestions how to solve my problem.

**Comment by patchthecode** [comment]
will check this out over the weekend.

**Comment by patchthecode** [comment]
I have updated the code on master branch.

Here  is what should happen.
When you show the toolbar and the size of the bounds change. See example below
```swift
calendarView.frame = CGRect(
            x: calendarView.frame.origin.x,
            y: calendarView.frame.origin.y,
            width: calendarView.frame.width,
            height: calendarView.frame.height - 50
        )
        
        let date = calendarView.visibleDates().monthDates.first!.date
        calendarView.reloadData(withanchor: date)
```

in example above, i have changed the frame of calendar. Therefore, you must reload the calendar view.
If you want the calendar to scroll back on reload, then please set an `anchorDate` that you want the calendar to scroll to on reload.

This code update is found on masterBranch (not yet released).
To try it out see here -> https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by pavelsmelovsky** [comment]
@patchthecode Hi!

I'm trying code from master branch.
But we don't use reloadData(withanchor:) method, and everything works as expected!

Thank you!

Will this changes goes to the next release?

**Comment by patchthecode** [comment]
>  But we don't use reloadData(withanchor:) method, and everything works as expected!

Do you mean that the navigation controller changes the height of the calendar and it is not reset?
If yes, then i will ask you this, is the calendar resized properly with the cells?

(and yes, if all master branch changes will be released in next version but only after all bugs are flushed out)

**Comment by pavelsmelovsky** [comment]
@patchthecode hi!

Yes, after calendarView bounds did change it is not reset. All works as expected (for our configuration). We use: vertical scroll, isPagingEnable = false and custom cell size (vertical height ==  55dp).
I can try another configuration. Tell me what configuration to try? 

Thanks.

**Comment by patchthecode** [comment]
If all works as expected, then cool.
consider this fixed.
I'll test the other configurations. 👍
