### ISSUE TITLE
Nil Optional Value of CalendarView

### ISSUE THREAD

**Issue by benjamin852** [patchthecode/JTAppleCalendar#749]
Hey everyone I had a basic version of the calendar working and now for some reason i keep getting an error with my outlet. 
Whenever I just try run the app, it compiles but then throws an error saying that the optional value of my outlet is nil.
Any ideas where im messing up?
<img width="1280" alt="screen shot 2018-03-30 at 4 26 02 pm" src="https://user-images.githubusercontent.com/13651771/38153703-02583ffc-343c-11e8-9747-1ffee9b6b9fb.png">

**Comment by patchthecode** [comment]
send me an email of your sample project.
patchthecode@gmail.com

**Comment by benjamin852** [comment]
Nvm I figured it out stupid mistake in my AppDelegate lol

**Comment by patchthecode** [comment]
awesome
