### ISSUE TITLE
Why i cant register header as class? only via xib(( from @Majid

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#75]
Why i cant register header as class? only via xib((

**Comment by patchthecode** [comment]
There are two functions that you can use. Choose anyone that you like.

1. `calendarView.registerCellViewClass(fileName: "myFileName")`
2. `calendarView.registerCellViewClass(cellClass: class.type)`

**Comment by mecid** [comment]
This is only for day cells? Or i can use it for Month Header too?

**Comment by patchthecode** [comment]
oooooh. O_o 
Damn..

**Comment by patchthecode** [comment]
I will have an update for you over the weekend.
Sounds good?

**Comment by patchthecode** [comment]
By the way, I mainly use xibs in my projects. I do not use classes, to the testing in that area is not as much as what i did for the xibs.  If you find anything wrong in that area, literally anything wrong (even the smallest thing), then let me know. This library should have no bugs.

**Comment by mecid** [comment]
I am using simple Month Header with single label and don't want to use xibs.
![simulator screen shot 15 2016 4 31 26](https://cloud.githubusercontent.com/assets/324372/16868495/fcbc3196-4a88-11e6-9593-e712f2aeb3fe.png)

**Comment by patchthecode** [comment]
Looks great. I can't wait to see it when it is finished.

By the way. Look at this:
<img width="298" alt="screen shot 2016-07-15 at 11 08 30 am" src="https://cloud.githubusercontent.com/assets/2439146/16884195/eb68cbd6-4a7c-11e6-9e97-8c07e0255932.png">

Is this a bug?

**Comment by patchthecode** [comment]
Hey, I have pushed your enhancement to the master repository. Can you test it?
I you are using CocoaPods, then follow the instructions on **question 6 ** here to test master branch -> https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by mecid** [comment]
@patchthecode I am using master branch and all working good! Thanks.

**Comment by patchthecode** [comment]
great. closing this.

**Comment by mecid** [comment]
Do you release it?

**Comment by patchthecode** [comment]
Not yet. 
I have to do some more rounds of testing. But I will release it over this weekend.
For now, you are the test subject :)

**Comment by mecid** [comment]
@patchthecode ok, no problem))
