### ISSUE TITLE
JTAppleCalendar 6.0 Two-Tap range selection 

### ISSUE THREAD

**Issue by sreekanthps** [patchthecode/JTAppleCalendar#751]
I am trying to build my iOS app calendar component with JTAppleCalendar and i have requirement for  two tap range selection, i have followed steps as per documentaiton. But i am not able to highlight the color between date range. Attaching code and screen shot of my requirement.

Your help is very much appreciated
<img width="373" alt="screen shot 2018-04-05 at 1 14 05 am" src="https://user-images.githubusercontent.com/6374791/38323160-0ad0719a-386f-11e8-98a5-7228bd5a5663.png">
[DBSCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/1876832/DBSCalendar.zip)

**Comment by patchthecode** [comment]
will take a look after work today

**Comment by patchthecode** [comment]
I just checked out your code.
You did not have this enabled ->

`calendarCollection.allowsMultipleSelection  = true`

That line was commented out.
Fix that and your range selection will work.

**Comment by sreekanthps** [comment]
Hi,

Sorry for delay in responding, that totally work. I have 2 issues now 
 1. cellInset is missing to avoid space between cells
 2. When i use calendarview. selectDates to highlight dates between, some dates are not being delegated 
(screen shot and code is attached)
[DBSCalendar 2.zip](https://github.com/patchthecode/JTAppleCalendar/files/1912926/DBSCalendar.2.zip)
<img width="411" alt="screen shot 2018-04-15 at 10 07 45 pm" src="https://user-images.githubusercontent.com/6374791/38779351-8a6ce344-40b6-11e8-95ab-876eb1453dfe.png">
<img width="411" alt="screen shot 2018-04-15 at 10 07 45 pm" src="https://user-images.githubusercontent.com/6374791/38779381-0a1cb812-40b7-11e8-91ac-b61b5ac36228.png">

**Comment by patchthecode** [comment]
Have you implemented the `willDisplayCell` function as shown in **bold** important text on the the main page? :) --> #553

**Comment by sreekanthps** [comment]
In the screen cap attached i am not getting the date 25th in willDisplayCell delegate, 
this is happening with calendarview. selectDates

**Comment by sreekanthps** [comment]
How about cellInset ? i i need to reduce the gap between cells (remove empty space)

**Comment by patchthecode** [comment]
```swift
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
```

**Comment by sreekanthps** [comment]
Hi,

My height issue got resolved, but assigning cellsize = view.frame/width/7 (since i display 7 rows)
But the second issue is not solved yet

When i select calendarCollection.allowsMultipleSelection = true and when i select two date ranges, the day before end date is not getting willDisplayCell delegate call

attaching screen cap and code for reference
[DBSCalendar 3.zip](https://github.com/patchthecode/JTAppleCalendar/files/1913927/DBSCalendar.3.zip)
<img width="410" alt="screen shot 2018-04-16 at 1 03 37 pm" src="https://user-images.githubusercontent.com/6374791/38790872-97c0531e-4133-11e8-831c-b21b2d8efb32.png">

**Comment by patchthecode** [comment]
i think you are making this way much harder than it needs to be man.
have you looked at the range selection tutorial? Its for version 6.0 but porting it over should be too hard.

here is your zipped file, i removed most of the un-needed code. it should take you to 90% of the way there  
[DBSCalendar 2.zip](https://github.com/patchthecode/JTAppleCalendar/files/1914157/DBSCalendar.2.zip)

**Comment by patchthecode** [comment]
you should be using version 7.1.5
Many bugs have been fixed in the prior versions.

**Comment by sreekanthps** [comment]
thank you very much, that helped a lot, we are trying to add the project as source code into our code, the reason being we are using some security libraries that don't allow dynamic frame works
If we have static library also works for ur. please help us with static library

**Comment by patchthecode** [comment]
@sreekanthps i do not know much about static libraries. Sorry about that. I know more about cocoapods.
