### ISSUE TITLE
 'ViewController' does not conform to protocol 'JTAppleCalendarViewDelegate'

### ISSUE THREAD

**Issue by ABGIII926** [patchthecode/JTAppleCalendar#752]
This seems to be a very common mistake.  Thank you for taking a look.
I get this error on the 'extension' line
I am using version 7.1.0

My code:

extension ViewController: JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource {
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2018 01 01")
        let endDate = formatter.date(from: "2018 12 31")
        
        
        let parameters = ConfigurationParameters (startDate: startDate!, endDate: endDate!)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        cell.dateLabel.text = cellState.text
        return cell

**Comment by aoot** [comment]
@ABGIII926 How did you resolve this issue? Xcode is telling me that my VC is not conforming to the protocol as well.

I've read through the protocol declaration, and it seems to me that my VC IS conformed to it.

**Comment by patchthecode** [comment]
click on the red error and let me know what XCode suggests as the fix?

**Comment by beajco** [comment]
here it is bro. I have the same prob right now

![screen shot 2018-12-06 at 11 49 50 am](https://user-images.githubusercontent.com/38550296/49560378-141c5800-f94d-11e8-8bc8-56f030c0ea57.png)

![screen shot 2018-12-06 at 11 50 01 am](https://user-images.githubusercontent.com/38550296/49560393-20081a00-f94d-11e8-980d-3d1e28f9a481.png)

**Comment by patchthecode** [comment]
is it resolved?
