### ISSUE TITLE
JTAppleCalender PreMonth selection issue [Version 6.0]

### ISSUE THREAD

**Issue by vnanaware** [patchthecode/JTAppleCalendar#756]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.  
Ans:       6.0

2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
Ans:   No, I updated latest but its gives many errors so are degrade to 6.0

I have implemented JTAppleCalender in my iOS project. for to select start date adnd end date.
Now the my problem is that When I open the calender popup from current month its not going to back month, ie. current month is April 2018 and I want to select the date 15 March 2017 its not possible right now.  Please help me.

**Comment by patchthecode** [comment]
Version 7 of this library has been out for some time now (over a year)
Going back to support version 6 would be too difficult for me.

I can help you port your 6.0 project to version 7.
Also version 7 has many videos which could help porting over from version 6 to 7.

**Comment by patchthecode** [comment]
closing issue.
Let me know when you need help porting to version 7
