### ISSUE TITLE
App not compiling for my friend after pull request

### ISSUE THREAD

**Issue by benjamin852** [patchthecode/JTAppleCalendar#758]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hey folks. My friend is trying to pull my project but he is having a bug with the calendar. The project compiles and works fine for me but here is a screenshot of the issue he is getting 
<img width="1142" alt="calendarbug" src="https://user-images.githubusercontent.com/13651771/38763705-54af72f0-3f6f-11e8-8ed0-abdb1f348d24.png">

For me  on my Xcode is doesn't show me that I'm missing any functions to conform to the protocol.

**Comment by patchthecode** [comment]
He needs to click on the red colored dot and XCode will tell him how to fix it.

I bet it will tell him that he needs to implement the `willDisplayCell` function as shown here -> #553

**Comment by benjamin852** [comment]
Ya i think thats what it tells him but its weird because I dont have that function in my code and it works fine for me

**Comment by patchthecode** [comment]
@benjamin852 do you have the exact same version 7.1.5?

Something must be wrong somewhere. Maybe try a `pod update` on console?
7.1.5 should force developers to implement that function.

**Comment by patchthecode** [comment]
closing until further input
