### ISSUE TITLE
Is it possible to display the calendar in "Outlook" style. From user @Karthik

### ISSUE THREAD

**Issue by patchthecode** [patchthecode/JTAppleCalendar#76]
** From user @Karthik ** i am only interested in showing 7 days. The header would be the day "Mon/Tue/..." while each row would be time of the day. I would like to color different segments of the day with different appointments. Is this possible within the framework you have provided?

**Comment by patchthecode** [comment]
It is possible to show 7 days on the calendar. 
All you have to do is set the number of rows per month to --> 1
That's it.

However, I am not sure if you will encounter this problem -> https://github.com/patchthecode/JTAppleCalendar/issues/37

**Comment by probugtivity** [comment]
Hi, thanks for starting the thread!... 

I am looking at showing a detail like the one shown in this screenshot. [From what i gathered in your comments/warning on github that this feature may not be available yet? - wanted to confirm :) ]

Thanks!, Karthik

![screen shot 2016-07-17 at 12 29 41 pm](https://cloud.githubusercontent.com/assets/20504700/16902377/32ff62ea-4c1a-11e6-8de8-e4ecd56bcf89.png)

**Comment by patchthecode** [comment]
Wow.. so this was what you meant when you said "outlook" style :/ 
Hmm.. In that case, it cant be done. 
That image is more of a schedule planner than a calendar. Because the blue boxes are of different sizes, I do not think this is possible with this project at this time.

**Comment by probugtivity** [comment]
My definition was a bit vague :)... sorry about that. 

Even if the blue boxes are fixed times across the week, i am guessing i wouldn't be able to use your project (currently). Right? I just need them to be displayed and the ability to change the colors.

Thanks,
Karthik

**Comment by patchthecode** [comment]
In order to use that style with JTAppleCalendar,

The sizes of the squares has to be the same size, and also, they have to be in a square grid layout.
The grird layout has to be 6 x 7. That's 42 separate equal size squares.

Your layout seems like a flow style layout. It cannot be configured like the image you just showed me.

I **might** be developing another control like the one you want in the the future. But for now, all I have is the calendar.

**Comment by patchthecode** [comment]
The one you want looks something like this -> https://github.com/jumartin/Calendar
I do not know if that one is a good scheduler however.

**Comment by patchthecode** [comment]
Yea.. unfortunately, it cannot be done.
I am currently creating a project like the one you want, but for now, it will not be able to work.

You might have to have a look at this project instead -> https://github.com/jumartin/Calendar
I am not sure how good it is though.
sorry man.

**Comment by probugtivity** [comment]
I look forward to your next project then!...

Thanks for the link. i will check it out.

**Comment by patchthecode** [comment]
cool 👍

**Comment by probugtivity** [comment]
Hi, Is the JTAppleCalendar swift3 compatible? I have been using CVCalendar
and it does not work with swift 3. From what i gathered there is no plan
for support till end of year (at least).

**Comment by patchthecode** [comment]
@probugtivity please follow the instructions here for swift 3. 

https://github.com/patchthecode/JTAppleCalendar/issues/138
