### ISSUE TITLE
get month before scrolling ends (willScrollToDateSegmentWith)

### ISSUE THREAD

**Issue by coc** [patchthecode/JTAppleCalendar#760]
Hi and thanks for this great calendar framework!

I´m using version 7.15 in a new app I'm developing.

**How can I get the month the user is scrolling to before scrolling is ready?**

I use the following settings:
```swift
calendarView.minimumLineSpacing = 0
calendarView.minimumInteritemSpacing = 0
calendarView.scrollingMode = .stopAtEachSection
calendarView.cellSize = calendarView.frame.size.width / 7 - 4.0 // make calendar height smaller
weekDaysView?.backgroundColor = .white
calendarViewHeightConstraint.constant = 6 * calendarView.cellSize
calendarView.scrollDirection = .vertical
```

One delegate that is called while user is scrolling is **didScrollToDateSegmentWith**. Can I get the month the user scrolls to or the scroll direction (up or down) inside this function?

**Comment by patchthecode** [comment]
It cant be done right now

```swift
func scrollDidEndDecelerating(for calendar: JTAppleCalendarView)
```

I meant to do this in this function. This function tells you when the calendar stops scrolling as soon as you lift your finger.
But it was **supposed** to be this

**Comment by patchthecode** [comment]
> One delegate that is called while user is scrolling is didScrollToDateSegmentWith. Can I get the month the user scrolls to or the scroll direction (up or down) inside this function?

Thinking on this. Will reply in some time

**Comment by coc** [comment]
Thanks, I meant **scrollDidEndDecelerating**, not **didScrollToDateSegmentWith**
** didScrollToDateSegmentWith** is too late, scrolling is done at this point. The reason why I wish this is of course I display the month and year in the UINavigationController´s **large title**

**Comment by patchthecode** [comment]
ok then. If it is `scrollDidEndDecelerating` then i have already marked this for an enhancement.
How soon do you need this? I am sorta swamped with projects right now.

**Comment by patchthecode** [comment]
alright. that _should_ be enough time.

**Comment by coc** [comment]
Thanks again!

**Comment by mock123** [comment]
I need this enhancement too!  Preferably before this month is out...

**Comment by coc** [comment]
Hi, I want ask again for this feature.

Thanks

**Comment by juliensagot** [comment]
Hi, any updates?
Could we expect that feature to be released _soon_?

**Comment by LeoGoemaere** [comment]
+1 I really need this please

**Comment by patchthecode** [comment]
i have added this as an update to master branch code -> 2c00513aab426f71787c443d017f2baf0ae5b3fc

**Comment by juliensagot** [comment]
It works like a charm!
Thank you so much, my calendar looks perfect now 👍.

![](https://i.imgur.com/cXo0l8p.gif)
