### ISSUE TITLE
Buggy or unexpected behavior for current day text color

### ISSUE THREAD

**Issue by mohghazi** [patchthecode/JTAppleCalendar#761]
Running latest version 7.1.5

Hi,

Im getting an unexpected behavior by selecting the cell of current day. CalendarView behaves normally for each selection and de-selection. Yet by selecting the current day, the view starts to behave in a strange way.

The text color should be set to red for current day. Yet other cells are getting red too! I set a breakpoint on the line where the color is set, and it is only executed when  day == today. So something intern in the library is mixing things up. As red text color is observed in other cells too! Please check code sample.

Similar behavior also observed if didSelectCell- Method is used to set the red text color.

Can u plz explain this behavior?

```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
    let calendarCell = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: CustomCalendarCell.reuseIdentifier, for: indexPath) as! CustomCalendarCell
        ...
        
        calendarCell.dateLabel.text = cellState.text
    
    if cell.dateLabel.textColor == .red {
        print("red: \(date.string!)")
    }
    return calendarCell
}


func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
    
    if Calendar.current.isDateInToday(date) {
        print(date.string!)
        let calendarCell = cell as! CustomCalendarCell
        calendarCell.dateLabel.textColor = .red
    }
}

**Comment by patchthecode** [comment]
This behavior is not strange.
JTAppleCalendar is a UICollectionView.
Cells are *reused*.

Therefore you have to reset the cell properly.

```swift
if Calendar.current.isDateInToday(date) {
    text = red
} else {
   text = black 
}
```

But all you are doing is setting to red. Therefore when cells are reused, all become red.

**Comment by patchthecode** [comment]
Also, your willDisplayFunction looks strange.

it should look more like this: (pasted from my example code)
```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! DateCelltemplate
        cell.dateLabel.text = cellState.text
        handleCellConfiguration(cell: cell, cellState: cellState)
    }

    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableCell(withReuseIdentifier: "DateCelltemplate", for: indexPath) as! DateCelltemplate
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return cell
    }
```

Your `cellForItem` function should call the `willDisplay` function. And all your configuration shoul dbe done in the will display function. This has been explain in #553

**Comment by patchthecode** [comment]
closing this issue. Let me know if youre still having a problem

**Comment by mohghazi** [comment]
ok. Im not using willDisplay-Method now. In cellForItem-Method I implemented this line of code to set the textColor:

```
cell.dateLabel.textColor = Calendar.current.isDateInToday(date) ? .red : cellTextColor
return cell
```

This is working fine, but not at first run i.e. when user open the calendar, even though the code is executed at first run (I set some break points and checked it). After user tap on any cell on calendar or scroll etc .. , it is set correctly.

I need to do it this way. As I have many CustomCells which are assigned accordingly to the calendar. Yet Today-Cell is an exception and need to be handled separately.

Many thanks in advance..

**Comment by patchthecode** [comment]
are you sure this is run correctly on first run?
convert this into an if statement
```swift
cell.dateLabel.textColor = Calendar.current.isDateInToday(date) ? .red : cellTextColor
// convert to this
if Calendar.current.isDateInToday(date) {
   cell.dateLabel.textColor = .red
} else {
   cell.dateLabel.textColor = cellTextColor
}
```
and let me know = `   cell.dateLabel.textColor = .red` i called correctly on first run

**Comment by mohghazi** [comment]
Just tried it. Its the same behavior. For todays-Date it is executing and textcolor ist set to red. Yet it is not set in the calendar.

**Comment by patchthecode** [comment]
do you have a sample project with just this problem alone in it that i can take a look at?. You can create a sample project demonstrating the error. and drag the zip file in this chat box.

**Comment by mohghazi** [comment]
I will try to provide sample code soon. Thanks for the support.

**Comment by patchthecode** [comment]
cool.

**Comment by mohghazi** [comment]
I made a sample code. Following similar structure as in my code. Yet in sample code, it is working at first run. And I cant find the difference in implementation! I'll check again..
```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell: CustomCalendarBaseCell

        if date < Date() {
            cell = calendar.dequeueReusableCell(withReuseIdentifier: "FirstCustomCalendarCell", for: indexPath) as! FirstCustomCalendarCell
        } else {
            cell = calendar.dequeueReusableCell(withReuseIdentifier: "SecondCustomCalendarCell", for: indexPath) as! SecondCustomCalendarCell
        }
        cell.dateLabel.text = cellState.text
        if Calendar.current.isDateInToday(date) {
            cell.dateLabel.textColor = .red
        } else {
            cell.dateLabel.textColor = .green
        }
        return cell
    }
```

**Comment by mohghazi** [comment]
worked now :)
I have some UIAppearance stuffs in my code which i didn't use in the sample code .. so I set the textcolor using its defined property in custom cell  i.e.

```
if Calendar.current.isDateInToday(date) {
            cell.textColor = .red
        } else {
            cell.textColor = .green
        }
```

Where textColor is defined in CustomCalendarBaseCell as dynamic var for dateLabel.textColor.

Many thanks, and

**Comment by patchthecode** [comment]
Have a good one.

**Comment by meanreaksmey** [comment]
@patchthecode  how can I hide cell is not not current ?

**Comment by patchthecode** [comment]
[example](https://www.youtube.com/watch?v=1Sta3aEo9E4)

**Comment by meanreaksmey** [comment]
@patchthecode thanks now it work 🥇
