### ISSUE TITLE
Invalid Redeclaration of func calendar and CustomCell has no member of selectedView

### ISSUE THREAD

**Issue by Davesanity9** [patchthecode/JTAppleCalendar#763]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. :  **xCode 9.3 beta**
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5 : **Yes**
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
Im sorry, but this is not enough information for me to recreate the problem

**Comment by Davesanity9** [comment]
Its okay. I already solved the problem. Thanks! Cheers

**Comment by patchthecode** [comment]
awesome. cool.
