### ISSUE TITLE
Multiple Months with Month Name In-Between

### ISSUE THREAD

**Issue by hactar** [patchthecode/JTAppleCalendar#767]
Hi there,

I'm about to pick a cal library for my next project, JTAppleCalendar appears the nicest, but there's one question I cannot find an answer for.

Can one create an apple-like cal like here with month names inbetween the months:

![2598de3a-db42-11e6-8699-6a85d58dbc2f](https://user-images.githubusercontent.com/645674/39312339-a167f856-496f-11e8-9462-2346b068c560.PNG)

Or at least like here:
![fscal](https://user-images.githubusercontent.com/645674/39312688-754e080e-4970-11e8-8740-34f9b69251a6.png)

In particular:
- Can one show multiple months below each other, with the month names as headers between the months. This includes the actual data, not just greyed out days like the JTAppleCalendar demo screen shots show

I just need a "yes it can" and I'll figure it out, but I'm just worried because non of the demo screen shots have month names between months, and the Common Questions section only lists "make the cells smaller" as the answer, but that wouldn't add that month name as far as I understand.

**Comment by patchthecode** [comment]
This can and has already been done many times.

some one has already done something like it --> https://github.com/patchthecode/WLAppleCalendar
This calendar has the "look"

Now if you want the multiple months, then all you have to do is implement headers.

```swift

calendarView.register(UINib(nibName: "MySectionHeaderView", bundle: Bundle.main),
                              forSupplementaryViewOfKind: UICollectionElementKindSectionHeader,
                              withReuseIdentifier: "MySectionHeaderView")


func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {
   let header = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: "MySectionHeaderView", for: indexPath) 
   return header 
} 

func calendarSizeForMonths(_ calendar: JTAppleCalendarView?) -> MonthSize? { 
   return MonthSize(defaultSize: 20) 
}
```

**Comment by patchthecode** [comment]
If you want the Month to look Exactly like AppleCalendar month where the `monthName` appears directly over the 1st date of the month, then this is also easy to do.
Make your month Header into a UIStackView with 7 labels equally spaced.

Then simply check on which column the 1st lands on (if column 1,2,3,4,5,6 or 7). Now depending on the column, just hide all the labels except the one where the column is on. Done. You will have an apple calendar clone.

**Comment by mgurreta** [comment]
@hactar you can build really good stuff with this library, it is super flexible

Here an example of `Multiple Months with Month Name In-Between`:
![32976927-51bcd68e-cbd7-11e7-8035-841a233ed7d7](https://user-images.githubusercontent.com/73706/39323280-fbe15a36-4940-11e8-9884-5f23d3fbcbb7.gif)

**Comment by hactar** [comment]
Awesome, thanks I'll be using this lib then, just wanted to make sure its doable, I'll figure it out with the hints you posted, thanks everyone.

**Comment by tomassliz** [comment]
@mgurreta Can you provide more details how did you achieve displaying names of days for each month? Is the day names row part of the section header or did you use some different solution? Thank you.

**Comment by patchthecode** [comment]
@tomassliz He implemented a header -> A UIStackView with 7 labels.

Details for implementing headers is found on the turotial wiki -> https://github.com/patchthecode/JTAppleCalendar/wiki/Tutorials number(6)

**Comment by tomassliz** [comment]
@patchthecode I know how to implement headers but I was curious if there is some other option than put month name and days names into single header.

**Comment by patchthecode** [comment]
@tomassliz 

>  I was curious if there is some other option than put month name and days names into single header.

There are many other options. You can design anything in your header. I'm not sure if i misunderstood your question... let me know.

**Comment by patchthecode** [comment]
@tomassliz message here if you are online. Will be faster -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by Fatimazodi** [comment]
@patchthecode I'm using headers in my project, but I need to make the first header to have some different content and size. I was wondering if it's possible to give different sizes to headers. Currently I'm using the only method: `calendarSizeForMonths` but only returning one default size for all headers.
