### ISSUE TITLE
JTAppleCalendar cells are not showing up - empty collection view.

### ISSUE THREAD

**Issue by nicholasdmoore** [patchthecode/JTAppleCalendar#769]
I think I have all the necessary code set up properly because I have no errors, but when I run the project I get a blank collection view. I set the cells background color to be different from the collection view color just in case. I am a beginner at coding so I won't know how to debug very well. I've included pictures from my project so you might be able to see what the problem is. Thank you so much for making this framework and for your help.
- I am using JTAppleCalendar version 7.1.5
![screenshot 2018-04-27_19-04-29](https://user-images.githubusercontent.com/31974362/39390733-d84c7b38-4a4d-11e8-9e48-69eaef4c49a8.png)
![screenshot 2018-04-27_19-05-58](https://user-images.githubusercontent.com/31974362/39390750-0c8dd86a-4a4e-11e8-85fc-85ef140072fb.png)
![screenshot 2018-04-27_19-08-12](https://user-images.githubusercontent.com/31974362/39390771-62cdbfba-4a4e-11e8-93db-d4eecb07ad3c.png)
![screenshot 2018-04-27_19-09-26](https://user-images.githubusercontent.com/31974362/39390786-9adf6516-4a4e-11e8-8fbc-601c1a7d07c6.png)
![screenshot 2018-04-27_19-09-52](https://user-images.githubusercontent.com/31974362/39390787-9b0cfd32-4a4e-11e8-8f0c-047661bd78bb.png)

**Comment by patchthecode** [comment]
@nicholasdmoore missed your msg
but are you sure your `cellForItem` function is being called?

**Comment by patchthecode** [comment]
issue resolved. 
<img width="265" alt="screen shot 2018-04-28 at 11 09 51 am" src="https://user-images.githubusercontent.com/2439146/39399664-bc02688c-4ad6-11e8-904c-7b5c9668c1ab.png">

correct delegate is now set
