### ISSUE TITLE
Scrolling months and years

### ISSUE THREAD

**Issue by vdeep** [patchthecode/JTAppleCalendar#771]
Is it possible to allow both horizontal and vertical scrolling? Horizontal will scroll months and vertical will scroll years?

**Comment by patchthecode** [comment]
@vdeep i am sorry i misread your question. I had a bunch of things going on at once.

You are right. We cannot have horizontal and vertical at the same time. Sorry about that.

**Comment by vdeep** [comment]
It's okay. I ended up using the calendar inside a collection view.
So the hierarchy becomes:

* Collection view (vertical scrolling)
  * Cell
    * Calendar (horizontal scrolling)

This way, the outer collection view scrolls years, and the calendar scrolls months.

**Comment by patchthecode** [comment]
@vdeep pretty creative. I'll save that answer for the next person who asks me your question.
