### ISSUE TITLE
Limiting To/Displaying Set Range of Days

### ISSUE THREAD

**Issue by ccynn** [patchthecode/JTAppleCalendar#773]
-- using version 7.1.5 ---

Is it possible for me to display a calendar for a range of dates?

My goal is to show a user a 10 day calendar from a given date (i.e. May 2nd - May 12th).

I tried configuring in the configureCalendar method with the start/endDate parameters for the case above, but I'd receive cells for all days within May. I'm also wondering if there'd be any issue for instances like May 29th - June 7th in terms of generating the in/out dates.

Below are my parameters I setup in the configureCalendar method:

```swift
let parameters = ConfigurationParameters(
   startDate: startDate, 
   endDate: endDate, 
   numberOfRows: 2,
   calendar: nil, 
   generateInDates: .off, 
   generateOutDates: .off, 
   firstDayOfWeek: nil, 
   hasStrictBoundaries: false)
```

**Comment by patchthecode** [comment]
This is the final update to this calendar and is already in the bucket list for an update.

**Comment by ccynn** [comment]
Ah I see...is this update available anytime soon or are there any suggested workarounds?

Any guidance is appreciated!

**Comment by patchthecode** [comment]
There is a work around i like to call `Boundary-dates`
but it works better with single row calendars. Ive never tried double row calendars.

it is mentioned here -> https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by ccynn** [comment]
Thanks for the reply, I'm admittedly trying to understand how I'll be able to incorporate #365 as a workaround.

My hope is to be able to show on load an unscrollable 2-week calendar displaying a specified day range (i.e. 4th-18th) and pre-selected cells that can thereafter be manually selected/deselected.

Any guidance/available tutorial would be appreciated, or if there's anything more I can supply I will try to!

**Comment by patchthecode** [comment]
If you want your calendar to be unscrollable, then #365 will not be of any help to you.
Maybe if you show me a screen shot of how your unscrollabe calendar with the range *should* look, then i can help further.

**Comment by ccynn** [comment]
I was able to resolve for my needs.

**Comment by patchthecode** [comment]
awesome 🍻
