### ISSUE TITLE
Please release new version to make number of rows free to change, thx!

### ISSUE THREAD

**Issue by massacreformash** [patchthecode/JTAppleCalendar#777]
current ver. : 7.1.5
issue: 
i found that you make the number of rows of Calendar is free from 1 to 6, but current version on pods still only support 1, 2, 3 and 6 rows.
please release a new ver. on pods to make it works! thanks a lot!

the comparison of two version:

![image](https://user-images.githubusercontent.com/12970186/39823443-a8677dc8-53df-11e8-91b6-b0c2536e9be7.png)

**Comment by patchthecode** [comment]
hi, you can use the master branch for now with your cocoapod file.
Version 7.1.6 will be released with other updates as well.

**Comment by patchthecode** [comment]
closing issue.
Let me know if you have other problems
