### ISSUE TITLE
selectDates() leads to a failed cell cast after scrollToDates() closure

### ISSUE THREAD

**Issue by adrgrondin** [patchthecode/JTAppleCalendar#778]
I am using JTAppleCalendar 7.1.4 and during the implementation of a search functionality I have found something that I can't solve. After searching for a day (with a search bar) my calendar will scroll to the searched date and select this date (which will perform a show segue). However the segue is not always performed with the following code : 

```swift
calendarView.scrollToDate(searchedDate, triggerScrollToDateDelegate: true, animateScroll: true, preferredScrollPosition: nil, extraAddedOffset: 0.0) {
   self.calendarView.selectDates([searchedDate], triggerSelectionDelegate: true)
}
```

The cast with the guard is what prevent the segue (the cast sometime fails for no apparent reason):

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        print("DID SELECT DATE")
        guard let validCell = cell as? CustomCell else {
            print("CELL NOT VALID")
            return
        }
// performSegue here...
}
```

If I search the date again (in the same month visible on the screen) the cast is successful. This is maybe related with the scroll animation (maybe played too fast because with animateScroll set to false the cast always fails on the first try (but is performed on the second again).

What is happening here and how can a ensure that the casting never fail  ?

Thank you for this library @patchthecode !

**Comment by patchthecode** [comment]
you are correct.
The closure *should* ensure that the cell is already on the screen.
Is it possible that you can zip a stripped down version of the project that only has this error in it?
send to patchthecode@gmail.com and let me know.

**Comment by AdrienGrondin** [comment]
Done !

**Comment by patchthecode** [comment]
ok. I got the app.
Can you give me some example dates which will show up the problem?
The ones i have tried are working properly.

**Comment by adrgrondin** [comment]
There are no specific dates that give the error sometime it take more than 6 attempts, sometime the same date can fail and after a retry it can work properly. I was often altering between dates in 1920-1930 and 2010-2020. All the tests was made on a real device. I will send you a video of this error on your email.

**Comment by patchthecode** [comment]
I found a way to recreate your issue 100%

1. run sample app you sent me via email
2. start with date `9 avril 1918`

This fails every time. It looks as if when you set a LARGE range, the scroll animation is not yet complete.
This is weird because i have the code which runs the completion handler located in here in the file called `UIScrollViewDelegates.swift`:
```swift
    /// Tells the delegate when a scrolling
    /// animation in the scroll view concludes.
    public func scrollViewDidEndScrollingAnimation(_ scrollView: UIScrollView) {
        isScrollInProgress = false
        if
            let shouldTrigger = triggerScrollToDateDelegate,
            shouldTrigger == true {
            scrollViewDidEndDecelerating(scrollView)
            triggerScrollToDateDelegate = nil
        }
        executeDelayedTasks(.scroll)
        saveLastContentOffset(scrollView.contentOffset)
    }
```

According to Apple Documentation, this function is definitely called after animaiton finished

> Tells the delegate when a scrolling animation in the scroll view concludes.
The scroll view calls this method at the end of its implementations of the setContentOffset(_:animated:) and scrollRectToVisible(_:animated:) methods, but only if animations are requested.

So i am not sure why it is being called when it is not yet finished.
As a fix, can you go to that function and change to source to the following?

go to file `UIScrollViewDelegates.swift` and find the function: 
```swift
     /// Tells the delegate when a scrolling
    /// animation in the scroll view concludes.
    public func scrollViewDidEndScrollingAnimation(_ scrollView: UIScrollView) {
        isScrollInProgress = false
        if
            let shouldTrigger = triggerScrollToDateDelegate,
            shouldTrigger == true {
            scrollViewDidEndDecelerating(scrollView)
            triggerScrollToDateDelegate = nil
        }
        DispatchQueue.main.async {
            self.executeDelayedTasks(.scroll)
            self.saveLastContentOffset(scrollView.contentOffset)
        } 
    }
```

If this update works for you then i will implement it.
But what i'd really like to know is why that function is being called before animation completes for large range scrolling.

**Comment by patchthecode** [comment]
if i put a breakpoint in that function, i can see that the calendar on the right has not yet finished scrolling to the point, but yet, the function is already called. Apple weirdness?
The calendar is scrolling toward 9 avril 1918. It has reached half way in scrolling (not yet finished scrolling) and the function is called :/ 

<img width="1021" alt="screen shot 2018-05-15 at 4 57 47 am" src="https://user-images.githubusercontent.com/2439146/40055402-a8134fde-57fc-11e8-850f-bb1c12310ce7.png">

**Comment by patchthecode** [comment]
https://github.com/patchthecode/JTAppleCalendar/issues/778
