### ISSUE TITLE
Switch between month is not smooth, when UICollectionCell has complex UI.

### ISSUE THREAD

**Issue by vasant-indpro** [patchthecode/JTAppleCalendar#780]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by vasant-indpro** [comment]
![simulator screen shot - ipad pro 9 7-inch - 2018-05-10 at 14 13 01](https://user-images.githubusercontent.com/31093499/39928196-51b3f7da-5552-11e8-919f-14ae0c1bc588.png)

Here is my screenshots.

I am using latest version of JTAppleCalendar which is 7.1.5, If I add stackView in cell, scrolling isn't smooth(There is jerk while switching between cell) at all, I have tried using just multiple labels, still I experienced the same issue. If I delete all the stackview/Views and keep one or two labels, reduces the amount of jerk.

```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "MonthCustomCell", for: indexPath) as! MonthCustomCell
        
        cell.addDoubleTap(to: self, action: #selector(doubleTapped(_:)))
        
        cell.belongsToThisMonth = cellState.dateBelongsTo == .thisMonth
        cell.date = date
        
        if let dayAssignment = self.dayAssignments?[indexPath.row] {
            cell.dayAssignment = dayAssignment
        }
        
        var isSelected = false
        if date.isEqual(self.selectedDate) {
            selectedCell = cell
            isSelected = true
        }
        cell.isCellSelected = isSelected
        
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
    }
```

Could you please suggest me, how my can be designed to reduce the jerk? Thanks!

**Comment by patchthecode** [comment]
This library uses a UICollectionView subclass.
I do not do any resource intensive calculations under the hood.
The only place I can help you determine why you calendar isnot scrolling smoothly is if you share me your 

1. `cellForItemAt` code
2. `willDisplayCell` code

Since these are the 2 functions where the bulk of things happen.

**Comment by patchthecode** [comment]
closing this issue until further info is provided.
I just set flag to awaiting user input.

**Comment by vasant-indpro** [comment]
`
 func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "MonthCustomCell", for: indexPath) as! MonthCustomCell
        
        cell.addDoubleTap(to: self, action: #selector(doubleTapped(_:)))
        
        //cell.belongsToThisMonth = cellState.dateBelongsTo == .thisMonth
        cell.date = date
        
        if let dayAssignment = self.dayAssignments?[indexPath.row] {
            cell.dayAssignment = dayAssignment
        }
        
        var isSelected = false
        if date.isEqual(self.selectedDate) {
            selectedCell = cell
            isSelected = true
        }
        cell.isCellSelected = isSelected
        
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
    }

`

**Comment by patchthecode** [comment]
Remember, the calculations you are doing is being done 42 times every time you do a scroll.
is it possible you are doing too much in the calculations?

**Comment by vasant-indpro** [comment]
Even if I avoid(Comment calculation code for testing) calculation and just show dummy UI on all 42 cells, Still I face same issue.

is there any solution so I could make it smoother with my requirements? Thanks!

**Comment by vasant-indpro** [comment]
```
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "MonthCustomCell", for: indexPath) as! MonthCustomCell
 
        return cell
    }
```


In this case works smooth.

**Comment by patchthecode** [comment]
Good, then if this is the case, can you slowly **one by one** add back your calculations until you know which is the calculation that is breaking the back of your smooth scrolling?
