### ISSUE TITLE
scrollToSegment(.next) doesn't scroll if you call it multiple times

### ISSUE THREAD

**Issue by agordeev** [patchthecode/JTAppleCalendar#782]
First of all thanks for the great library!

This issue is reproducible on example project: when you quickly tap Next month button, the calendar stops scrolling. I tried to debug `scrollToSegment` method and found out that `contentOffset.x` in this row:

    let section = CGFloat(Int(contentOffset.x / fixedScrollSize))

is not incrementing. Any idea how to fix/workaround?

**Comment by patchthecode** [comment]
can you try the new master branch code?
https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

let me know if it works.
new master branch code also fixed so that the following behavior also works as expected.
```swift
        sender.isEnabled = false
        self.calendarView.scrollToSegment(.next) {
            sender.isEnabled = true
        }
```

**Comment by agordeev** [comment]
Thanks, looks good now! When are you planning to release a new version?
