### ISSUE TITLE
Paging not correctly aligned

### ISSUE THREAD

**Issue by Mackarous** [patchthecode/JTAppleCalendar#785]
**Update: This is not only happening in the popover, for some reason it happens in a modal view controller also**

I am currently using v7.1.5 of JTAppleCalendar.

I created a view controller in a popover style for the calendar. 
I am attempting vertical paged scrolling
The pages of the collection view are misaligned.

Code for popover:
```swift
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    guard segue.identifier == "calenderSegue" else { return }
    segue.destination.modalPresentationStyle = .popover
    guard let popoverPresentationController = segue.destination.popoverPresentationController else { return }
    popoverPresentationController.delegate = self
    popoverPresentationController.sourceView = titleButton
    popoverPresentationController.sourceRect = titleButton.frame
    segue.destination.preferredContentSize = CGSize(width: view.bounds.width * 0.8, height: view.bounds.width * 0.8)
}

extension MyViewController: UIPopoverPresentationControllerDelegate {
    func adaptivePresentationStyle(for controller: UIPresentationController) -> UIModalPresentationStyle {
        return .none
    }
}
```
These screenshots were taken when the collection view was on a page, not mid-scroll

![shot1](https://user-images.githubusercontent.com/1043281/40117992-2d99a0e6-594b-11e8-81ed-ecc31f1055c5.png) | ![shot2](https://user-images.githubusercontent.com/1043281/40117994-2dd7cd30-594b-11e8-94cf-ee6171208002.png) | ![shot3](https://user-images.githubusercontent.com/1043281/40117995-2e0ff5ac-594b-11e8-9fdd-61691def3ed4.png)
--- | --- | ---

**Comment by patchthecode** [comment]
mind joining here?
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
resolved.
