### ISSUE TITLE
Bad performance on big range selection

### ISSUE THREAD

**Issue by nurkhatp** [patchthecode/JTAppleCalendar#787]
It's default code of range selection. When select few years, screen stops answering touch and delays 
 few second (depends on selected range) untill selection process has finished.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9607349/40269214-d9325404-5b9c-11e8-9130-fd44fa1b5f1a.gif)

**Comment by patchthecode** [comment]
A bit more information?

**Comment by nurkhatp** [comment]
Is there any idea to make it faster?

**Comment by patchthecode** [comment]
looking into it.

**Comment by muthukrishnanOCS** [comment]
Hi @nurkhatp , can you share this sample source? or please explain how to enable the range selection in this calendaerview

**Comment by muthukrishnanOCS** [comment]
@patchthecode how to remove 6th row?
![screenshot](https://user-images.githubusercontent.com/5507534/42263028-8585ec0a-7f8a-11e8-9b0c-62175bef9fb0.jpeg)

**Comment by patchthecode** [comment]
@muthukrishnanOCS 
hi, If you are asking questions that are unrelated to this main issue, then you'll new to create a new issue. In answer to your question however -> https://patchthecode.github.io/CalendarLayout/

**Comment by rs658726** [comment]
> It's default code of range selection. When select few years, screen stops answering touch and delays
> few second (depends on selected range) untill selection process has finished.
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9607349/40269214-d9325404-5b9c-11e8-9130-fd44fa1b5f1a.gif)

Are you sure it's not a simulator issue? Have you tried it on your phone?

**Comment by patchthecode** [comment]
@rs658726 you are not seeing the issue?

**Comment by rs658726** [comment]
@patchthecode I have seen this issue before on a simulator, but never on an actual device.

**Comment by patchthecode** [comment]
@rs658726 interesting.
Thanks for mentioning this.
I'll test of device.

**Comment by GodriXx** [comment]
I got this issue and fixed by turning `triggerSelectionDelegate` to false

so in my `didSelectDate` method, I have some logic to select ranges using `calendar.selectDates(dateRange, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)`

I've got high memory consumption when selecting a range of 12 months with like 10 seconds to complete it,
turn your `triggerSelectionDelegate` to false, that will fix it
I home it helps you

**Comment by patchthecode** [comment]
@GodriXx thank you!

**Comment by patchthecode** [comment]
closing issue
