### ISSUE TITLE
failed to render and update auto layout status for CalendarView Controller 

### ISSUE THREAD

**Issue by seongminchoob** [patchthecode/JTAppleCalendar#788]
my calendar was working fine but suddenly im getting this issue..

**Comment by patchthecode** [comment]
--> [seems not lib related](https://www.startpage.com/do/dsearch?query=failed+to+render+and+update+auto+layout+status+for&cat=web&pl=ext-ff&language=english)

Any screen shots?

**Comment by seongminchoob** [comment]
never mind it was an internal error of xcode!

**Comment by patchthecode** [comment]
ok. cool.
