### ISSUE TITLE
ReloadData(withanchor: date)

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#789]
Hi, I am on latest version 7.1.5
Calling reloadData with anchor sometimes drops scroll position to top.
How can I handle this?

**Comment by patchthecode** [comment]
> sometimes drops scroll position to top.

could you explain? Did you mean it scrolls the library all the way to the first date?

**Comment by mecid** [comment]
Yes, exactly.

**Comment by patchthecode** [comment]
Can you give some more information?

What do you do before the happens?
Do you change the frame of the calendar view? Does any thing relating to frame or position or size of anything relating to the calendar change?

**Comment by mecid** [comment]
@patchthecode 
I am not changing calendar frame, it is static. I am showing vertical calendar for 2 years.
Every page show single month.

1st: scrollToDate(Date.today(), animateScroll: false) at ViewDidLoad
2nd: on every didScrollToDateSegmentWith fetch data from local database and call 
            guard let date = calendarView.visibleDates().monthDates.first?.date else { return }
            calendarView.reloadData(withanchor: date)
to show fetched data only for visible month.

**Comment by mecid** [comment]
@patchthecode any ideas, how to fix this problem?

**Comment by patchthecode** [comment]
Can you let me know if this is still occurring on master branch?
https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by mecid** [comment]
@patchthecode fixed on master branch

**Comment by sambong0113** [comment]
Is this problem Fixed?? My version is 7.1.7 and I use calendar without storyboard. It also happen to me when I call `caledarView.reloadData(withAnchor: Date()){ ... }` in `viewDidLoad()`.
