### ISSUE TITLE
Extra Header Space

### ISSUE THREAD

**Issue by stillLife456** [patchthecode/JTAppleCalendar#79]
Hello again,
I'm having a problem that I'm sure has a simple fix, I just can't find it!
It seems that the Calendar is making space for an "extra" header that shouldn't be there. With registerHeaderViewXibs commented out I get this:
<img width="323" alt="screen shot 2016-07-17 at 6 11 34 pm" src="https://cloud.githubusercontent.com/assets/19790450/16904427/d999343e-4c4a-11e6-92a8-741f18601271.png">

And when I uncomment them I get this:
<img width="321" alt="screen shot 2016-07-17 at 6 12 32 pm" src="https://cloud.githubusercontent.com/assets/19790450/16904440/4daf4fca-4c4b-11e6-9948-660213bd1162.png">

Sorry for the ugly colors. The background color for the UIView is purple, the background color for the calendarView is yellow. The background color for the header xib is pink. It seems like the calendarView is adjusting its layout to make space for a header whether it is asked to or not. Any help is appreciated.

**Comment by patchthecode** [comment]
I may be able to provide you some help, 
but you are out of star credits 😏. 
Please hit the star ★ button of this repository to restart the help machine

**Comment by patchthecode** [comment]
Thanks!!
OK. Writing up the answer to this now. 
Give me 10 mins.

**Comment by stillLife456** [comment]
Great, thanks

**Comment by patchthecode** [comment]
Ok. After being a little mean to you, I really do hope this solves your problem xD
Check out the Wiki Question # 6 here --> https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions

**Comment by stillLife456** [comment]
Thanks, that did it! I feel like an idiot.

**Comment by patchthecode** [comment]
Nah man. No worries. No need to beat ya self up. 
Cheers.
