### ISSUE TITLE
hi, xcode 9. don't have JTAppleCalender, i need to download the JTAppleCalender where do install one?

### ISSUE THREAD

**Issue by hihaihy** [patchthecode/JTAppleCalendar#793]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
you need to do it via cocoapods.
There are many tutorials online on how to use either cocoapods or carthage  with your project.
here is two old vids i did on this.
https://www.youtube.com/watch?v=wyh_DVFeH_w&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q

Hope this helps.
