### ISSUE TITLE
date class given in the didselect function is behaving strange 

### ISSUE THREAD

**Issue by seongminchoob** [patchthecode/JTAppleCalendar#795]
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        formatter.dateFormat = "yyyy MM dd"
        print("The selecting part")
        currentDate = date
        print(date)
        print(date.dateTimeString())
}

this is the code I had, 

and 2018-05-31 15:00:00 +0000
Jun 1, 2018 at 12:00:00 AM 

this is the output I have..

I do not know where 2018-05-31 15:00:00 +0000 is coming from, where it should be 2018-06-01..

I wonder if it's an internal error..

**Comment by patchthecode** [comment]
Sounds like youre experiencing this -> https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
closing issue.
let me know if this works
