### ISSUE TITLE
Can't create IBOutlet of JTCalendarView

### ISSUE THREAD

**Issue by Tom-Fox1** [patchthecode/JTAppleCalendar#796]
I'm trying to follow the tutorial - [https://www.youtube.com/watch?v=Qd_Gc67xzlw](video). It tells you to create an IBOutlet for the JTAppleCalendarView however upon doing this I got the following error

`The calendarView outlet from the CheckoutTableViewController to the JTAppleCalendarView is invalid. Outlets cannot be connected to repeating content.`

I did later find that the attributes that were changed in the tutorial could also be done within the attributes inspector in interface builder. 

Perhaps a note could be added to to the tutorial explaining this?

**Comment by Tom-Fox1** [comment]
My apologies for this I now realise the issue arose because I embedded the collection view within a table view.

**Comment by patchthecode** [comment]
cool. no worries
