### ISSUE TITLE
ShouldScrollToTop delegate

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#798]
How to implement this method?

**Comment by patchthecode** [comment]
JTAppleCalender > UICollectionView > UIScrollView

so implement this? https://developer.apple.com/documentation/uikit/uiscrollviewdelegate/1619378-scrollviewshouldscrolltotop

**Comment by mecid** [comment]
@patchthecode yeah, I know it. But i have strange problem. Delegate property not visible for calendarView.
<img width="1189" alt="screen shot 2018-06-06 at 06 26 40" src="https://user-images.githubusercontent.com/324372/41040939-a97604fe-6952-11e8-87a8-23e990c368f9.png">

**Comment by patchthecode** [comment]
Ah not strange.
You just have to make a subclass.

```swift
class CustomJTAppleCalendarView: JTAppleCalendarView {
    func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
        return false
    }
}
```

Now use `CustomJTAppleCalendarView` on your storyboards and @IBOutlets.
Let me know if it works for you

**Comment by mecid** [comment]
@patchthecode hmm, but this is scrollViewDelegate method. Why I can't assign new delegate to calendarView and do my check there?

**Comment by patchthecode** [comment]
Hmm, but how do you intend to set a scrollViewDeleagte to a `JTAppleCalendarView` class?

Isn't the UIScrollViewDelegate is a protocol that your class has to conform to?

if you declared a class like below:
```swift
class MyCustomScroller: UICollectionView {

}
```

Then you get to use the UIScrollViewDelegate by conforming to it like so
```swift
extension MyCustomScroller: UIScrollViewDelegate {
   // implement the scroll view delegates here
}
```

**Comment by mecid** [comment]
@patchthecode yeah, that's what about I am talking.

**Comment by patchthecode** [comment]
Ok, therefore, to use the `scrollViewShouldScrollToTop` delegate, 
You can do it in 2 ways:

## 1 
Create a subclass of JTAppleCalendarView and use it
```swift
class CustomJTAppleCalendarView: JTAppleCalendarView {
    func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
        return false
    }
}
```

## 2
Create an extension inside your viewController and add this code
```swift
extension JTAppleCalendarView {
    func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
        return false
    }
}
```

**Comment by mecid** [comment]
Yeah, thank you. I am using first one right now.

**Comment by patchthecode** [comment]
cool. 🍻
