### ISSUE TITLE
How do you add the colored dots below dates?

### ISSUE THREAD

**Issue by hadiyazdi** [patchthecode/JTAppleCalendar#799]
Whenever I try to add rounded labels below the date and color them according to the date events I get a messy layout

I couldn't find a tutorial on how to achieve this in the videos, but many screenshots show colored dots (one or more) below the date without having any issue?

Thanks for your help

**Comment by patchthecode** [comment]
Are you sure you have your constraints etc set correctly?

zip a sample project with the messy layout and drop it in this chat box.
