### ISSUE TITLE
How to show weekdays?

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#80]
Any best practices how to show weekdays or this must be a custom view above calendar view?

**Comment by patchthecode** [comment]
How to show weekdays? what do you mean?

**Comment by patchthecode** [comment]
You can join me here --> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by mecid** [comment]
@patchthecode i want to show weekday labels like sunday, monday, etc.
