### ISSUE TITLE
Large Text Support

### ISSUE THREAD

**Issue by chamitha** [patchthecode/JTAppleCalendar#800]
Hi there. What is the recommended approach for supporting large text?
It appears that the cellSize property determines the size of the cell regardless of the constraints defined in the custom cell nib.

**Comment by patchthecode** [comment]
I have never dealt with large text before.
If you know the size of the text, then is it possible you can adjust the `cellSize` so that it fits?

**Comment by chamitha** [comment]
That is certainly an option but involves the need to perform calculations. In a UICollectionViewFlowLayout, setting the estimatedItemSize allows a cell with auto layout constrains to auto resize. Not sure if exposing estimatedItemSize is an option if the custom layout used is reliant on cell size calculations.

**Comment by patchthecode** [comment]
The custom layout *is* reliant on cellSize. Would exposing estimatedItemSize help your case?
I have never looked into large text things. So i do not know much on it yet.

**Comment by patchthecode** [comment]
closing issue until user responds.

**Comment by chamitha** [comment]
I doubt it would if the cell size is based on calculations instead of auto layout. I'll investigate this further when I start on accessibility.

**Comment by patchthecode** [comment]
thanks. let me know.
will be interested in this as well
