### ISSUE TITLE
Implementation of pre-load cells 

### ISSUE THREAD

**Issue by rollin-s** [patchthecode/JTAppleCalendar#801]
Hello, I'm using this library a lot, and I just wanted to know if there is any way to preload cells that are not present yet ? 
I didn't found anything in your documentation, and the willLoadcell is not implemented
This does look like [this](https://imgur.com/a/IPxp470)

I implemented the loading of the cells like that 

```swift
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        let date = calendar.visibleDates().monthDates.first?.date
      
        formatter.dateFormat = "MMMM yyyy"
        monthYear.text = formatter.string(from: date!)

        
        interactor?.fetchRDVFromAgendasCurrentMonth(request: AgendaModel.Request.fetchAgendasRDVCurrentMonth(day: date, view: self))
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        
        let cell = cell as! AgendaDayCell
        sharedFunctionToConfigureCell(myCell: cell, cellState: cellState, date: date);
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableCell(withReuseIdentifier: AgendaDayReuseIdentifier, for: indexPath) as! AgendaDayCell
        sharedFunctionToConfigureCell(myCell: cell, cellState: cellState, date: date)

        return cell;
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        let myCell = cell as! AgendaDayCell
        
        self.displayedRDV.removeAll()
        self.displayedRDV = myCell.RDV
        self.listRDV.reloadData();
    }
```

Is it possible with your library ?

**Comment by patchthecode** [comment]
sounds like youre talking about cell prefetching? -> https://developer.apple.com/documentation/uikit/uicollectionviewdatasourceprefetching/prefetching_collection_view_data

This feature comes with UICollectionView out of the box. Since JTAppleCalendar is a UICollectionView subclass, it should have this as well out of the box.

btw, shouldnt your VIP model be -> `AgendaModel.FetchAgendasRDVCurrentMonth.Request` ?

**Comment by rollin-s** [comment]
Oh, I didn't know this notion, I searched for it, but didn't find it.. (guess I search badly 👎  )
This is exactly what I'm looking for, thanks ! 


About VIP, the way you did it works, but I'm currently into the CleanSwift architecture (small derivate of VIP) which doesn't use the interaction the exact same way than the VIP. 
But thanks for your advice, I'll looking into it !

**Comment by patchthecode** [comment]
>  But does the prefetching give me the date, or I should implement this myself ? :)

hmm you have a point there.
Test this for me and if it works i'll make an update in the library.

The following function is in the **InternalQueryFunctions.swift** file.
```
func dateOwnerInfoFromPath(_ indexPath: IndexPath) -> (date: Date, owner: DateOwner)?
```

It returns you the date and the owner.
But it is private.
Make it public and let me know if it works for you.

**Comment by patchthecode** [comment]
closing issue as original question answered.
