### ISSUE TITLE
Unable to implement JTAppleCalendar tutorial project 

### ISSUE THREAD

**Issue by RyanCallery** [patchthecode/JTAppleCalendar#802]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

1) Using version 7.1.5 downloaded 6/8/18.  Using Xcode 9.4 Beta.

This is the first cocoapods class I have used.  Installed cocoapods then JTAppleCalendar 6/8/18.  Created a Xcode project exactly as tutorial instructed.  I have recreated this multiple times.  Have shut down and restarted XCode/computer.  Have spent hours trying to get it to execute calendar.  

Xcode seems to be getting stuck on this line of code provider in the JTAppleCalendar library.

    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setupNewLayout(from: collectionViewLayout as! JTAppleCalendarLayoutProtocol)
    }

It crashes on the setupNewLayout method.  
I have attached a few images.
<img width="1013" alt="errormessage" src="https://user-images.githubusercontent.com/40044106/41171275-fbe1b180-6b1d-11e8-8027-bf3fff5576db.png">
<img width="1182" alt="calendarviewdelegate and datasource" src="https://user-images.githubusercontent.com/40044106/41171286-03820688-6b1e-11e8-91a6-6c3131856e42.png">
<img width="1127" alt="calendarviewclass" src="https://user-
[ViewController.pdf](https://github.com/patchthecode/JTAppleCalendar/files/2085378/ViewController.pdf)

Any help would be greatly appreciated.  I'd love to use this.  

Ryan

**Comment by patchthecode** [comment]
Can you show screen shot of class type on the story board?

**Comment by RyanCallery** [comment]
[HelloCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2085819/HelloCalendar.zip)

Yes, absolutely.  Thanks for the quick response.  Here is the zip file.  

Best,
Ryan

**Comment by RyanCallery** [comment]
One thing I've noticed is that I have more outlet options in my storyboard than were present in your tutorial.  Also, these outlet options did not show in the zip file I sent to you.  I'm not sure why this is.  If you look at the screen shot about you will see 
dataSource
delegate
ibCalendarDataSource
ibCalendarDelegate 

All four of these were not shown in your tutorial and for some reason they are shown in the zipped file.  

Ryan

**Comment by patchthecode** [comment]
just checked out the zip file.

the project file is missing as well as the cocoapods.
Need the whole thing to see what went wrong.
The code looks ok.

**Comment by patchthecode** [comment]
hope you didnt accidentally delete the proj file together with the Build folder 😅

**Comment by RyanCallery** [comment]
Here they are.  I think this is the cocoapods file you are referring to.  

[HelloCalendar.xcodeproj.zip](https://github.com/patchthecode/JTAppleCalendar/files/2086505/HelloCalendar.xcodeproj.zip)
[Pods.xcodeproj.zip](https://github.com/patchthecode/JTAppleCalendar/files/2086506/Pods.xcodeproj.zip)

Thanks again,
Ryan

**Comment by patchthecode** [comment]
Hey. i got tied up. Jst getting back to this.
Is this still an issue? Can you just zip the project like normally?

one zip file with your project so that i can double click and unzip it?
I now have 3 separate zip files and when i unzip them, files etc are missing. Can you try unzipping the files you sent me and see if you can open them? because they are not for me.

**Comment by RyanCallery** [comment]
No worries.  I am sure you have many better things to do than help me with my calendar problem.  Thanks for getting back.  It is still a problem.  I have tried various things but still no go.  I apologize about the zip.  This zip I have attached has all the files when I open it.  I hope it doesn't give you any problems.  

[HelloCalendar_3.zip](https://github.com/patchthecode/JTAppleCalendar/files/2096144/HelloCalendar_3.zip)

**Comment by patchthecode** [comment]
your module was blank.
<img width="261" alt="screen shot 2018-06-12 at 5 55 43 pm" src="https://user-images.githubusercontent.com/2439146/41324552-ee0cda0e-6e69-11e8-99f1-7ba8b47a1096.png">

**Comment by RyanCallery** [comment]
Oh my god it is working.  I must have changed these things around one hundred times.  Thanks so much for your time.  
Ryan

**Comment by patchthecode** [comment]
sure thing.
have a good one 🍻

**Comment by RyanCallery** [comment]
Thanks again for the help.  The calendar is loading but unfortunately it’s not scrolling.  Any idea why this may be?

**Comment by patchthecode** [comment]
it wont scroll if you are only displaying one month.

**Comment by RyanCallery** [comment]
But I don't think I should be displaying just 1 month.  I wrote the code
exactly as you did in the tutorial.   Start date Jan 1, end date Dec 31 of
2017.

    func configureCalendar(_ calendar: JTAppleCalendarView) ->
ConfigurationParameters {

        formatter.dateFormat = "YYYY MM DD"

        formatter.timeZone = Calendar.current.timeZone

        formatter.locale = Calendar.current.locale

        let startDate = formatter.date(from: "2017 01 01")!

        let endDate = formatter.date(from: "2017 12 31")!



        let parameters = ConfigurationParameters(startDate: startDate,
endDate: endDate)

        return parameters

    }

**Comment by patchthecode** [comment]
is it possible can you zip your project and send?

**Comment by RyanCallery** [comment]
Yes, of course.  Here it is.

Ryan

**Comment by patchthecode** [comment]
didnt get it. sent to patchthecode@gmail.com ?

**Comment by patchthecode** [comment]
put this in your `confogureCalendar` function

```swift
print(startDate)
print(endDate)
```

You will see that you are displaying only one month

**Comment by patchthecode** [comment]
fix that and your problem is solved.

**Comment by RyanCallery** [comment]
Thank you.  I see that I was not using the right syntax in the dateFormat.
It is now scrolling.
