### ISSUE TITLE
Problem in updating cell on didSelect.

### ISSUE THREAD

**Issue by salvimayur89** [patchthecode/JTAppleCalendar#808]
First of all thank a lot for great library. Im using latest version of pod on Xcode v9.4.  
Ive implemented everything as you mentioned in your demo projects and tutorial. Everything is running fine except one thing. Whenever i'm clicking on particular date, then that date is not selected. If i click again on different date then previous date is selected not current one. Same problem in Month and Year updation also.  
I think there might be problem with willDisplay cell function as its not getting. 
Please help and thanks in advance :)

**Comment by patchthecode** [comment]
did you implement the **didSelect** and **willSelect** function as shown in issue #553 ?

**Comment by salvimayur89** [comment]
Yes i have.  Have you tested this with latest Xcode ?

**Comment by patchthecode** [comment]
not yet. will do so over the weekend. Has it been breaking since new XCode?

**Comment by salvimayur89** [comment]
I think its related new update only. Im using JTApple since last night only so no idea.

**Comment by patchthecode** [comment]
hmm. re-read your problem. It doesnnt sound Xcode related.
got a sample project or github somewhere i can take a look at?

**Comment by daviddauv** [comment]
Make sure you selected "didSelectDate" and not "didDeselectDate" which would cause your issue.
