### ISSUE TITLE
Possible feature

### ISSUE THREAD

**Issue by kwstasna** [patchthecode/JTAppleCalendar#81]
Hello. I was thinking if there is any way of making one events counter in each date cell which indicates something.
Lets say that in the date 14-10-2016 on the "14" cell should have a little circle with a number inside lets say "2" which indicates how many birthdays are in this date. Is there any feature or possible update?
Thanks a lot!

**Comment by patchthecode** [comment]
The goal of this project is to be as flexible as possible.

It allows the developer to create any thing he/she wants. Therefore, if you want an event counter, then create one your self.

This is the way a library should work -> be as flexible as possible.
If I were to add this new feature, then not every developer will want this feature on their design.

So, how will you create one? Simple.
If you have followed the [tutorial](https://github.com/patchthecode/JTAppleCalendar/wiki/Setup-the-calendar-in-this-quick-tutorial) then you will know how to design your dateCell. 
So all you have to do is simply add a counter on the cell with what ever design you want for your project, then add the functionality for it in your custom class.

**Comment by patchthecode** [comment]
Hey, I forgot to tell you: Thanks for the input!
I really like it when you guys give me suggestions. I want this project to be the best of its kind on github. 👍 
Again thanks.
