### ISSUE TITLE
How to scroll only one week?!

### ISSUE THREAD

**Issue by valentinkukjans** [patchthecode/JTAppleCalendar#810]
How to scroll only one week? if I have one row? how to set boundaries? So when I scroll it's match the days on top of my calendar. 

Thanks a lot in advance, Valentins

**Comment by patchthecode** [comment]
not sure what you mean.
Are you talking about paging?

**Comment by valentinkukjans** [comment]
![screen shot 2018-06-16 at 8 29 37 pm](https://user-images.githubusercontent.com/24559524/41504451-2446d1aa-71a4-11e8-81af-43023289ed0c.png)
![screen shot 2018-06-16 at 8 29 24 pm](https://user-images.githubusercontent.com/24559524/41504452-245e604a-71a4-11e8-8b81-70af7e88945b.png)

**Comment by valentinkukjans** [comment]
I wanna achieve same scrolling like calendar app does , scrolls week by week. How to set those boundaries? Thanks

**Comment by patchthecode** [comment]
simply setup a single row calendar -> https://github.com/patchthecode/JTAppleCalendar/issues/581
is this what you mean?

**Comment by valentinkukjans** [comment]
no, in calendar app when you scroll, the header stays (days on top). Can you please check calendar app, and see behavior of it. Thanks for your help.

**Comment by patchthecode** [comment]
I still do not understand what you mean.

> I wanna achieve same scrolling like calendar app does , scrolls week by week

What does this mean? The calendar already scrolls by week/month.
Are you saying you want to implement a header? Please be **extremely** specific. Sometimes an idea in your head may not mean the same in mine.

**Comment by valentinkukjans** [comment]
calendarView.scrollingMode = .stopAtEachSection.  

one line of code solve my problem:) I didn't know about scroll mode. Thanks you for great lib, and been so responsive. 👍

**Comment by patchthecode** [comment]
sure thing.
but this is weird. the default should be -> calendarView.scrollingMode = .stopAtEachFrame ( i think)
but its ok. Glad it is resolved.
