### ISSUE TITLE
How many section is generated in one row calendar?

### ISSUE THREAD

**Issue by valentinkukjans** [patchthecode/JTAppleCalendar#811]
HI, 

Thanks again for great lib. I wanna know how many section,  and how many rows in each section  is generated exactly  in one row calendar? 
also I have  generateInDates: .forFirstMonthOnly.  Why I'm asking this question, because when I try to print it out , looks like its printing if I remember correct 53 sections, and some sections only contains 2 rows, some of them 7 rows.

Thanks in advance, for your help.

**Comment by patchthecode** [comment]
hmm.. maybe im not clear on what youre trying to do.
But here is the setup for most single row calendars -> https://github.com/patchthecode/JTAppleCalendar/issues/581

Does this help?

**Comment by patchthecode** [comment]
closing until user responds
