### ISSUE TITLE
how to iterate all customcell in current month 

### ISSUE THREAD

**Issue by t4i5m6** [patchthecode/JTAppleCalendar#813]
hi,
i use version 7.0 
thanks for your cool library, it makes me do my final project in ios class more convenient!
but i have a question now
i want to iterate all customcell in current month to  check every  date has event in coredata should not hide eventview i created
when i use func calendar(cellforitemat)  it cant work because function calendar(didscrolltodate) do slower than  calendar(cellforitemat) so i cant get the current month and year first
so i think if i can iterate all customcell in currentmonth i can solve my problem
but i have no idea how to iterate without using  func(cellforitemat)

**Comment by patchthecode** [comment]
Hmm. can you explain a bit more what you are trying to do?
When your calendar loads, you want to show events on the calendar (form core data) ?

**Comment by t4i5m6** [comment]
if i select a date , then event will diplay under the calendar
now i want to  highlight the date has event
so i add a view in customcell and it is hidden by default
now i want to make cell has event  highlighted when calendr is loaded(or scroll)
so i want to iterate the custom cell in current month and check if it's date has event
but i dont know how to iterate

**Comment by patchthecode** [comment]
message me here if youre online -> https://gitter.im/patchthecode/JTAppleCalendar


you do not have to iterate.
This lib works the same way as a UITableView or a UICOllectionView.
Do you have a datasource for the events?
You can create a Dictionary datasource. I can have the date as the key and the event as the data.
Then in `cellForItem` functioin, you can simply pull out the data for the appropriate date.

I have an example of this here -> https://www.youtube.com/watch?v=CQNotydm58s

It is under the section that says **loading dates from the server**

**Comment by t4i5m6** [comment]
After watching example and do it, it works!
Thanks for your patience to reply
Have a nice day!

**Comment by patchthecode** [comment]
have a good one.
