### ISSUE TITLE
Do not display rows that out of start - end date

### ISSUE THREAD

**Issue by dbyst** [patchthecode/JTAppleCalendar#816]
Hi. I'm using version 7.1.5.

Is that possible to configure calendar to not display rows that out of start - end date ?
For example:
startDate = "2018-04-25"
endDate = "2018-07-25"

I can see all month dates:

![screen shot 2018-06-25 at 3 17 00 pm](https://user-images.githubusercontent.com/5080130/41849770-d627043e-788a-11e8-938d-abd5b276e55f.png)

But I'd like to see something like this:

<img width="367" alt="screen shot 2018-06-25 at 3 15 16 pm" src="https://user-images.githubusercontent.com/5080130/41849743-b4a83288-788a-11e8-8517-d4cdd0c91ddd.png">

Thanks,

**Comment by patchthecode** [comment]
Not possible at the moment.
I have a long due update for that coming. But been way too busy to implement it.

**Comment by dbyst** [comment]
Ok, thanks for answer
