### ISSUE TITLE
MISSING DAYS IN YOUR DEMO

### ISSUE THREAD

**Issue by blinkmeoff** [patchthecode/JTAppleCalendar#820]
Hi, I was using the latest version, and had problem with days, sometimes there are 1 week missing...
I'm trying to implement 1 row days, which are scrolled horizontally, then I tested the same thing in your demo project, and here you go, take a look at days

![simulator screen shot - iphone 8 plus - 2018-06-29 at 16 09 06](https://user-images.githubusercontent.com/15688672/42094020-0e2f280a-7bb7-11e8-90d2-c9fac136db3d.png)

Looking forward for your reply

**Comment by blinkmeoff** [comment]
Just select 1row mode, and try to scroll throw dates. You will notice, that in some months days are missing

**Comment by patchthecode** [comment]
Days are not missing. What you are seeing are outdates.
If you want the 1row calendar settings i think you need, its located here -> https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by patchthecode** [comment]
```swift
 let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 1,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .off,
                                                 hasStrictBoundaries: false)
```

therefore, 

under **PRE* select the button called **first**.
under **POST** select the button called **OFF**
