### ISSUE TITLE
SCROLL TO, NOT WORKING PROPERLY

### ISSUE THREAD

**Issue by blinkmeoff** [patchthecode/JTAppleCalendar#821]
Another question, default behavior is ok, looks like that with selected current date.
![simulator screen shot - iphone x - 2018-06-29 at 16 26 04](https://user-images.githubusercontent.com/15688672/42094742-6484b3b2-7bb9-11e8-9ed9-126d025b0fc7.png)

But, when I open controller for the first time, and I call this methods:
```
calendarCollection.scrollToDate(Date()) {
      self.calendarCollection.selectDates([Date()])
    }
```

it looks like that, how to fix scrolling offset issue, so the scrollToDate, will scroll to correct day?

![simulator screen shot - iphone x - 2018-06-29 at 16 26 48](https://user-images.githubusercontent.com/15688672/42094836-a5b4c638-7bb9-11e8-9b56-e8c987f74e2c.png)

Thank you!

**Comment by blinkmeoff** [comment]
Just point me, if I'm saying something wrong and this issue has nothing with the repo

**Comment by patchthecode** [comment]
did you build your calendar with code? or with storyboard.
If you built it with code, then do not forget

```swift
calendarView.scrollingMode = .stopAtEachCalendarFrame
```

or which ever one is suitable for you.
