### ISSUE TITLE
The Behaviour Of the UICollectionViewFlowLayout is not defined because...

### ISSUE THREAD

**Issue by zachcrystal** [patchthecode/JTAppleCalendar#823]
Hey there,

I'm creating the calendar and cells programatically and I am getting this error:

```
2018-07-05 22:38:23.395310-0400 App[4517:269288] The behavior of the UICollectionViewFlowLayout is not defined because:
2018-07-05 22:38:23.395450-0400 App[4517:269288] the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.
2018-07-05 22:38:23.395863-0400 App[4517:269288] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x7fac58d0d5b0>, and it is attached to <UICollectionView: 0x7fac5a065000; frame = (8 149; 359 518); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600000253a70>; layer = <CALayer: 0x6000000366e0>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}> collection view layout: <UICollectionViewFlowLayout: 0x7fac58d0d5b0>.
2018-07-05 22:38:23.395957-0400 App[4517:269288] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
```

My calendar initialization is as follows: 
```  
lazy var calendarView: JTAppleCalendarView = {
        let calendar = JTAppleCalendarView()
        calendar.backgroundColor = .white
        calendar.scrollDirection = .horizontal
        calendar.showsHorizontalScrollIndicator = false
        calendar.isPagingEnabled = true
        calendar.calendarDelegate = self
        calendar.calendarDataSource = self
        calendar.allowsMultipleSelection = false
        calendar.minimumLineSpacing = 0
        calendar.minimumInteritemSpacing = 0
        return calendar
    }()
```
My cells don't have any size inits within the Swift file.
I've tried a bunch of things like changing the cellSize property on calendar but nothing seems to be working...

Any ideas?

Thanks,
Zach

**Comment by patchthecode** [comment]
The width/height of the cells depends on the width/height of the calendarView.
Have you properly setup the constraints for the JTAppleCalendarView so that it has a valid width/height?

**Comment by zachcrystal** [comment]
Yeah, my constraints are: 
```
calendarView.topAnchor.constraint(equalTo: topAnchor).isActive = true
calendarView.leftAnchor.constraint(equalTo: leftAnchor, constant: 26).isActive = true
calendarView.rightAnchor.constraint(equalTo: rightAnchor, constant: -26).isActive = true
calendarView.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -12).isActive = true
```
Tried debugging for a while now... nothing is working

**Comment by patchthecode** [comment]
@zachcrystal got a sample app with the problem on github?

**Comment by zachcrystal** [comment]
@patchthecode yeah, I would really appreciate that! :)  i'll recreate it in a sample app and add it to github tomorrow if that's cool

**Comment by zachcrystal** [comment]
@patchthecode I put up a sample app! https://github.com/zachcrystal/SampleCalendar
Looking forward to your response :)

**Comment by patchthecode** [comment]
i put a breakpoint here and printed the following logs -> 
<img width="1600" alt="screen shot 2018-07-09 at 10 16 57 am" src="https://user-images.githubusercontent.com/2439146/42465591-466693be-8361-11e8-8f31-8ba700a1a624.png">


```
The behavior of the UICollectionViewFlowLayout is not defined because:
the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.
The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x7fb104f025a0>, and it is attached to <UICollectionView: 0x7fb107816a00; frame = (8 131; 398 605); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600001199080>; layer = <CALayer: 0x600001fc14e0>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}> collection view layout: <UICollectionViewFlowLayout: 0x7fb104f025a0>.
```

Here is the main part
> The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: **0x7fb104f025a0>**, and it is attached to <UICollectionView: **0x7fb107816a00**

But you can see in the screenshot that JTAppleCalendar's instance = **0x7fb10581e200**
and its flowlayout instance = **0x7fb104e0dd60**

So the error you are seeing is not coming from this library or its flowlayout. It looks like that error is coming from your collectionVire and its flowlayout?

**Comment by patchthecode** [comment]
I think the error message tells you what is wrong? 

> the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.

Your collectionview's cell should be less. But it is more.
Try print statements in your code to help.
Will close this issue.
