### ISSUE TITLE
CollectionView shows up as empty

### ISSUE THREAD

**Issue by cluelessoodles** [patchthecode/JTAppleCalendar#824]
I tried to check if the common problems in the solved issues section were present before posting. I have the correct module, I have set label and container view constraints, I have set the ibCalendarDateSource/Delegate outlets, set the class of my storyboard scene = file class of CalendarViewController, but my collection is still showing up as empty

I'm hoping you can help me figure out why.

Here is my project zip 
[Gutka 2.zip](https://github.com/patchthecode/JTAppleCalendar/files/2171639/Gutka.2.zip)

**Comment by cluelessoodles** [comment]
hey patchthecode, is my post showing up? This is my first time posting in github issues and I'm worried I didn't post this right or its showing up as private.

**Comment by patchthecode** [comment]
ah sorry.
i mentally responded to you 😂
Will take a look after work. Sorry about that.

**Comment by patchthecode** [comment]
As soon as i ran your app, the firsst error message i sae on the console was
```
2018-07-09 19:29:45.297106-0700 Gutka[20617:9585642] Unknown class CalendarViewController in Interface Builder file.
```

**Comment by patchthecode** [comment]
closing this issue.

**Comment by cluelessoodles** [comment]
Thanks. I looked at the Build Phase - Compile sources and I see all of my .swift files including CalendarViewController.swift ... but that message still shows up... was that not the issue?

**Comment by patchthecode** [comment]
np. have a good one.
