### ISSUE TITLE
By week, by month

### ISSUE THREAD

**Issue by blinkmeoff** [patchthecode/JTAppleCalendar#825]
Do we have an option, to set calendar by week, by month?
We can scroll April to May and etc... without showing the dates and days, only monthes
Horizontal scroll

**Comment by patchthecode** [comment]
A screen shot can help me understand what you mean.

But if you want to put the calendar in week mode --> https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by patchthecode** [comment]
Assuming fixed. 
Please comment again and i'll re-open if its not
