### ISSUE TITLE
Single Row Calender Not Starting from Todays Date.

### ISSUE THREAD

**Issue by tripathishivam35** [patchthecode/JTAppleCalendar#827]
My Code is like as follows-
```
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let currentDate = Date()
        print(currentDate)
        let endDate = Calendar.current.date(byAdding: .month, value: 4, to: Date())
        print(endDate!)
        let parameters = ConfigurationParameters(startDate: currentDate,
                                                 endDate: endDate!,
                                                 numberOfRows: 1,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .off,
                                                 hasStrictBoundaries: false)
      //  calendar.scrollToDate(currentDate)
        calendar.scrollToDate(currentDate, triggerScrollToDateDelegate: false, animateScroll: false)

        return parameters
    }
```

I am setting Todays date as starting date but calender is starting from 1st of this month, like this-
![screen shot 2018-07-13 at 5 04 21 pm](https://user-images.githubusercontent.com/13601158/42689659-df3f2974-86be-11e8-9f66-d140619c3998.png)

If i use - calender.scrollTodate() , I can move to current date.
But I want to start the calender from Todays date only. Is it can be done without using scrollToDate()?

**Comment by patchthecode** [comment]
> If i use - calender.scrollTodate() , I can move to current date.
 But I want to start the calender from Todays date only. Is it can be done without using scrollToDate()?

I do not understand this.
If `scrollToDate` gives you what you want, then why not use it?

**Comment by tripathishivam35** [comment]
@patchthecode If i use scrollToDate() then user can scroll to left and able to see previous dates. Due to this I want to show/Start calender from todays date.

**Comment by patchthecode** [comment]
Currently this library always start from the start of the month.
The ability to start it off from any date has been requested from a number of developers and is on my bucket list. It just I have not had much time to work on it lately.

In the mean time, can setting up a boundary date work for you? -> https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by tripathishivam35** [comment]
I am Ok with using scrollToDate() as of now. 
Thanks for your response.
