### ISSUE TITLE
Number of rows support is only till 3. I want 5 rows for that I need to make change in pods. But this is getting overridden after pod update.

### ISSUE THREAD

**Issue by SmritiSYadav** [patchthecode/JTAppleCalendar#828]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
can you try master branch?
