### ISSUE TITLE
Is it possible to reverse/invert the vertical calendar?

### ISSUE THREAD

**Issue by HenriLangenhoven** [patchthecode/JTAppleCalendar#829]
Is it possible to reverse/invert the order of the months in the calendar so the most recent month is displayed at the top of the collection view, followed by the second-most recent?

so:
Jul
Jun
May
etc.

instead of:
May
Jun
Jul
etc.

**Comment by patchthecode** [comment]
something like [this](https://blog.kulman.sk/filling-uitableview-from-bottom-top/) ?

**Comment by HenriLangenhoven** [comment]
@patchthecode That seems super hacky. I was hoping there would be a way to just invert the order of the dates.

**Comment by patchthecode** [comment]
unfortunately this library, does not provide this out of the box.
Maybe if someone does a pull request, then i'll accept it.

**Comment by patchthecode** [comment]
Will close this issue as I have answered the question.
