### ISSUE TITLE
I have a problem when calendar view height = 0 at first.

### ISSUE THREAD

**Issue by oniikal3** [patchthecode/JTAppleCalendar#83]
I have implement calendar in to tableview cell. this cell will disappear at first (height = 0) but after I reload cell height to anything (e.g. 100) calendar view is expand like cell but cellView didn't expand. 
How can I fixed?

**Comment by patchthecode** [comment]
wow.. i never imagined anyone would put this into a tableview cell.
Can you just provide a zipped sample code of what you did?  You can place it in this chat box

**Comment by patchthecode** [comment]
I have heard no response for 2 days. I will assume your issue was resolved. If this is still a problem for you, it can be re-opened.

**Comment by oniikal3** [comment]
@patchthecode Sorry for late reply. I already fixed with add ratio in cellView. I don't know why. but It's work.
:D Thanks.

**Comment by patchthecode** [comment]
I am always looking to improve this library.
Is there any change you can paste the ratio code here so that i can get an idea of what yo accomplished and what was trying to be solved?

**Comment by fatehwaharp** [comment]
I've got the same issue, 
the calendar is inside UIView, under tableViewCell, when i pressed the fourth row from the static cell, the calendar cell which is row number three supposedly to display that will cover up the whole cell, but apparently it only displaying like the calendar uiview's is shrinking, even I've already constraint the ui view to 0 from top, leading, trailing, and bottom of the cell's container

this is the image when the calendar cell is displaying:
<img width="376" alt="screenshot 2016-09-28 23 58 40" src="https://cloud.githubusercontent.com/assets/306898/18921695/66b07398-85d8-11e6-9d92-8c8031e582ae.png">

**Comment by fatehwaharp** [comment]
Solve already, thanks anyway, apparently its the constraint, quite confusing,

**Comment by patchthecode** [comment]
hmm. So in the end was it something wrong with the calendar? or.. ?
