### ISSUE TITLE
The calendar switches back to future when scrolling to past

### ISSUE THREAD

**Issue by agordeev** [patchthecode/JTAppleCalendar#830]
Reproducible on example project when `numberOfRows` = 1. Here's video demostrating the issue: https://drive.google.com/open?id=1gkc-8yoHXQiTQVybh1yHO7bFL6aGj2Xw

How to reproduce:

1. Launch the example project.
2. Navigate to Calendar Layout demonstrations.
3. Switch to 1-row representation.
4. Scroll to today's date.
5. Start scrolling back. Notice after June 25 it shows you a week starting from July 2.

Any thoughts how to workaround this?

**Comment by patchthecode** [comment]
do you properly have your 1-row calendar setup like [this](https://github.com/patchthecode/JTAppleCalendar/issues/581)?

I think what you are seeing are out/indates

**Comment by patchthecode** [comment]
closing issue then if resolved.
cheers 🍻

**Comment by agordeev** [comment]
@patchthecode  Thanks, that helped! You're the best, as always
