### ISSUE TITLE
Selected cells not appearing properly after scrolling.

### ISSUE THREAD

**Issue by tripathishivam35** [patchthecode/JTAppleCalendar#831]
I am facing a issue which is illustrated from below provided screenshots:
Image 1: Single Cell is selected from CollectionView -
![img_7157](https://user-images.githubusercontent.com/13601158/42947557-31346372-8b8b-11e8-866b-57377c63d6d8.png)

Image 2: After scrolling few cells top to bottom and coming back again to Top. Selected Cell state is like this now without any further selections.
![img_7159](https://user-images.githubusercontent.com/13601158/42947705-89c8e4ae-8b8b-11e8-952d-1a81c88d190a.png)

*******************
Related Code with Cell Selection is like this below -

```swift
    func handleCellConfiguration(cell: JTAppleCell?, cellState: CellState) {
        handleCellSelection(view: cell, cellState: cellState)
    }

    // Function to handle the calendar selection

    func handleCellSelection(view: JTAppleCell?, cellState: CellState) {
        
        guard let myCustomCell = view as? CalenderCell else {return }
        
        if cellState.isSelected {
            myCustomCell.containerView.layer.cornerRadius =  10
            myCustomCell.containerView.backgroundColor = UIColor.init(red: 0.26, green: 0.10, blue: 0.39, alpha: 1.0)
        } else {
            myCustomCell.containerView.layer.cornerRadius =  0
            myCustomCell.containerView.backgroundColor = UIColor.clear
        }
    }
    
```

 ``` swift
   func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        
        let myCustomCell = cell as! CalenderCell
        sharedFunctionToConfigureCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
    }

    
    func sharedFunctionToConfigureCell(myCustomCell: CalenderCell, cellState: CellState, date: Date) {
        
        handleCellConfiguration(cell: myCustomCell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellConfiguration(cell: cell, cellState: cellState)
        
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellConfiguration(cell: cell, cellState: cellState)
}

```

Could u tell what wrong I am doing here. How to maintain the State of Selected Cells?

**Comment by patchthecode** [comment]
cell selection state is always maintained.
Is it possible you can just pull out the calendar code, create a sample project which replicates this?

I would be very surprised if this was a library bug, because of all the testing that has occurred in that potion of code.

**Comment by tripathishivam35** [comment]
Hi @patchthecode 

**I created a sample project** in which I integrated JTAppleCalender and with the same static flow of CollectionView inside UITableView. **I am able produce the same issue on this sample project.**

Issue U can reproduce is - Select any CalenderCell and scroll the tableView. In Few other Calender Cells at bottom Some Cells appears to be selected though user didn't selected them.

Below is the Sample Project link -
[https://www.dropbox.com/s/k5e6b7qj24b8x8v/Demo2.zip?dl=0](https://www.dropbox.com/s/k5e6b7qj24b8x8v/Demo2.zip?dl=0)

If u get some time, Kindly give a look at it. 
It might be I am missing something which needed to be added here pls let me know.

**Comment by patchthecode** [comment]
you are not configuring your cell in your `cellForItemAt` function.
Sine youre _are_ configuring your cells properly in your `willDisplayCell` function then you can use it to configure your cell.

re-write your `cellForItem` function to the following
```swift
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalenderCell", for: indexPath) as! CalenderCell
        cell.lblDate.text = cellState.text
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return cell
    }
```

**Comment by tripathishivam35** [comment]
Thanks for your Reply.
Your suggestion resolves the issue which is related with Horizontal scrolling Of calender. 

But one Issue is there too which is mentioned above related with Scrolling TableView-

Issue U can reproduce is - Select any CalenderCell and scroll the tableView. In Few other Calender Cells at bottom Some Cells appears to be selected though user didn't selected them.

Could u assist wrt this?

**Comment by patchthecode** [comment]
Thats because youre puttine `JTApplecalendarView` inside of a `UITableView` cell.

UItableview cells are being resused. Therefore, the calendar inside of the cell is being reused.
You'll have to reset the UITableview cell like you normally would with any other data.
