### ISSUE TITLE
When vertical scrolling and outdates set to endofGrid, section header is duplicated for every month

### ISSUE THREAD

**Issue by ThasneemH** [patchthecode/JTAppleCalendar#832]
Hi,

I am using the version 7.1.5 . When section headers are enabled in the following scenario, the headers are shown twice for  the same month starting from the second month onwards. 

1)  Vertical scrolling enabled
2) Indates : for All months
3) OutDates : till end of grid

Is this a  valid issue or is there any other configuration that needs to be done to get this to work correctly. 

Thanks for your help.

Code used : 
```swift
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from:"2018 01 01")!
        let endDate = formatter.date(from:"2018 12 31")!
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 5,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfGrid
                                          )
```
Here is the delegate method for header : 
```swift
   public func calendarSizeForMonths(_ calendar: JTAppleCalendarView?) -> MonthSize? {
        return MonthSize(defaultSize: 30.0)
    }
    
    public func calendar(_ calendar: JTAppleCalendarView, headerViewForDateRange range: (start: Date, end: Date), at indexPath: IndexPath) -> JTAppleCollectionReusableView {

        let date = range.start
        formatter.dateFormat = "MMMM"
    
        var header: JTAppleCollectionReusableView
        header = calendar.dequeueReusableJTAppleSupplementaryView(withReuseIdentifier: "header", for: indexPath)
       (header as! CalendarHeader).monthLabel.text =  formatter.string(from: date)
        return header
    }
```

![screen shot 2018-07-19 at 8 41 43 am](https://user-images.githubusercontent.com/13650795/42954059-9bab6af8-8b30-11e8-87a9-a0b87ff63651.png)
![screen shot 2018-07-19 at 8 41 33 am](https://user-images.githubusercontent.com/13650795/42954071-a2e87a68-8b30-11e8-9fde-062f70addf96.png)
![screen shot 2018-07-19 at 8 41 51 am](https://user-images.githubusercontent.com/13650795/42954075-a6ff1e40-8b30-11e8-9a0c-03aa6b900c5c.png)

**Comment by patchthecode** [comment]
Number of rows 4 and 5 and only supported on master branch because it is experimental.
The official released version only has 1, 2, 3, 6.

What you have just found is a bug on master branch.
However, do you really need 5 rows?

Because even if i do fix this, you will see this weird look occurring again if you have a calendar with 6 valid rows. What will happen is, it will set 5 rows to one header, and another single row to the same header. It will look exactly as you see it right now.

I do not think that you want five rows. You want 6 rows. But you want your outDates to be --> OutDates : till end of **Row**

**Comment by patchthecode** [comment]
let me know if this fixed your issue

**Comment by ThasneemH** [comment]
Thanks very much for your reply. This solution works for us. Closing the issue.
