### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by kreeos** [patchthecode/JTAppleCalendar#834]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

1. 7.1.5
2. Yes
3.Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

i am on the part where i am setting the inter item spacing and the border width to 0. i am a newbie to swift so i do not really know how to fix this error. i am following your video. Designing an IOS calendar.

**Comment by kreeos** [comment]
i am closing all the issues as I solve them. so if it is closed please disregard

**Comment by patchthecode** [comment]
understood.
