### ISSUE TITLE
50+ compiler errors since update to 7.1.5

### ISSUE THREAD

**Issue by boywithaxe** [patchthecode/JTAppleCalendar#835]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. - 7.1.5
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5 - Yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.version 7.1

Since updating from 7.1 this morning I've begun getting a big number of compiler errors.

The framework was working correctly until the update. The only ting changed in the build was adding Firebase Crashlytics.

<img width="337" alt="screenshot 2018-07-20 at 15 09 51" src="https://user-images.githubusercontent.com/19761391/43007135-5bf9a83e-8c2f-11e8-94ff-132ff816a0bb.png">

**Comment by patchthecode** [comment]
I do not think this is library related.
try doing a clean install?

Not sure about this

**Comment by boywithaxe** [comment]
I'll try that and get back to you. Thanks for the suggestions.

PS, love the library. It's a great piece of work!

**Comment by patchthecode** [comment]
thanks :)
Let em know if you encounter anything odd.

**Comment by boywithaxe** [comment]
A full reinstall of all the pods solved the problem. Apologies for raising a non-issue

**Comment by patchthecode** [comment]
its cool. glad it was resolved.
