### ISSUE TITLE
Avoid jumping of the calendar when resized

### ISSUE THREAD

**Issue by DoTooapp** [patchthecode/JTAppleCalendar#838]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER 7.1.5

Great calendar! love it!

How can I avoid the collectionview to scroll when I resize the collectionview?
See the screenshot's to see what I'm talking about.
<img width=350 src="https://user-images.githubusercontent.com/36662535/43133297-a2f64f14-8f3e-11e8-9fea-8c06d0607823.jpeg">

<img width=350 src="https://user-images.githubusercontent.com/36662535/43133298-a309ac62-8f3e-11e8-8f0a-abb1fb2e47e7.jpeg">

When I use the calendarView.scrollToDate() function to get back to the right position it solves the problem only partially as it goes down (triggered by the resize) before going up again.

Let me know if you have anything for this, thanks!

**Comment by patchthecode** [comment]
Have you looked at this example?
https://github.com/patchthecode/WLAppleCalendar

**Comment by patchthecode** [comment]
What that example does is simply _not_ resize the calendar view.
All you do is change the constraints to cover the calendar.
So when the user agenda expands, its top covers the calendar, giving the impression tha tthe calendar has shrunk.

**Comment by patchthecode** [comment]
closing issue.
Let me me know if thi shelped.
