### ISSUE TITLE
ScrollResistance property not working

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#84]
I want to configure to more scrolling. Now calendarview need to scroll 6 rows to show next month.
How can i change this?

**Comment by patchthecode** [comment]
Scroll resistance only works when `calendarView.paging = false`.

What value are you setting the scroll resistance at?

**Comment by mecid** [comment]
@patchthecode 
`            calendarView.pagingEnabled = false
            calendarView.scrollResistance = 0.2
`

No difference.

**Comment by patchthecode** [comment]
can you join me in chat again? -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Are you able to recreate this issue on the example project?
I am not able to reproduce this. Everything is working fine on my end.

**Comment by mecid** [comment]
@patchthecode sample is using horizontal scrolling. I am using vertical.

**Comment by patchthecode** [comment]
ok. can you explain what exactly is happening?

When you say it is not working, do you mean you are getting no scroll resistance at all?

**Comment by mecid** [comment]
@patchthecode testing example with vertical direction and no problem.

**Comment by mecid** [comment]
@patchthecode ohh, it is my fault.
I am reloadData() in didScrollToDateSegmentStartingWithdate delegate method.

**Comment by patchthecode** [comment]
cheers (y)
