### ISSUE TITLE
Just 1 weekdata

### ISSUE THREAD

**Issue by StackHelp** [patchthecode/JTAppleCalendar#842]
The version is  7.1.5

I want just 1-week data to show with 1 raw and therefore I tried this code with start date `2018-07-28 18:30:00 +0000` and end date is `2018-08-03 18:30:00 +0000`

        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 1,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfRow,
                                                 hasStrictBoundaries: true)

But it doesn't work for me and gives data from 6th month of 2018. So how to show just 1 week of dates every week?

**Comment by patchthecode** [comment]
Does this help?
https://github.com/patchthecode/JTAppleCalendar/issues/581

**Comment by StackHelp** [comment]
@patchthecode thanks for quick reply and I do try that but the issue is when I try to use start date as `018-07-28 18:30:00 +0000` means this week's first date to next all months but calendar starts from `June` that is the `6th month ` and one more issue is when month change, I got same dates for 2 scrolls. Please check link

https://www.dropbox.com/s/vli8zovaoq9pcwe/jtcalender%20issue.mov?dl=0

and here is code for configuration

                 let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 1,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfRow,
                                                 firstDayOfWeek: .monday,
                                                 hasStrictBoundaries: false)

**Comment by patchthecode** [comment]
yes this is a limitation of this lib. As i have not coded partial dates yet.
It always start from the start of a month, and ends at the end of the month.

In the mean time you can setup some date boundary that the user cannot cross.
as shown here -> https://github.com/patchthecode/JTAppleCalendar/issues/365

**Comment by StackHelp** [comment]
@patchthecode ok but in that video, I sent you in above comment has another problem that got same dates when month changes mean 2 weeks is been same when month changes check last 5-10 seconds video.

**Comment by patchthecode** [comment]
I do not understand your last post. Can you please rephrase?

Also
Did you change your code to this?
```swift
ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 1,
                                                 generateInDates: .forFirstMonthOnly,
                                                 generateOutDates: .off,
                                                 hasStrictBoundaries: false)
```

**Comment by StackHelp** [comment]
`        let parameters = ConfigurationParameters(
            startDate: startDate,
            endDate: Date().addMonth(1),
            numberOfRows: 1,
            generateInDates: .forAllMonths,
            generateOutDates: .tillEndOfRow,
            firstDayOfWeek: .monday,
            hasStrictBoundaries: false)
`

Yes, I tried now check this video, In this [video](https://www.dropbox.com/s/whanaxbfev5gord/jtissue.mov?dl=0) week data start from Monday and that's ok but end with Tuesday because of month end but I want next months 1st and 2nd date to be filled there.

Now, I changed a property `generateOutDates: .off` with `generateOutDates: .tillEndOfRow` to display week data from Monday to Sunday and it works but now the issue is that I got same cells for 2 weeks when month changes like it show in this [video](https://www.dropbox.com/s/hypliqddbrdyohi/jtcalender%20issue.mov?dl=0)

**Comment by patchthecode** [comment]
```
ConfigurationParameters(
   startDate: startDate,
   endDate: endDate,
   numberOfRows: 1,
   generateInDates: .forFirstMonthOnly,  // <<<--- You Missed this ?
   generateOutDates: .off,
   hasStrictBoundaries: false)
```

**Comment by StackHelp** [comment]
I need data for all the months from a current month without recurring issue that I mention in my previous comment

**Comment by StackHelp** [comment]
@patchthecode hope you understand the issue

**Comment by patchthecode** [comment]
i do not understand. Can you join me here?

https://gitter.im/patchthecode/JTAppleCalendar

**Comment by StackHelp** [comment]
yes

**Comment by StackHelp** [comment]
@patchthecode hope you understand the issue

**Comment by patchthecode** [comment]
Is this still an issue?
closing this until user responds.

**Comment by StackHelp** [comment]
Hii

**Comment by patchthecode** [comment]
Is this still an issue?

**Comment by patchthecode** [comment]
issue resolved via chat.
wrong parameter problem.
