### ISSUE TITLE
Stop a horizontal scrolling calendar at todays date

### ISSUE THREAD

**Issue by gerryau** [patchthecode/JTAppleCalendar#846]
Currently using latest version of JTAppleCalendar.

I would like my calendar view have its startDate as 30 days ago and it's endDate as the users current date. Upon trying to implement this the calendar keeps including up to the end of the current month instead of stopping after todaysDate.

<img width="734" alt="issuejtapple" src="https://user-images.githubusercontent.com/29995627/43637854-d0cd3a10-9759-11e8-853c-16c17c32f1e8.png">

![jtappgi](https://user-images.githubusercontent.com/29995627/43637954-5002d7f4-975a-11e8-8b06-260abd2003c5.gif)

**Comment by patchthecode** [comment]
Yes. I have not done that update yet. It create dates till the start of the month. and then keep going till the end of the month.

In the mean time i guess you can do a date boundary. So that once it crosses the todayDate boundary, it will scroll back to the todayDate.
https://github.com/patchthecode/JTAppleCalendar/issues/365

Let me know if that helped

**Comment by gerryau** [comment]
I got the following error:
<img width="997" alt="error" src="https://user-images.githubusercontent.com/29995627/43676734-45c46588-983a-11e8-9ea9-29c0f71535b3.png">

**Comment by patchthecode** [comment]
that link was an older example. with earlier swift. i have now update the code on that example link.
Pasting it here as well for reference

```swift
func scrollDidEndDecelerating(for calendar: JTAppleCalendarView) {
        let visibleDates = calendarView.visibleDates()
        let dateWeShouldNotCross = formatter.date(from: "2017 08 07")!
        let dateToScrollBackTo = formatter.date(from: "2017 07 03")!
        if visibleDates.monthDates.contains (where: {$0.date >= dateWeShouldNotCross}) {
            calendarView.scrollToDate(dateToScrollBackTo)
            return
        }
    }
```

**Comment by gerryau** [comment]
Great that solved it.

Also, when I select a cell with a date and print the date it shows the correct selected date, when I store it and try to use it in fetch requests it is using a day before the date selected. See screenshots below:

![bug](https://user-images.githubusercontent.com/29995627/43706459-b9f600f0-99a8-11e8-8bfd-137cb6f33d7c.png)
![bugconsole](https://user-images.githubusercontent.com/29995627/43706462-be21592c-99a8-11e8-8527-a0e4c57a88cb.png)

**Comment by patchthecode** [comment]
will close this issue since your original issue was resolved.

In relation to that second problem this has been asked 1000s of times :)
So i'll point you to the post with the explanation -> https://github.com/patchthecode/JTAppleCalendar/issues/252

let me know if it helped.
