### ISSUE TITLE
Getting header issue when I never implemented one 

### ISSUE THREAD

**Issue by seongminchoob** [patchthecode/JTAppleCalendar#847]
I'm using JTAppleCalendar 7.1.5 

 I am getting  assert(false, "You have implemted a header size function, but forgot to implement the `headerViewForDateRange` function")

but I never implemented a header size function

**Comment by patchthecode** [comment]
probably bad error message, will have to revise it.
But have you registered a header?

**Comment by seongminchoob** [comment]
I have not registered a header

**Comment by patchthecode** [comment]
can you zip a sample project with the issue and drop the zip file in this chat box?
