### ISSUE TITLE
I want to use different color for different dates selected in view didload??  I used the latest version 

### ISSUE THREAD

**Issue by asmaabadreldin2** [patchthecode/JTAppleCalendar#848]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
This library is a UICollectionView (similar to a UITableView)
The same way you would have different colors for a collectionViewCells or tableViewCells, is the exact same way you would do it for this library.

**Comment by patchthecode** [comment]
closing issue.
If you still need help then let me know.
