### ISSUE TITLE
WillDisplay doesn't get called?

### ISSUE THREAD

**Issue by pandaApe** [patchthecode/JTAppleCalendar#849]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
v7.1.5
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
YES
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I run the sample project you attached at [issue 667](https://github.com/patchthecode/JTAppleCalendar/issues/667)

And I download the  sample project from the repo, it has same issue.
Any idea why?

**Comment by patchthecode** [comment]
For you to say that it is not getting called, you must have some expectation of when it gets called.
When do you expect it to be called?

**Comment by pandaApe** [comment]
I just want my calendar to scroll smoothly, since I need do some time-consuming jobs for the date before it calls **cellForItemAt**.

**Comment by patchthecode** [comment]
I understand the concern you have.
But i do not understand what you are trying to do in the code to fix your concern, and how is your fix not working.

**Comment by obianachebe** [comment]
I think what might be @pandaApe's issue is that when scrolling horizontally between calendar frames, cellForItemAt is not called for the very next cell coming into the view. My guess is this has something to do with tableView pre-fetching? 

In the screenshot below, I am scrolling from one week to the next and the 13th is the next date to appear in the view frame, however, cellForItemAt is not called for that cell and is instead called for a cell two indexPath's later. As a result, my configureCell function is not called to update the incoming cell's backgroundView for the appropriate selectedPosition

![simulator screen shot - iphone 8 - 2018-08-07 at 21 24 55](https://user-images.githubusercontent.com/13955058/43816226-796090ec-9a88-11e8-9770-9039579e9e69.png)


See my JTAppleCalendarViewDelegate implementation code below:

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as? CalendarDayCell
        cell?.configureCell(for: cellState, date: date)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableCell(ofType: CalendarDayCell.self, for: indexPath)!
        cell.configureCell(for: cellState, date: date)

        return cell
    }


    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        let cell = cell as? CalendarDayCell
        cell?.configureCell(for: cellState, date: date)
    }

    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        let cell = cell as? CalendarDayCell
        cell?.configureCell(for: cellState, date: date)
    }

**Comment by patchthecode** [comment]
@obianachebe 
I am not sure how your calendar is not updating because i do not have your code.
Therefore i just added an example code you can follow to do range selection.
Download the github project and run the sample calendar attached to it. You'll see rangel selection as the 4th option. Let me know how it works.

**Comment by obianachebe** [comment]
@patchthecode I think my issue was actually because I'm using a calendar embedded in a UITableViewCell. For my use case, calling tableView.reloadData() updated the selection style correctly. Thanks for all the help and great work on this library!

**Comment by patchthecode** [comment]
Awesome. Glad it works. Closing this issue now.
