### ISSUE TITLE
What to do if I want to select an initial date?

### ISSUE THREAD

**Issue by StackHelp** [patchthecode/JTAppleCalendar#851]
Latest version is currently 7.1.5

I do have horizontal calendar view and I want to select today's date as initial cell selection. So any property for that?

**Comment by patchthecode** [comment]
inside view did load.
```swift
calendarView.selectDates([date1, date2, ....])
```

**Comment by StackHelp** [comment]
ohhh easy and how to scroll to next page when paging is enabled with `stopAtEachCalendarFrame` and how do we know there are any cells available next or is empty?

**Comment by patchthecode** [comment]
```swift
calendarView.scrollToSegment(.next)
calendarView.scrollToSegment(.previous)
```

**Comment by StackHelp** [comment]
Thanks
