### ISSUE TITLE
Divide by zero error in InternalQueryFuctions

### ISSUE THREAD

**Issue by dreneral** [patchthecode/JTAppleCalendar#852]
7.1.5

We are having issues when reloading with dates where it crashes due to a division by zero error.
On a time budget here so can't go into detail, but basically it appears that trying to reload today, Aug 9th, via `reloadDates`, causes a crash in line 179 of `InternalQueryFuctions` :

```
let extraSection = itemIndex / collectionView(self, numberOfItemsInSection: section)
```
`collectionView(self, numberOfItemsInSection: section)` gets passed a section of 119, which then returns zero.  A simple check here to see if the number of items in section == 0 fixes this crash.

```
let itemsInSection = collectionView(self, numberOfItemsInSection: section)
let extraSection = itemsInSection > 0 ? itemIndex / itemsInSection : 0
let extraIndex = itemsInSection > 0 ? itemIndex % collectionView(self, numberOfItemsInSection: section) : 0
```

**Comment by patchthecode** [comment]
Ok. this issue is already resolved in master branch code.
The fix i have implemented is
```swift
let numberOfItemsInSection = collectionView(self, numberOfItemsInSection: section)
guard numberOfItemsInSection > 0 else {
   assert(false, "Number of sections in calendar = 0. Possible fixes (1) is your calendar visible size 0,0? (2) is your calendar already loaded/visible?")
   return nil
}
```
This will crash in development, for work correctly in production.
I made it assert there so that developer will have a chance to fix, but i have no released it yet because I am not 100% sure if the reason i gave in the assert message is correct.

**Comment by dreneral** [comment]
1. The frame of the calendar is (0, 40, 375, 507)
2. It looks like it isn't.  The code gets called after the parent VC has completed viewDidLoad but before viewWillAppear. Making sure the call happens after viewWillAppear fixes the issue

**Comment by patchthecode** [comment]
Ok cool. So is the fix done on the master branch good then?
I'll close this issue if this is the case.

**Comment by dreneral** [comment]
Yeah, looks good.  Thx!
