### ISSUE TITLE
adjusting calendar height when changing to single row

### ISSUE THREAD

**Issue by seongminchoob** [patchthecode/JTAppleCalendar#854]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. v7.15
2. Are you using the latest version of JTAppleCalendar? yes

before I elaborate on my issue, thank you for such a great code

so these are the functions I use to adjust the height of the calendar

```swift
//change to single row
    @objc func swipeUpTriggered(gesture: UISwipeGestureRecognizer) {
        singleRow = true
//it seems weird but setting constant here was the only option to make it work
        calendarViewConstraint.constant = -225
        calendarView.reloadData()
        self.calendarView.scrollToDate(self.currentDate, animateScroll: false)
    }

//change to multi-row

     @objc func swipeDownTriggered(gesture: UISwipeGestureRecognizer) {
         singleRow = false
         calendarView.reloadData()
         self.calendarView.scrollToDate(self.currentDate, animateScroll: false)
     }
    
//scrollToDate triggers adjustCalendarViewHeight.

     func adjustCalendarViewHeight() {
         if singleRow {
            //I need to change both height and constraint to make it single-row
             calendarView.height = 75
             calendarView.selectDates([self.currentDate])
         } else {
             calendarView.height = 300
             calendarViewConstraint.constant = self.numOfRowIsSix ? 0 : -54
             calendarView.selectDates([self.currentDate])
         }
         UIView.animate(withDuration: 0.1) { [unowned self] in
             self.view.layoutIfNeeded()
         }
     }
```

and this is what I have for calendarConfiguration
```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        guard let startDate = formatter.date(from: "2018 01 01") else {fatalError("Start date was not initialized")}
        guard let endDate = formatter.date(from: "2018 12 31") else {fatalError("End date was not initialized")}
        
        if singleRow {
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 1, generateOutDates: .off, hasStrictBoundaries: true)
        } else {
            return ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: 6, generateOutDates: .tillEndOfGrid, hasStrictBoundaries: true)
        }
    }
```
and my scroll method
```swift
    //scroll

    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        
        adjustCalendarViewHeight()
        setupViewOfController(with: visibleDates)
    }
```

so this makes it to become single-row, but there are problems that I do not know how to solve.

so on the first run, this is the screen when I scroll up. 

<img width="351" alt="screen shot 2018-08-14 at 12 51 39 pm" src="https://user-images.githubusercontent.com/35505959/44071094-228edf8c-9fc2-11e8-83ca-9c4ded447d72.png">

Then, when I scroll to the right or left, 

<img width="359" alt="screen shot 2018-08-14 at 12 51 48 pm" src="https://user-images.githubusercontent.com/35505959/44071095-22d8b512-9fc2-11e8-8947-0751d026a00d.png">

the height of the calendarView gets reset like this. 

However, if I scroll down and scroll up again, everything works properly

Furthermore, selection of dates give me an issue too. In my didSelectDate function, I do not change anything about the height of calendar. However, when I select a different date, the height also gets reset. 

Lastly, when I'm moving onto another month, the height also gets reset.
As shown in the images below, when I swipe right to september from august, the height changes again.

<img width="345" alt="screen shot 2018-08-14 at 12 51 58 pm" src="https://user-images.githubusercontent.com/35505959/44071096-2312bb04-9fc2-11e8-91a7-556661938701.png">
<img width="337" alt="screen shot 2018-08-14 at 12 52 02 pm" src="https://user-images.githubusercontent.com/35505959/44071097-2368d7fa-9fc2-11e8-9a3d-9390afb601a1.png">

If you know any possible reason for this issue, please let me know.

Again, thank you so much

**Comment by patchthecode** [comment]
What do you mean by the height gets reset?
Every time you said that the height was reset, i am still seeing a calendarView with the same height. Did the height increase/decrease? 

Also, do you have a vertical/horizontal calendar? You mentioned scrolling up/down and also left/right. Confused on this.

Also, can you try master branch to see if the behavior is the same?
-->  [instructions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions)

**Comment by seongminchoob** [comment]
after the master branch nothing actually works anymore... I'm using a horizontal calendar. i'm trying to make it so that if I swipe up it becomes a single row and if I swipe down it becomes a multi row calendar. If there's any way to implement this please help. Changing the constraint or the height of the calendar does not work

**Comment by patchthecode** [comment]
ok two things.

1. Can you leave the calendar height to be fixed? But instead adjust the height of the separator constraint. This guy has done an example of something you are looking for -> https://github.com/patchthecode/WLAppleCalendar

2. If things are breaking on master branch, then continue using 7.1.5 (since master branch is still in development). However, when you say nothing working.. i wish if you can be more specific. Im pretty sure that not absolutely nothing works :).
If possible, can you provide a sample app with what you have( with your company private code removed)? There are so many requests that it is impossible to investigate them all from scratch.

**Comment by seongminchoob** [comment]
sorry for the late response. so this is what happens when I only change the height of the calendar

<img width="304" alt="screen shot 2018-08-21 at 1 02 23 am" src="https://user-images.githubusercontent.com/35505959/44375283-b430ab80-a52d-11e8-9338-ab7146afb61d.png">


and this is what happens when I change the constraint of a seperator view and the height

<img width="1440" alt="screen shot 2018-08-21 at 10 28 30 am" src="https://user-images.githubusercontent.com/35505959/44375414-8dbf4000-a52e-11e8-8bab-3e04606f8c8a.png">


the problem about only changing the constraint is that when I chagne the calendar to single view, the row goes in the middle so I need to also change the height to set the row to be on top.

**Comment by seongminchoob** [comment]
things are really buggy especially when changing from singlerow to multirow and vise versa. 

this is the code I have for switching

    @objc func swipeUpTriggered(gesture: UISwipeGestureRecognizer) {
        singleRow = true
        calendarView.height = 75
        calendarViewConstraint.constant = 119
        calendarView.reloadData()

        calendarView.selectDates([self.currentDate])
        self.calendarView.scrollToDate(self.currentDate, animateScroll: false)
    }
    
    @objc func swipeDownTriggered(gesture: UISwipeGestureRecognizer) {
        singleRow = false
        calendarView.reloadData()
        print(numOfRowIsSix)
        calendarViewConstraint.constant = numOfRowIsSix ? 344 : 299
        calendarView.selectDates([self.currentDate])
        self.calendarView.scrollToDate(self.currentDate, animateScroll: false)
    }


and this is my singlerow variable, I print the visible dates here

    var numOfRowIsSix: Bool {
        get {
            print(calendarView.visibleDates())
            return calendarView.visibleDates().outdates.count < 7
        }
    }


and this is what I get when I swipe down

DateSegmentInfo(indates: [], monthDates: [], outdates: [])
true

so when changing from single row to multi-row, visibledate does not work properly. 
when I scroll down again, then calendarview.visibledates give me back the proper dates

**Comment by seongminchoob** [comment]
I figured out how to do this. The constraint should not be changed. So what I did was I set the height of the calndarview as a constraint variable in my viewController, and changed the height.

**Comment by seongminchoob** [comment]
setting the height as a proportion of
