### ISSUE TITLE
Unconstrained Scroll

### ISSUE THREAD

**Issue by viniciusromani** [patchthecode/JTAppleCalendar#856]
Hello all,

I am currently using version 7.1.5 of JTAppleCalendar and I am having some troubles with scrolling the calendar through months. I know it is a CollectionView behind the scenes so, my calendar is kinda of scrolling as a normal CollectionView and, not going from month to month as I scroll it. Does anyone know how to fix it ?

I've made a gif to show what I am explaining... I think the gif is not that good but I think it shows what is going on and where I want to go

![out](https://user-images.githubusercontent.com/5360777/44286436-7a1a8d80-a23f-11e8-9eb2-a36eb7149c52.gif)

I would like to constraint the scroll to go through months only..

**Comment by patchthecode** [comment]
https://patchthecode.github.io/CalendarScrolling/

closing issue.
let me know if it helped.

**Comment by viniciusromani** [comment]
@patchthecode 

Thanks for the quick and effective response :) It worked like a charm
