### ISSUE TITLE
Bug with multiple selection of the 31st of current month and the next week of the next month

### ISSUE THREAD

**Issue by NadzeyaStsepanchuk** [patchthecode/JTAppleCalendar#857]
Version 7.1.5. **iOS 10 ONLY**

![bug](https://user-images.githubusercontent.com/36277100/44303039-11b2d580-a33f-11e8-896a-225ebfe355a3.gif)

Steps to reproduce:
1. Select 31st of August
2. Select 8th of September
3. Select next month
4. Unselect 31st of August
5. Go back to previous month
-> None of 31st, 1st, 7th, and 8th cell are selectable
-> no delegates are getting called

I am using next settings:
```
        self.calendarView.allowsMultipleSelection = true
        self.calendarView.isRangeSelectionUsed = true
```

Temporary I've solved it by using next code when I go back to the previous month:

```
        self.calendarView.scrollToSegment(.previous, triggerScrollToDateDelegate: false, animateScroll: true, extraAddedOffset: 0.0, completionHandler: {
            self.calendarView.reloadData()
        })
```

Whole code is here: https://github.com/NadzeyaStsepanchuk/JTAppleCalendarTestExample

**Comment by patchthecode** [comment]
checkign this out now

**Comment by patchthecode** [comment]
What did you mean by
> Temporary I've solved it by using next code when I go back to the previous month:

What is next code?

**Comment by patchthecode** [comment]
I am using iOS 11.4 and it is working correctly.
Based on the comment you used in your app ---> `//FIX for iOS 10:`

Are you saying you are only seeing this in iOS 10 ?

**Comment by patchthecode** [comment]
One thing i would say is this.
I notice you have implemented the `shouldSelect` function.

Are you saying that even the `shouldSelect` delegate is not getting called?

**Comment by NadzeyaStsepanchuk** [comment]
It's working fine on iOS 11, right. Bug is only reproducing on iOS 10.
Yep, `shouldSelect` is also not getting called.
You can test it using my code on git.

**Comment by patchthecode** [comment]
updated master branch.
Closing issue now.
