### ISSUE TITLE
User can select multiple dates, even when it's set to false? + Weird things happen 

### ISSUE THREAD

**Issue by duancaro** [patchthecode/JTAppleCalendar#86]
Hello!

I'm not sure if my code is the problem, but even when I explicitly set the allowsMultipleSelection boolean to false, the user can still select multiple dates:

![img_3447](https://cloud.githubusercontent.com/assets/12994365/16999380/8aae064a-4e72-11e6-8ac9-3d04f1399880.PNG)

And when I swipe to the next month, the selected dates seem to persist, but they appear at random places:

![img_3448](https://cloud.githubusercontent.com/assets/12994365/16999407/a2942104-4e72-11e6-818f-01cac8178eab.PNG)

Here's my relevant code.

in CalendarViewController
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
		self.calendarView.dataSource = self
		self.calendarView.delegate = self
		self.calendarView.allowsMultipleSelection = false
		self.calendarView.registerCellViewXib(fileName: "CellView")
    }

```

delegate method 
```swift
func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {
	(cell as? CellView)?.configureForSelected(cellState)
}
```

in CellView.swift
```swift
func configureForSelected(cellState: CellState) {
	if cellState.isSelected {
		self.answeredView.layer.cornerRadius =  self.answeredView.frame.width / 2
		self.answeredView.hidden = false
		self.dateLabel.textColor = UIColor.whiteColor()
	}
}
```

Thank you for any help!

**Comment by patchthecode** [comment]
The calendar is a made from a UIColelctionView.
Therefore date cells are reused.

I see where you are setting the selection, but I do not see where you are removing the selection if a cell is _not_ selected.

Did this help?

**Comment by patchthecode** [comment]
did you implement this function?

`func calendar(calendar: JTAppleCalendarView, didDeselectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {}`

**Comment by duancaro** [comment]
I'm kinda confused as to when that function is called. Does deselected mean that the user tapped on a selected cell? If so, I don't want the user to be able to deselect cells. If the user taps an already selected cell, nothing should happen. 

I'm sorry about my noobness :'(

**Comment by patchthecode** [comment]
its cool.

The following means that a cell was selected. 
```swift
func calendar(calendar: JTAppleCalendarView, didSelectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {}  
```

the following means that a cell was deSelected
```swift
func calendar(calendar: JTAppleCalendarView, didDeselectDate date: NSDate, cell: JTAppleDayCellView?, cellState: CellState) {
```

**Comment by patchthecode** [comment]
When you select cell-A. 
- It is selected.

When you select cell-B. 
- cell-A is deselected
- It is selected.

This is the behavior of `calendarView.allowsMultipleSelection = false`

**Comment by duancaro** [comment]
Thank you for your help!
