### ISSUE TITLE
scrollToDate Not working 

### ISSUE THREAD

**Issue by vadimkrutovlv** [patchthecode/JTAppleCalendar#860]
Hello, 

I'm using calendar version 7.1.5. 

I'm trying to scroll programmatically to needed date like that self.calendarView.scrollToDate(date).  

Basically I have function which receives date from object and then depending on value should scroll calendar, unfortunately nothing works for me.

```
private func scrollCalendarView(to date: Date) {
        self.calendarView.scrollToDate(date)
        self.updateHeader(date: date)
 }
```

Here is calendar configuration

```
        self.calendarView.calendarDelegate = self
        self.calendarView.calendarDataSource = self
        self.calendarView.isRangeSelectionUsed = true
        self.calendarView.allowsMultipleSelection = true
        self.calendarView.register(UINib(nibName: Constants.Xibs.calendarCell, bundle: nil),
                                   forCellWithReuseIdentifier: Constants.Xibs.calendarCell.lowerCaseFirst)
        self.calendarView.minimumInteritemSpacing = 0
        self.calendarView.minimumLineSpacing = 0
        self.calendarView.sectionInset = UIEdgeInsetsMake(0, -8, 0, 3)
        self.calendarView.scrollingMode = .stopAtEachSection
        self.calendarView.scrollDirection = .horizontal
```

Please let me know if you need more information.

**Comment by patchthecode** [comment]
scroll to date should work as expected.
if you are using cocoapods, can you use breakpoints to check to see if you are scrolling to an invalid date (a date outside of the calendar boundary) ?

**Comment by vadimkrutovlv** [comment]
Hey, thanks for quick response. I guess my mistake was to call this method in initializer of custom ui view subclass.

**Comment by patchthecode** [comment]
cool. closing this then.
