### ISSUE TITLE
calendarView.selectDates Return always a nil cell on didSelectDate

### ISSUE THREAD

**Issue by Tastouma** [patchthecode/JTAppleCalendar#861]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

Used Version 7.1.5 the last one

On selecting  Today date on using: calendarView.selectDates([Date()]) it always return a nil cell on didSelectDate function.

I tried to call the select/dates function in difference places ( viewDidLoad(), viewDidAppear(), viewWillAppear() .... )

**Comment by Tastouma** [comment]
this image show the error
![image](https://user-images.githubusercontent.com/22947144/44488007-11ac2180-a62e-11e8-8f4b-70cbd4a9aab2.png)

**Comment by patchthecode** [comment]
if you selected the cell, and the cell is not visible on the screen, it will be nil in that function.

**Comment by patchthecode** [comment]
closing this issue.
If this is still a problem for you, then let me know.
