### ISSUE TITLE
selecting a date and moving into the next month issue

### ISSUE THREAD

**Issue by seongminchoob** [patchthecode/JTAppleCalendar#865]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. 7.1.5
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5 yes 
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

<img width="334" alt="screen shot 2018-08-26 at 6 35 00 pm" src="https://user-images.githubusercontent.com/35505959/44626870-57832580-a95f-11e8-90f3-884c6baf4408.png">

so if I select a date from a previous month (this case August 26th) and swipe to the next month, if the date is an indate of the next month, the date stays selected as it is shown. 
it still stays when I select other dates in September.

**Comment by patchthecode** [comment]
did you implement the `willDisplayCell` function?

**Comment by seongminchoob** [comment]
Yes I did

**Comment by patchthecode** [comment]
can you join me here? https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
did you implement the `didDeselect` function?

**Comment by seongminchoob** [comment]
Yes I have. I will send you a recreation of this problem

**Comment by seongminchoob** [comment]
https://github.com/seongminchoob/recreationOfProblem 

select dates like 28 or 29 and slide to the left. You will see that the dates are remained selected

**Comment by patchthecode** [comment]
in your willDisplayCell function, why are you dequeuing again?
You do not do this with regular UICollectionView/UITableView. 
Therefore do not do it with this library.

```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! CustomCell
        cell.dateLabel.text = cellState.text
        handleCellSelected(cell: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        cell.dateLabel.text = cellState.text
        self.calendar(calendar, willDisplay: cell, forItemAt: date, cellState: cellState, indexPath: indexPath)
        return cell
    }
```
