### ISSUE TITLE
Programmatically selecting dates

### ISSUE THREAD

**Issue by ThasneemH** [patchthecode/JTAppleCalendar#868]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I am using the latest version.

I have a vertical scrolling calendar with outDates as .tillEndOfRow

In didScrollToDateSegment, I want to programmatically select the first date of the month when i scroll to it .  Also in shouldSelectDate delegate, I have the following check : 

     if (cellState.dateBelongsTo == .followingMonthOutsideBoundary) || (cellState.dateBelongsTo == .previousMonthOutsideBoundary) {
            return false
        } else { return true }

However, when I scroll to previous month, half way through the scroll, both the first date of this month and the same date ( which is also  the outDate of last month) appears selected briefly. Is there any other way to get around this issue ?

 thanks very much.

<img width="559" alt="screen shot 2018-08-27 at 5 11 15 am" src="https://user-images.githubusercontent.com/13650795/44659372-dfe1e480-a9b8-11e8-8217-a06f0062a5ee.png">

**Comment by patchthecode** [comment]
So what behavior do you want?
Do you want that:
1. user begins scrolling
2. selected date becomes unselected
3. user gets to desired month
4. new date on desired month becomes selected?

I need to know what behavior you want in order to know what to suggest.

**Comment by ThasneemH** [comment]
Thanks for your fast reply. Here is the behavior I want:

Every time we scroll to a new month, I want the 1st of that month to be selected.  I am able to do that by calling selectDates in willScrollToDateSegment.  But while scrolling , the same date is also shows up selected when its the out date of the previous month ( or the in date of the next month) . Hence the reason it shows up twice as in the pic. How do I not have this date selected when its an in or out date?  My code snippet above  trying to use shouldSelectDate does not have any effect.

**Comment by ThasneemH** [comment]
Here is a clearer explanation of the behavior wanted  as we discussed in the chat yesterday, could you let me know the solution for it .thanks. 

ok, therefore you do want outdates selected
you only want outdates selected when a user selects it
but you do NOT want outdates selected when youre programatically select the 1st of the month

**Comment by patchthecode** [comment]
You need to use your delegates to handle this.

the `didSelect` delegate tells you 
1. The cell that was selected
2. `cellState.dateBelongsTo` tell you If the cell is an inDate or monthDate
3. `cellState.selectionType` tells you if the selection was a user selection or a programatic selection

I think with these you will be able to handle how the selection is displayed

**Comment by patchthecode** [comment]
closing this issue.

**Comment by ThasneemH** [comment]
In shouldSelectDate: delegate , I added the following code . The behavior now is that , when I scroll for eg. from Jan  to  Feb   , the 1st date of Feb is not selected when it shows as  the out date of Jan . This is the expected behavior. But while scrolling backwards  ( Feb to Jan) , then 1st date of Feb shows up as selected in  the out dates of the previous month
![scrollbackfromfebtojan](https://user-images.githubusercontent.com/13650795/44998219-a8e77200-af68-11e8-8af6-28f5ede38144.png)


 if ((cellState.dateBelongsTo == .previousMonthOutsideBoundary) || (cellState.dateBelongsTo == .previousMonthWithinBoundary) || (cellState.dateBelongsTo == .followingMonthWithinBoundary) || (cellState.dateBelongsTo == .followingMonthOutsideBoundary)) && (cellState.selectionType == .programatic) {
            return false
        } else {
            return true
        }
But I read from this issue : https://github.com/patchthecode/JTAppleCalendar/issues/877
that programmatic selection always returns true .

I also added the code to do the check in didSelectDate: as well as you have suggested , but the cellState always returns as belonging to 'thisMonth'.  here as well, so get the same result. 

 Is it possible to differentiate it  based on indates or outdates in shouldSelectDate. My call to select the 1st date of every month programmatically is in willScrollToDateSegment:.  If I can  check in shouldSelectDate and not select it when its programmatic , it would be easy.

Else, appreciate if you could you please let me know if there is any other way to get around this issue Would be great if I can get this issue fixed as this makes the app visually not right while scrolling. 

Thanks very much. 

ScrollingFromJanToFeb-ExpectedBehavior ( outdate not selected) 
![scrollingfromjantofeb-expectedbehavior](https://user-images.githubusercontent.com/13650795/44998189-6f166b80-af68-11e8-968d-600ea108c254.png)
:

ScrollingFromFebToJan ( to previous month) out date is selected:

**Comment by patchthecode** [comment]
sorry for the very late reply.

You simply want the selection to go away while you scroll because you do not want to briefly see the old selection while you scroll to the new month.

I dont know why i didnt think of this before, but what you can do is:
in the `willScroll` delegate function, you can deselect the cell there.
Then when it gets to the next month, in your `didScrollToDate` function, you can then reselect.

this will temporarily get rid of the selection until you get to the next month.

**Comment by ThasneemH** [comment]
This sounds like it will work. However, in my case, since I have the issue below with the offset, I have seen the willScroll not giving me the correct visibledates due to the offset.
https://github.com/patchthecode/JTAppleCalendar/issues/850

I will try this out again though.

Thanks for your time.

**Comment by patchthecode** [comment]
Hey, i am not saying to put the `visibleDates` in the willScroll function.
In the willScroll function, simply call the `calendarView.deselectDates` function.
Which will deselect the dates.

This should get rid of the selection until you stop scrolling right?

**Comment by ThasneemH** [comment]
yes, I don't mean putting the visible dates  in willScroll. In my case , if you see I use an offset to hide the header( issue #850) , because of that difference in offset , i have seen that the visibledates parameter in willScroll delegate function returns incorrect set of values. Remember seeing  this a while ago, I would have to retest and confirm though.

**Comment by patchthecode** [comment]
ok will re-open this issue.
let me know how it goes.
setting the awaitingResponse flag on this issue
