### ISSUE TITLE
How to reload calendar while getting response from server

### ISSUE THREAD

**Issue by PramodShukla10** [patchthecode/JTAppleCalendar#869]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
you reload by doing
`calendarView.reloadData()`.

The other part of your question is not descriptive enough for me to understand what you mean.
Closing issue until further clarification.
