### ISSUE TITLE
Weekly calendar showing incorrect dates despite following #581

### ISSUE THREAD

**Issue by acwlaw** [patchthecode/JTAppleCalendar#870]
1. Version number: 7.1.5
2. Yes.

Hello,

I am attempting to create a calendar with the option to switch between monthly and weekly views and have it function as closely to the Apple Calendar as possible.

My monthly calendar works fine and is set up with the following parameters:
```
let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6 ,
                                                 calendar: Calendar.current,
                                                 generateInDates:  InDateCellGeneration.forAllMonths,
                                                 generateOutDates: OutDateCellGeneration.off,
                                                 firstDayOfWeek: DaysOfWeek.sunday,
                                                 hasStrictBoundaries: true)
```
Monthly calendar:
<img width="363" alt="screen shot 2018-08-28 at 10 35 26 am" src="https://user-images.githubusercontent.com/24707164/44740643-d6877380-aaaf-11e8-94ca-a7e0640429db.png">

My weekly calendar however does not function as intended in that there are gaps between weeks and on months with dates not starting on Sunday, they are still being defaulted to the Sunday position. 

<img width="358" alt="screen shot 2018-08-28 at 10 35 39 am" src="https://user-images.githubusercontent.com/24707164/44740578-a93ac580-aaaf-11e8-956c-2d9ef026058a.png">

<img width="359" alt="screen shot 2018-08-28 at 10 35 49 am" src="https://user-images.githubusercontent.com/24707164/44740586-ae981000-aaaf-11e8-99cc-e0e032986604.png">

The goal:
![img_0578 copy](https://user-images.githubusercontent.com/24707164/44740829-3ed65500-aab0-11e8-8aa3-6cf62efd92a0.png)

The weekly calendar is configured as:
```
let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 1 ,
                                                 calendar: Calendar.current,
                                                 generateInDates:  InDateCellGeneration.forFirstMonthOnly,
                                                 generateOutDates: OutDateCellGeneration.off,
                                                 firstDayOfWeek: DaysOfWeek.sunday,
                                                 hasStrictBoundaries: false)

```
I have tried following solutions posted on #581 , but it still does not function as intended.

Any ideas or suggestions of what may be going wrong? Thanks in advance!! 

As a side note, I am having the `numberOfRows`, `generateInDates`, `generateOutDates` and `hasStrictBoundaries` parameters as variables that are toggled every time dates are selected. I think that's the right way to do it? Correct me if I'm wrong.

**Comment by patchthecode** [comment]
> As a side note, I am having the numberOfRows, generateInDates, generateOutDates and hasStrictBoundaries parameters as variables that are toggled every time dates are selected. I think that's the right way to do it? Correct me if I'm wrong.

Thats how i would do it.

> My weekly calendar however does not function as intended in that there are gaps between weeks and on months with dates not starting on Sunday, they are still being defaulted to the Sunday position.

1. There are gaps between the weeks. 
   * are ou sure you have `hasStrictBoundaries` setu to false
   * are you sure you are reloading the calendar 

2. and on months with dates not starting on Sunday, they are still being defaulted to the Sunday position
   * i am unsure what you mean by this

**Comment by patchthecode** [comment]
if you want a faster response, check me out [here](https://gitter.im/patchthecode/JTAppleCalendar). Will be there for a couple hours.

**Comment by patchthecode** [comment]
closing issue.
reslolved.
