### ISSUE TITLE
How can we extend the event (colored dot) to extend?

### ISSUE THREAD

**Issue by cybersgk** [patchthecode/JTAppleCalendar#873]
Hey,
 Sorry for taking your time
How can we extend the event dot at the bottom to extend like a line to the next day if the events are multiple dated ones? And also it should not extend if the adjacent dates are different events. Refer:
<img width="89" alt="screen shot 2018-08-29 at 3 42 13 pm" src="https://user-images.githubusercontent.com/42802917/44781523-437b3600-aba2-11e8-9a6d-8fc0830ec72d.png">

I also have a question about selecting the multiple dates so that the selection is like below. 
<img width="117" alt="screen shot 2018-08-29 at 3 42 46 pm" src="https://user-images.githubusercontent.com/42802917/44781582-6dccf380-aba2-11e8-9c8a-cc95f81d9f3d.png">
The selection of multiple dates should be draggable. If they are selected one by one they should be circles.

**Comment by cybersgk** [comment]
Sorry i looked around and found your tutorial at:
https://patchthecode.github.io/RangeSelection/
So this took care of my 2nd problem.
There is a problem I am facing where there is a small gap in between tue&wed and thu&fri and sat&sun.
I am setting cell size to be 50. Because I can't find a property to set only the height of the cell.By:
        calendarView.cellSize = 50;
My week starts from Mon and ends in Sun
It would help if you point me in the right direction.
And the first question about event dots still stands.
Btw awesome library really helped me save time.

**Comment by patchthecode** [comment]
Spaces problem

<img width="650" alt="screen shot 2018-08-29 at 3 42 13 pm" src="https://user-images.githubusercontent.com/2439146/44797956-3be96c00-ab65-11e8-84c2-b1556520f26b.png">

**Comment by patchthecode** [comment]
> How can we extend the event dot at the bottom to extend like a line to the next day if the events are multiple dated ones?

This seems to be app specific code. How would not have a solution for this.

**Comment by patchthecode** [comment]
The white space problem is not a library problem. It is a UICollectionView problem.

**Comment by cybersgk** [comment]
Ohh, thank u for the reply. So that was what the spaces were. The event dot thing is hard, but thank u for the response. 
Back to brainstorming mode then...

**Comment by patchthecode** [comment]
for the dots, i use something similar to determine what a rangeSelection should look like.

It can look `left half circle`, `right half circle`, `circle`, or a `square (if it is in the middle)`. This is similar to what you need for your dot.

The code i use for it is 
```swift
        let selectedPosition = { [unowned self] () -> SelectionRangePosition in
            let selectedDates = self.selectedDatesSet
            if !selectedDates.contains(date) || selectedDates.isEmpty  { return .none }
            
            let dateBefore = self.cachedConfiguration.calendar.date(byAdding: .day, value: -1, to: date)!
            let dateAfter = self.cachedConfiguration.calendar.date(byAdding: .day, value: 1, to: date)!
            
            let dateBeforeIsSelected = selectedDates.contains(dateBefore)
            let dateAfterIsSelected = selectedDates.contains(dateAfter)
            
            var position: SelectionRangePosition
            
            if dateBeforeIsSelected, dateAfterIsSelected {
                position = .middle
            } else if !dateBeforeIsSelected, dateAfterIsSelected {
                position = .left
            } else if dateBeforeIsSelected, !dateAfterIsSelected {
                position = .right
            } else if !dateBeforeIsSelected, !dateAfterIsSelected  {
                position = .full
            } else {
                position = .none
            }
            return position
        }
```

But im not sure if this can be of help to you.
Have a good one.

**Comment by cybersgk** [comment]
OMG. Thank you. Sorry for the late response. I had to work on another project, so I didn't look here for some days. I am very sorry. You helped me a lot. By the way, your calendar is awesome to work on. I will definitely put this to good use.
