### ISSUE TITLE
How to check if the calendar is showing a week / full calendar?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#875]
1. I am using the latest branch.
2. pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

Is there any inbuilt property to find this? Right now, the only possible way is to cross-verify with the calendar height.

**Comment by patchthecode** [comment]
Since you are the one changing the calendar from weekview to full view, then you can know this.
Because when you change the view, you change the number of row to either 1, or 6. So you do not have to use the height to determine this.

**Comment by patchthecode** [comment]
closing this issue as i have done an update here -> https://github.com/patchthecode/JTAppleCalendar/issues/880
