### ISSUE TITLE
selectDates with dateBelongsTo always returns true

### ISSUE THREAD

**Issue by bbo-jay** [patchthecode/JTAppleCalendar#877]
Version: 7.1.5

I have this code to print the date and a check if the date I selected belongs to current month display. 

    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        print("\(date) : \(cellState.dateBelongsTo == .thisMonth)")
    }

And it prints:
2018-01-27 16:00:00 +0000 : true
2018-01-28 16:00:00 +0000 : true
2018-02-01 16:00:00 +0000 : false
2018-02-02 16:00:00 +0000 : false

But, with this code: (Note: I'm in the January calendar)

     func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        if cellState.selectionType == .programatic {
            print("\(date) : \(cellState.dateBelongsTo == .thisMonth)")
        } else {
            self.calendarView.deselectAllDates(triggerSelectionDelegate: true)
            self.calendarView.selectDates(from: formatter.date(from: "2018 01 28")!, to: formatter.date(from: "2018 02 03")!, triggerSelectionDelegate: true, keepSelectionIfMultiSelectionAllowed: false)
        }
    }

It prints:
2018-01-27 16:00:00 +0000 : true
2018-01-28 16:00:00 +0000 : true
2018-01-29 16:00:00 +0000 : true
2018-01-30 16:00:00 +0000 : true
2018-01-31 16:00:00 +0000 : true
2018-02-01 16:00:00 +0000 : true
2018-02-02 16:00:00 +0000 : true

**Comment by kukurokie** [comment]
What i want to do is to select a row of dates and then check if those dates are in the current month displayed.

**Comment by patchthecode** [comment]
ok. i see.
Well, Programmatic selection always selects the true date (not inDates or outDates like manual selection). So there is no need to check.
