### ISSUE TITLE
Connecting a tableview with dates/holidays

### ISSUE THREAD

**Issue by cluelessoodles** [patchthecode/JTAppleCalendar#878]
1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5 
Yes

I'm practicing with a simple calendar where you select the date in the calendar collectionview and it finds the matching holiday and prints it in the tableview. I've managed to parse the XML file (saved in Bundle) and have also gotten it to print into my tableview as a test. However, I actually need to first select a date in the calendar collectionview and then print its date and holiday from the xml Can you guide me as to how to do this?  

I think I need a method that finds the events in the xml and matches them to selected date in calendar collectionview, (but I don't know how to write this part), and then I need to send that to the tableview and reload tableview. 

I watched your "JTAppleCalendar Common Questions #1 #Warning in description" video where you get events from server. When I tried to get events from my local calendar.xml file in func getEvents () I get an error that says can't convert Character to date but you dont seem to have that problem in the video. The dates in the xml are saved YYYY-MM-DD but they dont convert seem to convert with formatter.dateFormat = "dd MM yyyy". This is the part I need a little help with - getting my dates from the xml to == to the date selected and I can't seem to replicate what you did in the video. 

[I uploaded the full project here as well](https://github.com/cluelessoodles/CalendarTest)

Also copy pasted the code:

    import UIKit
    import JTAppleCalendar

    class CalendarViewController: UIViewController, XMLParserDelegate {
    
    @IBOutlet weak var calendarView: JTAppleCalendarView!
    @IBOutlet weak var year: UILabel!
    @IBOutlet weak var month: UILabel!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var separatorViewTopConstraint: NSLayoutConstraint!
    let outsideMonthColor = UIColor.cyan
    let monthColor = UIColor.white
    let selectedMonthColor = UIColor.darkGray
    let currentDateSelectedViewColor = #colorLiteral(red: 0.3647058904, green: 0.06666667014, blue: 0.9686274529, alpha: 1)
    let todaysDefaultDateColor  = #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1)
    let formatter = DateFormatter()
    let todaysDate = Date()
    let numOfRowsInCalendar = 6
    
    var tableViewDataSource = [CalendarDates]()
    var myCalendarDates = CalendarDates()
    var selectedDate: Date!
    var eventDate: Date!
    var myEventDate = String()
    var calendarevent = ""
    var monthTableview = ""
    var dateTableview = ""
    var datenumberTableview = ""
    var holidayTableview = ""
    var descriptionTableview = ""
    
    var numOfRowIsSix: Bool {
        get {
            return calendarView.visibleDates().outdates.count < 7
        }
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupCalendarViewAtStart()
        setUpTableViewAtStart()
        setUpBackgroundView()
        getEventDates()
        
        self.navigationController?.navigationBar.isTranslucent = true
    }
    
    //Mark: Calendar viewdidloadsetup
    func setupCalendarViewAtStart(){
        //Scroll to today's date at start
        calendarView.scrollToDate(todaysDate, animateScroll:false)
        calendarView.selectDates([todaysDate])
        //Setup calendar spacing
        calendarView.minimumLineSpacing = 0
        calendarView.minimumInteritemSpacing = 0
        //Setup labels
        self.calendarView.visibleDates { visibleDates in
            self.setupViewsOfCalendar(from: visibleDates)
        }
        self.adjustCalendarViewHeight()
    }

    //Mark: Calendar set cell selection colors, today's Date selection color
    func handleCellTextColor(view: JTAppleCell?, cellState: CellState) {
        guard let validCell = view as? CalendarCell else { return }
        if cellState.isSelected {
            validCell.dateLabel.textColor = currentDateSelectedViewColor
        } else {
            if cellState.dateBelongsTo == .thisMonth {
                validCell.dateLabel.textColor = monthColor
            } else {
                validCell.dateLabel.textColor = outsideMonthColor
            }
        
        validCell.isHidden = cellState.dateBelongsTo == .thisMonth ? false : true
        }
        //select today's date
        formatter.dateFormat = "yyyy MM dd"
        let todaysDateString = formatter.string(from: todaysDate)
        let monthDateString = formatter.string(from: cellState.date)
        if todaysDateString == monthDateString {
            validCell.dateLabel.textColor = todaysDefaultDateColor
            validCell.dateLabel.font = UIFont.systemFont(ofSize: 30.0)
        } else {
            validCell.dateLabel.textColor = monthColor
            validCell.dateLabel.font = UIFont.systemFont(ofSize: 18.0)
        }
    }
    
    //Mark: Calendar cell selection
    func handleCellSelected(view: JTAppleCell?, cellState: CellState) {
        guard let validCell = view as? CalendarCell else { return }
        if validCell.isSelected {
            validCell.selectedView.isHidden = false
        } else {
            validCell.selectedView.isHidden = true
        }
    }
    
    //Mark: Calendar cell month & year text
    func setupViewsOfCalendar(from visibleDates: DateSegmentInfo) {
        let date = visibleDates.monthDates.first!.date
        self.formatter.dateFormat = "yyyy"
        self.year.text = self.formatter.string(from: date)
        self.formatter.dateFormat = "MMMM"
        self.month.text = self.formatter.string(from: date)
    }
    
    //Mark: set events from XML == selected cell from Calendar
    /*func getEventDates() {
        let datesOfEvents = myCalendarDates.date
        print (datesOfEvents)
    }*/
    
    //Mark: TableView viewDidLoad
    func setUpTableViewAtStart() {
        tableView.dataSource = self
        tableView.delegate = self
        self.tableView.bounces = true
        if let path = Bundle.main.url(forResource: "calendar", withExtension: "xml")
        {
            if let parser = XMLParser(contentsOf: path) {
                parser.delegate = self
                parser.parse()
            }
        }
    }
    }

    // MARK: Dynamic CalendarView's height
    extension CalendarViewController {
    func adjustCalendarViewHeight() {
        adjustCalendarViewHeight(higher: self.numOfRowIsSix)
    }
    
    func adjustCalendarViewHeight(higher: Bool) {
        separatorViewTopConstraint.constant = higher ? 0 : -calendarView.frame.height / CGFloat(numOfRowsInCalendar)
    }
    }

    //Mark: JTAppleCalendarViewDataSource
    extension CalendarViewController: JTAppleCalendarViewDataSource {
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2018 08 01")!
        let endDate = formatter.date(from: "2019 01 31")!
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: numOfRowsInCalendar)
        return parameters
    }
    }

    //Mark: JTAppleCalendarViewDelegate
    extension CalendarViewController: JTAppleCalendarViewDelegate {
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarCell", for: indexPath) as! CalendarCell
        cell.dateLabel.text = cellState.text
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
        cell?.bounce()
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        handleCellSelected(view: cell, cellState: cellState)
        handleCellTextColor(view: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        setupViewsOfCalendar(from: visibleDates)
        
        //Mark: adjust tableview Y to calendarview numOfRows of 5 or 6. Then animate
        adjustCalendarViewHeight()
        UIView.animate(withDuration: 0.5) { [unowned self] in
            self.view.layoutIfNeeded()
        }
    }
    }

    //Mark: TableView Delegate/DataSource for Date and Holiday Names
    extension CalendarViewController: UITableViewDelegate, UITableViewDataSource {
    func numberOfSectionsInTableView(tableView: UITableView) -> Int {
       return dateTableview.count
    }
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "\(dateTableview)"
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return tableViewDataSource.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "CalendarDateEvent", for: indexPath)
        let holidayTableviewLabel = cell.viewWithTag(3) as! UILabel
        holidayTableviewLabel.text = tableViewDataSource[indexPath.row].holiday
        let dataTableviewLabel = cell.viewWithTag(2) as! UILabel
        dataTableviewLabel.text = tableViewDataSource[indexPath.row].datenumber
        return cell
    }
    
    func tableView(_ tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int) {
        let header = view as! UITableViewHeaderFooterView
        header.textLabel?.font = UIFont.systemFont(ofSize: 16.0)
        header.textLabel?.textColor = #colorLiteral(red: 0.2773199975, green: 0.3366781473, blue: 0.3707436919, alpha: 1)
        header.backgroundView?.backgroundColor = UIColor.white
        tableView.layer.cornerRadius = 20
        tableView.layer.masksToBounds = true

    }
    }

    //Mark: XML Parse Delegate
    extension CalendarViewController {
    func parser(_ parser: XMLParser, didStartElement elementName: String, namespaceURI: String?, qualifiedName qName: String?, attributes attributeDict: [String : String] = [:]) {
        calendarevent = elementName
    }
    
    func parser(_ parser: XMLParser, foundCharacters string: String) {
        
        let data = string.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
        
        if data.count != 0 {
            switch calendarevent
            {
            case "month": monthTableview = data
            case "date": dateTableview = data
            case "datenumber": datenumberTableview = data
            case "holiday": holidayTableview = data
            default: break
            }
        }
    }
    
    func parser(_ parser: XMLParser, didEndElement elementName: String, namespaceURI: String?, qualifiedName qName: String?) {
        
        if elementName == "calendarevent"
        {
            myCalendarDates.month = monthTableview
            myCalendarDates.date = dateTableview
            myCalendarDates.datenumber = datenumberTableview
            myCalendarDates.holiday = holidayTableview
            print (tableViewDataSource)
            tableViewDataSource.append(myCalendarDates)
        }
    }
    }

    struct CalendarDates {
    var month = ""
    var date = ""
    var datenumber = ""
        var holiday = ""
        var description = ""
    }

Am a beginner and still learning, so any tips to clean up code also appreciated.

**Comment by patchthecode** [comment]
let me know if that helped.
