### ISSUE TITLE
When do you plan to release next version?

### ISSUE THREAD

**Issue by mock123** [patchthecode/JTAppleCalendar#879]
Just let me confirm, when do you plan to release next version? Maybe after all of the current issues have been resolved? (I know I can use master branch as well though)

**Comment by hemangshah** [comment]
The last released version is almost an year back so I guess, @patchthecode will release a new version soon.

**Comment by patchthecode** [comment]
Is there anything on the master branch that is missing from 7.1.5  that you need?

**Comment by mock123** [comment]
I'm going to take a look at it this week, and then get back to you! @patchthecode

**Comment by patchthecode** [comment]
closing issue.
Will release master branch once i know it is stable.

**Comment by mock123** [comment]
I tried master branch (latest commit), and figured out that the layout bugs on the iPad still remains. @patchthecode 

FYI: https://github.com/patchthecode/JTAppleCalendar/issues/719#issuecomment-397420394
