### ISSUE TITLE
Get the minimum and maximum date from the Calendar

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#880]
I am using the latest branch.
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

Yes, I'm the developer who will set the min and max date while configuring the Calendar but since I don't hold the reference to those dates is there a way to get it back from the Calendar?

I have come across this special requirements and thinking if it can be possible?

**Comment by patchthecode** [comment]
Yes. you can hold reference to those dates :D ?

Anyway, i just made an update to master branch.
```swift
calendarView.cachedConfiguration
```
will now get you the parameters that you have setup.

**Comment by hemangshah** [comment]
Is it available in the master branch? I still don't have access to it.
