### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by AndreaMiotto** [patchthecode/JTAppleCalendar#881]
Any plan for migration to swift 4.2?

**Comment by patchthecode** [comment]
Yea sure.
Are there any breaking changes in this lib with 4.2?

**Comment by jaistudy1996** [comment]
There are no compile-time errors but there are run-time constraint resolution errors. It seems like as if the layout engine is not able to break constraints. Also, the buttons are smaller in radius than in iOS 11.

**Comment by juliancadi** [comment]
I'm getting 22 compile errors using JTAppleCalendar in empty project with Swift 4.2 and Xcode 10 GM seed. All of them associated to renamed objects within UICollectionView and UIScrollView classes.

**Comment by dbyst** [comment]
I have the Same. 
@patchthecode When to expect Swift 4.2 migration ? 
Thanks

**Comment by MAAV360** [comment]
Is this version available in cocoapods?

I get 7.1.5 with swift 4.0

Thx

**Comment by muthukrishnanOCS** [comment]
I have the same issue with swift 4.2.

**Comment by NickGaens** [comment]
@patchthecode Can you please push a version to Cocoapods that contains the migration to Swift 4.2?

**Comment by mayqiyue** [comment]
Can you please push a version to Cocoapods that contains the migration to Swift 4.2?

**Comment by TiagoMaiaL** [comment]
Can you please push a version to Cocoapods that contains the migration to Swift 4.2?

**Comment by patchthecode** [comment]
@TiagoMaiaL 
done. Closing issue.
let em know of any bugs

**Comment by imobdevtech** [comment]
@patchthecode my application was made in swift 4.0 and by mistake i updated the pod now there are lots error are coming. Is there any way to get older version back?

**Comment by NickGaens** [comment]
> @patchthecode my application was made in swift 4.1 and by mistake i updated the pod now there are lots error are coming. Is there any way to get older version back?

Put this in your Podfile for an Swift 4.1-compatible version of JTAppleCalendar:

`pod 'JTAppleCalendar', '~> 7.1.5'`

**Comment by faganello60** [comment]
Any version with Swift 4.0?
Tks
