### ISSUE TITLE
After Tutorial and inserting willDisplay App still crashing

### ISSUE THREAD

**Issue by flymeheaven** [patchthecode/JTAppleCalendar#882]
Hi, i am using Version 7.1.5 just installed and did everything exactly like in the tutorials plus added the willDisplay function. But the App crashes when opening the Viewcontroller. And as i am newbie i have absolutely no idea, what to do, i tried it two times from the beginning, compared with your files. But plenty of vars changed so it is hard to understand. Here are my sources. Thank you in advance for helping. BR Manuel

[Archiv.zip](https://github.com/patchthecode/JTAppleCalendar/files/2345480/Archiv.zip)

**Comment by patchthecode** [comment]
You should have zipped the entire project. I cannot tell anything from those 2 files.

**Comment by flymeheaven** [comment]
hey, i just checked again and found my mistake. Thank you very much for answering quickly.
