### ISSUE TITLE
wrong selected date when vertical scrolling

### ISSUE THREAD

**Issue by agent134ssa** [patchthecode/JTAppleCalendar#883]
I am using version 7.1.4
I already selected dates and I scrolling down the other dates also get selected without I click on it. When I scroll back to the selected dates, the dates do not show, when I click the dates back, it show again.

<img width=300 src="https://user-images.githubusercontent.com/43023414/45133961-b1d77e00-b1ca-11e8-89d9-9906a4b1ac72.gif">

**Comment by patchthecode** [comment]
what code do you use to setup your cells?

**Comment by agent134ssa** [comment]
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        let twentyFour = Locale(identifier: "en_GB")
        formatter.locale = twentyFour
        
        var startDate = Date()
        var endDate = Date()
        
        formatter.dateFormat = "yyyy MM dd"
        
        let tempDate = Int(formatter.string(from: Date()).components(separatedBy: " ")[0])! + 10
        
        endDate = formatter.date(from: "\(tempDate) 12 01")!
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6,
                                                 calendar: currentCalendar,
                                                 generateInDates:.forAllMonths,
                                                 generateOutDates:.tillEndOfGrid,
                                                 firstDayOfWeek:.monday,
                                                 hasStrictBoundaries:true)
        return parameters
    }

If I call reloadData() at didSelectDate, didDeselectDate and didScrollToDateSegmentWith, it will not select the date that I selected.

**Comment by agent134ssa** [comment]
It is okay, I already found the cause of the bug.

Thank you for replying me!

**Comment by DrD00der** [comment]
How does one "reset" the cell? I have the same issue - when I scroll to other months random dates get selected.

**Comment by patchthecode** [comment]
@DrD00der 
this library is *exactly* the same as a UICollectionView or UITableView.
The same way you reset your cells in them is the same way you reset your cells in this.
