### ISSUE TITLE
cellState.dateBelongsTo incorrect?

### ISSUE THREAD

**Issue by philipshen** [patchthecode/JTAppleCalendar#885]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. I'm using version: 7.1.5
2. That's the latest version

It seems like the "cellState.dateBelongsTo" is incorrect for all months besides the first loaded one. And even for that first loaded month, reloading it (i.e. scrolling forward a few months and then back to it) messes everything up again.

This is what it looks like when I first open the app. Everything as it should be:

<img width="352" alt="screen shot 2018-09-06 at 23 27 34" src="https://user-images.githubusercontent.com/6759852/45167821-871e1180-b22c-11e8-95ea-fb0bb02e4125.png">

But as I scroll, it just gets messier and messier.

<img width="350" alt="screen shot 2018-09-06 at 23 28 37" src="https://user-images.githubusercontent.com/6759852/45167874-a5840d00-b22c-11e8-8f89-a2702ca690dc.png">

<img width="352" alt="screen shot 2018-09-06 at 23 28 48" src="https://user-images.githubusercontent.com/6759852/45167876-a6b53a00-b22c-11e8-9d8b-787b629c67f1.png">

[Here is a gist to my calendar's configuration](https://gist.github.com/philipshen/575ff1287a5fc372ca3ff396bd884ba6). The cells are very simple UI components with no logic themselves.

**Comment by patchthecode** [comment]
you have not shown me code where you set the color.
so i cannot tell where the problem is.

**Comment by philipshen** [comment]
Yeah, that was the issue. Thanks!
