### ISSUE TITLE
Info.plist Utility Error

### ISSUE THREAD

**Issue by Cez1g** [patchthecode/JTAppleCalendar#886]
I'm getting an info.plist error when I try to run. "could not read data from 'user/...' : couldn't open file because there is no such file". 

I'm running the current version 7.1.5 and using Xcode 9.4.1
I also used the will display function. I started receiving this code after I installed JTAppleCalendar with cocoa pods and followed the instruction on your first tutorial video. Before it I didn't get this code. So maybe I'm missing something. 
thank you.

**Comment by patchthecode** [comment]
this is not a library problem. This sounds like something went wrong with the cocoapod setup?
Did you try removing this lib and see what happened?

**Comment by patchthecode** [comment]
closing issue. As this is unrelated to the calendar lib.
