### ISSUE TITLE
Is there a way to slow down the scrolling speed of the Calendar?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#888]
I am using the latest branch.
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

Is there a way to slow down the scrolling speed of the Calendar?

**Comment by patchthecode** [comment]
https://patchthecode.github.io/CalendarScrolling/

look at the resistance. Its a fractional value from `0 to 1`
