### ISSUE TITLE
How to call a UIScrollView function?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#889]
Below function is not getting called even if this Calendar is based from `UICollectionView`.

Any idea on how to call this?

`func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) { ... }
`

**Comment by patchthecode** [comment]
This function does get called.
You need to tell me what you are trying to do so that i can get an idea of what to solve.

**Comment by hemangshah** [comment]
This is rates to this https://github.com/patchthecode/JTAppleCalendar/issues/876#issuecomment-418295294

**Comment by patchthecode** [comment]
Finally closing this issue.
I have made a suggestion of how it can be done in #876
