### ISSUE TITLE
Status bar tap not call delegate method.

### ISSUE THREAD

**Issue by mecid** [patchthecode/JTAppleCalendar#89]
When user tap on statusbar calendar scrolls to top, but didScrollToDateSegmentStartingWithdate delegate method not called.

**Comment by patchthecode** [comment]
hmm.. which status bar?

**Comment by mecid** [comment]
@patchthecode this is system behavior. If view controller has scrollview or collectionview, tap on system statusbar scroll view to top.

**Comment by patchthecode** [comment]
Ok. I will take a look at it in some time.

**Comment by mecid** [comment]
@patchthecode good!

**Comment by patchthecode** [comment]
but if it is possible you can find where the error might be in the mean time, please do so.
I have place this project on 2nd priority for now as I am working on another project.

**Comment by patchthecode** [comment]
Fixed on master branch
