### ISSUE TITLE
scroll to date without animation?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#891]
I am using the latest branch.
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'

I want to scroll to the specific date without animation, is it already implemented or you can create a new method with animation `toggle`?

**Comment by patchthecode** [comment]
it is already implemented.
Hey just as a tip you can see all developer functions in the `userInteractionFunctions.swift` file.

Almost ever function has optional parameters attached to them.
the full version of scrollToDate is
```swift
    public func scrollToDate(_ date: Date,
                             triggerScrollToDateDelegate: Bool = true,
                             animateScroll: Bool = true,
                             preferredScrollPosition: UICollectionViewScrollPosition? = nil,
                             extraAddedOffset: CGFloat = 0,
                             completionHandler: (() -> Void)? = nil) 
```

**Comment by hemangshah** [comment]
Thanks @patchthecode
