### ISSUE TITLE
I need some sample without storyboard

### ISSUE THREAD

**Issue by jbarros35** [patchthecode/JTAppleCalendar#892]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.5
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I have an issue because we don't use any storyboards at all and your samples are always using those.
How do I register your collection view where is the instance?

**Comment by jbarros35** [comment]
I think I was very clear about that. 
Most of us use libraries like snap kit, we don't have any story board at all and I'm having serious difficulties adapting your component and changing it because dealing with storyboards its just a pain in the ass.
How do I instantiate a JTAppleCalendarView? I understand that  inherits from UICOllectionView, but collection views I'm very used to work when I have data to use inside it, in your case I have none.
Tell me how do I create your calendar without using any storyboards directly from the code of a ViewController? I'm desperately trying and won't do anything. I already did the tutorial on the story board and its running but its no use for me because its not customisable as I wanted.

**Comment by patchthecode** [comment]
I was confused at what you were asking because all we have to do to instantiate is this:
```swift
let calendarView = JTAppleCalendarView()
```
Is there anything else needed?

**Comment by patchthecode** [comment]
closing. assumed resolved
