### ISSUE TITLE
CellPosition returns only full and right

### ISSUE THREAD

**Issue by annahuae** [patchthecode/JTAppleCalendar#894]
Hello,
last version of JTAppleCalendar
this might be discussed and i have seen even similar issue, but my code doesn't have that mistake.
can you please have a look quickly to understand what am i doing wrong.

All i need is programatically select date range when view appears.

    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        calendar.allowsMultipleSelection = true
        let parameters = ConfigurationParameters(startDate: Date(), endDate: Date(), calendar: Calendar.current)
        return parameters
    }
    
    func setInitialDates(dateFrom: Date?, dateTo: Date?) {
        if let dateFrom = dateFrom, let dateTo = dateTo  {
            //calendarView.scrollToDate(dateFrom, animateScroll:false)
            calendarView.selectDates(from: dateFrom, to: dateTo, triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: false)
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "calendarCell", for: indexPath) as! ContractCalendarCell
        cell.dateLabel.text = cellState.text
        cell.handleSelected(cellState: cellState)

        return cell
    }

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as? ContractCalendarCell
        cell?.handleSelected(cellState: cellState)
        let df = DateFormatter()
        df.dateFormat = "dd.MM.YYYY"
        print(df.string(from: date), cellState.selectedPosition())
    }

    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        let cell = cell as? ContractCalendarCell
        cell?.handleSelected(cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        let cell = cell as? ContractCalendarCell
        cell?.handleSelected(cellState: cellState)
    }

The console shows
01.09.2018 full
02.09.2018 right
03.09.2018 right
04.09.2018 right
05.09.2018 right
06.09.2018 right
07.09.2018 right
08.09.2018 right
09.09.2018 right
10.09.2018 right
11.09.2018 right
12.09.2018 right
13.09.2018 right
14.09.2018 right
15.09.2018 right

and it looks like this
<img width="310" alt="screen shot 2018-09-14 at 13 56 03" src="https://user-images.githubusercontent.com/32207964/45543595-f0ea7c80-b825-11e8-92b4-6d663aaa5c8a.png">

Thanks in advance for your time

**Comment by patchthecode** [comment]
in viewDidLoad.
```swift
calendarView.isRangeSelectionUsed = true
```

**Comment by annahuae** [comment]
Amazing. Thanks a lot for your work!
