### ISSUE TITLE
How to show multiple dates with different color on this calendar?

### ISSUE THREAD

**Issue by vishnude** [patchthecode/JTAppleCalendar#899]
Hey there thanks for such an amazing calendar. This is more of a doubt than an issue. The thing is I have multiple arrays of date. I want to show each array of dates with different highlighted colours. Each array can contain different dates for a particular month I want dates to be highlighted according to each array and all of them should be in the calendar, even when we are selecting some other different dates of that particular month.
![screenshot from 2018-09-17 15-07-41](https://user-images.githubusercontent.com/43202650/45616038-e4675d80-ba8b-11e8-8fa4-06da7b63dd19.png)

I want the calendar to look like the screenshot. Could you please help me achieve this.

**Comment by patchthecode** [comment]
Sorry for the late reply, and the short response, but

This library is exactly a UICollectionView. The same way you would change colors of a cell based on data in an array for a UICollectionView, is the exact same way you should do it for this library.

Will close this issue, but let me know if it helped.

**Comment by vishnude** [comment]
Thank you for helping me out. That worked I have done that accordingly
