### ISSUE TITLE
Displaying custom design on a specified date

### ISSUE THREAD

**Issue by antonijap** [patchthecode/JTAppleCalendar#9]
I have many arrays of dates and I am extracting first date from arrays and adding 10 days on that first date. So I have a custom design set up already and it is working as expected when the app loads and shows current month. But when I scroll to a month before or a month after I still get that date printed out in my console that should have different design (that means my code for calculation works) but my custom function in `.isAboutToDisplayCell` is not affecting them. I tried to add `calendarView.reloadData()` but then calendar just freezes. I wonder if you have some suggestion on how to apply that custom design if `.isAboutToDisplayCell` meets certain date?

This is my code in `class CellView: JTAppleDayCellView`
```
// Display circle on a date that predict future bleeding
    func displayFutureDate(trueOrFalse: Bool, cellState: CellState) {
        if trueOrFalse == true {
            futureDate.hidden = false
            futureDate.layer.borderWidth = 1
            futureDate.makeCircle()
            futureDate.layer.borderColor = whiteColor.CGColor
        } else {
            futureDate.hidden = true
        }
    }
```

Just showing or hiding some UIView. And I am calling this in `.isAboutToDisplayCell` if certain date is met.

**Comment by patchthecode** [comment]
Acknowledged your question. Reading it now, to understand it more.

**Comment by patchthecode** [comment]
So just to understand this clearly.

1. you have a custom design for dateX
2. when you scroll forward to another month,
and then scroll back to the month with the custom date,

are you saying the custom selection disappears?

**Comment by antonijap** [comment]
This is in current month
http://d.pr/i/18R2o/1VKOpAro

And this is in March
http://d.pr/i/1iqmv/49wRA6Li
You see... That 10th date (03/24) is not selected like it was in April.

I figured it is because cells for dates are rendering as I scroll so by the time I finished it somehow overwrites that date that should have circle.

**Comment by patchthecode** [comment]
OK. Still a little confused.

On April, I see 3 yellow dates, one purple date, and one white date.
On March, 3 Yellow dates.

Are you saying that on March, i should also be seeing a a purple date, and a white date?

**Comment by patchthecode** [comment]
This is way to slow as a chat. -> head here
https://gitter.im/patchthecode/JTAppleCalendar?utm_source=share-link&utm_medium=link&utm_campaign=share-link

?

**Comment by patchthecode** [comment]
Some things to think about when you get back.
1. Are you using version 2.0.3 ?
2. Is the month of April working perfectly even if you scroll away from it and back to it?

If the answer to those two is a yes, then lets chat again, because i believe the issue might be code related.

**Comment by patchthecode** [comment]
Issue resolved. Closing issue
