### ISSUE TITLE
Making this work with TvOs 

### ISSUE THREAD

**Issue by mkogundi** [patchthecode/JTAppleCalendar#90]
Hi 

i am trying to use this calendar with apple tv app and os is TvOs

can you please provide some guidance as to how i can tweak it to make it work with tvos.

Thanks in advance!

**Comment by patchthecode** [comment]
Honestly, I have never used tvOS code/projects before. I do not know where to begin. I will have to look into this.

Have you worked with tvOS before? Since my code is for iOS, is there major code changes that needs to be made so that it works for tvOS?

**Comment by patchthecode** [comment]
If the code change is not much, then i will look into porting this to tvOS

**Comment by mkogundi** [comment]
@patchthecode even  i am newbie in tvos but i referred to this link https://waynehartman.com/posts/convert-ios-xibs-to-tvos.html

while converting the other project to tvos

**Comment by patchthecode** [comment]
Ok, I have looked into it and it is possible. But I am not good at the cocoapod setup. If any one is good at setting up projects to work with multiple frameworks, please provide your help here as to how I should make this project work with tvOS.

I will add the Help wanted tag to this thread.

**Comment by mkogundi** [comment]
even without the pod can u update the code and provide as a normal github project so that we can directly download and use sort ? something on these line (https://github.com/lancy98/Calendar)

**Comment by patchthecode** [comment]
Ok. I have got it working for tvOS.
One thing tho, I'm not a tvOS guru. So I will need some help if you have some free time. If not, then its all good.
