### ISSUE TITLE
After updating to 7.1.6

### ISSUE THREAD

**Issue by bbo-jay** [patchthecode/JTAppleCalendar#904]
![screen shot 2018-09-21 at 11 54 47 am](https://user-images.githubusercontent.com/36146249/45859506-3f9f9580-bd95-11e8-8f24-efa15594d166.png)

**Comment by annahuae** [comment]
Same here
<img width="1141" alt="screen shot 2018-09-21 at 12 44 59" src="https://user-images.githubusercontent.com/32207964/45870615-5a293d00-bd9c-11e8-8b80-42a7ecac8a4a.png">

**Comment by RobertHaworth** [comment]
These are Swift 4.2 compatibility issue errors, is there a release cleared for Swift 4.2 support?

**Comment by annahuae** [comment]
Not really, i have same errors for swift 4.1 band new project

**Comment by patchthecode** [comment]
@all 
Are you guys running swift 4.2 Xcode 10 ?

**Comment by annahuae** [comment]
Mine Xcode was 9, installing 10 now...

**Comment by RobertHaworth** [comment]
Yes this is an issue with Xcode 9, after installing 10 the issue went away.

**Comment by patchthecode** [comment]
OK yes, this isnt really an issue then
The latest release was to ready for Swift 4.2.
Swift 4.2 is available with XCode 10.

If any one have not yet upgraded, they should stay on 7.1.5

**Comment by annahuae** [comment]
thank you
