### ISSUE TITLE
The layout bug occurs when I rotate a device. (version 7.1.6)

### ISSUE THREAD

**Issue by mock123** [patchthecode/JTAppleCalendar#905]
The bug happens on both my own project and the iOS example project in this library (version 7.1.6).
I used Xcode10, and iPad Pro (9.7-inch, simulator) & iPhone8 (simulator) for testing. This bug does not happen in the previous version (7.1.5).

Please take a look at the iOS example project in this library. @patchthecode 

# Screenshots (FYI)

### iPad
![simulator screen shot - ipad pro 9 7-inch - 2018-09-23 at 04 14 07](https://user-images.githubusercontent.com/36657040/45920964-24dd3600-bee7-11e8-956d-4e6c510a3488.png)

![simulator screen shot - ipad pro 9 7-inch - 2018-09-23 at 04 00 00](https://user-images.githubusercontent.com/36657040/45920839-6b319580-bee5-11e8-8fa3-cb07c752aa67.png)

### iPhone
![simulator screen shot - iphone 8 - 2018-09-23 at 04 17 50](https://user-images.githubusercontent.com/36657040/45920999-e1cf9280-bee7-11e8-86e2-1fbac7d4249d.png)

![simulator screen shot - iphone 8 - 2018-09-23 at 04 17 55](https://user-images.githubusercontent.com/36657040/45921001-e4ca8300-bee7-11e8-9e5a-bc9473512099.png)

### iPad
![simulator screen shot - ipad pro 9 7-inch - 2018-09-23 at 03 59 37](https://user-images.githubusercontent.com/36657040/45920880-bf3c7a00-bee5-11e8-8494-46c7f2907930.png)

![simulator screen shot - ipad pro 9 7-inch - 2018-09-23 at 03 59 41](https://user-images.githubusercontent.com/36657040/45920837-5a811f80-bee5-11e8-986d-6dc8c9380832.png)

### iPhone
![simulator screen shot - iphone 8 - 2018-09-23 at 04 17 43](https://user-images.githubusercontent.com/36657040/45920985-adf46d00-bee7-11e8-8009-1de68c76da05.png)

![simulator screen shot - iphone 8 - 2018-09-23 at 04 17 46](https://user-images.githubusercontent.com/36657040/45920987-b3ea4e00-bee7-11e8-9e11-9c71d0fa5758.png)

**Comment by gsuthor** [comment]
I have the same Problem when switching from portrait to landscape on iPad with Version 7.1.6

**Comment by patchthecode** [comment]
will take a look

**Comment by patchthecode** [comment]
can you paste me the code you used on rotation?
@gsuthor 
@mock123

**Comment by gsuthor** [comment]
I used just constraints with a height constraint for the Calendar View that is changed in  viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator). I also tried calenderView.layoutSubviews but it doesn't work.

In Version 7.1.5 it was working.

**Comment by patchthecode** [comment]
yes. but what is the code you have in that **viewWillTransition** function?

**Comment by mock123** [comment]
With the code above, it worked like a charm for me!  @patchthecode

**Comment by gsuthor** [comment]
Yes it worked with the code above. Big Thanks @patchthecode

**Comment by patchthecode** [comment]
cool.closing issue
