### ISSUE TITLE
Dynamic Number of rows

### ISSUE THREAD

**Issue by agent134ssa** [patchthecode/JTAppleCalendar#906]
Hi, I am using version 7.14.

How can I generate dynamic number of row for the calendar? As in the image, I do not want the outdates to be appear too many row (2-3 row)

![picture1](https://user-images.githubusercontent.com/43023414/45926674-9bfee280-bf58-11e8-9900-c07364a58a0f.png)

**Comment by patchthecode** [comment]
ok. first thing.
Please use version 7.1.5

and 2nd, can you please paste the code for your `configureCalendar` function?

**Comment by agent134ssa** [comment]
Ok. I will update my version when I have time to do it.    

func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let formatter = DateFormatter()
        let twentyFour = Locale(identifier: "en_GB")
        formatter.locale = twentyFour
        
        var startDate = Date()
        var endDate = Date()
        
        formatter.dateFormat = "yyyy MM dd"
        
        let tempDate = Int(formatter.string(from: Date()).components(separatedBy: " ")[0])! + 10
        
        endDate = formatter.date(from: "\(tempDate) 12 01")!
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: 6,
                                                 calendar: currentCalendar,
                                                 generateInDates:.forAllMonths,
                                                 generateOutDates:.tillEndOfGrid,
                                                 firstDayOfWeek:.monday,
                                                 hasStrictBoundaries:true)
        return parameters
    }

**Comment by patchthecode** [comment]
I am asking you to update because i do not know what i am seeing on your screen shot.
If you look at the screen shot, i am seeing that October only has 11 days in it. Then after the 11th day, it skips and goes to the 29th.

**Comment by patchthecode** [comment]
I added the **awaiting input from user** flag on this question. Closing until requirement met.

**Comment by agent134ssa** [comment]
Sorry for the late reply. My question was how to make the calendar row dynamic if each month only had 5 or 6 or 7 row.

**Comment by patchthecode** [comment]
> My question was how to make the calendar row dynamic if each month only had 5 or 6 or 7 row.

I do not understand what this means. Can you please rephrase?
