### ISSUE TITLE
A proper way to show full/week calendar view?

### ISSUE THREAD

**Issue by hemangshah** [patchthecode/JTAppleCalendar#913]
What is the best way to decrease the height of the calendar view to display a week calendar and if user wants we can reverse it back to full calendar? For my app, this is happening when a bottom view will scroll to up (with pan gesture) I am updating the height constraint of the calendar view. But right now it's too fast for me and I don't really like it 👎 Did you answered this to any one earlier with similar query? Or do you recommended to reducing/increasing the height of calendar view properly?

**Comment by patchthecode** [comment]
i will come up with a good example soon.

**Comment by patchthecode** [comment]
example has been added at [patchthecode.com](patchthecode.com)
