### ISSUE TITLE
Unable to run project.

### ISSUE THREAD

**Issue by Vignesh-ios** [patchthecode/JTAppleCalendar#914]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. Yes
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6. Yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UICollectionView 0x7fec6a032800> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key ibCalendarDataSource.'

**Comment by Vignesh-ios** [comment]
![screenshot 2018-10-01 at 12 03 37 pm](https://user-images.githubusercontent.com/30468530/46273253-679baf80-c572-11e8-8e38-5c48b0d765dd.png)
![screenshot 2018-10-01 at 12 04 59 pm](https://user-images.githubusercontent.com/30468530/46273271-72564480-c572-11e8-9ee4-8f4e7b773d2a.png)
![screenshot 2018-10-01 at 12 05 28 pm](https://user-images.githubusercontent.com/30468530/46273287-81d58d80-c572-11e8-821d-a30557ef8248.png)

i am using xcode 10
Swift version 4.2
JTAppleCalendar version : 7.1.6.

**Comment by patchthecode** [comment]
you get that error when you have not properly set the class type on interface builder for the calendar/

**Comment by Vignesh-ios** [comment]
I changed collectionView class as JTAppleCalendarView and collectionView cell class as CustemCell. Custom cell is subclassed JTAppleCell.

**Comment by patchthecode** [comment]
are you still experiencing the error?

**Comment by patchthecode** [comment]
Have you set the module after putting in the class name? It should be in the same area.

**Comment by Vignesh-ios** [comment]
No

**Comment by Vignesh-ios** [comment]
![screenshot 2018-10-01 at 4 37 12 pm](https://user-images.githubusercontent.com/30468530/46286136-a1cd7700-c59b-11e8-800b-bf23d08ecfdb.png)
![screenshot 2018-10-01 at 4 41 19 pm](https://user-images.githubusercontent.com/30468530/46286138-a1cd7700-c59b-11e8-86b6-23d3e7f7f097.png)

Anything wrong ?

**Comment by patchthecode** [comment]
Yes. Your module is set to none.
Set it to JTAppleCalendar

**Comment by Vignesh-ios** [comment]
Changed module to JTAppleCalendar.
Still crashing.
![screenshot 2018-10-02 at 9 09 22 am](https://user-images.githubusercontent.com/30468530/46328115-f962f580-c622-11e8-9707-82e52867b14f.png)

**Comment by patchthecode** [comment]
you did not set it to **JTAppleCalendar**
you set it to **JTAppleCalendarView**
These are not the same thing

**Comment by patchthecode** [comment]
will close this issue now
