### ISSUE TITLE
dateBelongsTo not in sync when fast scrolling

### ISSUE THREAD

**Issue by alittle433** [patchthecode/JTAppleCalendar#916]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. 
7.16
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
Yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

We are setting borders and backgrounds for cells depending on data from an API, this works perfect for the first month or if you scroll slowly through the calendar. However once you scroll quicker the dates get messed up and dateBelongsTo isn't accurately setting up the cell. 

To improve upon this we have disabled the buttons used to scroll through the calendar using a delay that waits 0.5 seconds before enabling the buttons again.

However this does not fix the problem as if we need to scroll to a date more than a month or two away the same issues arise. It seems as though it may be a performance issue ie not being updated quick enough. 

Here is the datasource and delegate methods.

``` swift
extension CalendarView: JTAppleCalendarViewDelegate, JTAppleCalendarViewDataSource {

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        if let cell = cell as? CalendarCell {
            sharedFunctionToConfigureCell(calendar: calendar, cell: cell, cellState: cellState, date: date, indexPath: indexPath)
        }
    }


    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        if let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: CalendarCell.identifier, for: indexPath) as? CalendarCell {
            sharedFunctionToConfigureCell(calendar: calendar, cell: cell, cellState: cellState, date: date, indexPath: indexPath)
            return cell
        }
        return calendar.dequeueReusableJTAppleCell(withReuseIdentifier: CalendarCell.identifier, for: indexPath)
    }

    func sharedFunctionToConfigureCell(calendar: JTAppleCalendarView, cell: CalendarCell, cellState: CellState, date: Date, indexPath: IndexPath) {
        cell.state = cellState
    }

    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        let params = ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: Calendar.current, generateInDates: InDateCellGeneration.forAllMonths, generateOutDates: OutDateCellGeneration.off, hasStrictBoundaries: true)
        return params
    }

    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        updateStepper(visibleDates: visibleDates)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            self.stepper.enableStepper(enabled: true)
        }
    }
}
```

Here is the initialiser 

``` swift
lazy var calendarView: JTAppleCalendarView = {
        var cv = JTAppleCalendarView(frame: CGRect.zero)
        cv.backgroundColor = .clear
        cv.register(CalendarCell.self, forCellWithReuseIdentifier: CalendarCell.identifier)
        cv.showsHorizontalScrollIndicator = false
        cv.scrollingMode = ScrollingMode.nonStopToSection(withResistance: 0)
        cv.scrollDirection = .horizontal
        cv.isScrollEnabled = false
        return cv
    }()
```

Here is the setup

``` swift
 func setupCalendar() {
        calendarView.calendarDataSource = self
        calendarView.calendarDelegate = self
        calendarView.minimumLineSpacing = 2
        calendarView.minimumInteritemSpacing = 2
        calendarView.cellSize = dayStack.frame.width / 7
        calendarView.visibleDates { visibleDates in
            self.updateStepper(visibleDates: visibleDates)
        }
    }
```

**Comment by patchthecode** [comment]
> We are setting borders and backgrounds for cells depending on data from an API

Does this API make server calls (data over a network)?
Is it possible that the latency is causing this?

If yes, then what you need is some sort of loading notification popover dialogue box until the data is received.

**Comment by alittle433** [comment]
This is not a network issue, the data is already stored in a local database by the time the calendar is setup. We cannot scroll to a date, its like the calendar scrolls too fast which throws the datasource out of sync or something.

**Comment by patchthecode** [comment]
> its like the calendar scrolls too fast which throws the datasource out of sync or something

This should not be possible with the code i have in this lib.
Can you create a new sample project which recreates this issue? (removing all secret company code)

You do not have to design it. Make the sample app dirt simple.
Then zip the project and drop the file in this chat box.

**Comment by patchthecode** [comment]
closing until user responds.
