### ISSUE TITLE
scrollToSegment with .previous not working if Calendar is vertical

### ISSUE THREAD

**Issue by kboirel** [patchthecode/JTAppleCalendar#917]
I want to use this function but it's not working:
self.calendarView.scrollToSegment(.previous)

I don't know why, but the result is the same than self.calendarDataView.scrollToSegment(.next)

I tried to set the Calendar vertical on the demo app to see if there is a difference...and no... the result is the same. If I want to call the previous function, the next function seems to be called instead.

I tried to edit the file but I don't have any change. Could you help me on that please?

**Comment by patchthecode** [comment]
The demo app works.
I just tried it.

What version of the library are you using?

**Comment by kboirel** [comment]
I downloaded again the last version of the demo to try, and I'm sorry but it's not working on my phone..
I click on the first link on the homepage "Calendar Layouts demonstration", then click "vertical" button. And if I want to play with next & previous, the previous button is not working. (exactly like on my app, when I click the previous button, the calendar goes to the next month)

In my app I use: 
`pod 'JTAppleCalendar', '~> 7.0'`

**Comment by patchthecode** [comment]
can you try with the latest version of this library? 7.1.6?

**Comment by kboirel** [comment]
Still not working :/

**Comment by patchthecode** [comment]
in that case, can you provide me a zipped sample project which shows this bug?
All of my tests are passing from my end.

Just create a blank project with few lines of code and implement the next and previous buttons.
Then drop the zip file in this chat box.

**Comment by patchthecode** [comment]
closing this issue.
I set the "Awaiting user input flag"

**Comment by ghadgeakshay** [comment]
you need to add below line and everything works
CalenderView.scrollingMode =  .stopAtEachSection
