### ISSUE TITLE
2 Date Segment on 1 UIView

### ISSUE THREAD

**Issue by mrjimoy** [patchthecode/JTAppleCalendar#92]
Hi, can I show 2 segment using JTAppleCalendar? I mean, on a UIViewController, I would like to have 2 months displayed vertically instead of only 1.. Please see image below.

![image](https://cloud.githubusercontent.com/assets/6197219/17203520/379a67c4-54ca-11e6-84d0-5288686621bc.png)

Thank you.

**Comment by patchthecode** [comment]
That would mean you need to make your dateCells smaller.
If this is what you want, then set a smaller size like this:

`calendarView.itemSize = someSmallerNumber`

**Comment by mrjimoy** [comment]
Hi @patchthecode, thank you for your reply. I tried to make the UIView filled the whole screen and add that line of code, but when I tried to scroll it down, it doesn't fitted the container (pls see image below).

![snip20160729_84](https://cloud.githubusercontent.com/assets/6197219/17235342/953860d4-556a-11e6-85ab-0d2f51f96660.png)
![snip20160729_85](https://cloud.githubusercontent.com/assets/6197219/17235347/982461bc-556a-11e6-9bab-264aa8a3eefe.png)

**Comment by mrjimoy** [comment]
Hi @patchthecode, thank you so much. It's worked with some adjustment on the measurement. 1 quick question, how to show the day name above the date? Do we need to create a separate XIB (HeaderViewCell) or is there any function that can directly show the day name? Thanks.

**Comment by mecid** [comment]
@mrjimoy You need to create separate XIB or add View like this.

`class WeekdaysView: UIStackView {
    private lazy var weekdayLabels: [UILabel] = self.createWeekdayLabels()
    
    private func createWeekdayLabels() -> [UILabel] {
        let formatter = NSDateFormatter()
        var weekdayLabels = [UILabel]()
        
        for i in 0...6 {
            let label = UILabel(frame: CGRectZero)
            label.font = UIFont.preferredFontForTextStyle(UIFontTextStyleCaption2)
            label.text = formatter.veryShortWeekdaySymbols[i]
            label.textColor = UIColor.lightTextColor()
            label.textAlignment = .Center
            
            weekdayLabels.append(label)
        }
        
        return weekdayLabels
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
        setup()
    }
    
    private func setup() {
        self.axis = .Horizontal
        self.alignment = .Center
        self.distribution = .FillEqually
        
        for label in weekdayLabels {
            addArrangedSubview(label)
        }
    }
}
`

**Comment by patchthecode** [comment]
@mrjimoy 

1) **_How to show the day name above the date?_**


Are you trying to make your calendar look like the image you just provided above? If yes, then you can do exactly what @mecid said.

Simply create a header.xib file and design it with like this:

<img width="340" alt="screen shot 2016-07-29 at 9 45 13 am" src="https://cloud.githubusercontent.com/assets/2439146/17256179/35527a7c-5571-11e6-8fb6-74961caab79a.png">

You can look at the example code attached to this project to see how to create a header view. You can also checkout [this wiki question](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#3)

2) **_Is it possible to create the multiple selection as a range_**


Although I do not have this feature built in, the calendar is flexible enough that you can build it your self as can be seen [here](https://github.com/patchthecode/JTAppleCalendar/issues/2#issuecomment-231521234. It does not take much code to build it, but I will be implementing this as a feature in the library soon.

**Comment by patchthecode** [comment]
i'll close this issue. If you have any other questions please as it on another thread. This thread is now becoming more than one topic.

**Comment by mrjimoy** [comment]
Great, thank you so much @patchthecode  :)
