### ISSUE TITLE
Scrolling to a month?

### ISSUE THREAD

**Issue by SpajicM** [patchthecode/JTAppleCalendar#921]
Version 7.1.5

Is it possible to scroll to a specific month, so that month header is visible.

Because I retrieve dates from the server, select them, and want to scroll to first date, but I still want user to be able to see which month they're on, so I'd rather scroll to a month than to specific date.

Sounds like the opposite of https://github.com/patchthecode/JTAppleCalendar/issues/496

**Comment by patchthecode** [comment]
```swift
calendarView.scrollToDate( dateYouWantToScrollTo)
```

**Comment by SpajicM** [comment]
If I scroll to date, for example October 16, it will scroll to middle of the month and user won't be able to see what month it is right away.

That's why I'd like to scroll to month (with month header staying visible to user)

**Comment by patchthecode** [comment]
the scrolling is affected by your scrollingMode.
What is your scrolling mode? 
https://patchthecode.github.io/CalendarScrolling/

**Comment by SpajicM** [comment]
nonStopToSection is what I wanted :) Thanks!

**Comment by patchthecode** [comment]
cool
