### ISSUE TITLE
Enable selectable for specific dates

### ISSUE THREAD

**Issue by kenk11** [patchthecode/JTAppleCalendar#925]
Hi guys, I'm working on customize JTAppleCalendar. I only enable some specific dates such as public holiday in calendar view, and others are disable. How can I implement it ?

Thanks advance

**Comment by patchthecode** [comment]
this library is a UICollectionView under the hood, so the functions are very similar.
Implement the `shouldSelectDate` function and return either true or false based on your condition

**Comment by patchthecode** [comment]
closing this issue. let me know if it helped.
