### ISSUE TITLE
Cells not showing in JTAppleCalendar

### ISSUE THREAD

**Issue by bloghran618** [patchthecode/JTAppleCalendar#926]
Hello,
Sorry to bother, but I have been stuck on this problem for a few days now, cannot seem to figure it out. The issue is with displaying the cells in the calendar. I have been following along with a video at this [link](https://www.youtube.com/watch?v=zOphH-h-qCs): 

So this video seems to be for version 7.0. I am currently using version 7.1.6. I read the note [here](https://github.com/patchthecode/JTAppleCalendar/issues/553) which tells me to simply update the extension for UIViewController. So I did that, here is my code:
```
extension ViewController: JTAppleCalendarViewDataSource, JTAppleCalendarViewDelegate {
    
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        
        let startDate = formatter.date(from: "2017 01 01")!
        let endDate = formatter.date(from: "2017 12 31")!

        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate)
        return parameters
    }
    
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // This function should have the same code as the cellForItemAt function
        let myCustomCell = cell as! CustomCell
        sharedFunctionToConfigureCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
    }

    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        sharedFunctionToConfigureCell(myCustomCell: myCustomCell, cellState: cellState, date: date)
        return myCustomCell
    }

    func sharedFunctionToConfigureCell(myCustomCell: CustomCell, cellState: CellState, date: Date) {
        myCustomCell.backgroundColor = UIColor(red: 255, green: 0, blue: 0, alpha: 0)
        myCustomCell.dateLabel.text = cellState.text
        // more code configurations
    }
}
```

That's pretty much copied strait from the link. But my calendar still looks like:
![image](https://user-images.githubusercontent.com/10566928/47405471-a4953500-d71f-11e8-8a7f-5272fc3a9497.png)

:(

So I went online to try to solve the issue. Seems other people have had a similar issue, but I tried solutions from [here](https://github.com/patchthecode/JTAppleCalendar/issues/577), [here ](https://github.com/patchthecode/JTAppleCalendar/issues/59)and [here](https://github.com/patchthecode/JTAppleCalendar/issues/672), to no avail. 

One place my experience varied slightly from the youtube video was when setting the delegate and datasource for the UICollectionView was that the outlets looked like this:
![image](https://user-images.githubusercontent.com/10566928/47405545-035aae80-d720-11e8-912b-5821a32357ce.png)
which was marginally different from the video. Is this somehow the problem? I do not know why they are different from the video.

Another thought I had was that in one of the solutions, it says that this issue can occur "because sometimes developers forget to set constraints on their cells." However, I do not seem to be able to set constraints on my cells, when I pull up the constraints it looks like:
![image](https://user-images.githubusercontent.com/10566928/47405613-63e9eb80-d720-11e8-8d1e-1e77dac1d684.png)

At this point I really am quite stuck, I don't know what else to try. Any thoughts? Is this a bug, or is this just me?

**Comment by 7Kris** [comment]
I had the same problem when I set up my calendar for the first time as well.

Disconnect your dataSource and delegate from storyboard, and manually connect them in code
`calendarView.calendarDelegate = self
  calendarView.calendarDataSource = self`

Also make sure your calendar in storyboard is set up like this
<img width="256" alt="screen shot 2018-10-24 at 2 40 29 pm" src="https://user-images.githubusercontent.com/30877240/47408551-d5ff1680-d79a-11e8-8c3e-f6bbdbfdc853.png">

This should fix your issue, but if not let me know.

**Comment by bloghran618** [comment]
Yes! This fixed it! Thanks so much!

Just to be perfectly clear for anyone else struggling with the same issue, 7Kris created calendarView by CTRL+dragging the UICollectionView from the storyboard to the viewController, and creating a connection of type JTAppleCalendarView, setting the  storage to weak, and naming it calendarView. He then set the placed his code in the viewDidLoad() method. So all that looks like:

     

    class ViewController: UIViewController {
        @IBOutlet weak var calendarView: JTAppleCalendarView!
        let formatter = DateFormatter()
    
    
        override func viewDidLoad() {
            super.viewDidLoad()
        
            calendarView.calendarDataSource = self
            calendarView.calendarDelegate = self
        }
    }

The second point he makes about the storyboard is that in the video the Module is automatically set to JTAppleCalendar, but you have to manually set up in storyboard. 

Thank you very much 7Kris!

Closing the issue...
