### ISSUE TITLE
cellState.text is not correct 

### ISSUE THREAD

**Issue by SymonTBBD** [patchthecode/JTAppleCalendar#929]
Version: 7.1.6
![img_0003](https://user-images.githubusercontent.com/44426818/47600242-fbc92d00-d9df-11e8-8a55-79caa36ba6ee.PNG)

Into JTAppleCalendarViewDelegate, used below code

`func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CustomCell", for: indexPath) as! CustomCell
        cell.dateLabel.text = cellState.text
        return cell
    }`

Problem: Date order is not correct

**Comment by patchthecode** [comment]
nothing wrong here.
you are seeing inDates/outDates
https://cloud.githubusercontent.com/assets/2439146/18330595/651b8840-750e-11e6-8727-a148d7e1720f.png

**Comment by patchthecode** [comment]
closing issue.
