### ISSUE TITLE
How do you change the calendar layout to vertical mode?

### ISSUE THREAD

**Issue by RayZhuAU** [patchthecode/JTAppleCalendar#93]
What do you do to change the calendar to scroll vertically?

**Comment by idilgun** [comment]
@RayZhuAU I am looking for the same thing, since you closed this issue, did you find the solution?

**Comment by patchthecode** [comment]
@idilgun `calendarView.scrollDirection = .vertical`

**Comment by idilgun** [comment]
Thanks @patchthecode

**Comment by patchthecode** [comment]
@idilgun cool. If this library has saved you months of coding then consider leaving a Star ★ Github rating. It will be greatly appreciated. Cheers 🍻

**Comment by tungfam** [comment]
updated to: `calendarView.direction = .vertical`
Thanks! I was really about to look for a new pod but I found this answer which solved the problem of vertical scroll :)))

**Comment by patchthecode** [comment]
@tungfam thanks. I will update this!!

**Comment by tungfam** [comment]
@patchthecode  is it possible to make the calendar to scroll vertically + continuously (not discretely). 
In other words the calendar like standard apple calendar on iOS, where when you scroll vertically it's shows months not discretely but kind of "together". Hope my bad explaination was clear :)

**Comment by patchthecode** [comment]
@tungfam Hey I think one thing that could save you a lot of headaches is the tutorials -> https://github.com/patchthecode/JTAppleCalendar

Specifically, the part in the tutorials you are looking for is located here -> https://patchthecode.github.io/CalendarScrolling/

It shows you all the scrolling modes you can do with the library. Is your solution located in there? Let me know.

**Comment by tungfam** [comment]
@patchthecode thanks a lot! that's what was needed :) next time i better go through all tutorials then ask ..

**Comment by patchthecode** [comment]
@tungfam haha. its cool man. If you have any further questions, then just ask :)
