### ISSUE TITLE
Hide Weekend Days - with last version 7.1.6 is not working anymore

### ISSUE THREAD

**Issue by nairpic20** [patchthecode/JTAppleCalendar#932]
Hi,

Before switching to swift 4.2 and update JTAppleCalendar to the last version, I was hiding the weekend days by changing the cellSize property, followed by a calendar reloadData. Also the scrolling mode is set to .stopAtEachSection. After the migration, this feature is not working anymore or something has changed and I'm missing what's new. I've tested also your demo project, same behaviour. Any hints? Thanks

**Comment by patchthecode** [comment]
ok it looks like i definitely broke something.
Let me work on this.

**Comment by nairpic20** [comment]
thanks ;)

**Comment by patchthecode** [comment]
i just pushed an update to master branch.
can you test it and let me know if it was fixed?

To test master branch, follow [the instructions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions)

**Comment by nairpic20** [comment]
everything ok with the weekend days now ... still have some issues with visibleDates, but will create a new ticket because this issue is fixed

thanks a lot for your implication and for this awesome library ;)

**Comment by patchthecode** [comment]
cool.
