### ISSUE TITLE
Selecting date is off by one

### ISSUE THREAD

**Issue by ahmed-sal** [patchthecode/JTAppleCalendar#933]
Hello, first let me thank @patchthecode for this amazing library 👍 kudos.

Secondly, I am using version `7.1.6` and here's the problem
When I tap on any cell, the method `didSelectDate` gets called but with the wrong date. Instead it passes one date earlier. For example (check the attached screenshot) when I select November the 4th, the date passed is November the 3rd and so on. 

*NOTE* for reference,  the app UI clearly selects the 4th, but the `date` variable in the variables view clearly shows `date 2018-11-03 22:00:00 UTC` . 

Any ideas what might be causing this? It appears there is a mismatch between the displayed items and the actual dates. 

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/18123771/47968671-e1452280-e075-11e8-9994-b60d4c54a97f.png">

**Comment by seropusha** [comment]
Date creates with UTC timezone, as I see you located in +2 timeZone.
I think need to add your timeZone offset to this date and will be correct.

**Comment by patchthecode** [comment]
Yea this question has been asked many times before.
This is not a library problem. You'll just need to understand Dates  with swift and with time-zones fully.
Here is one discussion of it that should hopefully explain every thing -> https://github.com/patchthecode/JTAppleCalendar/issues/252

**Comment by patchthecode** [comment]
closing this issue. Let me know if youre still stuck.

**Comment by ahmed-sal** [comment]
@seropusha thank you for your insight .. going to investigate that and post back here on status.

@patchthecode thanks for confirming. I'll let you guys know how it goes.

**Comment by ahmed-sal** [comment]
@patchthecode @seropusha an update (also for anyone who runs into this issue again). You guys were right. So I added an extension for date to convert it to local date. 

```swift
extension Date {
    
    func inLocalRegion() -> Date{
        let dateInRegion = convertTo(region: .current)
        let seconds = dateInRegion.region.timeZone.secondsFromGMT(for: self)
        return Date(timeInterval: TimeInterval(seconds), since: self)
    }
}
```
