### ISSUE TITLE
No cells displayed

### ISSUE THREAD

**Issue by Fatalution** [patchthecode/JTAppleCalendar#936]
I'm running 7.1.6. 

I followed through the tutorial video thoroughly. I've set all the constraints as it was shown in the first video. I've set the outlets (however there are 7 outlets instead of 2 in the video?! nevertheless I've set dataSource, delegate, ibCalendarDataSource and ibCalendarDelegate to Apple Calendar View)

WillDisplay function created (copypasted the code from cellForItemAt, I have no idea what else should I've done)

I get nothing still. Just grey box.

Any help?

<img width="371" alt="2018-11-21 6 16 47" src="https://user-images.githubusercontent.com/17583199/48822473-1b404500-ed55-11e8-8ab9-79ad94ed30a3.png">
<img width="1105" alt="2018-11-21 6 16 36" src="https://user-images.githubusercontent.com/17583199/48822475-1b404500-ed55-11e8-9c14-4300e27054da.png">
<img width="1107" alt="2018-11-21 6 16 21" src="https://user-images.githubusercontent.com/17583199/48822476-1b404500-ed55-11e8-93ba-f451c02f5d36.png">

**Comment by patchthecode** [comment]
zip your sample app and send it to me by dragging the file into this chat box

**Comment by clima94** [comment]
It seems that connecting the delegate and datasource in Storyboard does not currently work for this version of Xcode, so you need to do it programtically. Go into your viewDidLoad() and try use something like this:

calendarView.calendarDataSource = self
calendarView.calendarDelegate = self

Note that you need an outlet for your calendar. I recommend that the owner put this fix in his big warning page, as anyone that finds this calendar extension and follows his video tutorial would run into this problem.

**Comment by patchthecode** [comment]
closing this as it seems resolved.
