### ISSUE TITLE
ScrollDirection' is not a member type of 'UICollectionView

### ISSUE THREAD

**Issue by khush004** [patchthecode/JTAppleCalendar#937]
I had Downloaded this project but I won't be able to run it because I am getting following error.
**'ScrollDirection' is not a member type of 'UICollectionView'**

I am using Xcode version 9.2 

Please Help!
Thanks

**Comment by patchthecode** [comment]
What do you have in your pod file?

**Comment by khush004** [comment]
@patchthecode  I haven't any pod file

**Comment by khush004** [comment]
@patchthecode  I had try once using **pod 'JTAppleCalendar', '~> 7.0'** but still I am getting Error.

**Comment by patchthecode** [comment]
are you saying youre trying to use tis library without cocoapods?

**Comment by khush004** [comment]
@patchthecode  Thank you for Instant Replay, I am not using cocoapods I had just Downloaded this project I just only want to run this project and want to check that how it will work. after that I will Add this in to my project.

**Comment by khush004** [comment]
![screen shot 2018-11-24 at 9 23 50 am](https://user-images.githubusercontent.com/29862624/48964313-cf96d100-efca-11e8-912c-5d066e39337c.png)

Please check this I hope you Find where I am getting issue or Why I am getting Issue.

**Comment by patchthecode** [comment]
The version of the code you have downloaded is for swift 4.2 Xcode 10+
That is why you are getting that error.

**Comment by PujaGRathod** [comment]
May i know which version of JTAppleCalendar will support xcode 9.4.1  and swift 4.1?

**Comment by patchthecode** [comment]
i dont know about Xcode version, but i do know htat version 7.1.5 supports swift 4.1

**Comment by patchthecode** [comment]
closing this issue now. Let me know if that helped

**Comment by Tonigt** [comment]
> closing this issue now. Let me know if that helped

thanks
