### ISSUE TITLE
Cells doesn't resize on multitasking mode

### ISSUE THREAD

**Issue by sercanorhangazi** [patchthecode/JTAppleCalendar#938]
Hi, I tried to solve the solution but i couldn't. So, sorry if I'm opening an issue that already solved.
I'm just trying to resize the calendar cells when the app moved in between full screen and multitasking mode like in the image.
**Library Version: 7.1.6**
![Screenshot-cell-resize-problem](https://user-images.githubusercontent.com/32338956/48946375-96b11a80-ef3e-11e8-9cfc-7cc27aece915.png)

Thanks for the great Library!

**Comment by patchthecode** [comment]
closing this issue.
Let me know if it worked.

**Comment by sercanorhangazi** [comment]
> closing this issue.
> Let me know if it worked.

Worked perfectly. Thanks!

**Comment by patchthecode** [comment]
awrsome
