### ISSUE TITLE
Undeclared type `ViewType`

### ISSUE THREAD

**Issue by jon-choi** [patchthecode/JTAppleCalendar#94]
Just cloned the repo, and it doesn't compile. Is this a known issue?

![image](https://cloud.githubusercontent.com/assets/9872658/17272372/d76ac30e-5649-11e6-99f6-64927824779a.png)

**Comment by jon-choi** [comment]
FYI I'm on Xcode 7.2

**Comment by patchthecode** [comment]
I am not sure how you are experiencing this.

All you did was: 
1. **git clone https://github.com/patchthecode/JTAppleCalendar.git**
2. open the JTAppleCalendar.xcworkspace contained inside the **Example** folder
3. Change the project scheme to JTAppleCalendar-Example
4. Build it

And you say you're experiencing this?

**Comment by patchthecode** [comment]
I just did those steps above, and it worked.
Also, The build is passing in Travis.

Here is the code i just cloned and built.
[JTAppleCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/392093/JTAppleCalendar.zip)

**Comment by jon-choi** [comment]
Yes I tried the four steps as well as download the zip. You think it's related to the pods?

**Comment by patchthecode** [comment]
if youre online now, can you join me here?
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
This maybe be because youre using swift 2.1
Let me know once you update to 2.2.

If all is well, you can close this issue. If not, just let me know here.

**Comment by jon-choi** [comment]
This was resolved. Thanks @patchthecode

**Comment by patchthecode** [comment]
cool 👍
