### ISSUE TITLE
How to set events based on Weekdays 

### ISSUE THREAD

**Issue by ajinkya92** [patchthecode/JTAppleCalendar#940]
The latest version is currently 7.1.6

### How can I add events based on weekdays? My server sends me values such as 1,2,3,4,5,6,7 which corresponds to Mon, Tues, Wed, Thu... If the value is 1 then I want to show a green dot on all Mondays and so on.

**Comment by patchthecode** [comment]
just format the data into a format that the lib can read. This lib is a UICollectionView under the hood. Therefore it uses the DataSource/Delegate approach.

**Comment by ajinkya92** [comment]
Then there is one thing I can do, can you please guide me about how can assign values that I get into array to cellState. day.rawvalue and use conditions appropriately. Any hint?

**Comment by patchthecode** [comment]
There are a million ways to do this.
The question that you area asking is not library related. It is specific to you app.
I gave an example of how you can accomplish this in a youtube video. But i already see that you have watched the video.

Are you familiar with how UITableView or how UICollectionView works?

**Comment by ajinkya92** [comment]
Yes I am aware of how both these elements work but I am getting index out
of range error. Could you please help me out achieving it?

**Comment by patchthecode** [comment]
I am not sure how to explain it more.
I gave a clear example [here](https://www.youtube.com/watch?v=CQNotydm58s&index=6&list=PLpqJf39XekqyUG7dxcqGO0JNprryysv9Q)  Look at the video from 4mins-41secs.

In the example i showed you that the data from my server was in the format
```swift
array -> [Date:String]
```
And i showed you how i used that data from the server to create dot events on the screen.
The only difference between your data from the server and my data from the server, is that your data is `1, 2, 3, 4, 5, 6 & 7`

Therefore, I am not sure how else I can explain this clearly. The method is exactly the same as in the video.
