### ISSUE TITLE
Calendar Cells Not Showing Up

### ISSUE THREAD

**Issue by Aismit** [patchthecode/JTAppleCalendar#941]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

Hi!

I am currently using 7.1.6 and I have tried everything to get the day cells to show up but it still hasn't worked. Also for some reason I cannot assign calendarView.calendarDataSource = self
        calendarView.calendarDelegate = self as many posts have suggested. I get this error.  I look forward to hearing from you soon!
Also here are my corresponding pictures. 
<img width="1557" alt="screen shot 2018-11-23 at 7 35 16 pm" src="https://user-images.githubusercontent.com/24821844/48964215-82c5e280-ef57-11e8-822b-ffb1328d9624.png">
<img width="989" alt="screen shot 2018-11-23 at 7 36 49 pm" src="https://user-images.githubusercontent.com/24821844/48964216-82c5e280-ef57-11e8-9f1c-d15ce92d48e7.png">
<img width="984" alt="screen shot 2018-11-23 at 7 37 04 pm" src="https://user-images.githubusercontent.com/24821844/48964217-82c5e280-ef57-11e8-9e13-11f3f4c98c4f.png">
<img width="977" alt="screen shot 2018-11-23 at 7 37 14 pm" src="https://user-images.githubusercontent.com/24821844/48964218-82c5e280-ef57-11e8-85fe-266524c50e78.png">
<img width="464" alt="screen shot 2018-11-23 at 7 37 19 pm" src="https://user-images.githubusercontent.com/24821844/48964219-835e7900-ef57-11e8-99ce-887f5f03e64f.png">

**Comment by patchthecode** [comment]
This is not a library problem.
This is an error in your code.

Your classed is called `CalendarViewController`
but your extensions are called `ViewController`

closing this issue.
