### ISSUE TITLE
JTAppleCalendar on IOS 11

### ISSUE THREAD

**Issue by Arminor** [patchthecode/JTAppleCalendar#943]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hello, congrats for your pod here, it's really great. I want to work with your project so I can practice on app development but I have an issue, you see I'm working with Xcode 9.4.1, IOS 11, I installed the latest version of the pod, with is as you confirm up here the 7.1.6. and I cannot run the workspace because it returns me 9 errors on the JTAppleCalendarFramework. Hope you can help me. Thanks a lot!

<img width="271" alt="captura de pantalla 2018-11-28 a la s 10 43 48" src="https://user-images.githubusercontent.com/37130954/49167292-b491cd00-f2fa-11e8-9998-948df8796e2f.png">

**Comment by patchthecode** [comment]
try a lower version? 7.1.5?

**Comment by patchthecode** [comment]
closing this issue.
Assuming it is resolved since if just about getting the correct version to work with the cocoapod, and not about the library specifically.
