### ISSUE TITLE
How do I make a calendar start not with the start date but with today's date.

### ISSUE THREAD

**Issue by danielkiz** [patchthecode/JTAppleCalendar#944]
My question is can I make the calendar launch with today's date, but not the start date. Because I want it to work like the real iOS calendar. Because iOS calendar start's with today's date, but not the start date...Thank you!

**Comment by patchthecode** [comment]
in your `viewDidLoad()`, put 
```swift
calendarView.scrollToDate( Date() )
```

**Comment by omerbaskurt** [comment]
I'm having a problem with this too. Is there any way to start with today's date when the program launches without calling scrollToDate? It looks odd scrolling on launch.

**Comment by patchthecode** [comment]
just turn scroll animation off.
```swift
calendarView.scrollToDate(Date(), animateScroll: false)
```

**Comment by omerbaskurt** [comment]
My bad, thanks
