### ISSUE TITLE
My calendar content looks strange

### ISSUE THREAD

**Issue by danielkiz** [patchthecode/JTAppleCalendar#947]
When I run my calendar app the calendar view looks a bit strange. It starts with wrong dates. Here is a screenshot of it: https://ibb.co/qy837SP.

**Comment by danielkiz** [comment]
That's how I expect it to look: https://ibb.co/dtqnC3X

**Comment by patchthecode** [comment]
to make it start off with correct dates, just use the `scrollToDate` function in your `viewDidLoad`

**Comment by danielkiz** [comment]
@patchthecode I'm already using it. I mean take a look at the calendar. It shows that the 11th of December is related to this month, but 5...no

**Comment by patchthecode** [comment]
your calendar is scrolled one column to far.
What version of this library are you using?

**Comment by danielkiz** [comment]
@patchthecode, I've got a question, how do I check the version of the library? And I'm testing an app on iPhone SE.

**Comment by patchthecode** [comment]
its in your pod file.
What text did you put in there for this library?

**Comment by danielkiz** [comment]
"What text did you put in there for this library?" -what do You mean?

**Comment by danielkiz** [comment]
version of the library is "7.1.6"

**Comment by patchthecode** [comment]
ok. this should not be happening.
can you create an empty sample project which demonsrates this problem?
The zip the project and drag it into this chat box, will take a look

**Comment by danielkiz** [comment]
I can send you the project, but how do I do that? Maybe you know where can I save it and send you a link on it?

**Comment by patchthecode** [comment]
you can either create it on github, or drag the zip file into this chat box

**Comment by danielkiz** [comment]
K, here is the project:
[EDaybook.zip](https://github.com/patchthecode/JTAppleCalendar/files/2660690/EDaybook.zip)

**Comment by patchthecode** [comment]
i tried building this.
It could not build.
There are many dependency pods + I got a message saying it my profile isnt enabled for push notifications. Can you re-zip a simple project without any of the added stuff? Just JTAppleCalendar and the bug?

**Comment by patchthecode** [comment]
closing until user responds.
Attached the `awaiting-user-input` flag.

**Comment by danielkiz** [comment]
@patchthecode, I'm sorry for not replying, was extremely busy. Really apologize.

**Comment by danielkiz** [comment]
@patchthecode I can't send you another project, it prints some errors regarding firebase, because I'm using it in my project. Maybe I can send you what you need, files, code...?

**Comment by patchthecode** [comment]
I do not need your project.
What i need is a sample application (a blank sample app) which recreates this issue.
Your do not need to design the calendar on that app. Just recreate the error.

Since the error you are seeing is a visual one, sending me just relevant files will nor help. Because the error could be as simple as an error in the xib constraints. To something more difficult.
