### ISSUE TITLE
EXC_BAD_ACCESS Error

### ISSUE THREAD

**Issue by LePips** [patchthecode/JTAppleCalendar#95]
Whenever I build the sample app from the start up guide, I get the following error in the ViewController viewDidLoad() after it runs.

![screen shot 2016-07-30 at 7 46 39 pm](https://cloud.githubusercontent.com/assets/20747774/17274141/d52e05d4-568e-11e6-8adc-50f1abeed45a.png)

I made sure everything was just like the guide

Fix?

**Comment by patchthecode** [comment]
If youre available online now, can you join me here? Will be one for some minutes.
https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Closing this issue.
User forgot to set calendarView class to be of type `JTAppleCalendarView`
