### ISSUE TITLE
[CRASH]Calendar is Japanese

### ISSUE THREAD

**Issue by pandaApe** [patchthecode/JTAppleCalendar#950]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
7.1.6
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

I changed my device settings, Region-> Japan, Calendar->Japanese.
File: CalendarStructs.swift
Line: 250
```
struct JTAppleDateConfigGenerator {
            let numberOfMonths = differenceComponents.month! + 1
}
```
numberOfMonths is less than 0, so when it execute
 ```            
 for monthIndex in 0 ..< numberOfMonths {}
```
It throws an exception: ` Can't form Range with upperBound < lowerBound`

**Comment by patchthecode** [comment]
This is not crashing for me.
Can you give me some more information?

What simulator type are you running?
What is your startDate and endDate paramters for the calendar?
If possible please provide a sample app that demonstrates this.
Drag the zip file into this chat box.

**Comment by pandaApe** [comment]
Start Date is  Date(timeIntervalSince1970: 0),
```
 func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let parameters = ConfigurationParameters(startDate: Date(timeIntervalSince1970: 0),
                                                 endDate: Date(timeIntervalSinceNow: 3600*12*1000),
                                                 numberOfRows: 6,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .off,
                                                 hasStrictBoundaries: true)
        return parameters
    }
```

**Comment by patchthecode** [comment]
```
let x = Date(timeIntervalSince1970: 0)
print(formatter.string(from: x))   // Result = 0044 12 31
        
let y = Date(timeIntervalSinceNow: 3600*12*1000)
print(formatter.string(from: y)) // Result = 0032 05 31
```

Therefore your start date is greater than the end date. Therefore it crashes.
Please make your start date larger than your end date, and there will be no crash.

**Comment by pandaApe** [comment]
Oh, that's a bit interesting, thanks.
