### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by joules06** [patchthecode/JTAppleCalendar#951]
Hi.

I’m using version 7.1.5 at the moment.

What I want to create is a multiple selection calendar, save the selected dates and leave the selection marked with a color. And each time you want to make a new selection, use a different color to mark the selection.

To handle the selected dates, I’m using  this code

```swift
func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {

        handleConfiguration(cell: cell, cellState: cellState, hexColor: nil)
        
        if firstDate != nil {
            customCalendarView.selectDates(from: firstDate!, to: date,  triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
        } else {
            firstDate = date
        }
    }
```
But my problem is when I make a second selection on the calendar, because the original selected dates are appending to the new ones. 

What do you advise me to do?

Thanks.

**Comment by patchthecode** [comment]
I do not understand what you are asking.

> But my problem is when I make a second selection on the calendar, because the original selected dates are appending to the new ones.

What does this "appending" here mean?
Also, i see what the problem you stated is, but I do not know what you want to happen instead.

**Comment by patchthecode** [comment]
There is an example of multiple selection attached to the example project attached to this github project.
Have you taken a look at it?

**Comment by joules06** [comment]
Thanks for the help.

Here's an image the first time i select dates:
![image](https://user-images.githubusercontent.com/45794075/50289031-43db5d80-042d-11e9-8463-0d224d91333c.png)

When i clicked on "save", the dates are saved (from Dec 5 to 13).

But if i try to select a new range, it's adding the previous selecting dates to the new range, (in yellow color, i just selected the dates from dec 14 to 21).

![image](https://user-images.githubusercontent.com/45794075/50289178-ad5b6c00-042d-11e9-9b08-4cdd5f991140.png)

Yes, i have seen the example of multiple selection. But this works fine just for the first time i select the dates.

Can you give any ideas please?

Thanks again.

**Comment by patchthecode** [comment]
i get what the prblem is for you, but i do not know what you want to happen.
So you do not want it to add. I get that.
What do you **want** it do? What should the correct behavior be?

**Comment by joules06** [comment]
Hi again.

Something like this:
![image](https://user-images.githubusercontent.com/45794075/50296452-25329200-0440-11e9-964f-600436dc3ed4.png)

Thanks for your time.

**Comment by patchthecode** [comment]
closing issue.
If any further questions, then ask. Will try to answer as best i can.
