### ISSUE TITLE
reloadData(atAnchor:) not always works

### ISSUE THREAD

**Issue by AndreaMiotto** [patchthecode/JTAppleCalendar#952]
This is the issue:

every time I select a date I call reloadData(atAnchor:), and this makes the calendar scrolls to the correct page if I was selecting an out month date.

But this sometimes not works.

Example:
I'm display December, and I select 29 November from the out month date, the calendar reload and scroll to the correct November page.
I am in November and I choose 30 October from  the out month date. The calendar does not scroll.

I do not implement any kind of logic so I'm sure this is an issue from the library. Tell me if you need more info to investigate.

**Comment by patchthecode** [comment]
can i have a sample app demonstrating the problem?

**Comment by patchthecode** [comment]
closing issue until user responds.

**Comment by jcbriones** [comment]
Just want to reopen this ticket. I did experience a similar issue to this. I think when the date you selected is currently out of bounce from ConfigurationParameters for startDate and endDate. Then it does not work. I tried setting a new ConfigurationParameters to basically accept the new startDate and endDate but still doesn't work after reload.

**Comment by patchthecode** [comment]
> when the date you selected is currently out of bounce from ConfigurationParameters for startDate and endDate... it does not work

This is expected. You are reloading to n anchor date that does not exist within the bounds of the library.

> I tried setting a new ConfigurationParameters to basically accept the new startDate and endDate but still doesn't work after reload

This would be a bug. Can you let me know 
1. the date boundaries you are using?
2. what date you selected?
3. what did you expect to happen?
4. paste the code that was run?

**Comment by patchthecode** [comment]
closing this. I realized you opened a new issue
