### ISSUE TITLE
Layout Issue after reloading the calendar view and scrolling down by UIPanGestureRecognizer.

### ISSUE THREAD

**Issue by mock123** [patchthecode/JTAppleCalendar#954]
### 1. PLEASE STATE THE VERSION NUMBER you are using.
7.1.6

### 2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
YES

#### Precondition:
- There is an initial view controller, and a second view controller is presented as a modal.
- The second vc has a calendar view as one of the child views.
- UIPanGestureRecognizer is used on the second vc. That means, by scrolling down, a user can dismiss it.
- This problem only happens on the devices with no home button.
For example: 
iPhone X Series (iPhone X, iPhone XS, iPhone XSMax, iPhone XR), 
iPad Pro (11 inches), 
iPad Pro (12.9 inches, 3rd generation).

#### Problem:
There is a layout issue for the calendar view after doing the followings:

##### 1 Show the second vc
All life cycle events on vc (e.g. viewDidLoad) are finished at this point.

##### 2 Scroll down a little bit (this step is optional)
FYI: Unless scrolling down to certain point, the vc is still presented and back to top.

##### 3 Swipe it to the left or right
 It works fine at this point. 
![before_reloading](https://user-images.githubusercontent.com/36657040/50233384-acf3ae80-03f6-11e9-8867-a2017293c054.gif)

##### 4 Reload the calendar view (≒ called calendarView.reloadData() on main thread)

It works fine at this point, but I guess something is changed for the calendar view. (height?)

##### 5 When I scroll it down a little bit, it just got broken.

Here's the video after scrolling it up to the top. 
I was swiping the calendar view and able to move it in all directions.

![after_reloading](https://user-images.githubusercontent.com/36657040/50233130-17581f00-03f6-11e9-8f08-25bbf7e7bc48.gif)

**Comment by patchthecode** [comment]
closing issue until user responds.
