### ISSUE TITLE
selectDates - different dates other than the ones I want are being selected.

### ISSUE THREAD

**Issue by desmondbaldwin** [patchthecode/JTAppleCalendar#955]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using. - Swift 4
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6 - Yes
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hi, Thanks a lot for providing this library. It's been absolutely helpful.

My issue is with selecting dates programmatically. When the calendar is first loaded on the screen. The dates I want to see selected programmatically show up correctly on the screen. When I scroll to the next month. Dates I did not select are showing up as highlighted. When I scroll back to the original month. Dates other than the ones is selected show up as being selected. Please see pictures below.

1)The dates I want selected show up correctly. (The month and year below is December 2018, I did not put in the code for the month and year to show up when the program first loads as yet)
![image](https://user-images.githubusercontent.com/23667035/50249957-2367c080-03a5-11e9-8f23-e357c8b7de75.png)

2) I scroll to the next month and see dates that I did not select being highlighted (January 2019)
![image](https://user-images.githubusercontent.com/23667035/50249946-15b23b00-03a5-11e9-97d6-ed31bbabd05a.png)

3) When I scroll back to where is started. The dates that are supposed to be selected are not shown as being selected. The application highlights a different set of dates (Back to December 2018).
![image](https://user-images.githubusercontent.com/23667035/50250052-66c22f00-03a5-11e9-9a2d-e2fd4ab3a098.png)

**Comment by desmondbaldwin** [comment]
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let myCustomCell = cell as! CustomJTAppleCell
        myCustomCell.dateLabel.text = cellState.text

    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let myCustomCell = calendar.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath) as! CustomJTAppleCell
        myCustomCell.dateLabel.text = cellState.text
        return myCustomCell
    }

**Comment by patchthecode** [comment]
I am sorry.
i mentally responded.

I do not see where in your code you reset the displayed selected views.
In your selectDate function, i assume you have a code that looks like this

```swift
cell.selectedView.isHidded = false
```

But where have you set the `isHidden` to = `true`?
This library is exactly like a UICollectionView/UItableView, therefore you need to reset your cells in those 2 funcitons.

**Comment by patchthecode** [comment]
this should resolve the issue. 
closing this issue now.
Let me know if you have anyother problems.

**Comment by desmondbaldwin** [comment]
Ok so I'm a bit confused because I'm not sure where to perform the reset in my code.

I call selectDates on my calenderview from within viewDidLoad.


override func viewDidLoad() {
        super.viewDidLoad()   

        calenderView.allowsMultipleSelection  = true
        //calenderView.rangeSelectionWillBeUsed = true
        
        setUpCalendarView()
       
        print("activityIdentifier 1 - \(activityIdentifier)")
        //Query database for the dates to put on the calendar
        let activityHistoryBuilder = ActivityHistoryBuilder(carePlanStore: carePlanStore, activityIdentifier: activityIdentifier)
        activityHistoryBuilder.getDatesForCalender { (true, dates) in
            self.calenderView.selectDates(dates!)
        }
        
    }

**Comment by patchthecode** [comment]
you perform the reset in the exact same place as you would for a UITableView or UICollectionView.
Under the hood, this calendar is a UICollectionView.

You have worked with UITableView and UICollectionView before?
You should do the resetting of your cells in the `cellForItem` delegate function.

**Comment by desmondbaldwin** [comment]
Apologies, this is my first time using it so thank you for your patience. I was able to get it to work. Thanks again!

**Comment by patchthecode** [comment]
awesome. cool
