### ISSUE TITLE
Would you be able to provide a working sample for your video tutorial?

### ISSUE THREAD

**Issue by jumper4000** [patchthecode/JTAppleCalendar#959]
Would you be able to provide a working sample with the video tutorial? I followed this - https://www.youtube.com/watch?v=zOphH-h-qCs and applied your suggestions from issue #553, but when the app launches the calendar is blank, and it doesn't hit the code in the extension section. I think a working sample based on the latest instructions to go with that video will be very helpful. 

Thanks very much in advance.

**Comment by patchthecode** [comment]
If your calendar is blank, this means you didnt follow the video _fully_ and that there was some thing you missed.

If your calendar is blank, this could be some reason reason -> 
1. did you setup constraints for your calendar?
2. did you set your calendar delegate? and are the delegate functions being called?

There is already a working sample of the app attached to this github project. You can download and run it.

**Comment by jumper4000** [comment]
Hi, I got it working. The video says we should drag dataSource, and delegate outlets to ViewController, but apparently, we need to drag ibCalendarDataSource and ibCalendarDelegate instead. Once I did that, it worked. I'm attaching a very basic working calendar that follows your video tutorial to the T, which the exception of what I just mentioned, and the addition of willDisplay function. It'll be extremely helpful if you can add it to your video tutorial and save beginners like myself a ton of time :). Thanks for this great project though. It's awesome. 

[BasicCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2717617/BasicCalendar.zip)

**Comment by patchthecode** [comment]
thanks.
I think when i did the tutorial, the ibCalendarDataSource was not yet there.
While the library constantly gets updated, unfortunately a video cannot.

I should have said a note to developers, that updates are constantly being done, and that you should check the github for the latest content.

Glad you got the issue resolved. Closing this now 👍

**Comment by jusher** [comment]
jumper4000

Thanks.  I was able to get your code running, which will allow me to have something to go from, at least until some things are updated.

**Comment by patchthecode** [comment]
@jusher 
im in the process of making the text documentation.
See them here -> patchthecode.com

Im still updating them daily
