### ISSUE TITLE
Missing delegate call.

### ISSUE THREAD

**Issue by Bashta** [patchthecode/JTAppleCalendar#96]
Hi. You are missing a delegate call on this function.
```` Swift
public func scrollToDate(date: NSDate, triggerScrollToDateDelegate: Bool = true, animateScroll: Bool = true, preferredScrollPosition: UICollectionViewScrollPosition? = nil, completionHandler:(()->Void)? = nil)
````
On line 251 you are currently setting the 
```` Swift
 self.triggerScrollToDateDelegate = triggerScrollToDateDelegate
 ````

but the delegate is never actually called. This cause programmatically scrolling date not allowing UI update.
```` Swift
 func calendar(calendar: JTAppleCalendarView, didScrollToDateSegmentStartingWithdate startDate: NSDate, endingWithDate endDate: NSDate)
````
 I can throw a PR if that will make the fix faster.
Thanks for the awesome work done so far.

**Comment by patchthecode** [comment]
This is odd. It should be called.

Can you show me the one line of code you are using to scrollToDate?

**Comment by Bashta** [comment]
````Swift 
@IBAction func nextMonthButtonTapped(sender: UIButton) {
        calendarView?.scrollToNextSegment(true, animateScroll: true, completionHandler: nil)
    }

   func setupCalendar() {
        formatter.dateFormat = "yyyy MM dd"
        testCalendar.timeZone = NSTimeZone(abbreviation: "GMT")!
        
        calendarView?.delegate = self
        calendarView?.dataSource = self
        calendarView?.registerCellViewXib(fileName: "DateCalendarCell")
        
        calendarView?.direction = .Horizontal
        calendarView?.cellInset = CGPoint(x: 0, y: 0)
        calendarView?.allowsMultipleSelection = false
        calendarView?.bufferTop = 0
        calendarView?.bufferBottom = 0
        calendarView?.firstDayOfWeek = .Sunday
        calendarView?.scrollEnabled = true
        calendarView?.pagingEnabled = true
        calendarView?.itemSize = nil
        calendarView?.cellSnapsToEdge = true
        calendarView?.reloadData()
       
        let currentDate = calendarView?.currentCalendarDateSegment() ?? (startDate:NSDate(), endDate: NSDate())
        self.setupViewsOfCalendar(currentDate.startDate, endDate: currentDate.endDate)
    }
````

The scroll is animating when user scrolls manually or taps the button. The delegate is called when user scrolls manually but not when taps the button.

**Comment by patchthecode** [comment]
wow.. that bug was introduced in last  update.
Thanks for noting. I'll put in a patch.

**Comment by patchthecode** [comment]
Ok bug has been fixed. Just doing some testing.

**Comment by patchthecode** [comment]
Hey, I have pushed a fix to master branch. Are you able to test it?
If you are using cocoapods, you can test using [these instructions](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#8)

**Comment by patchthecode** [comment]
Btw, you can reduce your code to the following. Because in what you had previously, some are already the default.

```swift
        calendarView?.delegate = self
        calendarView?.dataSource = self
        calendarView?.registerCellViewXib(fileName: "DateCalendarCell")
        calendarView?.cellInset = CGPoint(x: 0, y: 0)
        calendarView?.reloadData()
```

**Comment by Bashta** [comment]
Its working fine now. Thanks for the quick fix. The reason the for the default properties being left on the setup method is that we can quickly tinker the calendar since the  app is still in rapid development. Te code will be cleaned up after we get a final design submit ;). Thanks again for the awesome job!

**Comment by patchthecode** [comment]
Thanks :) 

And since its working again, i'll release the official version this evening.
