### ISSUE TITLE
I get a crash when I deselected dates

### ISSUE THREAD

**Issue by behzadardehei** [patchthecode/JTAppleCalendar#961]
I am using the latest (7.1.6) version of the library.

I implemented calendar(_ calendar: JTAppleCalendarView, shouldDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool then when I deselect dates I get a crash.

```swift 
func calendar(_ calendar: JTAppleCalendarView, shouldDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
   let dates = calendar.selectedDates.filter { $0 != date }
   self.calendar.deselect(dates: dates)
   return true
}
```
![screen shot 2018-12-31 at 10 23 21 pm](https://user-images.githubusercontent.com/11045580/50566080-b5c77700-0d4a-11e9-91df-188c6d567a0d.png)
![screen shot 2018-12-31 at 10 22 43 pm](https://user-images.githubusercontent.com/11045580/50566081-b6600d80-0d4a-11e9-8be2-ebc94cd6e5f5.png)

**Comment by patchthecode** [comment]
It looks like you are getting is an infinite loop crash.

```swift
func calendar(_ calendar: JTAppleCalendarView, shouldDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) -> Bool {
   let dates = calendar.selectedDates.filter { $0 != date }
   self.calendar.deselect(dates: dates)
   return true
}
```

1. Should deselect Date?
   ->  self.calendar.deselect(dates: dates)
      -> Should deselect Dates?
         ->  self.calendar.deselect(dates: dates)
            -> Should deselect Dates?
               ->  self.calendar.deselect(dates: dates)
                 -> etc etc etc

**Comment by behzadardehei** [comment]
@patchthecode Could you please help me for fixing the issue?

**Comment by patchthecode** [comment]
...just dont make the function call it self? 🤔
Im not sure what you are trying to do, so i would not know how to help much.

**Comment by behzadardehei** [comment]
@patchthecode I want to remove all of them, if one of the selected dates was selected
Thanks for helping me

**Comment by patchthecode** [comment]
You know when a date is selected from the `didSelectDate` function.
I think you are implementing the logic in the wrong function.
