### ISSUE TITLE
No such module 'JTAppleCalendar'

### ISSUE THREAD

**Issue by lauradde** [patchthecode/JTAppleCalendar#962]
Using version 7.1.6.

I've installed the JTAppleCalendar cocoapod but whenever I try to import it (whether into view controller or CustomCell) XCode throws a 'no such module 'JTAppleCalendar'' error.

Have tried re-installing gems, cocoapods, XCode and JTAppleCalendar, but no joy...

![screen shot 2019-01-03 at 16 24 43](https://user-images.githubusercontent.com/29626824/50648906-5ba9fa00-0f74-11e9-9202-25a31d1067ef.png)

**Comment by patchthecode** [comment]
zip your sample project.
drag it into the chat box, let me have a look

**Comment by lauradde** [comment]
[MyCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2725531/MyCalendar.zip)

**Comment by patchthecode** [comment]
have you just tried building it?
I just unzipped your project, built it, and it worked out of the box 🤔

**Comment by patchthecode** [comment]
I am using swift 4.2
Xcode 10

What version ado you have?

**Comment by lauradde** [comment]
Have installed the Mojave update which seems to have fixed it - thanks!

**Comment by patchthecode** [comment]
awesome!

**Comment by lauradde** [comment]
Apologies, me again - the build does succeed now but the UI doesn't display; instead XCode throws a signal SIGABRT error as shown in the screenshot. 

Have checked the outlets and they all seem to be fine so not sure why this is? 

Have zipped the project.

[FinalTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/2738228/FinalTest.zip)

![screenshot 2019-01-08 at 19 50 19](https://user-images.githubusercontent.com/29626824/50855065-b9788080-137e-11e9-82c7-97101b4bc3dd.png)

**Comment by patchthecode** [comment]
what is the error that is displayed in the log screen?

**Comment by lauradde** [comment]
Sorry, is this what you mean? 2019-01-09 17:37:12.436109+0000 FinalTest[5483:440894] Unknown class JTAppleCalendarView in Interface Builder file.
2019-01-09 17:37:12.447091+0000 FinalTest[5483:440894] -[FinalTest.ViewController collectionView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x7f830d40ead0
2019-01-09 17:37:12.469903+0000 FinalTest[5483:440894] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FinalTest.ViewController collectionView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x7f830d40ead0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111b371bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000110651735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111b55f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00000001165d1b4a -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x0000000111b3bed6 ___forwarding___ + 1446
	5   CoreFoundation                      0x0000000111b3dda8 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x0000000115e30c7b -[UICollectionViewData _updateItemCounts] + 423
	7   UIKitCore                           0x0000000115e335f2 -[UICollectionViewData numberOfSections] + 22
	8   UIKitCore                           0x0000000115e3eca7 -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 542
	9   UIKitCore                           0x0000000115e40fc4 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 231
	10  UIKitCore                           0x0000000115e399d9 -[UICollectionViewFlowLayout prepareLayout] + 246
	11  UIKitCore                           0x0000000115e30f85 -[UICollectionViewData _prepareToLoadData] + 231
	12  UIKitCore                           0x0000000115e319fb -[UICollectionViewData validateLayoutInRect:] + 53
	13  UIKitCore                           0x0000000115e0000e -[UICollectionView layoutSubviews] + 260
	14  UIKitCore                           0x0000000116a8d795 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1441
	15  QuartzCore                          0x0000000118015b19 -[CALayer layoutSublayers] + 175
	16  QuartzCore                          0x000000011801a9d3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
	17  QuartzCore                          0x0000000117f937ca _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 342
	18  QuartzCore                          0x0000000117fca97e _ZN2CA11Transaction6commitEv + 576
	19  UIKitCore                           0x00000001165be2d0 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 139
	20  CoreFoundation                      0x0000000111a9c62c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	21  CoreFoundation                      0x0000000111a9bde0 __CFRunLoopDoBlocks + 336
	22  CoreFoundation                      0x0000000111a96654 __CFRunLoopRun + 1284
	23  CoreFoundation                      0x0000000111a95e11 CFRunLoopRunSpecific + 625
	24  GraphicsServices                    0x000000011a1aa1dd GSEventRunModal + 62
	25  UIKitCore                           0x00000001165a381d UIApplicationMain + 140
	26  FinalTest                           0x000000010fc128a7 main + 71
	27  libdyld.dylib                       0x0000000113ccc575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by patchthecode** [comment]
Sorry i missed this.
The error message tells you exactly what is wrong.

```
Unknown class JTAppleCalendarView in Interface Builder file
```

**Comment by patchthecode** [comment]
again, provide a zip file so that i can see what is going on.

**Comment by lauradde** [comment]
Hey
[FinalTest.zip](https://github.com/patchthecode/JTAppleCalendar/files/2770369/FinalTest.zip)
 thanks for the reply - yeah, I can't work out why it's not recognising the class. The zip file is above but re-pasting here for ease

**Comment by patchthecode** [comment]
your module is missing
<img width="724" alt="screen shot 2019-01-17 at 12 03 20 pm" src="https://user-images.githubusercontent.com/2439146/51345483-fbc15200-1a4f-11e9-9dae-65064771d317.png">

**Comment by patchthecode** [comment]
This should resolve your issue.
Closing this now.
Let me know if any other help is needed.

**Comment by lauradde** [comment]
Great, thank you!!
