### ISSUE TITLE
A willScroll function of a JTAppleCalendarViewDelegate is not called.

### ISSUE THREAD

**Issue by Nikaaner** [patchthecode/JTAppleCalendar#963]
Hey. I use the latest version 7.1.6. 
I implemented a `func calendar(_ calendar: JTAppleCalendarView, willScrollToDateSegmentWith visibleDates: DateSegmentInfo)` function of a `JTAppleCalendarViewDelegate` but it is not called.

**Comment by patchthecode** [comment]
do you have an empty sample application that demonstrates this issue?
Mine is getting called.
If you can zip your sample project, just drag the zip file in to this chat box.

**Comment by Nikaaner** [comment]
@patchthecode Here you are, sorry for the delay
[CalendarBugs.zip](https://github.com/patchthecode/JTAppleCalendar/files/2733547/CalendarBugs.zip)

**Comment by patchthecode** [comment]
Sorry for the long delay as well. Got caught up with other stuffs.
The function is getting called.

Im using XCode 10.0
Swift 4.2

Are you using the same thing?

**Comment by patchthecode** [comment]
I have sample project attached to this github project you can take a look at. It gets called in there as well as in your demo app.

**Comment by patchthecode** [comment]
closing issue until user responds.
Added awaiting user input flag.

**Comment by Nikaaner** [comment]
Hey, I understood the problem! 
It is not called if I switch a month by pressing a button and using `scrollToSegment(:)` function.
