### ISSUE TITLE
RTL direction only chosen for semanticContentAttribute == .forceRightToLeft, not .unspecified

### ISSUE THREAD

**Issue by germs5** [patchthecode/JTAppleCalendar#965]
Version 7.1.6. Run the app in the Simulator with the schema Application Language set to Hebrew. Set up header views as in https://www.youtube.com/watch?v=CQNotydm58s. The header views will display right-to-left, but the calendar will not, even though both have their semanticContentAttribute set to .unspecified.

A workaround is in the viewController's viewDidLoad:
`if view.effectiveUserInterfaceLayoutDirection == .rightToLeft {
            calendarView.semanticContentAttribute = .forceRightToLeft
}`

But better would be to change JTAppleCalendarView.swift:199 to be something like:
`transform.a = semanticContentAttribute == .forceRightToLeft || (superview.effectiveUserInterfaceLayoutDirection == .rightToLeft && semanticContentAttribute == .unspecified) ? -1 : 1`

**Comment by patchthecode** [comment]
submit a pull request and i can merge.
if you cant, then i will fix.

**Comment by germs5** [comment]
I tried. Too complicated with IOS 9.

**Comment by patchthecode** [comment]
I am about to add this code.
one question 

```swift
transform.a = semanticContentAttribute == .forceRightToLeft || (superview.effectiveUserInterfaceLayoutDirection == .rightToLeft && semanticContentAttribute == .unspecified) ? -1 : 1
```
This part is not required right?
```swift
&& semanticContentAttribute == .unspecified
```

**Comment by patchthecode** [comment]
Pushed to master branch. closing issue

**Comment by germs5** [comment]
That part is required, because the problem occurs when the user says the calendar should follow whatever the system language direction is. That is, when the calendar semanticContentAttribute is .unspecified

**Comment by patchthecode** [comment]
ok. thanks. fixing this. now.
