### ISSUE TITLE
Select/deselect dates

### ISSUE THREAD

**Issue by jumper4000** [patchthecode/JTAppleCalendar#969]
In regards to this issue, https://github.com/patchthecode/JTAppleCalendar/issues/966, I setup my array of dates and the button works fine, but now the button acts as a toggle. So basically, cells that are already selected get deselected and vice versa. Is there any way to force all dates in the array to get selected, whether they're already selected or not? And is there a way to Deselect those dates based on an array (again whether they're already deselected or not)? 

BTW, I have multipleSelection enabled and I need it that way.

Thanks so much for all the help on this. It's truly appreciated.

**Comment by jumper4000** [comment]
I figured out the select part, but the deselect part still acts like a toggle. Anyway, I can force the deselect to always deselect everything whether cells are selected or not, instead of toggling them? This is my code so far -

var select: Bool = true
    @IBAction func TuesdayButton(_ sender: Any) {
        if select {
            calendarView.selectDates(selectDayOfAllWeeks(weekDay: .Tue), triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)
            select = false
        } else {
            calendarView.deselect(dates: selectDayOfAllWeeks(weekDay: .Tue))
            select = true
        }
    }

**Comment by patchthecode** [comment]
will this work?
```swift
func deselectAllDates(triggerSelectionDelegate: Bool = true) {
   deselect(dates: selectedDates, triggerSelectionDelegate: triggerSelectionDelegate)
}
```

**Comment by jumper4000** [comment]
No, unfortunately, that won't work. I only need to deselect the cells that are in an array without toggling the ones that are already deselected or deselecting the cells that are not in the array. I basically need the deselect version of this - `calendarView.selectDates([arrayOfDates], triggerSelectionDelegate: false, keepSelectionIfMultiSelectionAllowed: true)` is there anything like that?

**Comment by patchthecode** [comment]
I am guess youre looking specifically for this `keepSelectionIfMultiSelectionAllowed`.
Currently that doesnt exist though. Youre the first person to ask :)

I'll have to code that.

**Comment by patchthecode** [comment]
I guess you'll have to actually keep track of the dates you want to deselect (if possible for now).
Let me look into a code solution from my side.

**Comment by patchthecode** [comment]
updated on master branch.
Test master branch by following the [instructions here](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#how-do-i-test-my-project-with-your-latest-code-to-see-if-a-bug-is-fixed-there).
Closing issue.

Let me know if you find bug.
