### ISSUE TITLE
Localize calendar date cells?

### ISSUE THREAD

**Issue by cluelessoodles** [patchthecode/JTAppleCalendar#970]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6

Using 7.1.6

3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.

I have localized my app to several non-latin languages and everything works except the dates in the calendar which remain in English. Is there a built-in way to localize the collectionview calendar cell dates? Year and month are localizing just fine, but for some reason, the cell dates are not.

Here's what I have in the method that sets up the cell:

```swift
func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarCell", for: indexPath) as! CalendarCell
        cell.dateLabel.text = cellState.text
        configureCalendarCell(cell:cell, cellState: cellState)
        return cell
}
```

**Comment by patchthecode** [comment]
Can you paste the code of your `configureCalendar` function?

**Comment by cluelessoodles** [comment]
Yes, it is:

    //Mark: Configure Calendar Cell
    func configureCalendarCell(cell: JTAppleCell?, cellState: CellState) {
        guard let myCustomCell = cell as? CalendarCell else { return }
            handleCellTextColor(cell: myCustomCell, cellState: cellState)
            handleCellVisibility(cell: myCustomCell, cellState: cellState)
            handleCellSelected(cell: myCustomCell, cellState: cellState)
            getEventDates(cell: myCustomCell, cellState: cellState)
    }
    
    //Mark: Calendar set cell selection colors, today's Date selection
    func handleCellTextColor(cell: CalendarCell, cellState: CellState) {
        cell.dateLabel.textColor = cellState.isSelected ? UIColor.primaryOrange : UIColor.white
        
        formatter.dateFormat = "yyyy MM dd"
        let todaysDateString = formatter.string(from: todaysDate)
        let monthDateString = formatter.string(from: cellState.date)
        if todaysDateString == monthDateString {
            cell.dateLabel.layer.cornerRadius = 25
            cell.dateLabel.clipsToBounds = true
            cell.dateLabel.backgroundColor = cellState.isSelected ? UIColor.clear : #colorLiteral(red: 1, green: 1, blue: 1, alpha: 0.5)
        } else {
        }
    }
    
    //Mark: Calendar hide outside Month dates
    func handleCellVisibility(cell: CalendarCell, cellState: CellState) {
        cell.isHidden = cellState.dateBelongsTo == .thisMonth ? false : true
    }
    
    //Mark: Calendar cell selection
    func handleCellSelected(cell: CalendarCell, cellState: CellState) {
        cell.selectedView.isHidden = cellState.isSelected ? false : true
    }

**Comment by patchthecode** [comment]
I meant the code for the `configureCalendar` function
```swift
func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters
```

**Comment by patchthecode** [comment]
take a look at the `configureCalendar` function in my  sample app attached to this github project.

```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        formatter.dateFormat = "yyyy MM dd"
        formatter.timeZone = testCalendar.timeZone
        formatter.locale = testCalendar.locale
        
        
        let startDate = formatter.date(from: "2018 01 01")!
        let endDate = formatter.date(from: "2019 02 01")!
        
        let parameters = ConfigurationParameters(startDate: startDate,
                                                 endDate: endDate,
                                                 numberOfRows: numberOfRows,
                                                 calendar: testCalendar,
                                                 generateInDates: generateInDates,
                                                 generateOutDates: generateOutDates,
                                                 firstDayOfWeek: firstDayOfWeek,
                                                 hasStrictBoundaries: hasStrictBoundaries)
        return parameters
    }
```

You can see that i return a `ConfigurationParameters` object.
There is a parameter of that object called `calendar`.

This is a `Calendar()` object.
You create a calendar object, configure that calendar object to what ever geo/locale/etc. 
Then pass that calendar object to the library just like i did.

**Comment by cluelessoodles** [comment]
Oh I see. I do have something similar but it's not working. I went through the sample project code to see if you used testCalendar to set up the dates anywhere but I'm not seeing anything other than where you use dateComponent to get the month is the dateLabel.text is 1. In addition to the above methods, these are my relevant methods - can you spot anything that might prevent localization to a non latin language?

    var myCalendar = Calendar.current

   let monthFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.timeZone = Calendar.current.timeZone
        formatter.locale = Calendar.current.locale
        formatter.dateFormat = "MMMM"
        return formatter
    }()

       let formatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.timeZone = Calendar.current.timeZone
        dateFormatter.locale = Calendar.current.locale
        dateFormatter.dateFormat = "yyyy MM dd"
        return dateFormatter } ()

    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let startDate = formatter.date(from: "2019 01 01")!
        let endDate = formatter.date(from: "2020 01 31")!
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate, numberOfRows: numOfRowsInCalendar, calendar: Calendar.current)
        return parameters
    }
}

func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarCell", for: indexPath) as! CalendarCell
        configureCalendarCell(cell:cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
        let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CalendarCell", for: indexPath) as! CalendarCell
        cell.dateLabel.text = cellState.text
        configureCalendarCell(cell:cell, cellState: cellState)
        return cell
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        configureCalendarCell(cell: cell, cellState: cellState)
        cell?.bounce()
        selectedDate = date
        
        let datesFromCalendarXML = allEventsInVisibleMonth.map {$0.eventdate}
        let selectedDateToString = formatter.string(from: selectedDate!)
        if let index = datesFromCalendarXML.index(of: selectedDateToString) {
            let indexPath = IndexPath(row: 0 , section: index)
            self.tableView.scrollToRow(at: indexPath, at: UITableView.ScrollPosition.top, animated: true)
        }
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
        configureCalendarCell(cell: cell, cellState: cellState)
    }
    
    func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        setupViewsOfCalendar(dateSegment: visibleDates)
        selectFirstDateOnMonthScroll(onVisibleDates: visibleDates)
        
        //Mark: adjust tableview Y to calendarview numOfRows of 5 or 6. Then animate
        adjustCalendarViewHeight()
        UIView.animate(withDuration: 0.5) { [unowned self] in
            self.view.layoutIfNeeded()
        }
    }
    
    func scrollDidEndDecelerating(for calendar: JTAppleCalendarView) {
        let visibleDates = calendarView.visibleDates()
        let dateWeShouldNotCross = formatter.date(from: "2020 01 05")!
        let dateToScrollBackTo = formatter.date(from: "2019 12 29")!
        if visibleDates.monthDates.contains (where: {$0.date >= dateWeShouldNotCross}) { calendarView.scrollToDate(dateToScrollBackTo)
            return
        }
    }
}

**Comment by patchthecode** [comment]
in the sample project, its in the `TestPersianCalendar.swift` file.

here i configure a persian calendar.
```swift
    func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
        
        let persianCalendar = Calendar(identifier: .persian)
        
        let testFotmatter = DateFormatter()
        testFotmatter.dateFormat = "yyyy/MM/dd"
        testFotmatter.timeZone = persianCalendar.timeZone
        testFotmatter.locale = persianCalendar.locale
        
        let startDate = testFotmatter.date(from: "2017/01/01")!
        let endDate = testFotmatter.date(from: "2017/09/30")!
        
        
        let parameters = ConfigurationParameters(startDate: startDate, endDate: endDate, calendar: persianCalendar)
        return parameters
    }
```

I left the language in english so that it will be easier to debug for me.
```swift
    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        // The code here is the same as cellForItem function
        let cell = cell as! CellView
        cell.dayLabel.text = cellState.text
        ...
        ...
    }
```

**Comment by patchthecode** [comment]
Paste me one last thing.
Paste me the code for the function where you set the text to the cell.

I want to see what code you used there which you think should change the language.

**Comment by patchthecode** [comment]
The most i can do is show you an example of how to change the calendar in persian.

```swift
        let date = Date()
        let df = DateFormatter()
        df.locale = Locale(identifier: "fa_IR")
        df.calendar = persianCalendar
        df.dateFormat = "dd"
        print(df.string(from: date))
```

I guess you can apply the same for hindi.

**Comment by patchthecode** [comment]
closing this issue.
assumed resolved.
