### ISSUE TITLE
Week Calendar selectItem(at: indexpath) is not called

### ISSUE THREAD

**Issue by 973labs** [patchthecode/JTAppleCalendar#971]
JTAppleCalendar v7.1.6

Hello @patchthecode , thanks for this wonderful library. I don't think this is an issue but didn't know where else to ask sorry.

I have made a weekly calendar that scrolls to and selects the current date on starting the app which is fine. My problem is that when i scroll to the next/previous week, the date is not selected. 

Im trying something like this: 

```
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
       guard let firstVisibleDate = visibleDates.monthDates.first?.date else { return }
       weeklyCollectionView.reloadData(withanchor: firstVisibleDate) {
            self.weeklyCollectionView.scrollToDate(firstVisibleDate, triggerScrollToDateDelegate: false, animateScroll: true)       
        }
        guard let selectedDate = visibleDates.monthDates.first?.indexPath.item else {return}
        self.weeklyCollectionView.selectItem(at: [selectedDate], animated: false, scrollPosition: [])
    }
```
i did use `selectDates` and it works by doing:
`
self.weeklyCollectionView.selectDates([visibleDate])`

but what this does is it selects the first date in the week and what i want is the selection to be the same as where it was previously selected.

Any help appreciated. Thanks.

**Comment by patchthecode** [comment]
> I have made a weekly calendar that scrolls to and selects the current date on starting the app which is fine. My problem is that when i scroll to the next/previous week, the date is not selected.

`the date is not selected` --> What date is not selected?

Can you describe what you want accomplished?
Because i do not understand this
> what i want is the selection to be the same as where it was previously selected.

**Comment by 973labs** [comment]
if i select mon/tues/wed/etc., then after i scroll to the next week sun is selected.

![jan-12-2019 13-37-02](https://user-images.githubusercontent.com/42637597/51071743-069e7000-1667-11e9-8c96-ae723fa12a90.gif)

i want -> if i select mon then after scrolling it should select the next mon, or if tue is selected, then it should select next tues ...

right now the code is: 

```
func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
        guard let firstVisibleDate = visibleDates.monthDates.first?.date else { return }

        if firstVisibleDate.weekday == startDate?.weekday || firstVisibleDate.weekday == endDate?.weekday {
            setStartAndEndDates(for: firstVisibleDate)
            calendarView.reloadData(withanchor: firstVisibleDate) {
                
                if firstVisibleDate =~ Date.today.startOfWeek {
                    self.calendarView.selectDates([Date.today])
                } else {
                    self.calendarView.selectDates([firstVisibleDate])
                }
            }
        }
    }
```

**Comment by patchthecode** [comment]
sorry for the long reply.
What you can do is this --->

in your `didSelectDate` function, you can save the selected column of the cell.
```swift
let selectedColumn = cellState.column()
```

Now that you have the column saved.
In your `didScrollToDateSegmentWith` function put this
```
let cellState = calendarView.cellStatusForDate(at: 0, column: selectedColumn)
calendarView.selectDate(cellState.date)
```

**Comment by patchthecode** [comment]
let me know if this worked
