### ISSUE TITLE
[Bug + Fix] Issues in layout for JTAppleCalendar v7.1.6 - iOS 12 + Xcode 10

### ISSUE THREAD

**Issue by AlexPinhasovSelina** [patchthecode/JTAppleCalendar#972]
JTAppleCalendar v7.1.6

Hello 👋 
There is an issue with the library specifically on **iOS 12** compiled with **Xcode 10+** (compiling with Xcode 9 will NOT produce the issue)
**Running the app in Xcode 10 + iOS 11 also won't reproduce the issue.**

Steps to reproduce:
1) Run application on Xcode 10 and use iOS 12 simulator/device.
2) present the calendar
3) at first everything looks fine, but after scrolling a few month the layout produce a warning (in Debug view hierarchy ) stating "position is ambiguous for view" and everything breaks.

![ezgif-5-c63f6b0085d6](https://user-images.githubusercontent.com/46086995/50972874-53ac0600-14f0-11e9-8a09-cab28bc32ec1.gif)

I did found a fix for the issue:
What need to change is 
**class JTAppleCalendarLayout: UICollectionViewLayout, JTAppleCalendarLayoutProtocol {**
**class JTAppleCalendarLayout: UICollectionViewFlowLayout {**
UICollectionViewLayout -> UICollectionView**Flow**Layout

![screen shot 2019-01-10 at 11 38 43](https://user-images.githubusercontent.com/46086995/50972963-7dfdc380-14f0-11e9-8346-efcdeca559f8.png)

**Comment by AlexPinhasovSelina** [comment]
Hi patchthecode,
I hope you're right and it is specific to my app, yet I have tested many configuration and layouts and all the same result.
I don't have a sample app to provide currently, i'l try detaching the calendar to a new project and send you the .zip ASAP.
For the mean time leave this issue open for any future developers who in-counter this issue.
A question for you:
Why wouldn't you use UICollectionViewFlowLayout? the class extends the base UICollectionViewLayout class and added all the properties you need.

**Comment by patchthecode** [comment]
> Why wouldn't you use UICollectionViewFlowLayout? the class extends the base UICollectionViewLayout class and added all the properties you need.

Because that layout does not have all the properties I need.
It does not work for both horizontal and vertical and allows for all of the flexibility you see me do in the sample project attached to github.

The fact that i see your dates becoming jumbled tells me that you may be altering some code.
I just need to see a sample project to confirm, because what you are experiencing is not detected by any of our tests.

**Comment by patchthecode** [comment]
closing issue until user responds
added awaiting user input flag
