### ISSUE TITLE
Adding border on dates

### ISSUE THREAD

**Issue by bbo-jay** [patchthecode/JTAppleCalendar#973]
I'm trying to add borders on dates but excluding the dates on previous and next month. 

like this:
![screen shot 2019-01-14 at 11 30 46 am](https://user-images.githubusercontent.com/36146249/51095459-de8e4880-17ef-11e9-9678-a1602ac23098.png)

I have tried to use:
cell.layer.borderWidth = 1
cell.layer.borderColor = UIColor.gray

but the problem is some cells have thicker borders on the side because of their next cell which has a border.

**Comment by patchthecode** [comment]
```
cell.layer.borderWidth = 1
cell.layer.borderColor = UIColor.gray
``` 

is the correct way to do it.

You have showed me an image of what you want.
Can you also show me an image of what you have?

**Comment by bbo-jay** [comment]
![screen shot 2019-01-18 at 12 28 45 pm](https://user-images.githubusercontent.com/36146249/51366225-668d8e80-1b1f-11e9-9b53-bac86d76bfd2.png)

As you can see, the borders that are inside the red lines have a 2px of border and some outside the red lines has a 1px only which is what I want in all cells.

**Comment by bbo-jay** [comment]
So the previous and next months dates will also have a border right?

**Comment by patchthecode** [comment]
It will not have a border, because i just told you to remove the cell border code.

**Comment by bbo-jay** [comment]
I'll try this next week and update you if ever.
