### ISSUE TITLE
How to set a weekly based using 2 columns each days

### ISSUE THREAD

**Issue by delmarz** [patchthecode/JTAppleCalendar#974]
Hi,
I didn't find any sample for a weekly based Monday to Sunday using 2 columns each days.

Here's what I want to achieve. 

<img width="375" alt="screen shot 2019-01-14 at 3 19 22 pm" src="https://user-images.githubusercontent.com/7381514/51103297-1e1f5980-181d-11e9-8165-651dfa7d5580.png">

Any feedback?

Thanks,

**Comment by patchthecode** [comment]
i do not understand what i am looking at.
There are many Monday 31st ?

**Comment by delmarz** [comment]
@patchthecode sorry for the mockup up design. It should be Jan 1 to Jan 7 from Monday to Sunday.
And only Monday to Friday is clickable.

<img width="375" alt="screen shot 2019-01-14 at 3 19 22 pm" src="https://user-images.githubusercontent.com/7381514/51124263-d61e2800-1858-11e9-9eda-e00001d07b06.png">

Is there a way to achieve using the 2 colums?

Thanks,

**Comment by patchthecode** [comment]
ok i see.
unfortunately, the layout i have coded works with traditional Calendar layouts.
That is 7 columns and 6 rows.

I have made it flexible so that we can have adjustable row calendar.
example 1, 2, 3, 4, 5, 6 row calendars.

But I have not made it so that the columns are flexible.
Sorry about that.
Unless someone codes this for me.

**Comment by delmarz** [comment]
Ok I understand can you still open this issue until someone dev look on this? This is great to have an abillity for customizing also the column either 2, 3, 4 or it could be 5 to display i.e displaying Monday to Friday only.

Hopefully this will availalble in future updates. 

Thanks,

**Comment by patchthecode** [comment]
will close this issue.
Added to future projects

**Comment by serban-sz** [comment]
Hello, I also need to use a calendar showing only Monday - Friday days per week. 
Is it possible to do this with the latest JTAppleCalendar version ? 

Thanks, in advance.
