### ISSUE TITLE
Unable to select same date twice for range selection

### ISSUE THREAD

**Issue by divinebaibhav** [patchthecode/JTAppleCalendar#976]
Hello,

i have one condition where there is two dates checkIn and CheckOut. 
From calendar user can select these two dates.
For different date user is able select range eg. from 18 sep to 28 sep.
But in case user select same date twice means same date for checkIn checkout, Calendar is not selecting dates twice.
"**calender.selectedDates**" become 0 when i select date twice.

thanks

**Comment by patchthecode** [comment]
Have you checked out the range selection example project attached to this github project?

**Comment by divinebaibhav** [comment]
it deselects the selected date ..when i try to select it again

**Comment by patchthecode** [comment]
Yes, what i have there is an example you can use to follow.
Just change the code to what ever you need it to be.
Wasnt the example clear?

**Comment by patchthecode** [comment]
I guess what i am trying to say is this:

> But in case user select same date twice means same date for checkIn checkout, Calendar is not selecting dates twice.

I do not understand what you mean by this. You want a date to be selected twice?

**Comment by divinebaibhav** [comment]
it means if select same date 2 times it should with two different colors

**Comment by patchthecode** [comment]
Basically, with multi select enabled, you want a cell to be selected twice?
This library is a UICollectionView under the hood. Therefore you need to solve it the same way you would for a UICollectionView.

Does a UICOllectionView allow you to select the same cell twice when `multiSelect` is enabled?
I do not think so.

**Comment by patchthecode** [comment]
closing issue.
