### ISSUE TITLE
morethan 6 rows

### ISSUE THREAD

**Issue by beajco** [patchthecode/JTAppleCalendar#977]
latest version

It is possible to have more than 6 rows? because i am developing at iPad

![screen shot 2019-01-18 at 4 25 09 pm](https://user-images.githubusercontent.com/38550296/51374330-ab282280-1b3d-11e9-9d68-990901455931.png)

**Comment by patchthecode** [comment]
How would more than 6 rows look?

**Comment by beajco** [comment]
Like this sir..

![screen shot 2019-01-23 at 11 58 48 am](https://user-images.githubusercontent.com/38550296/51582347-9e714900-1f06-11e9-8e89-3ab92b8ceb54.png)

**Comment by patchthecode** [comment]
so.. basically you want a vertical scrolling calendar?
if so, then just set the calendar to vertical.

**Comment by beajco** [comment]
I already did that, and the output is the screenshot on the top sir.

**Comment by patchthecode** [comment]
can you past the code of your `configureCalendar()` function?

**Comment by beajco** [comment]
Here it is sir. 

![screen shot 2019-01-24 at 9 06 39 am](https://user-images.githubusercontent.com/38550296/51647391-8efe0880-1fb7-11e9-94ff-cc4cfeffdc1f.png)

**Comment by patchthecode** [comment]
In that case, you must have code to hide the cell in this function
```swift
calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath)
```

Because your cells should be visible.

What code do you have in that funciton?

**Comment by patchthecode** [comment]
Or better, 
can you provide a sample zipped project which demonstrates this error?

**Comment by patchthecode** [comment]
closing issue under user responds.
