### ISSUE TITLE
Cannot get dot image to display

### ISSUE THREAD

**Issue by MelissaW990** [patchthecode/JTAppleCalendar#978]
Hiya, 

I am using version 7.1.6 to add a calendar for the app I am creating for my university dissertation. I have fiddled about with adding the dot image to my custom cell for well over an hour now, with constraints, without constraints and I simply cannot get it to show. I was wondering if you could help me? I have a feeling it is something very simple! 

I have attached the project if you want to have a look, there is a 'calendar' view controller in the storyboard and the corresponding Calendar class is under the 'Registered' controller folder.

I appreciate you're a busy guy so thanks for the help in advance!
[MIND.xcodeproj.zip](https://github.com/patchthecode/JTAppleCalendar/files/2773757/MIND.xcodeproj.zip)

**Comment by patchthecode** [comment]
you zipped the wrong thing.
You only zipped the xcproj file. You should zip the entire folder.
Just remember to delete the` build` folder before zipping (if it exists)

**Comment by MelissaW990** [comment]
Sorry about that, the correct folder should be attached below.
[MIND.zip](https://github.com/patchthecode/JTAppleCalendar/files/2774036/MIND.zip)

**Comment by patchthecode** [comment]
project cannot be built.
<img width="865" alt="screen shot 2019-01-18 at 10 49 04 am" src="https://user-images.githubusercontent.com/2439146/51406709-bc0d6f80-1b0e-11e9-922c-65eb2e020071.png">

**Comment by patchthecode** [comment]
It will be better if you just do an empty project demonstrating the error you are seeing.
That way there will be no dependencies.

**Comment by MelissaW990** [comment]
Ok I have attached it here, it is not an error, I just simply cannot get the red dot image to show at all. Even in this basic example, do I need to call it somewhere else in the ViewController file? Sorry this sounds so stupid!

[JTCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2774323/JTCalendar.zip)

**Comment by patchthecode** [comment]
1. set constraints to the  image
2. set an image to the imageView. Although it looked like a red dot on interfaceBuilder, the image field was blank in the inspector.

**Comment by patchthecode** [comment]
[JTCalendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2775164/JTCalendar.zip)

**Comment by MelissaW990** [comment]
Sorted,I wasn't setting the constraint to the cell properly in my own project. Thank you for your help!
