### ISSUE TITLE
Which values can be added from a server

### ISSUE THREAD

**Issue by coty10** [patchthecode/JTAppleCalendar#979]
Hello,
I am retrieving the events to display on my calendar from a public google calendar.
I followed your tutorial and I am to the point where i create the array [String:String] with the date and the tile.
My question is:
Is it possibile to display also other information?
e.g. in my google calendar i have a location and a description. Is possibile to show this data too or it will be limited to a date and a title?

Thank you!

**Comment by patchthecode** [comment]
You can do anything you want with that calendar.
What i showed was only an example.
But you can code literally anything you want.
