### ISSUE TITLE
how can I change month scroll mode so I can change to page flip I am using the latest version

### ISSUE THREAD

**Issue by babakmuir** [patchthecode/JTAppleCalendar#980]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
I have no idea what you are asking :/

**Comment by babakmuir** [comment]
I need to change month like page flipping in iBook but every tutorial I read ays that I need a UIViewController
how can I specify month change and convert every month segment

**Comment by patchthecode** [comment]
Hmm. 
I would not be able to answer your question.
I am not good at animation. If your question was more directly related to the library then maybe i can help more.

But that said, what about just googling "animating a UICollectionViewCell to flip animation" or something like that. Might help.

**Comment by babakmuir** [comment]
actually I tried UIPageViewController and it worked but I need to separate months as a viewControllers

**Comment by patchthecode** [comment]
understood. but this question is more about animation and not directly related to the library.
I have no clue about anything animation 😅

But i do know that this library is a UICollectionView and that what you are asking for is very possible.
Will close this issue.
