### ISSUE TITLE
Views not showing in assigned spot of cell

### ISSUE THREAD

**Issue by gmhcode** [patchthecode/JTAppleCalendar#981]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INFORMATION SO I CAN RECREATE THE PROBLEM.

the screen shots say it all. Im just testing UIViews("dots") for an event indicator. 

When i run the app, the the dots dont show up in the places i assigned.

no constraints on the dots, the version im building on and running on are the same. I have tried all sorts of constraints, including attaching a dot to a dot that was centered in the cell with a stack view and that didnt even work. 

heres a github link (its the calendar you build in one of your tutorials)
https://github.com/gmhcode/Calendar-Example

![screen shot 2019-01-19 at 5 59 31 pm 2](https://user-images.githubusercontent.com/45080589/51433958-7044ee00-1c14-11e9-9006-cd179dcfe588.png)
![screen shot 2019-01-19 at 6 00 28 pm 2](https://user-images.githubusercontent.com/45080589/51433959-7044ee00-1c14-11e9-9e8e-2a2459854d40.png)

**Comment by patchthecode** [comment]
for your cell to work properly.
Everything in the cell needs constraits.
The dot also needs constraints

**Comment by patchthecode** [comment]
closing issue.
every view on the cell needs constraints to display properly.
