### ISSUE TITLE
hi how do I add events using local json

### ISSUE THREAD

**Issue by babakmuir** [patchthecode/JTAppleCalendar#983]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by babakmuir** [comment]
I have events for all of dates for 5 years as below
{
      "holiday": false,
      "year": 1395,
      "month": 10,
      "day": 29,
      "type": "Iran",
      "title": "روز غزه"
    }
how do i distribute them in my calendar

**Comment by patchthecode** [comment]
there is an example video about using creating events.
Have you taken a look at it?

**Comment by patchthecode** [comment]
closing this issue.
Example was provided on the video link https://www.youtube.com/watch?v=CQNotydm58s
