### ISSUE TITLE
please can someone help me, calendarView skipping part redundancy of month?

### ISSUE THREAD

**Issue by vfa-gianglt-hcm** [patchthecode/JTAppleCalendar#984]
latest version 7.1.6
I setting in JTAppleCalendar Example->JTAppleCalendar iOS Example->Example Calendars->ViewController.swift
1. numberOfRows = 5
2. generateInDates = .forAllMonths
3. generateOutDates = .tillEndOfRow
 4. let startDate = formatter.date(from: "2019 01 01")!
     let endDate = formatter.date(from: "2030 01 01")!

Error happen when I next to the month September have 29 days ??, please more details my screen Shot  below.
I want to remove screen number 2, please help me thanks.

![simulator screen shot - iphone xr - 2019-01-26 at 11 40 45](https://user-images.githubusercontent.com/33415783/51782859-60706100-2162-11e9-878a-e9d021fed755.png)

![simulator screen shot - iphone xr - 2019-01-26 at 11 40 57](https://user-images.githubusercontent.com/33415783/51782860-66664200-2162-11e9-81d8-2c45df6bfcf0.png)

![simulator screen shot - iphone xr - 2019-01-26 at 11 41 03](https://user-images.githubusercontent.com/33415783/51782861-6a925f80-2162-11e9-9e35-2666f0b45bba.png)

**Comment by patchthecode** [comment]
put the rows = 6.
not 5

**Comment by vfa-gianglt-hcm** [comment]
> put the rows = 6.
> not 5
> 
> You have set the number of row = 5.
> Therefore you are seeing 5 rows.

thank you for replying so quickly, this issue is resolved, I closed this ticket.
Thanks.
