### ISSUE TITLE
willDisplay added but still get blank screen

### ISSUE THREAD

**Issue by englishlc2002** [patchthecode/JTAppleCalendar#985]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:
Dear paththecode
Using the latest 7.1.6
did exactly the same thing as told by the first video and found error related to that 'willDisplay' thing, tried to fix this by adding the following code:

    func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
        let cell = cell as! CustomCell
        cell.dateLabel.text = cellState.text
    }

still didn't work, blank screen shows up after launching the app
Have been stuck by this for 2 days now and will go mad soon :(
[X-Calendar.zip](https://github.com/patchthecode/JTAppleCalendar/files/2798752/X-Calendar.zip)

**Comment by patchthecode** [comment]
black screen? your app crashes on launch with error
```swift
Unknown class JTAppleCalendarView in Interface Builder file.
```

**Comment by patchthecode** [comment]
because your module is missing
<img width="265" alt="screen shot 2019-01-26 at 8 02 13 am" src="https://user-images.githubusercontent.com/2439146/51789708-b9c79880-2140-11e9-9761-be9a3025a378.png">

**Comment by englishlc2002** [comment]
Thank you, this helps a lot!
