### ISSUE TITLE
When scrolling data is lost

### ISSUE THREAD

**Issue by Silea** [patchthecode/JTAppleCalendar#986]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hello. I don't know what to do now. When scrolling data is lost.
P.S. I speak English badly.

I use last version. (7.1)
The video shows what's not working.
[https://radikal.ru/video/lA5GwuCbJF8](https://radikal.ru/video/lA5GwuCbJF8)

```swift
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {`

        let cellDay = cell as! CellDay

        cellDay.select = cellState.isSelected
        cellDay.fill(cellState)
        cellDay.period(.defaults)
        
        if let cycle = presenter?.getCycles(date: cellState.dateSection().range.end) {
            self.cycle = cycle
        }
        
        if let mRange = cycle?.menstruation?.range, let oRange = cycle?.ovulation?.range {
            switch date {
            case mRange:
                cellDay.period(.menstruation)
            case oRange:
                cellDay.period(.ovulation)
            default: break
            }
        }
    }


func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {`

        if let cell = calendar.visibleCells.first, let indexPath = calendarView.indexPath(for: cell) {

            let cellDay = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CellDay", for: indexPath) as! CellDay
            self.calendar(calendar, willDisplay: cellDay, forItemAt: date, cellState: cellState, indexPath: indexPath)
            print("DATE \(date)")
            
            return cellDay
        } else {
            let cellDay = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "CellDay", for: indexPath) as! CellDay
            self.calendar(calendar, willDisplay: cellDay, forItemAt: date, cellState: cellState, indexPath: indexPath)
            print("DATE2 \(date)")
            return cellDay
        }
    }
```

I really hope for your help. Thanks.

**Comment by patchthecode** [comment]
video link not working.

**Comment by patchthecode** [comment]
Do you have a sample app with demonstrates this problem?
You can zip it and drop it in this message box.

Im sure the error that you are seeing is not related to the library.

**Comment by Silea** [comment]
[MyDay.zip](https://github.com/patchthecode/JTAppleCalendar/files/2799833/MyDay.zip)

You need to install pods.

> Im sure the error that you are seeing is not related to the library.

I hope that's the case.

**Comment by Silea** [comment]
> Do you have a sample app with demonstrates this problem?
> You can zip it and drop it in this message box.
> 
> Im sure the error that you are seeing is not related to the library.

**Comment by patchthecode** [comment]
1. I was not able to recreate the problem. When i scrolled, the data did not change.
Is there any specific thing I have to do to recreate the problem?

2. You are doing too processing for every cell. This causes your calendar to lag if a user taps the screen, and scrolls up and down quickly.

**Comment by Silea** [comment]
It seems to be no specific things. I just choose different dates so that they do not match. Maybe you are right and the case is in the processing in the cell. I will try further. Thanks for the help.

**Comment by patchthecode** [comment]
ok.

if you have specific steps which can recreate the problem, then let me know.
If i can recreate it, then i can help.

**Comment by Silea** [comment]
Good evening. There was my mistake, the calendar works correctly.
