### ISSUE TITLE
UIcollectionview showing only 6 columns

### ISSUE THREAD

**Issue by englishlc2002** [patchthecode/JTAppleCalendar#987]
Just started to learn coding by myself, apologies for all the silly questions.

I'm using 7.1.6 and my calendar only shows 6 columns on the screen, when I scroll the screen horizontally I can see the 7th column on the next screen, tried to play with the settings of the UICollectionview, but just can't figure out why this is happening.

Thanks.

**Comment by patchthecode** [comment]
1. does your calendar have proper constraints? - this may be the problem
2. did you get a chance to look at the tutorial vids? - this may help

**Comment by englishlc2002** [comment]
@patchthecode you are absolutely right about the constraints, removed all constraints and reset them all and it worked, thanks again!

**Comment by patchthecode** [comment]
awesome. closing this issue
