### ISSUE TITLE
Problem with sectionInset in the week view

### ISSUE THREAD

**Issue by codeagencypl** [patchthecode/JTAppleCalendar#988]
I use the latest version of the library 7.1.6, problem relates to poor component layout using sectionInset. 

```
calendar.minimumLineSpacing = 0
calendar.minimumInteritemSpacing = 0
calendar.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)

let parameters = ConfigurationParameters(startDate: Date(year: 2018, month: 1, day: 24),
                                                 endDate: Date(year: 2020, month: 1, day: 1),
                                                 numberOfRows: 1,
                                                 calendar: Calendar.autoupdatingCurrent,
                                                 generateInDates: .forAllMonths,
                                                 generateOutDates: .tillEndOfGrid,
                                                 firstDayOfWeek: .monday)
```
The problem is indicated on the screenshots below.

![img_0867](https://user-images.githubusercontent.com/12941320/51808602-3750ed00-2296-11e9-93d7-63ef914c45c0.jpg) 
![img_0869](https://user-images.githubusercontent.com/12941320/51808603-3b7d0a80-2296-11e9-8165-f315bc3265bc.jpg)

**Comment by patchthecode** [comment]
I cannot tell what the error is by looking at the picture.
You need to tell me what is wrong, else I will not know.

**Comment by codeagencypl** [comment]
I would like to configure the contentInset parameter for the calendar view, i.e. padding on the left and right side. From what I managed to find out, the sectionInset parameter is responsible for it. For the weekly view, the first week looks good, but each week is set in the wrong way, as I pointed out in the second screenshot.

**Comment by patchthecode** [comment]
I guess i do not understand what is wrong about it.
What is wrong with the 2nd screen shot?

If you download the sample application attached to this github, then run it and tap on `calendar layout demonstration`

1. Tap the button with the text `1`
2. tap the button `horizontal`
3. tap `resize` 3 times
4. tap button `all`
5. tap button `EOG` 
6. tap `+sInset` twice

then scroll.  This is what the section inset does.
Is this not what you want?

**Comment by codeagencypl** [comment]
Look at this screenshot
https://share.icloud.com/photos/0KfKrdo02xW0vtDKpyZHKdbSA

**Comment by patchthecode** [comment]
if youre online msg me here -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by codeagencypl** [comment]
There is no parameter in the calendar configuration
`hasStrictBoundaries: true`
