### ISSUE TITLE
Example for programmatically added JTAppleCalendar

### ISSUE THREAD

**Issue by 1ckola** [patchthecode/JTAppleCalendar#989]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hi,

Like to know is there any example adding calendar control programmatically ?

**Comment by patchthecode** [comment]
closing this issue
