### ISSUE TITLE
Scroll based on each months, not segments

### ISSUE THREAD

**Issue by mrjimoy** [patchthecode/JTAppleCalendar#99]
Hi, how do I make the scrolling based on each months, not segments?

![image](https://cloud.githubusercontent.com/assets/6197219/17359598/8a2b0176-5991-11e6-82aa-3fc0d867762c.png)

From the image above, the May 2017 is getting cut since it's on iPhone 5S, but on iPhone 6 it's working fine. I adjust the itemSize so it can fit iPhone 6, and it scroll on every 2 months. I would like it to scroll on 1 month. Is it possible? Thanks.

**Comment by patchthecode** [comment]
hmm. Yea, I didnt make the code scroll to page.
I'll have to work on that.

In the mean time though, Range selection has been added to master branch.
`CellState` now has a property called `selectedPosition`. By simply checking this value, you can put what ever type of selection you want.

**Comment by patchthecode** [comment]
I'll go check your paging thing now.

**Comment by mrjimoy** [comment]
Hi @patchthecode , wow thanks.. I tried to update the pod to 4.1.4 (latest version) but didn't get any `selectedPosition`. Can you please confirm? Thanks.

**Comment by patchthecode** [comment]
Ah, i havent releast it yet.
To test it, just follow the instruction [on this link on question #8] (https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#8)

**Comment by mrjimoy** [comment]
Okay, I will test it and let you know :)

**Comment by patchthecode** [comment]
if youre online, you can join me here btw -> https://gitter.im/patchthecode/JTAppleCalendar

**Comment by patchthecode** [comment]
Feature complete. Now testing it.

**Comment by patchthecode** [comment]
Pushed to master branch. Can you test with [these instructions](https://github.com/patchthecode/JTAppleCalendar/wiki/Common-Questions#8)?

**Comment by mrjimoy** [comment]
Thank you, @patchthecode. I updated the pod, and is there any additional code I need to append? I tried and still the same..

**Comment by patchthecode** [comment]
join me on chat. I can discuss.
