### ISSUE TITLE
Calendar single tap

### ISSUE THREAD

**Issue by dimaP8889** [patchthecode/JTAppleCalendar#990]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

Hi, i am using 7.0 version

I've got a questions, is there any way to detect single tap on Calendar? i am tried to addTapGestureRecognizer, but it stoped to select cells

Thanks

**Comment by patchthecode** [comment]
have you looked at the `didSelectDate` delegate function?

**Comment by dimaP8889** [comment]
yes, but its not good for me. i have an extra view in top of the calendar view with buttons to select some dates in calendar. I want to hide this view when i tap on Calendar.

Thanks for your answer

**Comment by patchthecode** [comment]
I do not know your code setup.
What i can tell you is this.
This library is a UICollectionView. And every date cell is a UICollectionViewCell.
You need to solve this problem the exact same way as you would for a UICollectionView.

**Comment by patchthecode** [comment]
cool closing this issue
