### ISSUE TITLE
How to update New min and max dates based on requirement 

### ISSUE THREAD

**Issue by PodalakurPrasanth** [patchthecode/JTAppleCalendar#991]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
can you please be more descriptive?

**Comment by patchthecode** [comment]
closing issue until user responds.
