### ISSUE TITLE
JTCalendar returning Segmentation Fault / Bus Error

### ISSUE THREAD

**Issue by tprasad23** [patchthecode/JTAppleCalendar#992]
Receiving this when trying to build:

<img width="264" alt="screen shot 2019-02-03 at 9 39 13 pm" src="https://user-images.githubusercontent.com/2342724/52187572-4686ec00-27fc-11e9-8080-cf2db397be96.png">

Another screenshot of error:

<img width="695" alt="screen shot 2019-02-03 at 9 42 07 pm" src="https://user-images.githubusercontent.com/2342724/52187648-a7162900-27fc-11e9-9d0f-dfa15996b399.png">

**Comment by patchthecode** [comment]
res
