### ISSUE TITLE
how to select a column dates, like vertical selection

### ISSUE THREAD

**Issue by NagamaniSeken** [patchthecode/JTAppleCalendar#993]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
`calendarView.selectDates(arrayOfDatesToSelect)`

Closing this issue.
