### ISSUE TITLE
can't change background image

### ISSUE THREAD

**Issue by babakmuir** [patchthecode/JTAppleCalendar#994]
IMPORTANT - BEFORE CREATING YOUR ISSUE PLEASE READ THE FOLLOWING:

1. PLEASE STATE THE VERSION NUMBER you are using.
2. Are you using the latest version of JTAppleCalendar? Latest version is currently 7.1.6
3. PROVIDE ENOUGH INPORMATION SO I CAN RECREATE THE PROBLEM.

**Comment by patchthecode** [comment]
JTApplecalendar is a uicollectionview under the hood, so every thing should work the same.

i do not understand.
Is this image on a cell?

**Comment by patchthecode** [comment]
closing issue.
