### ISSUE TITLE
ScrollToHeader function stops working when scroll to the same position twice with animation 

### ISSUE THREAD

**Issue by GHMarcus** [patchthecode/JTAppleCalendar#995]
This issue is reproducible with any calendar: 
1. Call method `scrollToHeaderForDate(date, withAnimation: true)` 
2. Call method `scrollToHeaderForDate(date, withAnimation: true)`  again with the same date
3. Now the method won't work anymore

You can reproduce the issue with the attached project. Here you must tap `Jump To January` - Button twice wich breaks the buttons.

We are using Version 7.1.6

[Reproduce-JTCalendarView-Issue.zip](https://github.com/patchthecode/JTAppleCalendar/files/2841539/Reproduce-JTCalendarView-Issue.zip)

**Comment by patchthecode** [comment]
good catch.
Yes please do, and i'll merge it

**Comment by patchthecode** [comment]
closing issue as patch was merged to master.
