### ISSUE TITLE
Date cell text is flipped in Arabic langauge

### ISSUE THREAD

**Issue by jvv-ab** [patchthecode/JTAppleCalendar#996]
The calendar cells shows dates flipped when I use Arabic. I have RTL enabled. I am using 7.1.6 version.
Please see the attached screenshot.

![mirrored-text](https://user-images.githubusercontent.com/46313996/52474194-c7a7ff80-2bbd-11e9-869c-250627143db9.png)

```
startDate = self.delegate.formatDate(date: "01 01 1998", dateFormat: self.delegate.dateFormat5)
endDate = self.delegate.formatDate(date: "31 12 2020", dateFormat: self.delegate.dateFormat5)
```
I tried setting date formatter with and without locale option.
```
func calendar(_ calendar: JTAppleCalendarView, willDisplay cell: JTAppleCell, forItemAt date: Date, cellState: CellState, indexPath: IndexPath) {
    let dateCell = cell as! DateCell
    dateCell.dateLabel.text = cellState.text
}

func configureCalendar(_ calendar: JTAppleCalendarView) -> ConfigurationParameters {
    return ConfigurationParameters(startDate: startDate!, endDate: endDate!)
}

func calendar(_ calendar: JTAppleCalendarView, cellForItemAt date: Date, cellState: CellState, indexPath: IndexPath) -> JTAppleCell {
    let cell = calendar.dequeueReusableJTAppleCell(withReuseIdentifier: "dateCell", for: indexPath) as! DateCell
    cell.dateLabel.text = cellState.text
    // ..
    return cell
}

func calendar(_ calendar: JTAppleCalendarView, didSelectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
    guard let dateCell = cell as? DateCell else { return }
    // ..
}

func calendar(_ calendar: JTAppleCalendarView, didDeselectDate date: Date, cell: JTAppleCell?, cellState: CellState) {
    guard let dateCell = cell as? DateCell else { return }
    // ..
}

func calendar(_ calendar: JTAppleCalendarView, didScrollToDateSegmentWith visibleDates: DateSegmentInfo) {
    // ..
}
```

I try to change the `cell.dateLabel.transform = CGAffineTransform(scaleX: -1, y: 1)`, but the cell exhibits random behavior when I switch the language from Arabic to English and back to Arabic. Sometimes, the dates are mirrored only when I swipe, other times, it shows mirrored and then when I swipe, it shows properly. Sometimes, it shows as flipped all the time.

**Comment by patchthecode** [comment]
hmm.. maybe i do not understand.
But if your language is Arabic, i dont think you have to flip anything yourself.
Have you tried this?
```swift
calendarView.semanticContentAttribute = .forceLeftToRight
```
?

**Comment by jvv-ab** [comment]
That fixes the issue. Thank you.

**Comment by ahmediosDeveloper** [comment]
i have the same issue , it happens only when you force language to be arabic when use some pods
like MOLH.
if i use apple localization system it moves from right to left as expected with flipping
if you force language in the app it moves from right to left but it flips numbers like the imag
i hope if you can look in this issue please .

**Comment by ahmediosDeveloper** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-05-18 at 06 45 13](https://user-images.githubusercontent.com/18172069/82172607-559b8b80-98d3-11ea-8ab4-d3cbad10e33c.png)

**Comment by hayax** [comment]
Have you fixed the issue?
